### ISSUE TITLE
Does mlc-llm support nv gpu using CUDA instead Vulkan

### ISSUE THREAD

**Issue by zhaoyang-star** [mlc-ai/mlc-llm#101]
I notice that mlc-llm has supported nv gpu by Vulkan. Does mlc-llm support nv gpu using CUDA instead Vulkan? I guess nv prefers CUDA than Vulkan so CUDA will be faster than Vulkan?

**Comment by yzh119** [comment]
Of course MLC-LLM supports CUDA, the reason we release Vulkan versions is it's general and supported by more backends to NV GPUs. You can compile the CUDA version manually by running
```bash
python build.py --model MODEL_NAME --target cuda ...
```

**Comment by zhaoyang-star** [comment]
> MLC-LLM supports CUDA, the reason we release Vu

Thanks, I will have a try.

**Comment by yzh119** [comment]
btw, you need to compile and install the [relax](https://github.com/mlc-ai/relax) project before running this `build.py` script.

**Comment by lucasjinreal** [comment]
@yzh119 does cuda got a faster speed to vulkan after both tuned?

**Comment by liyizhe3975** [comment]
奇怪的是，我的笔记本电脑没有安装Vulkan驱动，而是安装的CUDA驱动。运行MLC Chat也没有问题。
是不是我哪里操作不对？会不会是我在运行MLC Chat时没有跑在显卡上而是跑在CPU上？
Strangely, my laptop does not have the Vulkan driver installed, but CUDA driver installed. 
There is also no problem running MLC Chat. 
Is there something wrong with me? Could it be that I am not running on the NV GPU but on the CPU when I run MLC Chat?

**Comment by tqchen** [comment]
most recent gpu drivers usually automatically comes with vulkan support

**Comment by junrushao** [comment]
We haven't particularly focused a lot on CUDA optimization yet, as `torch.compile()` should already work for huggingface models out of the box. Happy to bring in more optimization later

**Comment by zhaoyang-star** [comment]
> cuda got a faster speed to vulkan after both tuned?

Thanks a lot. I have got the `vicuna-v1-7b_cuda_float16.so`. But error happened when building `mlc-llm-cli`. Could you please have a look? @yzh119  Detail infor can be found in #119

**Comment by yzh119** [comment]
Close it as the discussion continues in #119 .
