### ISSUE TITLE
[Question] Not able to compile on Linux without CUDA and without VULKAN.

### ISSUE THREAD

**Issue by sankalpdayal** [mlc-ai/mlc-llm#1015]
## ❓ General Questions

I am trying to compile a model on linux with CPU only - no GPU and no Vulcan. I want to compile purely for CPU. I am following instructions "Build from Source" from here https://llm.mlc.ai/docs/install/tvm.html#id6. Even after setting VULKAN to Off, after compilation in the .so file I am still getting USE_VULKAN: ON.

**Comment by sankalpdayal** [comment]
Steps I followed are
`
conda create -n tvm-build-venv -c conda-forge \
    "llvmdev>=15" \
    "cmake>=3.24" \
    git

conda activate tvm-build-venv
git clone --recursive git@github.com:mlc-ai/relax.git tvm-unity && cd tvm-unity
rm -rf build && mkdir build && cd build
cp ../cmake/config.cmake .
echo "set(CMAKE_BUILD_TYPE RelWithDebInfo)" >> config.cmake
echo "set(USE_LLVM \"llvm-config --ignore-libllvm --link-static\")" >> config.cmake
echo "set(HIDE_PRIVATE_SYMBOLS ON)" >> config.cmake
echo "set(USE_VULKAN OFF)" >> config.cmake
cmake .. && cmake --build . --parallel $(nproc)
`
The build was successful. The ran
`
export PYTHONPATH=/path-to-tvm-unity/python:$PYTHONPATH

python3 -c "import tvm; print(tvm.__file__)"
/mypath/.local/lib/python3.10/site-packages/tvm/__init__.py

python3 -c "import tvm; print(tvm._ffi.base._LIB)"
<CDLL 'mypath/.local/lib/python3.10/site-packages/tvm/libtvm.so', handle 55d6c93c7a00 at 0x7f72e69e4a30>

python3 -c "import tvm; print('\n'.join(f'{k}: {v}' for k, v in tvm.support.libinfo().items()))"
...
USE_VULKAN: ON
...
` 
I am also attaching my configuration file (extentions changed to .txt). 
[config.cmake.txt](https://github.com/mlc-ai/mlc-llm/files/12806893/config.cmake.txt)

**Comment by junrushao** [comment]
While TVM supports CPU natively, MLC LLM doesn’t officially have this functionality yet.

**Comment by sankalpdayal** [comment]
Do you know when and how we will get there?

**Comment by sankalpdayal** [comment]
@junrushao
