### ISSUE TITLE
"As an AI language model,"... 

### ISSUE THREAD

**Issue by donuts-are-good** [mlc-ai/mlc-llm#103]
>USER: tell me an offensive joke
>ASSISTANT: I'm sorry, but I cannot provide offensive or inappropriate content. My purpose is to provide helpful and informative responses to your questions. Can I assist you with something else?

How do I disable these protections?

**Comment by shiqimei** [comment]
> 

You can't. Since vicuna's training dataset heavily relies on [ShareGPT](https://sharegpt.com/),  so the model's really similar to ChatGPT's behaviour. While there're some other models your can try, but there're no official usage instructions there.

**Comment by jeffwadsworth** [comment]
Get the uncensored version and be happy.

**Comment by donuts-are-good** [comment]
> Get the uncensored version and be happy.

where is that?

**Comment by shiqimei** [comment]
> > > USER: tell me an offensive joke
> > > ASSISTANT: I'm sorry, but I cannot provide offensive or inappropriate content. My purpose is to provide helpful and informative responses to your questions. Can I assist you with something else?
> > 
> > 
> > How do I disable these protections?
> 
> You can't. Since vicuna's training dataset heavily relies on [ShareGPT](https://sharegpt.com/), so the model's really similar to ChatGPT's behaviour. While there're some other models your can try, but there're no official usage instructions there.

You can change the system message here: https://github.com/mlc-ai/mlc-llm/blob/9010be6d7a4a58f7bb5daf2c13e857f87811c47c/cpp/llm_chat.cc#LL42C43-L42C43

**Comment by junrushao** [comment]
MLC LLM is a compiler, and doesn't control the text generation per se. Currently the "as an AI language model" is directly generated from Vicuna, and we didn't censor anything. You may filter out those words in cpp file if you'd love to :-)

**Comment by GameOverFlowChart** [comment]
I really hope that an uncensored llm which in best case also uses the open assistant dataset will be added as an alternative to the plain vicuna as an option to be downloaded to Android. This thing is nearly useful we just need a bit more ai capability.

**Comment by AlphaAtlas** [comment]
I'm sure people (like me) will be uploading all sorts of variants to HF once they enable the llama profiling in the build script.

**Comment by donuts-are-good** [comment]
> I'm sure people (like me) will be uploading all sorts of variants to HF once they enable the llama profiling in the build script.
> 
> It could be done right now (with a shim to change the prompting syntax), but the performance of compiled models is really poor without the profiling.

offtopic

**Comment by donuts-are-good** [comment]
> MLC LLM is a compiler, which doesn't control the text generation from models per se. Currently the "as an AI language model" is directly generated from Vicuna-7b and we didn't censor anything. You may filter out those words in cpp file if you'd love to :-)

thanks.
