### ISSUE TITLE
[Question] Quantization outside MLC-LLM

### ISSUE THREAD

**Issue by sankalpdayal** [mlc-ai/mlc-llm#1030]
## ❓ General Questions

I have a quantization method that is similar to Smooth Quant but with some custom changes to the algorithm for Llama2. I already have the scale factors for weight and activations. What is the best way I can bypass the quantization and directly write the scale values to parameters and activations. I checked out the PR for smooth quant but I think in there the calibration is being done inside the quantization function. 

Any guidance would super helpful.

Thanks.

**Comment by tqchen** [comment]
This is something we are working on to bring support. @junrushao @LeshengJin

**Comment by MasterJH5574** [comment]
we opened a tracking issue in https://github.com/mlc-ai/mlc-llm/issues/1157
