### ISSUE TITLE
[Feature Request] will it support Tensorrt?

### ISSUE THREAD

**Issue by yongjer** [mlc-ai/mlc-llm#1031]
## 🚀 Feature
Tensorrt support

## Motivation

accelerate the inference with Nvidia Gpu

**Comment by junrushao** [comment]
I think if TensorRT could meaningfully accelerate some subgraph, integrating it is not a problem in terms of engineering effort, but so far, according to the data we have, it doesn't yet. Definitely good to keep this option open in the long run
