### ISSUE TITLE
[Bug] InternalError: Check failed: (__e == VK_SUCCESS) is false: Vulkan Error, code=-2: VK_ERROR_OUT_OF_DEVICE_MEMORY

### ISSUE THREAD

**Issue by yongjer** [mlc-ai/mlc-llm#1034]
## To Reproduce
![mlc](https://github.com/mlc-ai/mlc-llm/assets/54315206/6176d145-9a13-4fad-a319-40273bb68a3b)
![image](https://github.com/mlc-ai/mlc-llm/assets/54315206/5dad35d6-4916-498b-84d9-cd0554ac9e66)

## Environment

 - Platform (e.g. WebGPU/Vulkan/IOS/Android/CUDA):vulkan
 - Operating system (e.g. Ubuntu/Windows/MacOS/...):ubuntu 20.04
 - Device (e.g. iPhone 12 Pro, PC+RTX 3090, ...):RTX2060 6G
 - How you installed MLC-LLM (`conda`, source):conda MLC-Chat-CLI
 - How you installed TVM-Unity (`pip`, source):not yet
 - Python version (e.g. 3.10):3.12
 - GPU driver version (if applicable):NVIDIA-SMI 535.104.12, Driver Version: 535.104.12
 - CUDA/cuDNN version (if applicable):CUDA Version: 12.2
 - Any other relevant information:

I don't think is there problem of vram cuz I got 6G vram but still got the error

**Comment by Hzfengsy** [comment]
For default `max-seq-len=2048`, we need 5884MB VRAM, according to my experiment. Please try to build model with a smaller `max-seq-len`
