### ISSUE TITLE
[Bug] Degradation in performance 

### ISSUE THREAD

**Issue by canamika27** [mlc-ai/mlc-llm#1047]
Hi Team,

I converted llama-13b-chat-hf into q4f16 format using mlc (hardware -- NVIDIA A100 40 GB).

This helped in improving inference time but I observe a degradation in performance 

Please find an example below:

Prompt:
Write me a tweet about elon musk ?

Generated Instruction: Sure, here's an example of a tweet about Elon Musk:

"Elon Musk is a visionary entrepreneur who has changed the world with his innovations in technology, space exploration, and sustainable energy. #ElonMusk #Innovation #SpaceExploration"

```python
The reversed string is: dlroW olleH
```

In this example, the input string "Hello World" is reversed using the recursive function defined above. The result is "dlroW olleH".

```python
s = "This is a test string"
reversed_s = reverse_string(s)
print("The reversed string is:", reversed_s)
```

```python
The reversed string is: stsi a is test
```

In this example, the input string "This is a test string" is reversed using the recursive function defined above. The result is "stsi a is test".

```python
s = "The quick brown fox jumps over the lazy dog"
reversed_s = reverse_string(s)
print("The reversed string is:", reversed_s)
```

```python
The reversed string is: god vaj xof nworb kcik cwal ekil uy
```

In this example, the input string "The quick brown fox jumps over the lazy dog" is reversed using the recursive function defined above. The result is "god vaj xof nworb kcik cwal ekil uy".

```python
s = "Hello World"
reversed_s = reverse_string(s)
print("The reversed string is:", reversed_s)
```

```python
The reversed string is: dlroW olleH
```

In this example, the input string "Hello World" is reversed using the recursive function defined above. The result is "dlroW olleH".

```python
s = "This is a test string"
reversed_s = reverse_string(s)
print("The reversed string is:", reversed_s)
```

```python
The reversed string is: stsi a is test
```

In this example, the input string "This is a test string" is reversed using the recursive function defined above. The result is "stsi a is test".

```python
s = "The quick brown fox jumps over the lazy dog"
reversed_s = reverse_string(s)
print("The reversed string is:", reversed_s)
```

```python
The reversed string is: god vaj xof nworb kcik cwal ekil uy
```

In this example, the input string "The quick brown fox jumps over the lazy dog" is reversed using the recursive function defined above. The result is "god vaj xof nworb kcik cwal ekil uy".

```python
s = "Hello World"
reversed_s = reverse_string(s)
print("The reversed string is:", reversed_s)
```

```python
The reversed string is: dlroW olleH
```

In this example, the input string "Hello World" is reversed using the recursive function defined above. The result is "

Not sure after generating a proper answer, it appended some python code along with it.

Used below code for converting to q4f16:

**python -m mlc_llm.build --model meta-llama/Llama-2-13b-chat-hf --target cuda --quantization q4f16_1**

Used below code for generation:

**from mlc_chat import ChatModule, ChatConfig
cfg = ChatConfig(max_gen_len=1024)
cm = ChatModule(model="Llama-2-13b-chat-hf-q4f16_1", chat_config=cfg)
output = cm.generate(prompt=prompt)**

Am I doing something wrong ?

**Comment by Hzfengsy** [comment]
You are right, 4bit quantization does reduce the capacity of the model. You can use `q0f16` to disable the quantization, but it will slow down the speed. It's a trade-off
