### ISSUE TITLE
Do you have plans to support the Android platform？

### ISSUE THREAD

**Issue by mackzheng** [mlc-ai/mlc-llm#105]

**Comment by junrushao** [comment]
Yep of course :-)

**Comment by junrushao** [comment]
It’s up! https://twitter.com/bohanhou1998/status/1655772690760994818

**Comment by PlayCoder1024** [comment]
> It’s up! https://twitter.com/bohanhou1998/status/1655772690760994818

awesome work!

**Comment by mackzheng** [comment]
awesome  amaze  perfect work，  thanks！
