### ISSUE TITLE
[Bug] There is a problem with using the num-shards parameter for multiple GPUs

### ISSUE THREAD

**Issue by shifeiwen** [mlc-ai/mlc-llm#1050]
## To Reproduce

1.git clone --recursive https://github.com/mlc-ai/mlc-llm.git
2. build tvm
3. python build.py --hf-path llama-2-13b-chat-hf --target cuda --quantization q4f16_0 --use-cache 0 --artifact-path /home/dell/workSpace/mlc_dist --build-model-only --debug-dump --num-shards 2

![img_v2_63264300-2f3e-4dfa-8af2-754c48be3efg](https://github.com/mlc-ai/mlc-llm/assets/147359299/de321338-0e4d-4448-8d8e-bd5f155070f0)

## Expected behavior

build over 

## TVM option

USE_CUDA ON
USE_NCCL /usr/local/nccl_2.18.5
USE_OPENCL ON
USE_OPENCL_ENABLE_HOST_PTR OFF
USE_OPENCL_GTEST /path/to/opencl/gtest
USE_VULKAN OFF
USE_KHRONOS_SPIRV OFF
USE_SPIRV_KHR_INTEGER_DOT_PRODUCT OFF
USE_METAL OFF
USE_ROCM OFF
USE_RCCL OFF
ROCM_PATH /opt/rocm
USE_HEXAGON OFF
USE_HEXAGON_SDK /path/to/sdk
USE_HEXAGON_RPC OFF
USE_HEXAGON_GTEST /path/to/hexagon/gtest
USE_HEXAGON_EXTERNAL_LIBS OFF
USE_RPC ON
USE_THREADS ON
USE_LLVM ON
USE_MLIR OFF
USE_STACKVM_RUNTIME OFF
USE_GRAPH_EXECUTOR ON
USE_GRAPH_EXECUTOR_CUDA_GRAPH OFF
USE_AOT_EXECUTOR ON
USE_PROFILER ON
USE_OPENMP none
USE_RELAY_DEBUG OFF
USE_RTTI ON
USE_MSVC_MT OFF
USE_MICRO OFF
INSTALL_DEV OFF
HIDE_PRIVATE_SYMBOLS OFF
USE_TF_TVMDSOOP OFF
USE_PT_TVMDSOOP OFF
USE_FALLBACK_STL_MAP OFF
USE_ETHOSN OFF
USE_CMSISNN OFF
INDEX_DEFAULT_I64 ON
USE_LIBBACKTRACE AUTO
BACKTRACE_ON_SEGFAULT OFF
BUILD_STATIC_RUNTIME OFF
BUILD_DUMMY_LIBTVM OFF
USE_PAPI OFF
USE_GTEST AUTO
USE_CUSTOM_LOGGING OFF
USE_ALTERNATIVE_LINKER AUTO
USE_CCACHE AUTO
DLPACK_PATH 3rdparty/dlpack/include
DMLC_PATH 3rdparty/dmlc-core/include
RANG_PATH 3rdparty/rang/include
COMPILER_RT_PATH 3rdparty/compiler-rt
PICOJSON_PATH 3rdparty/picojson
USE_BYODT_POSIT OFF
USE_BLAS none
USE_AMX OFF
USE_MKL OFF
USE_DNNL OFF
USE_CUDNN OFF
USE_CUBLAS OFF
USE_NVTX ON
USE_CUTLASS OFF
USE_THRUST OFF
USE_CURAND OFF
USE_MIOPEN OFF
USE_ROCBLAS OFF
USE_SORT ON
USE_NNPACK OFF
USE_LIBTORCH OFF
USE_RANDOM ON
USE_MICRO_STANDALONE_RUNTIME OFF
USE_CPP_RPC OFF
USE_IOS_RPC OFF
USE_TFLITE OFF
USE_TENSORFLOW_PATH none
USE_COREML OFF
USE_BNNS OFF
USE_TARGET_ONNX OFF
USE_ARM_COMPUTE_LIB OFF
USE_ARM_COMPUTE_LIB_GRAPH_EXECUTOR OFF
USE_TENSORRT_CODEGEN OFF
USE_TENSORRT_RUNTIME OFF
USE_RUST_EXT OFF
USE_VITIS_AI OFF
SUMMARIZE OFF
USE_CLML OFF
USE_CLML_GRAPH_EXECUTOR OFF
USE_UMA OFF
USE_VERILATOR OFF
USE_MSC OFF

## Additional context
I think it might have something to do with this commit   https://github.com/mlc-ai/mlc-llm/pull/941

**Comment by junrushao** [comment]
CC @jinhongyii the author of #941. I don't know if the `num_shards` only works for `q4f16_1` for now tbh

**Comment by shifeiwen** [comment]
Thanks for your reply, q4f16_1 does work.
