### ISSUE TITLE
[Question] Serving System

### ISSUE THREAD

**Issue by varshith15** [mlc-ai/mlc-llm#1051]
@tqchen  @junrushao 

Is there any ongoing thread on implementing a serving system like in vLLM (moving from request-level to iteration-level scheduling)? To basically compliment @MasterJH5574 's Batching and PagedAttention patches?

**Comment by junrushao** [comment]
Yep @MasterJH5574 is working on this as our first priority now :)

**Comment by tqchen** [comment]
consolidating to https://github.com/mlc-ai/mlc-llm/issues/1118
