### ISSUE TITLE
[Model Request] TinyLlama 1.1B - Intermediate checkpoint AND chat finetune

### ISSUE THREAD

**Issue by Fax** [mlc-ai/mlc-llm#1059]
## ⚙️  Request New Models

- Link to an existing implementation (e.g. Hugging Face/Github): 
https://huggingface.co/PY007/TinyLlama-1.1B-intermediate-step-480k-1T
https://huggingface.co/PY007/TinyLlama-1.1B-Chat-v0.3 (Finetuned on OpenAssistant/oasst_top1_2023-08-25 following the chatml format.)
- Is this model architecture supported by MLC-LLM? Yes

## Additional context
This is an intermediary step that actually behaves quite well for its size. The TinyLlama is a 1.1B parameters model that is getting trained over 3T tokens. It's small and it would be a perfect micro model for the WASM interface.

The new checkpoint will be released on the 2023-09-16, we don't know yet how it will perform and if it will be overfitted.

**Comment by acalatrava** [comment]
I already did this, here is the model

https://huggingface.co/acalatrava/mlc-chat-TinyLlama-1.1B-Chat-v0.3-q4f16_1

And here is the pre compiled library

https://github.com/mlc-ai/binary-mlc-llm-libs/pull/32

BTW, it works pretty good for its size!
