### ISSUE TITLE
[Unable to get Llama-2-7b-chat-hf-q3f16_1 to work] 

### ISSUE THREAD

**Issue by winstonschen** [mlc-ai/mlc-llm#1069]
## 🐛 Bug

Unable to get Llama-2-7b-chat-hf-q3f16_1 to work on iOS device or MacOS (Designed for iPad).

## To Reproduce

1. Followed step-by-step the instructions at https://llm.mlc.ai/docs/deploy/ios.html 
2. Ran the App on iOS (iPhone 14 Pro). RedPajama-INCITE-Chat-3B-v1-q4f16_1 works.
3. Added Llama-2-7b-chat-hf-q3f16_1 to app_config. 
4. Ran prepare_libs.sh
5. Ran the app again, and downloaded Llama-2-7b-chat-hf-q3f16_1 via the UI.
6. Model downloaded and loaded fine. But when using the model, the app crashed at ChatModule.prefill(prompt)
7. Same result running on iPhone 14 Pro and MacOS (Designed for iPad).

{
  "model_libs": [
    "Llama-2-7b-chat-hf-q3f16_1",
    "RedPajama-INCITE-Chat-3B-v1-q4f16_1"
  ],
  "model_list": [
    {
      "model_url": "https://huggingface.co/mlc-ai/mlc-chat-RedPajama-INCITE-Chat-3B-v1-q4f16_1/",
      "local_id": "RedPajama-INCITE-Chat-3B-v1-q4f16_1"
    },
    {
      "model_url": "https://huggingface.co/mlc-ai/mlc-chat-Llama-2-7b-chat-hf-q3f16_1/",
      "local_id": "Llama-2-7b-chat-hf-q3f16_1"
    }
  ],
  "add_model_samples": [
    {
      "model_url": "https://huggingface.co/mlc-ai/mlc-chat-RedPajama-INCITE-Chat-3B-v1-q4f16_1/",
      "local_id": "RedPajama-INCITE-Chat-3B-v1-q4f16_1"
    },
    {
      "model_url": "https://huggingface.co/mlc-ai/mlc-chat-Llama-2-7b-chat-hf-q3f16_1/",
      "local_id": "Llama-2-7b-chat-hf-q3f16_1"
    }
  ]
}

## Environment

 - Platform (e.g. WebGPU/Vulkan/IOS/Android/CUDA): Metal
 - Operating system (e.g. Ubuntu/Windows/MacOS/...): MacOS
 - Device (e.g. iPhone 12 Pro, PC+RTX 3090, ...): MacBook Pro M1 Pro 32 GB
 - How you installed MLC-LLM (`conda`, source): Github clone
 - How you installed TVM-Unity (`pip`, source): pip
 - Python version (e.g. 3.10): 3.11
 - GPU driver version (if applicable):
 - CUDA/cuDNN version (if applicable):
 - TVM Unity Hash Tag (`python -c "import tvm; print('\n'.join(f'{k}: {v}' for k, v in tvm.support.libinfo().items()))"`, applicable if you compile models):
 - Any other relevant information:

**Comment by junrushao** [comment]
Would you mind sharing the stack trace with us? We couldn't without detailed info :)

**Comment by tqchen** [comment]
As of now we haven't tested the q3 for RP flow. In general q3 should only be used when the model is too big to fit(aka only llama2 on iPhone). We recommend q4 for all other cases
