### ISSUE TITLE
How to debug every step in compiled so

### ISSUE THREAD

**Issue by shifeiwen** [mlc-ai/mlc-llm#1092]
## ❓ General Questions

Background: I want to add hexagon backend support for mlc -llm but I'm running into a problem. When I converted out the model and successfully built llm.hexagon.so and I successfully loaded so via load module . When I started executing prefill func for the first time, my code returned an error at the location of the yellow box in Picture 1, but there was no error message. It only tells me that the program dies when it runs to a certain operator. I got it by printing in c_runtime_api.cc. All the data sent to prefill can be printed normally.
Question: My question is how do I add some print log near the code in the red box in picture 2
![20231020-102919mlc](https://github.com/mlc-ai/mlc-llm/assets/147359299/ac317fda-6d8b-451d-8dfb-97f2996aa55e)

![20231020-104321mlc2](https://github.com/mlc-ai/mlc-llm/assets/147359299/15064434-9b14-4377-b75a-ca781dcf74ef)

**Comment by junrushao** [comment]
You may use set_instrument in RelaxVM.

**Comment by junrushao** [comment]
More documentation for RelaxVM instrument: https://github.com/apache/tvm/blob/unity/python/tvm/runtime/relax_vm.py#L342
