### ISSUE TITLE
Missing features in Android

### ISSUE THREAD

**Issue by GameOverFlowChart** [mlc-ai/mlc-llm#110]
1. the ability to stop the ai from writing
2. the ability to regenerate the last answer
3. the ability to edit your own prompt and get a new answer
4. The ability to copy text from prompts and ai outputs 
5. The option to change the parameters for the model (for example I would really like to increase the repetition penalty for the current model)

**Comment by Mizstik** [comment]
6. ability to load your own models

**Comment by GameOverFlowChart** [comment]
> 6. ability to load your own models

That's confirmed to come as far as I know.

**Comment by tqchen** [comment]
Thank you for the suggestions, I am marking the issue as temporary inactive, we are keeping inactive issues closed so we can open new ones. 

More recently we are adding a new android sdk https://llm.mlc.ai/docs/deploy/android.html so hopefully more apps can be built on top.
