### ISSUE TITLE
[Feature Request] Embedding model support

### ISSUE THREAD

**Issue by VoVAllen** [mlc-ai/mlc-llm#1110]
## 🚀 Feature
Support embedding model in https://huggingface.co/spaces/mteb/leaderboard

**Comment by junrushao** [comment]
This quarter we are going to gradually expand our scope from a simplistic Llama to more usecases and model architectures, and those embedding models are definitely interesting to us! Also CC @tqchen

**Comment by VoVAllen** [comment]
@junrushao Also curious do you have any plan to.add speculative decoding support?

**Comment by junrushao** [comment]
This is in the scope this quarter as well

**Comment by tqchen** [comment]
agree this is something we would like to do after the model expansion foundation

**Comment by mashahbazi** [comment]
@junrushao Any update on this feature?

**Comment by tqchen** [comment]
consolidating to #2324
