### ISSUE TITLE
[Tracking] Batching Support

### ISSUE THREAD

**Issue by tqchen** [mlc-ai/mlc-llm#1118]
## Overview
This is a tracking issue to track the batching support

## Action Items

- [x] The data structures
- [x] Unit tests
- [x] Python API
- [x] Rest integration

## Links to Related Issues and PRs

- https://github.com/mlc-ai/mlc-llm/pull/1084
- https://github.com/mlc-ai/mlc-llm/pull/1075
- https://github.com/mlc-ai/mlc-llm/pull/1072

**Comment by kdcyberdude** [comment]
Any updates on this?

**Comment by tqchen** [comment]
we are getting close, see also https://github.com/mlc-ai/mlc-llm/issues/1767

**Comment by MasterJH5574** [comment]
We have updated the REST API documentation with the latest MLC serve instructions https://llm.mlc.ai/docs/deploy/rest.html. Closing this issue due to completion now.
