### ISSUE TITLE
Android application force closes

### ISSUE THREAD

**Issue by JackJollimore** [mlc-ai/mlc-llm#112]
hi, my device is samsung s10+

the application downloaded parameters, and I see a message that shows ready for chat. I type any message, and send. I see my message is sent, and then the app for closes.

Thanks for any direction on this issue.

**Comment by GameOverFlowChart** [comment]
Is your initial prompt large? That happens sometimes if my prompt is too large. It also helps to close all other apps in background.

**Comment by JackJollimore** [comment]
> Is your initial prompt large? That happens sometimes if my prompt is too large. It also helps to close all other apps in background.

Thanks for your reply.

No, I am sending the message, 'hi'.

I've also closed all background apps to ensure it's not a ram issue.

**Comment by starlitsky2010** [comment]
Seems error OOM

W Adreno-GSL: <gsl_ldd_control:549>: ioctl fd 58 code 0xc0300945 (IOCTL_KGSL_GPUOBJ_ALLOC) failed: errno 12 Out of memory
E Adreno-GSL: <gsl_memory_alloc_pure:2354>: GSL MEM ERROR: kgsl_sharedmem_alloc ioctl failed.
I SDM     : HWCDisplayBuiltIn::GetOptimalRefreshRate: active_refresh_rate_: 60
W Adreno-GSL: <gsl_ldd_control:549>: ioctl fd 58 code 0xc0300945 (IOCTL_KGSL_GPUOBJ_ALLOC) failed: errno 12 Out of memory
E Adreno-GSL: <gsl_memory_alloc_pure:2354>: GSL MEM ERROR: kgsl_sharedmem_alloc ioctl failed.
E libc++abi: terminating with uncaught exception of type tvm::runtime::InternalError:

**Comment by JackJollimore** [comment]
There doesn't seem to be a fix yet.

For your information, today I downloaded the apk and allowed it to download the parameters.

It says ready, I send, 'hi', then it closes.

**Comment by jokerElsa** [comment]
Exactly same issue here, snapdragon 855 Samsung S10, with 8G ram, check the chip supports OpenCL, but crashes too.
But still excited and looking forward to deploying LLM on my phone natively, hope this issue can be fixed soon!!!!

**Comment by jokerElsa** [comment]
Seems like everyone is afraid of heavy-lifting on mobile, and the first message is always "hi".
(but still crash)
