### ISSUE TITLE
[Android] Permission Denied in Model Downloading

### ISSUE THREAD

**Issue by abasgames** [mlc-ai/mlc-llm#1122]
## 🐛 Bug

The app failed to download model config 
## To Reproduce
Open the app on a device running android 10

1.open the app
2.the app will display an error

Error Download model config failed : /storage/emulated/0/Download/e26b7f19-b28e-4029-bea2-fd5719698027 : open failed : EACCES ( Permission denied )
## Expected behavior
The app doesn't fail in download and loading the model config

The app runs and function as expected on android 10 without displaying the mentioned error
## Environment

 - Platform (e.g. WebGPU/Vulkan/IOS/Android/CUDA):
 - android
 - Operating system (e.g. Ubuntu/Windows/MacOS/...):
 - Device (e.g. iPhone 12 Pro, PC+RTX 3090, ...)
 - pocophone f1
 - How you installed MLC-LLM (`conda`, source):
 - prebuilt apk from GitHub
 - How you installed TVM-Unity (`pip`, source):
 - Python version (e.g. 3.10):
 - GPU driver version (if applicable):
 - CUDA/cuDNN version (if applicable):
 - TVM Unity Hash Tag (`python -c "import tvm; print('\n'.join(f'{k}: {v}' for k, v in tvm.support.libinfo().items()))"`, applicable if you compile models):
 - Any other relevant information:

## Additional context
Might be an issue to do with the app permissions

**Comment by tqchen** [comment]
https://github.com/mlc-ai/mlc-llm/pull/1136 might be related

**Comment by anibohara2000** [comment]
Able to reproduce on Android 10 emulator. Works on Android 13 physical device though. Looking into it
