### ISSUE TITLE
[Model Request] Mistral 7B on iOS and iPadOS

### ISSUE THREAD

**Issue by winstonschen** [mlc-ai/mlc-llm#1124]
## ⚙️  Request New Models

- Link to an existing implementation (e.g. Hugging Face/Github): https://huggingface.co/Open-Orca/Mistral-7B-OpenOrca
- Is this model architecture supported by MLC-LLM? (the list of [supported models](https://llm.mlc.ai/docs/prebuilt_models.html))  Yes

## Additional context
I think the ability to run a good LLM locally on iOS is the single most important feature of this project. On Macs/Linux/Windows there're other ways to run a local LLMs that work perfectly fine. But on iOS it is not possible -- or extremely hard -- until mlc-llm. Mistral 7B has the potential to be as good as GPT 3.5 Turbo, and potential applications are endless. 

Also, please consider iPadOS to be a viable target deserving of separate treatment. iPad Pros now come with M2 chips with a lot of RAM. And running apps get more RAM than iOS.

Finally, please make it easier to download/convert new models in the Mistral family without having to create new iOS libraries.

**Comment by CharlieFRuan** [comment]
Mistral on iOS should be supported by this PR: https://github.com/mlc-ai/mlc-llm/pull/1320.

Closing this issue for now; feel free to open another one if there are other questions/requests. Thank you!

**Comment by coder543** [comment]
@CharlieFRuan that PR was merged a couple of weeks ago. I checked and the MLC Chat app on my iPhone is up to date. Downloading the weights from the URL in the PR description works, but attempting to open a Mistral chat instantly crashes the iOS app. Are we still waiting on the app update to go through App Store review?

**Comment by CharlieFRuan** [comment]
@davidpissarra Could you take a look when you get a chance? Thank you!

**Comment by davidpissarra** [comment]
Hi @coder543 MLC Chat with mistral support is still not upstreamed on the app store. Still, it already supports mistral on the testflight app.
