### ISSUE TITLE
[Question] Can we compile a model in FP16?

### ISSUE THREAD

**Issue by moinnadeem** [mlc-ai/mlc-llm#1128]
Is it possible to use MLC to build a model in FP16 and deploy it? I would like to offer both quantized and non-quantized options.

**Comment by junrushao** [comment]
Yes. Some number in our latest blog (http://blog.mlc.ai/2023/10/19/Scalable-Language-Model-Inference-on-Multiple-NVDIA-AMD-GPUs#scalability) are fp16, see Figure 2 for details

**Comment by lx200100** [comment]
So，what is parameter ofnon-quantized options.

**Comment by junrushao** [comment]
Ah yep it's q0f16!
