### ISSUE TITLE
[Bug] RedPajama 3B cannot run in iPhone simulator

### ISSUE THREAD

**Issue by zhuochen24** [mlc-ai/mlc-llm#1131]
## 🐛 Bug

I am running MLC chat with default RedPajama 3B model in iPhone 15 Pro Max simulator.
However it says "Sorry, the system cannot provide 2150.4MB VRAM as requested to the app,..."

I can run MLC chat with RedPajama 3B on a physical iPhone Xs, so iPhone 15 Pro Max should have no problem doing that.

I wonder if I am missing any necessary setup/configuration?

I followed the steps in https://llm.mlc.ai/docs/deploy/ios.html, and used the simulator build by running "./prepare_libs.sh -s"

## Environment

 - MacBook Pro with Apple M2 processor
 - Operating system (e.g. Ubuntu/Windows/MacOS/...): Ventura 13.6.1
 - Device (e.g. iPhone 12 Pro, PC+RTX 3090, ...): iPhone 15 Pro Max simulator

**Comment by junrushao** [comment]
You will need a real phone with real A-series GPUs, unfortunately. There's no guarantee that simulators could work :(
