### ISSUE TITLE
[Doc] zstd.dll installation on Windows

### ISSUE THREAD

**Issue by David-Sharma** [mlc-ai/mlc-llm#1135]
### Suggestion
Please review and update the following from this page:
https://llm.mlc.ai/docs/install/tvm.html#install-tvm-unity

original: It is likely zstd, a dependency to LLVM, was missing. Please download the precompiled binary, rename it to zstd.dll and copy to the same folder as tvm.dll

Suggested:
It is likely zstd, a dependency to LLVM, was missing. Please download the precompiled binary, rename it to zstd.dll and copy to the same folder as tvm.dll. Hint - Perform a search for "tvm.dll" and identify the folder in which the path includes the name of the current environment eg. mlc-chat-venv. Copy zstd.dll to that folder. 

### Bug
- Link to the buggy documentation/tutorial: 
- Description of the bug:
This suggestion is based on the following reported by @Sing-Li 

Please pardon my (possible) related comment. The Note section above. Downloading and "rename it to zstd.dll and copy to the same folder as tvm.dll" part of the instruction --- is almost impossible for new users to accomplish because they have to understand how conda relates to python, and where miniconda keeps its python site libs before they can find "the same folder as tvm.dll". I hope one of the above fixes will make sure that zstd.dll is always included as part of the tvm bundle/nightly

**Comment by junrushao** [comment]
This is a headache I really wanted to resolve :(

**Comment by junrushao** [comment]
One easier way I found is to install zstd in conda, which even works nicely with Windows:

```bash
conda install zstd
```

**Comment by junrushao** [comment]
I don’t think it’s complete :((  Eventually we should be able to pack zstd with TVM so no extra steps are required

**Comment by junrushao** [comment]
Happy to share the zstd issue seems resolved with a few latest changes!

* https://github.com/apache/tvm/pull/16081
* https://github.com/apache/tvm/pull/16032
* https://github.com/mlc-ai/package/commit/ebe2cd9aa6c3db3a50026b94267e97f8d7ec8d4c

Would you guys mind trying out tomorrow with the latest nightly build?

**Comment by junrushao** [comment]
Closing as the issue has been addressed. Feel free to create new ones if it persists!
