### ISSUE TITLE
[Bug] Can't use rwkv-raven q8f16_0 on iphone

### ISSUE THREAD

**Issue by daystudio** [mlc-ai/mlc-llm#1140]
## 🐛 Bug

on the [link](https://llm.mlc.ai/docs/prebuilt_models.html#prebuilt-models-on-ios) , rwkv-raven only has q8f16_0 supported. but on the conversion script, no q8f16_0 supported.

invalid choice: 'q8f16_0' (choose from 'autogptq_llama_q4f16_0', 'autogptq_llama_q4f16_1', 'q0f16', 'q0f32', 'q3f16_0', 'q3f16_1', 'q4f16_0', 'q4f16_1', 'q4f16_2', 'q4f16_ft', 'q4f32_0', 'q4f32_1', 'q8f16_ft', 'q8f16_1')

if using the original model, don't have ...-iphone.tar file.

**Comment by MasterJH5574** [comment]
Thanks for your comment, on iphone, we only support a limited set of models with quantized format, we can also find that it is not part of iOS column of the model tab for now.  We will need specific quantized model support, e.g. q3f16 on llama2
