### ISSUE TITLE
[Bug] iOS app crashes when build from source

### ISSUE THREAD

**Issue by zhuochen24** [mlc-ai/mlc-llm#1141]
## 🐛 Bug

I have an iPhone Xs Max running the default RedPajama 3B model:
- It works when using the MLCChat app downloaded from App store
- It crashes due to OOM when building from source in Xcode and run on the iPhone (it can initialize, but when I type in first query and click "send", the app crashes due to OOM) 

I wonder why is there this difference and how can I fix it? Is it possible that a recent change (after the version in App Store) caused this bug? 

Thank you!

## Environment

 - Platform (e.g. WebGPU/Vulkan/IOS/Android/CUDA): iOS 17.0.3
 - Device (e.g. iPhone 12 Pro, PC+RTX 3090, ...): iPhone Xs Max
 - How you installed MLC-LLM (`conda`, source): from source following https://llm.mlc.ai/docs/deploy/ios.html

**Comment by Hzfengsy** [comment]
As you said, it's crashes due to OOM. As it only has 4GB memory, there is only 2GB free memory for applications.

Please confirm that you are using 768 as max length, per https://llm.mlc.ai/docs/compilation/compile_models.html
