### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by zappy586** [mlc-ai/mlc-llm#1145]
## 🐛 Bug
![image](https://github.com/mlc-ai/mlc-llm/assets/89218647/48657b24-355d-402b-884a-0c6c27009c58)
There is no file called chatmodule inside the mlcchat folder. Someone removed it from the official repo ig but idk. i need some help here.

**Comment by junrushao** [comment]
Indeed it’s available here: https://github.com/mlc-ai/mlc-llm/blob/main/android/src/java/ai/mlc/mlcllm/ChatModule.java
