### ISSUE TITLE
[Doc]  Under standing Code flow for model conversion and compilation | How to track code flow for llama mode / operators conversion to TIR & down to lower kernels for OpenCL

### ISSUE THREAD

**Issue by Nick-infinity** [mlc-ai/mlc-llm#1148]
### Request 

I am very new to TVM Unity, Relax, TIR etc. I tried following multiple tutorials to get understanding of TVM and then got to know TVM Unity is different and uses relax and not relay. 
1. The tuner and auto schedule does not apply to relax ( I guess)?
2. Does that means the llama mode is hand tuned and or static tuned config is used for every backend (OpenCL)?
3. How Can we print the kernels or the TIR config / optimiations used final model?
4. How can we build overall understanding of compilation (Pytorch - Relax - TIR - Model Lib) flow?

I am sorry if this is already explained somewhere. I tried reading the forums, Issues a lot but unable to build a good understanding of the project working and flow.

Can Someone Please help me to get started and list down how the model is written in mlc llm as entry point and how its converted.

@tqchen @Hzfengsy

**Comment by Nick-infinity** [comment]
Is this the entry point ? https://github.com/mlc-ai/mlc-llm/blob/main/mlc_llm/relax_model/llama.py
Is MLC-LLM a frontend for Relax?

**Comment by tqchen** [comment]
created a tracking issue at https://github.com/mlc-ai/mlc-llm/issues/1156

**Comment by Nick-infinity** [comment]
> Thanks for the questions
> 
>     * right now we are not applying tuning, instead we apply an optimization library called dlight
> 
>     * the kernels can be dumped using debug-dump option
> 
> 
> We are in the process of bringing up a LLM.compile flow around a new set of mechanism, after that we will come up to documentation item.
> 
> cc @cyx-6

Thanks for your time and replying to my queries.

1. Can you please point me code where dlight is being applied.  What kind of optimization dlight is doing? Does it gets applied on every backend ?
2. The TIR model is pre stored : https://github.com/mlc-ai/mlc-llm/blob/main/mlc_llm/dispatch/llama/main.py
    I thought that Relax graph is lowered to TIR & operator  prim functions using legalize op and other optimization passes.
    Is it not the case right now? Is tuning == Pass Optimizations for which you replied with dlight usage?

Thanks.

**Comment by Hzfengsy** [comment]
> Can you please point me code where dlight is being applied. What kind of optimization dlight is doing? Does it gets applied on every backend ?

The interface is at https://github.com/mlc-ai/mlc-llm/blob/main/mlc_llm/core.py#L598, while the dlight codes are at https://github.com/apache/tvm/tree/unity/python/tvm/dlight

> The TIR model is pre stored : https://github.com/mlc-ai/mlc-llm/blob/main/mlc_llm/dispatch/llama/main.py
I thought that Relax graph is lowered to TIR & operator prim functions using legalize op and other optimization passes.
Is it not the case right now? Is tuning == Pass Optimizations for which you replied with dlight usage?

Currently we are not using TIR dispatching. The link you provided is a legacy file and we may remove it in the near future.

**Comment by Nick-infinity** [comment]
Thanks for your time and reply @Hzfengsy 
I am trying ti understand the flow for the complete project. I wish to contribute to this project in future so I am trying to develop understanding of TVM Unity and mlc llm. I feel that MLC LLM diverges from the TVM Unity Tutorials and Forum posts and does thing in a more "hardcoded"  way (I might be completely wrong).

Do we store the model python code manually here : https://github.com/mlc-ai/mlc-llm/blob/main/mlc_llm/relax_model/llama.py
Is it being used anywhere in any way ( I think it gets used)
I wish to understand atleast the high level overview and major steps that comes into the picture. 
I will really appreciate some help..

Thanks
