### ISSUE TITLE
[Android] App causes extreme system slowdown and freezing

### ISSUE THREAD

**Issue by AutonomicPerfectionist** [mlc-ai/mlc-llm#115]
Running the Android app on my OnePlus 7 Pro (8Gb RAM) causes the phone to become nearly unresponsive. I am unable to bring up the keyboard, gesture controls fail, and pressing the power button takes several seconds to turn off the screen.

My best bet is it just doesn't have enough RAM because the issues occur after loading the model but before sending any messages. 8Gb seems pretty standard on Android phones though, is there a way to select a different model for me to test with?

**Comment by AutonomicPerfectionist** [comment]
I tried out the latest version and I still have slowdown issues, but I've found a new and interesting problem: upon the app crashing (probably because it's out of memory), I found my phone wallpaper had been changed. I have no idea how that happened, but I'm thinking there's something not quite right about my phone's operating system. I'll give the app a try on a different phone from a different manufacturer

**Comment by tqchen** [comment]
We indeed have a limit on RAM we can handle. Latest app ships with 3B model that might help in such cases
