### ISSUE TITLE
[Tracking][Docs] Document the overall LLM.compile flow

### ISSUE THREAD

**Issue by tqchen** [mlc-ai/mlc-llm#1156]
## Overview

We should provide an overview of the set of steps involved in the LLM.compile flow after it lands 

## Action Items

- [ ] Gives an overview of the import, compile(list of pipeline passes) and export step

## Links to Related Issues and PRs

https://github.com/mlc-ai/mlc-llm/issues/1148

**Comment by junrushao** [comment]
Basically this is a [ten-liner workflow](https://github.com/mlc-ai/mlc-llm/blob/02d1e57/python/mlc_chat/compiler/compile.py#L46-L59) with the following steps:

- Line 47-49: Create a non-quantized `nn.Module`, and mutate `nn.Module` to become a quantized one
- Line 51-53: Export the `nn.Module` to TVM's IRModule `mod`
- Line 56: Optimize `mod` with a Relax pipeline called `mlc_llm`
- Line 58: Export the `mod` to a `.so` or `.tar` file

**Comment by Nick-infinity** [comment]
Thank You very much for this @junrushao . It will help to map my component level understanding with e2e flow.

**Comment by Nick-infinity** [comment]
@junrushao is the same flow followed for android as well. I tried putting some prints in the code above and its not invoking my prints at all so I wonder if we are taking a diff approach for android?

**Comment by CharlieFRuan** [comment]
Closed via https://github.com/mlc-ai/mlc-llm/issues/1420
