### ISSUE TITLE
[Tracking][Docs] nn.Module quantize slim-LM flow

### ISSUE THREAD

**Issue by MasterJH5574** [mlc-ai/mlc-llm#1157]
## Overview

We are working on slim-LM to enable customized quantization format. This is an tracking issue to create a document example about importing customized quantized format

## Action Items

- [ ] customized quantization format docs

## Links to Related Issues and PRs

https://github.com/mlc-ai/mlc-llm/issues/606

**Comment by MasterJH5574** [comment]
cc @zxybazh @LeshengJin

**Comment by junrushao** [comment]
Basically this is a [ten-liner workflow](https://github.com/mlc-ai/mlc-llm/blob/02d1e57/python/mlc_chat/compiler/compile.py#L46-L59) with the following steps:

- Line 47-49: Create a non-quantized `nn.Module`, and mutate `nn.Module` to become a quantized one
- Line 51-53: Export the `nn.Module` to TVM's IRModule `mod`
- Line 56: Optimize `mod` with a Relax pipeline called `mlc_llm`
- Line 58: Export the `mod` to a `.so` or `.tar` file

**Comment by mayakolad** [comment]
Hi, I could not find "customized quantization format docs" on https://llm.mlc.ai/docs/, could you please point out the path or provide an example for reference?
