### ISSUE TITLE
prefill和decode速率获取

### ISSUE THREAD

**Issue by ChenJY1221** [mlc-ai/mlc-llm#1161]
## ❓ General Questions
我现在希望通过一个脚本化软件对mlc进行一个多次循环的测试，并且记录每一次输入之后的prefill和decode速率，请问有什么办法能在每一次输入之后对相应的prefill和decode速率进行抓取吗

**Comment by MasterJH5574** [comment]
Thanks for the question. Right now, on Python side we have the `stats()` function which returns a string containing the statistics https://github.com/mlc-ai/mlc-llm/blob/9076d0134f314d5cbf11909b8c0f954c399e8f62/examples/python/sample_mlc_chat.py#L18-L19 Likely you can parse the string to get the number.

**Comment by junrushao** [comment]
And we do provide docker-based tools to conveniently reproduce model performance: https://github.com/mlc-ai/llm-perf-bench#mlc-llm

**Comment by ChenJY1221** [comment]
@junrushao It seems that this docker-based tool is used to test the speed of prebuild and decode on the PC side. What I need to test now is the speed of the Android mobile terminal when it is running. Should I use the stats() function to obtain the relevant speed?Or there are some other ways to get the Android running speed?

**Comment by MasterJH5574** [comment]
The Android app displays the speed on screen and the app does not have public API to get the speed if I understand correctly.

Also cc @cyx-6, since I am not very familiar with Android.

**Comment by cyx-6** [comment]
@ChenJY1221 I think the current way to obtain speed info on android is by calling `ChatModule.runtimeStatsText()`, refer to https://github.com/mlc-ai/mlc-llm/blob/main/android/src/java/ai/mlc/mlcllm/ChatModule.java#L58-L60.
