### ISSUE TITLE
prefill and decode rate acquisition

### ISSUE THREAD

**Issue by ChenJY1221** [mlc-ai/mlc-llm#1162]
## ❓ General Questions
I now hope to use a scripted software to test mlc in multiple loops and record the prefill and decode rates after each input. Is there any way to capture the corresponding prefill and decode rates after each input? ?

**Comment by junrushao** [comment]
This is identical question to #1161. See the reply: https://github.com/mlc-ai/mlc-llm/issues/1161#issuecomment-1787268899
