### ISSUE TITLE
[Question]Model performance deteriorates

### ISSUE THREAD

**Issue by lx200100** [mlc-ai/mlc-llm#1163]
## ❓ General Questions

I build the llama2 13b model with q0f16 in cuda platform. but, when inference the output, the performance deteriorates obviously.
mlc-chat-config.json is below
`"conv_template": "llama-2",
    "conv_config": {
    "seps": [""
    ],
    "stop_tokens": [
    2
    ],
    "offset": 0,
    "separator_style": 1,
    "messages": [],
    "stop_str": "<\/s>",
    "roles": [],
    "role_msg_sep": "",
    "role_empty_sep": "",
    "system": "",
    "add_bos": false
    },
    "temperature": 0.7,
    "repetition_penalty": 1.1,
    "top_p": 0.05,
    "mean_gen_len": 1280,
    "max_gen_len": 2120,
    "max_window_size": 4096,
    "num_shards": 1,
    "shift_fill_factor": 0.3,
    "tokenizer_files": [
        "tokenizer.model"
    ],
    "model_category": "llama",
    "model_name": "cllm-pre363G5k-llama2-13b-mtask_v14_68k_ls_fa_10k",
    "vocab_size": 55296`

**Comment by junrushao** [comment]
Please use `q4f16_1`
