### ISSUE TITLE
[Question]the code of libmlc_llm.so ?

### ISSUE THREAD

**Issue by lx200100** [mlc-ai/mlc-llm#1164]
## ❓ General Questions

I want to know where is the code of libmlc_llm.so? because, In this libmlc_llm.so the decode process is in it, I need to make a little modifiy to the source code of libmlc_llm.so.

**Comment by MasterJH5574** [comment]
Hi @lx200100 thanks for the question. `libmlc_llm.so` is basically built from our ChatModule in this file https://github.com/mlc-ai/mlc-llm/blob/9076d0134f314d5cbf11909b8c0f954c399e8f62/cpp/llm_chat.cc#L795-L815 You can follow the instructions here to build it from source. https://llm.mlc.ai/docs/deploy/cli.html#option-2-build-mlc-runtime-from-source

The decode process in our ChatModule essentially invokes the decode function in models. E.g., the decode function in Llama we define here https://github.com/mlc-ai/mlc-llm/blob/9076d0134f314d5cbf11909b8c0f954c399e8f62/mlc_llm/relax_model/llama.py#L978-L1015

So if you want to change the model behavior, you may want to modify the model and compile models by following https://llm.mlc.ai/docs/compilation/compile_models.html
