### ISSUE TITLE
 Error: Cannot find PackedFunc vm.builtin.null_value in either Relax VM kernel library

### ISSUE THREAD

**Issue by CurryFRice** [mlc-ai/mlc-llm#118]
when i run mlc_chat_cli, occurs the error on mac m1

/Users/jshao/Projects/mlc-ai-utils/tvm/src/runtime/metal/metal_device_api.mm:165: Intializing Metal device 0, name=Apple M1
Initializing the chat module...
[15:54:34] /Users/jshao/Projects/mlc-ai-utils/tvm/src/runtime/relax_vm/vm.cc:768:
---------------------------------------------------------------
An error occurred during the execution of TVM.
For more information, please see: https://tvm.apache.org/docs/errors.html
---------------------------------------------------------------
  Check failed: (func.defined()) is false: Error: Cannot find PackedFunc vm.builtin.null_value in either Relax VM kernel library, or in TVM runtime PackedFunc registry, or in global Relax functions of the VM executable

**Comment by cgsvv** [comment]
I have encountered the same problem this morning. I tried to run `conda install -c mlc-ai -c conda-forge mlc-chat-nightly` again, it updated mlc-chat-nightly and finally worked

**Comment by tqchen** [comment]
closing as the latest version resolved the problem.
