### ISSUE TITLE
Support for ChatGLM3-6B please

### ISSUE THREAD

**Issue by developer-ken** [mlc-ai/mlc-llm#1181]
## 🚀 Feature

mlc-llm works perfectly with ChatGLM2-6B. But it wont work with the new ChatGLM3-6B.
So requesting for ChatGLM3-6B support.

## Motivation

ChatGLM3 supports Function Call, which is a powerful feature.

**Comment by fierceX** [comment]
I tested it with the current version by changing `"chatglm2": "glm",` in utils.py to `"chatglm3": "glm",` and changing `model.startswith("chatglm2")` in chatglm.py to `model.startswith("chatglm3")`. And change `vocab_size=config["vocab_size"]` to `vocab_size=config["padded_vocab_size"]` in core.py. It is possible to compile chatglm3-6b successfully and it runs. But I'm not sure if the new features of chatglm3 will be supported
