### ISSUE TITLE
[Question] I want to know in "qAfB_id", which quantization algorithms the "_id" stands for?

### ISSUE THREAD

**Issue by xukui1203** [mlc-ai/mlc-llm#1183]
For example , if I want to use gptq, which number should I use for "_id"?
Is there a document to show the relationship?

Thanks

**Comment by Hzfengsy** [comment]
Here is the definition of quantization methods: https://github.com/mlc-ai/mlc-llm/blob/main/mlc_llm/quantization/__init__.py

GPTQ only works for llama now
