### ISSUE TITLE
[Question]  Is input prompt processing (prefill) a parallel process unlike token by token generation of decoding phase in Android OpenCL

### ISSUE THREAD

**Issue by Nick-infinity** [mlc-ai/mlc-llm#1184]
## ❓ General Questions

Hello, 
Is the input prompt processing to generate kv cache a parallel process or a token by token process like decode?
I see diff results for prefill t/s and decode t/s in Android app and prefill is usually slower.

If decode is much faster by token by token scheme, what's the advantage of using parallel prefill processing (if that's the case)

**Comment by Hzfengsy** [comment]
It's parallel, but the kernel implementation is not good enough.

**Comment by Nisbij** [comment]
Is there a way to see the kernel implementation? I want to have a look for performance predictions
