### ISSUE TITLE
[Bug] Out of memory error with mistral 7B

### ISSUE THREAD

**Issue by Lurrobert** [mlc-ai/mlc-llm#1186]
## 🐛 Bug

After running `mlc_chat_cli --model Mistral-7B-OpenOrca-q4f16_1 --device metal` chat opens up. But typing something and pressing enter, it breaks instantly. Looks like memory problem

## To Reproduce

1. git clone https://huggingface.co/Open-Orca/Mistral-7B-OpenOrca
2.  python3 -m mlc_llm.build --model Mistral-7B-OpenOrca --target metal --quantization q4f16_1
3. mlc_chat_cli --model Mistral-7B-OpenOrca-q4f16_1 --device metal
4. type in something and press enter

```
❯ mlc_chat_cli --model Mistral-7B-OpenOrca-q4f16_1 --device metal
Use MLC config: "/Users/robertlukoshko/Programming/mlc-llm/dist/Mistral-7B-OpenOrca-q4f16_1/params/mlc-chat-config.json"
Use model weights: "/Users/robertlukoshko/Programming/mlc-llm/dist/Mistral-7B-OpenOrca-q4f16_1/params/ndarray-cache.json"
Use model library: "/Users/robertlukoshko/Programming/mlc-llm/dist/Mistral-7B-OpenOrca-q4f16_1/Mistral-7B-OpenOrca-q4f16_1-metal.so"
You can use the following special commands:
  /help               print the special commands
  /exit               quit the cli
  /stats              print out the latest stats (token/sec)
  /reset              restart a fresh chat
  /reload [model]  reload model `model` from disk, or reload the current model if `model` is not specified

Loading model...
Loading finished
Running system prompts...
System prompts finished
[INST]: hello
[00:41:22] /Users/catalyst/Workspace/miniforge3/envs/mlc-llm-build/conda-bld/mlc-chat-cli-nightly-package_1698048403779/work/3rdparty/tvm/src/runtime/relax_vm/pooled_allocator.h:64: Warning: PooledAllocator got InternalError during allocation: InternalError: Check failed: (buf != nil) is false:
[00:41:22] /Users/catalyst/Workspace/miniforge3/envs/mlc-llm-build/conda-bld/mlc-chat-cli-nightly-package_1698048403779/work/3rdparty/tvm/src/runtime/relax_vm/pooled_allocator.h:65: Warning: Trying to release all unused memory and reallocate...
libc++abi: terminating due to uncaught exception of type tvm::runtime::InternalError: [00:41:23] /Users/catalyst/Workspace/miniforge3/envs/mlc-llm-build/conda-bld/mlc-chat-cli-nightly-package_1698048403779/work/3rdparty/tvm/include/tvm/runtime/packed_func.h:1307: unknown type = 0
Stack trace:
  [bt] (0) 1   libtvm_runtime.dylib                0x00000001034dd95c tvm::runtime::detail::LogFatal::Entry::Finalize() + 68
  [bt] (1) 2   libtvm_runtime.dylib                0x00000001034dd918 tvm::runtime::detail::LogFatal::Entry::Finalize() + 0
  [bt] (2) 3   libtvm_runtime.dylib                0x00000001034d7c20 __clang_call_terminate + 0
  [bt] (3) 4   libtvm_runtime.dylib                0x00000001035a748c tvm::runtime::relax_vm::MemoryManager::GetAllocator(DLDevice) + 640
  [bt] (4) 5   libtvm_runtime.dylib                0x0000000103584f34 tvm::runtime::SimpleObjAllocator::Handler<tvm::runtime::relax_vm::StorageObj>::Deleter_(tvm::runtime::Object*) + 28
  [bt] (5) 6   libtvm_runtime.dylib                0x0000000103580f70 tvm::runtime::relax_vm::VMAllocStorage(void*, tvm::runtime::ShapeTuple, long long, DLDataType, tvm::runtime::String) + 980
  [bt] (6) 7   libtvm_runtime.dylib                0x0000000103585ab0 void tvm::runtime::TypedPackedFunc<tvm::runtime::relax_vm::Storage (void*, tvm::runtime::ShapeTuple, long long, DLDataType, tvm::runtime::String)>::AssignTypedLambda<tvm::runtime::relax_vm::Storage (*)(void*, tvm::runtime::ShapeTuple, long long, DLDataType, tvm::runtime::String)>(tvm::runtime::relax_vm::Storage (*)(void*, tvm::runtime::ShapeTuple, long long, DLDataType, tvm::runtime::String), std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>)::'lambda'(tvm::runtime::TVMArgs const&, tvm::runtime::TVMRetValue*)::operator()(tvm::runtime::TVMArgs const&, tvm::runtime::TVMRetValue*) const + 284
  [bt] (7) 8   libtvm_runtime.dylib                0x00000001035bd614 tvm::runtime::relax_vm::VirtualMachineImpl::InvokeClosurePacked(tvm::runtime::ObjectRef const&, tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*) + 96
  [bt] (8) 9   libtvm_runtime.dylib                0x00000001035bf584 tvm::runtime::relax_vm::VirtualMachineImpl::RunInstrCall(tvm::runtime::relax_vm::VMFrame*, tvm::runtime::relax_vm::Instruction) + 1504


[1]    97437 abort      mlc_chat_cli --model Mistral-7B-OpenOrca-q4f16_1 --device metal
```

## Expected behavior

No crashes optimal exection

## Environment

 - Platform (e.g. WebGPU/Vulkan/IOS/Android/CUDA): metal
 - Operating system (e.g. Ubuntu/Windows/MacOS/...): macos
 - Device (e.g. iPhone 12 Pro, PC+RTX 3090, ...): metal
 - How you installed MLC-LLM (`conda`, source): conda
 - How you installed TVM-Unity (`pip`, source): pip
 - Python version (e.g. 3.10): 3.8
 - GPU driver version (if applicable):
 - CUDA/cuDNN version (if applicable):
 - TVM Unity Hash Tag (`python -c "import tvm; print('\n'.join(f'{k}: {v}' for k, v in tvm.support.libinfo().items()))"`, applicable if you compile models):
 - Any other relevant information:

## Additional context
image from activity monitor just before crash
![image](https://github.com/mlc-ai/mlc-llm/assets/40468118/bd6d3425-3ad2-4937-b3be-b1bfa7916664)
![image](https://github.com/mlc-ai/mlc-llm/assets/40468118/94f82315-f387-4735-92ad-f30849118cfb)

another person mentioned the same problem
https://github.com/mlc-ai/mlc-llm/pull/986#issuecomment-1784565456

**Comment by davidpissarra** [comment]
Mistral OpenOrca seems to work fine on the cuda side, must be an issue on metal. cc @CharlieFRuan

**Comment by CharlieFRuan** [comment]
Hi @Lurrobert, thanks for reporting the issue! Just tried both Mistral Instruct and Mistral OpenOrca on a Mac Studio and it worked fine. The problem you are seeing is probably due to #1087, where we updated `llm_chat.cc`. Therefore, you would need to either install the latest nightly, or build from source using the latest repo. 

Note that the bad output of OpenOrca is due to the fact that I didn't update the conv template (since they use different template than mistral instruct).
Mistral-Instruct: 
<img width="1735" alt="Screen Shot 2023-11-06 at 7 27 12 PM" src="https://github.com/mlc-ai/mlc-llm/assets/53290280/a3be6aa2-f74c-4b76-adaf-ca14de764aec">
Mistral-OpenOrca:
<img width="1994" alt="Screen Shot 2023-11-06 at 7 34 11 PM" src="https://github.com/mlc-ai/mlc-llm/assets/53290280/4dc66340-b010-49d4-bd7b-9511a1123181">
