### ISSUE TITLE
[issue] Cmake OPENCL Error

### ISSUE THREAD

**Issue by Vinaysukhesh98** [mlc-ai/mlc-llm#1199]
## ❓ Android app

 while running prepare_library.sh script in android im getting the below error couldn’t able fix and identity those files as well
CMake Error at /home/mbu-lap/Documents/Vinay/31/mlc-llm/3rdparty/tvm/cmake/modules/OpenCL.cmake:86 (add_executable):
  No SOURCES given to target: opencl-cpptest
Call Stack (most recent call first):
  /home/mbu-lap/Documents/Vinay/31/mlc-llm/3rdparty/tvm/CMakeLists.txt:539 (include)

**Comment by junrushao** [comment]
This part of logic should only be executed when  USE_OPENCL_GTEST Is turned on: https://github.com/apache/tvm/blob/main/cmake/modules/OpenCL.cmake#L62. You may comment out the related logic given they are not used anyways

**Comment by Vinaysukhesh98** [comment]
HI junru,
![Screenshot from 2023-11-07 12-18-13](https://github.com/mlc-ai/mlc-llm/assets/147804128/52005350-bb08-48f1-83dd-6a8e1544cc51)
i have crossed checked the following lines are same i haven't changed anything, uploading screenshot for ref

**Comment by junrushao** [comment]
1) Can you actually remove any logic related USE_OPENCL_GTEST? It’s not used anyways;
2) Could you share the steps you made to reproduce this error. I will need more context to be helpful

**Comment by Vinaysukhesh98** [comment]
HI Junur by removing USE_OPENCL_GTEST able to build the apk , but while running the llama model , i'm getting below error: 
 mlc-llm/3rdparty/tvm/src/runtime/relax_vm/ndarray_cache_support.cc:262: Check failed: shard_rec.nbytes == raw_data.length() (45088768 vs. 41161212) : ValueError: Parameters are not loaded properly. Please check your parameter shards and git lfs installation

**Comment by tqchen** [comment]
this likely mean that we get a corrupted parameter file, please try to redownload the parameter shards or rebuild to recreate these files

**Comment by junrushao** [comment]
Yeah just re-download and it should be fine

**Comment by Vinaysukhesh98** [comment]
hi your mention about re-download tvm or only relax_vm , if you're mentioning about relax_vm , couldn't able to find that module in tvm.

**Comment by Vinaysukhesh98** [comment]
Hi here your mentioning about re-download tvm?

**Comment by Vinaysukhesh98** [comment]
i just re-downloaded and completed the setup from first it worked.

Thanks for your help junrushao.
