### ISSUE TITLE
8gen2数据

### ISSUE THREAD

**Issue by ugvvff** [mlc-ai/mlc-llm#120]
![Screenshot_MLCChat_20230510_162517](https://github.com/mlc-ai/mlc-llm/assets/102452767/bcc7ce17-c7c0-4fa8-bb3b-6c7478394619)
这是8gen2处理器数据。运行时gpu占满，话说用的是int8还是多少。他能否运行在npu上？如果能运行在npu上，使用int4量化说不定有更快的速度（第一款npu支持int4的处理器）

**Comment by tqchen** [comment]
Thank you, consolidating data to #15

**Comment by lixiangnlp** [comment]
> ![Screenshot_MLCChat_20230510_162517](https://user-images.githubusercontent.com/102452767/237326346-bcc7ce17-c7c0-4fa8-bb3b-6c7478394619.jpg) 这是8gen2处理器数据。运行时gpu占满，话说用的是int8还是多少。他能否运行在npu上？如果能运行在npu上，使用int4量化说不定有更快的速度（第一款npu支持int4的处理器）

int4 works only for limited ops
