### ISSUE TITLE
[Question]  Does it work on ROCm with AMD APU - Ryzen 7940HS / Radeon 780M

### ISSUE THREAD

**Issue by bod2000** [mlc-ai/mlc-llm#1208]
## ❓ General Questions

I'm new in this space and want to try this library and pipeline. Have couple questions.
1. Does it work on ROCm 5.7 with AMD APU - Ryzen 7940HS / Radeon 780M ?
2. Is performance of this iGPU enough to do simple things? Can I use this GPU to take existing model and train it with additional data?
3. Is it even worth to spend time trying this GPU or support/performance so bad that it makes sense to buy cheap Nvidia card?

**Comment by junrushao** [comment]
MLC LLM does work on an APU we have (a SteamDeck) [Link](https://blog.mlc.ai/2023/08/09/Making-AMD-GPUs-competitive-for-LLM-inference). It works with ROCm as well, according to multiple reports on 7900XTX and MI-50/100/300, etc.

I don't know anything about Radeon 780M this particular model, and a possible alternative is to try [WebLLM](https://webllm.mlc.ai/) first to determine if Chrome's WebGPU runtime supports it or not.

**Comment by junrushao** [comment]
See https://github.com/mlc-ai/mlc-llm/issues/787#issuecomment-1801064211
