### ISSUE TITLE
[Question] Can we have any optimization within the mlc-llm project?

### ISSUE THREAD

**Issue by Lanssi** [mlc-ai/mlc-llm#1219]
## ❓ General Questions

Hi! I've managed to deploy Llama and RedPajama on android with mlc-llm project. However, I trying to make the inference faster on the android device. Is there any method we can do the optimization?

**Comment by Lanssi** [comment]
For example, can I achieve the goal by modifying the build arguments?
I've check the "mlc_llm.build" script. Can I do the optimization in the tvm style? How can I achieve that?

**Comment by MasterJH5574** [comment]
Hi @Lanssi, thanks for the question. We have applied optimizations along the way https://github.com/mlc-ai/mlc-llm/blob/1a6faddd0c13c23e5560ec124d78797be9140c15/mlc_llm/core.py#L450 https://github.com/mlc-ai/mlc-llm/blob/1a6faddd0c13c23e5560ec124d78797be9140c15/mlc_llm/core.py#L626
The models built with MLC LLM running on Android devices are already optimized.

**Comment by Lanssi** [comment]
> Hi @Lanssi, thanks for the question. We have applied optimizations along the way
> 
> https://github.com/mlc-ai/mlc-llm/blob/1a6faddd0c13c23e5560ec124d78797be9140c15/mlc_llm/core.py#L450
> 
> https://github.com/mlc-ai/mlc-llm/blob/1a6faddd0c13c23e5560ec124d78797be9140c15/mlc_llm/core.py#L626
> 
> 
> The models built with MLC LLM running on Android devices are already optimized.

Thanks for your reply!
I wonder if I can further do some customized optimization?

**Comment by junrushao** [comment]
I was curious what kind of optimization specifically in your mind? I believe by default, MLC LLM has done optimizations at different levels, including on-the-fly decoding, fusion, kernel optimization and memory optimization. What else in your mind?

**Comment by junrushao** [comment]
Got it. Let us know if there’s any optimization not included in the current pipeline :)

**Comment by Lanssi** [comment]
> > I was curious what kind of optimization specifically in your mind? I believe by default, MLC LLM has done optimizations at different levels, including on-the-fly decoding, fusion, kernel optimization and memory optimization. What else in your mind?
> 
> No. But I'm exploring if I can customize the optimization so that I can evaluate the effect of different optimization strategy.

By the way, one more question.
In terms of mobile phone, we have CPU and GPU. And a CPU have multiple cores. Do you consider the heterogeneous computing? For example, using blocking in mat_mul and balance them onto different computing resource. Will it make sense?

**Comment by junrushao** [comment]
Unfortunately the CPU is pretty slow compared with GPU even on mobile settings (e.g. snapdragon 8gen3), and the memory bandwidth between them are pretty limited, and therefore, it’s not particularly useful in LLM inference. However, on the other hand, Hexagon DSP might be something worth considering if you are interested in this direction!
