### ISSUE TITLE
[Bug] `mlc-ai-nightly-rocm` not found in pip.

### ISSUE THREAD

**Issue by fmv1992** [mlc-ai/mlc-llm#1223]
## 🐛 Bug

`mlc-ai-nightly-rocm` not found in pip.

## To Reproduce

1.  [Follow the documentation](https://llm.mlc.ai/docs/install/mlc_llm.html) for installing the library: `python3 -m pip install --pre -U -f https://mlc.ai/wheels mlc-chat-nightly-rocm56 mlc-ai-nightly-rocm56`.

1.  But I get:

    ```
    #27 [20/40] RUN python3 -m pip install --pre --force-reinstall mlc-ai-nightly-rocm mlc-chat-nightly-rocm -f https://mlc.ai/wheels
    #27 0.718 Looking in links: https://mlc.ai/wheels
    #27 1.228 ERROR: Could not find a version that satisfies the requirement mlc-ai-nightly-rocm (from versions: none)
    #27 1.229 ERROR: No matching distribution found for mlc-ai-nightly-rocm
    #27 ERROR: executor failed running [/bin/bash -o pipefail -c python3 -m pip install --pre --force-reinstall mlc-ai-nightly-rocm mlc-chat-nightly-rocm -f https://mlc.ai/wheels]: exit code: 1
    ------
     > [20/40] RUN python3 -m pip install --pre --force-reinstall mlc-ai-nightly-rocm mlc-chat-nightly-rocm -f https://mlc.ai/wheels:
    0.718 Looking in links: https://mlc.ai/wheels
    1.228 ERROR: Could not find a version that satisfies the requirement mlc-ai-nightly-rocm (from versions: none)
    1.229 ERROR: No matching distribution found for mlc-ai-nightly-rocm
    ```

## Expected behavior

I expected: that the package installation would always succeed.

A suggestion: I've also noticed that there's a single `tag: v0.1.dev0` release for this project. I know this is a "nightly" supported only, but maybe we could have some versioning still to avoid breaking things? Then people could use the bleeding-edge nightly if they wanted to, but folks could instead opt for `nightly-2023-11-08-v0.1.dev0` for example.

## Environment

- Platform (e.g. WebGPU/Vulkan/IOS/Android/CUDA): ROCM.
- Operating system (e.g. Ubuntu/Windows/MacOS/...): `ubuntu`.
- Device (e.g. iPhone 12 Pro, PC+RTX 3090, ...): independent of device.
- How you installed MLC-LLM (`conda`, source): the problem is installing it.
- How you installed TVM-Unity (`pip`, source): no.
- Python version (e.g. 3.10): 3.10
- GPU driver version (if applicable): not applicable.
- CUDA/cuDNN version (if applicable): not applicable.
- TVM Unity Hash Tag (`python -c "import tvm; print('\n'.join(f'{k}: {v}' for k, v in tvm.support.libinfo().items()))"`, applicable if you compile models): not applicable.

**Comment by junrushao** [comment]
Please follow the documentation here: https://llm.mlc.ai/docs/install/tvm.html#option-1-prebuilt-package

**Comment by junrushao** [comment]
There should be a suffix like rocm57, i suppose?

**Comment by fmv1992** [comment]
> There should be a suffix like rocm57, i suppose?

Thanks for the fast response. I'll try that, but in any case, I think this could be affecting others.

**Comment by junrushao** [comment]
oh i think it’s just a typo on your end. as you mentioned in step 1, the documentation says:

```
python3 -m pip install --pre -U -f https://mlc.ai/wheels mlc-chat-nightly-rocm56 mlc-ai-nightly-rocm56
```

but the instructions you’ve got are using:

```
#27 [20/40] RUN python3 -m pip install --pre --force-reinstall mlc-ai-nightly-rocm mlc-chat-nightly-rocm -f https://mlc.ai/wheels
```

which lacks the suffix 56/57

**Comment by junrushao** [comment]
The suffix 56/57 corresponds to ROCm versions 5.6 and 5.7, which are not related to MLC LLM’s version, so even if with date-based naming, we still need 56/57 as the suffix.

**Comment by junrushao** [comment]
I assume this issue is gone after fixing the typo, but please feel free to reopen this issue if there’s still anything wrong

**Comment by fmv1992** [comment]
Thanks for your input. That worked for our case but I don't want to miss out on the opportunity of saying others could be affected if they install through the [CPU tab](https://llm.mlc.ai/docs/install/mlc_llm.html). I still think that labeling your releases, even if they are nightly could help the user base.

**Comment by junrushao** [comment]
Fair enough. Thanks for the input! What do you think we should do to avoid users mistakenly installing a CPU-only pip package in the CPU tab?

**Comment by fmv1992** [comment]
Thanks for giving attention to this!

> Fair enough. Thanks for the input! What do you think we should do to avoid users mistakenly installing a CPU-only pip package in the CPU tab?

The documentation is clear enough on that part. I think it was I that didn't pay enough attention.

My perspective here is more on the release part. Ideally I would like to pin to a version, even if a dev one:

```
python3 -m pip install 'mlc-ai-nightly-rocm56==1.2.3'
```

So that I'm sure to be using the same code over different days.

Irrespective of specifying the CPU/GPU architecture, it looks like using:

```
python3 -m pip install --pre -U -f https://mlc.ai/wheels mlc-chat-nightly-rocm56 mlc-ai-nightly-rocm56
```

For instance, will give me a slightly different package every now and then. Correct me if I'm wrong...

**Comment by MasterJH5574** [comment]
@fmv1992 Yes, the latter command will always give you the up-to-date wheel package. Actually, for now we apply an auto-cleaning routine and do not keep the old versions. That is to say, we will automatically remove old wheels once there are newer ones. This is because we do nightly build everyday, and the total wheel list will be very large if we keep multiple history versions for different combination of OS, Python versions, CUDA/ROCm versions.
