### ISSUE TITLE
[BUG] [Solved] running Mistral-7B-Instruct-v0.1 on CUDA

### ISSUE THREAD

**Issue by chymian** [mlc-ai/mlc-llm#1240]
## 🐛 Bug

there are no precompiled cuda-libs available for Mistral.
I was testing the multiGPU feature, so I sticked to create a lib with these instructions:
https://blog.mlc.ai/2023/10/19/Scalable-Language-Model-Inference-on-Multiple-NVDIA-AMD-GPUs

## To Reproduce
follow the instructions
`MODEL=Mistral-7B-Instruct-v0.1`
step  0 & 1.
step 2. __Attention:__
the Mistral's config file is missing from from the `mlc-ai/llm-perf-bench/main/model_configs`
so, instead of 
```
curl https://raw.githubusercontent.com/mlc-ai/llm-perf-bench/main/model_configs/$MODEL.json \
     --create-dirs -o ./dist/models/$MODEL/config.json
```
do 
```
curl https://huggingface.co/mistralai/Mistral-7B-Instruct-v0.1/raw/main/config.json  \
    --create-dirs -o ./dist/models/$MODEL/config.json
```

The Mistral uses on a 3070 (8GB) GPU:  5151MiB VRAM 
so it should fit in a GPU >= 6GB VRAM
adapt the `--num-shards` in the compile command and the `dist/Mistral-7B-Instruct-v0.1/params/mlc-chat-config.json` file accordingly.

then compile:
```
python3 -m mlc_llm.build --build-model-only \
    --model ./dist/models/$MODEL/ \
    --quantization q4f16_1 \
    --max-seq-len 4096 \
    --num-shards 1 \
    --target cuda --use-cuda-graph
```

## Test
Run the rest-api:
```
 PYTHONPATH=python python -m mlc_chat.rest --model Mistral-7B-Instruct-v0.1  --device cuda --host 0.0.0.0
```

even so, the models endpoint gives nothing back:
```
$ curl -s http://gulag:8000/v1/models|jq
{
  "detail": "Not Found"
}
```

it does work:
```
 curl -s http://gulag:8000/v1/chat/completions -H "Content-Type: application/json" -d '{ 
  "model": "Mistral-7B-Instruct-v0.1", 
  "messages": [{"role": "user", "content": "Say this is a test!"}],
  "temperature": 0.1 }' | jq

{
  "id": "chatcmpl-39NAUarNFdMnj8LkXWNtSL",
  "object": "chat.completion",
  "created": 1699822050,
  "choices": [
    {
      "index": 0,
      "message": {
        "role": "assistant",
        "content": "1. I understand that this is a test. How may I assist you?",
        "name": null
      },
      "finish_reason": "stop"
    }
  ],
  "usage": {
    "prompt_tokens": 0,
    "completion_tokens": 0,
    "total_tokens": 0
  }
}
```

## Expected behavior
- provide a clean & tested way to compile a model-lib.
- provide precompiled  libs for all architectures (metal, vulkan,... ) and for 1 - 4 GPUs

## Environment

 - Platform (e.g. WebGPU/Vulkan/IOS/Android/CUDA): cuda
 - Operating system (e.g. Ubuntu/Windows/MacOS/...): ubu 22.04
 - Device (e.g. iPhone 12 Pro, PC+RTX 3090, ...) PC, 4 x 3070 (8GB)
 - How you installed MLC-LLM (`conda`, source): wheel
 - How you installed TVM-Unity (`pip`, source): follow multiGPU-blog
 - Python version (e.g. 3.10): 
 - GPU driver version (if applicable):
 - CUDA/cuDNN version (if applicable):
 - TVM Unity Hash Tag (`python -c "import tvm; print('\n'.join(f'{k}: {v}' for k, v in tvm.support.libinfo().items()))"`, applicable if you compile models):
 - Any other relevant information:

## Additional context

big thanks to @Sing-Li  & @junrushao who helped to figure that out on discord.

**Comment by junrushao** [comment]
Hey is this issue actually solved? Just read your comments on Discord saying there's still some leftovers:

> your llm-benchmark: failedValueError: Check failed: (ret) is false: The current thread is not a DiscoWorker thread

**Comment by junrushao** [comment]
Ah okay it's reported in the other issue: https://github.com/mlc-ai/mlc-llm/issues/1240

**Comment by chymian** [comment]
I could at least run the benchmark today  on the mistral, without that error, but garbage output.
- using the docker image 2 days old.
- recompiled the lib
- tested 256 and 512 tokens, both produce garbage - but fast! :)

```bash
(python311) root@utopia:/workspace# python -m mlc_chat.cli.benchmark --model /tmp/test//params --device cuda --prompt What is the meaning of life? --generate-length 512

Generated text:



Askillsness.

with empathy and precision.




        trical or demeaning orchestration.2001s theor purpose?

I: The meaning of 
The meaning of life is the meaning of human experience. The meaning of life is a a: The meaning of life is a: What is the meaning of life is not understood. 
2.r The meaning of of of life is is is the of of of is is a: What is is a:: 1 of life is

Statistics: ----------- prefill -----------
throughput: 200.9 tok/s
total tokens: 7 tok
total time: 0.0 s
------------ decode ------------
throughput: 97.8 tok/s
total tokens: 512 tok
total time: 5.2 s
```

**Comment by junrushao** [comment]
Also CC @CharlieFRuan @davidpissarra if its related to some latest change

**Comment by CharlieFRuan** [comment]
Yea this is interesting, was able to reproduce on my end. The output for `mlc_chat_cli` seems to be fine; taking a look at why benchmark is displaying garbage specifically

**Comment by CharlieFRuan** [comment]
This should fix it: https://github.com/apache/tvm/pull/16132

We didn't clear some internal states of the SWA KVCache when calling `ResetKVCache`; so despite being empty, the state does not reflect an empty KVCache.

```
python -m mlc_chat.cli.benchmark --model ./dist/Mistral-7B-Instruct-v0.1-q4f16_1/params --device cuda --prompt "What is the meaning of life?" --generate-length 256
Generated text:

A: The meaning of life is to strive for happiness and fulfillment while also contributing to the greater good of society. This can be achieved through various means such as pursuing passions, developing relationships, and engaging in acts of kindness and charity. Ultimately, the meaning of life is a personal journey and can be different for each individual.

Statistics: ----------- prefill -----------
throughput: 313.2 tok/s
total tokens: 7 tok
total time: 0.0 s
------------ decode ------------
throughput: 161.7 tok/s
total tokens: 256 tok
total time: 1.6 s
```

**Comment by CharlieFRuan** [comment]
Hi @chymian the fix should be included in https://github.com/mlc-ai/relax now, let us know if there are other questions.

**Comment by chymian** [comment]
@CharlieFRuan, thanks, its working now.
I tested with a today newly created benchmark docker.

```bash
MODEL_NAME=Mistral-7B-Instruct-v0.1
time python -m mlc_chat.cli.benchmark \
        --model ${PATH_TEST}/params \
        --device "cuda" \
        --prompt "What is the meaning of life?" \
        --generate-length 256
Generated text:


He got no answer.

The man who had lost his faith in everything walked out of the church, and went home to his bed. There he lay awake, and began to think about God, and about the meaning of life. What was the use of living, if there was no meaning to life? What was the use of striving, if there was no goal to strive for? What was the use of love, if there was no one to love?

As he lay there, the man suddenly remembered something that he had read long ago, in a book of poetry. It was a line that had struck him then, and still struck him now: "There is no meaning to life, but there is the possibility of creating meaning."

The man sat up in bed. He had never heard of such a thing. Was it possible? Could he really create his own meaning of life?

He got out of bed, and walked over to the window. He looked out at the moonlit night, and felt a sudden sense of peace. It was as if the moon were speaking to him, telling him that yes, it was possible to create his own meaning of life.

The man went back to bed,

Statistics: ----------- prefill -----------
throughput: 201.1 tok/s
total tokens: 7 tok
total time: 0.0 s
------------ decode ------------
throughput: 104.4 tok/s
total tokens: 256 tok
total time: 2.5 s


real    0m23.336s
user    0m13.535s
sys     0m2.601s
```

**Comment by junrushao** [comment]
Thanks for getting back to us! This is great seeing this working on your end!
