### ISSUE TITLE
[Model Request] RWKV v5 models, preferably for Android MLC Chat

### ISSUE THREAD

**Issue by MrCsabaToth** [mlc-ai/mlc-llm#1242]
## ⚙️  Request New Models

- Link to an existing implementation (e.g. Hugging Face/Github): https://github.com/BlinkDL/RWKV-LM
- Is this model architecture supported by MLC-LLM? Yes, but older Raven versions and not on Android by MLCChat

## Additional context

MLC Chat had trouble supporting other models than the preloaded configurations, needs to be solved as well, but first the modal would be great

**Comment by Hzfengsy** [comment]
@bbuf is working on it

**Comment by MasterJH5574** [comment]
I believe RWKV5 is already supported in our codebase and works for Android. You are welcome to try out :-)
