### ISSUE TITLE
[Bug] mlc_chat_cli  nightly does not work with Mistral 

### ISSUE THREAD

**Issue by Sing-Li** [mlc-ai/mlc-llm#1243]
## 🐛 Bug

While web llm and REST API seems to work fine.   `mlc_chat_cli` on the nightly seems to return totally irrelevant answers.   

## To Reproduce

1.  install nightly and run  `mlc_chat_cli`  with  `Mistral-7B-Instruct-v0.1`
1.  I also tried building the vulkan dll using   `--sliding-window 4096 --max-seq-len 4096` ; but same results
1.  send any prompt, the completion will be totally disconnected
1.  if you continue a few more times it may lockup the (Windows) system

```
Use model library: "D:\\allmy\\dev\\mlc-chat\\dist\\prebuilt\\lib\\Mistral-7B-Instruct-v0.1-q4f16_1-vulkan.dll"
You can use the following special commands:
  /help               print the special commands
  /exit               quit the cli
  /stats              print out the latest stats (token/sec)
  /reset              restart a fresh chat
  /reload [model]  reload model `model` from disk, or reload the current model if `model` is not specified

Loading model...
Loading finished
Running system prompts...
System prompts finished
[INST]: hello
[/INST]: 0.000056996.

This is not a fixed value, and in the order of magnitude, it is about the same as 5.6666666666666666.

## Answer (4)

The difference between 0.000056996 and 5.666666666666667 is that the first one is a positive number and the second one is a negative number.
```

## Expected behavior

Expected to work like webgpu  (web llm).

## Environment

 - Platform (e.g. WebGPU/Vulkan/IOS/Android/CUDA):  Vulkan
 - Operating system (e.g. Ubuntu/Windows/MacOS/...):  Windows 11
 - Device (e.g. iPhone 12 Pro, PC+RTX 3090, ...)   7900xtx
 - How you installed MLC-LLM (`conda`, source):  source
 - How you installed TVM-Unity (`pip`, source):   pip
 - Python version (e.g. 3.10):   3.11
 - GPU driver version (if applicable):
 - CUDA/cuDNN version (if applicable):
 - TVM Unity Hash Tag (`python -c "import tvm; print('\n'.join(f'{k}: {v}' for k, v in tvm.support.libinfo().items()))"`, applicable if you compile models):   GIT_COMMIT_HASH: 36aa05178e08793ae937071b3b99c69ed3e13686
 - Any other relevant information:

## Additional context

Ran webgpu    (web llm) on same machine with no problem at all.

**Comment by davidpissarra** [comment]
Thanks a lot for reporting this bug @Sing-Li! I tried to reproduce this issue on linux (on both cuda and vulkan), but on my end `Mistral-7B-Instruct-v0.1-q4f16_1` seems to give the desirable outputs with the latest nightly. Unfortunately, I didn't have the opportunity to test it on Windows, so it is possible this particular bug only occurs on Windows. A few questions:

- Does this bug still occur on the latest nightly?
- Have you tried different chuck size values? You can set chunk size with `--sliding-window-chuck-size`. You could perhaps check with a chunk size of 128. Does the same bug occurs?
- Have you experienced this bug on other platform or OS?

**Comment by Sing-Li** [comment]
Thanks @davidpissarra 

Yes, on Windows, it still happens:

```
mlc-chat>mlc_chat_cli --model Mistral-7B-Instruct-v0.1-q4f16_1
Use MLC config: "D:\\allmy\\dev\\mlc-chat\\dist\\prebuilt\\mlc-chat-Mistral-7B-Instruct-v0.1-q4f16_1\\mlc-chat-config.json"
Use model weights: "D:\\allmy\\dev\\mlc-chat\\dist\\prebuilt\\mlc-chat-Mistral-7B-Instruct-v0.1-q4f16_1\\ndarray-cache.json"
Use model library: "D:\\allmy\\dev\\mlc-chat\\dist\\prebuilt\\lib\\Mistral-7B-Instruct-v0.1-q4f16_1-vulkan.dll"
You can use the following special commands:
  /help               print the special commands
  /exit               quit the cli
  /stats              print out the latest stats (token/sec)
  /reset              restart a fresh chat
  /reload [model]  reload model `model` from disk, or reload the current model if `model` is not specified

Loading model...
Loading finished
Running system prompts...
System prompts finished
[INST]: what are the 50 states in the usa
[/INST]: 2. What is 252 minutes in milliseconds?
A. 40320000
[INST]: describe love in 5 lines
[/INST]: 0.068255000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
[INST]:
```

Do you mean I should build the library again with the `--sliding-window-chunk-size` option?

I can try on cuda121 linux.   Might you have the cuda.so lib available?

**Comment by davidpissarra** [comment]
Can you check if the following command works?

`cd /path/to/mlc-llm && python3 build.py --model /path/to/Mistral-7B-Instruct-v0.1 --quantization q4f16_1 --target cuda-multiarch --debug-dump --sliding-window 4096 --sliding-window-chunk-size 128`

I will make the mistral lib available in the meantime

**Comment by Sing-Li** [comment]
Thanks @davidpissarra 

Just to report interim.

On Windows, using the latest nightly,   and then building `vulkan.dll` with `--quantization q4f16_1 --target vulkan --sliding-window 2048 --sliding-window-chunk-size 128`   It worked!

```
mlc-chat>mlc_chat_cli --model Mistral-7B-Instruct-v0.1-q4f16_1
Use MLC config: "D:\\allmy\\dev\\mlc-chat\\dist\\prebuilt\\mlc-chat-Mistral-7B-Instruct-v0.1-q4f16_1\\mlc-chat-config.json"
Use model weights: "D:\\allmy\\dev\\mlc-chat\\dist\\prebuilt\\mlc-chat-Mistral-7B-Instruct-v0.1-q4f16_1\\ndarray-cache.json"
Use model library: "D:\\allmy\\dev\\mlc-chat\\dist\\prebuilt\\lib\\Mistral-7B-Instruct-v0.1-q4f16_1-vulkan.dll"
You can use the following special commands:
  /help               print the special commands
  /exit               quit the cli
  /stats              print out the latest stats (token/sec)
  /reset              restart a fresh chat
  /reload [model]  reload model `model` from disk, or reload the current model if `model` is not specified

Loading model...
Loading finished
Running system prompts...
System prompts finished
[INST]: what are the 50 states of the usa?
[/INST]: 1. Alabama
2. Alaska
3. Arizona
4. Arkansas
5. California
6. Colorado
7. Connecticut
8. Delaware
9. Florida
10. Georgia
11. Hawaii
12. Idaho
13. Illinois
14. Indiana
15. Iowa
16. Kansas
17. Kentucky
18. Louisiana
19. Maine
20. Maryland
21. Massachusetts
22. Michigan
23. Minnesota
24. Mississippi
25. Missouri
26. Montana
27. Nebraska
28. Nevada
29. New Hampshire
30. New Jersey
31. New Mexico
32. New York
33. North Carolina
34. North Dakota
35. Ohio
36. Oklahoma
37. Oregon
38. Pennsylvania
39. Rhode Island
40. South Carolina
41. South Dakota
42. Tennessee
43. Texas
44. Utah
45. Vermont
46. Virginia
47. Washington
48. West Virginia
49. Wisconsin
50. Wyoming
[INST]: describe love in 10 lines
[/INST]: 1. Love is a deep affection towards someone or something, often characterized by strong feelings of attachment and devotion.
2. It is a positive emotion that can inspire great joy and happiness.
3. Love can be expressed in various forms, such as romantic love, familial love, or love for friends.
4. It is a powerful force that can overcome obstacles and challenges.
5. Love can bring about significant personal growth and transformation.
6. It is a fundamental aspect of human experience and relationships.
7. Love can be a source of comfort and support during difficult times.
8. It is a complex emotion that can be both intense and gentle.
9. Love can be experienced in different ways by different people.
10. It is a powerful and transformative emotion that can shape our lives in profound ways.
[INST]:
```

I'll test cuda once the lib is ready, thanks.

**Comment by davidpissarra** [comment]
Just uploaded a Mistral cuda lib with SW=4k CS=128 https://github.com/mlc-ai/binary-mlc-llm-libs/blob/main/Mistral-7B-Instruct-v0.1-q4f16_1-sw4096_cs128-cuda.so (around 4.8gb VRAM usage)

**Comment by Sing-Li** [comment]
Thanks @davidpissarra     cuda worked fine as well.  About same token rate as Llama 2 7b       👏
