### ISSUE TITLE
Add new available models

### ISSUE THREAD

**Issue by Henevy-HDR** [mlc-ai/mlc-llm#125]

**Comment by GameOverFlowChart** [comment]
Mpt 7B Chat is very interesting right now. Unfortunately I don't have the hardware or knowledge to compile it so that it can be used with mlcchat. Things are evolving fast right now.

**Comment by Kathryn-cat** [comment]
Hi, I think there's a PR #460 on adding MPT 7B models. Please let us know if you have any further questions.
