### ISSUE TITLE
[Doc]  *bug* conflicting docs after switching solver to libmamba-solver

### ISSUE THREAD

**Issue by Sing-Li** [mlc-ai/mlc-llm#1255]
### Bug

Latest doc suggests config `libmamba-solver` instead of `classic` for speed -up  https://llm.mlc.ai/docs/install/conda.html

BUT once that's switched,  the `mlc_chat_cli` from prebuilt no longer works.   It keeps insisting on reverting to `classic`.

https://llm.mlc.ai/docs/deploy/cli.html

**Comment by junrushao** [comment]
Well, this is a bummer...Which OS are you using btw? I'd love to test if I could reproduce this issue

**Comment by Sing-Li** [comment]
I am on Windows.   But cannot reproduce the problem today 😞    Closing the issue.  Thanks.
