### ISSUE TITLE
[Feature Request]  Support ROCM/MIOPEN codegen

### ISSUE THREAD

**Issue by lhcalibur** [mlc-ai/mlc-llm#1257]
## 🚀 Feature
Support ROCM/MIOPEN codegen

## Motivation

Speedup model  that runs on AMD GPU

## Alternatives

Maybe consider using MIGraphX as an alternative for ROCM/MIOPEN

**Comment by junrushao** [comment]
ROCm is already supported. Either MIGraphX or MIOpen could be helpful for non LLM usecases, but we haven't seen much benefit so far
