### ISSUE TITLE
[Bug] - mlc-chat-python does not use AMD Vulkan GPU properly, where as C++ mlc_chat_cli works on the same hardware.

### ISSUE THREAD

**Issue by BenjaminGittins** [mlc-ai/mlc-llm#1259]
## 🐛 Bug

I have vulkan driver for 16Giabyte AMD Radeon 7800xt GPU  installed on Debian Linux 12.  

The C++ implementation of MLC:  `mlc_chat_cli` works without any problems.  So the problem is not with my Vulkan Driver, or with Debian. 

However the Python REST API implementation fails to use Vulkan. And when it tries to use Vulkan it throws the error message: 

[19:59:07] /workspace/tvm/src/runtime/memory/pooled_allocator.h:65: Warning: PooledAllocator got InternalError during allocation: InternalError: Check failed: (__e == VK_SUCCESS) is false: Vulkan Error, code=-2: VK_ERROR_OUT_OF_DEVICE_MEMORY
[19:59:07] /workspace/tvm/src/runtime/memory/pooled_allocator.h:66: Warning: Trying to release all unused memory and reallocate...
Aborted (core dumped)

I am using `radeontop` to monitor GPU memory usage. I can see that the C++ command line version of `mcl_chat_cli` allocates GPU memory. However, no memory is ever allocated by `mlc-chat-python`. 

## To Reproduce

1. `conda create -n mlc-chat-python`
2. `conda activate mlc-chat-python`
3. `python3 -m pip install --pre -U -f https://mlc.ai/wheels mlc-chat-nightly mlc-ai-nightly`
4. `python -m mlc_chat.rest --model Llama-2-13b-chat-hf-q4f16_1 --device vulkan`
5.  Error message is generated.

## Expected behavior

It should not crash, and the REST API should work. 

## Environment

 - Platform : Vulkan 
 - Operating system: Debian 12
 - Device: 
      - Intel® Core™ i7-6700K 
 - GPU:
       - AMD Radeon™ RX 6800 XT Mesa
       -  Intel® HD Graphics 530 (SKL GT2)
 - How you installed MLC-LLM (`conda`, source):
     -       python3 -m pip install --pre -U -f https://mlc.ai/wheels mlc-chat-nightly mlc-ai-nightly
 - How you installed TVM-Unity (`pip`, source):
     -  I didn't compile from soruce. 
 - Python version (e.g. 3.10):  3.11.5

 - GPU driver version (if applicable):
    libdrm-amdgpu1/stable,now 2.4.114-1+b1 amd64 [installed,automatic]
   ricks-amdgpu-utils/stable 3.8.0-1 all
   xserver-xorg-video-amdgpu/stable,now 23.0.0-1 amd64 [installed,automatic]
    libvulkan-dev/stable 1.3.239.0-1 amd64
    libvulkan-volk-dev/stable 1.3.239.0-1 all
    libvulkan1/stable,now 1.3.239.0-1 amd64 [installed,automatic]
    mesa-vulkan-drivers/stable,now 22.3.6-1+deb12u1 amd64 [installed,automatic]
    vulkan-tools/stable,now 1.3.239.0+dfsg1-1 amd64 [installed]

 - CUDA/cuDNN version (if applicable):
N/A

 - TVM Unity Hash Tag (`python -c "import tvm; print('\n'.join(f'{k}: {v}' for k, v in tvm.support.libinfo().items()))"`, applicable if you compile models): N/a
 - Any other relevant information:

**Comment by junrushao** [comment]
Interesting. I didn’t expect there’s any difference in the memory being allocated. To help us better understand this issue, would you mind sharing if the Python API works without REST API?

Instructions: tab Python in https://llm.mlc.ai/docs/

**Comment by junrushao** [comment]
Interesting. I didn’t expect there’s any difference in the memory being allocated. To help us better understand this issue, would you mind sharing if the Python API works without REST API?

Instructions: tab Python in https://llm.mlc.ai/docs/

**Comment by BenjaminGittins** [comment]
I'm sorry for the delay.  i've had to rebuild my machine for other unrelated reasons. I will have to try MLC again maybe some time next year. I really like the work your doing, and I hope it continues to grow and mature. :)

**Comment by tqchen** [comment]
please try out the latest instructions in https://github.com/mlc-ai/mlc-llm/pull/2095 Specifically you need to conda install gcc and libvulkan-loader in your env
