### ISSUE TITLE
[Feature Request] Add extended virtual addressing entitlement to iOS app

### ISSUE THREAD

**Issue by SForeKeeper** [mlc-ai/mlc-llm#1260]
## 🚀 Feature
Adding `com.apple.developer.kernel.extended-virtual-addressing` to iOS app entitlements could allow the app to allocate more space for gpu inference. It is worth noting that the virtual addressing entitlement is for registered dev program users only, so I'd suggest that only the official app adapts this entitlement.

## Motivation
Currently in `ios/MLCChat/MLCChat.entitlements` there's the `com.apple.developer.kernel.increased-memory-limit` entitlement. However it would still cause a crash when running larger models on devices with 16GB of memory (such as iPad Pros models with more than 1/2 TBs of memory).

## Alternatives
There's no alternative to the best of my knowledge.

**Comment by junrushao** [comment]
This is definitely an interesting feature. I was wondering how this is implemented under the hood? Is this like swap memory that offloads some weights on disk? Thanks a lot!

**Comment by SForeKeeper** [comment]
> This is definitely an interesting feature. I was wondering how this is implemented under the hood? Is this like swap memory that offloads some weights on disk? Thanks a lot!

It seems the XNU kernel would enable Jumbo mode for apps with this entitlement. [xnu src](https://github.com/apple-oss-distributions/xnu/blob/xnu-7195.141.2//bsd/kern/kern_exec.c#L2930-L2932) 

I can't test it at this moment because I am not registered to Apple developer program, but according to sources it would allow about 12 GB of ram to be allocated for a single program for the iPad Pro models with 16 GB of ram. With only the `com.apple.developer.kernel.increased-memory-limit` entitlement it would be around 8 GB, and 5 GB for no entitlement at all. 
For any other iOS devices the improvement is expected to be marginal.

**Comment by tqchen** [comment]
This is added to the latest app. Note: seems it only helps the MacBook but not iPhone

**Comment by SForeKeeper** [comment]
> This is added to the latest app. Note: seems it only helps the MacBook but not iPhone

I could test it if it benefits the iPad pros with 16GBs of memory, but "Add model" was dropped and it seems current models don't need that much of memory. I can't compile and test it on my own because it would require a dev program account to use the specific entitlement.

**Comment by tqchen** [comment]
We temporarily disabled the add model since it requires quite a bit of restrictions in what models being supported, we will evaluate possible ways to add it back more robustly.
