### ISSUE TITLE
[Bug]  PIP install failure is not a supported wheel on this platform.

### ISSUE THREAD

**Issue by EzioZz** [mlc-ai/mlc-llm#1281]
## To Reproduce
in docker environment
trying to pip install offline and download wheel from https://[mlc.ai/wheels](https://mlc.ai/wheels)
pip install failure
`
root@xcdl220338:~/workspace/mlc-llm# pip install --pre --force-reinstall mlc_ai_nightly_rocm56-0.12.dev1832-cp38-cp38-manylinux_2_28_x86_64.whl 

ERROR: mlc_ai_nightly_rocm56-0.12.dev1832-cp38-cp38-manylinux_2_28_x86_64.whl is not a supported wheel on this platform.

`

## Environment

 - Platform ROCM
 - Operating system  ubuntu20
 - Device ROCM5.6
 - Python version 3.8
 - in docker environment

**Comment by junrushao** [comment]
The pip wheel we provided is based on a relatively new format [`manylinux_2_28`](https://github.com/pypa/manylinux/issues/1282), which requires the latest `pip` and potentially glibc. How about upgrading `pip` and try again?

**Comment by EzioZz** [comment]
thx, upgrade pip will solve this error.
