### ISSUE TITLE
Computing Perplexity of MLC LLMs

### ISSUE THREAD

**Issue by touqir14** [mlc-ai/mlc-llm#1282]
## ❓ General Questions

Is there a way to compute the perplexity of MLC LLMs? I wanted to evaluate the `mlc-chat-RedPajama-INCITE-Chat-3B-v1-q4f16_1` model and my runtime is Cuda. From what I understand, the chat_module provides API for only response generation. Is there any way to access the loss value to compute the perplexity? 

If not, is there a way to wrap the model as a huggingface model (from where perplexity can be computed)? 

Also, please let me know if you have any evaluation that highlight the performance loss when comparing this model with its non-quantized version. Thanks a lot!

**Comment by junrushao** [comment]
Indeed this is something interesting and we wanted to do in the near future. Not limited to perplexity but also include other metrics.

For now, you may safely assume the quantization we are using is identical to llama.cpp’s group quantization with group size = 32.

**Comment by tqchen** [comment]
we are moving towards OpenAI api which coems with logprob support that can be used for this goal
