### ISSUE TITLE
[Bug] Pytest not working

### ISSUE THREAD

**Issue by musram** [mlc-ai/mlc-llm#1288]
## 🐛 Bug
pytest not executing the tests.

## To Reproduce

1. pytest (on command line). Using venv.
2. was getting error "Defining 'pytest_plugins' in a non-top-level conftest is no longer supported:
It affects the entire test suite instead of just below the conftest as expected.
  /home/munusairam/softwares/programs/mlc-llm/3rdparty/tvm/conftest.py
Please move it to a top level conftest file at the rootdir:
  /home/munusairam/softwares/programs/mlc-llm"
so added  
[tool.pytest.ini_options]
minversion = "6.0"
testpaths = "tests/python/model/"     to pyproject.toml

3. Changed export PYTHONPATH=/home/munusairam/softwares/programs/mlc-llm/:$PYTHONPATH  but still not working
4. able to import tests

1.

platform linux -- Python 3.11.5, pytest-7.4.3, pluggy-1.3.0
rootdir: /home/munusairam/softwares/programs/mlc-llm
configfile: pyproject.toml
testpaths: tests/python/model/
collected 0 items / 3 errors                                                                                                                       

====================================================================== ERRORS ======================================================================
________________________________________________ ERROR collecting tests/python/model/test_llama.py _________________________________________________
ImportError while importing test module '/home/munusairam/softwares/programs/mlc-llm/tests/python/model/test_llama.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/lib/python3.11/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/python/model/test_llama.py:4: in <module>
    from mlc_chat.compiler import MODEL_PRESETS, MODELS
E   ModuleNotFoundError: No module named 'mlc_chat'
__________________________________________ ERROR collecting tests/python/model/test_llama_quantization.py __________________________________________
ImportError while importing test module '/home/munusairam/softwares/programs/mlc-llm/tests/python/model/test_llama_quantization.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/lib/python3.11/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/python/model/test_llama_quantization.py:4: in <module>
    from mlc_chat.compiler import MODEL_PRESETS, MODELS, QUANTIZATION
E   ModuleNotFoundError: No module named 'mlc_chat'
_______________________________________________ ERROR collecting tests/python/model/test_mistral.py ________________________________________________
ImportError while importing test module '/home/munusairam/softwares/programs/mlc-llm/tests/python/model/test_mistral.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/lib/python3.11/importlib/__init__.py:126: in import_module

## Expected behavior

pytest should have run all the tests.

## Environment

 - Operating system (e.g.Arch linux):
 - How you installed MLC-LLM ( source):
 - How you installed TVM-Unity (`pip`):
 - Python version (e.g. 3.11):

**Comment by junrushao** [comment]
> E ModuleNotFoundError: No module named 'mlc_chat'

it’s just because you don’t put “python/mlc_chat” directory into PYTHONPATH

**Comment by musram** [comment]
Thanks @junrushao
