### ISSUE TITLE
[iOS] - `dolly-v2-3b` missing tokenizer?

### ISSUE THREAD

**Issue by terryworona** [mlc-ai/mlc-llm#129]
I asked this question as a followup to a previous [issue](https://github.com/mlc-ai/mlc-llm/issues/116) (now closed). Apologies for the duplication - just wanted to make sure it gets visibility. 

I'm able to build the `dolly-v2-3b` model. However, I'm missing the `tokenizer.model` - see blocker @ bottom. 

### Get Model

```
$ git lfs install && git clone https://huggingface.co/databricks/dolly-v2-3b
```

### Link Model 

```
$ cd relax
$ mkdir -p dist/models 
$ ln -s /Users/me/Desktop/dolly-v2-3b dist/models/dolly-v2-3b 
```

### Build Model

```
$ git clone https://github.com/mlc-ai/mlc-llm.git --recursive
$ cd mlc-llm
$ python3 build.py --model dolly-v2-3b --dtype float16 --target iphone --quantization-mode int3 --quantization-sym --quantization-storage-nbit 16 --max-seq-len 768
```

### Output

```
/Users/me/Development/llm/relax/src/runtime/metal/metal_device_api.mm:165: Intializing Metal device 0, name=Apple M1 Max
Finish exporting to dist/dolly-v2-3b/float16/dolly-v2-3b_iphone_float16.a
```

### Mobile Integration

As per the [instructions](https://github.com/mlc-ai/mlc-llm/tree/main/ios) in the `ios` repo:

```
$ cd ios
$ ./prepare_libs.sh
```

**Note**: I had to change the last line of `prepare_libs.sh` to point to the dolly model (it was _hardcoded_ for `vicuna-v1-7b`)

```
cp ../dist/dolly-v2-3b/float16/dolly-v2-3b_iphone_float16.a build/lib/libmodel_iphone.a
```

The script seemed to complete successfully, so I ran the next one:

```
$ ./prepare_params.sh
```

**Note**: this script too, has `vicuna-v1-7b` hardcoded, so I went to update it to the point to the `dolly-v2-3b` path, but this is where I got stuck. 

The path `../dist/models/*` does not exist, I'm not sure where to find the `tokenizer.model`? The `params` are available however via `../dist/dolly-v2-3b/float16/params`. Screenshot attached. 

Any help would be appreciated. Thanks! 

![237529093-fc899792-67e4-49d9-ae1e-04cbf82b086b](https://github.com/mlc-ai/mlc-llm/assets/358709/31a875fe-4358-4041-b995-e20361ee475a)

**Comment by yzh119** [comment]
Currently the ios building script only recognizes `tokenizer.model` which is not the tokenizer format used in Dolly.
You can change the `tokenizer.model` this line:
https://github.com/mlc-ai/mlc-llm/blob/9a3e3c7794f546ea47488e815335cac65b16a1b2/ios/MLCChat/LLMChat.mm#L31
to `tokenizer.json` for Dolly.

@junrushao will update the complete scripts for building Dolly.

**Comment by terryworona** [comment]
Thanks for the help @yzh119 - updating the `tokenizer_path` did work:

```
std::string tokenizer_path = bundle_path + "/dist/tokenizer.json";
```

I noticed via `LLMChat.mm`, that the `model` and `conv_template` properties are hardcoded to `vircuna` and `vicuna_v1.1` respectively:

```
std::string model = "vircuna";
std::string conv_template = "vicuna_v1.1";
```

_Do these matter in any way, or is it just a namespace thing? Should they be updated to point to dolly?_

On another note, I'm running `dolly-v2-3b` on a iPad Pro M1, two observations:
1. Latency is quite long - it can take several minutes to stream a response. _Is this typical for an M1 device?_
2. Most output makes no sense at all - see attachment of a few simple prompts. I find that occasionally the answer is correct, but it's surrounded by a bunch of irrelevant/erroneous content. The model never seems to stop streaming - most prompts go on forever - oftentimes in loops (see second example, where it repeatedly gets stuck streaming "_mix, mix, mix.._."). _Is this the expected performance of Dolly, or is something somehow misconfigured?_ 

<img width="1044" alt="dolly-output" src="https://github.com/mlc-ai/mlc-llm/assets/358709/96bcfa11-4f1c-461b-b75d-42fe7379f985">
