### ISSUE TITLE
[Bug][CI] Check out from version control fails

### ISSUE THREAD

**Issue by davidpissarra** [mlc-ai/mlc-llm#1298]
## 🐛 Bug

I have noticed Jenkins is now being used for the CI (as of #1292). In one of my PRs (#1280) it keeps failing on the checkout step, despite passing on all github actions. It seems that it randomly breaks in some of the tests (if I try to rerun it even may break in different tests). I wonder if this could be a concurrency issue with different jobs trying to checkout in parallel and eventually some will break.

Example: https://ci.mlc.ai/blue/organizations/jenkins/mlc-llm/detail/PR-1280/8/pipeline/11/

cc @Hzfengsy @junrushao

**Comment by junrushao** [comment]
https://github.com/mlc-ai/mlc-llm/pull/1299 Ruihang submitted a fix

**Comment by junrushao** [comment]
But still doesn’t seem to fix this issue @MasterJH5574

**Comment by MasterJH5574** [comment]
@davidpissarra Would you like to do a rebase for #1280 to incorporate the fix?

**Comment by MasterJH5574** [comment]
Ah wait a minute, it indeed does not seem to fix perfectly.. The main branch is failed.

**Comment by davidpissarra** [comment]
It seems to work on my end now @MasterJH5574

**Comment by MasterJH5574** [comment]
Ah great @davidpissarra. I also reran the task on main branch and it passed.
