### ISSUE TITLE
Works like a charm ! 

### ISSUE THREAD

**Issue by dbddv01** [mlc-ai/mlc-llm#13]
Just wanted to report that this works perfect on my gtx1060 (6gb) on my old i5-7200 16gb ram under win10. So far, i never reached such a speed  with all other existing solution ( oobabooga, textsynth, llama.cpp). No single issue during install. I can't tell exactly but it's surely a couple of tokens / sec during inference. Need more deep dive to get a feeling of quality as it seems to be quantized model in int3 ? 
Now, we want more : more models, 13b size, parameter access (temp, topp etc) and api. Anyway, i think this is great work already ! 
![image](https://user-images.githubusercontent.com/39023861/235347457-b4f946ef-f0bf-4584-920c-065c60ff64e4.png)

**Comment by junrushao** [comment]
Thank you for sharing the information! We are currently gathering data points on runnable devices and their speed. Would you be willing to assist us in this effort by sharing the tokens/sec data on your GTX 1060?

**Comment by dbddv01** [comment]
I have no tools to measure it. So i handle it manually. I prompted 'please produce 500 tokens story of starwars' then copy pasted the text produced to count the tokens using the https://platform.openai.com/tokenizer and my stopwatch. 
i have following results. 
673 tokens in 50 sec : 13,46 t/sec
318 tokens in 25 sec : 12,72 t/sec
256 tokens in 23 sec : 11,13 t/sec


by the way, i noticed : 
Usage: mlc_chat [--help] [--version] [--device-name VAR] [--artifact-path VAR] [--model VAR] [--dtype VAR] [--params VAR] [--evaluate]

Optional arguments:
  -h, --help            shows help message and exits
  -v, --version         prints version information and exits
  --device-name         [default: "auto"]
  --artifact-path       [default: "dist"]
  --model               [default: "vicuna-v1-7b"]
  --dtype               [default: "auto"]
  --params              [default: "auto"]
  --evaluate

Is it just a matter of documentation that we would be able to already play with the arguments ?

**Comment by junrushao** [comment]
Hey thanks for the data! This is super valuable to us!

We updated `mlc_chat_cli` [this morning](https://github.com/mlc-ai/mlc-llm/pull/14) to include a command `\stats`. Would you mind if you updated the conda environment to include this change? Thanks a bunch!

**Comment by dbddv01** [comment]
Ok thx !  now with the /stats. 

USER: /stats
**encode: 35.4 tok/s, decode: 16.7 tok/s**
USER: continue
ASSISTANT: In this epic (... removed ...)
USER: /stats
**encode: 11.1 tok/s, decode: 14.0 tok/s**
USER: continue
ASSISTANT: Sure, here's the continuation:
 (... removed ...)
USER: /stats
**encode: 37.7 tok/s, decode: 17.0 tok/s**

**Comment by junrushao** [comment]
Thanks a lot for your swift response! The data is super valuable to us!
