### ISSUE TITLE
[Bug] REST API  streaming completion does not issue `data: [DONE]` 

### ISSUE THREAD

**Issue by Sing-Li** [mlc-ai/mlc-llm#1300]
## 🐛 Bug

Unlike OpenAI's streaming completion, the REST API in MLC AI does not issue a final line with `data: [DONE]` at the end of the streamed tokens.

This causes many applications that depends on in-stream-termination to fail.    Especially web apps running in browser that may have limitations on catching the stream closing from server.  

## To Reproduce

Make a streaming completion REST API call.  Log the streamed events/deltas.   No end `data: [DONE]` event received. 

All our examples depend on the stream being closed on the server end to terminate the stream.

## Expected behavior

The last event/delta generated from the completion should be `data: [DONE]` as documented in OpenAI docs.

See  **Additional context** section for reference.

## Environment

 - Platform (e.g. WebGPU/Vulkan/IOS/Android/CUDA): all
 - Operating system (e.g. Ubuntu/Windows/MacOS/...): all
 - Device (e.g. iPhone 12 Pro, PC+RTX 3090, ...) all
 - How you installed MLC-LLM (`conda`, source): conda
 - How you installed TVM-Unity (`pip`, source): pip
 - Python version (e.g. 3.10): 3.10
 - GPU driver version (if applicable):
 - CUDA/cuDNN version (if applicable):
 - TVM Unity Hash Tag (`python -c "import tvm; print('\n'.join(f'{k}: {v}' for k, v in tvm.support.libinfo().items()))"`, applicable if you compile models):
 - Any other relevant information:

## Additional context

See OpenAI documentation here -->  https://platform.openai.com/docs/api-reference/chat/create

![image](https://github.com/mlc-ai/mlc-llm/assets/122633/73d8aac6-2587-42c3-9e57-a5e4a27ab8ae)

**Comment by junrushao** [comment]
This is a problem we need to fix. CC @MasterJH5574

**Comment by junrushao** [comment]
Also CC @sudeepag

**Comment by Sing-Li** [comment]
Also CC @Kartik14
