### ISSUE TITLE
[Bug] Mistral-7B-Instruct-v0.1-q3f16_1 does not work successfully on ios and android

### ISSUE THREAD

**Issue by MrJungle1** [mlc-ai/mlc-llm#1301]
## 🐛 Bug

Mistral-7B-Instruct-v0.1-q3f16_1 does not work successfully on ios and android
## To Reproduce

1. Compile a Mistral-7B-Instruct-v0.1-q3f16_1 model via MLC
1. Build Auxiliary Components
1. Build Apps with MLC Swift API

On ios the iphone freezes, the screen will be black and you need to restart the phone. On Android, the MLCChat software will crash.
## Expected behavior
Mistral-7B-Instruct-v0.1-q3f16_1 work successfully on ios and android

## Environment

 - Platform (IOS/Android):
 - Operating system (MacOS):
 - Device (iPhone 15 Pro Max, iQOO11)
 - How you installed MLC-LLM ( source):
 - How you installed TVM-Unity ( source):
 - Python version (3.10):
 - GPU driver version (None):
 - CUDA/cuDNN version (None):
 - TVM Unity Hash Tag (36aa05178e08793ae937071b3b99c69ed3e13686):
 - Any other relevant information:

**Comment by CharlieFRuan** [comment]
Hi, thanks for raising the issue! Mistral support on iOS is a current WIP, please stay tuned.

**Comment by junrushao** [comment]
For more information: https://github.com/mlc-ai/mlc-llm/issues/991#issuecomment-1822228731

**Comment by MrJungle1** [comment]
@CharlieFRuan @junrushao Thanks for your reply，LGTM!

**Comment by davidpissarra** [comment]
MIstral support on iOS: #1320

**Comment by CharlieFRuan** [comment]
Closing this one for now. Feel free to open another one if there are further issues. Thanks!
