### ISSUE TITLE
[Question][Android] Issues with Create Android Project using Compiled Models 

### ISSUE THREAD

**Issue by drahmad89** [mlc-ai/mlc-llm#1302]
I am trying to create android project on window 10. When trying to run prepare.sh I am getting the following issue:

+ cd build
+ touch config.cmake
+ echo 'set(TVM_HOME C:\Users\chaahm\Documents\mlc-llm-main\3rdparty\tvm\include\tvm\runtime)'
+ cmake .. -DCMAKE_BUILD_TYPE=Release '-DCMAKE_TOOLCHAIN_FILE=C:\Users\chaahm\AppData\Local\Android\Sdk\ndk\26.1.10909125/build/cmake/android.toolchain.cmake' -DCMAKE_INSTALL_PREFIX=. -DCMAKE_CXX_FLAGS=-O3 -DANDROID_ABI=arm64-v8a -DANDROID_NATIVE_API_LEVEL=android-24 -DANDROID_PLATFORM=android-24 -DCMAKE_FIND_ROOT_PATH_MODE_PACKAGE=ON -DANDROID_STL=c++_static -DUSE_HEXAGON_SDK=OFF -DMLC_LLM_INSTALL_STATIC_LIB=ON -DCMAKE_SKIP_INSTALL_ALL_DEPENDENCY=ON -DUSE_OPENCL=ON -DUSE_CUSTOM_LOGGING=ON
CMake Error at CMakeLists.txt:3 (project):
  Running

   'nmake' '-?'

  failed with:

   no such file or directory

Can anyone help me? 

Thanks

**Comment by junrushao** [comment]
Could you share the full logs? Given it fails with "no such file or directory", I'd love to see what is missing exactly

**Comment by drahmad89** [comment]
$ ./prepare_libs.sh
+ rustup target add aarch64-linux-android
info: component 'rust-std' for target 'aarch64-linux-android' is up to date
+ cd build
+ touch config.cmake
+ '[' 'C:\Doc\Android\Innovation_Technologique\ArxVision\mlc-llm\3rdparty\tvm\include\tvm\runtime' -ne 0 ']'
./prepare_libs.sh: line 12: [: C:\Doc\Android\Innovation_Technologique\ArxVision\mlc-llm\3rdparty\tvm\include\tvm\runtime: integer expression expected
+ cmake .. -DCMAKE_BUILD_TYPE=Release '-DCMAKE_TOOLCHAIN_FILE=C:\Development\adt-bundle-windows-x86_64-20131030\sdk\ndk\26.0.10792818/build/cmake/android.tooL_PREFIX=. -DCMAKE_CXX_FLAGS=-O3 -DANDROID_ABI=arm64-v8a -DANDROID_NATIVE_API_LEVEL=android-24 -DANDROID_PLATFORM=android-24 -DCMAKE_FIND_ROOT_PATH_MODE_PACKtic -DUSE_HEXAGON_SDK=OFF -DMLC_LLM_INSTALL_STATIC_LIB=ON -DCMAKE_SKIP_INSTALL_ALL_DEPENDENCY=ON -DUSE_OPENCL=ON -DUSE_CUSTOM_LOGGING=ON
CMake Error at CMakeLists.txt:3 (project):
  Generator
 
    Visual Studio 15 2017
 
  could not find specified instance of Visual Studio:
 
    C:/Program Files (x86)/Microsoft Visual Studio/2017/Professional
 
 
-- Configuring incomplete, errors occurred!

**Comment by zilong-dy** [comment]
but even so, have fixed the nmake error, I meet another error, anyone can help ?

(mlc-llm) PS D:\project\ai\llm\MLC-LLM\download\mlc-llm\android> .\prepare_libs.sh
(mlc-llm) PS D:\project\ai\llm\MLC-LLM\download\mlc-llm\android> sh .\prepare_libs.sh
+ rustup target add aarch64-linux-android
info: component 'rust-std' for target 'aarch64-linux-android' is up to date
+ mkdir -p build/model_lib
+ python prepare_model_lib.py
Creating lib from ['D:\\project\\ai\\llm\\MLC-LLM\\download\\mlc-llm\\dist\\Llama-2-7b-chat-hf-q4f16_1\\Llama-2-7b-chat-hf-q4f16_1-android.tar']..
+ cd build
+ touch config.cmake
+ '[' 'D:\project\ai\llm\MLC-LLM\download\mlc-llm\3rdparty\tvm' -ne 0 ']'
.\prepare_libs.sh: line 13: [: D:\project\ai\llm\MLC-LLM\download\mlc-llm\3rdparty\tvm: integer expression expected
+ cmake .. -DCMAKE_BUILD_TYPE=Release '-DCMAKE_TOOLCHAIN_FILE=D:\android-sdk\ndk\26.1.10909125/build/cmake/android.toolchain.cmake' -DCMAKE_INSTALL_PREFIX=. -DCMAKE_CXX_FLAGS=-O3 -DANDROID_ABI=arm64-v8a -DANDROID_NATIVE_API_LEVEL=android-24 -DANDROID_PLATFORM=android-24 -DCMAKE_FIND_ROOT_PATH_MODE_PACKAGE=ON -DANDROID_STL=c++_static -DUSE_HEXAGON_SDK=OFF -DMLC_LLM_INSTALL_STATIC_LIB=ON -DCMAKE_SKIP_INSTALL_ALL_DEPENDENCY=ON -DUSE_OPENCL=ON -DUSE_CUSTOM_LOGGING=ON
-- Building for: Visual Studio 17 2022
CMake Error at CMakeLists.txt:3 (project):
  Failed to run MSBuild command:

    D:/Program Files/VisualStudio/install/MSBuild/Current/Bin/amd64/MSBuild.exe

  to get the value of VCTargetsPath:

    MSBuild version 17.8.3+195e7f5a3 for .NET Framework
    Build started 11/27/2023 10:34:29 PM.

    Project "D:\project\ai\llm\MLC-LLM\download\mlc-llm\android\build\CMakeFiles\3.22.1-g37088a8-dirty\VCTargetsPath.vcxproj" on node 1 (default targets).
    D:\Program Files\VisualStudio\install\MSBuild\Current\Bin\amd64\Microsoft.Common.CurrentVersion.targets(832,5): error : The BaseOutputPath/OutputPath property is not set for project 'VCTargetsPath.vcxproj'.  Please check to make sure that you have specified a valid combination of Configuration and Platform for this project.  Configuration='Debug'  Platform='x64'.  You may be seeing this message because you are trying to build a project without a solution file, and have specified a non-default Configuration or Platform that doesn't exist for this project. [D:\project\ai\llm\MLC-LLM\download\mlc-llm\android\build\CMakeFiles\3.22.1-g37088a8-dirty\VCTargetsPath.vcxproj]
    Done Building Project "D:\project\ai\llm\MLC-LLM\download\mlc-llm\android\build\CMakeFiles\3.22.1-g37088a8-dirty\VCTargetsPath.vcxproj" (default targets) -- FAILED.

    Build FAILED.

    "D:\project\ai\llm\MLC-LLM\download\mlc-llm\android\build\CMakeFiles\3.22.1-g37088a8-dirty\VCTargetsPath.vcxproj" (default target) (1) ->
    (_CheckForInvalidConfigurationAndPlatform target) ->
      D:\Program Files\VisualStudio\install\MSBuild\Current\Bin\amd64\Microsoft.Common.CurrentVersion.targets(832,5): error : The BaseOutputPath/OutputPath property is not set for project 'VCTargetsPath.vcxproj'.  Please check to make sure that you have specified a valid combination of Configuration and Platform for this project.  Configuration='Debug'  Platform='x64'.  You may be seeing this message because you are trying to build a project without a solution file, and have specified a non-default Configuration or Platform that doesn't exist for this project. [D:\project\ai\llm\MLC-LLM\download\mlc-llm\android\build\CMakeFiles\3.22.1-g37088a8-dirty\VCTargetsPath.vcxproj]

        0 Warning(s)
        1 Error(s)

    Time Elapsed 00:00:01.52


  Exit code: 1



-- Configuring incomplete, errors occurred!

**Comment by fanchb** [comment]
Hi,

I did the same procedure than zilong-dy and got exactly the same error than him.

Since we need to set environment variables like ANDROID_NDK and TVM_NDK_CC pointing to the Android toolchain, why would be Visual Studio environment tools be involved here? We are building for the Android target, right?

Thank you for your help!

**Comment by tqchen** [comment]
likely you don;t want visual studio being involved, instead, it should involve android toolchain. Consolidate to https://github.com/mlc-ai/mlc-llm/issues/1337 which also have some updated comments
