### ISSUE TITLE
Purpose of mlc_chat compiler

### ISSUE THREAD

**Issue by brian-pieces** [mlc-ai/mlc-llm#1306]
## ❓ General Questions

I was looking through the repo and I'm confused about why there are two Llama implementations: a Relax [model](https://github.com/mlc-ai/mlc-llm/blob/main/mlc_llm/relax_model/llama.py) and a seemingly higher-level nn.Module-based [definition](https://github.com/mlc-ai/mlc-llm/blob/main/python/mlc_chat/compiler/model/llama/llama_model.py). 

I saw the [PR](https://github.com/mlc-ai/mlc-llm/pull/1082) but I still don't fully understand what its purpose is and why it rquires a second model definition.  Some clarification would be much appreciated, thanks!

**Comment by junrushao** [comment]
Thanks for asking! This is going to be the next generation of the compilation pipeline that aims at making the system actually easy to use.

**Comment by brian-pieces** [comment]
> Thanks for asking! This is going to be the next generation of the compilation pipeline that aims at making the system actually easy to use.

Ah okay that makes sense. Looking forward to the evolution! Thanks for the fast reply!
