### ISSUE TITLE
[Question] Multiple prompts/batches

### ISSUE THREAD

**Issue by bethalianovike** [mlc-ai/mlc-llm#1317]
## ❓ General Questions

Hi, is it possible to input multiple prompts or batches when running CLI? Is there any reference code? Thank you!

**Comment by MasterJH5574** [comment]
Hi @bethalianovike, thanks for the question! We are actively developing the batching and serving support, and it is expected to be released in the soon future. You can refer the branch https://github.com/mlc-ai/mlc-llm/tree/serving and the PRs https://github.com/mlc-ai/mlc-llm/pulls?q=is%3Apr+%5Bserving%5D for the current status. Please stay tuned :-)

**Comment by MasterJH5574** [comment]
Hi @bethalianovike thank you for following up. The serving branch is still under development, and the file you ran is very likely outdated (sorry for not maintaining that file, perhaps I should check and remove it), but I'm happy to share some commands that you can use to run some of the tests or set up the server right now.

There are a few steps to follow:
* build TVM from source with [FlashInfer](https://github.com/flashinfer-ai/flashinfer) enabled (only available for CUDA right now), by adding `set(USE_FLASHINFER ON)` in under `path/to/tvm/build/config.cmake`. (Following this section to build TVM from source https://llm.mlc.ai/docs/install/tvm.html#option-2-build-from-source)
* compile model with the command
```
python build.py --model=Llama-2-7b-chat-hf \
    --quantization=q0f16 \
    --sep-embed \
    --enable-batching
```
* then you would be able to run tests like `tests/python/serve/test_serve_async_engine.py` or `tests/python/serve/server/test_server.py`.

It is possible that I missed a few steps here (apologize in ahead if that happens). We are actively working on the serving branch, and will post detailed documentation once ready.

**Comment by bethalianovike** [comment]
Hi @MasterJH5574 
Thank you for your response!
`test_serve_async_engine.py` runs well in my environment. Thank you for your help!
