### ISSUE TITLE
[Tracking] More friendly error message during load when input file might get corrupted

### ISSUE THREAD

**Issue by tqchen** [mlc-ai/mlc-llm#1319]
## Overview

We have seen quite a few instances of the error
```
_pickle.UnpicklingError: invalid load key, 'v' 
```

and the reason seems to due to the fact that input model is not completely downloaded.

It would be nice to catch this error, check the pattern and append another actionable hint

```
We normally get this error when input file is incomplete, please check/redownload the input file and rerun the build
```

## Action Items

- [ ] Add the error message in the current pipeline (can be optional depending on how fast we move to new pipeline)
- [ ] Add the error message in the new loader

## Links to Related Issues and PRs

- https://github.com/mlc-ai/mlc-llm/issues/1305

**Comment by tqchen** [comment]
cc @LeshengJin @MasterJH5574 @junrushao @cyx-6

**Comment by junrushao** [comment]
With the latest SLM project, the MLC-quantized weights from continuous model delivery will have `md5sum` as its metadata, and the downloader will check the `md5sum` to decide if a file is corrupted or not.
