### ISSUE TITLE
[Question] Mistral MultiGPU

### ISSUE THREAD

**Issue by michel-m** [mlc-ai/mlc-llm#1324]
## ❓ General Questions

Hi, could you please help me pinpoint the reason why MLC (or is it TVM?) doesn't detect my second GPU?

Here is the result of `nvidia-smi`:
```
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.129.03             Driver Version: 535.129.03   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA RTX A4000               Off | 00000000:03:00.0 Off |                  Off |
| 41%   37C    P8              14W / 140W |     18MiB / 16376MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
|   1  NVIDIA RTX A4000               Off | 00000000:0B:00.0 Off |                  Off |
| 41%   39C    P8              17W / 140W |     18MiB / 16376MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
```

I installed MLC in a virtualenv as such:
```bash
git clone https://github.com/mlc-ai/mlc-llm.git --recursive
cd mlc-llm
pip install .
pip install --pre mlc-ai-nightly-cu122 -f https://mlc.ai/wheels
```

In my Python package I load the model as such:
```python
ChatModule(
    model="/sandbox/tmp/models/mlc/dist/prebuilt/mlc-chat-Mistral-7B-Instruct-v0.1-q4f16_1",
    chat_config=ChatConfig(use_presharded_weights=True),
    model_lib_path="/sandbox/tmp/models/mlc/dist/prebuilt/lib/Mistral-7B-Instruct-v0.1-q4f16_1-sw4096_cs128-cuda.so"
)
```
I have tried with `device="cuda"`, `device="cuda:0"`, `device="cuda:1"`, they all work (single GPU only though, even in the case of `device="cuda"`, or if I let MLC set the device automatically).
I have tried with `chat_config=ChatConfig(use_presharded_weights=True)`, `chat_config=ChatConfig(num_shards=2)`, both at the same time.
I have tried with the precompiled Mistral model, and also with a manually compiled one as such:
```bash
python3 -m mlc_llm.build --hf-path mistralai/Mistral-7B-Instruct-v0.1 --target cuda --quantization q8f16_1 --num-shards 2
```
with both `--convert-weights-only` or `--build-model-only`.

To no avail.

I keep getting TVM error `TVMError: Check failed: (!use_presharded_weights) is false: Use of pre-sharded weights requires more than one GPU` or at init:
```
INFO:mlc_chat.support.auto_device:Found device: cuda:0
INFO:mlc_chat.support.auto_device:Not found device: rocm:0
INFO:mlc_chat.support.auto_device:Not found device: metal:0
INFO:mlc_chat.support.auto_device:Not found device: vulkan:0
INFO:mlc_chat.support.auto_device:Not found device: opencl:0
INFO:mlc_chat.support.auto_device:Using device: cuda:0. Use `--device` to override.
```
But no trace of `cuda:1` here (unless I set it explicitly with `device="cuda:1"` but then there is no `cuda:0` in the trace).
I tried setting explicitly `CUDA_VISIBLE_DEVICES="0,1"`.

Nothing seems to work, and any kind of advice would be greatly appreciated.
Thank you!

**Comment by junrushao** [comment]
CC @MasterJH5574

**Comment by tqchen** [comment]
Looking at the code that was pasted, likely you need to pass in num_shards explicitly in the ChatConfig, try 

```python
chat_config=ChatConfig(num_shards=2),
```

**Comment by tqchen** [comment]
also cc @CharlieFRuan @davidpissarra , would be good to confirm Mistral under multiGPU

**Comment by michel-m** [comment]
Hey, thank you for your quick answer. Unfortunately, as I mentioned, I also tried with `chat_config=ChatConfig(num_shards=2)` to no avail.
Thanks for taking the time to help with my issue.

**Comment by tqchen** [comment]
Leaving some context for developers looking into this. The error seems to trigger when `use_disco=False`

-  https://github.com/mlc-ai/mlc-llm/blob/main/cpp/llm_chat.cc#L195 (aka use_disco=False)

But if num_shards get set correctly, it should set `use_disco=True`
-https://github.com/mlc-ai/mlc-llm/blob/main/cpp/llm_chat.cc#L125

So seems for some reason num_shards wasn't propagated correctly into the backend

**Comment by jinhongyii** [comment]
I cannot reproduce this error. The model you build is using **q8f16_1,** but in the initialization of chat module you use mlc-chat-Mistral-7B-Instruct-v0.1-**q4f16_1**. Does this mismatch cause the error?

**Comment by jinhongyii** [comment]
Also, given you didn't use presharded weights to build the model, you may just use the default value of chat_config to let mlc-llm automatically detect chat config.
```
ChatModule(
    model="/sandbox/tmp/models/mlc/dist/prebuilt/mlc-chat-Mistral-7B-Instruct-v0.1-q4f16_1",
    model_lib_path="/sandbox/tmp/models/mlc/dist/prebuilt/lib/Mistral-7B-Instruct-v0.1-q4f16_1-sw4096_cs128-cuda.so"
)
```

**Comment by michel-m** [comment]
Hello, thank you for your answers.
As I mentioned, I tried with both the precompiled model (mlc-chat-Mistral-7B-Instruct-v0.1-q4f16_1) and also with a Mistral I compiled myself, using `--num-shards 2`. I tried both models separately, meaning in different occasions, so no mismatch here.
I still cannot run them on 2 GPUs. It seems either MLC or TVM cannot detect my second GPU (except when I set explicitly `device="cuda:1"` but then it doesn't detect `cuda:0`).
When you say you cannot reproduce, does it mean you managed to run the precompiled Mistral model (this one https://huggingface.co/mlc-ai/mlc-chat-Mistral-7B-Instruct-v0.1-q4f16_1) on 2 GPUs?
Thanks again for your help.

**Comment by michel-m** [comment]
I should add, both models (the precompiled one and the one I compiled myself) run perfectly fine on one GPU alone. I just can't seem to enable using multiple GPUs.

**Comment by jinhongyii** [comment]
I managed to compile Mistral and run it. Here's the commands I run:

```
python3 build.py --model /models/Mistral-7B-Instruct-v0.1 --target cuda --quantization q8f16_1 --num-shards 2 --build-model-only
python3 build.py --model /models/Mistral-7B-Instruct-v0.1 --target cuda --quantization q8f16_1 --num-shards 2 --convert-weight-only
python3 examples/python/sample_mlc_chat.py
```
I modified sample_mlc_chat.py to below:
```
from mlc_chat import ChatModule, ChatConfig
from mlc_chat.callback import StreamToStdout

# From the mlc-llm directory, run
# $ python examples/python/sample_mlc_chat.py

# Create a ChatModule instance
cm = ChatModule(model="Mistral-7B-Instruct-v0.1-q8f16_1")
# You can change to other models that you downloaded, for example,
# cm = ChatModule(model="Llama-2-13b-chat-hf-q4f16_1")  # Llama2 13b model

# Generate a response for a given prompt
output = cm.generate(
    prompt="What is the meaning of life?",
    progress_callback=StreamToStdout(callback_interval=2),
)

# Print prefill and decode performance statistics
print(f"Statistics: {cm.stats()}\n")

output = cm.generate(
    prompt="How many points did you list out?",
    progress_callback=StreamToStdout(callback_interval=2),
)

# Reset the chat module by
# cm.reset_chat()

```

**Comment by jinhongyii** [comment]
I run on 2 gpus, and adding `num-shards=2` in chat config doesn't take any effect because it's automatically detected

**Comment by davidpissarra** [comment]
Hi @michel-m. I believe this error message is misleading regarding the number of GPUs, TVM can recognize your GPUs.

> I keep getting TVM error TVMError: Check failed: (!use_presharded_weights) is false: Use of pre-sharded weights requires more than one GPU or at init:

Here's a quick explanation about why this is not working for you. The uploaded libraries ([mlc-ai/binary-mlc-llm-libs](https://github.com/mlc-ai/binary-mlc-llm-libs)) only support single GPU inference (e.g., they were not compiled with `--num-shards` argument which is 1 by default). Regardless of the model, in order to use MultiGPU support, you need to build the model library for the desired number of GPUs (`--num-shards`), for instance running the command `python3 build.py --model /models/Mistral-7B-Instruct-v0.1 --target cuda --quantization q8f16_1 --num-shards 2 --build-model-only` as presented by @jinhongyii. Additionally, just tested and I can confirm that you don't need to clone the original mistral model from huggingface to build the model library, and you can still use mlc-ai quantized weights. Just make sure everything is well configured in the `mlc-chat-config.json` file or via python API to override the defaults, namely the `num_shards` again. Let me know

**Comment by michel-m** [comment]
Hi, sorry for the late response.

So it turns out that by installing MLC as such:
```bash
git clone https://github.com/mlc-ai/mlc-llm.git --recursive
cd mlc-llm
pip install .
```
I must have had the bad luck of getting a regression commit, because when I installed MLC using:
```bash
python3 -m pip install --pre -U -f https://mlc.ai/wheels mlc-chat-nightly-cu122 mlc-ai-nightly-cu122
```
as mentioned in the documentation (which I definitely should have followed, sorry about that), it worked to a better extent.

Now MLC detects my two GPUs:
```
INFO:mlc_chat.support.auto_device:Found device: cuda:0
INFO:mlc_chat.support.auto_device:Found device: cuda:1
INFO:mlc_chat.support.auto_device:Not found device: rocm:0
INFO:mlc_chat.support.auto_device:Not found device: metal:0
INFO:mlc_chat.support.auto_device:Found device: vulkan:0
INFO:mlc_chat.support.auto_device:Found device: vulkan:1
INFO:mlc_chat.support.auto_device:Found device: vulkan:2
INFO:mlc_chat.support.auto_device:Not found device: opencl:0
INFO:mlc_chat.support.auto_device:Using device: cuda:0
```

Although MLC still doesn't seem to be using the second GPU. Here is the result of `nvidia-smi`:
```
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.129.03             Driver Version: 535.129.03   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA RTX A4000               Off | 00000000:03:00.0 Off |                  Off |
| 41%   41C    P2              43W / 140W |   2766MiB / 16376MiB |     45%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
|   1  NVIDIA RTX A4000               Off | 00000000:0B:00.0 Off |                  Off |
| 41%   44C    P2              55W / 140W |   4382MiB / 16376MiB |    100%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+

+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|    0   N/A  N/A      1519      G   /usr/lib/xorg/Xorg                            4MiB |
|    0   N/A  N/A    817071      C   ...e-ml-llm-7xQ3UPjs-py3.10/bin/python        0MiB |
|    1   N/A  N/A      1519      G   /usr/lib/xorg/Xorg                            4MiB |
|    1   N/A  N/A    817072      C   ...e-ml-llm-7xQ3UPjs-py3.10/bin/python     4356MiB |
+---------------------------------------------------------------------------------------+
```

Inference is slower than vLLM (and even Transformers pipeline, slightly) as seen in this graph:
<img width="776" alt="Screenshot 2023-12-04 at 15 21 33" src="https://github.com/mlc-ai/mlc-llm/assets/2655039/7ba54716-d397-4709-8700-409fb48b2d7f">

Although this is most likely due to MLC not offering batch inference at the moment (if I'm not mistaken, reading https://github.com/mlc-ai/mlc-llm/issues/1118).

Does MLC support sharding on multiple GPUs though? That may explain why I'm not seeing any activity on one of my GPUs during inference.
