### ISSUE TITLE
Add eos_token and bos_token between historical dialogue prompts, as Llama2 prompt required[Feature Request] 

### ISSUE THREAD

**Issue by robinhyg** [mlc-ai/mlc-llm#1328]
## 🚀 Feature

As Llama2 prompt required, there need a eos_token and bos_token between two adjacent rounds of historical dialogue prompt, as shown below:
![image](https://github.com/mlc-ai/mlc-llm/assets/11474228/6e392982-52f9-47c0-a18c-f8270525d484)
For now, it seems lost this part during 'GetConcatPrompt' or somewhere else.
## Motivation
Adding this function can ensure strict compliance with llama2's requirements for prompts. This may improve Llama2's performance on MLC.

## Alternatives
Open tokenizer.encode calling to the user interface, and add new prefill api which can taken tokens as input, then users can add eos_token and bos_token outside the lib.

## Additional context

Sample from https://github.com/facebookresearch/llama/blob/main/llama/generation.py
eos_token and bos_token added by the tokenizer.encode through "bos=True" and "eos=True":
```
dialog_tokens: List[int] = sum(
                [
                    self.tokenizer.encode(
                        f"{B_INST} {(prompt['content']).strip()} {E_INST} {(answer['content']).strip()} ",
                        bos=True,
                        eos=True,
                    )
                    for prompt, answer in zip(
                        dialog[::2],
                        dialog[1::2],
                    )
                ],
                [],
            )
            assert (
                dialog[-1]["role"] == "user"
            ), f"Last message must be from user, got {dialog[-1]['role']}"
            dialog_tokens += self.tokenizer.encode(
                f"{B_INST} {(dialog[-1]['content']).strip()} {E_INST}",
                bos=True,
                eos=False,
            )
```

**Comment by rickzx** [comment]
Hello, this should be fixed in the new unified conversation template.

https://github.com/mlc-ai/mlc-llm/blob/2b8aadf57479ffffa24380846cfb9976d00d437c/python/mlc_llm/conversation_template.py#L66
