### ISSUE TITLE
[Bug] iOS MLCChat App crashes on my M1 Macbook - Mistral_7B_Instruct_v0.1_q3f16_1_fused_fused_decode1_take1

### ISSUE THREAD

**Issue by kevin36524** [mlc-ai/mlc-llm#1332]
## 🐛 Bug MLCChat App crashes while calling `[ChatModule prefill:]`

I tried to compile the iOS app on my M1 Mac app, I followed all the steps https://llm.mlc.ai/docs/deploy/ios.html
but the app keeps on crashing when chatting with the LLM.

The crash starts with `[ChatModule prefill:]` and ends at one of these depending on the model.
`Mistral_7B_Instruct_v0.1_q3f16_1_fused_fused_decode1_take1`
`RedPajama_INCITE_Chat_3B_v1_q4f16_1_fused_fused_decode1_take`
`Llama_2_7b_chat_hf_q3f16_1_fused_fused_decode1_take1`

I tried to download the app from the App store and that works without any issues.

## To Reproduce

Follow the steps at https://llm.mlc.ai/docs/deploy/ios.html

1. python -m venv venv  
2. source venv/bin/activate
3.  python3 -m pip install --pre -U -f https://mlc.ai/wheels mlc-ai-nightly
4. git clone https://github.com/mlc-ai/mlc-llm
5. cd mlc-llm   
6. mkdir -p dist/prebuilt  
7. git clone https://github.com/mlc-ai/binary-mlc-llm-libs.git dist/prebuilt/lib
8. cd dist/prebuilt 
9. git lfs install     
10. git clone https://huggingface.co/mlc-ai/mlc-chat-RedPajama-INCITE-Chat-3B-v1-q4f16_1
11. cd ../..        
12.  ls -l ./dist/prebuilt/lib/*-iphone.tar 
13. ls -l ./dist/prebuilt/mlc-chat-RedPajama-INCITE-Chat-3B-v1-q4f16_1   
14. git submodule update --init --recursive 
15. cd ./ios           
16.  ./prepare_libs.sh      
17. ls ./build/lib/  
18. vim prepare_params.sh    and ensure RedPajama is the only one uncommented
19. ./prepare_params.sh  
20. ls ./dist 
21. open MLCChat.xcodeproj  fixed the provisioning and complied.
22. Run the app on My Mac (Designed for iPad)
23. The app launches fine
24. Now choose RedPajama and type hello world and hit send

=== Getting CRASH ===

[MLCChat_crash.txt](https://github.com/mlc-ai/mlc-llm/files/13468416/MLCChat_crash.txt)

## Expected behavior

No crash.

## Environment

 - Platform (e.g. WebGPU/Vulkan/IOS/Android/CUDA): iOS
 - Operating system (e.g. Ubuntu/Windows/MacOS/...): 14.0
 - Device (e.g. iPhone 12 Pro, PC+RTX 3090, ...) : M1 Mac
 - How you installed MLC-LLM (`conda`, source): via source code. https://github.com/mlc-ai/mlc-llm/tree/main
 - How you installed TVM-Unity (`pip`, source): `python3 -m pip install --pre -U -f https://mlc.ai/wheels mlc-ai-nightly`
 - Python version (e.g. 3.10): `3.10.11`
 - GPU driver version (if applicable):
 - CUDA/cuDNN version (if applicable):
 - TVM Unity Hash Tag (`python -c "import tvm; print('\n'.join(f'{k}: {v}' for k, v in tvm.support.libinfo().items()))"`, applicable if you compile models):
 - Any other relevant information:

## Additional context

I tired 3 models mistral, RedPajama via prebuilt and Llama via download. Below are the crash logs for each of them.

Thread 6 Crashed:
0   MLCChat                       	       0x102062cb8 Mistral_7B_Instruct_v0.1_q3f16_1_fused_fused_decode1_take1 + 1288
1   MLCChat                       	       0x1021b74bc tvm::runtime::relax_vm::VirtualMachineImpl::InvokeClosurePacked(tvm::runtime::ObjectRef const&, tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*) + 96
2   MLCChat                       	       0x1021b9b48 tvm::runtime::relax_vm::VirtualMachineImpl::RunInstrCall(tvm::runtime::relax_vm::VMFrame*, tvm::runtime::relax_vm::Instruction) + 1312
3   MLCChat                       	       0x1021b9350 tvm::runtime::relax_vm::VirtualMachineImpl::RunLoop() + 100
4   MLCChat                       	       0x1021b8f60 tvm::runtime::relax_vm::VirtualMachineImpl::InvokeBytecode(long long, std::__1::vector<tvm::runtime::TVMRetValue, std::__1::allocator<tvm::runtime::TVMRetValue>> const&) + 284
5   MLCChat                       	       0x1021c1140 tvm::runtime::PackedFuncObj::Extractor<tvm::runtime::PackedFuncSubObj<tvm::runtime::relax_vm::VirtualMachineImpl::GetClosureInternal(tvm::runtime::String const&, bool)::$_2>>::Call(tvm::runtime::PackedFuncObj const*, tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*) + 188
6   MLCChat                       	       0x1021b7688 tvm::runtime::relax_vm::VirtualMachineImpl::InvokeClosurePacked(tvm::runtime::ObjectRef const&, tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*) + 556
7   MLCChat                       	       0x1021c1e80 tvm::runtime::PackedFuncObj::Extractor<tvm::runtime::PackedFuncSubObj<tvm::runtime::relax_vm::VirtualMachineImpl::_LookupFunction(tvm::runtime::String const&)::$_4>>::Call(tvm::runtime::PackedFuncObj const

Thread 5 Crashed:
0   MLCChat                       	       0x10459f028 RedPajama_INCITE_Chat_3B_v1_q4f16_1_fused_fused_decode1_take + 1264
1   MLCChat                       	       0x1046d34bc tvm::runtime::relax_vm::VirtualMachineImpl::InvokeClosurePacked(tvm::runtime::ObjectRef const&, tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*) + 96
2   MLCChat                       	       0x1046d5b48 tvm::runtime::relax_vm::VirtualMachineImpl::RunInstrCall(tvm::runtime::relax_vm::VMFrame*, tvm::runtime::relax_vm::Instruction) + 1312
3   MLCChat                       	       0x1046d5350 tvm::runtime::relax_vm::VirtualMachineImpl::RunLoop() + 100
4   MLCChat                       	       0x1046d4f60 tvm::runtime::relax_vm::VirtualMachineImpl::InvokeBytecode(long long, std::__1::vector<tvm::runtime::TVMRetValue, std::__1::allocator<tvm::runtime::TVMRetValue>> const&) + 284
5   MLCChat                       	       0x1046dd140 tvm::runtime::PackedFuncObj::Extractor<tvm::runtime::PackedFuncSubObj<tvm::runtime::relax_vm::VirtualMachineImpl::GetClosureInternal(tvm::runtime::String const&, bool)::$_2>>::Call(tvm::runtime::PackedFuncObj const*, tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*) + 188

Thread 3 Crashed:
0   MLCChat                       	       0x100d2b1dc Llama_2_7b_chat_hf_q3f16_1_fused_fused_decode1_take1 + 1288
1   MLCChat                       	       0x100e6f4bc tvm::runtime::relax_vm::VirtualMachineImpl::InvokeClosurePacked(tvm::runtime::ObjectRef const&, tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*) + 96
2   MLCChat                       	       0x100e71b48 tvm::runtime::relax_vm::VirtualMachineImpl::RunInstrCall(tvm::runtime::relax_vm::VMFrame*, tvm::runtime::relax_vm::Instruction) + 1312
3   MLCChat                       	       0x100e71350 tvm::runtime::relax_vm::VirtualMachineImpl::RunLoop() + 100
4   MLCChat                       	       0x100e70f60 tvm::runtime::relax_vm::VirtualMachineImpl::InvokeBytecode(long long, std::__1::vector<tvm::runtime::TVMRetValue, std::__1::allocator<tvm::runtime::TVMRetValue>> const&) + 284
5   MLCChat                       	       0x100e79140 tvm::runtime::PackedFuncObj::Extractor<tvm::runtime::PackedFuncSubObj<tvm::runtime::relax_vm::VirtualMachineImpl::GetClosureInternal(tvm::runtime::String const&, bool)::$_2>>::Call(tvm::runtime::PackedFuncObj const*, tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*) + 188

Model: MacBookPro18,1, BootROM 10151.0.156.505.1, proc 10:8:2 processors, 16 GB, SMC 
Graphics: Apple M1 Pro, Apple M1 Pro, Built-In
Display: Color LCD, 3456 x 2234 Retina, Main, MirrorOff, Online
Display: DELL P2419HC, 1920 x 1080 (1080p FHD - Full High Definition), MirrorOff, Online
Memory Module: LPDDR5, Samsung
AirPort: spairport_wireless_card_type_wifi (0x14E4, 0x4387), wl0: May  7 2023 18:47:04 version 20.10.1025.0.8.7.146 FWID 01-daa32250
AirPort: 

Just note that the downloaded app from the AppStore works fine.

**Comment by kevin36524** [comment]
BTW here's how my ios/build/lib looks like

```
(mlc-chat-venv) patelkev@W6GY7X733W ios %  ls -al build/lib

total 170720
drwxr-xr-x   8 patelkev  staff       256 Nov 26 16:29 .
drwxr-xr-x  15 patelkev  staff       480 Nov 26 16:27 ..
-rw-r--r--   1 patelkev  staff    941632 Nov 26 16:27 libmlc_llm.a
-rw-r--r--   1 patelkev  staff  24192280 Nov 26 16:29 libmodel_iphone.a
-rw-r--r--   1 patelkev  staff   1749056 Nov 26 16:27 libsentencepiece.a
-rw-r--r--   1 patelkev  staff  53551136 Nov 26 16:27 libtokenizers_c.a
-rw-r--r--   1 patelkev  staff     82256 Nov 26 16:27 libtokenizers_cpp.a
-rw-r--r--   1 patelkev  staff   6875832 Nov 26 16:27 libtvm_runtime.a
```

**Comment by kevin36524** [comment]
Hey @davidpissarra thanks for looking at the issue. 

But I found out the issue. The issue was with Xcode beta. I updated to XCode-15.0.1 and now it works fine.

**Comment by davidpissarra** [comment]
Thanks @kevin36524, also tested your commands on my end and it looks great
