### ISSUE TITLE
[Question] Testing relax model code.

### ISSUE THREAD

**Issue by musram** [mlc-ai/mlc-llm#1334]
## ❓ General Questions

I am new to this repo trying to understand things.  The tests/python tests mlc_chat.  From https://github.com/mlc-ai/mlc-llm/issues/1306  and mlc_chat code, I understand that its not going to test ml_llm/relax_model. How do we test mlc_llm/relax_model? Suppose if I want to write code for a new model architecture how to make sure the model written in relax framework is correct?  
My assumption is that if we have IRModule for a given model architecture then we can pass a object of tvm.nd.array to test it.  Pls help me to understand.

**Comment by MasterJH5574** [comment]
Hi @musram, thanks for the question. We are gradually switching over all model implementation to the new compilation pipeline where the models are defined under https://github.com/mlc-ai/mlc-llm/tree/main/python/mlc_chat/compiler/model, which has better debuggability than models defined in the previous pipeline (`mlc_llm/relax_model` as you point).

Your assumption is right and we indeed have some legacy test for the models in `mlc_llm/relax_model` (like https://github.com/mlc-ai/mlc-llm/blob/main/tests/legacy-python/evaluate.py) for you as a reference (need to compile the model before running tests), though the tests may be outdated and need some fixes.

**Comment by musram** [comment]
Thanks @MasterJH5574  for your response. I felt mlc_chat/compiler/model path was bit easy compared to mlc_llm/relax_model.

**Comment by musram** [comment]
@MasterJH5574   Is there any documentation regarding  or how do you compile  the model in  mlc_chat/complier/model. Can you provide a specific example?  For example we use 
"python3 -m mlc_llm.build --hf-path togethercomputer/RedPajama-INCITE-Chat-3B-v1 --target vulkan_x86_64 --quantization q4f16_1"   using mlc_llm

**Comment by MasterJH5574** [comment]
Yes we do have commands to compile the models under the new workflow. For example,

* Compiling llama2
  ```
  python -m mlc_chat compile --model path/to/your/local/Llama-2-7b-chat-hf --quantization q4f16_1 -o llama2-7b-q4f16_1.so
  ```
* Quantizing weights
  ```
  mkdir llama2-7b-q4f16_1
  python -m mlc_chat convert_weight --model path/to/your/local/Llama-2-7b-chat-hf --quantization q4f16_1 -o llama2-7b-q4f16_1
  ```
* Generating `mlc-chat-config.json` config
  ```
  python -m mlc_chat gen_mlc_chat_config --model path/to/your/local/Llama-2-7b-chat-hf --quantization q4f16_1 -o llama2-7b-q4f16_1 --conv-template llama-2
  ```

We do not have RedPajama (backed by GPT-NeoX) in the new flow right now, but will make the switch in the soon future.

**Comment by junrushao** [comment]
@MasterJH5574 no need to use “python -m”. Just do:

mlc_chat compile -h
mlc_chat convert_weight -h

**Comment by MasterJH5574** [comment]
@junrushao Thanks for the correction!!
