### ISSUE TITLE
Error after calling the ios api for mlc-llm

### ISSUE THREAD

**Issue by rjzsatvara** [mlc-ai/mlc-llm#1336]
I got into this error while calling api like mention in documentation. Can you please help me?

terminating with uncaught exception of type tvm::runtime::InternalError: [14:31:27] /Users/nileshkatariya/mlc-llm/cpp/llm_chat.cc:500: InternalError: Check failed: (config_istream) is false: 
Stack trace:
  [bt] (0) 1   Solo Ai Chat App                    0x0000000104de8ba8 tvm::runtime::detail::LogFatal::Entry::Finalize() + 68
  [bt] (1) 2   Solo Ai Chat App                    0x0000000104de8b64 tvm::runtime::detail::LogFatal::Entry::Finalize() + 0
  [bt] (2) 3   Solo Ai Chat App                    0x0000000104de7b84 __clang_call_terminate + 0
  [bt] (3) 4   Solo Ai Chat App                    0x0000000104dffdc0 mlc::llm::LLMChat::Reload(tvm::runtime::TVMArgValue, tvm::runtime::String, tvm::runtime::String) + 11236
  [bt] (4) 5   Solo Ai Chat App                    0x0000000104dfcf1c mlc::llm::LLMChatModule::GetFunction(tvm::runtime::String const&, tvm::runtime::ObjectPtr<tvm::runtime::Object> const&)::'lambda'(tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*)::operator()(tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*) const + 768
  [bt] (5) 6   Solo Ai Chat App                    0x0000000104dfcc10 tvm::runtime::PackedFuncObj::Extractor<tvm::runtime::PackedFuncSubObj<mlc::llm::LLMChatModule::GetFunction(tvm::runtime::String const&, tvm::runtime::ObjectPtr<tvm::runtime::Object> const&)::'lambda'(tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*)> >::Call(tvm::runtime::PackedFuncObj const*, tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*) + 40
  [bt] (6) 7   Solo Ai Chat App                    0x0000000104da04ec tvm::runtime::TVMRetValue tvm::runtime::PackedFunc::operator()<tvm::runtime::Module&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&>(tvm::runtime::Module&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&) const + 252
  [bt] (7) 8   Solo Ai Chat App                    0x0000000104d9ffac -[ChatModule reload:modelPath:appConfigJson:] + 408
  [bt] (8) 9   Solo Ai Chat App                    0x0000000104d85574 $s16Solo_Ai_Chat_App12HomeScreenVCC11viewDidLoadyyF + 3572

**Comment by tqchen** [comment]
Hi @rjzsatvara this error seems to indicate that the particular project cannot find the mlc-chat-config.json locally in the folder. Please make sure you place the files in the right place. The example app would be a good tutorial to follow

**Comment by loekTheDreamer** [comment]
> Hi @rjzsatvara this error seems to indicate that the particular project cannot find the mlc-chat-config.json locally in the folder. Please make sure you place the files in the right place. The example app would be a good tutorial to follow

where does the error indicate it cannot find the mlc-chat-config.json? i see it saying Check failed: (config_istream) is false: which is indicating a different sort of issue from tvm. 

where should the files be?
mine is located at dist/bundle/Llama-3.2-3B-Instruct-q4f16_1-MLC/

```
dist
├── bundle                   # The directory for mlc-app-config.json (and optionally model weights)
    │                        # that will be bundled into the iOS app.
    ├── mlc-app-config.json  # The app config JSON file.
    └──Llama-3.2-3B-Instruct-q4f16_1-MLC
     │
     └──mlc-chat-config.json  
```

**Comment by MasterJH5574** [comment]
Hi @loekTheDreamer, thanks for bringing this up. This issue is a bit outdated so do you mind opening a new issue and describing the problems you met there? If you can also share the contents of your `mlc-chat-config.json` that might be helpful for us to figure out.

**Comment by loekTheDreamer** [comment]
Sure, I can do that 😉
