### ISSUE TITLE
[Bug] iOS app much slower when built than the TestFlight version

### ISSUE THREAD

**Issue by nundys** [mlc-ai/mlc-llm#1338]
## 🐛 Bug

When I build  the iOS app from the latest source code and run on the same device as the TestFlight version, the app runs much slower (and sometimes crashes) than the TestFlight version

## To Reproduce

1. Build iOS app per https://llm.mlc.ai/docs/deploy/ios.html#step-4-build-ios-app
2. Run on device (iPhone 14)
3. Check speed (about 0.2-0.5 tok/s)
4. Download TestFlight build
5. Run on device (same iPhone 14)
6. Check speed (about 2 tok/s)

## Expected behavior

The speed should be the same

## Environment

 - Platform (e.g. iOS):
 - Operating system (e.g. Ubuntu/Windows/MacOS/...):
 - Device (e.g. iPhone 14)
 - How you installed MLC-LLM (`conda`, source): as per the instructions https://llm.mlc.ai/docs/deploy/ios.html#step-4-build-ios-app
 - How you installed TVM-Unity (`pip`, source): as per instructions https://llm.mlc.ai/docs/deploy/ios.html#step-4-build-ios-app
 - Python version (e.g. 3.10): -
 - GPU driver version (if applicable):
 - CUDA/cuDNN version (if applicable):
 - TVM Unity Hash Tag (`python -c "import tvm; print('\n'.join(f'{k}: {v}' for k, v in tvm.support.libinfo().items()))"`, applicable if you compile models):
 - Any other relevant information:

**Comment by davidpissarra** [comment]
Hi @nundys, thanks for sharing your experience. Which model are you using? Llama-2? On my end (iPhone 14 Pro Max), the mlc app performs with approximately the same speed as the app built from the source code. Have you tried to reset the chat once the app is slow? Sometimes there are some speed variabilities but once the app is warmed up I reset the chat and it turns out to get faster.

**Comment by davidpissarra** [comment]
When building the iOS app from source make sure to correctly set the `max-seq-len` in the mlc-chat-config.json file

**Comment by nundys** [comment]
Thanks for your response, @davidpissarra 

The slowdown happens when using the new Mistral models.  Strange, Is the TestFlight app built from the current code base on this repo?  Will check on the context length parameter you suggested.


thank you

**Comment by davidpissarra** [comment]
Yes, the TestFlight app is built on the latest ios src code. Make sure to have the latest xcode version, as well as the latest mlc llm code. Let me know if you can run it at a more reasonable speed.
