### ISSUE TITLE
[Bug] Sometimes the answer is truncated

### ISSUE THREAD

**Issue by li-jun-jiang** [mlc-ai/mlc-llm#1340]
## 🐛 Bug

The last sentence is not completed.

## To Reproduce

Steps to reproduce the behavior (The file _my_rag.py is in the attached my.zip):

1. python3 -m mlc_llm.build --model CodeLlama-7b-Instruct-hf --target metal --max-seq-len 768 --quantization q3f16_1
2. python3 _my_rag.py
3. Please refer to the file truncated_answer.png in the attached file, my.zip, for an answer.

## Expected behavior

A simple answer without truncation.

## Environment

 - Platform (e.g. WebGPU/Vulkan/IOS/Android/CUDA): IOS and MacOS
 - Operating system (e.g. Ubuntu/Windows/MacOS/...): IOS and MacOS
 - Device (e.g. iPhone 12 Pro, PC+RTX 3090, ...): iphone 15 pro max and macbook pro 14 (m2 pro)
 - How you installed MLC-LLM (`conda`, source): source
 - How you installed TVM-Unity (`pip`, source): pip
 - Python version (e.g. 3.10): 3.11.6
 - GPU driver version (if applicable):
 - CUDA/cuDNN version (if applicable):
 - TVM Unity Hash Tag (`python -c "import tvm; print('\n'.join(f'{k}: {v}' for k, v in tvm.support.libinfo().items()))"`, applicable if you compile models):
 - Any other relevant information:

[my.zip](https://github.com/mlc-ai/mlc-llm/files/13484694/my.zip)

**Comment by li-jun-jiang** [comment]
Here are the token numbers (The prompt and answer are in the attached file):
```
  prompt: 610
  answer: 146
  mean_gen_len: 128
  max_gen_len: 512
  max_window_size: 768
```

It seems the answer is less than max_gen_len, but greater than mean_gen_len.
Does max_gen_lean refer to the sum of the prompt and the answer?

**Comment by CharlieFRuan** [comment]
max gen len only refers to the answer I believe; can I see the full generated answer? 512 is pretty small to be honest; perhaps consider making it to 4096 regardless

**Comment by CharlieFRuan** [comment]
Ahh the max window size is also a bit too small -- this one is for both prompt and answer (and multi-round history if that is what you are doing). It makes sense to have a smaller one for iPhone, but for MacBooks we can probably get at least 2048 if not 4096

**Comment by CharlieFRuan** [comment]
> Is the max_window_size for the context size?

Yes, `max_window_size` is the same as max context length.

> Is it possible for mlc to continue outputting until either the end or the max gen size is reached?

I believe currently we would just stop generating when either `max_gen_len` or `max_window_size` is reached: 
https://github.com/mlc-ai/mlc-llm/blob/b4ba7ca9a337f64838083fd64fdc7ff52fd0a6de/cpp/llm_chat.cc#L1181-L1193

> I'd like to run MLCChat on iphone, for llama 2 with q3f16_1,

For iPhone, @davidpissarra might have more expertise. Alternatively, you could consider Mistral, which uses sliding-window-attention, so that we essentially do not have `max_window_size`.

**Comment by Hzfengsy** [comment]
> I'd like to run MLCChat on iphone, for llama 2 with q3f16_1, what's the recommended maximum value for max_window_size?

768 is recommended for 6GB iPhones, 1024 would be safe for 8GB iPhones
