### ISSUE TITLE
[Feature Request] Function Calling in OpenAI API

### ISSUE THREAD

**Issue by t-dettling** [mlc-ai/mlc-llm#1341]
## 🚀 Feature
Add ability to pass function to model on supported LLMs

## Motivation

With the ChatGPT API you can pass a list of functions to the model, and some models that can be self-hosted require this to function properly, for example: https://huggingface.co/gorilla-llm/gorilla-openfunctions-v1
This would allowe the functions parameter to be used with the models that support them allowing for code calling to work.

## Additional context

```python
import openai


def get_gorilla_response(prompt="Call me an Uber ride type \"Plus\" in Berkeley at zipcode 94704 in 10 minutes",
                         model="gorilla-openfunctions-v0", functions=[]):
    openai.api_key = "EMPTY"
    openai.api_base = "http://192.168.30.27:8000/v1"
    try:
        completion = openai.ChatCompletion.create(
            model="gorilla-openfunctions-v1-q4f32_0",
            temperature=0.0,
            messages=[{"role": "user", "content": prompt}],
            functions=functions,
        )
        return completion.choices[0].message.content
    except Exception as e:
        print(e, model, prompt)


query = "Call me an Uber ride type \"Plus\" in Berkeley at zipcode 94704 in 10 minutes"
functions = [
    {
        "name": "Uber Carpool",
        "api_name": "uber.ride",
        "description": "Find suitable ride for customers given the location, type of ride, and the amount of time the customer is willing to wait as parameters",
        "parameters": [{"name": "loc", "description": "location of the starting place of the uber ride"},
                       {"name": "type", "enum": ["plus", "comfort", "black"],
                        "description": "types of uber ride user is ordering"},
                       {"name": "time", "description": "the amount of time in minutes the customer is willing to wait"}]
    }
]

for i in range(10):
    resp = get_gorilla_response(query, functions=functions)
    print(resp)
print("Done!")
```

This is example code that would use the feature shown above. Currently the endpoint listed in the code is a MLC chat rest endpoint with the gorilla model, but because the model is not actually getting the functions that it can call, it is producing bad output, effectively making gorilla not work with MLC even though it functions and does try to return a function call: `call_me_uber_ride_type("Plus", Berkeley, zipcode=94704, duration=10)`

**Comment by Kartik14** [comment]
@t-dettling Thank you for bringing this up. We will look into add function calling support to rest API for MLC.

**Comment by MasterJH5574** [comment]
Thanks to @Kartik14, we have the PR #1378 which brings the function call supports. We will upload prebuilt gorilla model weights to HF after the PR getting merged.
