### ISSUE TITLE
[Question] More details on specific quantization method used

### ISSUE THREAD

**Issue by jamestwhedbee** [mlc-ai/mlc-llm#1351]
## ❓ General Questions

Your link below is unfortunately difficult for me to follow (reading the paper is not straightforward). Can I get more info on how the quantization compares to auto_gptq and auto_awq?

https://llm.mlc.ai/docs/compilation/configure_quantization.html

**Comment by lhl** [comment]
Hi, revisiting MLC after a bit and saw there were a some more new formats, are these documented  anywhere? https://github.com/mlc-ai/mlc-llm/blob/main/mlc_llm/quantization/__init__.py

**Comment by srikanthsrnvs** [comment]
Bumping on this, can we get documentation for these quantization formats? GPTQ seems to have the best results AFAIK and I'd like to understand the algorithms used better
