### ISSUE TITLE
[Bug] Ask the same question multiple times in Android APP, response wont stop

### ISSUE THREAD

**Issue by qc903113684** [mlc-ai/mlc-llm#1355]
## 🐛 Bug

when ask the same question multiple times (4 to 6 times) in Android APP. The requestGenerate function wont stop generate tokens, even though the content of response is finished (same response will continue generate without new words).

## To Reproduce

1. build mlc-llm project (commit 02a41e1fe4918b0c313ce24a532adc6eaed6ae02)
2. build tvm unity environment (mlc-ai-nightly-cu118 0.12.dev1880)
3. compile llama-2-7b and android tar
4. build andoid app
5. ask same question "who are you" for 4 to 6 times
6. check response print in Android Studio

## Expected behavior

the same response will continue show:
![image](https://github.com/mlc-ai/mlc-llm/assets/38254779/16f2e00e-5291-45eb-a3e9-b911fba210dc)

## Environment

 - Platform (e.g. WebGPU/Vulkan/IOS/Android/CUDA): Android
 - Operating system (e.g. Ubuntu/Windows/MacOS/...): 
 - Device (e.g. iPhone 12 Pro, PC+RTX 3090, ...) 8gen2 android phone with 24GB RAM
 - How you installed MLC-LLM (`conda`, source): source
 - How you installed TVM-Unity (`pip`, source): pip
 - Python version (e.g. 3.10): 3.8
 - GPU driver version (if applicable): 
 - CUDA/cuDNN version (if applicable): 11.8
 - TVM Unity Hash Tag (`python -c "import tvm; print('\n'.join(f'{k}: {v}' for k, v in tvm.support.libinfo().items()))"`, applicable if you compile models): 189412e9ad52fee4dc3dc46bcf60d820e82422d8
 - Any other relevant information:

**Comment by Hzfengsy** [comment]
Could you please check if the stop token was generated? If not, it might be the issue of the model (or quantization)

**Comment by qc903113684** [comment]
> Could you please check if the stop token was generated? If not, it might be the issue of the model (or quantization)

1. I tested if I ask 4 to 6 different question wont happen this issue.
2. ask 4 to 6 "who are you" will continue generate same content, which means stop token is generated. If stop token doesnt generated it will generate more new token added behind content.

**Comment by qc903113684** [comment]
if I add "conv_config" to determined the stop token this issue may sovled:

"conv_config": {
        "stop_tokens": [2],
        "stop_str": "</s>"
    }
