### ISSUE TITLE
Add Attention Sinks

### ISSUE THREAD

**Issue by kmn1024** [mlc-ai/mlc-llm#1357]
## 🚀 Feature
Add Attention Sinks (https://arxiv.org/pdf/2309.17453.pdf, https://github.com/tomaarsen/attention_sinks/) to MLC.

## Motivation
mlc_chat_cli gets noticeably slower as the conversation progresses. I tried this on Orange Pi 5, with two setups: as exactly described in https://blog.mlc.ai/2023/08/09/GPU-Accelerated-LLM-on-Orange-Pi, and then compiling my own StableLM 3B (q4f16_1, OpenCL). You can see from these screenshots that toks/sec gradually decreases with progress (I waited in between each generation to ensure it wasn't due to thermal throttling).
![Screenshot from 2023-11-30 15-52-48](https://github.com/mlc-ai/mlc-llm/assets/6571924/62ef678c-79b1-4a89-8ed7-3b3e18069810)
![Screenshot from 2023-11-30 16-26-43](https://github.com/mlc-ai/mlc-llm/assets/6571924/03e4033c-ae1e-4243-a061-653b85e32b65)

Such slow down is unavoidable given the nature of Attention, but maybe we can reduce the latency hit without affecting decoding quality too much by using Attention Sinks (figure 1 from the paper). The default cache settings for most models is window attention with window size = sequence length; with Attention Sinks maybe we can use something smaller.

## Alternatives
It seems there will always be a latency vs quality trade off for any type of cache, but perhaps Attention Sinks currently offers the best trade off.

## Additional context
I would love to work on this, if I can get a mentor to point out which files should be changed for a tidy implementation!

**Comment by CharlieFRuan** [comment]
Thank you so much for offering help! We really appreciate it.

However, implementing attention sink may not be the most beginner-friendly task as we handle most kv cache logic in a lower-level stack called TVM. For instance, when we introduced sliding-window-attention, some work needed to be done in TVM: https://github.com/apache/tvm/pull/15963.

Regarding speculative decoding, it is definitely something we are considering as well. We are currently working on another front for model serving (in contrast with simple chatting), which will probably include speculative decoding.

**Comment by kmn1024** [comment]
Thanks for the heads up! Looking forwards to an implementation of this and speculative decoding too.

**Comment by kmn1024** [comment]
@CharlieFRuan @davidpissarra So I didn't heed Charlie's warning, and attempted to implement attention sink. Ended up pulling most of my hair our, but I have something that seems to work. The changes are in the two repos that Charlie pointed out:
https://github.com/mlc-ai/relax/compare/mlc...kmn1024:relax_attention_sinks:main
https://github.com/mlc-ai/mlc-llm/compare/main...kmn1024:llm_attention_sinks:main (please ignore conv_templates.cc)

I will try to get some /stats tomorrow. Is this something that I can send to you two for review? No worries at all if you prefer not, I can see that you guys are super busy =)

**Comment by CharlieFRuan** [comment]
@kmn1024 Wow this is really impressive, thank you for the hard work!

We are in the process of migrating from [the `relax_model` folder](https://github.com/mlc-ai/mlc-llm/tree/main/mlc_llm/relax_model) to [SLIM](https://github.com/mlc-ai/mlc-llm/pulls?q=SLIM+in%3Atitle+OR+SLM+in%3Atitle+), essentially a new workflow for compiling models on the mlc-llm layer. We are still wrapping it up and making documentation for it.

Therefore, the changes in `lm_support.cc`, `llm_chat.cc` would not be affected; but those in `relax_model` and `mlc_llm/core.py` may need to be migrated later when the new workflow is up.

With that being said, once you are ready, feel free to open a PR for both the TVM side and the mlc-llm side (old workflow is fine), then @davidpissarra and/or I will help review. We can later pick the changes to the new workflow.

Really appreciate the contribution!

**Comment by davidpissarra** [comment]
Hi, @kmn1024! Regarding sinks, since most of the SW logic was already implemented, we were able to reuse the `WindowOverride` function from SWA to implement it (three-line change, see https://github.com/apache/tvm/pull/16240). As of now, mistral is the only architecture that supports SWA and sinks. Part of our effort now is to bring sinks to the other models.

**Comment by kmn1024** [comment]
Thanks, really appreciate your work! I will close out my PRs.

I want to take this opportunity to ask you (@davidpissarra) and Charlie (@CharlieFRuan) if there's more information on speculative decoding. Even with shortened context window, the steady state throughput is still too low, and extrapolating from Medusa numbers (my board has smaller warp size), I think something similar would give me a much needed ~1.3x boost.

I would be happy to sponsor a bounty, but 1. the TVM/MLC group seems better funded than myself; 2. I'm not sure if bounties are a source of motivation in academia. Any how, laying this out there, please let me know =)

**Comment by CharlieFRuan** [comment]
Thanks for proposing it! Unfortunately, there isn't too much update in speculative decoding as the team is occupied on various other things (e.g. serving, multi GPU, etc.). We would probably look into that after https://github.com/mlc-ai/mlc-llm/tree/serving lands.

**Comment by junrushao** [comment]
Si-ze and I are on speculative decoding on the serving branch

**Comment by kmn1024** [comment]
Thanks for the replies! @junrushao do you plan on implementing it "bring your own draft model" style, or integrated like Medusa, or something else?

**Comment by jpf888** [comment]
@junrushao  hi， When will medusa be supported on the serve branch? Do you have any plans?
