### ISSUE TITLE
Prefill is very slow on Xiaomi 14 (released in Oct)

### ISSUE THREAD

**Issue by li-jun-jiang** [mlc-ai/mlc-llm#1359]
## 🐛 Bug

Here are the results of tests on my phones and PC.
  On iphone/macbook, the model is CodeLlama-7b-Instruct-hf-q3f16_1
  On xiaomi 14, the model is Llama-2-7b-chat-hf-q4f16_1 and CodeLlama-7b-Instruct-hf-q4f16_1

```
                Prefill     Decode
----------------------------------
xiaomi 14             7         10
iphone 15 pro        56          9
macbook pro 14      133         18

```

BTW: on Xiaomi 14, the Llama-2-7b-chat-hf-q  **3**  f16_1 operates more slowly. The prefill is less than 2 and the decode is less than 3. A prompt with 600 tokens causes the phone to freeze and reboot within minutes.

## To Reproduce

1. run python to compile models (--max-seq-len 768)
2. build MLCChat and run

## Environment

 - Platform (e.g. WebGPU/Vulkan/IOS/Android/CUDA): Android
 - Operating system (e.g. Ubuntu/Windows/MacOS/...): Android
 - Device (e.g. iPhone 12 Pro, PC+RTX 3090, ...): Xiaomi 14
 - How you installed MLC-LLM (`conda`, source): conda
 - How you installed TVM-Unity (`pip`, source): pip
 - Python version (e.g. 3.10): 3.11.6
 - GPU driver version (if applicable):
 - CUDA/cuDNN version (if applicable):
 - TVM Unity Hash Tag (`python -c "import tvm; print('\n'.join(f'{k}: {v}' for k, v in tvm.support.libinfo().items()))"`, applicable if you compile models):
 - Any other relevant information:

**Comment by li-jun-jiang** [comment]
Thanks.

q4f16_0 is better with a prefill of 20 and decode of 5 on the xiaomi 14.

**Comment by kmn1024** [comment]
@Hzfengsy Can you explain a bit the theory behind why `q4f16_0` would lead to faster prefill?

Related to this, I'm wondering if vocab size, or embedding hidden size, has big effects of prefill latency.
