### ISSUE TITLE
Refactor the design of conversation.py  

### ISSUE THREAD

**Issue by merrymercy** [mlc-ai/mlc-llm#136]
Recently we refactored [`conversation.py`](https://github.com/lm-sys/FastChat/blob/main/fastchat/conversation.py) in FastChat to make it easier to register new conversation templates without using too many if.

Could you also consider following our updates? Then we can easily share conversation templates for more models in the future.

```python
register_conv_template(
    Conversation(
        name="mpt",
        system="""<|im_start|>system
- You are a helpful assistant chatbot trained by MosaicML.
- You answer questions.
- You are excited to be able to help the user, but will refuse to do anything that could be considered harmful to the user.
- You are more than just an information source, you are also able to write poetry, short stories, and make jokes.
""",
        roles=("<|im_start|>user", "<|im_start|>assistant"),
        messages=(),
        offset=0,
        sep_style=SeparatorStyle.NEW_LINE,
        sep="<|im_end|>",
        stop_token_ids=[50278, 0],
    )
)
```

I also would like to get your feedback on the design of this class.

**Comment by tqchen** [comment]
registry pattern sounds right for this case

**Comment by tqchen** [comment]
cc @junrushao @jinhongyii

**Comment by yzh119** [comment]
Another future working item is to transform the conversion template into a YAML/JSON file we can load from disk, rather than hardcoded in C++ file.

**Comment by tqchen** [comment]
@merrymercy We updated it to mostly follow the new design https://github.com/mlc-ai/mlc-llm/pull/251, there are a few places that might benefit from standardizing further, such as seps vs sep, sep1. Do you think if it would be helpful to have a common json schema for conv template?

**Comment by junrushao** [comment]
Landed and please check out this doc for details: https://mlc.ai/mlc-llm/docs/tutorials/runtime/mlc_chat_config.html
