### ISSUE TITLE
[Bug] Herman555/dolphin-2.2.1-AshhLimaRP-Mistral-7B mlc_chat_cli exits without error

### ISSUE THREAD

**Issue by 0xDEADFED5** [mlc-ai/mlc-llm#1368]
## To Reproduce

1. grab Herman555/dolphin-2.2.1-AshhLimaRP-Mistral-7B-GGUF (safetensors only) from HF
1. compile without "--use-safetensors" produces this error
1. compile with "--use-safetensors" seems to work, but then mlc_chat_cli exits without error after "Use model library: ..." is printed.  
 i've tested the prebuilt mlc_chat_cli, and also debug/release binaries built myself

## Environment

windows 11, vulkan

## Additional context
i do get these errors when compiling models in Windows: "/concrete_schedule.h:285: ValueError: The block no longer exists in the IRModule",  but vicuna_v1.1 and guanaco models have worked just fine despite them

**Comment by MasterJH5574** [comment]
Hi @0xDEADFED5, thanks for reporting. If the huggingface repository “Herman555/dolphin-2.2.1-AshhLimaRP-Mistral-7B-GGUF” only provides safetensors, then you need to compile with `--use-safetensors` enabled.

Regarding your description
> compile with "--use-safetensors" seems to work, but then mlc_chat_cli exits without error after "Use model library: ..." is printed.

do you mind sharing a bit more about the concrete error messages?

**Comment by 0xDEADFED5** [comment]
okay, i finally got around to updating this and running in a debugger.  i'm on commit fe4a0fa49d7743e97347ab7094a32a062fc291b6, which is the most recent as of this update.

here's the exception i'm getting:

Exception thrown at 0x00007FFCB4646250 (igvk64.dll) in mlc_chat_cli.exe: 0xC0000005: Access violation reading location 0x0000000000000000.

it's happening at line 61 in mlc-llm\3rdparty\tvm\src\runtime\vulkan\vulkan_buffer.cc
at VULKAN_CALL(vkAllocateMemory(device, &mem_info, nullptr, &memory));

i'm able to successfully run 2 other models in the debugger.  not sure what i'm looking for, but i'll keep blindly debugging around.

**Comment by Nick-infinity** [comment]
@0xDEADFED5 did you manage to get it working on windows?

**Comment by 0xDEADFED5** [comment]
@Nick-infinity MLC has changed a lot since then and everything has been working for me using the nightly wheels for months now.

**Comment by 0xDEADFED5** [comment]
sorry i didn't close this before
