### ISSUE TITLE
[Model Request] Qwen-1.8

### ISSUE THREAD

**Issue by MrJungle1** [mlc-ai/mlc-llm#1373]
## ⚙️  Request New Models

- Link to an existing implementation (e.g. Hugging Face/Github): https://huggingface.co/Qwen/Qwen-1_8B
- Is this model architecture supported by MLC-LLM? (the list of [supported models](https://llm.mlc.ai/docs/prebuilt_models.html)) No

## Additional context

This would be a great addition to MLC-LLM since it has only 1.8B parameters and therefor it will use very little RAM making it very suitable for mobile devices, And it has great Chinese capabilities.

**Comment by Tao-begd** [comment]
Looking forward to this model, I think it will have better performance on mobile

**Comment by momomobinx** [comment]
插眼关注

**Comment by CharlieFRuan** [comment]
Please see the Qwen PR: https://github.com/mlc-ai/mlc-llm/pull/1646; we'll release prebuilts soon

**Comment by CharlieFRuan** [comment]
Closing the issue for now. Prebuilt weights released on https://huggingface.co/mlc-ai
