### ISSUE TITLE
[Bug] Memory error after opening installed model on android app

### ISSUE THREAD

**Issue by noknownerrors** [mlc-ai/mlc-llm#1382]
## To Reproduce

1. I compiled this model: https://huggingface.co/Weyaxi/OpenHermes-2.5-neural-chat-7b-v3-1-7B
2. copy it onto my device with the steps from https://llm.mlc.ai/docs/deploy/android.html
3. Open the app on my s23 ultra. Click chat -> say hello -> crash

/home/user/documents/mlc-llm/3rdparty/tvm/src/runtime/opencl/opencl_device_api.cc:238: InternalError: Check failed: (err_code == CL_SUCCESS) is false: OpenCL Error, code=-61: CL_INVALID_BUFFER_SIZE
2023-12-04 18:37:04.362 13338-13419 TVM_RUNTIME             ai.mlc.mlcchat                       A  /home/user/documents/mlc-llm/3rdparty/tvm/include/tvm/runtime/packed_func.h:1346: unknown type = 0
2023-12-04 18:37:04.362 13338-13419 TVM_RUNTIME             ai.mlc.mlcchat                       A  /home/user/documents/mlc-llm/3rdparty/tvm/src/runtime/memory/memory_manager.cc:162: Allocator for 
2023-12-04 18:37:04.362 13338-13419 libc++abi               ai.mlc.mlcchat                       E  terminating due to uncaught exception of type tvm::runtime::InternalError: [18:37:04] /home/user/documents/mlc-llm/3rdparty/tvm/src/runtime/memory/memory_manager.cc:162: Allocator for 
                                                                                                    Stack trace not available when DMLC_LOG_STACK_TRACE is disabled at compile time.
2023-12-04 18:37:04.364 13338-13419 libc                    ai.mlc.mlcchat                       A  Fatal signal 6 (SIGABRT), code -1 (SI_QUEUE) in tid 13419 (pool-3-thread-1), pid 13338 (ai.mlc.mlcchat)

## Expected behavior

Chat with the model

## Environment

 - Platform (e.g. WebGPU/Vulkan/IOS/Android/CUDA): Android
 - Operating system (e.g. Ubuntu/Windows/MacOS/...): Windows
 - Device (e.g. iPhone 12 Pro, PC+RTX 3090, ...) 
 - How you installed MLC-LLM (`conda`, source): conda
 - How you installed TVM-Unity (`pip`, source): the wheel in the docs
 - Python version (e.g. 3.10): 3.11.5
 - GPU driver version (if applicable):
 - CUDA/cuDNN version (if applicable):
 - TVM Unity Hash Tag (`python -c "import tvm; print('\n'.join(f'{k}: {v}' for k, v in tvm.support.libinfo().items()))"`, applicable if you compile models):
```
USE_NVTX: OFF
USE_GTEST: AUTO
SUMMARIZE: OFF
USE_IOS_RPC: OFF
USE_MSC: OFF
USE_ETHOSU:
CUDA_VERSION: NOT-FOUND
USE_LIBBACKTRACE: AUTO
DLPACK_PATH: 3rdparty/dlpack/include
USE_TENSORRT_CODEGEN: OFF
USE_THRUST: OFF
USE_TARGET_ONNX: OFF
USE_AOT_EXECUTOR: ON
BUILD_DUMMY_LIBTVM: OFF
USE_CUDNN: OFF
USE_TENSORRT_RUNTIME: OFF
USE_ARM_COMPUTE_LIB_GRAPH_EXECUTOR: OFF
USE_CCACHE: AUTO
USE_ARM_COMPUTE_LIB: OFF
USE_CPP_RTVM:
USE_OPENCL_GTEST: /path/to/opencl/gtest
USE_MKL: OFF
USE_PT_TVMDSOOP: OFF
MLIR_VERSION: NOT-FOUND
USE_CLML: OFF
USE_STACKVM_RUNTIME: OFF
USE_GRAPH_EXECUTOR_CUDA_GRAPH: OFF
ROCM_PATH: /opt/rocm
USE_DNNL: OFF
USE_VITIS_AI: OFF
USE_MLIR: OFF
USE_RCCL: OFF
USE_LLVM: llvm-config --link-static
USE_VERILATOR: OFF
USE_TF_TVMDSOOP: OFF
USE_THREADS: ON
USE_MSVC_MT: OFF
BACKTRACE_ON_SEGFAULT: OFF
USE_GRAPH_EXECUTOR: ON
USE_NCCL: OFF
USE_ROCBLAS: OFF
GIT_COMMIT_HASH: 189412e9ad52fee4dc3dc46bcf60d820e82422d8
USE_VULKAN: ON
USE_RUST_EXT: OFF
USE_CUTLASS: OFF
USE_CPP_RPC: OFF
USE_HEXAGON: OFF
USE_CUSTOM_LOGGING: OFF
USE_UMA: OFF
USE_FALLBACK_STL_MAP: OFF
USE_SORT: ON
USE_RTTI: ON
GIT_COMMIT_TIME: 2023-11-22 10:29:46 -0500
USE_HEXAGON_SDK: /path/to/sdk
USE_BLAS: none
USE_ETHOSN: OFF
USE_LIBTORCH: OFF
USE_RANDOM: ON
USE_CUDA: OFF
USE_COREML: OFF
USE_AMX: OFF
BUILD_STATIC_RUNTIME: OFF
USE_CMSISNN: OFF
USE_KHRONOS_SPIRV: OFF
USE_CLML_GRAPH_EXECUTOR: OFF
USE_TFLITE: OFF
USE_HEXAGON_GTEST: /path/to/hexagon/gtest
PICOJSON_PATH: 3rdparty/picojson
USE_OPENCL_ENABLE_HOST_PTR: OFF
INSTALL_DEV: OFF
USE_PROFILER: ON
USE_NNPACK: OFF
LLVM_VERSION: 17.0.6
USE_OPENCL: OFF
COMPILER_RT_PATH: 3rdparty/compiler-rt
RANG_PATH: 3rdparty/rang/include
USE_SPIRV_KHR_INTEGER_DOT_PRODUCT: OFF
USE_OPENMP: OFF
USE_BNNS: OFF
USE_CUBLAS: OFF
USE_METAL: OFF
USE_MICRO_STANDALONE_RUNTIME: OFF
USE_HEXAGON_EXTERNAL_LIBS: OFF
USE_ALTERNATIVE_LINKER: AUTO
USE_BYODT_POSIT: OFF
USE_HEXAGON_RPC: OFF
USE_MICRO: OFF
DMLC_PATH: 3rdparty/dmlc-core/include
INDEX_DEFAULT_I64: ON
USE_RELAY_DEBUG: OFF
USE_RPC: ON
USE_TENSORFLOW_PATH: none
TVM_CLML_VERSION:
USE_MIOPEN: OFF
USE_ROCM: OFF
USE_PAPI: OFF
USE_CURAND: OFF
TVM_CXX_COMPILER_PATH: C:/Program Files/Microsoft Visual Studio/2022/Enterprise/VC/Tools/MSVC/14.37.32822/bin/HostX64/x64/cl.exe
HIDE_PRIVATE_SYMBOLS: OFF
```
 - Any other relevant information:

**Comment by CharlieFRuan** [comment]
Hi we recently updated our Android flow and the documentation correspondingly: https://github.com/mlc-ai/mlc-llm/pull/1494. Check if the error still persists.

Besides, this could also be an issue of the model demanding too much memory. Try to tweak `prefill_chunk_size`, `context_window_size` and `sliding_window_size` when compiling the model; for more about these params, see `python -m mlc_chat gen_config --help`. 

We also print out an estimated memory requirement for each model compiled, something like this would be printed out:
```
[2024-02-08 20:49:38] INFO model_metadata.py:95: Total memory usage: 3730.64 MB (Parameters: 3615.13 MB. KVCache: 0.00 MB. Temporary buffer: 115.51 MB)
[2024-02-08 20:49:38] INFO model_metadata.py:104: To reduce memory usage, tweak `prefill_chunk_size`, `context_window_size` and `sliding_window_size`
```

**Comment by CharlieFRuan** [comment]
Closing this one for now; feel free to open another one if issues persist!
