### ISSUE TITLE
[Doc] Add Android documentation on how to compile and load models

### ISSUE THREAD

**Issue by tobrun** [mlc-ai/mlc-llm#1383]
## 📚 Documentation

As part of https://github.com/mlc-ai/mlc-llm/pull/1248#issuecomment-1811622752, I was looking to see which parts of the documentation needing updates but now noticing we don't have any concrete docs on how to compile models and deploy them on an Android application. Creating this issue to track the addition of this documentation.

**Comment by CharlieFRuan** [comment]
Hi @tobrun, thanks for the suggestion! The Android flow and documentation was updated quite a lot recently via https://github.com/mlc-ai/mlc-llm/pull/1494.

Closing this issue for now; but definitely feel free to open another one!!
