### ISSUE TITLE
[Feature Request] Add CI for all supported platforms

### ISSUE THREAD

**Issue by tobrun** [mlc-ai/mlc-llm#1384]
## 🚀 Feature

Continuous integration bots for all supported platforms

## Motivation

CI is needed to be able to quickly iterate on the codebase, ensure nothing breaks and enforce quality gates.

At minimum the code for a given platform should compile.

Bonus points for:
 - running static code analysis to ensure code quality
 - running some kind of smoke test on real hardware (ensure not runtime crash occurs)
 - capture and track metric data (eg. token throughput, initial load time, etc.)

**Comment by MasterJH5574** [comment]
Thank you @tobrun for the suggestion! Yes we have the plan of setting up basic CI to ensure new changes don't break things. Right now we have basic code format and lint tests, and more will be set up in the future.

**Comment by junrushao** [comment]
Yeah I'm actually working on it: https://github.com/mlc-ai/env
