### ISSUE TITLE
何时支持 Qwen/Qwen-1_8B-Chat-Int4 呢？目前llama.cpp已经支持了Qwen。

### ISSUE THREAD

**Issue by Pangu-Immortal** [mlc-ai/mlc-llm#1390]
llama.cpp 上周已经支持了Qwen，MLC-LLM何时支持Qwen呢？或者给出Qwen的集成方式，毕竟Llama-2-7b-和RedPajama-INCITE-Chat-3B都太大了，Qwen1.8B，这两天通过llama.cpp测试结果，在Android端的资源占用非常少，强烈建议给出一个Qwen1.8B资料，也许架构上可能已经支持了Qwen1.8B，但是我不知道如何把 Qwen/Qwen-1_8B-Chat-Int4 集成到MLC-LLM项目里面。。

**Comment by Hzfengsy** [comment]
Thanks for your interest. It's duplicated with https://github.com/mlc-ai/mlc-llm/issues/1373. Please track the [Model Request Tracking](https://github.com/orgs/mlc-ai/projects/2/views/1) and that issue for the update.
