### ISSUE TITLE
[Bug] Gradio not launching

### ISSUE THREAD

**Issue by rxjx** [mlc-ai/mlc-llm#1395]
## 🐛 Bug
While in the conda env with python 3.11, using the latest nightly for M1, and Llama-2-13b-chat-hf-q4f16_1, the python script works fine as does executing the model via the python prompt. However, initiating Gradio crashes.

(mlc_llm) ~/src/mlc_llm%python -m mlc_chat.gradio --device metal:0

/Users/rj/miniforge3/envs/mlc_llm/lib/python3.11/site-packages/gradio/layouts/column.py:55: UserWarning: 'scale' value should be an integer. Using 0.3 will cause issues.
  warnings.warn(
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/Users/rj/miniforge3/envs/mlc_llm/lib/python3.11/site-packages/mlc_chat/gradio.py", line 247, in <module>
    launch_gradio(ARGS.artifact_path, ARGS.device, ARGS.port, ARGS.share, ARGS.host)
  File "/Users/rj/miniforge3/envs/mlc_llm/lib/python3.11/site-packages/mlc_chat/gradio.py", line 242, in launch_gradio
    demo.launch(share=share, enable_queue=True, server_port=port, server_name=host)
TypeError: Blocks.launch() got an unexpected keyword argument 'enable_queue'`

**Comment by gatepoet** [comment]
It's easy fix yourself. Edit the file `/Users/rj/miniforge3/envs/mlc_llm/lib/python3.11/site-packages/mlc_chat/gradio.py`, or if you're installing mlc_chat from local source `./python/mlc_chat/gradio.py`

At the end of the file, on line 242, change the following:
```python
    demo.launch(share=share, enable_queue=True, server_port=port, server_name=host)
```

to:

```python
    demo.queue(max_size=10)
    demo.launch(share=share, server_port=port, server_name=host)
```

and you should be able to run the gradio frontend
