### ISSUE TITLE
[Bug] libmlc_llm_module.dylib

### ISSUE THREAD

**Issue by zyxcambridge** [mlc-ai/mlc-llm#1398]
(tvm-build-venv) zhangyixin@zhangyixin python % python3  -c "from mlc_chat import ChatModule; print(ChatModule)"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/zhangyixin/Desktop/mlc-llm/mlc-llm/python/mlc_chat/__init__.py", line 6, in <module>
    from .chat_module import ChatModule
  File "/Users/zhangyixin/Desktop/mlc-llm/mlc-llm/python/mlc_chat/chat_module.py", line 13, in <module>
    from . import callback
  File "/Users/zhangyixin/Desktop/mlc-llm/mlc-llm/python/mlc_chat/callback.py", line 4, in <module>
    from .base import get_delta_message
  File "/Users/zhangyixin/Desktop/mlc-llm/mlc-llm/python/mlc_chat/base.py", line 25, in <module>
    _LIB, _LIB_PATH = _load_mlc_llm_lib()
                      ^^^^^^^^^^^^^^^^^^^
  File "/Users/zhangyixin/Desktop/mlc-llm/mlc-llm/python/mlc_chat/base.py", line 19, in _load_mlc_llm_lib
    lib_path = libinfo.find_lib_path(lib_name, optional=False)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/zhangyixin/Desktop/mlc-llm/mlc-llm/python/mlc_chat/libinfo.py", line 72, in find_lib_path
    raise RuntimeError(message)
RuntimeError: Cannot find libraries: libmlc_llm_module.dylib
List of candidates:
/Users/zhangyixin/Desktop/mlc-llm/mlc-llm/python/mlc_chat/libmlc_llm_module.dylib
/Users/zhangyixin/anaconda3/envs/tvm-build-venv/lib/libmlc_llm_module.dylib

/Users/zhangyixin/anaconda3/envs/tvm-build-venv/lib/libmlc_llm_module.dylib
(tvm-build-venv) zhangyixin@zhangyixin python % pip install -e "."                                                                          
Looking in indexes: https://mirrors.aliyun.com/pypi/simple
Obtaining file:///Users/zhangyixin/Desktop/mlc-llm/mlc-llm/python
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [15 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/Users/zhangyixin/Desktop/mlc-llm/mlc-llm/python/setup.py", line 47, in <module>
          LIB_LIST, __version__ = get_lib_path()
                                  ^^^^^^^^^^^^^^
        File "/Users/zhangyixin/Desktop/mlc-llm/mlc-llm/python/setup.py", line 27, in get_lib_path
          libinfo["find_lib_path"]("mlc_llm")[0],
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/zhangyixin/Desktop/mlc-llm/mlc-llm/python/./mlc_chat/libinfo.py", line 72, in find_lib_path
          raise RuntimeError(message)
      RuntimeError: Cannot find libraries: libmlc_llm.dylib
      List of candidates:
      /Users/zhangyixin/Desktop/mlc-llm/mlc-llm/python/mlc_chat/libmlc_llm.dylib
      /Users/zhangyixin/anaconda3/envs/tvm-build-venv/lib/libmlc_llm.dylib
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
(tvm-build-venv) zhangyixin@zhangyixin python %

**Comment by Hzfengsy** [comment]
How did you install it? via pip or compile by yourself

**Comment by 2665477495** [comment]
same error with win11, cuda12.2

` D:\code_ai\mlc-llm\python>pip install -e "."
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Obtaining file:///D:/code_ai/mlc-llm/python
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [97 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "D:\code_ai\mlc-llm\python\setup.py", line 47, in <module>
          LIB_LIST, __version__ = get_lib_path()
        File "D:\code_ai\mlc-llm\python\setup.py", line 27, in get_lib_path
          libinfo["find_lib_path"]("mlc_llm")[0],
        File "D:\code_ai\mlc-llm\python\./mlc_chat/libinfo.py", line 72, in find_lib_path
          raise RuntimeError(message)
      RuntimeError: Cannot find libraries: mlc_llm.dll
      List of candidates:
      D:\code_ai\mlc-llm\python\mlc_chat\mlc_llm.dll
      C:\Users\zhiwei\anaconda3\envs\torchenv\lib\mlc_llm.dll
      C:\Users\zhiwei\anaconda3\envs\torchenv\mlc_llm.dll
      C:\Users\zhiwei\anaconda3\envs\torchenv\Library\mingw-w64\bin\mlc_llm.dll
      C:\Users\zhiwei\anaconda3\envs\torchenv\Library\bin\mlc_llm.dll
      C:\Users\zhiwei\anaconda3\envs\torchenv\Scripts\mlc_llm.dll
      C:\Users\zhiwei\anaconda3\envs\torchenv\bin\mlc_llm.dll
      C:\Users\zhiwei\anaconda3\condabin\mlc_llm.dll
      C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.1\bin\mlc_llm.dll
      C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.1\libnvvp\mlc_llm.dll
      C:\Program Files\Microsoft\jdk-11.0.16.101-hotspot\bin\mlc_llm.dll
      C:\windows\system32\mlc_llm.dll
      C:\windows\mlc_llm.dll
      C:\windows\System32\Wbem\mlc_llm.dll
      C:\windows\System32\WindowsPowerShell\v1.0\mlc_llm.dll
      C:\windows\System32\OpenSSH\mlc_llm.dll
      C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common\mlc_llm.dll
      C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR\mlc_llm.dll
      C:\WINDOWS\system32\mlc_llm.dll
      C:\WINDOWS\mlc_llm.dll
      C:\WINDOWS\System32\Wbem\mlc_llm.dll
      C:\WINDOWS\System32\WindowsPowerShell\v1.0\mlc_llm.dll
      C:\WINDOWS\System32\OpenSSH\mlc_llm.dll
      C:\Program Files\Pandoc\mlc_llm.dll
      C:\Users\zhiwei\anaconda3\mlc_llm.dll
      C:\Users\zhiwei\anaconda3\Scripts\mlc_llm.dll
      C:\Users\zhiwei\anaconda3\Library\mingw-w64\bin\mlc_llm.dll
      C:\Users\zhiwei\anaconda3\Library\usr\bin\mlc_llm.dll
      C:\Users\zhiwei\anaconda3\Library\bin\mlc_llm.dll
      C:\Users\zhiwei\AppData\Roaming\nvm\mlc_llm.dll
      C:\Program Files\nodejs\mlc_llm.dll
      C:\Program Files\Go\bin\mlc_llm.dll
      C:\Program Files\dotnet\mlc_llm.dll
      C:\Program Files\Microsoft VS Code\bin\mlc_llm.dll
      C:\Program Files\Microsoft SQL Server\150\Tools\Binn\mlc_llm.dll
      C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\170\Tools\Binn\mlc_llm.dll
      C:\Program Files (x86)\Windows Kits\10\Windows Performance Toolkit\mlc_llm.dll
      C:\Program Files\MySQL\MySQL Server 8.0\bin\mlc_llm.dll
      C:\Program Files\NVIDIA Corporation\Nsight Compute 2023.1.0\mlc_llm.dll
      C:\Program Files (x86)\GnuPG\bin\mlc_llm.dll
      D:\Program Files (x86)\Graphviz\bin\mlc_llm.dll
      C:\Program Files\Git\cmd\mlc_llm.dll
      C:\Program Files\CMake\bin\mlc_llm.dll
      C:\Program Files\MySQL\MySQL Shell 8.0\bin\mlc_llm.dll
      C:\Users\zhiwei\AppData\Roaming\nvm\mlc_llm.dll
      C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.1\bin\mlc_llm.dll
      C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.1\libnvvp\mlc_llm.dll
      C:\Program Files\Microsoft\jdk-11.0.16.101-hotspot\bin\mlc_llm.dll
      C:\windows\system32\mlc_llm.dll
      C:\windows\mlc_llm.dll
      C:\windows\System32\Wbem\mlc_llm.dll
      C:\windows\System32\WindowsPowerShell\v1.0\mlc_llm.dll
      C:\windows\System32\OpenSSH\mlc_llm.dll
      C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common\mlc_llm.dll
      C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR\mlc_llm.dll
      C:\WINDOWS\system32\mlc_llm.dll
      C:\WINDOWS\mlc_llm.dll
      C:\WINDOWS\System32\Wbem\mlc_llm.dll
      C:\WINDOWS\System32\WindowsPowerShell\v1.0\mlc_llm.dll
      C:\WINDOWS\System32\OpenSSH\mlc_llm.dll
      C:\Program Files\Pandoc\mlc_llm.dll
      C:\Users\zhiwei\anaconda3\mlc_llm.dll
      C:\Users\zhiwei\anaconda3\Scripts\mlc_llm.dll
      C:\Users\zhiwei\anaconda3\Library\mingw-w64\bin\mlc_llm.dll
      C:\Users\zhiwei\anaconda3\Library\usr\bin\mlc_llm.dll
      C:\Users\zhiwei\anaconda3\Library\bin\mlc_llm.dll
      C:\Users\zhiwei\AppData\Roaming\nvm\mlc_llm.dll
      C:\Program Files\nodejs\mlc_llm.dll
      C:\Program Files\Go\bin\mlc_llm.dll
      C:\Program Files\dotnet\mlc_llm.dll
      C:\Program Files\Microsoft VS Code\bin\mlc_llm.dll
      C:\Program Files\Microsoft SQL Server\150\Tools\Binn\mlc_llm.dll
      C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\170\Tools\Binn\mlc_llm.dll
      C:\Program Files (x86)\Windows Kits\10\Windows Performance Toolkit\mlc_llm.dll
      C:\Program Files\MySQL\MySQL Server 8.0\bin\mlc_llm.dll
      C:\Program Files\NVIDIA Corporation\Nsight Compute 2023.1.0\mlc_llm.dll
      C:\Program Files (x86)\GnuPG\bin\mlc_llm.dll
      D:\Program Files (x86)\Graphviz\bin\mlc_llm.dll
      C:\Program Files\Git\cmd\mlc_llm.dll
      C:\Program Files\CMake\bin\mlc_llm.dll
      D:\Program Files (x86)\PyCharm Community Edition 2023.2.5\bin\mlc_llm.dll
      D:\code_ai\mlc-llm\python\mlc_llm.dll
      C:\Users\zhiwei\AppData\Local\GitHubDesktop\bin\mlc_llm.dll
      D:\code_ai\mlc-llm\python\mlc_llm.dll
      C:\Program Files\JetBrains\DataGrip 2023.2.1\bin\mlc_llm.dll
      D:\code_ai\mlc-llm\python\mlc_llm.dll
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.`

**Comment by 2665477495** [comment]
I sove it. just copy mlc_llm.dll and mlc_llm_module.dll  before pip uninstall mlc-chat-nightly. And add it ainto 'C:\Users\***\anaconda3\envs\yourenvname'. After that you could run pip install -e "." successfully!😋

**Comment by Hzfengsy** [comment]
Close it as the author did not reply for 2 weeks. Feel free to reopen it if you would update your information
