### ISSUE TITLE
[Feature Request] [REST] Add a /v1/models REST API endpoint

### ISSUE THREAD

**Issue by CamilleHbp** [mlc-ai/mlc-llm#1400]
## 🚀 Feature
It would be nice to get a `/v1/models` REST endpoint with a behaviour similar to [OpenAI](https://platform.openai.com/docs/api-reference/models/list) or [oobabooga/Text-Generation-WebUI](https://github.com/oobabooga/text-generation-webui/wiki/12-%E2%80%90-OpenAI-API#compatibility--not-so-compatibility): lists models, currently loaded model first.

## Motivation
I am writing a connector for MLC-LLM in [SillyTavern](https://github.com/SillyTavern/SillyTavern). There is currently no way to get a status report and a model list from MLC-LLM. This would be wonderful to increase the discovery and use of the project since SillyTavern is used by many people. It would also allow us to use existing models without having to remember the exact name of the model and if we installed it in MLC-LLM.

## Alternatives
I don't know of any?

## Additional context
None.

**Comment by Kartik14** [comment]
This is supported now. Closing this issue.
