### ISSUE TITLE
[Bug] Prebuilt wheel not available for MacOS 12

### ISSUE THREAD

**Issue by neubig** [mlc-ai/mlc-llm#1403]
## 🐛 Bug

I tried to follow the Mac install directions [here](https://llm.mlc.ai/docs/install/mlc_llm.html) in a new conda environment.

## To Reproduce

1. `conda create --name=mlc-llm python=3.11`
1. `conda activate mlc-llm`
1. `python3 -m pip install --pre -U -f https://mlc.ai/wheels mlc-chat-nightly mlc-ai-nightly`

This resulted in the following error:

```
$ python3 -m pip install --pre -U -f https://mlc.ai/wheels mlc-chat-nightly mlc-ai-nightly

Looking in links: https://mlc.ai/wheels
ERROR: Could not find a version that satisfies the requirement mlc-chat-nightly (from versions: none)
ERROR: No matching distribution found for mlc-chat-nightly
```

## Expected behavior

I would expect installation to work.

## Environment

 - Platform (e.g. WebGPU/Vulkan/IOS/Android/CUDA): Apple Silicon (`osx-arm64`)
 - Operating system (e.g. Ubuntu/Windows/MacOS/...): MacOS Monterey
 - Device (e.g. iPhone 12 Pro, PC+RTX 3090, ...): MacBook Pro
 - How you installed MLC-LLM (`conda`, source): `conda 23.3.1`
 - How you installed TVM-Unity (`pip`, source): `pip 23.3.1`
 - Python version (e.g. 3.10): `Python 3.11.5`
 - GPU driver version (if applicable): N/A
 - CUDA/cuDNN version (if applicable): N/A
 - TVM Unity Hash Tag (`python -c "import tvm; print('\n'.join(f'{k}: {v}' for k, v in tvm.support.libinfo().items()))"`, applicable if you compile models): N/A
 - Any other relevant information: N/A

**Comment by tqchen** [comment]
Thanks for reporting! Seems the issue was due to the fact that the nightly wheel atm was built for macos 13 (Ventura) or higher and macOS Monterey was version 12.

**Comment by neubig** [comment]
Ah, I guess I should upgrade then!

**Comment by egaoneko** [comment]
@tqchen
The same error occurs in Sonoma version 14. Are there any plans to build a nightly wheel ATM for version 14?

**Comment by MasterJH5574** [comment]
Hi @egaoneko, we have renamed the package name to `mlc-llm-nightly`. It should work for Sonoma. Could you check if you put in the correct name? See the documentation here https://llm.mlc.ai/docs/install/mlc_llm.html. I am on Sonoma and I can install the package:
```
> python -m pip install --upgrade --pre mlc-ai-nightly mlc-llm-nightly -f https://mlc.ai/wheels
Looking in links: https://mlc.ai/wheels
Requirement already satisfied: mlc-ai-nightly in ./Work/mlc-llm-iphone/lib/python3.12/site-packages (0.15.dev154)
Collecting mlc-ai-nightly
  Downloading https://github.com/mlc-ai/package/releases/download/v0.9.dev0/mlc_ai_nightly-0.15.dev184-cp312-cp312-macosx_13_0_arm64.whl (79.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 79.0/79.0 MB 12.7 MB/s eta 0:00:00
Requirement already satisfied: mlc-llm-nightly in ./Work/mlc-llm-iphone/lib/python3.12/site-packages (0.1.dev1013)
Collecting mlc-llm-nightly
  Downloading https://github.com/mlc-ai/package/releases/download/v0.9.dev0/mlc_llm_nightly-0.1.dev1053-cp312-cp312-macosx_13_0_arm64.whl (6.9 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.9/6.9 MB 13.2 MB/s eta 0:00:00
...
Installing collected packages: mlc-ai-nightly, mlc-llm-nightly
  Attempting uninstall: mlc-ai-nightly
    Found existing installation: mlc-ai-nightly 0.15.dev154
    Uninstalling mlc-ai-nightly-0.15.dev154:
      Successfully uninstalled mlc-ai-nightly-0.15.dev154
  Attempting uninstall: mlc-llm-nightly
    Found existing installation: mlc-llm-nightly 0.1.dev1013
    Uninstalling mlc-llm-nightly-0.1.dev1013:
      Successfully uninstalled mlc-llm-nightly-0.1.dev1013
Successfully installed mlc-ai-nightly-0.15.dev184 mlc-llm-nightly-0.1.dev1053

> neofetch
                    'c.          masterjh5574@ruihangs-mbp-2.wifi.local.cmu.edu
                 ,xNMM.          ----------------------------------------------
               .OMMMMo           OS: macOS 14.3.1 23D60 arm64
               OMMM0,            Host: MacBookPro18,1
     .;loddo:' loolloddol;.      Kernel: 23.3.0
   cKMMMMMMMMMMNWMMMMMMMMMM0:    Uptime: 23 hours, 59 mins
 .KMMMMMMMMMMMMMMMMMMMMMMMWd.    Packages: 133 (brew)
 XMMMMMMMMMMMMMMMMMMMMMMMX.      Shell: zsh 5.9
;MMMMMMMMMMMMMMMMMMMMMMMM:       Resolution: 1920x1080, 1920x1080
:MMMMMMMMMMMMMMMMMMMMMMMM:       DE: Aqua
.MMMMMMMMMMMMMMMMMMMMMMMMX.      WM: Quartz Compositor
 kMMMMMMMMMMMMMMMMMMMMMMMMWd.    WM Theme: Blue (Light)
 .XMMMMMMMMMMMMMMMMMMMMMMMMMMk   Terminal: iTerm2
  .XMMMMMMMMMMMMMMMMMMMMMMMMK.   Terminal Font: MesloLGS-NF-Regular 14
    kMMMMMMMMMMMMMMMMMMMMMMd     CPU: Apple M1 Pro
     ;KMMMMMMMWXXWMMMMMMMk.      GPU: Apple M1 Pro
       .cooc,.    .,coo:.        Memory: 2519MiB / 16384MiB
```

I am going to close this issue given the original macOS 12 issue was concluded. You are more than welcome to open a new one if there is anything wrong with the installation on Sonoma.
