### ISSUE TITLE
[Question]  I can't add a small 2.5B model

### ISSUE THREAD

**Issue by suoko** [mlc-ai/mlc-llm#1406]
## ❓ General Questions

I wanted to try the smallest models from your repo https://huggingface.co/mlc-ai , those with 2.5B, but it gives me errors when trying to add them.
Am I doing something wrong?

**Comment by anibohara2000** [comment]
Could you please provide some more information.
What platform are you using? 
What steps are you following? 
What is the error that you are getting?

**Comment by suoko** [comment]
> Could you please provide some more information. What platform are you using? What steps are you following? What is the error that you are getting?

![Screenshot_2023-12-12-22-20-21-253_ai mlc mlcchat](https://github.com/mlc-ai/mlc-llm/assets/3659980/13a34323-dfc1-4cd4-aa4f-dd2d0c64db10)

**Comment by suoko** [comment]
![Uploading Screenshot_2023-12-12-22-22-05-350_ai.mlc.mlcchat.jpg…]()
