### ISSUE TITLE
No cropping on Android?

### ISSUE THREAD

**Issue by GameOverFlowChart** [mlc-ai/mlc-llm#141]
It seems like if an output is too long, that the ai doesn't have any memory about the passed conversation anymore. Instead the passed conversation should be cropped so that it fits into its context again.

Edit: This happened multiple times but of course it might be just a flaw of the model that gives me the illusion that it forgot the whole conversation.

**Comment by GameOverFlowChart** [comment]
> Sliding window attention is added recently to support this

What I was describing was not Sliding Window and this is a different problem (sliding window tries to make the effective window bigger, while I'm talking about making use of the full windows by cropping what doesn't fit as a whole).
But if the implementation of Sliding Window also fixes this at the same time, I'm fine.

**Comment by tqchen** [comment]
Currently the chat module likely will slide over and effectively do what you meant by cropping. There used to be a bug of such sliding which i think was fixed a while ago, happy to check over if we have an example if it happens again
