### ISSUE TITLE
[Bug] 我按照Android的编译文档尝试编译Android端可用的so和jar包，在Ubuntu系统。

### ISSUE THREAD

**Issue by Pangu-Immortal** [mlc-ai/mlc-llm#1428]
我验证了自己的开发环境，Rust、NDK、conda，CUDA，环境目前没有问题，我成功变异了TVM并且加入了path环境变量。
我全程在conda环境中进行的：
`
conda create -n mlc-chat-venv -c mlc-ai -c conda-forge mlc-chat-cli-nightly
conda activate mlc-chat-venv
`

我通过教程：https://llm.mlc.ai/docs/compilation/compile_models.html
已经成功拉取了模型文件，
`python3 -m mlc_llm.build --hf-path togethercomputer/RedPajama-INCITE-Chat-3B-v1 --target android --max-seq-len 768 --quantization q4f16_1`

检查时：
`~/mlc-llm > ls dist/RedPajama-INCITE-Chat-3B-v1-q4f16_1
  RedPajama-INCITE-Chat-3B-v1-q4f16_1-android.tar  # ===> the model library
  mod_cache_before_build_android.pkl               # ===> a cached file for future builds
  params                                           # ===> containing the model weights, tokenizer and chat config

~/mlc-llm > ls dist/RedPajama-INCITE-Chat-3B-v1-q4f16_1/params
  mlc-chat-config.json                             # ===> the chat config
  ndarray-cache.json                               # ===> the model weight info
  params_shard_0.bin                               # ===> the model weights
  params_shard_1.bin
  ...
  tokenizer.json                                   # ===> the tokenizer files
  tokenizer_config.json`

到目前为止，一切正常。

我按照Android的教程，文档地址：https://llm.mlc.ai/docs/deploy/android.html

`cd ./android/`
然后：
`./prepare_libs.sh`

我全程都在conda环境中进行的，到这一步我出现了一些错误，我尝试着检查了一遍，目前为止，我不知道如何下手，我已经翻了很多网上的资料，似乎没有人遇到这个问题。我的详细构建细节如下：
`
(mlc-chat-venv) qihao@qihao-System-Product-Name:/media/qihao/D/ai/mlc-llm/android$ ./prepare_libs.sh
+ rustup target add aarch64-linux-android
info: component 'rust-std' for target 'aarch64-linux-android' is up to date
+ mkdir -p build/model_lib
+ python prepare_model_lib.py
Creating lib from ['/media/qihao/D/ai/mlc-llm/dist/RedPajama-INCITE-Chat-3B-v1-q4f16_1/RedPajama-INCITE-Chat-3B-v1-q4f16_1-android.tar']..
+ cd build
+ touch config.cmake
+ '[' /home/qihao/anaconda3/envs/mlc-chat-venv/lib/python3.10/site-packages/tvm -ne 0 ']'
./prepare_libs.sh: 第 12 行： [: /home/qihao/anaconda3/envs/mlc-chat-venv/lib/python3.10/site-packages/tvm: 需要整数表达式
+ cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=/home/qihao/android-ndk-r26b/build/cmake/android.toolchain.cmake -DCMAKE_INSTALL_PREFIX=. -DCMAKE_CXX_FLAGS=-O3 -DANDROID_ABI=arm64-v8a -DANDROID_NATIVE_API_LEVEL=android-24 -DANDROID_PLATFORM=android-24 -DCMAKE_FIND_ROOT_PATH_MODE_PACKAGE=ON -DANDROID_STL=c++_static -DUSE_HEXAGON_SDK=OFF -DMLC_LLM_INSTALL_STATIC_LIB=ON -DCMAKE_SKIP_INSTALL_ALL_DEPENDENCY=ON -DUSE_OPENCL=ON -DUSE_CUSTOM_LOGGING=ON
-- The C compiler identification is Clang 17.0.2
-- The CXX compiler identification is Clang 17.0.2
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /home/qihao/android-ndk-r26b/toolchains/llvm/prebuilt/linux-x86_64/bin/clang - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /home/qihao/android-ndk-r26b/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Performing Test SUPPORT_CXX17
-- Performing Test SUPPORT_CXX17 - Success
-- Hide private symbols
-- TVM_HOME: 3rdparty/tvm
-- Hide private symbols...
-- Forbidding undefined symbols in shared library, using -Wl,--no-undefined on platform Android
-- Building for Android
-- Didn't find the path to CCACHE, disabling ccache
-- VTA build with VTA_HW_PATH=/media/qihao/D/ai/mlc-llm/3rdparty/tvm/3rdparty/vta-hw
-- Build VTA runtime with target: sim
-- Enabled runtime search for OpenCL library location
-- Couldn't build OpenCL-Gtests
-- Android Vulkan_INCLUDE_DIRS=/home/qihao/android-ndk-r26b/sources/third_party/vulkan/src/include
-- Skip finding SPIRV in Android, make sure you only build tvm runtime.
-- Build with contrib.random
-- Build with contrib.sort
-- Build with contrib.hybriddump
-- Git found: /home/qihao/anaconda3/envs/mlc-chat-venv/bin/git
-- Found TVM_GIT_COMMIT_HASH=0ed0be0fdf006e9a9ae52f48e1cd25f0cc2c4637
-- Found TVM_GIT_COMMIT_TIME=2023-12-04 15:08:36 -0500
-- Building with TVM Map...
-- Build with thread support...
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Check if compiler accepts -pthread
-- Check if compiler accepts -pthread - yes
-- Found Threads: TRUE  
-- CLANG_VERSION 17.0
-- Setting enhanced clang warning flags
-- Performing Test FILE_PREFIX_MAP_SUPPORTED
-- Performing Test FILE_PREFIX_MAP_SUPPORTED - Success
-- Added "-fuse-ld=lld" to linker flags -static-libstdc++ -Wl,--build-id=sha1 -Wl,--no-rosegment -Wl,--no-undefined-version -Wl,--fatal-warnings -Wl,--no-undefined -Qunused-arguments 
-- Build without FlashInfer
-- system-nameAndroid
-- Could NOT find Doxygen (missing: DOXYGEN_EXECUTABLE) 
-- VERSION: 0.2.00
CMake Warning at /media/qihao/D/ai/mlc-llm/CMakeLists.txt:103 (message):
  Cannot find libflash_attn.  The model must not have been built with
  --use-flash-attn-mqa option.

-- TVM_HOME: /media/qihao/D/ai/mlc-llm/android/../3rdparty/tvm
-- Found Java: /usr/bin/java (found version "17.0.9") 
CMake Error at /usr/share/cmake-3.22/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find JNI (missing: JAVA_AWT_LIBRARY JAVA_JVM_LIBRARY
  JAVA_INCLUDE_PATH2 JAVA_AWT_INCLUDE_PATH)
Call Stack (most recent call first):
  /usr/share/cmake-3.22/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake-3.22/Modules/FindJNI.cmake:382 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  CMakeLists.txt:22 (find_package)

-- Configuring incomplete, errors occurred!
See also "/media/qihao/D/ai/mlc-llm/android/build/CMakeFiles/CMakeOutput.log".
See also "/media/qihao/D/ai/mlc-llm/android/build/CMakeFiles/CMakeError.log".
(mlc-chat-venv) qihao@qihao-System-Product-Name:/media/qihao/D/ai/mlc-llm/android$ 
`
我尝试咨询了ChatGPT，但是都没有得到可行的方案，哪位专家或者教授如果遇到过这个问题，或者能看懂我这个问题，麻烦指点我一下，我十万分的感谢。我已经卡在这里一周了。实在没有思路，而且自己确实能力有限，看不太懂这个错误。

**Comment by aadarsh-ram** [comment]
@Pangu-Immortal I had a similar issue, try using this [solution](https://stackoverflow.com/a/69025703) from StackOverFlow.

**Comment by lr8soft** [comment]
我看cmake报错里写了Could NOT find JNI，配置JAVA_AWT_LIBRARY JAVA_JVM_LIBRARY
JAVA_INCLUDE_PATH2 JAVA_AWT_INCLUDE_PATH环境变量了吗？

**Comment by Moon-Ahn** [comment]
I faced the same problem, but I solved it.
Please run
```
conda install cmake
``` 

If not, please follow the order below.
```
sudo apt-get install -y openjdk-8-jdk
sudo apt-get install -y default-jdk
export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64
conda install cmake
```

**Comment by MasterJH5574** [comment]
Gonna close this issue due to inactivity. Please feel free to open new ones if there are any other problems.
