### ISSUE TITLE
[Bug] Cannot open https://mlc.ai/

### ISSUE THREAD

**Issue by EmilioZhao** [mlc-ai/mlc-llm#1429]
## 🐛 Bug
cannot open https://mlc.ai/ 

MLC courses, notebooks, mlc-llm installation docs are not available at all, please fix it ASAP!

**Comment by Hzfengsy** [comment]
It works, but it is blocked by the GFW in China mainland, since it is hosted by GitHub. Please try proxy to access

**Comment by EmilioZhao** [comment]
I can open github.com, but can't open [https://mlc.ai](https://mlc.ai)  . It's not good for the popularity of mlc-llm.

**Comment by wenshuai-xiaomi** [comment]
Yes, the proxy is needed, I met the same question.

**Comment by Hzfengsy** [comment]
We'd like the website can be accessed by everyone. Please let me know if there is someplace we can deploy/mirror to let it accessible. Actionable suggestions are appreciated!
