### ISSUE TITLE
[Model Request] mistralai/Mixtral-8x7B-Instruct-v0.1

### ISSUE THREAD

**Issue by jamestwhedbee** [mlc-ai/mlc-llm#1431]
## ⚙️  Request New Models

- Link to an existing implementation (e.g. Hugging Face/Github): https://huggingface.co/mistralai/Mixtral-8x7B-Instruct-v0.1
- Is this model architecture supported by MLC-LLM? I am not sure, I know you support Mistral but this is a MoE which may be a first

**Comment by junrushao** [comment]
I think @vinx13 already got it working nicely. What's our timeline getting it merged?

**Comment by vinx13** [comment]
There's a prototype in my branch https://github.com/vinx13/mlc-llm/tree/moe https://github.com/vinx13/tvm/tree/moe. Once cleaned up and have quantization refactored we can upstream it

**Comment by ivfiev** [comment]
Nice, will there be a Vulkan binary lib (.so)? Mistral-7B didn't have one...

**Comment by srikanthsrnvs** [comment]
Bumping on this, Any status update?

**Comment by vinx13** [comment]
It has been added to SLM flow. More performance optimizations will come soon 
https://github.com/mlc-ai/mlc-llm/tree/main/python/mlc_chat/model/mixtral
