### ISSUE TITLE
[Question] How to use DispatchTIROperator? I see those optimized things for Llama and Adreno but they seems not used.

### ISSUE THREAD

**Issue by xunkai55** [mlc-ai/mlc-llm#1440]
## ❓ General Questions

Hi there,

I wonder how we use DispatchTIROperator and other `dispatch.*` stuff.

I see those optimized things for Llama and Adreno but they seems not used.

Thanks!

**Comment by tqchen** [comment]
likely you can add the dispatch back into the compilaiton pipeline, https://github.com/mlc-ai/mlc-llm/blob/main/python/mlc_chat/compiler/compiler_pass/pipeline.py#L45

this is the place where we inject the current ones under the latest pipeline
