### ISSUE TITLE
[Bug] TinyLlama-1.1B doesn't work on Android

### ISSUE THREAD

**Issue by shreydesai** [mlc-ai/mlc-llm#1452]
## 🐛 Bug

Following the MLC-LLM Android deployment instructions (https://llm.mlc.ai/docs/deploy/android.html), I'm not able to get a TinyLlama-1.1B model working. Everything builds on MacOS and the APK is installed on my Pixel 6 Pro. However, after opening the app, it says "Model lib TinyLlama-1.1B-Chat-v0.2-q4f16_1 is not supported".

## To Reproduce

[Get pre-built model artifacts]
1. Create `dist/models/TinyLlama-1.1B-Chat-v0.2_q4f16_1`
2. Clone TinyLlama-1.1B HF repo: https://huggingface.co/DavidSharma/mlc-chat-TinyLlama-1.1B-Chat-v0.2_q4f16_1/
3. Add android .tar file: https://github.com/mlc-ai/binary-mlc-llm-libs/blob/main/TinyLlama-1.1b-q4f16_1-android.tar (rename TinyLlama-1.1b -> TinyLlama-1.1B)

[Build Android app]
1. Update `android/src/main/assets/app-config.json` to use TinyLlama-1.1B:
```
{
  "model_libs": [
    "TinyLlama-1.1B-Chat-v0.2_q4f16_1"
  ],
  "model_list": [
    {
      "model_url": "https://huggingface.co/DavidSharma/mlc-chat-TinyLlama-1.1B-Chat-v0.2_q4f16_1/",
      "local_id": "TinyLlama-1.1B-Chat-v0.2-q4f16_1"
    }
  ],
  "add_model_samples": []
}
```
2. Prepare libraries: `./android/library/prepare_libs.sh`
3. Install APK on Android phone (Pixel 6 Pro)

## Expected behavior

TinyLlama-1.1B is supposed to work on the MLC-LLM Android app

## Environment

 - Platform (e.g. WebGPU/Vulkan/IOS/Android/CUDA): Android
 - Operating system (e.g. Ubuntu/Windows/MacOS/...): MacOS
 - Device (e.g. iPhone 12 Pro, PC+RTX 3090, ...) Pixel 6 Pro
 - How you installed MLC-LLM (`conda`, source): Conda
 - How you installed TVM-Unity (`pip`, source): Pip
 - Python version (e.g. 3.10): 3.8
 - GPU driver version (if applicable): NA
 - CUDA/cuDNN version (if applicable): NA
 - TVM Unity Hash Tag (`python -c "import tvm; print('\n'.join(f'{k}: {v}' for k, v in tvm.support.libinfo().items()))"`, applicable if you compile models): https://pastebin.com/vDcLSceT
 - Any other relevant information:

**Comment by CharlieFRuan** [comment]
Hi! We recently updated our Android flow and the documentation correspondingly quite a lot: https://github.com/mlc-ai/mlc-llm/pull/1494. Check if the error still persists with the new directions in Android documentation.

Closing this issue for now; but definitely feel free to open another issue!
