### ISSUE TITLE
[Speed]

### ISSUE THREAD

**Issue by wangdc666** [mlc-ai/mlc-llm#1457]
# 🏎️  Speed Report

- The model code: 

- The model configuration (e.g. quantization mode, running data type, etc.):
- Device (e.g. MacBook Pro M2, PC+RTX 3080): 
- OS (if applicable):
- Encode speed (Token/s):
- Decode speed (Token/s):
- Memory usage (if applicable):

**Comment by Hzfengsy** [comment]
Close it as there is no meaningful information. Feel free to reopen a new one if you indeed want to report speed or discuss something
