### ISSUE TITLE
[Question]When Qwen-1_8B is deployed, the video memory is consumed too much

### ISSUE THREAD

**Issue by lss0510** [mlc-ai/mlc-llm#1458]
## ❓ General Questions

Some errors occurred while deploying Qwen, when I finished compiling the model, I ran the model with ./build/mlc_chat_cli --model Qwen-1_8B-Chat-q4f32_1 --device cuda, but nvidia-smi it shows that I am using close to 14g of video memory, which is obviously there some errors, how should I find these errors?

**Comment by limour-blog** [comment]
Has Qwen-1.8B been supported? It still shows as "Todo" on [the MLC LLM Model Request Tracking](https://github.com/orgs/mlc-ai/projects/2/views/1). Could you please share the compilation process?

**Comment by CharlieFRuan** [comment]
Hi @lss0510! Qwen as of now is not supported yet. If you added support for this model architecture, would you mind share a pointer to your code so that we could help debug? Even better, it would be great if you could open a PR!

**Comment by CharlieFRuan** [comment]
Qwen is now supported via https://github.com/mlc-ai/mlc-llm/pull/1646.

Try it out with `python -m mlc_chat chat HF://mlc-ai/Qwen-1_8B-Chat-q4f16_1-MLC`

Testing on our machine, it takes roughly 2GB:
<img width="1541" alt="image" src="https://github.com/mlc-ai/mlc-llm/assets/53290280/ac6aa616-f77d-4566-96c0-d18e8d5cc2ae">

**Comment by CharlieFRuan** [comment]
Closing this issue for now; if issues persist, feel free to open another one.
