### ISSUE TITLE
[Bug] libnvrtc.so.11.2: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by Rahu218** [mlc-ai/mlc-llm#1460]
## To Reproduce

1. Tried running the notebook (https://colab.research.google.com/github/mlc-ai/notebooks/blob/main/mlc-llm/tutorial_chat_module_getting_started.ipynb)
1. Facing the below error while running the notebook, it as working fine till yesterday.
1.

## Environment

 - Platform (e.g. WebGPU/Vulkan/IOS/Android/CUDA):
 - Operating system (e.g. Ubuntu/Windows/MacOS/...):
 - Device (e.g. iPhone 12 Pro, PC+RTX 3090, ...)
 - How you installed MLC-LLM (`conda`, source):
 - How you installed TVM-Unity (`pip`, source):
 - Python version (e.g. 3.10):
 - GPU driver version (if applicable):
 - CUDA/cuDNN version (if applicable):
 - TVM Unity Hash Tag (`python -c "import tvm; print('\n'.join(f'{k}: {v}' for k, v in tvm.support.libinfo().items()))"`, applicable if you compile models):
 - Any other relevant information:

## Additional context
![Screenshot 2023-12-19 102349](https://github.com/mlc-ai/mlc-llm/assets/107320365/fcef9b5c-e6ee-4e2b-ba7a-2bb628951f41)

**Comment by tqchen** [comment]
this likely due to the fact that cuda is not readily available. try to ensure you have the CUDA path in your LD_LIBRARY_PATH

**Comment by rickzx** [comment]
@Rahu218 You can try install the version compatible with CUDA 12.2:
In the notebook,
```
!pip install --pre --force-reinstall mlc-ai-nightly-cu122 mlc-chat-nightly-cu122 -f https://mlc.ai/wheels
```

**Comment by CharlieFRuan** [comment]
Closing this issue for now. Feel free to open another issue if errors persist!
