### ISSUE TITLE
[Question] Sometimes only single token (the first) is generated

### ISSUE THREAD

**Issue by li-jun-jiang** [mlc-ai/mlc-llm#1461]
## ❓ General Questions

I am running mlc chat with RAG on an android (Xiaomi 6 android phone), and the model in use is CodeLlama-7b-Instruct-hf-q4f16_0 (content size is 768).
However, I sometimes find that only a single token - the first token of the correct answer - is generated.

Are there any parameters I can modify to alter this occurrence?

Additionally, I have been unable to run this model on an iphone or macosx due to compilation failures.

Please refer to the attachments for the screenshot of the first token, my full prompt, and the compilation failures.

BTW:
    1. I also tried the same model (but with q3f16_1) on an iphone using the same full prompt. The same problem exists, but it occurs rarely.
    2. Does MLC support running Mistral on Android?
<img width="554" alt="only_first_token_generated" src="https://github.com/mlc-ai/mlc-llm/assets/18555993/621e6696-d095-4e58-b30b-d72faf080dc2">
[full_prompt.txt](https://github.com/mlc-ai/mlc-llm/files/13711621/full_prompt.txt)
[failure_when_targeting_iphone.txt](https://github.com/mlc-ai/mlc-llm/files/13711622/failure_when_targeting_iphone.txt)
[failure_when_targeting_metal.txt](https://github.com/mlc-ai/mlc-llm/files/13711623/failure_when_targeting_metal.txt)

**Comment by li-jun-jiang** [comment]
I tried to compile the model targeting metal or iphone with q4f16_0, but failed, please refer to the attachments for the output:[failure_when_targeting_iphone.txt](https://github.com/mlc-ai/mlc-llm/files/13711622/failure_when_targeting_iphone.txt)
[failure_when_targeting_metal.txt](https://github.com/mlc-ai/mlc-llm/files/13711623/failure_when_targeting_metal.txt)

**Comment by ChristianWeyer** [comment]
Did you ever fix your issue @li-jun-jiang ?

**Comment by Moon-Ahn** [comment]
@li-jun-jiang 
I'm thinking about how to apply RAG in mlc-llm's Android app.
It seems that you have solved the solution for that method.. Can you give me some advice?
I need help.

**Comment by aiakubovich** [comment]
@li-jun-jiang I am interested in RAG too. Could you share details please?
