### ISSUE TITLE
[Bug] mlc-llm/tvm/src/runtime/cuda/cuda_device_api.cc:129: InternalError: Check failed: (e == cudaSuccess || e == cudaErrorCudartUnloading) is false: CUDA: out of memory

### ISSUE THREAD

**Issue by wenshuai-xiaomi** [mlc-ai/mlc-llm#1462]
## 🐛 Bug

mlc-llm/tvm/src/runtime/cuda/cuda_device_api.cc:129: InternalError: Check failed: (e == cudaSuccess || e == cudaErrorCudartUnloading) is false: CUDA: out of memory

On Ubuntu20.4 with memory of 16G

(base) ➜  mlc-chat-Llama-2-7b-chat-hf-q4f16_1 git:(main) ✗ du -h
3.6G

1. python3 examples/python/sample_mlc_chat.py (run the the demo changing nothing)
then the next backtrace error:

(base) ➜  mlc-llm git:(main) ✗ python3 examples/python/sample_mlc_chat.py
Traceback (most recent call last):
  File "/home/ws/code/opensource_wenshuai_branch/mlc-llm/mlc-llm/examples/python/sample_mlc_chat.py", line 8, in <module>
    cm = ChatModule(model="Llama-2-7b-chat-hf-q4f16_1")
  File "/home/ws/code/opensource_wenshuai_branch/mlc-llm/mlc-llm/python/mlc_chat/chat_module.py", line 713, in __init__
    self._reload(self.model_lib_path, self.model_path, user_chat_config_json_str)
  File "/home/ws/code/opensource_wenshuai_branch/mlc-llm/mlc-llm/python/mlc_chat/chat_module.py", line 927, in _reload
    self._reload_func(lib, model_path, app_config_json)
  File "/home/ws/code/opensource_wenshuai_branch/mlc-llm/tvm/python/tvm/_ffi/_ctypes/packed_func.py", line 239, in __call__
    raise_last_ffi_error()
  File "/home/ws/code/opensource_wenshuai_branch/mlc-llm/tvm/python/tvm/_ffi/base.py", line 481, in raise_last_ffi_error
    raise py_err
  File "/home/ws/code/opensource_wenshuai_branch/mlc-llm/mlc-llm/cpp/llm_chat.cc", line 1535, in mlc::llm::LLMChatModule::GetFunction(tvm::runtime::String const&, tvm::runtime::ObjectPtr<tvm::runtime::Object> const&)::{lambda(tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*)#1}::operator()(tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*) const
    chat_->Reload(args[0], args[1], args[2]);
  File "/home/ws/code/opensource_wenshuai_branch/mlc-llm/mlc-llm/cpp/llm_chat.cc", line 578, in mlc::llm::LLMChat::Reload(tvm::runtime::TVMArgValue, tvm::runtime::String, tvm::runtime::String)
    this->params_ = ft_.LoadParams(model_path, device_, use_presharded_weights_);
  File "/home/ws/code/opensource_wenshuai_branch/mlc-llm/mlc-llm/cpp/llm_chat.cc", line 208, in LoadParams
    (*fload_cache)(model_path, static_cast<int32_t>(device.device_type), device.device_id);
ValueError: Traceback (most recent call last):
  4: mlc::llm::LLMChatModule::GetFunction(tvm::runtime::String const&, tvm::runtime::ObjectPtr<tvm::runtime::Object> const&)::{lambda(tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*)#1}::operator()(tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*) const
        at /home/ws/code/opensource_wenshuai_branch/mlc-llm/mlc-llm/cpp/llm_chat.cc:1535
  3: mlc::llm::LLMChat::Reload(tvm::runtime::TVMArgValue, tvm::runtime::String, tvm::runtime::String)
        at /home/ws/code/opensource_wenshuai_branch/mlc-llm/mlc-llm/cpp/llm_chat.cc:578
  2: LoadParams
        at /home/ws/code/opensource_wenshuai_branch/mlc-llm/mlc-llm/cpp/llm_chat.cc:208
  1: tvm::runtime::PackedFuncObj::Extractor<tvm::runtime::PackedFuncSubObj<tvm::runtime::TypedPackedFunc<void (std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int, int)>::AssignTypedLambda<void (*)(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int, int)>(void (*)(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int, int), std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)::{lambda(tvm::runtime::TVMArgs const&, tvm::runtime::TVMRetValue*)#1}> >::Call(tvm::runtime::PackedFuncObj const*, tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*)
  0: tvm::runtime::relax_vm::NDArrayCache::Load(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int, int)
  9: mlc::llm::LLMChatModule::GetFunction(tvm::runtime::String const&, tvm::runtime::ObjectPtr<tvm::runtime::Object> const&)::{lambda(tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*)#1}::operator()(tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*) const
        at /home/ws/code/opensource_wenshuai_branch/mlc-llm/mlc-llm/cpp/llm_chat.cc:1535
  8: mlc::llm::LLMChat::Reload(tvm::runtime::TVMArgValue, tvm::runtime::String, tvm::runtime::String)
        at /home/ws/code/opensource_wenshuai_branch/mlc-llm/mlc-llm/cpp/llm_chat.cc:578
  7: LoadParams
        at /home/ws/code/opensource_wenshuai_branch/mlc-llm/mlc-llm/cpp/llm_chat.cc:208
  6: tvm::runtime::PackedFuncObj::Extractor<tvm::runtime::PackedFuncSubObj<tvm::runtime::TypedPackedFunc<void (std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int, int)>::AssignTypedLambda<void (*)(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int, int)>(void (*)(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int, int), std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)::{lambda(tvm::runtime::TVMArgs const&, tvm::runtime::TVMRetValue*)#1}> >::Call(tvm::runtime::PackedFuncObj const*, tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*)
  5: tvm::runtime::relax_vm::NDArrayCache::Load(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int, int)
  4: tvm::runtime::relax_vm::NDArrayCacheMetadata::FileRecord::Load(DLDevice, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, tvm::runtime::Optional<tvm::runtime::NDArray>*) const
  3: tvm::runtime::relax_vm::NDArrayCacheMetadata::FileRecord::ParamRecord::Load(DLDevice, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const*, tvm::runtime::Optional<tvm::runtime::NDArray>*) const
  2: tvm::runtime::NDArray::Empty(tvm::runtime::ShapeTuple, DLDataType, DLDevice, tvm::runtime::Optional<tvm::runtime::String>)
  1: tvm::runtime::DeviceAPI::AllocDataSpace(DLDevice, int, long const*, DLDataType, tvm::runtime::Optional<tvm::runtime::String>)
  0: tvm::runtime::CUDADeviceAPI::AllocDataSpace(DLDevice, unsigned long, unsigned long, DLDataType)
  File "/home/ws/code/opensource_wenshuai_branch/mlc-llm/tvm/src/runtime/relax_vm/ndarray_cache_support.cc", line 254
ValueError: Error when loading parameters from params_shard_58.bin: [04:30:55] /home/ws/code/opensource_wenshuai_branch/mlc-llm/tvm/src/runtime/cuda/cuda_device_api.cc:129: InternalError: Check failed: (e == cudaSuccess || e == cudaErrorCudartUnloading) is false: CUDA: out of memory

## Environment
 - Platform (CUDA):
 - Operating system (Ubuntu):
 - Device (PC)
 - How you installed MLC-LLM (source):
 - How you installed TVM-Unity ( source):
 - Python version (3.9.12):
 - GPU driver version (nvidia-driver-535):
 - CUDA version (cuda-11.8):
 - TVM Unity Hash Tag (not compile models):

**Comment by wenshuai-xiaomi** [comment]
By the way, using vulkan backend on this PC with 16G memory, out of memory too. 
In an another PC whith having no NV GPU with 32G memory，vulkan backend can work.

**Comment by wenshuai-xiaomi** [comment]
(base) ➜  mlc-chat-Llama-2-7b-chat-hf-q4f16_1 git:(main) ✗ nvidia-smi 
Tue Dec 19 05:25:33 2023       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.129.03             Driver Version: 535.129.03   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce MX350           Off | 00000000:01:00.0 Off |                  N/A |
| N/A   42C    P8              N/A / ERR! |      9MiB /  2048MiB |      0%      Default |
|                                         |                      |                  N/A |

I learned the closed issue, Is the reason next that?
1. from the above info of nvidia-smi, the VRAM total size is 2G which is not enough for mlc-chat-Llama-2-7b-chat-hf-q4f16_1.
2. not care the RAM size of 16G.

I check the PC with 32G RAM which has intel HD graphics530 using the shared memory

Is right?

**Comment by Hzfengsy** [comment]
You are right. Your VRAM is only 2GB, not 16GB. So it failed.
