### ISSUE TITLE
[Bug] No model will run in an Iphone 13 mini

### ISSUE THREAD

**Issue by neuromancer** [mlc-ai/mlc-llm#1465]
All the models available (even using testflight) will fail to run with memory issues or just crash when input any text on an Iphone 13 mini. If the app is not supported, it will good to know in the documentation or directly disallowing to install it from the app store.

**Comment by rahulvk007** [comment]
Same issue but with an IPhone 13.

Did you find any way to get it working ?

**Comment by neuromancer** [comment]
No workaround so far :disappointed:

**Comment by Lq-qm** [comment]
I think that is a problem with the redpajama models, as after the update, is the only available now for iphones with 4GB of RAM.

**Comment by Lq-qm** [comment]
Alas the Phi model from microsoft was posted some hours ago so...

**Comment by neuromancer** [comment]
Is this available in the TestFlight releases or should we use the AppStore ones?

**Comment by Lq-qm** [comment]
The TestFlight version is the same as i tested so far... Both have problems of crashing with the RedPajama model... There are two problems being more specific, the first is that the option to download other models from HF was removed in this new versions and the second one it's with the RedPajama model as this one is a new updated version from MLC HF repository...

**Comment by tqchen** [comment]
checkout #1554 , clsing this one for now

**Comment by neuromancer** [comment]
Great news!, can we test this fix using a specific version of the App Store or Test Flight?
