### ISSUE TITLE
[Bug] ctx_length and re-encode prompts logic

### ISSUE THREAD

**Issue by sbwww** [mlc-ai/mlc-llm#1470]
## 🐛 Bug

I notice the code in [cpp/llm_chat.cc](https://github.com/mlc-ai/mlc-llm/blob/36c0d61065680cf2735245b6fdceef19fbfb1604/cpp/llm_chat.cc#L681-L691) has a logic of re-encoding prompts when the next generation might exceed `max_window_size_`. `ctx_length` is initialized as the length of the first prompt.
I guess it might be reserved for the **system prompt**. However, **when `conversation.system` is empty**, `all_prompts[0]` is not the empty system prompt but the **first user query**. And `ctx_length` will have a length which will never be used later (as the first user query is usually dropped when exceeding max length).

https://github.com/mlc-ai/mlc-llm/blob/36c0d61065680cf2735245b6fdceef19fbfb1604/cpp/llm_chat.cc#L681-L691

Plus, `i + 2 < all_prompts.size()` is also unclear. We mainly want to preserve **latest user query** and **a sep**, so it should be `i + 1 < all_prompts.size()` and I could be the re-encode pos I guess.

## To Reproduce

1. `conv.system = "";` in [cpp/conv_templates.cc](https://github.com/mlc-ai/mlc-llm/blob/36c0d61065680cf2735245b6fdceef19fbfb1604/cpp/conv_templates.cc)
2. LOG `all_prompts[0]` and `ctx_length` in [cpp/llm_chat.cc](https://github.com/mlc-ai/mlc-llm/blob/36c0d61065680cf2735245b6fdceef19fbfb1604/cpp/llm_chat.cc)
1. compile and run the model with 2 long input
1. when processing the 2nd long input, LOG shows the 1st long input is `all_prompts[0]` and `ctx_length` is initialized as a large value

## Expected behavior

N/A

## Environment

N/A

## Additional context

N/A

**Comment by tqchen** [comment]
This is a good point, we are migrating towards a MLCEngine, which using SWA and sink for re-encoding, so closing this for now
