### ISSUE TITLE
[Model Request] SOLAR-10.7B-Instruct

### ISSUE THREAD

**Issue by joseph777111** [mlc-ai/mlc-llm#1474]
## ⚙️  Request New Models

- Link to an existing implementation (e.g. Hugging Face/Github): https://huggingface.co/upstage/SOLAR-10.7B-Instruct-v1.0 
- Is this model architecture supported by MLC-LLM? (the list of [supported models](https://llm.mlc.ai/docs/prebuilt_models.html)) No (Hybrid Model - mix of LLAMA-2 13B with Mistral-7B layers)

### SOLAR-10.7B, is a compact, yet remarkably powerful large language model; it has **demonstrated unparalleled state-of-the-art performance in models under 30B parameters** - rivaling model's with up to 30B parameters in performance.

SOLAR-10.7B, was developed using Upstage's Depth Up-Scaling. And, it was **Built on the Llama2 architecture with integrated Mistral 7B weights integrated into its upscaled layers** as part of its pre-training.

**Upstage's Depth-Upscaled SOLAR-10.7B has remarkable performance. It outperforms models with up to 30B parameters, even surpassing the recent Mixtral 8X7B model.** For detailed information, please refer to the experimental table. Solar 10.7B is an ideal choice for fine-tuning. SOLAR-10.7B offers robustness and adaptability for your fine-tuning needs. Our simple instruction fine-tuning using the SOLAR-10.7B pre-trained model yields significant performance improvements ([SOLAR-10.7B-Instruct-v1.0](https://huggingface.co/upstage/SOLAR-10.7B-Instruct-v1.0)).

https://huggingface.co/upstage/SOLAR-10.7B-v1.0
![IMG_0309](https://github.com/mlc-ai/mlc-llm/assets/80947356/daa1a8b7-304e-4448-998b-53346c77b0a0)

**Comment by alphaarea** [comment]
This is a model that has been llamafied to use mlc-llm inference directly.

I've tried it and it works fine

```python
>>> cm.generate("What's the meaning of life?")
"The meaning of life is a profound and multifaceted question that has been pondered upon by philosophers, theologians, and ordinary people for centuries. Ultimately, the meaning of life is subjective and varies from person to person. It's about finding personal fulfillment, purpose, and happiness in one's own life journey.\n\nSome believe that the meaning of life comes from relationships, connecting with others, and building strong bonds with family, friends, and community. Others find meaning in their professional and personal pursuits, striving for excellence, and making a difference through their work. For some, spirituality, religion, or faith can provide guidance and a sense of meaning.\n\nIn essence, the meaning of life is a personal quest to find significance and joy in one's own life experiences. It's essential to engage in self-reflection and introspection to understand what brings fulfillment and to create a life that aligns with one's values, beliefs, and aspirations."
>>> print(f"Statistics: {cm.stats()}")
Statistics: prefill: 516.5 tok/s, decode: 33.3 tok/s
```

----------

In addition, the results in the standard 256 tokens test are

prefill: 137.1 tok/s, decode: 33.8 tok/s
