### ISSUE TITLE
[Bug] Privacy Policy link broken (404) in Apple Appstore

### ISSUE THREAD

**Issue by shusso** [mlc-ai/mlc-llm#1475]
## 🐛 Bug

1. Open MLC Chat app in [appstore](https://apps.apple.com/us/app/mlc-chat/id6448482937)
2. Click "Privacy Policy" link (https://llm.mlc.ai/privacy) and observe 404

 - Platform (e.g. WebGPU/Vulkan/IOS/Android/CUDA): Apple App Store
 - Operating system (e.g. Ubuntu/Windows/MacOS/...): ios/mac

**Comment by tqchen** [comment]
Thanks for reporting, this is now baxck online
