### ISSUE TITLE
AttributeError: 'GroupQuantizeEmbedding' object has no attribute 'weight'. Did you mean: 'q_weight'?

### ISSUE THREAD

**Issue by musram** [mlc-ai/mlc-llm#1477]
I am building model for whisper targeting vulkan gpu.
The encoder code is 
class WhisperEncoder(nn.Module):
    def __init__(self, config: WhisperConfig):
        super().__init__()

        embed_dim = config.d_model
        self.num_mel_bins = config.num_mel_bins
        self.max_source_positions = config.max_source_positions
    
        self.conv1 = nn.Conv1D(self.num_mel_bins, embed_dim, kernel_size=3, padding=1)
        self.conv2 = nn.Conv1D(embed_dim, embed_dim, kernel_size=3, stride=2, padding=1)

        self.embed_positions = nn.Embedding(self.max_source_positions, embed_dim)

        self.layers = nn.ModuleList([EncoderLayer(config) for _ in range(config.encoder_layers)])
        self.layer_norm = nn.LayerNorm(config.d_model)

    def forward(self, input_features: Tensor) -> Tensor:
        expected_seq_length = self.max_source_positions * self.conv1.stride * self.conv2.stride
        if input_features.shape[-1] != expected_seq_length:
            raise ValueError(
                f"Whisper expects the mel input features to be of length {expected_seq_length}, but found {input_features.shape[-1]}. Make sure to pad the input mel features to {expected_seq_length}."
            )

        # for quantization purposes
        input_features = input_features.astype(self.conv1.weight.dtype)

        inputs_embeds = nn.gelu(self.conv1(input_features))
        inputs_embeds = nn.gelu(self.conv2(inputs_embeds))

        inputs_embeds = nn.permute_dims(inputs_embeds, [0, 2, 1])

        embed_pos = self.embed_positions.weight

        hidden_states = inputs_embeds + embed_pos

        for _, encoder_layer in enumerate(self.layers):
            hidden_states = encoder_layer(hidden_states)

        hidden_states = self.layer_norm(hidden_states)

        return hidden_states

Getting error  at:  embed_pos = self.embed_positions.weight  when I am running the command for convert_weight
mlc_chat convert_weight  --model /home/munusairam/softwares/programs/python_projects/tvm-framework/source-build-support/mlc-llm/dist/models/whisper-tiny/ --quantization q4f16_1 --output  /home/munusairam/softwares/programs/python_projects/whisper-tiny/

The whisper_quantization.py is 
"""This file specifies how MLC's Whisper parameters are quantized using group quantization
or other formats."""
from typing import Tuple

from tvm.relax.frontend import nn

from ...loader import QuantizeMapping
from ...quantization import AWQQuantize, GroupQuantize, NoQuantize
from .whisper_model import WhisperConfig, WhisperForConditionalGeneration

def group_quant(
    model_config: WhisperConfig, quantization: GroupQuantize
) -> Tuple[nn.Module, QuantizeMapping]:
    """Quantize a Whisper-architecture model using group quantization."""
    model: nn.Module = WhisperForConditionalGeneration(model_config)
    model.to(quantization.model_dtype)
    quant_map = QuantizeMapping({}, {})
    model = quantization.quantize_model(model, quant_map, name_prefix="")
    return model, quant_map

def awq_quant(
    model_config: WhisperConfig, quantization: AWQQuantize
) -> Tuple[nn.Module, QuantizeMapping]:
    """Quantize a Whisper-architecture model using Activation-aware Weight Quantization(AWQ).."""
    model: nn.Module = WhisperForConditionalGeneration(model_config)
    model.to(quantization.model_dtype)
    quant_map = QuantizeMapping({}, {})
    model = quantization.quantize_(model, quant_map, name_prefix="")
    return model, quant_map

def no_quant(
    model_config: WhisperConfig, quantization: NoQuantize
) -> Tuple[nn.Module, QuantizeMapping]:
    """Quantize a Whisper-architecture model using no quantization."""
    model: nn.Module = WhisperForConditionalGeneration(model_config)
    model.to(quantization.model_dtype)
    quant_map = QuantizeMapping({}, {})
    return model, quant_map

**Comment by tqchen** [comment]
closing for now due to an inactive status, feel free to open new ones
