### ISSUE TITLE
Add custom model no longer available on iOS demo app.

### ISSUE THREAD

**Issue by Mmnyc123** [mlc-ai/mlc-llm#1478]
As of an update last week the feature that allows a custom model to be added via url no longer appears in app. Apologies if this is the wrong place to report this but I didn't see it in the AppStore change log so thought it was a bug.

**Comment by tqchen** [comment]
Closing for now, we decided to opt for removing this support since it was a bit too fragile(as it requires model libraries), we now enable custom models via iOS SDK https://llm.mlc.ai/docs/deploy/ios.html
