### ISSUE TITLE
terminal is crashed when build android.

### ISSUE THREAD

**Issue by chensinit** [mlc-ai/mlc-llm#148]
Hello.
This project is amazing!
I really want to run my android device. but i have a problem.
when i make by below command, my ubuntu terminal is crashed.

make -j

I used ubuntu 22.04.
When it reached 31%, PC is stoped few minutes and suddenly closed terminal.
Could you tell me what is problem? and how can i build this?

**Comment by thomaszheng** [comment]
`make -j4`  you can try

**Comment by chensinit** [comment]
Cool!
