### ISSUE TITLE
[Tracking] Lightweight addition of conversation templates

### ISSUE THREAD

**Issue by CharlieFRuan** [mlc-ai/mlc-llm#1485]
## Overview

Currently, when users want to add a model that requires a conversation template different from those listed in [conv_templates.cc](https://github.com/mlc-ai/mlc-llm/blob/main/cpp/conv_templates.cc), they need to modify various files including building the project from source. The process perhaps may be more cumbersome for web, android, and iOS.

We would like to make the process of adding conversation templates more lightweight. One possibility is to offer the option of embedding the template into `mlc-chat-config.json` and provide a python script that helps generate such content during `mlc_chat gen_config`. During runtime, we simply read the template from `mlc-chat-config.json`, hence not needing to rebuild the project.

The specifics of carrying out this change is not thought through yet.

## Action Items

To be decided

## Links to Related Issues and PRs

Example of adding a new conversation template to C++/Python runtime as of now:
- https://github.com/mlc-ai/mlc-llm/pull/1402

**Comment by Thore1954** [comment]
It'd make sense to automatically read [`chat_template`](https://huggingface.co/docs/transformers/main/en/chat_templating#advanced-how-do-chat-templates-work) from tokenizer_config.json when available.

**Comment by CharlieFRuan** [comment]
Moving this to https://github.com/mlc-ai/mlc-llm/issues/1766
