### ISSUE TITLE
[Bug] cpp/metadata/model.cc:72: InternalError: Check failed: (pf != nullptr) is false: Unable to find `_metadata` function.'

### ISSUE THREAD

**Issue by lizuobin** [mlc-ai/mlc-llm#1489]
i use ndk23 build mlcchat app, run with Llama-2-7b-chat-hf-q4f16_1 crash
use prebuild libtvm4j_runtime_packed.so from https://llm.mlc.ai/ android demo app replace my libtvm4j_runtime_packed.so work ok

crash info:
12-20 20:04:56.858 32577   317 F libc    : Fatal signal 6 (SIGABRT), code -1 (SI_QUEUE) in tid 317 (pool-2-thread-1), pid 32577 (ai.mlc.mlcchat)
12-20 20:04:58.178  5223  5223 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
12-20 20:04:58.178  5223  5223 F DEBUG   : Build fingerprint: 'Redmi/munch/munch:12/SKQ1.211006.001/V13.0.11.0.SLMCNXM:user/release-keys'
12-20 20:04:58.178  5223  5223 F DEBUG   : Revision: '0'
12-20 20:04:58.178  5223  5223 F DEBUG   : ABI: 'arm64'
12-20 20:04:58.178  5223  5223 F DEBUG   : Timestamp: 2023-12-20 20:04:56.966553998+0800
12-20 20:04:58.178  5223  5223 F DEBUG   : Process uptime: 0s
12-20 20:04:58.179  5223  5223 F DEBUG   : Cmdline: ai.mlc.mlcchat
12-20 20:04:58.179  5223  5223 F DEBUG   : pid: 32577, tid: 317, name: pool-2-thread-1  >>> ai.mlc.mlcchat <<<
12-20 20:04:58.179  5223  5223 F DEBUG   : uid: 10493
12-20 20:04:58.179  5223  5223 F DEBUG   : signal 6 (SIGABRT), code -1 (SI_QUEUE), fault addr --------
12-20 20:04:58.179  5223  5223 F DEBUG   : Abort message: '/work/sda/mlc-llm/cpp/metadata/model.cc:72: InternalError: Check failed: (pf != nullptr) is false: Unable to find `_metadata` function.'
12-20 20:04:58.179  5223  5223 F DEBUG   :     x0  0000000000000000  x1  000000000000013d  x2  0000000000000006  x3  0000006f8cfed110
12-20 20:04:58.179  5223  5223 F DEBUG   :     x4  736f646277641f73  x5  736f646277641f73  x6  736f646277641f73  x7  7f7f7f7f7f7f7f7f
12-20 20:04:58.179  5223  5223 F DEBUG   :     x8  00000000000000f0  x9  147438c22892253e  x10 0000000000000000  x11 ffffff80fffffbdf
12-20 20:04:58.179  5223  5223 F DEBUG   :     x12 0000000000000001  x13 00009a68b1fd413b  x14 0032c84605352000  x15 0000000034155555
12-20 20:04:58.180  5223  5223 F DEBUG   :     x16 000000704092cd30  x17 0000007040906870  x18 0000000000000000  x19 0000000000007f41
12-20 20:04:58.180  5223  5223 F DEBUG   :     x20 000000000000013d  x21 00000000ffffffff  x22 ffffff80ffffffc8  x23 0000006f8cfed360
12-20 20:04:58.180  5223  5223 F DEBUG   :     x24 0000006f8cfed240  x25 0000006f8cfed280  x26 0000000000000005  x27 b400006f35bcb734
12-20 20:04:58.180  5223  5223 F DEBUG   :     x28 0000000000000000  x29 0000006f8cfed190
12-20 20:04:58.180  5223  5223 F DEBUG   :     lr  00000070408b6c1c  sp  0000006f8cfed0f0  pc  00000070408b6c48  pst 0000000000001000
12-20 20:04:58.180  5223  5223 F DEBUG   : backtrace:
12-20 20:04:58.180  5223  5223 F DEBUG   :       #00 pc 000000000008bc48  /apex/com.android.runtime/lib64/bionic/libc.so (abort+168) (BuildId: d15a6afaad4d7e44de8683bcf906a6bd)
12-20 20:04:58.180  5223  5223 F DEBUG   :       #01 pc 0000000001126a38  /data/app/~~RSjrs38Bl86gO19MbJoYsQ==/ai.mlc.mlcchat-kzCeLxZV71d7Qiu9ZXOT_Q==/base.apk!libtvm4j_runtime_packed.so (abort_message+240) (BuildId: fc157c46525f10e2eaa2d9f3e755deada3b4a373)
12-20 20:04:58.180  5223  5223 F DEBUG   :       #02 pc 0000000001126c60  /data/app/~~RSjrs38Bl86gO19MbJoYsQ==/ai.mlc.mlcchat-kzCeLxZV71d7Qiu9ZXOT_Q==/base.apk!libtvm4j_runtime_packed.so (demangling_terminate_handler()+264) (BuildId: fc157c46525f10e2eaa2d9f3e755deada3b4a373)
12-20 20:04:58.180  5223  5223 F DEBUG   :       #03 pc 0000000001126af0  /data/app/~~RSjrs38Bl86gO19MbJoYsQ==/ai.mlc.mlcchat-kzCeLxZV71d7Qiu9ZXOT_Q==/base.apk!libtvm4j_runtime_packed.so (std::__terminate(void (*)())+16) (BuildId: fc157c46525f10e2eaa2d9f3e755deada3b4a373)
12-20 20:04:58.180  5223  5223 F DEBUG   :       #04 pc 0000000001126a88  /data/app/~~RSjrs38Bl86gO19MbJoYsQ==/ai.mlc.mlcchat-kzCeLxZV71d7Qiu9ZXOT_Q==/base.apk!libtvm4j_runtime_packed.so (std::terminate()+56) (BuildId: fc157c46525f10e2eaa2d9f3e755deada3b4a373)
12-20 20:04:58.180  5223  5223 F DEBUG   :       #05 pc 0000000000b34324  /data/app/~~RSjrs38Bl86gO19MbJoYsQ==/ai.mlc.mlcchat-kzCeLxZV71d7Qiu9ZXOT_Q==/base.apk!libtvm4j_runtime_packed.so (__clang_call_terminate+8) (BuildId: fc157c46525f10e2eaa2d9f3e755deada3b4a373)

**Comment by CharlieFRuan** [comment]
Hi, thanks for raising the issue! This should probably be solved by this PR https://github.com/mlc-ai/mlc-llm/pull/1494

We are currently under a revamp of model compilation workflow, hence the mismatch of compilation/runtime in docs. This is tracked here https://github.com/mlc-ai/mlc-llm/issues/1420. Apologies for the inconvenience.

**Comment by CharlieFRuan** [comment]
The Android PR https://github.com/mlc-ai/mlc-llm/pull/1494 just got merged in, with an updated documentation page as well: https://llm.mlc.ai/docs/deploy/android.html

Let us know if issues persist!

**Comment by CharlieFRuan** [comment]
Closing this one for now. Feel free to open another if issues persist!
