### ISSUE TITLE
"dist/vicuna-v1-7b/float16/vicuna-v1-7b_vulkan_float16.so" not found

### ISSUE THREAD

**Issue by NeoWang9999** [mlc-ai/mlc-llm#149]
I installed mlc chat according to the documentation, but encountered an error

`Cannot find vicuna-v1-7b lib in preferred path "dist/vicuna-v1-7b/float16/vicuna-v1-7b_vulkan_float16.so" or other candidate paths`

![image](https://github.com/mlc-ai/mlc-llm/assets/48009681/280d18c3-9df6-421a-be62-869685cb854e)

My environment is Ubuntu 22.04，windows WSL

nvidia-smi output:
```
Mon May 15 21:34:53 2023
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 530.46                 Driver Version: 531.61       CUDA Version: 12.1     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                  Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf            Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce RTX 3060         On | 00000000:01:00.0  On |                  N/A |
|  0%   38C    P8               19W / 170W|   3702MiB / 12288MiB |      1%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+

+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|    0   N/A  N/A        22      G   /Xwayland                                 N/A      |
|    0   N/A  N/A        23      G   /Xwayland                                 N/A      |
|    0   N/A  N/A        25      G   /Xwayland                                 N/A      |
+---------------------------------------------------------------------------------------+
```

**Comment by sudeepag** [comment]
Hi @NeoWang9999 , thanks for trying out the MLC LLM project. It is possible that you are attempting to run the model using cuda, but it has been compiled using vulkan. Could you try running the following, and see if that works?

```
$ mlc_chat_cli --device-name=vulkan
```

**Comment by NeoWang9999** [comment]
> Hi @NeoWang9999 , thanks for trying out the MLC LLM project. It is possible that you are attempting to run the model using cuda, but it has been compiled using vulkan. Could you try running the following, and see if that works?
> 
> ```
> $ mlc_chat_cli --device-name=vulkan
> ```

Hi @sudeepag  , thanks for reply, I just tried that, it give me the same error

![image](https://github.com/mlc-ai/mlc-llm/assets/48009681/aaa32cf4-6157-4e73-886b-718e8d964666)

**Comment by sudeepag** [comment]
Interesting, can you try these two things and post the results here?
```
$ cd /mnt/c/Ubuntu/mlc
$ ls -R
```
```
$ mlc_chat_cli -h
```

**Comment by tantanorange** [comment]
I don't know why the path error happened. But I have a similar problem on mac1: https://github.com/mlc-ai/mlc-llm/issues/138. It seems that following the instruction (here: https://mlc.ai/mlc-llm/#windows-linux-mac) leads to a dist/vicuna-v1-7b folder that does not contain a float16 folder (https://huggingface.co/mlc-ai/demo-vicuna-v1-7b-int3/tree/main)

I don't know, I'm just a beginner that has a similar problem with the M1 machine.

**Comment by NeoWang9999** [comment]
> 

yes, and I have tried download the other link: "https://huggingface.co/mlc-ai/demo-vicuna-v1-7b-int4" which include  float16 folder, but it still doesn't work .

**Comment by NeoWang9999** [comment]
> I don't know why the path error happened. But I have a similar problem on mac1: #138. It seems that following the instruction (here: https://mlc.ai/mlc-llm/#windows-linux-mac) leads to a dist/vicuna-v1-7b folder that does not contain a float16 folder (https://huggingface.co/mlc-ai/demo-vicuna-v1-7b-int3/tree/main)
> 
> I don't know, I'm just a beginner that has a similar problem with the M1 machine.

yes, and I have tried download the other link: "https://huggingface.co/mlc-ai/demo-vicuna-v1-7b-int4" which include float16 folder, but it still doesn't work .

**Comment by sudeepag** [comment]
@NeoWang9999 Thanks for sharing the output. It looks like you may have an older version of the mlc-chat-nightly library. Could you try the following?

```shell
$ conda uninstall mlc-chat-nightly
$ conda install -c mlc-ai -c conda-forge mlc-chat-nightly
```

And verify that your environment has a newer version of mlc-chat-nightly.
```shell
(sudeep-mlc-llm) conda list mlc-chat-nightly
# packages in environment at /home/sudeepag/.conda/envs/sudeep-mlc-llm:
#
# Name                    Version                   Build  Channel
mlc-chat-nightly          0.1.dev40       40_g1a4ee89_h1234567_0    mlc-ai

```

**Comment by sudeepag** [comment]
@ScorpionOO8 Try specifying the version number, e.g. 
```
$ conda install -c mlc-ai mlc-chat-nightly=0.1.dev40
```

**Comment by NeoWang9999** [comment]
> @ScorpionOO8 Try specifying the version number, e.g.
> 
> ```
> $ conda install -c mlc-ai mlc-chat-nightly=0.1.dev40
> ```

that works for me， thanks！

**Comment by hqd19950905** [comment]
> > @ScorpionOO8 Try specifying the version number, e.g.
> > ```
> > $ conda install -c mlc-ai mlc-chat-nightly=0.1.dev40
> > ```
> 
> I get this error trying to do that:
> 
> Collecting package metadata (current_repodata.json): done Solving environment: failed with initial frozen solve. Retrying with flexible solve. Collecting package metadata (repodata.json): done Solving environment: failed with initial frozen solve. Retrying with flexible solve.
> 
> PackagesNotFoundError: The following packages are not available from current channels:
> 
> * mlc-chat-nightly=0.1.dev40
> 
> Current channels:
> 
> * https://conda.anaconda.org/mlc-ai/osx-arm64
> * https://conda.anaconda.org/mlc-ai/noarch
> * https://repo.anaconda.com/pkgs/main/osx-arm64
> * https://repo.anaconda.com/pkgs/main/noarch
> * https://repo.anaconda.com/pkgs/r/osx-arm64
> * https://repo.anaconda.com/pkgs/r/noarch
> 
> To search for alternate channels that may provide the conda package you're looking for, navigate to
> 
> https://anaconda.org
> 
> and use the search bar at the top of the page.

I have the same issue, because the newest version for Mac M1 is 0.1.dev34. 
I checked this website.  https://anaconda.org/mlc-ai/mlc-chat-nightly/files

**Comment by tqchen** [comment]
Thanks for reporting, this is likely due to the lagging of the M1 build, we are upgrading the build and will report back here

**Comment by tantanorange** [comment]
Great project! Much much appreciated!   --Kun

**Comment by deep-pipeline** [comment]
Looks like osx-64 is getting very regular (almost nightly) uploads from mlc-ai uploader..
but osx-arm64 is only uploaded by junrushao1994 (last two were dev.34 8 days ago, and dev.9 18 days ago) so I guess maybe the builds for osx-arm64 aren't automated like the others?

Thanks for all your work and for looking into this.

**Comment by mbarsot** [comment]
hello, on macbook air M1 8 GB  i get this error:

**_Cannot find library "vicuna-v1-7b-q3f16_0-metal.so" in dist/prebuilt/lib or other search paths_**

after executing:

conda create -n mlc-chat
conda activate mlc-chat
conda install git git-lfs
conda install -c mlc-ai -c conda-forge mlc-chat-nightly
mkdir -p dist/prebuilt
cd dist/prebuilt
git lfs install
git clone https://huggingface.co/mlc-ai/mlc-chat-vicuna-v1-7b-q3f16_0
git clone https://github.com/mlc-ai/binary-mlc-llm-libs.git lib
cd ../..
 mlc_chat_cli --local-id vicuna-v1-7b-q3f16_0

what is wrong?

-- sidenote: why the great MLC Chat Ios App cannot run via testflight on M1 mac (it is listed as "ios only") ?

**Comment by tqchen** [comment]
The M1 build should now be fixed, please try to do 

```
conda install -c mlc-ai -c conda-forge mlc-chat-nightly --force-reinstall
```

And try run the instructions here again https://mlc.ai/mlc-llm/#windows-linux-mac

 osx-arm64 nightly shuold be fixed

**Comment by ScorpionOO8** [comment]
Worked for me. Deleted the files I used to have in Dist as the new files loaded into Dist/prebuilt. This runs faster than any other LLM I've run on my Macbook Air M1 (8gb ram). And it _doesn't_ max out my memory and freeze my computer, wild (happened with other, M1 CPU-only programs). Thanks all!

**Comment by tqchen** [comment]
Thank you @ScorpionOO8 for confirming, closing his for now, and feel free to post followups

**Comment by mbarsot** [comment]
@tqchen worked great! thanks

**Comment by logicalpath** [comment]
Hello,
I'm running Linux Mint 21.1 
When I run this command from the instructions on https://mlc.ai/mlc-llm/#windows-linux-mac, I get an error locating a so file:

mlc-chat) eddie@eddie-XPS-15-9560:~/workspace/mlc$ mlc_chat_cli --local-id vicuna-v1-7b-q3f16_0
Use MLC config: "dist/prebuilt/mlc-chat-vicuna-v1-7b-q3f16_0/mlc-chat-config.json"
Use model weights: "dist/prebuilt/mlc-chat-vicuna-v1-7b-q3f16_0/ndarray-cache.json"
**Cannot find library "vicuna-v1-7b-q3f16_0-vulkan.so" in "dist"/prebuilt/lib or other search paths**

However, The file does exist in the ./lib directory:

(mlc-chat) eddie@eddie-XPS-15-9560:~/workspace/mlc$ tree -f | grep vicuna-v1-7b-q3f16_0-vulkan.so
    **├── ./lib/vicuna-v1-7b-q3f16_0-vulkan.so**
(mlc-chat) eddie@eddie-XPS-15-9560:~/workspace/mlc$ 

Should I just move the file or change the search path? Any help appreciated.

Thanks, 
Eddie

**Comment by tqchen** [comment]
the lib needs to sit in workspace/mlc/dist/prebuilt/lib

**Comment by logicalpath** [comment]
Thank you @tqchen - that got me past that hurdle!

**Comment by tqchen** [comment]
glad it works
