### ISSUE TITLE
CMake iOS Error 

### ISSUE THREAD

**Issue by chenqi2013** [mlc-ai/mlc-llm#1497]
When I execute prepare_libs.sh  ，
The following error was reported
I followed the link（https://llm.mlc.ai/docs/deploy/ios.html） below step by step to execute it
I have tried adding 
enable_language(C)
enable_language(CXX)
set(CMAKE_C_COMPILER gcc)
set(CMAKE_CXX_COMPILER g++)  to CMakeLists.txt
I found that the “ios” folder does not have  CMakeLists.txt

bo@BodeMacBook-Pro ios % ./prepare_libs.sh  
+ sysroot=iphoneos
+ type=Release
+ '[' false = true ']'
+ rustup target add aarch64-apple-ios
info: component 'rust-std' for target 'aarch64-apple-ios' is up to date
+ mkdir -p build/
+ cd build/
+ cmake ../.. -DCMAKE_BUILD_TYPE=Release -DCMAKE_SYSTEM_NAME=iOS -DCMAKE_SYSTEM_VERSION=14.0 -DCMAKE_OSX_SYSROOT=iphoneos -DCMAKE_OSX_ARCHITECTURES=arm64 -DCMAKE_OSX_DEPLOYMENT_TARGET=14.0 -DCMAKE_BUILD_WITH_INSTALL_NAME_DIR=ON -DCMAKE_SKIP_INSTALL_ALL_DEPENDENCY=ON -DCMAKE_INSTALL_PREFIX=. -DCMAKE_CXX_FLAGS=-O3 -DMLC_LLM_INSTALL_STATIC_LIB=ON -DUSE_METAL=ON
CMake Error at /usr/local/Cellar/cmake/3.28.1/share/cmake/Modules/Platform/iOS-Initialize.cmake:4 (message):
  iphoneos is not an iOS SDK
Call Stack (most recent call first):
  /usr/local/Cellar/cmake/3.28.1/share/cmake/Modules/CMakeSystemSpecificInitialize.cmake:34 (include)
  CMakeLists.txt:2 (project)

CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
-- Configuring incomplete, errors occurred!

**
> How to fix this issue？
**

**Comment by sherelynyap** [comment]
This command worked for me
`sudo xcode-select -switch /Applications/Xcode.app/Contents/Developer`

**Comment by MasterJH5574** [comment]
Sorry for the delayed response. @chenqi2013 would you like to try if @sherelynyap's suggestion works?
