### ISSUE TITLE
android maven repository

### ISSUE THREAD

**Issue by BaeBae33** [mlc-ai/mlc-llm#150]
Can you provide the Android Maven SDK format?

**Comment by yzh119** [comment]
Hi @BaeBae33, would you mind creating PR for this? It would be a cool feature to have in MLC-LLM!

**Comment by BaeBae33** [comment]
> Hi @BaeBae33, would you mind creating PR for this? It would be a cool feature to have in MLC-LLM!

I can do this, but it seems like every model needs to release a Maven package. Is there any way to isolate them? If not, are there any plans for this in the future?

**Comment by cyx-6** [comment]
Hi @BaeBae33, our Android build is refactored and free from Maven in #478. And it would be easy to import the packed `ChatModule` into other Android projects.

**Comment by BaeBae33** [comment]
> @cyx-6 I've built a few versions of the new library. But the library is only compatible with the models it was built with. So I'm still confused about the answer to @BaeBae33 question "I can do this, but seems like every model needs to release a Maven package. Is there any way to isolate them? If not, are there any plans for this in the future?"
> 
> When we build a packed `ChatModule`, how do you know which models the library would actually be compatible with? https://huggingface.co/mlc-ai

Sorry, I haven't been keeping up with this topic recently, and my previous understanding of this framework was only superficial. It was my mistake, so please disregard it.

**Comment by tqchen** [comment]
the android SDK has been updated https://llm.mlc.ai/docs/deploy/android.html
