### ISSUE TITLE
[Question] How to get the implement of PackedFunc of "prefill/ decode/ create_kv_cache" ?

### ISSUE THREAD

**Issue by wenshuai-xiaomi** [mlc-ai/mlc-llm#1500]
How to get the implement of PackedFunc of "prefill/ decode" ? I cannot get it by grep command in tvm and mlc-llm project.
   236   void _InitFunctions() {
   237     this->prefill_func_ = mod_get_func("prefill");
   238     this->embed_func_ = mod_get_func("embed");
   239     this->prefill_with_embed_func_ = mod_get_func("prefill_with_embed");
   240     this->decode_func_ = mod_get_func("decode");
   241     this->softmax_func_ = mod_get_func("softmax_with_temperature");
   242     this->encoding_without_cache_func_ = mod_get_func("encoding_without_cache");
   243     this->create_kv_cache_func_ = mod_get_func("create_kv_cache");

Maybe the fuction of "mod_get_func" be valued as below: 
   167       this->mod_get_func = [this](const std::string& name) -> PackedFunc {                                                                                                      
   168         PackedFunc func = this->local_vm->GetFunction(name, false);
   169         return func;
   170       };

**Comment by CharlieFRuan** [comment]
The most high-level implementations of `prefill` and `decode` are in the model definition (`tvm.nn.module`) like here: 
https://github.com/mlc-ai/mlc-llm/blob/37e1de995ac870dbf8b49dd8cc8089c533f21387/python/mlc_chat/compiler/model/llama/llama_model.py#L271

It would then go through compilation and eventually be packed into model libs that end in `.so` or `.wasm`, etc, hence the name `mod_get_func`.

IIUC `create_kv_cache` is deprecated now and we use `_initialize_effect` insetad (old code kept for backward-compatibility for now):
https://github.com/mlc-ai/mlc-llm/blob/37e1de995ac870dbf8b49dd8cc8089c533f21387/cpp/llm_chat.cc#L243-L246

**Comment by wenshuai-xiaomi** [comment]
> The most high-level implementations of `prefill` and `decode` are in the model definition (`tvm.nn.module`) like here:
> 
> https://github.com/mlc-ai/mlc-llm/blob/37e1de995ac870dbf8b49dd8cc8089c533f21387/python/mlc_chat/compiler/model/llama/llama_model.py#L271
> 
> It would then go through compilation and eventually be packed into model libs that end in `.so` or `.wasm`, etc, hence the name `mod_get_func`.
> 
> IIUC `create_kv_cache` is deprecated now and we use `_initialize_effect` insetad (old code kept for backward-compatibility for now):
> 
> https://github.com/mlc-ai/mlc-llm/blob/37e1de995ac870dbf8b49dd8cc8089c533f21387/cpp/llm_chat.cc#L243-L246

thanks your reponse!
But I cannot get the prefill by that
nm [Llama-2-7b-chat-hf-q4f16_1-vulkan.so](http://llama-2-7b-chat-hf-q4f16_1-vulkan.so/) | c++filt | grep prefill

**Comment by CharlieFRuan** [comment]
This PR may help: https://github.com/mlc-ai/mlc-llm/pull/1499. You can browse the files dumped during the compilation process and search for the function you are interested in

**Comment by wenshuai-xiaomi** [comment]
Thanks, I think the submit will resolve my confuse.
And I had traced into relax_vm by GDB.

**Comment by CharlieFRuan** [comment]
Closing this issue for now. Feel free to open another if there are other questions!
