### ISSUE TITLE
[Bug] Android APP Runtime & Initialization failure

### ISSUE THREAD

**Issue by Nick-infinity** [mlc-ai/mlc-llm#1517]
## 🐛 Bug
 This Check fails in android apk

MLCChat failed

Stack trace:
org.apache.tvm.Base$TVMError: InternalError: Check failed: (fload_exec.defined()) is false: TVM runtime cannot find vm_load_executable
Stack trace:
  File "/Users/workspace/stacks/mlc-llm/cpp/llm_chat.cc", line 161

	at org.apache.tvm.Base.checkCall(Base.java:173)
	at org.apache.tvm.Function.invoke(Function.java:130)
	at ai.mlc.mlcllm.ChatModule.reload(ChatModule.java:43)
	at ai.mlc.mlcchat.AppViewModel$ChatState$mainReloadChat$1$2.invoke(AppViewModel.kt:633)
	at ai.mlc.mlcchat.AppViewModel$ChatState$mainReloadChat$1$2.invoke(AppViewModel.kt:631)
	at ai.mlc.mlcchat.AppViewModel$ChatState.callBackend(AppViewModel.kt:534)
	at ai.mlc.mlcchat.AppViewModel$ChatState.mainReloadChat$lambda$3(AppViewModel.kt:631)
	at ai.mlc.mlcchat.AppViewModel$ChatState.$r8$lambda$JJKpoRMMpp77FzXKA0o00i8lgRA(Unknown Source:0)
	at ai.mlc.mlcchat.AppViewModel$ChatState$$ExternalSyntheticLambda3.run(Unknown Source:8)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:487)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)

Error message:
InternalError: Check failed: (fload_exec.defined()) is false: TVM runtime cannot find vm_load_executable
Stack trace:
  File "/Users/workspace/stacks/mlc-llm/cpp/llm_chat.cc", line 161

## To Reproduce

1. Compile android apk 
2. All the json are pushed to hugging face
3. Weights (params_.*bin) are pushed using adb

## Environment

 - Platform (e.g. WebGPU/Vulkan/IOS/Android/CUDA): Android
 - Operating system (e.g. Ubuntu/Windows/MacOS/...): MacOS
 - Device (e.g. iPhone 12 Pro, PC+RTX 3090, ...)
 - How you installed MLC-LLM (`conda`, source): source
 - How you installed TVM-Unity (`pip`, source): source
 - Python version (e.g. 3.10): 3.9
 - GPU driver version (if applicable):
 - CUDA/cuDNN version (if applicable):
 - TVM Unity Hash Tag (`python -c "import tvm; print('\n'.join(f'{k}: {v}' for k, v in tvm.support.libinfo().items()))"`, applicable if you compile models):
 - Any other relevant information:

## Additional context

@junrushao @tqchen 
suspecting tvm unity commit : bd3e8bb9cf33512a9da7af5d6854161131d8a6ac

**Comment by Kartik14** [comment]
Hey, I think this error is because the `system_lib_prefix` field might not be set correctly. Can you share what command you used for compilation? And you mlc-chat-config.json and app-config.json files as well?

**Comment by Nick-infinity** [comment]
Hello @Kartik14 , here is the requested info

**Compile commands**

python3 /Users/workspace/stacks/mlc-llm/python/mlc_chat/__main__.py convert_weight models/custom-mistral --quantization q4f16_1 -o dist/custom-mistral-q4f16_1

python3 /Users/workspace/stacks/mlc-llm/python/mlc_chat/__main__.py gen_config models/custom-mistral --quantization q4f16_1 --conv-template mistral_default -o dist/custom-mistral-q4f16_1 --sliding-window-size 1024 --prefill-chunk-size 128

python3 /Users/workspace/stacks/mlc-llm/python/mlc_chat/__main__.py compile dist/custom-mistral-q4f16_1/mlc-chat-config.json --device android -o dist/custom-mistral-q4f16_1/custom-mistral-q4f16_1-android.tar



**MLC-CHAT-CONFIG**

`{
  "model_type": "mistral",
  "quantization": "q4f16_1",
  "model_config": {
    "hidden_size": 4096,
    "intermediate_size": 20000,
    "num_attention_heads": 32,
    "num_hidden_layers": 16,
    "rms_norm_eps": 1e-05,
    "vocab_size": 32000,
    "position_embedding_base": 10000.0,
    "context_window_size": -1,
    "num_key_value_heads": 8,
    "head_dim": 128,
    "sliding_window_size": 1024,
    "prefill_chunk_size": 128,
    "attention_sink_size": 4,
    "tensor_parallel_shards": 1
  },
  "vocab_size": 32000,
  "context_window_size": -1,
  "sliding_window_size": 1024,
  "prefill_chunk_size": 128,
  "attention_sink_size": 4,
  "tensor_parallel_shards": 1,
  "mean_gen_len": 128,
  "max_gen_len": 512,
  "shift_fill_factor": 0.3,
  "temperature": 0.7,
  "repetition_penalty": 1.0,
  "top_p": 0.95,
  "conv_template": "mistral_default",
  "pad_token_id": 2,
  "bos_token_id": 1,
  "eos_token_id": 2,
  "tokenizer_files": [
    "tokenizer.model",
    "tokenizer.json",
    "tokenizer_config.json"
  ],
  "version": "0.1.0"`


**APP CONFIG JSON**

`{
  "model_libs": [
    "custom-mistral-q4f16_1"
  ],
  "model_list": [
    {
      "model_url": "https://huggingface.co/User/custom-mistral-q4f16_1/",
      "local_id": "custom-mistral-q4f16_1",
      "model_lib_path": "custom-mistral-q4f16_1/custom-mistral-q4f16_1-android.tar",
      "model_lib": "custom-mistral-q4f16_1"
    }
  ]
}`

**Comment by Kartik14** [comment]
You need to replace `custom-mistral-q4f16_1` in `model_libs` and `model_lib` field with `mistral_q4f16_1`.

Basically, the `model_libs` and `model_lib` fields in `app-config.json` needs to match the `system-lib-prefix` argument in `mlc-chat compile` command which by default is set to `<model-type>_<quantization>`(from mlc-chat-config.json file)

**Comment by Nick-infinity** [comment]
Do you mean something like this

{
"model_libs": [
"mistral_q4f16_1"
],
"model_list": [
{
"model_url": "https://huggingface.co/User/custom-mistral-q4f16_1/",
"local_id": "custom-mistral-q4f16_1",
"model_lib_path": "custom-mistral-q4f16_1/custom-mistral-q4f16_1-android.tar",
"model_lib": "mistral_q4f16_1"
}
]
}


This is diff flow as compared to earlier, I think because of refactoring.

Does this mean that app tries to identify supported model template using "mistral_q4f16_1"  ?

**Comment by Kartik14** [comment]
Yes, It is different from earlier logic. Sorry for the confusion, we are in the midst of switching to a new workflow leading to these issues.

**Comment by Nick-infinity** [comment]
> Yes, It is different from earlier logic. Sorry for the confusion, we are in the midst of switching to a new workflow leading to these issues.

Thank you very much. It works with your suggestion. 

Where can I see all the default model_lib template names for supported models?

Thank you for your contributions.

**Comment by Kartik14** [comment]
You can check [this](https://github.com/mlc-ai/mlc-llm/blob/main/python/mlc_chat/model/model.py) file for different model types.

**Comment by muafei** [comment]
app-config.json：
 {
  "model_list": [
    {
      "model_url": "https://huggingface.co/mlc-ai/minicpm_q4f16_1-MLC/",
      "model_lib": "minicpm_q4f16_1",
      "estimated_vram_bytes": 4348727787,
      "model_id": "minicpm_q4f16_1"
    }
  ],
  "model_lib_path_for_prepare_libs": {
    "minicpm_q4f16_1": "prebuilt_lib/minicpm_q4f16_1/MiniCPM-2b-q4f16_1-android.tar"
  }
}
mlc-chat-config.json：
{
  "model_type": "minicpm",
  "quantization": "q4f16_1",
  ......}
with the same Error message:
InternalError: Check failed: (fload_exec.defined()) is false: TVM runtime cannot find vm_load_executable
Stack trace:
  File "/opt/mlc-llm/cpp/llm_chat.cc", line 163
  What should I do?
