### ISSUE TITLE
[Feature Request] Allow compiling models containing `model.safetensors` without having `model.safetensors.index.json`

### ISSUE THREAD

**Issue by felladrin** [mlc-ai/mlc-llm#1519]
## 🚀 Feature

Hi! I just tested the compilation to MLC WASM using `mlc_chat convert_weight`, and noticed it doesn't find Safetensors weight if the `model.safetensors.index.json` doesn't exist.

The `model.safetensors.index.json` is usually not present when there's a single Safetensors file.

Example of a model that doesn't have the `model.safetensors.index.json`:
<img width="591" alt="image" src="https://github.com/mlc-ai/mlc-llm/assets/418083/21a9302e-3017-44a9-893d-d3633673c933">

## Motivation

I noticed that this is already handled for `pytorch_model.bin` files.
https://github.com/mlc-ai/mlc-llm/blob/cb7bd105fab53ae3e6971c018feb75d5f9483898/python/mlc_chat/support/auto_weight.py#L117-L137

So I'd like to ask for the same for `model.safetensors` files.
https://github.com/mlc-ai/mlc-llm/blob/cb7bd105fab53ae3e6971c018feb75d5f9483898/python/mlc_chat/support/auto_weight.py#L140-L150

## Extra Info

Currently, when we try to convert a model that doesn't have the `model.safetensors.index.json`, it triggers the following error:
```
INFO auto_weight.py:149: Not found Huggingface Safetensor
Traceback (most recent call last):
  File "/usr/local/bin/mlc_chat", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/mlc_chat/__main__.py", line 28, in main
    cli.main(sys.argv[2:])
  File "/usr/local/lib/python3.10/dist-packages/mlc_chat/cli/convert_weight.py", line 81, in main
    parsed.source, parsed.source_format = detect_weight(
  File "/usr/local/lib/python3.10/dist-packages/mlc_chat/support/auto_weight.py", line 86, in detect_weight
    raise ValueError(f"The weight is not in {weight_format} format.")
ValueError: The weight is not in huggingface-safetensor format.
```

## Workaround

As a workaround, we can generate the `model.safetensors.index.json` with the following code:

```python
from safetensors.torch import load_file
import os
import json

weights = load_file(f"./{MODEL_NAME}/model.safetensors", device="cpu")
weight_map = {}

for key in weights:
    weight_map[key] = "model.safetensors"

with open(
    os.path.join(f"./{MODEL_NAME}", "model.safetensors.index.json"),
    "w",
    encoding="utf-8",
) as file:
    json.dump(
        {
            "weight_map": weight_map,
        },
        file,
    )
```

<details>
  <summary>Which renders a valid JSON (Click to expand)</summary>
  <img alt="image" src="https://github.com/mlc-ai/mlc-llm/assets/418083/2b9e3d43-4098-4c07-91fa-7e41035b2551">
</details>

**Comment by junrushao** [comment]
Thanks for reporting! Yeah it’s definitely a reasonable change to do. Would you love to create a PR? Thanks in advance!

**Comment by Nick-infinity** [comment]
`
from safetensors.torch import load_file
import os

def _check_safetensor(weight_path: Path) -> Optional[Path]:
    safetensor_json_path = weight_path / "model.safetensors.index.json"
    if safetensor_json_path.exists():
        logger.info(
            "%s source weight format: huggingface-safetensor. Source configuration: %s",
            FOUND,
            safetensor_json_path,
        )
    else:
        weights = load_file(f"./{weight_path}/model.safetensors", device="cpu")
        weight_map = {}
        for key in weights:
            weight_map[key] = "model.safetensors"
        with open(
            os.path.join(f"./{weight_path}", "model.safetensors.index.json"),
            "w",
            encoding="utf-8",
        ) as file:
            json.dump(
                {
                    "weight_map": weight_map,
                },
                file,
            )
        
    return safetensor_json_path

`

**Comment by Nick-infinity** [comment]
Created a change and tested it locally. it works
```
from safetensors.torch import load_file
import os

def _check_safetensor(weight_path: Path) -> Optional[Path]:
    safetensor_json_path = weight_path / "model.safetensors.index.json"
    if safetensor_json_path.exists():
        logger.info(
            "%s source weight format: huggingface-safetensor. Source configuration: %s",
            FOUND,
            safetensor_json_path,
        )
    else:
        weights = load_file(f"./{weight_path}/model.safetensors", device="cpu")
        weight_map = {}
        for key in weights:
            weight_map[key] = "model.safetensors"
        with open(
            os.path.join(f"./{weight_path}", "model.safetensors.index.json"),
            "w",
            encoding="utf-8",
        ) as file:
            json.dump(
                {
                    "weight_map": weight_map,
                },
                file,
            )
        
    return safetensor_json_path
```
