### ISSUE TITLE
[Bug] Mistral generates repetitive content after a few rounds of long conversation

### ISSUE THREAD

**Issue by junrushao** [mlc-ai/mlc-llm#1526]
## 🐛 Bug

Chatting with Mistral on MLC LLM's Testflight distro, I noticed that it fails to correctly handle long conversation as demonstrated below:

https://github.com/mlc-ai/mlc-llm/assets/22515877/0298bb11-750a-49e8-945a-624be1ee4ee0

On 00:21, I asked a question about dumbbell chest press, but Mistral started to repeat its previous answer using exact words starting 00:17. To rule out the possibility of miscommunication, I clarified the question on 00:33, but still it repeated the previous answers with many exact words.

The issue is pretty easy to reproduce with 5 different topics I tried, and the behavior is relatively consistent that it generates exact words - based on that, I'm afraid it could be some bugs hiding in KVCache handling rather than the model itself.

## Environment

 - Platform (e.g. WebGPU/Vulkan/IOS/Android/CUDA): iPhone
 - Operating system (e.g. Ubuntu/Windows/MacOS/...): iOS 16
 - Device (e.g. iPhone 12 Pro, PC+RTX 3090, ...): iPhone 15 Pro Max
 - Any other relevant information: It's the latest MLC Chat from Testflight

**Comment by junrushao** [comment]
CC @CharlieFRuan @davidpissarra

**Comment by Rishita32** [comment]
I believe is with the model. Check out this link: https://huggingface.co/mistralai/Mistral-7B-v0.1/discussions/29

**Comment by MasterJH5574** [comment]
Thank you @Rishita32 for following up! Looks like we are good to conclude this issue for now.
