### ISSUE TITLE
[Question] LLM Output on GPU vs Android for a finetuned model

### ISSUE THREAD

**Issue by zorowanoshusui** [mlc-ai/mlc-llm#1528]
## ❓ General Questions

I fine tuned LLaMA2 model using LoRA so that it can answer some questions related to media search queries. I finetuned with dataset containing data like 

{"text": "<s>[INST] Query: Search for action movies of the lawyer from breaking bad [/INST]\nClassification:Indirect Cast\nTitle:None\nCast:Bob Odenkrik\nGenre:Action\nType:Movie\nDirector:None </s><eos>"}

When I ran the finetuned model on GPU server the results are according to the training data 
```
Query : 
Classification : 
Title : 
Cast : 
Genre : 
Type : 
Director : 
```

I compiled the model to android using 
```
python3 -m mlc_llm.build         --target android         --max-seq-len 768         --model ./dist/models/$MODEL_NAME         --quantization $QUANTIZATION
```
When I ran the finetuned model on MLC Android app it doesn't exactly follow the format given during finetuning. 

Will there be difference between the outputs generated by same model on GPU vs MLC Android ? If so what is the reason for it ?

**Comment by CharlieFRuan** [comment]
Hi! We recently migrated to a new workflow for compiling models. The workflow under `python3 -m mlc_llm.build ` is no longer maintained and will likely be removed soon. Checkout the new steps here: https://llm.mlc.ai/docs/deploy/android.html

`Will there be difference between the outputs generated by same model on GPU vs MLC Android ?`

Supposedly, there should not be any difference.

**Comment by CharlieFRuan** [comment]
Closing this issue for now; but definitely feel free to open another one if issues persist!
