### ISSUE TITLE
[Bug] Unable to recognize vocab.json, merges.txt tokenizer format 

### ISSUE THREAD

**Issue by alphaarea** [mlc-ai/mlc-llm#1533]
## 🐛 Bug

according to #31 , mlc-llm should already support `vocab.json`, `merges.txt` tokenizer formats.

But when I try to inference [CausalLM/72B-preview-llamafied-qwen-llamafy](https://huggingface.co/CausalLM/72B-preview-llamafied-qwen-llamafy) I run into the error that can't find the tokenizer

```python
>>> from mlc_chat import ChatModule
>>> cm = ChatModule(model="/home/alphaarea/models/CausalLM-7B-DPO-alpha-q0f16", model_lib_path="/home/alphaarea/models/CausalLM-7B-DPO-alpha-q0f16/CausalLM-7B-DPO-alpha-q0f16-cuda.so")
[2024-01-03 14:04:58] INFO model_metadata.py:55: Total memory usage: 9917.13 MB (Parameters: 5462.51 MB. KVCache: 1024.00 MB. Temporary buffer: 3430.62 MB)
[2024-01-03 14:04:58] INFO model_metadata.py:64: To reduce memory usage, tweak `prefill_chunk_size`, `context_window_size` and `sliding_window_size`
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/alphaarea/.conda/envs/mlc-llm-20240103/lib/python3.11/site-packages/mlc_chat/chat_module.py", line 774, in __init__
    self._reload(self.model_lib_path, self.model_path, user_chat_config_json_str)
  File "/home/alphaarea/.conda/envs/mlc-llm-20240103/lib/python3.11/site-packages/mlc_chat/chat_module.py", line 988, in _reload
    self._reload_func(lib, model_path, app_config_json)
  File "tvm/_ffi/_cython/./packed_func.pxi", line 332, in tvm._ffi._cy3.core.PackedFuncBase.__call__
  File "tvm/_ffi/_cython/./packed_func.pxi", line 263, in tvm._ffi._cy3.core.FuncCall
  File "tvm/_ffi/_cython/./packed_func.pxi", line 252, in tvm._ffi._cy3.core.FuncCall3
  File "tvm/_ffi/_cython/./base.pxi", line 182, in tvm._ffi._cy3.core.CHECK_CALL
  File "/home/alphaarea/.conda/envs/mlc-llm-20240103/lib/python3.11/site-packages/tvm/_ffi/base.py", line 481, in raise_last_ffi_error
    raise py_err
  File "/workspace/mlc-llm/cpp/llm_chat.cc", line 1532, in mlc::llm::LLMChatModule::GetFunction(tvm::runtime::String const&, tvm::runtime::ObjectPtr<tvm::runtime::Object> const&)::{lambda(tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*)#1}::operator()(tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*) const
  File "/workspace/mlc-llm/cpp/llm_chat.cc", line 553, in mlc::llm::LLMChat::Reload(tvm::runtime::TVMArgValue, tvm::runtime::String, tvm::runtime::String)
  File "/workspace/mlc-llm/cpp/tokenizers.cc", line 63, in mlc::llm::TokenizerFromPath(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
tvm._ffi.base.TVMError: Traceback (most recent call last):
  3: mlc::llm::LLMChatModule::GetFunction(tvm::runtime::String const&, tvm::runtime::ObjectPtr<tvm::runtime::Object> const&)::{lambda(tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*)#1}::operator()(tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*) const
        at /workspace/mlc-llm/cpp/llm_chat.cc:1532
  2: mlc::llm::LLMChat::Reload(tvm::runtime::TVMArgValue, tvm::runtime::String, tvm::runtime::String)
        at /workspace/mlc-llm/cpp/llm_chat.cc:553
  1: mlc::llm::TokenizerFromPath(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
        at /workspace/mlc-llm/cpp/tokenizers.cc:63
  0: _ZN3tvm7runtime6deta
  File "/workspace/mlc-llm/cpp/tokenizers.cc", line 63
TVMError: Cannot find any tokenizer under: /home/alphaarea/models/CausalLM-7B-DPO-alpha-q0f16
```

Here is the `mlc-chat-config.json` generated by `mlc_chat gen_config`, which looks like it already recognizes the tokenizer file. But it doesn't work in practice

```json
{
  ...
  "tokenizer_files": [
    "vocab.json",
    "merges.txt",
    "tokenizer_config.json"
  ],
  "version": "0.1.0"
}
```

## To Reproduce

1. Several of CausalLM's models use the same tokenizer format, which can be reproduced by downloading the smallest model [CausalLM/7B-DPO-alpha](https://huggingface.co/CausalLM/7B-DPO-alpha)

2. convert, gen_config and compile  
  ```shell
  MODEL_PATH='/home/alphaarea/models/CausalLM-7B-DPO-alpha'
  MLC_QUANT='q0f16'
  MLC_DEV='cuda'
  MLC_SHARDS=4
  MODEL_ARCH='llama'
  MODEL_TEMP='gpt2'
  MODEL_NAME=${MODEL_PATH##*/}
  MODEL_OUTPUT=$MODEL_PATH'-'$MLC_QUANT
  MODEL_LIB=$MODEL_NAME'-'$MLC_QUANT'-'$MLC_DEV'.so'
  
  mlc_chat convert_weight --quantization $MLC_QUANT --model-type $MODEL_ARCH --output $MODEL_OUTPUT $MODEL_PATH
  mlc_chat gen_config --quantization $MLC_QUANT --model-type $MODEL_ARCH --conv-template $MODEL_TEMP --tensor-parallel-shards $MLC_SHARDS --output $MODEL_OUTPUT $MODEL_PATH
  mlc_chat compile --device $MLC_DEV --output $MODEL_OUTPUT/$MODEL_LIB $MODEL_OUTPUT/mlc-chat-config.json
  ```

3. run  in python
```python
from mlc_chat import ChatModule
cm = ChatModule(model="/yourpath/CausalLM-7B-DPO-alpha-q0f16", model_lib_path="/yourpath/CausalLM-7B-DPO-alpha-q0f16/CausalLM-7B-DPO-alpha-q0f16-cuda.so")
```

## Expected behavior

TVMError: Cannot find any tokenizer under: /yourpath/CausalLM-7B-DPO-alpha-q0f16

## Environment

 - Platform: CUDA
 - Operating system: Ubuntu 22.04.3 LTS
 - Device: Tesla P100
 - How you installed MLC-LLM: `python3 -m pip install --pre -U -f https://mlc.ai/wheels mlc-chat-nightly-cu121 mlc-ai-nightly-cu121`
 - How you installed TVM-Unity: pip
 - Python version: 3.11
 - GPU driver version: 545.23.08
 - CUDA/cuDNN version: 12.1

**Comment by junrushao** [comment]
Currently we support the following tokenizers:
- SentencePiece
- HuggingFace
- RWKV world
- Byte-level BPE

See the tokenizer finding logics here for more details: https://github.com/mlc-ai/mlc-llm/blob/main/cpp/tokenizers.cc. The tokenizer-related files exist (`vocab.json`, `merges.txt` and `tokenizer_config.json`) don't match any of the patterns in our tokenizer detection, and that's why an error is reported.

Not super familiar with the tokenizer part - could you share which tokenizer it is? Please feel free to contribute if you are interested!

**Comment by alphaarea** [comment]
I've figured it out, the models I've been able to run without problems in the past have the tokenizer_class `LlamaTokenizer` or  `LlamaTokenizerFast` in `tokenizer_config.json`. But the CausalLM-72B is `GPT2Tokenizer`. And I had a similar problem when I trying Nous-Capybara-34B, whose tokenizer_class is `YiTokenizer`.

Does HuggingFace tokenizers support mean only `LlamaTokenizer` and `LlamaTokenizerFast` in currently? 

In the future, will the common tokenizer supported by `transformers.AutoTokenizer` be more easily supported by mlc-llm?

**Comment by junrushao** [comment]
I do think fundamentally we support full HuggingFace tokenizers because we compile its full source in rust: https://github.com/mlc-ai/tokenizers-cpp with some wrapping logic:
- Rust wrapper: https://github.com/mlc-ai/tokenizers-cpp/blob/main/rust/src/lib.rs#L106-L130
- Expose Rust wrapper in C++: https://github.com/mlc-ai/tokenizers-cpp/blob/main/src/huggingface_tokenizer.cc#L84

It would be awesome if you'd love to contribute adding the related wrappers to `tokenizers-cpp`!

**Comment by junrushao** [comment]
Ah I just noticed that `GPT2Tokenizer` is actually byte-level BPE tokenizer, which is supported already. We only need to figure out what the missing file `add_tokens.json` is used for

**Comment by junrushao** [comment]
I saw a blog explaining this file. Let me know if it's helpful! https://blog.rfox.eu/en/Programming/How_to_run_your_own_LLM_GPT.html

**Comment by CharlieFRuan** [comment]
I'll see if there's a way of generating an `added_tokens.json` during `gen_config`, just like how we currently convert `tokenizer.model` to `tokenizer.json` there. 

https://github.com/mlc-ai/mlc-llm/blob/main/python/mlc_chat/interface/gen_config.py#L132-L153

Meanwhile we might have to do it manually.

**Comment by junrushao** [comment]
@CharlieFRuan I tried to add an `added_tokens.json` with an empty json string "{}", but got another error from our tokenizer wrapper complaining about `merges.txt`:

```
thread '<unnamed>' panicked at 'Invalid merges.txt file.', src/lib.rs:63:21
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
fatal runtime error: failed to initiate panic, error 5
```

[This line](https://github.com/mlc-ai/tokenizers-cpp/blob/main/rust/src/lib.rs#L63) in our tokenizer wrapper tries to split each line in `merges.txt` into two pieces, separate by " ", which fails at the last line which only contains:

```
å
```

**Comment by junrushao** [comment]
Note that the `merges.txt` file is different from GPT2's [official one](https://huggingface.co/gpt2/raw/main/merges.txt).

**Comment by junrushao** [comment]
OK I know how to make this work now! @alphaarea There are two things you will want to patch up:

- Add an `added_tokens.json` which contains an empty json object: "{}"
- Replace the truncated `merge.txt` with QWen's [official one](https://huggingface.co/vonjack/Qwen-LLaMAfied-HFTok-7B-Chat/blob/main/merges.txt).

**Comment by alphaarea** [comment]
> OK I know how to make this work now! @alphaarea There are two things you will want to patch up:
> 
> * Add an `added_tokens.json` which contains an empty json object: "{}"
> * Replace the truncated `merge.txt` with QWen's [official one](https://huggingface.co/vonjack/Qwen-LLaMAfied-HFTok-7B-Chat/blob/main/merges.txt).

Very thanks, I successfully run [CausalLM/7B-DPO-alpha](https://huggingface.co/CausalLM/7B-DPO-alpha) follow your way. English and Chinese both run good.

And I compare the `mergers.txt` from [CausalLM/7B-DPO-alpha](https://huggingface.co/CausalLM/7B-DPO-alpha) and [vonjack/Qwen-LLaMAfied-HFTok-7B-Chat](https://huggingface.co/vonjack/Qwen-LLaMAfied-HFTok-7B-Chat). The front half of them is exactly the same. But the [CausalLM/7B-DPO-alpha](https://huggingface.co/CausalLM/7B-DPO-alpha)'s `mergers.txt` is short, and looks like having a incomplete ending. The last line only has one character `å`. I deleted the line and try to run it, can't believe it work well. Seems no different with when use `mergers.txt` from [vonjack/Qwen-LLaMAfied-HFTok-7B-Chat](https://huggingface.co/vonjack/Qwen-LLaMAfied-HFTok-7B-Chat).

Is this due to an error in the file provided by CausalLM itself?

----------

When I use the same way on [CausalLM/72B-preview-llamafied-qwen-llamafy](https://huggingface.co/CausalLM/72B-preview-llamafied-qwen-llamafy), it didn't have the same effect. It output broken characters, looks like the tokenizer is still having error.

So I ran the test all over again, I noticed a warning appeared when starting the convert_weight

```log
[2024-01-06 11:57:23] WARNING utils.py:25: Unused extern parameters: model.layers.0.self_attn.k_proj.bias, model.layers.0.self_attn.o_proj.bias, model.layers.0.self_attn.q_proj.bias, model.layers.0.self_attn.v_proj.bias, model.layers.1.self_attn.k_proj.bias...
```

(Incomplete, the warning is very long)

Is this the reason why the model outputs broken characters? Other than that I haven't encountered any other warning messages

----------

CausalLM is not a popular model, I'm not sure if there's something wrong with the model itself.

If manager determines that these errors are caused by the CauseLM's non-standard llama model itself, please close the issues.
