### ISSUE TITLE
[Bug] TVM runtime cannot find vm_load_executable

### ISSUE THREAD

**Issue by xuqiang-idotools** [mlc-ai/mlc-llm#1535]
## 🐛 Bug

I build the library libtvm4j_runtime_packed.so with the prebuild tar as below:
https://github.com/mlc-ai/binary-mlc-llm-libs/blob/main/Mistral-7B-Instruct-v0.2/Mistral-7B-Instruct-v0.2-q4f16_1-android.tar

And run the android app got the error as below:
cpp/llm_chat.cc:161: InternalError: Check failed: (fload_exec.defined()) is false: TVM runtime cannot find vm_load_executable

## To Reproduce

1. Downloading the prebuild tar: Mistral-7B-Instruct-v0.2-q4f16_1-android.tar
2. set env as below: 
export ANDROID_NDK="\~/Library/Android/sdk/ndk/25.2.9519653"
export TVM_NDK_CC="\~/Library/Android/sdk/ndk/25.2.9519653/toolchains/llvm/prebuilt/darwin-x86_64/bin/x86_64-linux-android24-clang"
export TVM_HOME="\~/tvm/mlc-llm/3rdparty/tvm"
4. run the script prepare_libs.sh
5. copy so and jar to android project and run it.
6. got the error: vm_load_executable

## Expected behavior

Run the android app successfully.

## Environment

 - Platform (Android):
 - Operating system (MacOS):
 - Device (Honor 20 Pro and more)
 - How you installed MLC-LLM (conda):
 - How you installed TVM-Unity (pip):
 - Python version (3.10):
 - GPU driver version (if applicable):
 - CUDA/cuDNN version (if applicable):
 - TVM Unity Hash Tag (`python -c "import tvm; print('\n'.join(f'{k}: {v}' for k, v in tvm.support.libinfo().items()))"`, applicable if you compile models):
USE_NVTX: OFF
USE_GTEST: AUTO
SUMMARIZE: OFF
USE_IOS_RPC: OFF
USE_MSC: OFF
USE_ETHOSU: 
CUDA_VERSION: NOT-FOUND
USE_LIBBACKTRACE: AUTO
DLPACK_PATH: 3rdparty/dlpack/include
USE_TENSORRT_CODEGEN: OFF
USE_THRUST: OFF
USE_TARGET_ONNX: OFF
USE_AOT_EXECUTOR: ON
BUILD_DUMMY_LIBTVM: OFF
USE_CUDNN: OFF
USE_TENSORRT_RUNTIME: OFF
USE_ARM_COMPUTE_LIB_GRAPH_EXECUTOR: OFF
USE_CCACHE: AUTO
USE_ARM_COMPUTE_LIB: OFF
USE_CPP_RTVM: 
USE_OPENCL_GTEST: /path/to/opencl/gtest
USE_MKL: OFF
USE_PT_TVMDSOOP: OFF
MLIR_VERSION: NOT-FOUND
USE_CLML: OFF
USE_STACKVM_RUNTIME: OFF
USE_GRAPH_EXECUTOR_CUDA_GRAPH: OFF
ROCM_PATH: /opt/rocm
USE_DNNL: OFF
USE_VITIS_AI: OFF
USE_MLIR: OFF
USE_RCCL: OFF
USE_LLVM: llvm-config --link-static
USE_VERILATOR: OFF
USE_TF_TVMDSOOP: OFF
USE_THREADS: ON
USE_MSVC_MT: OFF
BACKTRACE_ON_SEGFAULT: OFF
USE_GRAPH_EXECUTOR: ON
USE_NCCL: OFF
USE_ROCBLAS: OFF
GIT_COMMIT_HASH: 72a7644159cc415788f4d819c7e8196e0eef751d
USE_VULKAN: OFF
USE_RUST_EXT: OFF
USE_CUTLASS: OFF
USE_CPP_RPC: OFF
USE_HEXAGON: OFF
USE_CUSTOM_LOGGING: OFF
USE_UMA: OFF
USE_FALLBACK_STL_MAP: OFF
USE_SORT: ON
USE_RTTI: ON
GIT_COMMIT_TIME: 2023-12-25 10:23:42 -0500
USE_HEXAGON_SDK: /path/to/sdk
USE_BLAS: none
USE_ETHOSN: OFF
USE_LIBTORCH: OFF
USE_RANDOM: ON
USE_CUDA: OFF
USE_COREML: OFF
USE_AMX: OFF
BUILD_STATIC_RUNTIME: OFF
USE_CMSISNN: OFF
USE_KHRONOS_SPIRV: OFF
USE_CLML_GRAPH_EXECUTOR: OFF
USE_TFLITE: OFF
USE_HEXAGON_GTEST: /path/to/hexagon/gtest
PICOJSON_PATH: 3rdparty/picojson
USE_OPENCL_ENABLE_HOST_PTR: OFF
INSTALL_DEV: OFF
USE_PROFILER: ON
USE_NNPACK: OFF
LLVM_VERSION: 17.0.6
USE_OPENCL: OFF
COMPILER_RT_PATH: 3rdparty/compiler-rt
RANG_PATH: 3rdparty/rang/include
USE_SPIRV_KHR_INTEGER_DOT_PRODUCT: OFF
USE_OPENMP: OFF
USE_BNNS: OFF
USE_CUBLAS: OFF
USE_METAL: ON
USE_MICRO_STANDALONE_RUNTIME: OFF
USE_HEXAGON_EXTERNAL_LIBS: OFF
USE_ALTERNATIVE_LINKER: AUTO
USE_BYODT_POSIT: OFF
USE_HEXAGON_RPC: OFF
USE_MICRO: OFF
DMLC_PATH: 3rdparty/dmlc-core/include
INDEX_DEFAULT_I64: ON
USE_RELAY_DEBUG: OFF
USE_RPC: ON
USE_TENSORFLOW_PATH: none
TVM_CLML_VERSION: 
USE_MIOPEN: OFF
USE_ROCM: OFF
USE_PAPI: OFF
USE_CURAND: OFF
TVM_CXX_COMPILER_PATH: /Applications/Xcode_14.2.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++
HIDE_PRIVATE_SYMBOLS: ON

 - Any other relevant information:

## Additional context

I always got the error whatever using prebuild tar or compile my own tar.

**Comment by Hzfengsy** [comment]
You need to edit `android/library/src/main/assets/app-config.json` before `prepare_libs.sh`, following the docs https://llm.mlc.ai/docs/deploy/android.html

**Comment by xuqiang-idotools** [comment]
Yes, I had already modified it as below:
{
  "model_libs": [
    "Mistral-7B-Instruct-v0.2-q4f16_1"
  ],
  "model_list": [
    {
      "model_url": "https://huggingface.co/mlc-ai/mlc-chat-Mistral-7B-Instruct-v0.2-q4f16_1/",
      "local_id": "Mistral-7B-Instruct-v0.2-q4f16_1"
    }
  ],
  "add_model_samples": []
}

**Comment by Nick-infinity** [comment]
https://github.com/mlc-ai/mlc-llm/issues/1517

**Comment by xuqiang-idotools** [comment]
Is “model_lib_path” necessary? The same issue using the config like this:

{
  "model_libs": [
    "mistral_q4f16_1"
  ],
  "model_list": [
    {
      "model_url": "https://huggingface.co/mlc-ai/mlc-chat-Mistral-7B-Instruct-v0.2-q4f16_1/",
      "local_id": "Mistral-7B-Instruct-v0.2-q4f16_1",
      "model_lib": "mistral_q4f16_1"
    }
  ],
  "add_model_samples": []
}

**Comment by hmzdtz** [comment]
I've encountered this issue as well. I checked the generated `libtvm_runtim.so` after compilation and found that they are all for the x86_64 architecture. I couldn't find any for arm64. I'v explicitly set `TVM_NDK_CC` to the path of `aarch64-linux-android28-clang`. Are there steps missing or not well-documented in the documents?

**Comment by CharlieFRuan** [comment]
Closing this one for now. Feel free to open another one if issues persist!
