### ISSUE TITLE
Is it possible to support mistral-8x7b ?

### ISSUE THREAD

**Issue by xuqiang-idotools** [mlc-ai/mlc-llm#1538]
## ⚙️  Request New Models

- Link to an existing implementation (e.g. Hugging Face/Github): https://huggingface.co/mistralai/Mixtral-8x7B-Instruct-v0.1
- Is this model architecture supported by MLC-LLM? (the list of [supported models](https://llm.mlc.ai/docs/prebuilt_models.html)) No

**Comment by CharlieFRuan** [comment]
Mixtral has been supported here: https://github.com/mlc-ai/mlc-llm/tree/main/python/mlc_chat/model/mixtral

You may refer to https://github.com/mlc-ai/mlc-llm/pull/1529 to try it out!
