### ISSUE TITLE
[Question] error: package org.apache.tvm does not exist import org.apache.tvm.Device

### ISSUE THREAD

**Issue by shalinsirwani** [mlc-ai/mlc-llm#1545]
While buidling apk from this project `https://github.com/mlc-ai/mlc-llm/tree/main/android/` getting error `/home/<user_name>/Downloads/mlc-llm/android/library/src/main/java/ai/mlc/mlcllm/ChatModule.java:3: error: package org.apache.tvm does not exist
import org.apache.tvm.Device;`

How to resolve this error.

**Comment by daniele777** [comment]
same problem

**Comment by RageshAntonyHM** [comment]
@shalinsirwani @daniele777 

After running prepare_libs.sh, a jar and a ARM lib will be copied to /library/built/output folder in Android project. 
(Note: NOT `outputs` , it's `output` (singular))

That jar contains apache.tvm package

The problem is, if you "Clean/rebuild Project", the Gradle is clearing the `build/output` folder !!!, so I can't get the package !!!

I fixed this by copying the contents of 'output' folder to a new folder libs (/library/libs).
<img width="183" alt="image" src="https://github.com/mlc-ai/mlc-llm/assets/141845438/f2a90ac2-7f59-4820-bd35-e1db6a9594d3">


Then went to the build.gradle in library folder and changed build/output in both JniLibs and dependenies  like this 

[build/output] ===> [libs]

Then Clean and rebuilt project

**Comment by xiaotongyangTran** [comment]
I met the same problem and tried @RageshAntonyHM  method.  after running the app in Android Studio or manually run prepare_libs.sh, I cannot find the output directory nor tvm jar. 
Is there any other solution or what did I missed?

**Comment by NSTiwari** [comment]
@RageshAntonyHM: 
I'm getting the following error when I'm running `prepare_libs.sh`

![image](https://github.com/mlc-ai/mlc-llm/assets/37960279/80662509-7ee7-4c48-a0b9-e01bddf4d4de)
![image](https://github.com/mlc-ai/mlc-llm/assets/37960279/f3ccc91d-b9a1-488e-9237-97aa4289755f)

Could you please help me with what's possibly going wrong?

**Comment by NSTiwari** [comment]
@RageshAntonyHM: In your case, did you use Linux? I suppose this is an issue specifically for Windows.

**Comment by RageshAntonyHM** [comment]
@NSTiwari No. I am using Mac OS (Macbook M2 )

**Comment by RageshAntonyHM** [comment]
[libs.zip](https://github.com/mlc-ai/mlc-llm/files/14429472/libs.zip)
@NSTiwari @xiaotongyangTran 
check with this. This is my built libs

**Comment by NSTiwari** [comment]
@RageshAntonyHM: Thanks for sharing the libs. I copied the lib files you shared and the project built successfully.
However, when I run the app using the gemma-2b-q4f16_1 model, I get the following error.

```
MLCChat failed

Stack trace:
org.apache.tvm.Base$TVMError: TVMError: Unknown conversation template: gemma_instruction
Stack trace:
  File "/Users/rageshantonyd/Documents/working_prj/mlc-llm/cpp/conv_templates.cc", line 743

	at org.apache.tvm.Base.checkCall(Base.java:173)
	at org.apache.tvm.Function.invoke(Function.java:130)
	at ai.mlc.mlcllm.ChatModule.reload(ChatModule.java:46)
	at ai.mlc.mlcchat.AppViewModel$ChatState$mainReloadChat$1$2.invoke(AppViewModel.kt:648)
	at ai.mlc.mlcchat.AppViewModel$ChatState$mainReloadChat$1$2.invoke(AppViewModel.kt:646)
	at ai.mlc.mlcchat.AppViewModel$ChatState.callBackend(AppViewModel.kt:548)
	at ai.mlc.mlcchat.AppViewModel$ChatState.mainReloadChat$lambda$3(AppViewModel.kt:646)
	at ai.mlc.mlcchat.AppViewModel$ChatState.$r8$lambda$CXL6v4mjTu_Sr5Pk2zFDcus0R-8(Unknown Source:0)
	at ai.mlc.mlcchat.AppViewModel$ChatState$$ExternalSyntheticLambda2.run(Unknown Source:8)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:487)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)


Error message:
TVMError: Unknown conversation template: gemma_instruction
Stack trace:
  File "/Users/rageshantonyd/Documents/working_prj/mlc-llm/cpp/conv_templates.cc", line 743
```

![image](https://github.com/mlc-ai/mlc-llm/assets/37960279/2d2b7346-5061-4f58-9205-0d3b37c758b5)

**Comment by RageshAntonyHM** [comment]
@NSTiwari 
Sorry. I don't have idea. I think that JAR is mapped with my device. May be you should built on your own

**Comment by AashiDutt** [comment]
@RageshAntonyHM , we are trying to run the shell script but it's not working. Could you please compile the tar file for us and share the generated build files?

[prebuilt_libs.zip](https://github.com/mlc-ai/mlc-llm/files/14652320/prebuilt_libs.zip)

**Comment by RageshAntonyHM** [comment]
@AashiDutt 

Is this okay ? https://github.com/mlc-ai/binary-mlc-llm-libs/tree/main

**Comment by NSTiwari** [comment]
@RageshAntonyHM: We need the corresponding JAR files for the Android .tar files that @AashiDutt has shared.

**Comment by RageshAntonyHM** [comment]
@NSTiwari @AashiDutt 

Sorry. I didn't tried that. And my Manager tried compiling a fine tined model and he got many errors 

So we now trying MAID 
https://github.com/Mobile-Artificial-Intelligence/maid

For now it available only for Android

It is based on Flutter and supports GGUF model directly without any conversion like MLC-LLM.

**Comment by RageshAntonyHM** [comment]
@AashiDutt @NSTiwari 

For Gemma, also try this 

https://github.com/tensorflow/tensorflow/issues/63025#issuecomment-1993756859

**Comment by NSTiwari** [comment]
@RageshAntonyHM: I see. However, could you please just give it a try considering that the shell script worked for you before?

It will be really a great help if you could take out some time and see if this works? The fine-tuned model is nearly the same as the original Gemma 2b-it model with little differences.

**Comment by RageshAntonyHM** [comment]
@NSTiwari 

You want the JAR files for your "Science Gemma" ?

**Comment by NSTiwari** [comment]
@RageshAntonyHM: Yes.

**Comment by RageshAntonyHM** [comment]
@NSTiwari 
But for that , do I need your "model file" also ?

**Comment by NSTiwari** [comment]
@RageshAntonyHM: According to the documentation, the initial steps were to convert the model to sharded weights and then compile the model which generates a Android tar file.

These steps are already done by us. If you need the model file, you can find it here:
https://huggingface.co/NSTiwari/scigemma_fine_tuned_quantized/tree/main

We're only stuck at the last step where the Android tar file needs to be compiled using the `prepare_libs.sh` script by putting the tar file in the prebuilt_libs folder inside Android/library folder.

**Comment by RageshAntonyHM** [comment]
@NSTiwari 
But doesn't the JAR files are common?

**Comment by NSTiwari** [comment]
@RageshAntonyHM: No, they are not common. They differ from model to model. Remember, in the same thread, you provided me one of your JAR files? It didn't work.

For the Scigemma model, the JAR generated will be different.

**Comment by RageshAntonyHM** [comment]
@NSTiwari 

Then I think you try other alternatives

In the above mentioned MAID, I directly used fine tined Airboros model without any problem

**Comment by RageshAntonyHM** [comment]
@NSTiwari @AashiDutt 

provide me the app_config.json

**Comment by NSTiwari** [comment]
@RageshAntonyHM:
[app-config.json](https://github.com/mlc-ai/mlc-llm/files/14662870/app-config.json)

**Comment by RageshAntonyHM** [comment]
@NSTiwari @AashiDutt 

Sorry. I also get the same error:

<img width="332" alt="image" src="https://github.com/mlc-ai/mlc-llm/assets/141845438/a07b7388-3836-4930-9919-ae36cbad51b8">

i think we need the Repo Devs support

**Comment by RageshAntonyHM** [comment]
i think llama works but not Gemma

**Comment by NSTiwari** [comment]
@RageshAntonyHM: Were you able to generate the JAR for the files we shared?

**Comment by RageshAntonyHM** [comment]
[Archive 2.zip](https://github.com/mlc-ai/mlc-llm/files/14663221/Archive.2.zip)

@NSTiwari

**Comment by RageshAntonyHM** [comment]
@NSTiwari 

Remove the base Gemma from json. Two Gemma models produce build error

**Comment by NSTiwari** [comment]
@RageshAntonyHM: Okay, just removing the base Gemma from JSON will run, or do I need to anything else additionally?

**Comment by RageshAntonyHM** [comment]
@NSTiwari 

That's enough

**Comment by NSTiwari** [comment]
I still get the same error after removing the base Gemma model.

**Comment by RageshAntonyHM** [comment]
@NSTiwari 

What error ?

**Comment by RageshAntonyHM** [comment]
@NSTiwari 

Sorry. I told about fixing JAR build errors only. But this error also happens for me. 

I think we need the support of MLC-LLM devs here.

**Comment by RageshAntonyHM** [comment]
@NSTiwari 

better to post an issue

**Comment by NSTiwari** [comment]
Hello @RageshAntonyHM: I think I've found the issue. Could you please share the `app-config.json` file you used to generate the JAR files last time?

**Comment by RageshAntonyHM** [comment]
@NSTiwari 

Please update me if you able to run it successfully.  

[app-config.json](https://github.com/mlc-ai/mlc-llm/files/14758988/app-config.json)

And,

**Comment by NSTiwari** [comment]
@RageshAntonyHM: I edited the `app-config.json`, can you please try to run with this? Unfortunately, the shell script doesn't run at my end.
[app-config.json](https://github.com/mlc-ai/mlc-llm/files/14759044/app-config.json)

**Comment by NSTiwari** [comment]
> @RageshAntonyHM: I edited the `app-config.json`, can you please try to run with this? Unfortunately, the shell script doesn't run at my end. [app-config.json](https://github.com/mlc-ai/mlc-llm/files/14759044/app-config.json)

@RageshAntonyHM: Could you check this?

**Comment by RageshAntonyHM** [comment]
@NSTiwari 
[Archive.zip](https://github.com/mlc-ai/mlc-llm/files/14792921/Archive.zip)


you can try in another PCs if the script fails ?

**Comment by NSTiwari** [comment]
> @NSTiwari [Archive.zip](https://github.com/mlc-ai/mlc-llm/files/14792921/Archive.zip)
> 
> you can try in another PCs if the script fails ?

@RageshAntonyHM: Is this zip file based on the updated JSON that I provided?

**Comment by NSTiwari** [comment]
> > @NSTiwari [Archive.zip](https://github.com/mlc-ai/mlc-llm/files/14792921/Archive.zip)
> > you can try in another PCs if the script fails ?
> 
> @RageshAntonyHM: Is this zip file based on the updated JSON that I provided?

Thanks for the help, @RageshAntonyHM. Unfortunately, the app still crashes.
![image](https://github.com/mlc-ai/mlc-llm/assets/37960279/023ba366-2734-44e8-aba7-252154bf2282)

I've created a new [issue](https://github.com/mlc-ai/mlc-llm/issues/2045). Hopefully, the MLC team can check and help.

**Comment by NSTiwari** [comment]
Hello @RageshAntonyHM: We have an update on this issue. The MLC team has suggested to run the below command:
`git submodule update --init --recursive`

![image](https://github.com/mlc-ai/mlc-llm/assets/37960279/dd3e6bcd-ccb4-40d8-b7ef-68cafab2fd30)

Could you please try to generate the JAR files again after running this command? I know I'm asking too much, but unfortunately, CMake is not working on any of my devices. Appreciate your kind assistance.
