### ISSUE TITLE
[Bug] mlc_chat convert_weight fails with: ModuleNotFoundError: No module named 'mlc_chat.nn'

### ISSUE THREAD

**Issue by brian-pieces** [mlc-ai/mlc-llm#1547]
## 🐛 Bug

I'm unable to reproduce the example in the docs for compiling models using the new mlc_chat cli. When trying to convert the weights I get the error: `ModuleNotFoundError: No module named 'mlc_chat.nn'`

## To Reproduce

1. Create fresh conda env with Python 3.11
2. Install mlc_chat from prebuilt
3. Clone weights for RedPajama-INCITE-Chat-3B-v1
4. Run the given convert_weight command:
`mlc_chat convert_weight ./dist/models/RedPajama-INCITE-Chat-3B-v1/ \
    --quantization q4f16_1 \
    -o dist/RedPajama-INCITE-Chat-3B-v1-q4f16_1-MLC`

I then get the ModuleNotFoundError from above.

## Expected behavior

Converted weights for the model. 

## Environment

 - Platform (e.g. WebGPU/Vulkan/IOS/Android/CUDA): Metal
 - Operating system (e.g. Ubuntu/Windows/MacOS/...): MacOS 
 - Device (e.g. iPhone 12 Pro, PC+RTX 3090, ...): M1 Max
 - How you installed MLC-LLM (`conda`, source): python3 -m pip install --pre -U -f https://mlc.ai/wheels mlc-chat-nightly mlc-ai-nightly
 - How you installed TVM-Unity (`pip`, source): python3 -m pip install --pre -U -f https://mlc.ai/wheels mlc-chat-nightly mlc-ai-nightly 
 - Python version (e.g. 3.10): 3.11
 - GPU driver version (if applicable):
 - CUDA/cuDNN version (if applicable):
 - TVM Unity Hash Tag (`python -c "import tvm; print('\n'.join(f'{k}: {v}' for k, v in tvm.support.libinfo().items()))"`, applicable if you compile models): 30c129ef4d43f40c02835a7fa5b485804dbae2c1
 - Any other relevant information:

## Additional context

None

**Comment by junrushao** [comment]
It is a new module introduced by the [latest commit](https://github.com/mlc-ai/mlc-llm/commit/7239a91d4319d57307466bfe3ebf159b6eb82d37).

@brian-pieces Could you share the full Python stacktrace? And @MasterJH5574 Could you confirm?

**Comment by MasterJH5574** [comment]
Indeed there is no `nn` directory under `mlc_chat`. Let me dig a bit to see what happened.
```
~/w/test ❯ ls /home/ruihangl/miniconda3/envs/python311/lib/python3.11/site-packages/mlc_chat/
base.py                embeddings/            libinfo.py             model/                 support/
callback.py            gradio.py              libmlc_llm_module.so*  op/
chat_module.py         help.py                libmlc_llm.so*         __pycache__/
cli/                   __init__.py            loader/                quantization/
compiler_pass/         interface/             __main__.py            rest.py
```

**Comment by MasterJH5574** [comment]
Is it possibly because I forgot to import `nn` in the root `__init__.py`?

**Comment by MasterJH5574** [comment]
Ah it is possible that I forgot to add an `__init__.py` under `nn` subpackage.

**Comment by junrushao** [comment]
> Ah it is possible that I forgot to add an `__init__.py` under `nn` subpackage.

Ah that could be the cause!

**Comment by MasterJH5574** [comment]
Okay I added it in! https://github.com/mlc-ai/mlc-llm/pull/1548

I will trigger the wheel build after merging this PR, and the build will finish after about 2-3 hours. Will report back to you @brian-pieces when it is ready. Thanks for reporting the issue!

**Comment by junrushao** [comment]
Thanks @MasterJH5574 for the swift response!!
