### ISSUE TITLE
[Bug] AMD GPU Bridge causes rcclError: unhandled cuda error

### ISSUE THREAD

**Issue by TNT3530** [mlc-ai/mlc-llm#1552]
## 🐛 Bug

After a few months of running successfully across 4 PCIe 3.0 16x linked cards, switching to a GPU Bridge causes MLC-LLM to crash during initialization. 

Here is the output when attempting to run with `NCCL_DEBUG=INFO`
[screenlog.txt](https://github.com/mlc-ai/mlc-llm/files/13852656/screenlog.txt)

## To Reproduce
ROCm 6.0
mlc-ai-nightly-rocm57==0.12.dev1953
mlc-chat-nightly-rocm57==0.1.dev741

```
cm = ChatModule(model="goliath-120b-q4f16_1", chat_config=ChatConfig(
	max_gen_len=4096,
	conv_template="LM",
	temperature=0.75,
	repetition_penalty=1.1,
	top_p=0.9,
	tensor_parallel_shards=4,
	context_window_size=4096
))

output = cm.generate(
    prompt="What is the meaning of life?",
    progress_callback=StreamToStdout(callback_interval=2),
)
```

## Expected behavior
Model should load into VRAM and start inferring

## Environment

 - Platform (e.g. WebGPU/Vulkan/IOS/Android/CUDA): ROCm 6.0
 - Operating system (e.g. Ubuntu/Windows/MacOS/...): Ubuntu 22.04
 - Device (e.g. iPhone 12 Pro, PC+RTX 3090, ...): 4x AMD Instinct MI100
 - How you installed MLC-LLM (`conda`, source): conda
 - How you installed TVM-Unity (`pip`, source): pip
 - Python version (e.g. 3.10): 3.10.12
 - TVM Unity Hash Tag: [unity.txt](https://github.com/mlc-ai/mlc-llm/files/13852651/unity.txt)

## Additional context
I originally had dev1690 and dev505 for their respective versions, same issue. Inferring with a smaller model on a single card works fine. `rocm-bandwidth-test` runs fine, so I don't think the GPU Bridge is defective.

**Comment by TNT3530** [comment]
Issue is confirmed only with the bridge enabled, adding `amdgpu.use_xgmi_p2p=0` to grub config makes the issue stop with no other changes.

**Comment by TNT3530** [comment]
Note: As of the latest version this still happens. Other libraries dont have this problem, so I think its a kernel issue

**Comment by tqchen** [comment]
this likely is a rccl issue and not something mlc project can do about, so closing it for now. love to know if there are followup findings and we love to share these setups
