### ISSUE TITLE
Support Phi-2 on iOS

### ISSUE THREAD

**Issue by winstonschen** [mlc-ai/mlc-llm#1554]
## ⚙️  Request New Models

- Link to an existing implementation (e.g. Hugging Face/Github): [](https://huggingface.co/microsoft/phi-2)
- Is this model architecture supported by MLC-LLM? (the list of [supported models](https://llm.mlc.ai/docs/prebuilt_models.html)) Yes

**Comment by Kartik14** [comment]
Please check [this](https://github.com/mlc-ai/binary-mlc-llm-libs/pull/70)

**Comment by Kartik14** [comment]
Have you checked with any other model? I am not familiar with IOS. cc @davidpissarra

**Comment by Lq-qm** [comment]
There is a bug raised on #1465. Check it if is not the same as you having.

**Comment by davidpissarra** [comment]
Hi @winstonschen, thanks for coming up with this. Still some tweaks to do, so that iOS fully supports the new model compilation flow. I will keep you updated.

cc @CharlieFRuan @Kartik14

**Comment by davidpissarra** [comment]
iOS refactor to support the new flow is implemented here #1601. Nevertheless, it seems phi-2 is having some issues running on metal #1505. While doing some checking I wasn't able to run phi-2 on iphone. Still not sure if this metal issue also applies to iphone. I will continue to dig a bit

**Comment by CharlieFRuan** [comment]
Hi @winstonschen this should be fixed by https://github.com/apache/tvm/pull/16438. We'll recompile the phi-2 for iphone soon.

**Comment by davidpissarra** [comment]
Libs fixed in https://github.com/mlc-ai/binary-mlc-llm-libs/pull/81
