### ISSUE TITLE
OpenCL Support when Convert Weight [Feature Request] 

### ISSUE THREAD

**Issue by BeiningWu** [mlc-ai/mlc-llm#1557]
## 🚀 Feature

MLC_CHAT ADD OPENCL SUPPORT
## Motivation

When I used 
```shell
python3 -m mlc_llm.build ...
```
on my opencl mobile device, i got the error as #1541 .
So i used the comdline
```shell
mlc_chat convert_weight...
```
to convert my custom llm.
But I got the error as follow:
ValueError: Auto detection for device `opencl` is not supported. Currently only supports: dict_keys(['cpu', 'cuda', 'metal', 'vulkan', 'rocm'])

As so far, I can't covert and quantization my custom llm model and run on my orangepi 5 plus( I follow the #821 , and it seems not work.)

**Comment by junrushao** [comment]
@Hzfengsy Yeah definitely! Would you like to enhance these lines: https://github.com/apache/tvm/blob/main/python/tvm/target/detect_target.py#L77

**Comment by BeiningWu** [comment]
> @Hzfengsy Yeah definitely! Would you like to enhance these lines: https://github.com/apache/tvm/blob/main/python/tvm/target/detect_target.py#L77

oh! Thanks for your reply and I'll try it later

**Comment by federicoparra** [comment]
> @Hzfengsy Yeah definitely! Would you like to enhance these lines: https://github.com/apache/tvm/blob/main/python/tvm/target/detect_target.py#L77

Oh I see you are already on top of this (you asked me to open a ticket for this issue but I see BeiningWu has brought it up already)

**Comment by JokerJostar** [comment]
have the function been enhanced yet?

**Comment by mengshyu** [comment]
Hi @BeiningWu, I fixed it in [#16854](https://github.com/apache/tvm/pull/16854), Can you try it again with latest mlc llm and relax. Thanks.
