### ISSUE TITLE
[Question] How can mlc-llm be used to complete the deployment of large models without quantization

### ISSUE THREAD

**Issue by lss0510** [mlc-ai/mlc-llm#1559]
## ❓ General Questions

I wanted to use mlc-llm framework to complete the unquantized deployment of RedPajama-INCITE-Chat-3B-v1, so I compiled the large model as follows: “python -X faulthandler build.py --hf-path RedPajama-INCITE-Chat-3B-v1 --quantization q4f32_1 --target cuda  --max-seq-len 768 --build-model-only ", However, when I ran "./build/mlc_chat_cli --model RedPajama-INCITE-Chat-3B-v1-q4f32_1 --device cuda "to try to deploy a large model, I got the following error:
![image](https://github.com/mlc-ai/mlc-llm/assets/67734602/1fd7a9bd-e012-40f1-be2b-e5631389e0fd)
By comparison, I find that with build-model-only parameter, there is no param subfolder under the generated folder, which leads to the failure to read the corresponding configuration file. Is it possible for me to generate the corresponding configuration file to complete the deployment of the large model?

**Comment by CharlieFRuan** [comment]
We have updated the workflow and deprecated the usage of `build.py`. Please follow https://llm.mlc.ai/docs/compilation/compile_models.html. We now break it down into three seperate commands: `gen_config`, `convert_weight`, and `compile`.

To deploy unquantized models, you just need to build the model library in `q0f16` or `q0f32`, and convert the weights with `q0f16` or `q0f32` as well.

**Comment by lss0510** [comment]
Thank you. When I followed your instructions, I did deploy the unquantized model. However, my ultimate goal is to use mlc-llm to complete the deployment of my own quantified model. Now I have completed the quantification of RedPajama with the help of my own code (weight: 4, activation: 16), how can I use mlc-llm to complete the deployment of the quantified model.

**Comment by CharlieFRuan** [comment]
I see, just to make sure, you are trying to deploy a model quantized through other methods right?

I do not think this is well-supported as of now. You might need to write your own code in mlc-llm; you may refer to the [tutorial notebook](https://github.com/mlc-ai/notebooks/blob/main/mlc-llm/tutorial_add_new_model_architecture_in_tvm_nn_module.ipynb) that uses gpt2 as an example, specifically, you may want to look at `gpt2_loader.py` and `gpt2_quantization.py`. You mainly want to map between mlc-llm's params with your quantized params, and how it may change the inference (e.g. do we want to dequantize during inference, etc.).

What is your quantization algorithm? We have some support for AWQ.

**Comment by lss0510** [comment]
I have used the awq quantization algorithm implemented by myself to complete the quantization of the model, and I have also implemented the conversion of the quantized file by myself, but I have encountered problems in the model compilation now, and I do not know how to modify the mapping between the original parameters and the quantized parameters to change the reasoning. My current work is based on build.py, core.py, utils.py in mlc_llm. I only know that the model is in a form that supports quantized weights after mod_transform_before_build(), but I don't know how to modify it. Can you give me some advice?
![image](https://github.com/mlc-ai/mlc-llm/assets/67734602/40e961db-49dd-42f4-8824-93b8f9ce15d1)

**Comment by tqchen** [comment]
closing due to stale status, the latest system comes with q0 support
