### ISSUE TITLE
[Question] q4f16_0 support in new workflow.

### ISSUE THREAD

**Issue by neobaud** [mlc-ai/mlc-llm#1561]
## ❓ q4f16_0 Support

Has q4f16_0 been deprecated in the new workflow (i.e. mlc_chat compile etc.)?  Will this always be the case?

I find q4f16_0 to be considerably faster than q4f16_1 on Adreno? Would it be possible to reinstate it?

**Comment by Hzfengsy** [comment]
Added back in https://github.com/mlc-ai/mlc-llm/pull/1566
