### ISSUE TITLE
[Bug]  Mismatch Between build args comments  in core.py and Actual Command Line Arguments

### ISSUE THREAD

**Issue by na20215** [mlc-ai/mlc-llm#1574]
## 🐛 Bug??##

I've noticed that the code of the command line build parameters have been updated, but the corresponding comments in core.py have not been synchronized. This has caused a problem where the parameter names and how to use them in the describe in core.py are different from what's actually in the code. This mismatch is particularly confusing for noob like myself, who do not have the ability to understand how to use the new version of the code just by looking at the commits. I believe many other beginners are facing the same issue.

I expected:
update the Comment in 'core.py' which about guidance on the arguments used in the build command line.

**Comment by MasterJH5574** [comment]
We have now deprecated the old model compilation flow which used `core.py`. The documentation of the model new compilation flow is at https://llm.mlc.ai/docs/compilation/compile_models.html. You are welcome to check it out.
