### ISSUE TITLE
Missing weights for Llama 70B

### ISSUE THREAD

**Issue by hrishi-06** [mlc-ai/mlc-llm#1576]
The wieghts for Llama 70B as found [here](https://huggingface.co/mlc-ai/Llama-2-70b-chat-hf-q4f16_1-MLC) do not seem to be correct. Git LFS pointer is likely not pointing to correct location.

**Comment by junrushao** [comment]
How about this: https://huggingface.co/junrushao/Llama-2-70b-chat-hf-q4f16_1

**Comment by junrushao** [comment]
You may want to try this in command line

```
mlc_chat chat HF://junrushao/Llama-2-70b-chat-hf-q4f16_1
```

**Comment by hrishi-06** [comment]
> How about this: https://huggingface.co/junrushao/Llama-2-70b-chat-hf-q4f16_1

Thank You! This link worked
