### ISSUE TITLE
[Question] How to achieve the best optimization effect by searching different hardware devices

### ISSUE THREAD

**Issue by shifeiwen** [mlc-ai/mlc-llm#1583]
## ❓ General Questions

As described in the title, I saw that after the code mod is fused, it needs to go through dl.ApplyDefaultSchedule(), which uses some general operator optimizations of gpu. I want to know whether the gpu for different hardware devices can search for some schedules separately. strategies to achieve optimal performance.

**Comment by shifeiwen** [comment]
Are there any open interfaces that can help me, or information that I can refer to?

**Comment by Hzfengsy** [comment]
We use different configs for different targets in flight. e.g. 
https://github.com/apache/tvm/blob/474c06b8b3e9c0f751a69a7aaf718af156edcd32/python/tvm/dlight/gpu/gemv.py#L422-L500

**Comment by shifeiwen** [comment]
These settings on the GPU backend may produce better results on different hardware devices through auto_scheduler.

**Comment by Hzfengsy** [comment]
I'm afraid the auto-scheduler won't help, at least on CUDA devices.

**Comment by shifeiwen** [comment]
I want to complete some testing on android, is there some documentation that can help me experiment. Thanks

**Comment by shifeiwen** [comment]
I can see that you have made many commits on the files for scheduling optimization, I think you should be an expert in this area, can you please advise, if I want to optimize for a specific adreno gpu, for example matmul.py config I can try those @Hzfengsy
