### ISSUE TITLE
[Bug] VulkanOnWindows: Intel i7 device giving VK_ERROR_OUT_OF_DEVICE_MEMORY during the Run

### ISSUE THREAD

**Issue by HarshithaSanku123** [mlc-ai/mlc-llm#1584]
## 🐛 Bug
Device: Intel Windows machine
seeing the following error after using locally compiled model library following the steps in page:
Loading model...
[17:50:02] C:\Miniconda\envs\mlc-llm-build\conda-bld\mlc-chat-cli-nightly-package_1703567242858\work\3rdparty\tvm\src\runtime\vulkan\vulkan_buffer.cc:61: InternalError: Check failed: (__e == VK_SUCCESS) is false: Vulkan Error, code=-2: VK_ERROR_OUT_OF_DEVICE_MEMORY
Stack trace not available when DMLC_LOG_STACK_TRACE is disabled at compile time.

1.Followed steps here to compile model library for windows:https://llm.mlc.ai/docs/compilation/compile_models.html#compile-model-libraries
2. For running the model we followed steps from: https://llm.mlc.ai/docs/index.html#getting-started

## Environment

 - Platform Vulkan:
 - Operating system Windows:
 - Device Intel i7
 - How you installed MLC-LLM (`conda`, source):
 - How you installed TVM-Unity (`pip`, source):
 - Python version  3.10:
 - GPU driver version : Intel UHD Graphics 630: 27.20.100.9415
 - TVM Unity Hash Tag (`python -c "import tvm; print('\n'.join(f'{k}: {v}' for k, v in tvm.support.libinfo().items()))"`, applicable if you compile models):  find below
 USE_NVTX: OFF
USE_GTEST: AUTO
SUMMARIZE: OFF
USE_IOS_RPC: OFF
USE_MSC: OFF
USE_ETHOSU:
CUDA_VERSION: NOT-FOUND
USE_LIBBACKTRACE: AUTO
DLPACK_PATH: 3rdparty/dlpack/include
USE_TENSORRT_CODEGEN: OFF
USE_THRUST: OFF
USE_TARGET_ONNX: OFF
USE_AOT_EXECUTOR: ON
BUILD_DUMMY_LIBTVM: OFF
USE_CUDNN: OFF
USE_TENSORRT_RUNTIME: OFF
USE_ARM_COMPUTE_LIB_GRAPH_EXECUTOR: OFF
USE_CCACHE: AUTO
USE_ARM_COMPUTE_LIB: OFF
USE_CPP_RTVM:
USE_OPENCL_GTEST: /path/to/opencl/gtest
USE_MKL: OFF
USE_PT_TVMDSOOP: OFF
MLIR_VERSION: NOT-FOUND
USE_CLML: OFF
USE_STACKVM_RUNTIME: OFF
USE_GRAPH_EXECUTOR_CUDA_GRAPH: OFF
ROCM_PATH: /opt/rocm
USE_DNNL: OFF
USE_VITIS_AI: OFF
USE_MLIR: OFF
USE_RCCL: OFF
USE_LLVM: llvm-config --link-static
USE_VERILATOR: OFF
USE_TF_TVMDSOOP: OFF
USE_THREADS: ON
USE_MSVC_MT: OFF
BACKTRACE_ON_SEGFAULT: OFF
USE_GRAPH_EXECUTOR: ON
USE_NCCL: OFF
USE_ROCBLAS: OFF
GIT_COMMIT_HASH: 5c884369758793fe5b15aefd5b62122e04efce57
USE_VULKAN: ON
USE_RUST_EXT: OFF
USE_CUTLASS: OFF
USE_CPP_RPC: OFF
USE_HEXAGON: OFF
USE_CUSTOM_LOGGING: OFF
USE_UMA: OFF
USE_FALLBACK_STL_MAP: OFF
USE_SORT: ON
USE_RTTI: ON
GIT_COMMIT_TIME: 2023-12-26 13:14:06 -0800
USE_HEXAGON_SDK: /path/to/sdk
USE_BLAS: none
USE_ETHOSN: OFF
USE_LIBTORCH: OFF
USE_RANDOM: ON
USE_CUDA: OFF
USE_COREML: OFF
USE_AMX: OFF
BUILD_STATIC_RUNTIME: OFF
USE_CMSISNN: OFF
USE_KHRONOS_SPIRV: OFF
USE_CLML_GRAPH_EXECUTOR: OFF
USE_TFLITE: OFF
USE_HEXAGON_GTEST: /path/to/hexagon/gtest
PICOJSON_PATH: 3rdparty/picojson
USE_OPENCL_ENABLE_HOST_PTR: OFF
INSTALL_DEV: OFF
USE_PROFILER: ON
USE_NNPACK: OFF
LLVM_VERSION: 17.0.6
USE_OPENCL: OFF
COMPILER_RT_PATH: 3rdparty/compiler-rt
RANG_PATH: 3rdparty/rang/include
USE_SPIRV_KHR_INTEGER_DOT_PRODUCT: OFF
USE_OPENMP: OFF
USE_BNNS: OFF
USE_CUBLAS: OFF
USE_METAL: OFF
USE_MICRO_STANDALONE_RUNTIME: OFF
USE_HEXAGON_EXTERNAL_LIBS: OFF
USE_ALTERNATIVE_LINKER: AUTO
USE_BYODT_POSIT: OFF
USE_HEXAGON_RPC: OFF
USE_MICRO: OFF
DMLC_PATH: 3rdparty/dmlc-core/include
INDEX_DEFAULT_I64: ON
USE_RELAY_DEBUG: OFF
USE_RPC: ON
USE_TENSORFLOW_PATH: none
TVM_CLML_VERSION:
USE_MIOPEN: OFF
USE_ROCM: OFF
USE_PAPI: OFF
USE_CURAND: OFF
TVM_CXX_COMPILER_PATH: C:/Program Files/Microsoft Visual Studio/2022/Enterprise/VC/Tools/MSVC/14.37.32822/bin/HostX64/x64/cl.exe
HIDE_PRIVATE_SYMBOLS: OFF

**Comment by Hzfengsy** [comment]
The error message is clear that you do not have enough memory for vulkan device

**Comment by HarshithaSanku123** [comment]
the machine have 32GB free memory, I guess that should be sufficient to run the app.

**we tried on the AMD windows laptop and seeing the same issue:**
Loading model...
[17:29:58] C:\Miniconda\envs\mlc-llm-build\conda-bld\mlc-chat-cli-nightly-package_1704863156333\work\3rdparty\tvm\src\runtime\vulkan\vulkan_buffer.cc:61: InternalError: Check failed: (__e == VK_SUCCESS) is false: Vulkan Error, code=-2: VK_ERROR_OUT_OF_DEVICE_MEMORY
Stack trace not available when DMLC_LOG_STACK_TRACE is disabled at compile time.

[17:29:58] C:\Miniconda\envs\mlc-llm-build\conda-bld\mlc-chat-cli-nightly-package_1704863156333\work\3rdparty\tvm\src\runtime\vulkan\vulkan_buffer.cc:61: InternalError: Check failed: (__e == VK_SUCCESS) is false: Vulkan Error, code=-2: VK_ERROR_OUT_OF_DEVICE_MEMORY
Stack trace not available when DMLC_LOG_STACK_TRACE is disabled at compile time.

AMD specifications:
AMD RYZEN PRO7
Driver Version: 27.20.15026.9002

pls let me know, if we need any settings to carveout memory for Vk additionally to run the app?

**Comment by kripper** [comment]
Similar to https://github.com/mlc-ai/mlc-llm/issues/1673#issuecomment-1913720697
