### ISSUE TITLE
[Bug] ios can not load compiled model

### ISSUE THREAD

**Issue by zkh2016** [mlc-ai/mlc-llm#1588]
## 🐛 Bug

ios get error:

"Failed to resolve model config: The data couldn’t be read because it is missing."

## To Reproduce

1. convert and compile model : https://llm.mlc.ai/docs/compilation/compile_models.html
1. build and run ios app : https://llm.mlc.ai/docs/deploy/ios.html
1.

## Environment

 - My Mac( Designed for iPhone)

## Additional context

The model converted according to the tutorial can run on Android, but an error occurred when loading the model on iOS.

**Comment by davidpissarra** [comment]
Hi @zkh2016! There are still some tweaks to do so that iOS fully supports the new model compilation flow. I will keep you updated.

**Comment by davidpissarra** [comment]
Libs fixed in https://github.com/mlc-ai/binary-mlc-llm-libs/pull/81
