### ISSUE TITLE
[Feature Request] make SLM support quant by CPU in weight convert process

### ISSUE THREAD

**Issue by null-define** [mlc-ai/mlc-llm#1591]
## 🚀 Feature
make SLM support quant by CPU in weight convert process

## Motivation
legacy way by using `mlc_llm.build` can use CPU to quant weight in android model build process .
but current SLM's `mlc_chat convert_weight`  process doesn't support CPU quantization.
when user try to build model on a machine without enable x86's TVM GPU build option or convert model without GPU env, the process will fail.

**Comment by shifeiwen** [comment]
The modification I tried was to add in check_device.py to break out of the current loop when device_str == "cpu". Then you can use cpu quantization.

**Comment by null-define** [comment]
> The modification I tried was to add in check_device.py to break out of the current loop when device_str == "cpu". Then you can use cpu quantization.

thanks, I modified auto_target.py and convert_weight.py then quantization passed
