### ISSUE TITLE
Multi-GPU support for larger-than-VRAM models

### ISSUE THREAD

**Issue by emvw7yf** [mlc-ai/mlc-llm#16]
Awesome project, thanks!

Does it support sharding large models across multiple GPUs, or would this be in scope for this project in the future?

**Comment by tqchen** [comment]
thank you for your suggestion, yes we love to support the needs of the community

**Comment by earonesty** [comment]
llama.cpp seems to support this now fyi!

**Comment by tqchen** [comment]
Multi gpu now lands in mlc
