### ISSUE TITLE
[Bug] ROCM build Llama2 model LLVM verify failed

### ISSUE THREAD

**Issue by lhcalibur** [mlc-ai/mlc-llm#1600]
## 🐛 Bug

ROCM build Llama2 model failed:

src/target/llvm/codegen_llvm.cc", line 354
TVMError: LLVM module verification failed with the following errors:
Call parameter type does not match function signature!
float 1.000000e+04
 <4 x float>  %46 = call <4 x float> @__ocml_pow_f32(float 1.000000e+04, float %45)
Both operands to a binary operator are not of the same type!
  %47 = fdiv float %41, <4 x float> %46
Call parameter type does not match function signature!
  %47 = fdiv float %41, <4 x float> %46
 <4 x float>  %48 = call <4 x float> @__ocml_sin_f32(float %47)
fptrunc source and destination must both be a vector or neither
  %49 = fptrunc <4 x float> %48 to half
Call parameter type does not match function signature!
float 1.000000e+04
 <4 x float>  %222 = call <4 x float> @__ocml_pow_f32(float 1.000000e+04, float %221)
Both operands to a binary operator are not of the same type!
  %223 = fdiv float %217, <4 x float> %222
Call parameter type does not match function signature!
  %223 = fdiv float %217, <4 x float> %222
 <4 x float>  %224 = call <4 x float> @__ocml_cos_f32(float %223)
fptrunc source and destination must both be a vector or neither
  %225 = fptrunc <4 x float> %224 to half
Call parameter type does not match function signature!
float 1.000000e+04
 <4 x float>  %391 = call <4 x float> @__ocml_pow_f32(float 1.000000e+04, float %390)
Both operands to a binary operator are not of the same type!
  %392 = fdiv float %386, <4 x float> %391
Call parameter type does not match function signature!
  %392 = fdiv float %386, <4 x float> %391
 <4 x float>  %393 = call <4 x float> @__ocml_sin_f32(float %392)
fptrunc source and destination must both be a vector or neither
  %394 = fptrunc <4 x float> %393 to half
Call parameter type does not match function signature!
float 1.000000e+04
 <4 x float>  %681 = call <4 x float> @__ocml_pow_f32(float 1.000000e+04, float %680)
Both operands to a binary operator are not of the same type!
  %682 = fdiv float %676, <4 x float> %681
Call parameter type does not match function signature!
  %682 = fdiv float %676, <4 x float> %681
 <4 x float>  %683 = call <4 x float> @__ocml_cos_f32(float %682)
fptrunc source and destination must both be a vector or neither
  %684 = fptrunc <4 x float> %683 to half

## To Reproduce

1.mlc-llm: a42bab40fedef529bbe9826252782c9d1425fb76
2.tvm: f7fa60201602fee8eae4e1e318b995c8493cf02f (mlc-ai/relax)
3.PATH=/opt/rocm/llvm/bin:$PATH mlc_chat compile dist/Llama-2-70b-chat-hf-q4f16_1-MLC/mlc-chat-config.json --device rocm -o dist/libs/Llama-2-70b-chat-hf-q4f16_1-rocm.so

## Environment

 - Platform (e.g. WebGPU/Vulkan/IOS/Android/CUDA): ROCM
 - Operating system (e.g. Ubuntu/Windows/MacOS/...): Ubuntu
 - How you installed MLC-LLM (`conda`, source): source
 - How you installed TVM-Unity (`pip`, source): source
 - Python version (e.g. 3.10):3.9.5
 - ROCMversion (if applicable): 6.0
 - TVM Unity Hash Tag (`python -c "import tvm; print('\n'.join(f'{k}: {v}' for k, v in tvm.support.libinfo().items()))"`, applicable if you compile models):
USE_NVTX: OFF
USE_GTEST: AUTO
SUMMARIZE: OFF
USE_IOS_RPC: OFF
USE_MSC: OFF
USE_ETHOSU: OFF
CUDA_VERSION: NOT-FOUND
USE_LIBBACKTRACE: AUTO
DLPACK_PATH: 3rdparty/dlpack/include
USE_TENSORRT_CODEGEN: OFF
USE_THRUST: OFF
USE_TARGET_ONNX: OFF
USE_AOT_EXECUTOR: ON
BUILD_DUMMY_LIBTVM: OFF
USE_CUDNN: OFF
USE_TENSORRT_RUNTIME: OFF
USE_ARM_COMPUTE_LIB_GRAPH_EXECUTOR: OFF
USE_CCACHE: AUTO
USE_ARM_COMPUTE_LIB: OFF
USE_CPP_RTVM: OFF
USE_OPENCL_GTEST: /path/to/opencl/gtest
USE_MKL: OFF
USE_PT_TVMDSOOP: OFF
MLIR_VERSION: NOT-FOUND
USE_CLML: OFF
USE_STACKVM_RUNTIME: OFF
USE_GRAPH_EXECUTOR_CUDA_GRAPH: OFF
ROCM_PATH: /opt/rocm
USE_DNNL: OFF
USE_VITIS_AI: OFF
USE_MLIR: OFF
USE_RCCL: OFF
USE_LLVM: llvm-config --ignore-libllvm --link-static
USE_VERILATOR: OFF
USE_TF_TVMDSOOP: OFF
USE_THREADS: ON
USE_MSVC_MT: OFF
BACKTRACE_ON_SEGFAULT: OFF
USE_GRAPH_EXECUTOR: ON
USE_NCCL: OFF
USE_ROCBLAS: OFF
GIT_COMMIT_HASH: f7fa60201602fee8eae4e1e318b995c8493cf02f
USE_VULKAN: OFF
USE_RUST_EXT: OFF
USE_CUTLASS: OFF
USE_CPP_RPC: OFF
USE_HEXAGON: OFF
USE_CUSTOM_LOGGING: OFF
USE_UMA: OFF
USE_FALLBACK_STL_MAP: OFF
USE_SORT: ON
USE_RTTI: ON
GIT_COMMIT_TIME: 2024-01-12 09:34:04 -0500
USE_HEXAGON_SDK: /path/to/sdk
USE_BLAS: none
USE_ETHOSN: OFF
USE_LIBTORCH: OFF
USE_RANDOM: ON
USE_CUDA: OFF
USE_COREML: OFF
USE_AMX: OFF
BUILD_STATIC_RUNTIME: OFF
USE_CMSISNN: OFF
USE_KHRONOS_SPIRV: OFF
USE_CLML_GRAPH_EXECUTOR: OFF
USE_TFLITE: OFF
USE_HEXAGON_GTEST: /path/to/hexagon/gtest
PICOJSON_PATH: 3rdparty/picojson
USE_OPENCL_ENABLE_HOST_PTR: OFF
INSTALL_DEV: OFF
USE_PROFILER: ON
USE_NNPACK: OFF
LLVM_VERSION: 17.0.0git
USE_OPENCL: OFF
COMPILER_RT_PATH: 3rdparty/compiler-rt
RANG_PATH: 3rdparty/rang/include
USE_SPIRV_KHR_INTEGER_DOT_PRODUCT: OFF
USE_OPENMP: none
USE_BNNS: OFF
USE_CUBLAS: OFF
USE_METAL: OFF
USE_MICRO_STANDALONE_RUNTIME: OFF
USE_HEXAGON_EXTERNAL_LIBS: OFF
USE_ALTERNATIVE_LINKER: AUTO
USE_BYODT_POSIT: OFF
USE_HEXAGON_RPC: OFF
USE_MICRO: OFF
DMLC_PATH: 3rdparty/dmlc-core/include
INDEX_DEFAULT_I64: ON
USE_RELAY_DEBUG: ON
USE_RPC: ON
USE_TENSORFLOW_PATH: none
TVM_CLML_VERSION:
USE_MIOPEN: ON
USE_ROCM: ON
USE_PAPI: OFF
USE_CURAND: OFF
TVM_CXX_COMPILER_PATH: /opt/rocm/llvm/bin/clang++
HIDE_PRIVATE_SYMBOLS: ON

**Comment by lhcalibur** [comment]
The LLVM IR:


 define dllexport amdgpu_kernel void @llama_rope_kernel(ptr addrspace(1) noalias %k, ptr addrspace(1) noalias %q, ptr addrspace(1) noalias %qkv, ptr addrspace(1) noalias %v, i32 %batch_size, i32 %seq_len, i32 %total_seq_len) #0 {
entry:
  %0 = call i32 @llvm.amdgcn.workgroup.id.x()
  %1 = call i32 @llvm.amdgcn.workitem.id.x()
  %2 = srem i32 %0, 10
  %3 = icmp slt i32 %2, 8
  br i1 %3, label %if_then, label %if_else

if_then:                                          ; preds = %entry
  %4 = mul nsw i32 %0, 1024
  %5 = add nsw i32 %4, %1
  %6 = mul nsw i32 %seq_len, 10240
  %rmod = srem i32 %5, %6
  %7 = mul nsw i32 %seq_len, 10240
  %8 = add nsw i32 %rmod, %7
  %9 = icmp sle i32 %rmod, 0
  %10 = mul nsw i32 %seq_len, 10240
  %11 = icmp slt i32 %10, 0
  %12 = and i1 %11, %9
  %13 = icmp sge i32 %rmod, 0
  %14 = mul nsw i32 %seq_len, 10240
  %15 = icmp sge i32 %14, 0
  %16 = and i1 %15, %13
  %17 = or i1 %16, %12
  %18 = select i1 %17, i32 %rmod, i32 %8
  %19 = srem i32 %18, 10240
  %20 = ashr i32 %19, 31
  %21 = mul nsw i32 %0, 1024
  %22 = add nsw i32 %21, %1
  %23 = mul nsw i32 %seq_len, 10240
  %rmod1 = srem i32 %22, %23
  %24 = mul nsw i32 %seq_len, 10240
  %25 = add nsw i32 %rmod1, %24
  %26 = icmp sle i32 %rmod1, 0
  %27 = mul nsw i32 %seq_len, 10240
  %28 = icmp slt i32 %27, 0
  %29 = and i1 %28, %26
  %30 = icmp sge i32 %rmod1, 0
  %31 = mul nsw i32 %seq_len, 10240
  %32 = icmp sge i32 %31, 0
  %33 = and i1 %32, %30
  %34 = or i1 %33, %29
  %35 = select i1 %34, i32 %rmod1, i32 %25
  %36 = sdiv i32 %35, 10240
  %37 = add nsw i32 %36, %20
  %38 = add nsw i32 %37, %total_seq_len
  %39 = sub nsw i32 %38, %seq_len
  %40 = sitofp i32 %39 to half
  %41 = fpext half %40 to float
  %42 = and i32 %1, 63
  %43 = mul nsw i32 %42, 2
  %44 = sitofp i32 %43 to float
  %45 = fmul float %44, 7.812500e-03
  %46 = call <4 x float> @__ocml_pow_f32(float 1.000000e+04, float %45)
  %47 = fdiv float %41, <4 x float> %46
  %48 = call <4 x float> @__ocml_sin_f32(float %47)
  %49 = fptrunc <4 x float> %48 to half
  %50 = and i32 %1, 127
  %51 = icmp slt i32 %50, 64
  br i1 %51, label %if_then2, label %if_else3

if_end:                                           ; preds = %if_end23, %if_end4
  ret void

**Comment by junrushao** [comment]
Should be fixed by: https://github.com/mlc-ai/relax/commit/9c8cf0861bd5431d91ddea42f91f7e68d33f67ca

**Comment by lhcalibur** [comment]
I have tested this fix, and it works! Thanks!
