### ISSUE TITLE
[Bug] load model failed when use mlc-chat-cli with rocm and prebuilt model lib

### ISSUE THREAD

**Issue by alexhegit** [mlc-ai/mlc-llm#1614]
## To Reproduce

1. Create conda env and install tvm unity of ROCm5.7 as https://llm.mlc.ai/docs/install/tvm.html#install-tvm-unity
    $conda activate your-environment
    $python3 -m pip install --pre -U -f https://mlc.ai/wheels mlc-ai-nightly-rocm57
1. Check TVM 
	$ python -c "import tvm; print('\n'.join(f'{k}: {v}' for k, v in tvm.support.libinfo().items()))" | grep ROC
![image](https://github.com/mlc-ai/mlc-llm/assets/31022192/a76b3170-86d0-458e-8316-0f520b80aa2b)

1. Download mlc-chat-Llama-2-7b-chat-hf-q4f16_1 model files from HuggingFace
1. Run inference with prebuilt model lib
  mlc_chat_cli --model mlc-chat-Llama-2-7b-chat-hf-q4f16_1/ --model-lib-path ~/mlc-ai/dist/prebuilt_libs/Llama-2-7b-chat-hf-q4f16_1-rocm.so  --device rocm:0

Failed with log

![image](https://github.com/mlc-ai/mlc-llm/assets/31022192/3282d0b2-f04d-4157-96bb-0101cb22e43a)

## Environment

 - Platform (ROCm):
 - Operating system (Ubuntu22.04.):
 - Device (AMD Radeon PRO W7900)
 - How you installed MLC-LLM (`conda):
 - How you installed TVM-Unity (`pip`):
 - Python version (3.11):
 - GPU driver version ():
 - CUDA/cuDNN version (ROCm5.7):
 - TVM Unity Hash Tag (`python -c "import tvm; print('\n'.join(f'{k}: {v}' for k, v in tvm.support.libinfo().items()))"`, applicable if you compile models):
USE_GTEST: AUTO
SUMMARIZE: OFF
USE_IOS_RPC: OFF
USE_ETHOSU: ON
CUDA_VERSION: NOT-FOUND
USE_LIBBACKTRACE: AUTO
DLPACK_PATH: 3rdparty/dlpack/include
USE_TENSORRT_CODEGEN: OFF
USE_THRUST: OFF
USE_TARGET_ONNX: OFF
USE_AOT_EXECUTOR: ON
BUILD_DUMMY_LIBTVM: OFF
USE_CUDNN: OFF
USE_TENSORRT_RUNTIME: OFF
USE_ARM_COMPUTE_LIB_GRAPH_EXECUTOR: OFF
USE_CCACHE: AUTO
USE_ARM_COMPUTE_LIB: /opt/arm/acl
USE_CPP_RTVM:
USE_OPENCL_GTEST: /path/to/opencl/gtest
USE_MKL: OFF
USE_PT_TVMDSOOP: OFF
MLIR_VERSION: NOT-FOUND
USE_CLML: OFF
USE_STACKVM_RUNTIME: OFF
USE_GRAPH_EXECUTOR_CUDA_GRAPH: OFF
ROCM_PATH: /opt/rocm
USE_DNNL: OFF
USE_VITIS_AI: OFF
USE_MLIR: OFF
USE_RCCL: OFF
USE_LLVM: llvm-config --ignore-libllvm --link-static
USE_VERILATOR: OFF
USE_TF_TVMDSOOP: OFF
USE_THREADS: ON
USE_MSVC_MT: OFF
BACKTRACE_ON_SEGFAULT: OFF
USE_GRAPH_EXECUTOR: ON
USE_NCCL: OFF
USE_ROCBLAS: OFF
GIT_COMMIT_HASH: 878a61105ea4c85f3547fe137a28d0a80b1f0e94
USE_VULKAN: OFF
USE_RUST_EXT: OFF
USE_CUTLASS: OFF
USE_CPP_RPC: OFF
USE_HEXAGON: OFF
USE_CUSTOM_LOGGING: OFF
USE_UMA: OFF
USE_FALLBACK_STL_MAP: OFF
USE_SORT: ON
USE_RTTI: ON
GIT_COMMIT_TIME: 2023-10-31 16:09:58 -0500
USE_HEXAGON_SDK: /path/to/sdk
USE_BLAS: none
USE_ETHOSN: /opt/arm/ethosn-driver
USE_LIBTORCH: OFF
USE_RANDOM: ON
USE_CUDA: OFF
USE_COREML: OFF
USE_AMX: OFF
BUILD_STATIC_RUNTIME: OFF
USE_CMSISNN: ON
USE_KHRONOS_SPIRV: OFF
USE_CLML_GRAPH_EXECUTOR: OFF
USE_TFLITE: OFF
USE_HEXAGON_GTEST: /path/to/hexagon/gtest
PICOJSON_PATH: 3rdparty/picojson
USE_OPENCL_ENABLE_HOST_PTR: OFF
INSTALL_DEV: OFF
USE_PROFILER: ON
USE_NNPACK: OFF
LLVM_VERSION: 10.0.1
USE_OPENCL: OFF
COMPILER_RT_PATH: 3rdparty/compiler-rt
RANG_PATH: 3rdparty/rang/include
USE_SPIRV_KHR_INTEGER_DOT_PRODUCT: OFF
USE_OPENMP: OFF
USE_BNNS: OFF
USE_CUBLAS: OFF
USE_METAL: OFF
USE_MICRO_STANDALONE_RUNTIME: ON
USE_HEXAGON_EXTERNAL_LIBS: OFF
USE_ALTERNATIVE_LINKER: AUTO
USE_BYODT_POSIT: OFF
USE_HEXAGON_RPC: OFF
USE_MICRO: ON
DMLC_PATH: 3rdparty/dmlc-core/include
INDEX_DEFAULT_I64: ON
USE_RELAY_DEBUG: OFF
USE_RPC: ON
USE_TENSORFLOW_PATH: none
TVM_CLML_VERSION:
USE_MIOPEN: OFF
USE_ROCM: OFF
USE_PAPI: OFF
USE_CURAND: OFF
TVM_CXX_COMPILER_PATH: /opt/rh/devtoolset-9/root/usr/bin/c++

 - Any other relevant information:

**Comment by shreygupta2809** [comment]
Referencing a similar issue:
https://github.com/mlc-ai/mlc-llm/issues/1216#issuecomment-1801087884

Copying from there:
This is a common issue that we probably forgot to set PATH in ROCm. To resolve this, you will have to add ROCm's LLVM to PATH, so that ROCm's lld exists:

`export PATH=/opt/rocm/llvm/bin:$PATH`

In Dockerfile it is reflected on [this line](https://github.com/mlc-ai/llm-perf-bench/blob/main/docker/Dockerfile.rocm57.mlc#L10C11-L10C48).

**Comment by tqchen** [comment]
Likely we should update rocm.py and enable lld search to include `/opt/rocm/llvm/bin` so we don't have to do this path setting.

cc @MasterJH5574 @shreygupta2809 @CharlieFRuan
