### ISSUE TITLE
'tvm/runtime/relax_vm/memory_manager.h' file not found

### ISSUE THREAD

**Issue by chensinit** [mlc-ai/mlc-llm#162]
Hello.
I try to build for android.
I pulled latest code.
But There is no 'tvm/runtime/relax_vm/memory_manager.h'.
What is problem?

./prepare_libs.sh 
...
[  7%] Building CXX object tokenizers/sentencepiece/src/CMakeFiles/sentencepiece-static.dir/__/third_party/protobuf-lite/arenastring.cc.o
/home/gihun/IdeaProjects/230515_mlc-llm/cpp/llm_chat.cc:12:10: fatal error: 'tvm/runtime/relax_vm/memory_manager.h' file not found

**Comment by chensinit** [comment]
My enviroument is bad. : (

**Comment by YouCii** [comment]
Hello, i meet the same question. Can you share your solution?

**Comment by YouCii** [comment]
> Hello, i meet the same question. Can you share your solution?

The error is because of sources dismiss, i solved it by clone again with this :
`git clone https://github.com/apache/tvm --branch unity --recursive`

The new folder contains `tvm/include/tvm/runtime/relax_vm/memory_manager.h`
