### ISSUE TITLE
[Bug] The API implementation TIRPagedKVCache mismatched with PagedAttentionKVCacheObj

### ISSUE THREAD

**Issue by lhcalibur** [mlc-ai/mlc-llm#1623]
## 🐛 Bug

The implementaion in mlc-llm:python/mlc_chat/nn/kv_cache.py:TIRPagedKVCache is mismatch with relax(tvm):src/runtime/relax_vm/paged_kv_cache.cc:PagedAttentionKVCacheObj

For example 
1. The 
https://github.com/mlc-ai/mlc-llm/blob/24490ba11cccb0c450f3d73b97d6a49dffb21edd/python/mlc_chat/nn/kv_cache.py#L171C10-L171C10 
is mismatched with 
https://github.com/mlc-ai/relax/blob/a7818f0942a88a1e9c2c29dc0249d6ea7fd2a1e3/src/runtime/relax_vm/paged_kv_cache.cc#L1088
2. The 
https://github.com/mlc-ai/mlc-llm/blob/24490ba11cccb0c450f3d73b97d6a49dffb21edd/python/mlc_chat/nn/kv_cache.py#L401
is mismatched with 
https://github.com/mlc-ai/relax/blob/a7818f0942a88a1e9c2c29dc0249d6ea7fd2a1e3/src/runtime/relax_vm/paged_kv_cache.cc#L907 

## To Reproduce

mlc-llm git hash: 24490ba11cccb0c450f3d73b97d6a49dffb21edd
relax(tvm) git hash: a7818f0942a88a1e9c2c29dc0249d6ea7fd2a1e3

```
from mlc_chat.serve import Engine
from mlc_chat.serve.config import KVCacheConfig, GenerationConfig
from mlc_chat.serve.engine import ModelInfo


engine = Engine(
    ModelInfo(
        model="dist/Llama-2-7b-chat-hf-q4f16_1-MLC",
        model_lib_path="dist/libs/Llama-2-7b-chat-hf-q4f16_1-rocm.so",
        device="rocm:0"
    ),
    KVCacheConfig())

engine.generate(
    prompts=["How many points did you list out?"],
    generation_config=GenerationConfig(temperature=0.0, top_p=0.6)
)
```

**Comment by MasterJH5574** [comment]
Hi @lhcalibur, apologize for this late reply. I think the latest codebase may have got rid of that issue. So would appreciate it if you would like to try out again. I am going to close this issue given it is quite outdated, but you are welcome to open new issues at any time for any problems you encounter.
