### ISSUE TITLE
[Doc] There are some commands inconsistent with the documentation.

### ISSUE THREAD

**Issue by hmzdtz** [mlc-ai/mlc-llm#1624]
### About `mlc_chat_cli`

The usage of `mlc_chat_cli` in the document is incorrect.  [https://llm.mlc.ai/docs/](https://llm.mlc.ai/docs/)

I got command `mlc_chat_cli` by `conda install -c mlc-ai mlc-chat-cli-nightly`, and then run the following command:

```bash
mlc_chat_cli --model dist/Llama-2-7b-chat-hf-q4f16_1-MLC \
             --model-lib-path dist/prebuilt_libs/Llama-2-7b-chat-hf/Llama-2-7b-chat-hf-q4f16_1-cuda.so
```

But the command `mlc_chat_cli` has no argument named `--model-lib-path`, and the output of `mlc_chat_cli --help` is: 

```
Usage: mlc_chat [--help] [--version] [--local-id VAR] [--model VAR] [--quantization VAR] [--device-name VAR] [--device_id VAR] [--artifact-path VAR] [--evaluate]

Optional arguments:
  -h, --help            shows help message and exits
  -v, --version         prints version information and exits
  --local-id            [default: ""]
  --model               [default: "vicuna-v1-7b"]
  --quantization        [default: "auto"]
  --device-name         [default: "auto"]
  --device_id           [default: 0]
  --artifact-path       [default: "dist"]
  --evaluate
```

### About `mlc_chat`

I can't find the `mlc_chat` command, though I've been looking through the document. How can I get it?

**Comment by DavidGOrtega** [comment]
@hmzdtz you can install it via nightly builds or build it from source. [Here](https://llm.mlc.ai/docs/install/mlc_llm.html#mlcchat-build-from-source) you can find the docs.

**Comment by hmzdtz** [comment]
Thank you for your reply. I have been busy with other projects recently, but I will try compiling from source code when I am free later.

**Comment by DavidGOrtega** [comment]
I would recommend you to just [install the nightly](https://llm.mlc.ai/docs/install/mlc_llm.html#option-1-prebuilt-package) builds to try it out.

**Comment by hmzdtz** [comment]
I have built from source and get the right version of the above commands successfully.

**Comment by hmzdtz** [comment]
I have built from source and get the right version of the above commands successfully.
