### ISSUE TITLE
[Bug] `mlc_chat` several dependancies are not installed

### ISSUE THREAD

**Issue by DavidGOrtega** [mlc-ai/mlc-llm#1626]
## 🐛 Bug

mlc_chat requires several packages which are not installed:
 - [ ] requests
 - [ ] tqdm
 - [ ] safetensors
 - [ ] torch

## To Reproduce

1. `conda create --name mlc python=3.9`
2. `python3 -m pip install --pre -U -f https://mlc.ai/wheels mlc-chat-nightly mlc-ai-nightly`
3. `mlc_chat --help`

## Expected behavior

Should install all the required dependencies

## Environment

 - Operating system (e.g. Ubuntu/Windows/MacOS/...): MACOS ventura 13.6.3
 - Python version (e.g. 3.10): 3.9

**Comment by shreygupta2809** [comment]
Can also be reproduced by following [Building from Source](https://llm.mlc.ai/docs/install/mlc_llm.html#option-2-build-from-source)
