### ISSUE TITLE
[Question] Error "...expect a Tuple with 327 elements,  but get a Tuple with 0 elements"

### ISSUE THREAD

**Issue by springeryuan** [mlc-ai/mlc-llm#1645]
## ❓ General Questions
When I run command line as follows:
C:\d\myprograms\miniconda3> **mlc_chat_cli.exe --model .\dist\Llama-2-7b-chat-hf-q4f16_1-MLC --model-lib-path .\dist\prebuilt_libs\Llama-2-7b-chat-hf-q4f16_1-vulkan.dll**
Use MLC config: "C:\\d\\myprograms\\miniconda3\\dist\\Llama-2-7b-chat-hf-q4f16_1-MLC\\mlc-chat-config.json"
Use model weights: "C:\\d\\myprograms\\miniconda3\\dist\\Llama-2-7b-chat-hf-q4f16_1-MLC\\ndarray-cache.json"
Use model library: ".\\dist\\prebuilt_libs\\Llama-2-7b-chat-hf-q4f16_1-vulkan.dll"
You can use the following special commands:
  /help               print the special commands
  /exit               quit the cli
  /stats              print out the latest stats (token/sec)
  /reset              restart a fresh chat
  /reload [model]  reload model `model` from disk, or reload the current model if `model` is not specified

Loading model...
Loading finished
Running system prompts...

...

t16"), R.Tensor((4096,), dtype="float16"), R.Tensor((4096,), dtype="float16"), R.Tensor((12288, 512), dtype="uint32"), R.Tensor((12288, 128), dtype="float16"), R.Tensor((4096, 512), dtype="uint32"), R.Tensor((4096, 128), dtype="float16"), R.Tensor((22016, 512), dtype="uint32"), R.Tensor((22016, 128), dtype="float16"), R.Tensor((4096, 1376), dtype="uint32"), R.Tensor((4096, 344), dtype="float16"), R.Tensor((4096,), dtype="float16"), R.Tensor((4096,), dtype="float16"), R.Tensor((4096,), dtype="float16"), R.Tensor((v, 512), dtype="uint32"), R.Tensor((v, 128), dtype="float16"), R.Tensor((cache_len, 128), dtype="float16"), R.Tensor((cache_len, 128), dtype="float16")))  **expect a Tuple with 327 elements,  but get a Tuple with 0 elements.**
Stack trace not available when DMLC_LOG_STACK_TRACE is disabled at compile time.

I 'm with a gaming laptop with nvidia rtx 3060 , didn't install additional gpu drivers but leave it with the default drivers coming with the laptop , it seems both cuda and vulkan drivers are in place when i check driver details from device manager.  
This is my first time trying mlc-llm, so only with prebuilt weights and libs, not sure if i missed any steps ? Any inputs are welcome!

**Comment by MasterJH5574** [comment]
Hey @springeryuan, we have deprecated the conda-based CLI a while ago. You are welcome to follow our documentation at https://llm.mlc.ai/docs/index.html to try out the latest instructions. Feel free to open new issues if you have any other problems.
