### ISSUE TITLE
[Question] 交叉编译端侧模型部署过程中，遇到静态库libtokenizers_c.a 和目标系统aarch64不匹配问题。

### ISSUE THREAD

**Issue by mayway530** [mlc-ai/mlc-llm#1649]
## ❓ General Questions

执行命令过程如下：
1. rm -rf build && mkdir -p build && cd build
2. python3 ../cmake/gen_cmake_config.py
依次勾选生成config.cmake
3. 使用交叉编译工具链：
cmake .. \
    -DCMAKE_SYSTEM_NAME=Linux \
    -DCMAKE_SYSTEM_VERSION=1 \
    -DCMAKE_C_COMPILER=/usr/bin/aarch64-linux-gnu-gcc \
    -DCMAKE_CXX_COMPILER=/usr/bin/aarch64-linux-gnu-g++ \
    -DCMAKE_FIND_ROOT_PATH=/usr/aarch64-linux-gnu \
    -DCMAKE_FIND_ROOT_PATH_MODE_PROGRAM=NEVER \
    -DCMAKE_FIND_ROOT_PATH_MODE_LIBRARY=ONLY \
    -DMACHINE_NAME=aarch64-linux-gnu
    
 4. make -j8
 
![git_issu1](https://github.com/mlc-ai/mlc-llm/assets/14232046/d0f6c462-5315-438f-8eb8-f1d06a7a9358)

 
![git_issu2](https://github.com/mlc-ai/mlc-llm/assets/14232046/c4bcc654-8d3c-4f4a-8afd-1f2675805bc4)

详细报错：
/usr/lib/gcc-cross/aarch64-linux-gnu/9/../../../../aarch64-linux-gnu/bin/ld: tokenizers/release/libtokenizers_c.a(tokenizers_c-958c783c9df9a543.tokenizers_c.dd30e4df46cec63e-cgu.04.rcgu.o): Relocations in generic ELF (EM: 62)
/usr/lib/gcc-cross/aarch64-linux-gnu/9/../../../../aarch64-linux-gnu/bin/ld: tokenizers/release/libtokenizers_c.a(tokenizers_c-958c783c9df9a543.tokenizers_c.dd30e4df46cec63e-cgu.04.rcgu.o): Relocations in generic ELF (EM: 62)
/usr/lib/gcc-cross/aarch64-linux-gnu/9/../../../../aarch64-linux-gnu/bin/ld: tokenizers/release/libtokenizers_c.a(tokenizers_c-958c783c9df9a543.tokenizers_c.dd30e4df46cec63e-cgu.04.rcgu.o): Relocations in generic ELF (EM: 62)
/usr/lib/gcc-cross/aarch64-linux-gnu/9/../../../../aarch64-linux-gnu/bin/ld: tokenizers/release/libtokenizers_c.a(tokenizers_c-958c783c9df9a543.tokenizers_c.dd30e4df46cec63e-cgu.04.rcgu.o): Relocations in generic ELF (EM: 62)
/usr/lib/gcc-cross/aarch64-linux-gnu/9/../../../../aarch64-linux-gnu/bin/ld: tokenizers/release/libtokenizers_c.a(tokenizers_c-958c783c9df9a543.tokenizers_c.dd30e4df46cec63e-cgu.04.rcgu.o): Relocations in generic ELF (EM: 62)
/usr/lib/gcc-cross/aarch64-linux-gnu/9/../../../../aarch64-linux-gnu/bin/ld: tokenizers/release/libtokenizers_c.a(tokenizers_c-958c783c9df9a543.tokenizers_c.dd30e4df46cec63e-cgu.04.rcgu.o): Relocations in generic ELF (EM: 62)
/usr/lib/gcc-cross/aarch64-linux-gnu/9/../../../../aarch64-linux-gnu/bin/ld: tokenizers/release/libtokenizers_c.a(tokenizers_c-958c783c9df9a543.tokenizers_c.dd30e4df46cec63e-cgu.04.rcgu.o): Relocations in generic ELF (EM: 62)
/usr/lib/gcc-cross/aarch64-linux-gnu/9/../../../../aarch64-linux-gnu/bin/ld: tokenizers/release/libtokenizers_c.a(tokenizers_c-958c783c9df9a543.tokenizers_c.dd30e4df46cec63e-cgu.04.rcgu.o): Relocations in generic ELF (EM: 62)
/usr/lib/gcc-cross/aarch64-linux-gnu/9/../../../../aarch64-linux-gnu/bin/ld: tokenizers/release/libtokenizers_c.a(tokenizers_c-958c783c9df9a543.tokenizers_c.dd30e4df46cec63e-cgu.04.rcgu.o): Relocations in generic ELF (EM: 62)
/usr/lib/gcc-cross/aarch64-linux-gnu/9/../../../../aarch64-linux-gnu/bin/ld: tokenizers/release/libtokenizers_c.a(tokenizers_c-958c783c9df9a543.tokenizers_c.dd30e4df46cec63e-cgu.04.rcgu.o): Relocations in generic ELF (EM: 62)
/usr/lib/gcc-cross/aarch64-linux-gnu/9/../../../../aarch64-linux-gnu/bin/ld: tokenizers/release/libtokenizers_c.a(tokenizers_c-958c783c9df9a543.tokenizers_c.dd30e4df46cec63e-cgu.04.rcgu.o): Relocations in generic ELF (EM: 62)
/usr/lib/gcc-cross/aarch64-linux-gnu/9/../../../../aarch64-linux-gnu/bin/ld: tokenizers/release/libtokenizers_c.a(tokenizers_c-958c783c9df9a543.tokenizers_c.dd30e4df46cec63e-cgu.04.rcgu.o): Relocations in generic ELF (EM: 62)
/usr/lib/gcc-cross/aarch64-linux-gnu/9/../../../../aarch64-linux-gnu/bin/ld: tokenizers/release/libtokenizers_c.a(tokenizers_c-958c783c9df9a543.tokenizers_c.dd30e4df46cec63e-cgu.04.rcgu.o): Relocations in generic ELF (EM: 62)
/usr/lib/gcc-cross/aarch64-linux-gnu/9/../../../../aarch64-linux-gnu/bin/ld: tokenizers/release/libtokenizers_c.a(tokenizers_c-958c783c9df9a543.tokenizers_c.dd30e4df46cec63e-cgu.04.rcgu.o): Relocations in generic ELF (EM: 62)
/usr/lib/gcc-cross/aarch64-linux-gnu/9/../../../../aarch64-linux-gnu/bin/ld: tokenizers/release/libtokenizers_c.a: error adding symbols: file in wrong format
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/mlc_llm_module.dir/build.make:143: libmlc_llm_module.so] Error 1
make[1]: *** [CMakeFiles/Makefile2:362: CMakeFiles/mlc_llm_module.dir/all] Error 2
[100%] Built target mlc_llm_static
make: *** [Makefile:156: all] Error 2

目前项目推进卡点在最后一步整合依赖资源，能力有限，盼各位老师能帮忙指导下解决思路？

**Comment by na20215** [comment]
你这个不匹配是你cmake参数缺了一些，你子项目的cmake参数没有设置（你这儿是tokenizers），导致你的tokenizers静态库还是为本机的架构编译的，，在链接步骤就会出现将为本机架构编译的二进制文件连接到目标架构上出现不匹配的问题。建议你好好看看3rdparty里的tokenizers的cmakelist文件，看看tokenizers的cmake有哪些参数需要设置。 因为他这个项目套一个子项目的，这种问题就很麻烦， 可能两个项目的两个不同的参数名字其实要的是一个东西， 但是不都设置好就会出现这样的问题

**Comment by na20215** [comment]
> ## ❓ General Questions
> 执行命令过程如下：
> 
> 1. rm -rf build && mkdir -p build && cd build
> 2. python3 ../cmake/gen_cmake_config.py
>    依次勾选生成config.cmake
> 3. 使用交叉编译工具链：
>    cmake .. 
>    -DCMAKE_SYSTEM_NAME=Linux 
>    -DCMAKE_SYSTEM_VERSION=1 
>    -DCMAKE_C_COMPILER=/usr/bin/aarch64-linux-gnu-gcc 
>    -DCMAKE_CXX_COMPILER=/usr/bin/aarch64-linux-gnu-g++ 
>    -DCMAKE_FIND_ROOT_PATH=/usr/aarch64-linux-gnu 
>    -DCMAKE_FIND_ROOT_PATH_MODE_PROGRAM=NEVER 
>    -DCMAKE_FIND_ROOT_PATH_MODE_LIBRARY=ONLY 
>    -DMACHINE_NAME=aarch64-linux-gnu
> 4. make -j8
> 
> ![git_issu1](https://private-user-images.githubusercontent.com/14232046/298849050-d0f6c462-5315-438f-8eb8-f1d06a7a9358.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcwMzM0NTMsIm5iZiI6MTcwNzAzMzE1MywicGF0aCI6Ii8xNDIzMjA0Ni8yOTg4NDkwNTAtZDBmNmM0NjItNTMxNS00MzhmLThlYjgtZjFkMDZhN2E5MzU4LmpwZWc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwNFQwNzUyMzNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lNjgwMTkyYjQ0OTg1MmZjZWIyOTdmYjQwNmQxMmMwMWEzYjdlNGRlY2Y0M2M1NGQzNGMyM2Q1OTkwYmM5ZWRkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.XgKxMQPLfRBYxjqhOz-21-yBxfwzdp_4MDja4Z9cXYc)
> 
> ![git_issu2](https://private-user-images.githubusercontent.com/14232046/298849079-c4bcc654-8d3c-4f4a-8afd-1f2675805bc4.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcwMzM0NTMsIm5iZiI6MTcwNzAzMzE1MywicGF0aCI6Ii8xNDIzMjA0Ni8yOTg4NDkwNzktYzRiY2M2NTQtOGQzYy00ZjRhLThhZmQtMWYyNjc1ODA1YmM0LmpwZWc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwNFQwNzUyMzNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jNjRiYzljMzk4MWQzZjFiMmY1YTJiOGViZmE3YjE3ZDc3ZDZlNjUyMDZmODAwNmJlMmJkNjdiYWNiMjM5OWU5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.iGA7U04DlQtVTqJysiMfU_YTNQLepZh__vfEHpLekDc)
> 
> 详细报错： /usr/lib/gcc-cross/aarch64-linux-gnu/9/../../../../aarch64-linux-gnu/bin/ld: tokenizers/release/libtokenizers_c.a(tokenizers_c-958c783c9df9a543.tokenizers_c.dd30e4df46cec63e-cgu.04.rcgu.o): Relocations in generic ELF (EM: 62) /usr/lib/gcc-cross/aarch64-linux-gnu/9/../../../../aarch64-linux-gnu/bin/ld: tokenizers/release/libtokenizers_c.a(tokenizers_c-958c783c9df9a543.tokenizers_c.dd30e4df46cec63e-cgu.04.rcgu.o): Relocations in generic ELF (EM: 62) /usr/lib/gcc-cross/aarch64-linux-gnu/9/../../../../aarch64-linux-gnu/bin/ld: tokenizers/release/libtokenizers_c.a(tokenizers_c-958c783c9df9a543.tokenizers_c.dd30e4df46cec63e-cgu.04.rcgu.o): Relocations in generic ELF (EM: 62) /usr/lib/gcc-cross/aarch64-linux-gnu/9/../../../../aarch64-linux-gnu/bin/ld: tokenizers/release/libtokenizers_c.a(tokenizers_c-958c783c9df9a543.tokenizers_c.dd30e4df46cec63e-cgu.04.rcgu.o): Relocations in generic ELF (EM: 62) /usr/lib/gcc-cross/aarch64-linux-gnu/9/../../../../aarch64-linux-gnu/bin/ld: tokenizers/release/libtokenizers_c.a(tokenizers_c-958c783c9df9a543.tokenizers_c.dd30e4df46cec63e-cgu.04.rcgu.o): Relocations in generic ELF (EM: 62) /usr/lib/gcc-cross/aarch64-linux-gnu/9/../../../../aarch64-linux-gnu/bin/ld: tokenizers/release/libtokenizers_c.a(tokenizers_c-958c783c9df9a543.tokenizers_c.dd30e4df46cec63e-cgu.04.rcgu.o): Relocations in generic ELF (EM: 62) /usr/lib/gcc-cross/aarch64-linux-gnu/9/../../../../aarch64-linux-gnu/bin/ld: tokenizers/release/libtokenizers_c.a(tokenizers_c-958c783c9df9a543.tokenizers_c.dd30e4df46cec63e-cgu.04.rcgu.o): Relocations in generic ELF (EM: 62) /usr/lib/gcc-cross/aarch64-linux-gnu/9/../../../../aarch64-linux-gnu/bin/ld: tokenizers/release/libtokenizers_c.a(tokenizers_c-958c783c9df9a543.tokenizers_c.dd30e4df46cec63e-cgu.04.rcgu.o): Relocations in generic ELF (EM: 62) /usr/lib/gcc-cross/aarch64-linux-gnu/9/../../../../aarch64-linux-gnu/bin/ld: tokenizers/release/libtokenizers_c.a(tokenizers_c-958c783c9df9a543.tokenizers_c.dd30e4df46cec63e-cgu.04.rcgu.o): Relocations in generic ELF (EM: 62) /usr/lib/gcc-cross/aarch64-linux-gnu/9/../../../../aarch64-linux-gnu/bin/ld: tokenizers/release/libtokenizers_c.a(tokenizers_c-958c783c9df9a543.tokenizers_c.dd30e4df46cec63e-cgu.04.rcgu.o): Relocations in generic ELF (EM: 62) /usr/lib/gcc-cross/aarch64-linux-gnu/9/../../../../aarch64-linux-gnu/bin/ld: tokenizers/release/libtokenizers_c.a(tokenizers_c-958c783c9df9a543.tokenizers_c.dd30e4df46cec63e-cgu.04.rcgu.o): Relocations in generic ELF (EM: 62) /usr/lib/gcc-cross/aarch64-linux-gnu/9/../../../../aarch64-linux-gnu/bin/ld: tokenizers/release/libtokenizers_c.a(tokenizers_c-958c783c9df9a543.tokenizers_c.dd30e4df46cec63e-cgu.04.rcgu.o): Relocations in generic ELF (EM: 62) /usr/lib/gcc-cross/aarch64-linux-gnu/9/../../../../aarch64-linux-gnu/bin/ld: tokenizers/release/libtokenizers_c.a(tokenizers_c-958c783c9df9a543.tokenizers_c.dd30e4df46cec63e-cgu.04.rcgu.o): Relocations in generic ELF (EM: 62) /usr/lib/gcc-cross/aarch64-linux-gnu/9/../../../../aarch64-linux-gnu/bin/ld: tokenizers/release/libtokenizers_c.a(tokenizers_c-958c783c9df9a543.tokenizers_c.dd30e4df46cec63e-cgu.04.rcgu.o): Relocations in generic ELF (EM: 62) /usr/lib/gcc-cross/aarch64-linux-gnu/9/../../../../aarch64-linux-gnu/bin/ld: tokenizers/release/libtokenizers_c.a: error adding symbols: file in wrong format collect2: error: ld returned 1 exit status make[2]: *** [CMakeFiles/mlc_llm_module.dir/build.make:143: libmlc_llm_module.so] Error 1 make[1]: *** [CMakeFiles/Makefile2:362: CMakeFiles/mlc_llm_module.dir/all] Error 2 [100%] Built target mlc_llm_static make: *** [Makefile:156: all] Error 2
> 
> 目前项目推进卡点在最后一步整合依赖资源，能力有限，盼各位老师能帮忙指导下解决思路？

你这个不匹配是你cmake参数缺了一些，你子项目的cmake参数没有设置（你这儿是tokenizers），导致你的tokenizers静态库还是为本机的架构编译的，，在链接步骤就会出现将为本机架构编译的二进制文件连接到目标架构上出现不匹配的问题。建议你好好看看3rdparty里的tokenizers的cmakelist文件，看看tokenizers的cmake有哪些参数需要设置。 因为他这个项目套一个子项目的，这种问题就很麻烦， 可能两个项目的两个不同的参数名字其实要的是一个东西， 但是不都设置好就会出现这样的问题

**Comment by ningpengtao-coder** [comment]
严格照着文档执行，不要瞎改参数就可以通过。

**Comment by MasterJH5574** [comment]
Gonna close this issue due to inactivity. You're welcome to reopen it or open a new one if there is any further question :-)
