### ISSUE TITLE
[Question] Issues with model deployment after pruning

### ISSUE THREAD

**Issue by lss0510** [mlc-ai/mlc-llm#1654]
## ❓ General Questions

Hello, I am currently trying to deploy the pruned model. I built the pruned model based on the pruned parameters and compiled the model successfully, but when I ran the model, the model gave irrelevant answers to my questions. In my pruned model, the parameters of the linear layer in multiple attentions are no longer consistent. Does the optimization during compilation require the parameters of multiple attentions to be consistent?

![image](https://github.com/mlc-ai/mlc-llm/assets/67734602/74273481-8fca-424c-9a87-cc6c678aa435)

**Comment by BenchuYee** [comment]
hey Iss0510, I've encountered some issues with deploying the pruned model, the pruned model has different kqv heads in different layers and the official kvcache can't work for it, could you please share how you deploy the pruned model？thanks very much

**Comment by lss0510** [comment]
I'm sorry, but my experience shouldn't help you. I only modified the parameters of the different layers of the model at the beginning of the deployment to ensure that the parameters read into the model were correct, but the pruning model I deployed did not answer the question as well as the normal model. At first I thought the problem was that the official kv cache could not handle the different kv headers of each layer after pruning, but I tried to read the official source code and found that their code can handle the different number of kqv headers (of course, as long as the number of KQV headers in the single layer is the same). It is also possible that the test I did did not take into account some cases, you can also try to modify the official kv cache, if there is a good result, please share with me, thank you.

**Comment by BenchuYee** [comment]
@lss0510 ，hi，I just deploy my pruned model in the android app and it seems work well, I use the nn.KVCache instead of pagedkvcache because nn.KVCache defined in the layer and I can adjust the argument in config to control nn.KVCache's size.
I want to know where the code show the pagedkvcache can manage different size kvcache in different layers, I used to see the code in paged_kv_cache.cc and I find it seems to give  different layers with the same size of NDArray(about line 784-787)(maybe I misunderstand the code，I am not familar with c++ project which is not my code in common use).thanks very much

**Comment by lss0510** [comment]
@BenchuYee I deployed it using nn.KVCache as well, but the model I deployed lost its logic in answering questions. At that time, I suspected that there was a problem in the calculation of kv cache in the attention module, so I debug the part responsible for kv calculation in tvm, and the result shows that there is no problem. As for the PagedKVCache you mentioned, I haven't used it. I'm sorry that I can't help you. I was surprised that the pruning model you deployed worked well. Could you describe your work in more detail? I think it will help me to some extent, thank you.

**Comment by BenchuYee** [comment]
I adjust my code when create the layers list, I make more than one config(use copy.deepcopy to copy the original config and change the argument), and for different layer I use different config to create them(give different config as the argument), I think maybe you can also consider your prune method, maybe it have some problems.

**Comment by tqchen** [comment]
pruned models may have degenerated perf, closing for now, feel free to open new issues
