### ISSUE TITLE
[Feature Request] How to change "sliding_window_size" in the Android APK ?

### ISSUE THREAD

**Issue by taeyeonlee** [mlc-ai/mlc-llm#1663]
## 🚀 Feature

I want to change the value of "sliding_window_size" on the Android APK.

I downloaded the models "Mistral-7B-Instruct-v0.2" and "RedPajama-INCITE-Chat-3B-v1" and "phi-2" from the huggingface.
and successfully onverted weights and created mlc-chat-config.json and compiled in the PC (ubuntu).
and I built tne Android APK, according to the guide [https://llm.mlc.ai/docs/deploy/android.html].
It's working on the Android Mobile well.
The two models "RedPajama-INCITE-Chat-3B-v1" and "phi-2" are working well on the Android Mobile.
But, the model "Mistral-7B-Instruct-v0.2" is not working on the Android Mobile. To run the model "Mistral-7B-Instruct-v0.2", it needs 11GB RAM.
so i want to change the value of "sliding_window_size" on the Android APK, to reduce the memory usage.
Could you please share how to change the value of "sliding_window_size" on the Android APK ?

![Screenshot from 2024-01-25 23-19-03](https://github.com/mlc-ai/mlc-llm/assets/86475892/a6cfa8f3-742f-474e-871a-0048b05787c1)

## Motivation

[ I checked it in the PC (Ubuntu),
[2024-01-25 23:10:49] INFO model_metadata.py:55: Total memory usage: 11581.26 MB (Parameters: 3885.13 MB. KVCache: 512.00 MB. Temporary buffer: 7184.13 MB)
when changing the value of the sliding_window_size as 256, and prefill_chunk_size as 256, it needs  4G RAM.
        chat_config=ChatConfig(sliding_window_size=256, prefill_chunk_size=256),
[2024-01-25 23:13:27] INFO model_metadata.py:55: Total memory usage: 3996.26 MB (Parameters: 3885.13 MB. KVCache: 32.00 MB. Temporary buffer: 79.13 MB)

/mlc-llm/android/library/src/main/assets/app-config.json
{
  "model_libs": [
    "mistral_q4f16_1",
    "gpt_neox_q4f16_1",
    "phi_q4f16_1"
  ],
  "model_list": [
    {
      "model_url": "https://huggingface.co/mlc-ai/Mistral-7B-Instruct-v0.2-q4f16_1-MLC/",
      "local_id": "Mistral-7B-Instruct-v0.2-q4f16_1",
      "model_lib_path": "libs/Mistral-7B-Instruct-v0.2-q4f16_1-android.tar",
      "model_lib": "mistral_q4f16_1"
    },
    {
      "model_url": "https://huggingface.co/mlc-ai/RedPajama-INCITE-Chat-3B-v1-q4f16_1-MLC/",
      "local_id": "RedPajama-INCITE-Chat-3B-v1-q4f16_1",
      "model_lib_path": "libs/RedPajama-INCITE-Chat-3B-v1-q4f16_1-android.tar",
      "model_lib": "gpt_neox_q4f16_1"
    },
    {
      "model_url": "https://huggingface.co/mlc-ai/phi-2-q4f16_1-MLC/",
      "local_id": "phi-2-q4f16_1",
      "model_lib_path": "libs/phi-2-q4f16_1-android.tar",
      "model_lib": "phi_q4f16_1"
    }
  ]
}

**Comment by Kartik14** [comment]
@taeyeonlee You can specify the `sliding_window_size` in the `mlc-chat-config.json` file. You can use the following command to create the `mlc-chat-config.json` for android:
```
mlc_chat gen_config ./dist/models/Mistral-7B-Instruct-v0.2/ --quantization q4f16_1 \
    --conv-template mistral_default --sliding-window-size 1024 --prefill-chunk-size 128 -o dist/Mistral-7B-Instruct-v0.2-q4f16_1-MLC/
```
Then you can compile the model library using this config file which you would need to compile for android

**Comment by taeyeonlee** [comment]
@Kartik14 
Thanks for the info. I'll try.

**Comment by taeyeonlee** [comment]
@Kartik14 
It's working well. 
The model "Mistral-7B-Instruct-v0.2" is working well on the Android Mobile,  with your change.
Thanks a lot. Have a good day.!

**Comment by tqchen** [comment]
@Kartik14 maybe it is worthwhile to update docs given this is a common need(to control memory usage for android)

**Comment by Kartik14** [comment]
Yes, will do that
