### ISSUE TITLE
How to make sure the (final TIR Module or .so) works as expected ? 

### ISSUE THREAD

**Issue by musram** [mlc-ai/mlc-llm#1668]
## ❓ General Questions

[debug-final.zip](https://github.com/mlc-ai/mlc-llm/files/14056037/debug-final.zip)
If we take the example of gpt2 the debug-final is attached.

To invoke the prefill function we have to pass packed_effects and packed_params.
packed_params can be got from the hugging face: map torch -> tvm.nd.NDArray
packed_effects are  like 
transformer_h_0_attn_k_cache1: R.Object = packed_effects[0]
        transformer_h_0_attn_v_cache1: R.Object = packed_effects[1]
        transformer_h_1_attn_k_cache1: R.Object = packed_effects[2]
        transformer_h_1_attn_v_cache1: R.Object = packed_effects[3]
        transformer_h_2_attn_k_cache1: R.Object = packed_effects[4]
        transformer_h_2_attn_v_cache1: R.Object = packed_effects[5]
        transformer_h_3_attn_k_cache1: R.Object = packed_effects[6]
        transformer_h_3_attn_v_cache1: R.Object = packed_effects[7]
        transformer_h_4_attn_k_cache1: R.Object = packed_effects[8]
        transformer_h_4_attn_v_cache1: R.Object = packed_effects[9]
        transformer_h_5_attn_k_cache1: R.Object = packed_effects[10]
        transformer_h_5_attn_v_cache1: R.Object = packed_effects[11]
        transformer_h_6_attn_k_cache1: R.Object = packed_effects[12]
        transformer_h_6_attn_v_cache1: R.Object = packed_effects[13]
        transformer_h_7_attn_k_cache1: R.Object = packed_effects[14]
        transformer_h_7_attn_v_cache1: R.Object = packed_effects[15]
        transformer_h_8_attn_k_cache1: R.Object = packed_effects[16]
        transformer_h_8_attn_v_cache1: R.Object = packed_effects[17]
        transformer_h_9_attn_k_cache1: R.Object = packed_effects[18]
        transformer_h_9_attn_v_cache1: R.Object = packed_effects[19]
        transformer_h_10_attn_k_cache1: R.Object = packed_effects[20]
        transformer_h_10_attn_v_cache1: R.Object = packed_effects[21]
        transformer_h_11_attn_k_cache1: R.Object = packed_effects[22]
        transformer_h_11_attn_v_cache1: R.Object = packed_effects[23]
what should be the in the packed_effects tuple? or what should be the eg transformer_h_1_attn_v_cache1?

ex = relax.build(Module, target="llvm")
vm = relax.VirtualMachine(ex, tvm.vulkan())

nd_res = vm["prefill"](data_nd,, packed_effects, packed_params)

is this the correct method to cross check the tir module?

**Comment by rickzx** [comment]
Hi @musram, the packed_effects are non-user-facing parameters that are used to represent operations with side effects. For example, kv_cache, I/O, etc. In your example, the packed effects are the [KV cache](https://github.com/mlc-ai/relax/blob/05dc738fb687154f0927868062858471879ea18b/python/tvm/relax/frontend/nn/modules.py#L480).

You will also notice an `_initialize_effect` in your `debug-final.py` that creates all the effects for you.
```
def _initialize_effect() -> R.Tuple(R.Object, R.Object, R.Object, R.Object, R.Object, R.Object, R.Object, R.Object, R.Object, R.Object, R.Object, R.Object, R.Object, R.Object, R.Object, R.Object, R.Object, R.Object, R.Object, R.Object, R.Object, R.Object, R.Object, R.Object):
        R.func_attr({"relax.force_pure": 1, "tir_var_upper_bound": {"seq_len": 1024, "total_seq_len": 1024}})
        shape_heap: R.Object = R.null_value()
        transformer_h_0_attn_k_cache: R.Object = R.call_packed("vm.builtin.attention_kv_cache_create", metadata["relax.expr.Constant"][0], R.shape([1024, 12, 64]), R.prim_value(0), sinfo_args=(R.Object,))
        transformer_h_0_attn_v_cache: R.Object = R.call_packed("vm.builtin.attention_kv_cache_create", metadata["relax.expr.Constant"][1], R.shape([1024, 12, 64]), R.prim_value(0), sinfo_args=(R.Object,))
 ...
```

We strongly recommend to debug using the higher level nn.Module, instead of dealing with tvm code. Please take a look at https://github.com/mlc-ai/notebooks/blob/main/mlc-llm/tutorial_add_new_model_architecture_in_tvm_nn_module.ipynb and the sections related to `Validating the Correctness of an nn.Module`

**Comment by musram** [comment]
Thanks @rickzx.  I am clear with the model building using  SLM rollout. But while calling the packed function (GPU )(eg:   ObjectRef ret = ft_.decode_func_(input_data, ShapeTuple({1}),  // generated_tokens_length_shape
                                     embedding_, kv_cache_, params_);
 i am not able to debug the error even though the jit gives me the correct result.

**Comment by MasterJH5574** [comment]
Hi @musram, given this issue is a bit inactive, I'm gonna close it. You can create a new one if still having problem with the latest codebase, and I will be happy to help.
