### ISSUE TITLE
[Question] How does cross-compile support work?

### ISSUE THREAD

**Issue by srikanthsrnvs** [mlc-ai/mlc-llm#1677]
## ❓ General Questions

I am trying to use the core.py file that contains build arguments to build an MLC model for AARCH64 on an x86 host, The problem I'm having is with incorrect symbols so I'm assuming the issue is that I have built the TVM library incorrectly. 

Can someone help me understand how cross compile support works? Merely setting the CC_path does not work and gives weird errors:

`/home/srikanth/l4t-gcc/aarch64--glibc--stable-2022.08-1/bin/../lib/gcc/aarch64-buildroot-linux-gnu/11.3.0/../../../../aarch64-buildroot-linux-gnu/bin/ld: /tmp/tmpsushxijm/lib0.o: error adding symbols: file in wrong format
collect2: error: ld returned 1 exit status`

**Comment by tqchen** [comment]
Closing as we are migrating to a new engine besides core
