### ISSUE TITLE
[Question] Swap memory not working

### ISSUE THREAD

**Issue by raj-khare** [mlc-ai/mlc-llm#1678]
## ❓ General Questions

I'm trying to load a 70B 4-bit quantized model on a 32 GB unified ram architecture machine. However my process gets killed even when i have a lot of swap. Does MLC support swap out of the box? Any advice is highly appreciated

![image](https://github.com/mlc-ai/mlc-llm/assets/37476411/f3a1a073-94b4-4156-96ef-c798877c08cc)

```
root@tegra-ubuntu:/# python3 /opt/mlc-llm/benchmark.py --model /data/models/mlc/dist/models/q4f16_ft/params/ --prompt /data/prompts/completion_16.json --max-new-tokens 128
Namespace(model='/data/models/mlc/dist/models/q4f16_ft/params/', prompt=['/data/prompts/completion_16.json'], chat=False, streaming=False, max_new_tokens=128, max_num_prompts=None, save='')
-- loading /data/models/mlc/dist/models/q4f16_ft/params/
Killed
root@tegra-ubuntu:/# 
```

**Comment by anibohara2000** [comment]
@raj-khare swap memory is managed by the operating system. The linux Out of Memory(OOM) Killer kills processes based on the used memory, and doesn't take swap into account usually

**Comment by MasterJH5574** [comment]
Yah I think for Linux, swap does not help too much here. Gonna close this issue for now. You are welcome to reopen it or open a new one if there is any further question.
