### ISSUE TITLE
[Question] tvm-unity build undefined reference to `std::__throw_bad_array_new_length()'

### ISSUE THREAD

**Issue by jpf888** [mlc-ai/mlc-llm#1683]
## ❓ General Questions
When I compile tvm-unity according to the official documentation, the following error occurs. 
 libllvmd version is 17.0. 6
 

> [100%] Linking CXX shared library libtvm.so
[100%] Linking CXX shared library libtvm_allvisible.so
/usr/bin/ld: /root/miniconda3/envs/tvm-build-venv/lib/libLLVMAMDGPUCodeGen.a(AMDGPUHSAMetadataStreamer.cpp.o): in function `llvm::AMDGPU::HSAMD::MetadataStreamerV2::verify(llvm::StringRef) const':
AMDGPUHSAMetadataStreamer.cpp:(.text._ZNK4llvm6AMDGPU5HSAMD18MetadataStreamerV26verifyENS_9StringRefE+0x1320): undefined reference to `std::__throw_bad_array_new_length()'
/usr/bin/ld: AMDGPUHSAMetadataStreamer.cpp:(.text._ZNK4llvm6AMDGPU5HSAMD18MetadataStreamerV26verifyENS_9StringRefE+0x1324): undefined reference to `std::__throw_bad_array_new_length()'
/usr/bin/ld: /root/miniconda3/envs/tvm-build-venv/lib/libLLVMAMDGPUCodeGen.a(AMDGPUHSAMetadataStreamer.cpp.o): in function `llvm::AMDGPU::HSAMD::MetadataStreamerV2::end()':
AMDGPUHSAMetadataStreamer.cpp:(.text._ZN4llvm6AMDGPU5HSAMD18MetadataStreamerV23endEv+0xc4c): undefined reference to `std::__throw_bad_array_new_length()'
/usr/bin/ld: AMDGPUHSAMetadataStreamer.cpp:(.text._ZN4llvm6AMDGPU5HSAMD18MetadataStreamerV23endEv+0xc50): undefined reference to `std::__throw_bad_array_new_length()'
/usr/bin/ld: /root/miniconda3/envs/tvm-build-venv/lib/libLLVMAMDGPUCodeGen.a(AMDGPUTargetMachine.cpp.o): in function `llvm::RegisterTargetMachine<llvm::R600TargetMachine>::Allocator(llvm::Target const&, llvm::Triple const&, llvm::StringRef, llvm::StringRef, llvm::TargetOptions const&, llvm::Optional<llvm::Reloc::Model>, llvm::Optional<llvm::CodeModel::Model>, llvm::CodeGenOpt::Level, bool)':
AMDGPUTargetMachine.cpp:(.text._ZN4llvm21RegisterTargetMachineINS_17R600TargetMachineEE9AllocatorERKNS_6TargetERKNS_6TripleENS_9StringRefES9_RKNS_13TargetOptionsENS_8OptionalINS_5Reloc5ModelEEENSD_INS_9CodeModel5ModelEEENS_10CodeGenOpt5LevelEb[_ZN4llvm21RegisterTargetMachineINS_17R600TargetMachineEE9AllocatorERKNS_6TargetERKNS_6TripleENS_9StringRefES9_RKNS_13TargetOptionsENS_8OptionalINS_5Reloc5ModelEEENSD_INS_9CodeModel5ModelEEENS_10CodeGenOpt5LevelEb]+0x780): undefined reference to `std::__throw_bad_array_new_length()'
/usr/bin/ld: /root/miniconda3/envs/tvm-build-venv/lib/libLLVMAMDGPUCodeGen.a(AMDGPUTargetMachine.cpp.o):AMDGPUTargetMachine.cpp:(.text._ZN4llvm21RegisterTargetMachineINS_17R600TargetMachineEE9AllocatorERKNS_6TargetERKNS_6TripleENS_9StringRefES9_RKNS_13TargetOptionsENS_8OptionalINS_5Reloc5ModelEEENSD_INS_9CodeModel5ModelEEENS_10CodeGenOpt5LevelEb[_ZN4llvm21RegisterTargetMachineINS_17R600TargetMachineEE9AllocatorERKNS_6TargetERKNS_6TripleENS_9StringRefES9_RKNS_13TargetOptionsENS_8OptionalINS_5Reloc5ModelEEENSD_INS_9CodeModel5ModelEEENS_10CodeGenOpt5LevelEb]+0x784): more undefined references to `std::__throw_bad_array_new_length()' follow
/usr/bin/ld: /root/miniconda3/envs/tvm-build-venv/lib/libLLVMRuntimeDyld.a(RuntimeDyld.cpp.o): in function `std::_Sp_counted_ptr_inplace<std::promise<llvm::Expected<std::map<llvm::StringRef, llvm::JITEvaluatedSymbol, std::less<llvm::StringRef>, std::allocator<std::pair<llvm::StringRef const, llvm::JITEvaluatedSymbol> > > > >, std::allocator<std::promise<llvm::Expected<std::map<llvm::StringRef, llvm::JITEvaluatedSymbol, std::less<llvm::StringRef>, std::allocator<std::pair<llvm::StringRef const, llvm::JITEvaluatedSymbol> > > > > >, (__gnu_cxx::_Lock_policy)2>::_M_dispose()':
RuntimeDyld.cpp:(.text._ZNSt23_Sp_counted_ptr_inplaceISt7promiseIN4llvm8ExpectedISt3mapINS1_9StringRefENS1_18JITEvaluatedSymbolESt4lessIS4_ESaISt4pairIKS4_S5_EEEEEESaISE_ELN9__gnu_cxx12_Lock_policyE2EE10_M_disposeEv[_ZNSt23_Sp_counted_ptr_inplaceISt7promiseIN4llvm8ExpectedISt3mapINS1_9StringRefENS1_18JITEvaluatedSymbolESt4lessIS4_ESaISt4pairIKS4_S5_EEEEEESaISE_ELN9__gnu_cxx12_Lock_policyE2EE10_M_disposeEv]+0x160): undefined reference to `std::__exception_ptr::exception_ptr::_M_release()'
/usr/bin/ld: RuntimeDyld.cpp:(.text._ZNSt23_Sp_counted_ptr_inplaceISt7promiseIN4llvm8ExpectedISt3mapINS1_9StringRefENS1_18JITEvaluatedSymbolESt4lessIS4_ESaISt4pairIKS4_S5_EEEEEESaISE_ELN9__gnu_cxx12_Lock_policyE2EE10_M_disposeEv[_ZNSt23_Sp_counted_ptr_inplaceISt7promiseIN4llvm8ExpectedISt3mapINS1_9StringRefENS1_18JITEvaluatedSymbolESt4lessIS4_ESaISt4pairIKS4_S5_EEEEEESaISE_ELN9__gnu_cxx12_Lock_policyE2EE10_M_disposeEv]+0x168): undefined reference to `std::__exception_ptr::exception_ptr::_M_release()'
/usr/bin/ld: /root/miniconda3/envs/tvm-build-venv/lib/libLLVMRuntimeDyld.a(RuntimeDyld.cpp.o): in function `void std::deque<llvm::SectionEntry, std::allocator<llvm::SectionEntry> >::emplace_back<llvm::SectionEntry>(llvm::SectionEntry&&)':
RuntimeDyld.cpp:(.text._ZNSt5dequeIN4llvm12SectionEntryESaIS1_EE12emplace_backIJS1_EEEvDpOT_[_ZNSt5dequeIN4llvm12SectionEntryESaIS1_EE12emplace_backIJS1_EEEvDpOT_]+0x2f4): undefined reference to `std::__throw_bad_array_new_length()'
/usr/bin/ld: RuntimeDyld.cpp:(.text._ZNSt5dequeIN4llvm12SectionEntryESaIS1_EE12emplace_backIJS1_EEEvDpOT_[_ZNSt5dequeIN4llvm12SectionEntryESaIS1_EE12emplace_backIJS1_EEEvDpOT_]+0x2f8): undefined reference to `std::__throw_bad_array_new_length()'
/usr/bin/ld: /root/miniconda3/envs/tvm-build-venv/lib/libLLVMRuntimeDyld.a(RuntimeDyld.cpp.o): in function `llvm::RuntimeDyldImpl::resolveExternalSymbols() [clone .localalias]':
RuntimeDyld.cpp:(.text._ZN4llvm15RuntimeDyldImpl22resolveExternalSymbolsEv+0xb50): undefined reference to `std::__exception_ptr::exception_ptr::_M_addref()'
/usr/bin/ld: RuntimeDyld.cpp:(.text._ZN4llvm15RuntimeDyldImpl22resolveExternalSymbolsEv+0xb5c): undefined reference to `std::__exception_ptr::exception_ptr::_M_addref()'
/usr/bin/ld: /root/miniconda3/envs/tvm-build-venv/lib/libLLVMRuntimeDyld.a(RuntimeDyld.cpp.o): in function `std::_Hashtable<unsigned int, std::pair<unsigned int const, llvm::SmallVector<llvm::RelocationEntry, 64u> >, std::allocator<std::pair<unsigned int const, llvm::SmallVector<llvm::RelocationEntry, 64u> > >, std::__detail::_Select1st, std::equal_to<unsigned int>, std::hash<unsigned int>, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<false, false, true> >::_M_insert_unique_node(unsigned long, unsigned long, std::__detail::_Hash_node<std::pair<unsigned int const, llvm::SmallVector<llvm::RelocationEntry, 64u> >, false>*, unsigned long)':
RuntimeDyld.cpp:(.text._ZNSt10_HashtableIjSt4pairIKjN4llvm11SmallVectorINS2_15RelocationEntryELj64EEEESaIS6_ENSt8__detail10_Select1stESt8equal_toIjESt4hashIjENS8_18_Mod_range_hashingENS8_20_Default_ranged_hashENS8_20_Prime_rehash_policyENS8_17_Hashtable_traitsILb0ELb0ELb1EEEE21_M_insert_unique_nodeEmmPNS8_10_Hash_nodeIS6_Lb0EEEm[_ZNSt10_HashtableIjSt4pairIKjN4llvm11SmallVectorINS2_15RelocationEntryELj64EEEESaIS6_ENSt8__detail10_Select1stESt8equal_toIjESt4hashIjENS8_18_Mod_range_hashingENS8_20_Default_ranged_hashENS8_20_Prime_rehash_policyENS8_17_Hashtable_traitsILb0ELb0ELb1EEEE21_M_insert_unique_nodeEmmPNS8_10_Hash_nodeIS6_Lb0EEEm]+0x1c8): undefined reference to `std::__throw_bad_array_new_length()'
/usr/bin/ld: RuntimeDyld.cpp:(.text._ZNSt10_HashtableIjSt4pairIKjN4llvm11SmallVectorINS2_15RelocationEntryELj64EEEESaIS6_ENSt8__detail10_Select1stESt8equal_toIjESt4hashIjENS8_18_Mod_range_hashingENS8_20_Default_ranged_hashENS8_20_Prime_rehash_policyENS8_17_Hashtable_traitsILb0ELb0ELb1EEEE21_M_insert_unique_nodeEmmPNS8_10_Hash_nodeIS6_Lb0EEEm[_ZNSt10_HashtableIjSt4pairIKjN4llvm11SmallVectorINS2_15RelocationEntryELj64EEEESaIS6_ENSt8__detail10_Select1stESt8equal_toIjESt4hashIjENS8_18_Mod_range_hashingENS8_20_Default_ranged_hashENS8_20_Prime_rehash_policyENS8_17_Hashtable_traitsILb0ELb0ELb1EEEE21_M_insert_unique_nodeEmmPNS8_10_Hash_nodeIS6_Lb0EEEm]+0x1cc): undefined reference to `std::__throw_bad_array_new_length()'
/usr/bin/ld: /root/miniconda3/envs/tvm-build-venv/lib/libLLVMRuntimeDyld.a(RuntimeDyldELF.cpp.o): in function `void std::deque<llvm::SectionEntry, std::allocator<llvm::SectionEntry> >::_M_push_back_aux<llvm::SectionEntry>(llvm::SectionEntry&&)':
RuntimeDyldELF.cpp:(.text._ZNSt5dequeIN4llvm12SectionEntryESaIS1_EE16_M_push_back_auxIJS1_EEEvDpOT_[_ZNSt5dequeIN4llvm12SectionEntryESaIS1_EE16_M_push_back_auxIJS1_EEEvDpOT_]+0x26c): undefined reference to `std::__throw_bad_array_new_length()'
/usr/bin/ld: RuntimeDyldELF.cpp:(.text._ZNSt5dequeIN4llvm12SectionEntryESaIS1_EE16_M_push_back_auxIJS1_EEEvDpOT_[_ZNSt5dequeIN4llvm12SectionEntryESaIS1_EE16_M_push_back_auxIJS1_EEEvDpOT_]+0x270): undefined reference to `std::__throw_bad_array_new_length()'
/usr/bin/ld: /root/miniconda3/envs/tvm-build-venv/lib/libLLVMipo.a(ArgumentPromotion.cpp.o): in function `doPromotion(llvm::Function*, llvm::SmallPtrSetImpl<llvm::Argument*>&, llvm::SmallPtrSetImpl<llvm::Argument*>&, llvm::Optional<llvm::function_ref<void (llvm::CallBase&, llvm::CallBase&)> >) [clone .isra.0]':
ArgumentPromotion.cpp:(.text._ZL11doPromotionPN4llvm8FunctionERNS_15SmallPtrSetImplIPNS_8ArgumentEEES6_NS_8OptionalINS_12function_refIFvRNS_8CallBaseESA_EEEEE.isra.0+0x25fc): undefined reference to `std::__throw_bad_array_new_length()'
/usr/bin/ld: /root/miniconda3/envs/tvm-build-venv/lib/libLLVMipo.a(ArgumentPromotion.cpp.o):ArgumentPromotion.cpp:(.text._ZL11doPromotionPN4llvm8FunctionERNS_15SmallPtrSetImplIPNS_8ArgumentEEES6_NS_8OptionalINS_12function_refIFvRNS_8CallBaseESA_EEEEE.isra.0+0x2600): more undefined references to `std::__throw_bad_array_new_length()' follow

**Comment by shreygupta2809** [comment]
Could you provide some more information about your build and conda environment?

**Comment by jpf888** [comment]
> Could you provide some more information about your build and conda environment? I tried reproducing this but am not able to directly.


Thank you for your response. My base environment is a container based on TVM image for aarch64, and then I set up Conda within the container.  followed this “https://llm.mlc.ai/docs/install/tvm.html ” for setting up the Conda environment.

My current issue is that when linking libtvm.so, there's an error mentioning that the function llvm::AMDGPU::HSAMD::MetadataStreamerV2::verify(llvm::StringRef) in the target file AMDGPUHSAMetadataStreamer.cpp.o references an undefined function std::__throw_bad_array_new_length(). The static library is installed via Conda and is LLVM 17.0.6. Currently, I suspect it's a C++ library version problem.

In the initial compilation, I used the gcc and g++ from /usr/bin within the container.   Later, I speculated that I should use gcc and g++ from Conda for compilation. However, when I switched to Conda's gcc, it threw an error saying "gcc compiler does not recognize -march=nocona".   Therefore, I still need to use the gcc from the container.

but this issue not solved

**Comment by jpf888** [comment]
> Could you provide some more information about your build and conda environment? I tried reproducing this but am not able to directly.

this is  my  conda env list
`# Name                    Version                   Build  Channel
_openmp_mutex             4.5                       2_gnu    conda-forge
binutils_impl_linux-aarch64 2.38                 h0c9fd12_1  
bzip2                     1.0.8                h31becfc_5    conda-forge
c-ares                    1.26.0               h31becfc_0    conda-forge
ca-certificates           2024.2.2             hcefe29a_0    conda-forge
clang                     14.0.6               hd43f75c_1  
clang-14                  14.0.6          default_hd3a980f_1  
cmake                     3.26.4               h3bd60fd_0  
curl                      8.2.1                h581cc77_0  
expat                     2.5.0                h419075a_0  
gcc_impl_linux-aarch64    11.2.0               h1234567_1  
gettext                   0.21.1               ha18d298_0    conda-forge
git                       2.40.1          pl5340h0779aa8_1  
kernel-headers_linux-aarch64 4.14.214            h1cb168f_14  
keyutils                  1.6.1                h4e544f5_0    conda-forge
krb5                      1.20.1               h519e096_0    conda-forge
ld_impl_linux-aarch64     2.38                 h8131f2d_1  
libclang-cpp14            14.0.6          default_hd3a980f_1  
libcurl                   8.2.1                h79326fa_0  
libedit                   3.1.20191231         he28a2e2_2    conda-forge
libev                     4.33                 h31becfc_2    conda-forge
libexpat                  2.5.0                hd600fc2_1    conda-forge
libffi                    3.4.4                h419075a_0  
libgcc-devel_linux-aarch64 11.2.0               h1234567_1  
libgcc-ng                 13.2.0               hf8544c7_5    conda-forge
libgomp                   13.2.0               hf8544c7_5    conda-forge
libiconv                  1.17                 h31becfc_2    conda-forge
libllvm14                 14.0.6               hb8fdbf2_3  
libllvm17                 17.0.6               h64b4ff8_0  
libnghttp2                1.52.0               h5192db0_1  
libnsl                    2.0.0                h998d150_0  
libssh2                   1.10.0               h581cc77_2  
libstdcxx-ng              13.2.0               h9a76618_5    conda-forge
libuv                     1.46.0               h31becfc_0    conda-forge
libxcrypt                 4.4.36               h31becfc_1    conda-forge
libzlib                   1.2.13               h31becfc_5    conda-forge
llvm-tools                14.0.6               hb8fdbf2_3  
llvmdev                   14.0.6               hb8fdbf2_3  
ncurses                   6.4                  h0425590_2    conda-forge
openssl                   1.1.1w               h2f4d8fa_0  
pcre2                     10.42                hd0f9c67_0    conda-forge
perl                      5.32.1          7_h31becfc_perl5    conda-forge
pip                       21.3.1             pyhd8ed1ab_0    conda-forge
python                    3.6.15          h30375ac_0_cpython    conda-forge
python_abi                3.6                     2_cp36m    conda-forge
readline                  8.2                  h998d150_0  
rhash                     1.4.4                h31becfc_0    conda-forge
setuptools                58.0.4           py36h704843e_2    conda-forge
sqlite                    3.41.2               h998d150_0  
sysroot_linux-aarch64     2.26                h4744778_14  
tk                        8.6.12               h241ca14_0  
wheel                     0.37.1             pyhd3eb1b0_0  
xz                        5.4.5                h998d150_0  
zlib                      1.2.13               h31becfc_5    conda-forge
zstd                      1.5.5                h4c53e97_0    conda-forge
`

**Comment by jpf888** [comment]
Hi, I have solved this problem by compiling directly in the container without using conda. The compilation passed, which verified that my previous guess was correct.
Be careful about the direct environmental dependencies between conda and the container

**Comment by jpf888** [comment]
@shreygupta2809 

I have set config.cmake use_rocm to OFF, but libtvm.so still links to amdgpu, and I'm not sure why.  Can you explain why?

[100%] Linking CXX shared library libtvm.so
[100%] Linking CXX shared library libtvm_allvisible.so
/usr/bin/ld: /root/miniconda3/envs/tvm-build-venv/lib/libLLVMAMDGPUCodeGen.a(AMDGPUHSAMetadataStreamer.cpp.o): in function llvm::AMDGPU::HSAMD::MetadataStreamerV2::verify(llvm::StringRef) const': AMDGPUHSAMetadataStreamer.cpp:

**Comment by shreygupta2809** [comment]
Did you have `use_rocm` ON initially? Could you try building it again after doing `make clean` or deleting the build folder completely and doing it again?

**Comment by jpf888** [comment]
> Did you have `use_rocm` ON initially? Could you try building it again with the flag `--clean-first` [CMake Options](https://cmake.org/cmake/help/v3.1/manual/cmake.1.html#options) or deleting the build folder completely and doing it again?

I didn't build rocm at the beginning, and every time I deleted other files in the build folder, leaving only config.cmake. 

When cmake added printing and compiled, rocm was off. 

I suspect that rocm was set in the environment variable, but No, do other third-party libraries or files depend on amdgpu?

**Comment by shreygupta2809** [comment]
Not sure, exactly. Can you try building tvm using the `main` branch instead of `unity`?
