### ISSUE TITLE
mlc_chat_cli doesn't using GPU

### ISSUE THREAD

**Issue by NeoWang9999** [mlc-ai/mlc-llm#169]
mlc_ chat_ Cli is running on my WSL, but it seems that I didn't use GPU, but instead used CPU entirely, which is very slow. How can I use GPU in this environment?

![image](https://github.com/mlc-ai/mlc-llm/assets/48009681/bed4e767-b5ae-41dc-a1a0-0ba4a65238c8)

![image](https://github.com/mlc-ai/mlc-llm/assets/48009681/f3561c70-0321-404a-80d9-48953f333fb6)

**Comment by LeiWang1999** [comment]
If the Vulkan driver is not properly installed, the CPU simulation of Vulkan will be used, the way to check out the vulkan installation is find if the `/usr/share/vulkan/icd.d/nvidia_icd.json` exists.
