### ISSUE TITLE
[Bug]  TVMruntime cannot find vm_load_executable only for phi-2 on Android

### ISSUE THREAD

**Issue by qc903113684** [mlc-ai/mlc-llm#1692]
## 🐛 Bug

I compile phi-2 and Mistral-7B for Android. And Mistral-7B worked but phi-2 get error.
![1c595a8e4872d633237ca0f8f43478d](https://github.com/mlc-ai/mlc-llm/assets/38254779/afda2893-f179-48d0-8130-6f3478eca726)

## To Reproduce

Follow document to compile phi-2 and Mistral and build Android app (https://llm.mlc.ai/docs/deploy/android.html)

## Expected behavior

phi-2 work success

## Environment

 - Platform (e.g. WebGPU/Vulkan/IOS/Android/CUDA):Android
 - Operating system (e.g. Ubuntu/Windows/MacOS/...):Ubuntu 22.04
 - Device (e.g. iPhone 12 Pro, PC+RTX 3090, ...)
 - How you installed MLC-LLM (`conda`, source):conda
 - How you installed TVM-Unity (`pip`, source):pip
 - Python version (e.g. 3.10):3.10
 - GPU driver version (if applicable):535.86.05
 - CUDA/cuDNN version (if applicable):11.8
 - TVM Unity Hash Tag (`python -c "import tvm; print('\n'.join(f'{k}: {v}' for k, v in tvm.support.libinfo().items()))"`, applicable if you compile models):
USE_NVTX: OFF
USE_GTEST: AUTO
SUMMARIZE: OFF
USE_IOS_RPC: OFF
USE_MSC: OFF
USE_ETHOSU: 
CUDA_VERSION: 11.8
USE_LIBBACKTRACE: AUTO
DLPACK_PATH: 3rdparty/dlpack/include
USE_TENSORRT_CODEGEN: OFF
USE_THRUST: OFF
USE_TARGET_ONNX: OFF
USE_AOT_EXECUTOR: ON
BUILD_DUMMY_LIBTVM: OFF
USE_CUDNN: OFF
USE_TENSORRT_RUNTIME: OFF
USE_ARM_COMPUTE_LIB_GRAPH_EXECUTOR: OFF
USE_CCACHE: AUTO
USE_ARM_COMPUTE_LIB: OFF
USE_CPP_RTVM: 
USE_OPENCL_GTEST: /path/to/opencl/gtest
USE_MKL: OFF
USE_PT_TVMDSOOP: OFF
MLIR_VERSION: NOT-FOUND
USE_CLML: OFF
USE_STACKVM_RUNTIME: OFF
USE_GRAPH_EXECUTOR_CUDA_GRAPH: OFF
ROCM_PATH: /opt/rocm
USE_DNNL: OFF
USE_VITIS_AI: OFF
USE_MLIR: OFF
USE_RCCL: OFF
USE_LLVM: llvm-config --ignore-libllvm --link-static
USE_VERILATOR: OFF
USE_TF_TVMDSOOP: OFF
USE_THREADS: ON
USE_MSVC_MT: OFF
BACKTRACE_ON_SEGFAULT: OFF
USE_GRAPH_EXECUTOR: ON
USE_NCCL: ON
USE_ROCBLAS: OFF
GIT_COMMIT_HASH: 05dc738fb687154f0927868062858471879ea18b
USE_VULKAN: ON
USE_RUST_EXT: OFF
USE_CUTLASS: ON
USE_CPP_RPC: OFF
USE_HEXAGON: OFF
USE_CUSTOM_LOGGING: OFF
USE_UMA: OFF
USE_FALLBACK_STL_MAP: OFF
USE_SORT: ON
USE_RTTI: ON
GIT_COMMIT_TIME: 2024-01-24 10:28:52 -0500
USE_HEXAGON_SDK: /path/to/sdk
USE_BLAS: none
USE_ETHOSN: OFF
USE_LIBTORCH: OFF
USE_RANDOM: ON
USE_CUDA: ON
USE_COREML: OFF
USE_AMX: OFF
BUILD_STATIC_RUNTIME: OFF
USE_CMSISNN: OFF
USE_KHRONOS_SPIRV: OFF
USE_CLML_GRAPH_EXECUTOR: OFF
USE_TFLITE: OFF
USE_HEXAGON_GTEST: /path/to/hexagon/gtest
PICOJSON_PATH: 3rdparty/picojson
USE_OPENCL_ENABLE_HOST_PTR: OFF
INSTALL_DEV: OFF
USE_PROFILER: ON
USE_NNPACK: OFF
LLVM_VERSION: 15.0.7
USE_OPENCL: OFF
COMPILER_RT_PATH: 3rdparty/compiler-rt
RANG_PATH: 3rdparty/rang/include
USE_SPIRV_KHR_INTEGER_DOT_PRODUCT: OFF
USE_OPENMP: OFF
USE_BNNS: OFF
USE_CUBLAS: ON
USE_METAL: OFF
USE_MICRO_STANDALONE_RUNTIME: OFF
USE_HEXAGON_EXTERNAL_LIBS: OFF
USE_ALTERNATIVE_LINKER: AUTO
USE_BYODT_POSIT: OFF
USE_HEXAGON_RPC: OFF
USE_MICRO: OFF
DMLC_PATH: 3rdparty/dmlc-core/include
INDEX_DEFAULT_I64: ON
USE_RELAY_DEBUG: OFF
USE_RPC: ON
USE_TENSORFLOW_PATH: none
TVM_CLML_VERSION: 
USE_MIOPEN: OFF
USE_ROCM: OFF
USE_PAPI: OFF
USE_CURAND: OFF
TVM_CXX_COMPILER_PATH: /opt/rh/gcc-toolset-11/root/usr/bin/c++
HIDE_PRIVATE_SYMBOLS: ON
 - Any other relevant information:

## Additional context

I'd like to know if this error means it's not currently supported for phi-2 on Android or if there's something wrong with my compilation process。

**Comment by Kartik14** [comment]
Copying from Discord

I think that the app is not able to locate the model library correctly? It might be if the model_lib is not set correctly in app-config.json while building the apk (Refer https://llm.mlc.ai/docs/deploy/android.html#create-android-project-using-compiled-models for more details). Can you share your app-config.json file that you are using to compile the model lib?

**Comment by qc903113684** [comment]
Thanks, I fixed this error.

**Comment by hmzdtz** [comment]
May I ask how to fix it? 

I didn't explicitly use `--system-lib-prefix` but all with default value. All other steps and documents are completely consistent, and no exceptions were thrown throughout the process.

This my `app-config.json`.

```
{
  "model_list": [
    {
      "model_url": "https://huggingface.co/mlc-ai/Llama-2-7b-chat-hf-q4f16_1-MLC/",
      "model_lib": "llama_q4f16_1",
      "estimated_vram_bytes": 4348727787,
      "model_id": "Llama-2-7b-chat-hf-q4f16_1"
    },
    {
      "model_url": "https://huggingface.co/mlc-ai/RedPajama-INCITE-Chat-3B-v1-q4f16_1-MLC/",
      "model_lib": "gpt_neox_q4f16_1",
      "estimated_vram_bytes": 1948348579,
      "model_id": "RedPajama-INCITE-Chat-3B-v1-q4f16_1"
    }
  ],
  "model_lib_path_for_prepare_libs": {
    "llama_q4f16_1": "libs/Llama-2-7b-chat-hf-q4f16_1-android.tar",
    "gpt_neox_q4f16_1": "libs/RedPajama-INCITE-Chat-3B-v1-q4f16_1-android.tar"
  }
}
```

**Comment by hmzdtz** [comment]
@qc903113684 @Kartik14 
May I ask how to fix it? 
I didn't explicitly use `--system-lib-prefix`, and all with default value. All other steps and documents are completely consistent, and no exceptions were thrown throughout the process.

This my `app-config.json`:

```json
{
  "model_list": [
    {
      "model_url": "https://huggingface.co/mlc-ai/Llama-2-7b-chat-hf-q4f16_1-MLC/",
      "model_lib": "llama_q4f16_1",
      "estimated_vram_bytes": 4348727787,
      "model_id": "Llama-2-7b-chat-hf-q4f16_1"
    },
    {
      "model_url": "https://huggingface.co/mlc-ai/RedPajama-INCITE-Chat-3B-v1-q4f16_1-MLC/",
      "model_lib": "gpt_neox_q4f16_1",
      "estimated_vram_bytes": 1948348579,
      "model_id": "RedPajama-INCITE-Chat-3B-v1-q4f16_1"
    }
  ],
  "model_lib_path_for_prepare_libs": {
    "llama_q4f16_1": "libs/Llama-2-7b-chat-hf-q4f16_1-android.tar",
    "gpt_neox_q4f16_1": "libs/RedPajama-INCITE-Chat-3B-v1-q4f16_1-android.tar"
  }
}
```
