### ISSUE TITLE
[Bug] Failed to set the allowed dynamic shared memory size to 73728

### ISSUE THREAD

**Issue by louis030195** [mlc-ai/mlc-llm#1694]
## 🐛 Bug

>[Bug] Failed to set the allowed dynamic shared memory size to 73728

## To Reproduce

```
gcloud compute instances create llm --zone=us-central1-a --machine-type=n1-standard-8 --network-interface=network-tier=PREMIUM,stack-type=IPV4_ONLY,subnet=default --maintenance-policy=TERMINATE --provisioning-model=STANDARD --scopes=https://www.googleapis.com/auth/devstorage.read_only,https://www.googleapis.com/auth/logging.write,https://www.googleapis.com/auth/monitoring.write,https://www.googleapis.com/auth/servicecontrol,https://www.googleapis.com/auth/service.management.readonly,https://www.googleapis.com/auth/trace.append --accelerator=count=1,type=nvidia-tesla-t4 --tags=https-server --create-disk=auto-delete=yes,boot=yes,device-name=llm,image=projects/ml-images/global/images/c0-deeplearning-common-gpu-v20240111-debian-11-py310,mode=rw,size=400,type=projects/mediar-394022/zones/us-central1-a/diskTypes/pd-balanced --no-shielded-secure-boot --shielded-vtpm --shielded-integrity-monitoring --labels=goog-ec-src=vm_add-gcloud --reservation-affinity=any
```

```
gcloud compute ssh --zone "us-central1-a" "llm" 
```
```bash
sudo apt-get install git-lfs
git lfs install
conda create -n myenv python=3.9 -y
conda activate myenv
python3 -m pip install --pre -U -f https://mlc.ai/wheels mlc-chat-nightly-cu118 mlc-ai-nightly-cu118
mkdir -p dist
git clone https://github.com/mlc-ai/binary-mlc-llm-libs.git dist/prebuilt_libs
MODEL="Mistral-7B-Instruct-v0.2-q4f16_1-MLC"
cd dist && git clone https://huggingface.co/mlc-ai/$MODEL
python -m mlc_chat.rest --model $MODEL --port 3000 --host 0.0.0.0
```

```
 curl http://127.0.0.1:3000/v1/chat/completions -H "Content-Type: application/json"    -d '{
    "model": "Mistral-7B-Instruct-v0.2-q4f16_1-MLC",
    "messages": [
      {
        "role": "user",
        "content": "You are a helpful assistant."
      }
    ]
  }'
```

python -m mlc_chat.rest --model $MODEL --port 3000 --host 0.0.0.0

## Expected behavior

answer

## Environment

```
gcloud compute instances create llm --zone=us-central1-a --machine-type=n1-standard-8 --network-interface=network-tier=PREMIUM,stack-type=IPV4_ONLY,subnet=default --maintenance-policy=TERMINATE --provisioning-model=STANDARD --scopes=https://www.googleapis.com/auth/devstorage.read_only,https://www.googleapis.com/auth/logging.write,https://www.googleapis.com/auth/monitoring.write,https://www.googleapis.com/auth/servicecontrol,https://www.googleapis.com/auth/service.management.readonly,https://www.googleapis.com/auth/trace.append --accelerator=count=1,type=nvidia-tesla-t4 --tags=https-server --create-disk=auto-delete=yes,boot=yes,device-name=llm,image=projects/ml-images/global/images/c0-deeplearning-common-gpu-v20240111-debian-11-py310,mode=rw,size=400,type=projects/mediar-394022/zones/us-central1-a/diskTypes/pd-balanced --no-shielded-secure-boot --shielded-vtpm --shielded-integrity-monitoring --labels=goog-ec-src=vm_add-gcloud --reservation-affinity=any

```

 - Platform (e.g. WebGPU/Vulkan/IOS/Android/CUDA): Cuda 11.8
 - Operating system (e.g. Ubuntu/Windows/MacOS/...): Debian
 - Device (e.g. iPhone 12 Pro, PC+RTX 3090, ...) 
 - How you installed MLC-LLM (`conda`, source):
 - How you installed TVM-Unity (`pip`, source):
 - Python version (e.g. 3.10): 3.9
 - GPU driver version (if applicable):
 - CUDA/cuDNN version (if applicable):
 - TVM Unity Hash Tag (`python -c "import tvm; print('\n'.join(f'{k}: {v}' for k, v in tvm.support.libinfo().items()))"`, applicable if you compile models):
 - Any other relevant information:

**Comment by louis030195** [comment]
Update: upgrade to GPU L4 and it works.

What should I've done to run on the T4? Is there a way to run in half precision or smthing?

**Comment by shreygupta2809** [comment]
`q4f16` refers to the quantization with which the model was built. You can read more about this here: [Quantization Docs](https://llm.mlc.ai/docs/compilation/configure_quantization.html). `q0f16`/`q3f16` are also supported which should reduce model size however they might not be provided precompiled and you may need to convert weights manually and then compile the model to run on MLC. You can read about this: [Converting weights and Compilation](https://llm.mlc.ai/docs/compilation/convert_weights.html)

On the other hand, if you want to stick to `q4f16`, by default only 1 GPU is used, so you may need to use 2 or more T4 GPUs.
On leveraging 2 CUDA, only 2 extra steps are needed: 
1. Build `tvm` with `set(USE_NCCL ON)`
2. Change `tensor_parallel_shards` to `2` in `mlc-chat-config.json` and then compile the model
