### ISSUE TITLE
consider adding 6.9/12B/20B from h2oGPT project

### ISSUE THREAD

**Issue by pseudotensor** [mlc-ai/mlc-llm#17]
https://huggingface.co/h2oai

Better than dolly for 12B for example, trained on OASST data.

**Comment by thepra** [comment]
I also have the 30B LLAMA and a computer powerful enough, is there a way to support it?

**Comment by tqchen** [comment]
Comparing to other models seems this model was less in demand, closing due to inactive issues, feel free to open new ones
