### ISSUE TITLE
What is the best way to deploy the 'mlc_chat' service as an API that accepts HTTP requests?

### ISSUE THREAD

**Issue by NeoWang9999** [mlc-ai/mlc-llm#170]
I tested the 'mlc_chat_cli' command in a Linux environment, and I want to deploy it as an API that can call services. Is there a convenient way to deploy it, such as a Docker image?

**Comment by sudeepag** [comment]
Not currently, but we are in the process of putting up a PR soon that will expose a REST API.

**Comment by sudeepag** [comment]
Please check out https://github.com/mlc-ai/mlc-llm/tree/main/python#rest-api for instructions on how to use the REST API.

**Comment by tqchen** [comment]
closing as rest api is not part of the main
