### ISSUE TITLE
[Question] Can the demo run on the Kirin chip

### ISSUE THREAD

**Issue by zkh2016** [mlc-ai/mlc-llm#1702]
## ❓ General Questions

I compiled a demo based on the [document](https://llm.mlc.ai/docs/deploy/android.html) and found that it crashes directly on a Huawei Kirin chip phone, while it runs normally on other chip phones. Is this a persistent issue? Or what configuration needs to be modified to run?

**Comment by Hzfengsy** [comment]
We only tested on the Android App on Qualcomm 8gen2 and 8gen3, but we do not have use any specific API for Qualcomm Soc, so it should work on any android devices.

It would be great if you could locate the problem or send a PR to fix it :)

**Comment by MasterJH5574** [comment]
Gonna close this issue due to inactivity. You are welcome to reopen it or open a new one if there are further questions.
