### ISSUE TITLE
[Question] Caching the beginning of the prompt

### ISSUE THREAD

**Issue by kripper** [mlc-ai/mlc-llm#1703]
## ❓ General Questions

My understanding is that, with other inference implementations, a part of the prompt at the begging, eg. the system prompt, can be cached and reused to accelerate further inferences that share the same initial cached prompt section.

I confirmed this using CTranslate2, for example, and got huge speed improvements by leaving the repeating instructions in the system message at the begging of the prompt and only changed the end of the prompt providing different context information for each inference iteration.

Is this possible with mlc-llm and Mistral 7B?

Is this maybe considered in https://github.com/mlc-ai/mlc-llm/issues/1118?

**Comment by federicoparra** [comment]
Hi @tqchen @kripper , I wonder if this is related to HuggingFace's Transformers generate() implementation - when we use use_cache = True we get the key-values that we can reuse to avoid recalculation of previously calculated tokens (in the encoder).
The difference between using vs. not using use_cache in transformers generate() is tremendous. I was wondering today if MLC allows this.

**Comment by federicoparra** [comment]
> thanks for the suggestion, this is something that we are working on through the updated kv cache interface with forking, please stay tuned

Hi! Any news on this?

**Comment by MasterJH5574** [comment]
Hi @federicoparra, https://github.com/mlc-ai/mlc-llm/pull/1868 supports prefix caching in MLC Serve in the form of parameter `n` in OpenAI API. Right now we are also working on more general prefix caching.

**Comment by tqchen** [comment]
moving to #2295
