### ISSUE TITLE
[FEATURE]VL Model Support

### ISSUE THREAD

**Issue by ningpengtao-coder** [mlc-ai/mlc-llm#1709]
## 🚀 Feature
Currently, mlc-llm lacks support for VL models. Consider supporting the following VL models:
https://huggingface.co/Qwen/Qwen-VL-Chat
https://huggingface.co/openbmb/MiniCPM-V
https://huggingface.co/mtgv/MobileLLaMA-2.7B-Chat
https://huggingface.co/liuhaotian/llava-v1.6-mistral-7b

Recently, the mlc-llm fork https://github.com/OpenBMB/mlc-MiniCPM supports its own VL Model. Is it possible to port from this fork?

## Motivation
Nowadays, there are less and less text data on the Internet, and the proportion of video and image data is increasing. It is also important to look at pictures to speak.

**Comment by anibohara2000** [comment]
We are working on adding support for Llava. It is expected to be supported within this week

**Comment by WangFengtu1996** [comment]
+1

**Comment by EmilioZhao** [comment]
+1, look forward to trying LLaVA model on mlc-llm @anibohara2000 , please let us know when it is ready ASAP, thanks a bunch!

**Comment by jpf888** [comment]
+1

**Comment by Paramstr** [comment]
Any update on this? Really looking forward to using Llava!

**Comment by tqchen** [comment]
llava now lands in mlc serve
