### ISSUE TITLE
[Feature Request] Does Hexagon backend supported？

### ISSUE THREAD

**Issue by FdyCN** [mlc-ai/mlc-llm#1712]
## 🚀 Feature
I am a newer to TVM and mlc-llm，and i know mlc-llm is based on TVM unity branch and using Relax IR.
I don't know Relax IR can be generate hexagon target code？ If not, would you take this feature into consideration on Relax？

## Motivation
deploy mlc-llm on mobile phones and using Hexagon backend.

**Comment by Hzfengsy** [comment]
duplicated of #1689
