### ISSUE TITLE
Does MLC support key-value cache ?

### ISSUE THREAD

**Issue by federicoparra** [mlc-ai/mlc-llm#1717]
## ❓ General Questions

Hi guys! I'm testing the newly added StableLM-2 (1.6B) on MLC.

I've noticed that when using the same model in HF Transformers, one has the option to pass to the model not just the prompt but also the past key values, in which case the inference is accelerated enormously. 

To give you an example, on Google Colab using CPU only, inference for 20 tokens using a custom loop and without using key-value cache takes 22 seconds, whereas the same inference using key-value cache (passing the previous key-values to the model for the next token) takes only 4 seconds. 

The difference increases when the inference is longer (more tokens).

I'm wondering if MLC allows this and/or if you do this internally. If so, it would be nice to have an API for it, I give you an example:
I'm creating a chat, and I want, every 10 or so question-response cycles, to summarize the conversation so that the chat can continue without becoming slowed down. The call to the LLM to summarize is better done without using any memory of the conversation. But then when the conversation continues, it would be good to have the context again. In this case, the call to the LLM for summarization should be done with value-keys set to None, whereas the calls to the LLM to continue the conversation should be done with the previous value-keys.

**Comment by anibohara2000** [comment]
We currently don't support explicitly passing the KV cache, that is managed internally. However, we do support passing a list of messages in the `generate` function. For example, you can pass this as the input prompt:
`[
                    ChatMessage(role="user", content="Hello, how are you?"),
                    ChatMessage(role="assistant", content="I'm fine, thank you. How about you?"),
                    ChatMessage(role="user", content="I'm good too."),
                ]`

**Comment by federicoparra** [comment]
Hi @anibohara2000 thanks for your response.

To clarify: you are saying that a) MLC *does* implement KV cache (in general, and in particular for the StableLM-2-1_6 model) and b) that it is not available for the user (i.e., there is no API for it)?

When we do cm.reset_chat() are we a) removing all previous messages from a list and/or b) deleting the kv cache? 

The question is important for two reasons: speed and customizability. For speed, as said in my post above, using kv vs not using it amounts to a many-fold increase in speed.

With regards to customizability, in certain situations, it would be of value to be able to handle the kv cache manually.
In particular, if we need several "cognitive" services, for example if we need an LLM for chat and an LLM to review the other LLM's messages for offensive language, we can resolve this with a single instance of an LLM, which we call with kv about the chat history in the former case (for chatting) and which we call without kv for review (so that it can review a message specifically outside of context).

Is there any workaround to access the methods to send the kv manually?

Finally, you mentioned that the generator of MLC supports batch generation (I think that's the name for generating based on a list of messages) - is there any difference between doing that vs simply accumulating previous generated messages in a list myself and sending them all together to the cm.generate call ?

All my best!
Federico

**Comment by federicoparra** [comment]
Thank you for such a prompt, detailed, response ! can you point me in the right direction (i.e., the right .py file?) if I wanted to explore and submit a pr for this? thanks!

**Comment by anibohara2000** [comment]
Sure! You can look at [chat_module.py](https://github.com/mlc-ai/mlc-llm/blob/main/python/mlc_chat/chat_module.py), [llm_chat.cc](https://github.com/mlc-ai/mlc-llm/blob/main/cpp/llm_chat.cc) and [kv_cache.h](https://github.com/mlc-ai/relax/blob/292137088115ac81779607ca223bbbd9ad40cb55/src/runtime/relax_vm/kv_cache.h) to start

**Comment by anibohara2000** [comment]
Closing this for now

**Comment by Dujianhua1008** [comment]
hei bro .
now I want to get a hiddenstate or KVcache,does Tvm support a api now?
