### ISSUE TITLE
[Question] Use relax.VirtualMachine to call func, how to load params ?

### ISSUE THREAD

**Issue by Bobo-y** [mlc-ai/mlc-llm#1718]
## ❓ General Questions
For llama model, after mlc-chat convert_weights,gen_config, complie, the model can run with ChatModule, But when i use relax.VirtualMachine to call func, report error.

![image](https://github.com/mlc-ai/mlc-llm/assets/9928596/8c66ed1f-c806-40bc-98d6-61bb66e41dac)

![image](https://github.com/mlc-ai/mlc-llm/assets/9928596/3b962fac-c183-4bae-bd2a-1bcddc320ce0)

code
`python
    primary_device = tvm.device(args.primary_device)
    params, meta = tvmjs.load_ndarray_cache(args.artifact_path, primary_device)
    const_params = []
    for k, v in params.items():
        const_params.append(v)
    ex = tvm.runtime.load_module(os.path.join('dist/libs/Llama-2-3b-chat-hf-q4f16_1-MLC.so'))
    vm = relax.VirtualMachine(ex, primary_device)
    tokenizer = AutoTokenizer.from_pretrained(os.path.join(args.artifact_path), trust_remote_code=True)
    inputs = tvm.nd.array(tokenizer(args.prompt, return_tensors="pt").input_ids.to(torch.int32).numpy(),primary_device,)
    vm['embed'](inputs, const_params)

`

**Comment by CharlieFRuan** [comment]
Perhaps you can refer to https://github.com/mlc-ai/mlc-llm/blob/main/tests/legacy-python/dump_intermediate.py, specifically there is a method called `load_params_SLM()`

**Comment by Bobo-y** [comment]
@CharlieFRuan not work,same error
