### ISSUE TITLE
The output issues encountered when deploying on iPhone.

### ISSUE THREAD

**Issue by cvv-student** [mlc-ai/mlc-llm#172]
I successfully deployed LLM on iPhone 12 Pro without any errors, but the output results are garbled. I think it might be an issue during model quantization, but I have no experience with deploying using TVM. Where should I start to solve this problem?
![IMG_4718](https://github.com/mlc-ai/mlc-llm/assets/58026988/ad5fb0e3-49e5-40c0-9b57-39e8da0c9c2a)

**Comment by junrushao** [comment]
Should be fixed by HEAD for UTF-8 decoding, but feel free to raise new issues if it still persists.
