### ISSUE TITLE
[Question]  Getting "can't find crate" errors when running prepare_libs.sh

### ISSUE THREAD

**Issue by RageshAntonyHM** [mlc-ai/mlc-llm#1722]
## ❓ General Questions

When trying to run `sh prepare_libs.sh` for android library build phase, I am getting errors like this 

error[E0463]: can't find crate for `core`
error[E0463]: can't find crate for `compiler_builtins`

How to fix this? please help me

Build Log: 
https://gist.github.com/RageshAntonyHM/2a738efa67e2354a74be273b7957c7ba

OS:
Mac OS X 14.3 
M2 Chip

**Comment by Kartik14** [comment]
@RageshAntonyHM  Do you have rust installed using conda? If that's the case, can you try installing it using [this method](https://www.rust-lang.org/tools/install)?

**Comment by RageshAntonyHM** [comment]
I installed Rust using home brew.

May I know why dependency resolving failing even though I added them using rust add?
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Kartik14** [comment]
I am not sure, but I was getting the same error was my rust was not configured properly. For me it was conflicts with conda installation of rust (can check using `conda list | grep "rust"`. You can maybe try installing and uninstalling rust. Please refer [here](https://stackoverflow.com/a/77852953) for more details.

**Comment by RageshAntonyHM** [comment]
> I am not sure, but I was getting the same error because my rust was not configured properly. For me it was conflicts with conda installation of rust (can check using `conda list | grep "rust"`). You can maybe try uninstalling and installing rust. Please refer [here](https://stackoverflow.com/a/77852953) for more details.

I followed the SO answer you gave and it worked. Thanks. 

Is there any way to pre-download and locally host models and provide them to app instead of downloading again and again. ?

**Comment by Kartik14** [comment]
> Is there any way to pre-download and locally host models and provide them to app instead of downloading again and again. ?

you can copy the models to the phone using `adb`. Please refer here https://llm.mlc.ai/docs/deploy/android.html#incorporate-model-weights for more information.
