### ISSUE TITLE
[Question] maximizing inference speed

### ISSUE THREAD

**Issue by federicoparra** [mlc-ai/mlc-llm#1726]
## ❓ General Questions

Let's say the only thing you care about is inference speed and you are willing to sacrifice everything else: what would be the parameters to tweak in MLC to achieve this?

**Comment by shreygupta2809** [comment]
You can explore the `--tensor-parallel-shard TENSOR_PARALLEL_SHARDS` flag which should help in using multi-gpus. Tweaking `--context-window-size CONTEXT_WINDOW_SIZE ` might also help in inference speed but it may negatively impact the performance of the model (in model weight conversion and compilation [Docs](https://llm.mlc.ai/docs/compilation/compile_models.html#generate-mlc-chat-config).) There is also an option to pass an optimization flag in [mlc chat](https://github.com/mlc-ai/mlc-llm/blob/main/python/mlc_chat/chat_module.py#L184C5-L189C43), by default [O2 is already used](https://github.com/mlc-ai/mlc-llm/blob/main/python/mlc_chat/cli/chat.py#L19).
```
opt : Optional[str]
        Optimization flags. MLC LLM maintains a predefined set of optimization flags,
        denoted as O0, O1, O2, O3, where O0 means no optimization, O2 means majority of them,
        and O3 represents extreme optimization that could potentially break the system.
        Meanwhile, optimization flags could be explicitly specified via details knobs, e.g.
        --opt="cublas_gemm=1;cudagraph=0".
```

**Comment by federicoparra** [comment]
Hi, thank you. I tried using a smaller context and a smaller prefill and got some improvement but not a lot.
I should be more specific: the rate of tokens per second is very good (around 10 or more) which is perfectly fine.
The problem is the encoding time, i.e. the idle time the model spends understanding the prompt before it begins responding at the 10 tokens per second speed.
Even with very simple prompts such as "How are you?" or "Who is Barack Obama?" the model might take several seconds before the first token is generated. In the context of chatting this time is what breaks the illusion of chatting with someone that would be real (I'm using this in the context of a robot that speaks to you).
Are there steps I could take to make the initial encoding faster? I'm not referring to encoding after a few back and forth (I understand as conversation goes by there is more stuff to process), I'm referring to accelerating the very first time we call the model with a prompt - accelerating the time it takes to understand such a prompt and begin generating a response.
In my usage all prompts are short - max 20 tokens - so maybe knowing that can help you suggest an optimization or parameter?

**Comment by shifeiwen** [comment]
The slow speed of first token may need to be analyzed based on the device you are using. As far as I am concerned, when I use Android devices, the first stage of prefill is not only a memory bandwidth bottleneck, but also a computing bottleneck. Therefore, you should investigate whether the time spent by several time-consuming GEMM on your device when running prefill is normal. When judging the overall time-consuming, this is how I understand it.

**Comment by tqchen** [comment]
great discussions, closing for now as part of issue cleaning up, feel free to open new ones
