### ISSUE TITLE
[Bug] while running app

### ISSUE THREAD

**Issue by Vinaysukhesh98** [mlc-ai/mlc-llm#1739]
OpenCL build error for device=0x6fc6718ae0
                                                                                                    Error: CL_OUT_OF_HOST_MEMORY
                                                                                                    Pass

3rdparty/tvm/src/runtime/library_module.cc:78: TVMError: OpenCL build error for device=0x6fc6718ae0
                                                                                                    Error: CL_OUT_OF_HOST_MEMORY
                                                                                                    Pass

**Comment by shreygupta2809** [comment]
Referencing another issue #512, this seems to be the case due to larger memory cost of some models.
