### ISSUE TITLE
moss support

### ISSUE THREAD

**Issue by qitao052** [mlc-ai/mlc-llm#174]
I met problems when build MOSS. since the config.json of MOSS model (fnlp/moss-moon-003-sft) was changed by the developer. 

in the config.json file, several parameters are not included, like hidden_size. while these parameters are required by the get_model function from moss.py.

Does any one could help to solve this problem?

**Comment by yzh119** [comment]
Thank you for reporting this, I'll take a look.

**Comment by KPatr1ck** [comment]
> Thank you for reporting this, I'll take a look.

Waiting for moss tuning results. :)

**Comment by tqchen** [comment]
closing for now as moss was less in a demand comparing to latest models, this issue is now inactive, feel free to open new ones.
