### ISSUE TITLE
[Doc] android download link stop working after LFS was used to store the apk

### ISSUE THREAD

**Issue by asl97** [mlc-ai/mlc-llm#1740]
### Bug
- Link to the buggy documentation/tutorial: https://llm.mlc.ai/docs/deploy/android.html#demo-app
- Description of the bug: After the repo was changed to use LFS to store the apk, the link no longer start a download for the apk.

Related:
https://github.com/mlc-ai/binary-mlc-llm-libs/pull/87

**Comment by Kartik14** [comment]
Thanks for catching this. We will look into this.

**Comment by Kartik14** [comment]
#1737 should fix it for now.
