### ISSUE TITLE
[Question] How can I get "mlc_llm.dll" ?

### ISSUE THREAD

**Issue by Moon-Ahn** [mlc-ai/mlc-llm#1750]
## ❓ General Questions

RuntimeError: Cannot find libraries: mlc_llm.dll

Cannot find libraries: mlc_llm.dll error ocurred 
when I run the "pip install -e.pip install -e." command or any action related to mlc_chat.
I can't find a solution.

**Comment by Hzfengsy** [comment]
Please follow [instruction](https://llm.mlc.ai/docs/install/mlc_llm.html) to install the library

**Comment by Moon-Ahn** [comment]
@Hzfengsy 

I tried 'Step 3. Install via Python' on https://llm.mlc.ai/docs/install/mlc_llm.html .
The following error occurs when I run 'pip install -e.'

--------------------------------
(mlc-chat-venv) PS D:\test\mlc-llm\python> pip install -e .
Obtaining file:///D:/test/mlc-llm/python
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [62 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "D:\test\mlc-llm\python\setup.py", line 49, in <module>
          LIB_LIST, __version__ = get_lib_path()
                                  ^^^^^^^^^^^^^^
        File "D:\test\mlc-llm\python\setup.py", line 25, in get_lib_path
          libinfo["find_lib_path"]("mlc_llm")[0],
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "D:\test\mlc-llm\python\./mlc_chat/libinfo.py", line 69, in find_lib_path
          raise RuntimeError(message)
      RuntimeError: Cannot find libraries: mlc_llm.dll
      List of candidates:
      D:\test\mlc-llm\python\mlc_chat\mlc_llm.dll
      D:\test\mlc-llm\build\mlc_llm.dll
      D:\anaconda3\envs\mlc-chat-venv\lib\mlc_llm.dll
      D:\anaconda3\envs\mlc-chat-venv\mlc_llm.dll
      D:\anaconda3\envs\mlc-chat-venv\Library\usr\bin\mlc_llm.dll
      D:\anaconda3\envs\mlc-chat-venv\Library\bin\mlc_llm.dll
      D:\anaconda3\envs\mlc-chat-venv\Scripts\mlc_llm.dll
      D:\anaconda3\condabin\mlc_llm.dll
      C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8\bin\mlc_llm.dll
      C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8\libnvvp\mlc_llm.dll
      C:\Program Files\Common Files\Oracle\Java\javapath\mlc_llm.dll
      C:\Windows\system32\mlc_llm.dll
      C:\Windows\mlc_llm.dll
      C:\Windows\System32\Wbem\mlc_llm.dll
      C:\Windows\System32\WindowsPowerShell\v1.0\mlc_llm.dll
      C:\Windows\System32\OpenSSH\mlc_llm.dll
      C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common\mlc_llm.dll
      C:\Users\user\AppData\Local\Android\Sdk\platform-tools\mlc_llm.dll
      C:\Program Files\Git\cmd\mlc_llm.dll
      C:\Program Files\PuTTY\mlc_llm.dll
      C:\Program Files\Tesseract-OCR\mlc_llm.dll
      C:\Program Files\Microsoft SQL Server\150\Tools\Binn\mlc_llm.dll
      C:\Program Files\nodejs\mlc_llm.dll
      C:\Program Files\VanDyke Software\SecureCRT\mlc_llm.dll
      C:\Program Files\CMake\bin\mlc_llm.dll
      C:\ProgramData\chocolatey\bin\mlc_llm.dll
      C:\Program Files\Java\jdk-18.0.2\bin\mlc_llm.dll
      C:\Program Files\Java\jdk-18.0.2\bin\mlc_llm.dll
      C:\Program Files\dotnet\mlc_llm.dll
      D:\Windows Kits\10\Windows Performance Toolkit\mlc_llm.dll
      C:\Program Files\Git LFS\mlc_llm.dll
      C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR\mlc_llm.dll
      C:\Program Files\NVIDIA Corporation\Nsight Compute 2022.3.0\mlc_llm.dll
      C:\Users\user\.cargo\bin\mlc_llm.dll
      D:\flutter\bin\mlc_llm.dll
      D:\anaconda3\mlc_llm.dll
      D:\anaconda3\Library\mingw-w64\bin\mlc_llm.dll
      D:\anaconda3\Library\usr\bin\mlc_llm.dll
      D:\anaconda3\Library\bin\mlc_llm.dll
      D:\anaconda3\Scripts\mlc_llm.dll
      C:\Users\user\AppData\Local\Microsoft\WindowsApps\mlc_llm.dll
      C:\Program Files\JetBrains\PyCharm Community Edition 2023.1\bin\mlc_llm.dll
      D:\test\mlc-llm\python\mlc_llm.dll
      C:\Program Files\Java\jdk-18.0.2\bin\mlc_llm.dll
      C:\Users\user\AppData\Local\Programs\Microsoft VS Code\bin\mlc_llm.dll
      C:\Users\user\AppData\Local\Pub\Cache\bin\mlc_llm.dll
      C:\Users\user\AppData\Roaming\npm\mlc_llm.dll
      C:\tools\dart-sdk\bin\mlc_llm.dll
      D:\test\mlc-llm\python\mlc_llm.dll
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
--------------------------------

**Comment by icecoins** [comment]
same problem at pip install -e .
follow https://llm.mlc.ai/docs/install/mlc_llm.html
windows 10

**Comment by andylokandy** [comment]
Solved by copying `mlc_llm.ddl` from `site-packages\mlc_llm` to the dir where I'm gonna `pip install -e .`

**Comment by henrywang0314** [comment]
after copy dll files
this is what i get


$ pip install -e .
Obtaining file:///C:/Users/XXX/AndroidStudioProjects/mlc-MiniCPM/python
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [15 lines of output]
      WARNING:root:git describe: fatal: No names found, cannot describe anything.

      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\XXX\AndroidStudioProjects\mlc-MiniCPM\python\setup.py", line 121, in <module>
          main()
        File "C:\Users\XXX\AndroidStudioProjects\mlc-MiniCPM\python\setup.py", line 72, in main
          shutil.copy(path, os.path.join(CURRENT_DIR, "mlc_chat"))
        File "C:\Users\XXX\AppData\Local\anaconda3\envs\mlc-chat-venv\Lib\shutil.py", line 431, in copy
          copyfile(src, dst, follow_symlinks=follow_symlinks)
        File "C:\Users\XXX\AppData\Local\anaconda3\envs\mlc-chat-venv\Lib\shutil.py", line 236, in copyfile
          raise SameFileError("{!r} and {!r} are the same file".format(src, dst))
      shutil.SameFileError: 'C:\\Users\\11305064\\AndroidStudioProjects\\mlc-MiniCPM\\python\\mlc_chat\\mlc_llm.dll' and 'C:\\Users\\XXX\\AndroidStudioProjects\\mlc-MiniCPM\\python\\mlc_chat\\mlc_llm.dll' are the same file
      Use original version 0.1.dev0
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
(mlc-chat-venv)
