### ISSUE TITLE
Smudge error when downloading pre-built model binaries

### ISSUE THREAD

**Issue by vin136** [mlc-ai/mlc-llm#1754]
## 🐛 Bug

Command I run : `git clone https://github.com/mlc-ai/binary-mlc-llm-libs.git dist/prebuilt_libs`

Here's the error:
```

Receiving objects: 100% (689/689), 184.05 MiB | 25.71 MiB/s, done.
Resolving deltas: 100% (495/495), done.
Updating files: 100% (197/197), done.
Downloading mlc-chat.apk (124 MB)
Error downloading object: mlc-chat.apk (b7b937c): Smudge error: Error downloading mlc-chat.apk (b7b937c7be3b7e5f8164f0f1ef58c9e1df15fd0f08721fbf7fe16d058ef09c6e): batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.
```

## To Reproduce

conda create --name mlc-llm python=3.10
conda activate mlc-llm
conda install git git-lfs
git lfs install
git clone https://github.com/mlc-ai/binary-mlc-llm-libs.git dist/prebuilt_libs

## Note

I thought it might just be git-lfs error put upon googling I realized it might be that there are limits in terms of the data-storage on GitHub and it needs to be upgraded. Thus sharing it here.

**Comment by Kartik14** [comment]
@vin136 Recently added the `mlc-chat.apk` to LFS because of size issues. Will remove it for now and keep it as a [github release](https://github.com/mlc-ai/binary-mlc-llm-libs/releases/tag/Android) instead. Should fix this for now
