### ISSUE TITLE
[Model Request] openbmb/MiniCPM-V

### ISSUE THREAD

**Issue by Vinaysukhesh98** [mlc-ai/mlc-llm#1765]
## ⚙️  Request New Models

- Link to an existing implementation (e.g. Hugging Face/Github): 
- Is this model architecture supported by MLC-LLM? (the list of [supported models](https://llm.mlc.ai/docs/prebuilt_models.html)) No
- https://huggingface.co/openbmb/MiniCPM-V

## Additional context

https://llm.mlc.ai/docs/prebuilt_models.html
found below resources:
https://github.com/OpenBMB/mlc-MiniCPM/tree/main

**Comment by WangFengtu1996** [comment]
version 2 / 2.5 support?

**Comment by mos-fine** [comment]
yes we need this model

**Comment by Nikhil34712** [comment]
hey @mos-fine  how to use Minicpm-v model in mlc_llm are they supporting this??

**Comment by Nikhil34712** [comment]
> version 2 / 2.5 support?

hey @WangFengtu1996  is mlc_llm suporting minicpm-v or are there any vision llms that supports mlc_llm??

**Comment by mos-fine** [comment]
Yes, I can make mlc_llm support minicpm and minicpm-v, but I modified the script according to the official documentation.

**Comment by mos-fine** [comment]
Well, it works normally. I modified their mcl_llm toolkit. I can send you the kit if you want.

**Comment by Nikhil34712** [comment]
@mos-fine  it would be great help for me if you send that

**Comment by Nikhil34712** [comment]
Hello @mos-fine  did you follow these steps or any other sorce you have??     https://github.com/OpenBMB/mlc-MiniCPM

**Comment by mos-fine** [comment]
Yes, but instead of following their steps, I followed their source code to make changes to the mlc_llm tool

**Comment by Nikhil34712** [comment]
@mos-fine  I don’t know how I can get to know about those changes. By any chance can you share those changes. It will be so much of help.

**Comment by mos-fine** [comment]
It works, I'll try to put the modified mlc_llm into my project, it may take a little while. Note that they are adapted to cu122 and cp310 linux systems

**Comment by Nikhil34712** [comment]
Thank you @mos-fine  if you completed  modifying please let me know. I’ll be waiting. Thank you

**Comment by tqchen** [comment]
@mos-fine contribution is more than welcomed!

**Comment by mos-fine** [comment]
If you want to know how to modify the code inside, feel free to communicate with me. My company is trying to launch a private app model product that builds large models into the app and combines it with rag to understand users. @Nikhil34712

**Comment by Nikhil34712** [comment]
Hey @mos-fine i have located the files so those files are not opening so can you tell me how to view it ??

**Comment by mos-fine** [comment]
You can download those tools and unzip them to view them. If you want to know where I have changed specifically, you can take a look at my project [mlc_llm_Modify](https://github.com/mos-fine/mlc_llm_Modify ) @Nikhil34712

**Comment by Nikhil34712** [comment]
yeah i have downloaded and unzipped  thank you @mos-fine  so as per the minicpm documentaion we have to create environment and we have to compile right?? so where did you modified like in creating environment or setting paths ?

**Comment by mos-fine** [comment]
There are two packages in hugging: mlc_llm_nightly_cu122-0.1.dev1352-cp310-cp310-manylinux_2_28_x86_64.whl and mlc_ai_nightly_cu122-0.15.dev404-cp310-cp310-manylinux_2_28_x86_64.whl. 

You can download them directly. After they get to your server, in cu122 and pip install them in the cp310 environment, and then you can use mlc_llm directly in the environment.

 For example, you can directly use commands such as mlc_llm gen_config and mlc_llm convert_weight to change the minicpm and minicpm_v models. @Nikhil34712

**Comment by mos-fine** [comment]
If you don’t want to know what code has been modified, you can download it and pip install it to the server and use the mlc_llm tool directly.There is no need to adjust the environment according to the minicpm documentaion.

**Comment by mos-fine** [comment]
I don't know if I made it clear😂😂

**Comment by Nikhil34712** [comment]
I will check and confirm with you tomorrow yes for your side you made it
clear I have to try it from my side

**Comment by tqchen** [comment]
thanks @mos-fine  do you mind send s pull request to add the support officially ? would be good to see the diff

**Comment by Single430** [comment]
@mos-fine 非常棒的工作！

**Comment by Vinaysukhesh98** [comment]
hi @mos-fine  do you support phi-3 vision model?

**Comment by Nikhil34712** [comment]
Hey @mos-fine  in extracted_Whl file i have three files  : mlc_ai_nightly_cu122.libs,  mlc_ai_nightly_cu122-0.15.dev404.dist-info, and tvm  i extracted and installed them in wsl environment  next i directly use the commands its not working

**Comment by Single430** [comment]
> Hey @mos-fine  in extracted_Whl file i have three files  : mlc_ai_nightly_cu122.libs,  mlc_ai_nightly_cu122-0.15.dev404.dist-info, and tvm  i extracted and installed them in wsl environment  next i directly use the commands its not working 
> 
> 

search mlc-minicpm，这是面壁官方改的

**Comment by AkulRT** [comment]
Hey @mos-fine I followed your instructions, used the toolkit and tried to convert the weights for MiniCPM-V-2. This is facing an error where a file within can't recognize the name TVM. I'm not entirely sure why this is happening given that the same files uses tvm in earlier lines. I was wondering if you've had any luck converting V-2 or if MiniCPM-V is all you converted. I will also try MiniCPM-V and see if that works. This is a SS of the error:

![image](https://github.com/mlc-ai/mlc-llm/assets/170328789/0b5b49b5-a614-4d00-9414-90496bfb85d6)

**Comment by Single430** [comment]
> Hey @mos-fine I followed your instructions, used the toolkit and tried to convert the weights for MiniCPM-V-2. This is facing an error where a file within can't recognize the name TVM. I'm not entirely sure why this is happening given that the same files uses tvm in earlier lines. I was wondering if you've had any luck converting V-2 or if MiniCPM-V is all you converted. I will also try MiniCPM-V and see if that works. This is a SS of the error:
> 
> 
> 
> ![image](https://github.com/mlc-ai/mlc-llm/assets/170328789/0b5b49b5-a614-4d00-9414-90496bfb85d6)
> 
> 

你可以先测试tvm是否安装成功，测试命令
｀
>>> python -c "import tvm; print(tvm.__file__)"
/some-path/lib/python3.11/site-packages/tvm/__init__.py
｀
如果有问题，可以直接安装如下

https://github.com/apache/tvm

**Comment by AkulRT** [comment]
@Single430 thank you for the reply!

![image](https://github.com/mlc-ai/mlc-llm/assets/170328789/ddce5a61-d8c1-4f71-877a-63b8c958b740)

This is the weird thing. TVM checks as per the documentation all show outputs that match it.

**Comment by aiakubovich** [comment]
> If you want to know how to modify the code inside, feel free to communicate with me. My company is trying to launch a private app model product that builds large models into the app and combines it with rag to understand users. @Nikhil34712

Hi @mos-fine , do you have any plans to share you RAG implementation?

**Comment by MasterJH5574** [comment]
Minicpm series are supported by #2755, #2808, #2815.

**Comment by AnyangAngus** [comment]
> Minicpm series are supported by #2755, #2808, #2815.

cool!
 And how about Minicpm-v? any plan?

**Comment by tqchen** [comment]
cc @tlopex on minicpm-v

**Comment by tlopex** [comment]
@tqchen  Got that! Now under the learning of its code, trying to support that in a few weeks.
