### ISSUE TITLE
Incorrect link for mlc chat download for Android

### ISSUE THREAD

**Issue by BlindDeveloper** [mlc-ai/mlc-llm#1773]
Hello, then i open
https://llm.mlc.ai/docs/index.html#getting-started
And press Android and after press on link i be rederected to unexisting github page.
Also in your homepage in copyright is last 2023 year.
Thamks!

**Comment by Kartik14** [comment]
@BlindDeveloper Do you mean the download link for the apk? I am able to download it on my end. Can you please check the downloads because it starts automatically in the background

**Comment by BlindDeveloper** [comment]
If i click on download browser open link
https://github.com/mlc-ai/binary-mlc-llm-libs/raw/main/mlc-chat.apk

**Comment by Kartik14** [comment]
This is not the correct link, it was recently updated to https://github.com/mlc-ai/binary-mlc-llm-libs/releases/download/Android/mlc-chat.apk . Please use this.
