### ISSUE TITLE
Closing if start chating


### ISSUE THREAD

**Issue by BlindDeveloper** [mlc-ai/mlc-llm#1777]
Device: Samsung Galaxy a34 5g 6 GB ram
OS version: Android 14 

Steps to reproduce:
1. Enable Talkback.
2. Enable ram plus 6 GB, and restart phone
.
3  download Mlc Chat from here: https://github.com/mlc-ai/binary-mlc-llm-libs/releases/download/Android/mlc-chat.apk
 And install it.
3. Download Llama and Mistral.
4. Start chating.

If select start chating with Llama or Mistral Llm Chat closing and Talkback restarting.
If i start chating with Redpajama or Phi all working correctly.
Thanks.

**Comment by Hzfengsy** [comment]
6GB RAM is not enough for 7B models. Since we use GPU memory, I don't think a disk swap would help
