### ISSUE TITLE
[Question]  error: typedef redefinition with different types ('struct cpu_set_t' vs 'struct cpu_set_t')

### ISSUE THREAD

**Issue by Moon-Ahn** [mlc-ai/mlc-llm#1783]
## ❓ General Questions

 error: typedef redefinition with different types ('struct cpu_set_t' vs 'struct cpu_set_t')
 
 Running './prepare_libs.sh' causes the above error and does not proceed. Why does this issue occur?

Below is the log of the error.

-----------------------------------------------------------------

[ 35%] Generating CMakeFiles/tvm4j_core.dir/java_class_filelist
[ 35%] Creating Java archive tvm4j_core.jar
[ 35%] Built target tvm4j_core
[ 35%] Building CXX object mlc_llm/CMakeFiles/mlc_llm_objs.dir/cpp/conv_templates.cc.o
[ 35%] Building CXX object mlc_llm/CMakeFiles/mlc_llm_objs.dir/cpp/conversation.cc.o
[ 35%] Building CXX object mlc_llm/CMakeFiles/mlc_llm_objs.dir/cpp/image_embed.cc.o
[ 35%] Building CXX object mlc_llm/CMakeFiles/mlc_llm_objs.dir/cpp/llm_chat.cc.o
[ 35%] Building CXX object mlc_llm/CMakeFiles/mlc_llm_objs.dir/cpp/loader/multi_gpu_loader.cc.o
[ 35%] Building CXX object mlc_llm/CMakeFiles/mlc_llm_objs.dir/cpp/metadata/model.cc.o
[ 35%] Building CXX object mlc_llm/CMakeFiles/mlc_llm_objs.dir/cpp/serve/async_threaded_engine.cc.o
[ 42%] Building CXX object mlc_llm/CMakeFiles/mlc_llm_objs.dir/cpp/serve/config.cc.o
[ 42%] Building CXX object mlc_llm/CMakeFiles/mlc_llm_objs.dir/cpp/serve/data.cc.o
[ 42%] Building CXX object mlc_llm/CMakeFiles/mlc_llm_objs.dir/cpp/serve/encoding.cc.o
[ 42%] Building CXX object mlc_llm/CMakeFiles/mlc_llm_objs.dir/cpp/serve/engine.cc.o
[ 42%] Building CXX object mlc_llm/CMakeFiles/mlc_llm_objs.dir/cpp/serve/engine_actions/action.cc.o
[ 42%] Building CXX object mlc_llm/CMakeFiles/mlc_llm_objs.dir/cpp/serve/engine_actions/action_commons.cc.o
[ 42%] Building CXX object mlc_llm/CMakeFiles/mlc_llm_objs.dir/cpp/serve/engine_actions/batch_decode.cc.o
[ 42%] Building CXX object mlc_llm/CMakeFiles/mlc_llm_objs.dir/cpp/serve/engine_actions/batch_draft.cc.o
[ 42%] Building CXX object mlc_llm/CMakeFiles/mlc_llm_objs.dir/cpp/serve/engine_actions/batch_verify.cc.o
In file included from /mnt/f/mlc-llm/cpp/serve/engine_actions/batch_verify.cc:11:
In file included from /mnt/f/mlc-llm/cpp/serve/engine_actions/../../random.h:10:
In file included from /mnt/d/Android_sdk/ndk/android-ndk-r21b/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/c++/v1/random:1645:
In file included from /mnt/d/Android_sdk/ndk/android-ndk-r21b/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/c++/v1/istream:163:
In file included from /mnt/d/Android_sdk/ndk/android-ndk-r21b/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/c++/v1/ostream:138:
In file included from /mnt/d/Android_sdk/ndk/android-ndk-r21b/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/c++/v1/ios:215:
In file included from /mnt/d/Android_sdk/ndk/android-ndk-r21b/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/c++/v1/__locale:17:
In file included from /mnt/d/Android_sdk/ndk/android-ndk-r21b/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/c++/v1/mutex:190:
In file included from /mnt/d/Android_sdk/ndk/android-ndk-r21b/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/c++/v1/__mutex_base:16:
In file included from /mnt/d/Android_sdk/ndk/android-ndk-r21b/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/c++/v1/__threading_support:27:
In file included from /mnt/d/Android_sdk/ndk/android-ndk-r21b/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/pthread.h:34:
/mnt/d/Android_sdk/ndk/android-ndk-r21b/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/sched.h:87:3: error: typedef redefinition with different types ('struct cpu_set_t' vs 'struct cpu_set_t')
} cpu_set_t;
  ^
/mnt/f/mlc-llm/3rdparty/tvm/include/tvm/runtime/threading_backend.h:41:3: note: previous definition is here
} cpu_set_t;
  ^
1 error generated.
make[3]: *** [mlc_llm/CMakeFiles/mlc_llm_objs.dir/build.make:286: mlc_llm/CMakeFiles/mlc_llm_objs.dir/cpp/serve/engine_actions/batch_verify.cc.o] Error 1
make[2]: *** [CMakeFiles/Makefile2:290: mlc_llm/CMakeFiles/mlc_llm_objs.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:271: CMakeFiles/tvm4j_runtime_packed.dir/rule] Error 2
make: *** [Makefile:203: tvm4j_runtime_packed] Error 2

**Comment by Moon-Ahn** [comment]
I've solved it.

The cpu_set_t structure of the file **'sched.h'** in the path **'/linux-x86_64/sysroot/usr/include'** of Android ndk was changed to another name.

May be, this is an error that occurs when andriod ndk in linux is updated.

I hope it helps others. Thank you.

**Comment by Moon-Ahn** [comment]
I changed cpu_set_t on path './Android_sdk/ndk/android-ndk-r21b/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/sched.h' to cpu_set_e and now the following error occurs.


----------------------------------

mlc_llm/tvm/CMakeFiles/tvm_runtime_objs.dir/src/runtime/threading_backend.cc.o
/mnt/f/mlc-llm/3rdparty/tvm/src/runtime/threading_backend.cc:167:5: error: unknown type name 'cpu_set_t'; did you mean 'cpu_set_e'?
    cpu_set_t cpuset;
    ^~~~~~~~~
    cpu_set_e
/mnt/d/Android_sdk/ndk/android-ndk-r21b/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/sched.h:87:3: note: 'cpu_set_e' declared here
} cpu_set_e;
  ^
/mnt/f/mlc-llm/3rdparty/tvm/src/runtime/threading_backend.cc:183:39: error: unknown type name 'cpu_set_t'; did you mean 'cpu_set_e'?
    if (sched_setaffinity(tid, sizeof(cpu_set_t), &cpuset) != 0) {
                                      ^~~~~~~~~
                                      cpu_set_e
/mnt/d/Android_sdk/ndk/android-ndk-r21b/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/sched.h:87:3: note: 'cpu_set_e' declared here
} cpu_set_e;

**Comment by Hzfengsy** [comment]
Not sure of the reason, but could you please try a newer ndk, e.g., `android-ndk-r26b`?

**Comment by Moon-Ahn** [comment]
@Hzfengsy Thank you, and that was helpful.
