### ISSUE TITLE
[Question] Weight shape mismatch when compiling Llama-2-7b-chat-hf

### ISSUE THREAD

**Issue by calebtung** [mlc-ai/mlc-llm#1797]
## ❓ Weight shape mismatch when compiling Llama-2-7b-chat-hf

I finetuned a Llama-2-7b-chat-hf model from Meta's official Huggingface implementation.
However, I get a size mismatch when I attempt to compile both the normal model and my finetuned model with MLC chat.

**Steps to reproduce:**

In Python, do the following:

```python
import torch
from transformers import AutoModelForCausalLM, AutoTokenizer, BitsAndBytesConfig, TrainingArguments, GenerationConfig
from transformers.models.llama.modeling_llama import LlamaForCausalLM

quantization_config = BitsAndBytesConfig(
        load_in_4bit=True,
        bnb_4bit_compute_dtype=torch.float16,
        bnb_4bit_quant_type="nf4",
        bnb_4bit_use_double_quant=True
        )
model: LlamaForCausalLM = AutoModelForCausalLM.from_pretrained(
        pretrained_model_name_or_path="meta-llama/Llama-2-7b-chat-hf",
        quantization_config=quantization_config,
        device_map={"": 0}
        )

model.config.use_cache = False

model.save_pretrained("normal_llama2")

# Perform some finetuning on model here...

model.save_pretrained("finetuned_llama2")
```

Then, both of the following commands fail (MLC Chat version 0.1.dev0 pip installed). Even the normal, not-yet finetuned Llama2 cannot be compiled:

```bash
mlc_chat convert_weight normal_llama2/ --quantization q4f16_1 -o mlc_normal_out # Fails

mlc_chat convert_weight finetuned_llama2/ --quantization q4f16_1 -o mlc_finetuned_out # Fails
``` 

The error in both cases is:
```
File "/home/caleb/anaconda3/envs/mlc/lib/python3.11/site-packages/mlc_chat/interface/convert_weight.py", line 102, in _check_param
    raise ValueError(
ValueError: Parameter model.layers.0.mlp.down_proj.q_weight has shape (22544384, 4), but expected [4096, 1376]
```

The sizes are mismatched; do you know what I should change to make compilation succeed?

Thank you!

**Comment by Hzfengsy** [comment]
We do not support pre-quant models. 

We would quantize with our method, within command `mlc_chat convert_weight normal_llama2/ --quantization q4f16_1 -o mlc_normal_out`

**Comment by gatepoet** [comment]
Below is roughly the process I use. From how I read your question you should be good to go if you just reload your model w/o BnB quant, apply the LoRA adapter, and then save the merged model.

1. Train
  1.1 Load model in 4 bit using BnB
  1.2 Fine-tune LoRA adapter using PEFT
  1.3 Save LoRA adapter model
2. Merge
  2.1 (Re-)Load model _normally_ (without BnB quant)
  2.2 Load and apply LoRA
  2.3 Save merged model
3. Optimize with MLC
  3.1 Convert weights _for the merged model_
  3.2 Generate config
  3.3 Compile model

**Comment by calebtung** [comment]
Thanks @gatepoet this looked like it worked!
