### ISSUE TITLE
Consider supporting 8bit quantization

### ISSUE THREAD

**Issue by emvw7yf** [mlc-ai/mlc-llm#18]
Based on experimenting with GPTQ-for-LLaMa, int4 quantization seems to introduce 3-5% drop in perplexity, while int8 is almost identical to fp16. Would it be possible to use int8 quantization with mlc-llm, assuming the model fits in VRAM in int8?

**Comment by Kathryn-cat** [comment]
Hi, int8 quantization is now supported here https://github.com/mlc-ai/mlc-llm/blob/main/mlc_llm/utils.py#L44-L49
