### ISSUE TITLE
[Question] performance optimization

### ISSUE THREAD

**Issue by MuYu-zhi** [mlc-ai/mlc-llm#1800]
## ❓ General Questions

- Does the defalut implementation in master branch include any performance tuning by autotvm or auto-scheduler?

- Any other advices for performance optimization？

**Comment by Hzfengsy** [comment]
We tried auto-tuning at the very initial version, but we focus on DLight and attention kernels. As the current auto-tuning rules do not suit LLM cases.

**Comment by MuYu-zhi** [comment]
any further plan for support this?

**Comment by Hzfengsy** [comment]
No evidence shows that auto-tuning will improve the perf. We deprecate it due to unsatisfied performance

**Comment by MuYu-zhi** [comment]
Why no performance improvement by auto-tuning, in my experiments for non-llm model, there is improvement observed by autoTVM tunning. Anything different?

Besides, I also have some questions about TVM. Currently, does the tuning primarily focus on the scheduling strategy of kernels?  Are there optimizations at the graph level, such as memory reuse, thread allocation and scheduling, supported in TVM? Are these strategies supported in the tuning process?

thanks.
