### ISSUE TITLE
[Model Request] Google Gemma 2B/7B

### ISSUE THREAD

**Issue by dusty-nv** [mlc-ai/mlc-llm#1802]
## ⚙️  Request New Models

- Link to an existing implementation (e.g. Hugging Face/Github): 
    * https://huggingface.co/google/gemma-2b
    * https://huggingface.co/google/gemma-7b
- Is this model architecture supported by MLC-LLM? (the list of [supported models](https://llm.mlc.ai/docs/prebuilt_models.html))    NO

## Additional context

Google has release a new series of models, which are purportedly ['better than llama-2-7b'](https://www.reddit.com/r/LocalLLaMA/comments/1awbo84/google_publishes_open_source_2b_and_7b_model/):

https://blog.google/technology/developers/gemma-open-models/

Given MLC's support for edge devices and that this includes a 2B SLM, I thought Gemma good to get on your radar awhile.  llama.cpp already had support for it added this morning (https://github.com/ggerganov/llama.cpp/pull/5631)

**Comment by tqchen** [comment]
https://github.com/mlc-ai/mlc-llm/pull/1805
