### ISSUE TITLE
[Question] other linker flags in Xcode IOS

### ISSUE THREAD

**Issue by Gustavclausen1804** [mlc-ai/mlc-llm#1803]
## ❓ General Questions

First of all, thank you the amazing work. 

The **-all_load flag** which is currently specified in "other linker flags" in my Xcode project is causing a "duplicate symbol error" since I'm using another library which has a binary which has a function named the same, and that is being loaded due to the -all_load flag, I wonder if someone can help me specify the actual files needed, so I can use -force_load instead of using -all_load flag which affects my whole project?

**Comment by tqchen** [comment]
```
-Wl,-all_load
-lmodel_iphone
-lmlc_llm -ltvm_runtime
-ltokenizers_cpp
-lsentencepiece
-ltokenizers_c
```

the above files corresponds to the files, each to one .a file

**Comment by tqchen** [comment]
Some of the functions uses reverse registration mechanism, which requires all load to function properly, likely you can avoid other parts, and focus on `-lmodel_iphone -lmlc_llm -ltvm_runtime`

**Comment by MasterJH5574** [comment]
Close the issue for now. You're welcome to reopen it or open a new one if there are further questions.
