### ISSUE TITLE
[Bug][Android] duplicate symbol when building Android libs with more than 1 models of the same type and quantization

### ISSUE THREAD

**Issue by sbwww** [mlc-ai/mlc-llm#1810]
## 🐛 Bug

Building Android libs with more than 1 models of the same type and quantization results in linking error.
I can  build Android libs with **1 Llama model successfully**, but **fail with 2 different Llama models**. It seems that **different models with same type `llama` and quantization `q4f16_1`** are all compiled into `llama_q4f16_1_xxx`.
Is there a way to distinguish them by name? I don't know whether we can reuse the lib as the model size are different.

Error:
```
...
[100%] Built target tokenizers_c
[100%] Building CXX object mlc_llm/tokenizers/CMakeFiles/tokenizer_cpp_objs.dir/src/sentencepiece_tokenizer.cc.o
[100%] Building CXX object mlc_llm/tokenizers/CMakeFiles/tokenizer_cpp_objs.dir/src/huggingface_tokenizer.cc.o
[100%] Building CXX object mlc_llm/tokenizers/CMakeFiles/tokenizer_cpp_objs.dir/src/rwkv_world_tokenizer.cc.o
[100%] Built target tokenizer_cpp_objs
[100%] Linking CXX static library libtokenizers_cpp.a
[100%] Built target tokenizers_cpp
[100%] Linking CXX static library libmlc_llm.a
[100%] Built target mlc_llm_static
[100%] Building CXX object CMakeFiles/tvm4j_runtime_packed.dir/xxx/mlc-llm/3rdparty/tvm/jvm/native/src/main/native/org_apache_tvm_native_c_api.cc.o
[100%] Linking CXX shared library libtvm4j_runtime_packed.so
ld: error: duplicate symbol: llama_q4f16_1___tvm_dev_mblob
>>> defined at llama_q4f16_1_devc
>>>            llama_q4f16_1_devc.o:(llama_q4f16_1___tvm_dev_mblob) in archive model_lib/libmodel_android.a
>>> defined at llama_q4f16_1_devc
>>>            llama_q4f16_1_devc.o:(.rodata+0x0) in archive model_lib/libmodel_android.a

ld: error: duplicate symbol: llama_q4f16_1_batch_decode_paged_kv
>>> defined at main.tir:0
>>>            lib0.o:(llama_q4f16_1_batch_decode_paged_kv) in archive model_lib/libmodel_android.a
>>> defined at main.tir:0
>>>            lib0.o:(.text+0x0) in archive model_lib/libmodel_android.a
...
```

app-config:
```
"model_list": [
      {
        "model_url": "",
        "model_id": "myllama-v1-q4f16_1",
        "model_lib": "llama-q4f16_1"
      },
      {
        "model_url": "",
        "model_id": "myllama-v2-q4f16_1",
        "model_lib": "llama-q4f16_1"
      }
  ],
```

## To Reproduce

1. compile multiple Llama models with different size following `docs/deploy/android.rst`
2. modify `assets/app-config.json`
3. run `bash prepare_libs.sh` in `andorid/librarys`

## Environment

 - Platform **Android**
 - Operating system **Ubuntu**
 - Device N/A
 - How you installed MLC-LLM **`conda`**
 - How you installed TVM-Unity **`pip`**
 - Python version (e.g. 3.10): **3.10**
 - GPU driver version (if applicable): N/A
 - CUDA/cuDNN version (if applicable): N/A
 - TVM Unity Hash Tag **484d42526a9992c372d1687ff68a86bda0d1c238**
 - Any other relevant information:

## Additional context

Related https://github.com/mlc-ai/mlc-llm/issues/1517#issuecomment-1872663867

**Comment by Hzfengsy** [comment]
Please change the ` --system-lib-prefix` when compiling models :)
