### ISSUE TITLE
error: linking with `link.exe` failed: exit code: 1

### ISSUE THREAD

**Issue by sjtu-scx** [mlc-ai/mlc-llm#1811]
## 🐛 Bug
I am trying to deploy android side LLM under windows. when i run` . /prepare_libs.sh`, it comes up with error: linking with`link.exe failed: exit code: 1`. My mingw is x86_64-8.1.0-release-win32-seh-rt_v6-rev0 and it's not clear what's wrong!
![image](https://github.com/mlc-ai/mlc-llm/assets/74237729/c505d8e4-c1fa-4778-b2eb-1e1059828b7b)

**Comment by DiegoCao** [comment]
Could you provide more envs on the issue? I tried on my windows and didn't encounter the error

**Comment by sjtu-scx** [comment]
> Could you provide more envs on the issue?
> 
> I tried on my windows (mingw) and didn't encounter the error

I have solved it,thanks!
