### ISSUE TITLE
性能优化[Question] 

### ISSUE THREAD

**Issue by XJY990705** [mlc-ai/mlc-llm#1821]
## ❓ General Questions

如果想进行算子层面的定制化优化，有没有可能在mlc-llm上实现呢？目前有一个比较不成熟的想法，发现这里 https://github.com/mlc-ai/mlc-llm/blob/main/mlc_llm/dispatch/llama/main.py 有将算子替换成更优的算子的列表，有没有可能针对另外的模型也手写一个这样的算子替换进行优化？另外mlc-llm的内存优化在哪里进行实现呢？目前我已经看到有添加新模型的教程，那么有没有在mlc-llm上进行定制化优化的教程？
目前对mlc-llm的项目了解还比较少，如果您能抽空回答我的问题，非常感谢！

**Comment by Hzfengsy** [comment]
Kernel dispatch has been depreciated. Please see the optimization pipeline:

https://github.com/mlc-ai/mlc-llm/blob/43d38eeca5102865b860c8d248a73a6ef61d9beb/python/mlc_chat/compiler_pass/pipeline.py#L86-L154

**Comment by XJY990705** [comment]
感谢！！
