### ISSUE TITLE
[Question] When using the MLC to infer the QWEN2 model, the memory usage is much higher than when using Transformers

### ISSUE THREAD

**Issue by MingkangW** [mlc-ai/mlc-llm#1824]
## ❓ General Questions

I downloaded and compiled the model using the following command:
```
git clone https://huggingface.co/Qwen/Qwen1.5-4B-Chat
python -m mlc_chat convert_weight ./Qwen1.5-4B-Chat --quantization q4f32_1 -o ./Qwen1.5-4B-Chat-MLC
python -m mlc_chat gen_config ./Qwen1.5-4B-Chat --quantization q4f32_1 --conv-tempate chatml -o ./Qwen1.5-4B-Chat-MLC
python -m mlc_chat compile ./Qwen1.5-4B-Chat --device cuda -o ./Qwen1.5-4B-Chat-MLC-cuda.so
```
When running the model with `max_position_embeddings=32768`, MLC requires approximately 199444.85 MB of memory, while using the unquantized model with Transformers only requires around 10GB of memory. Why is the difference so significant?
```
[2024-02-23 15:45:00] INFO model_metadata.py:95: Total memory usage: 199444.85 MB (Parameters: 2356.26 MB. KVCache: 25600.00 MB. Temporary buffer: 171488.59 MB)
```

**Comment by na20215** [comment]
Check the mlc-config file because the config file of Qwen does not define the context_window_size, and this value in the mlc-config file is set to a huge number. It causes the KV cache to require a huge amount of memory. Manually reducing the context_window_size value in the generated mlc config file can solve the issue. For example, change it to 4096 or 768.

**Comment by MasterJH5574** [comment]
Hi @MingkangW, thanks for the question! I think what @na20215 suggested can address your issue. On the other hand, right now we are switching the attention implementation of the models from naive attention computation to [FlashInfer](http://github.com/flashinfer-ai/flashinfer). The switch of Qwen model is still in progress. After the switch, the memory consumption will be much less.

**Comment by MasterJH5574** [comment]
Gonna close the issue for now. You're welcome to reopen it or open a new one if there are further questions :-)
