### ISSUE TITLE
[Question] Link to download Llm Chat Apk with Google Gemma support

### ISSUE THREAD

**Issue by BlindDeveloper** [mlc-ai/mlc-llm#1825]
Hello, add link for download  Llm Chat Apk With Google Gemma 2b and 7b models
Thanks!.

**Comment by Hzfengsy** [comment]
You could compile it by yourself :)  https://llm.mlc.ai/docs/deploy/android.html

**Comment by BlindDeveloper** [comment]
@Hzfengsy 
Hello! I don't have that option at the moment.  Gemma has already been added to the project.  on the website
https://llm.mlc.ai/docs/index.html#getting-started
 there is a Android version without Google Gemma .

**Comment by Kartik14** [comment]
Hi, Gemma is already supported in the prebuilt apk

**Comment by BlindDeveloper** [comment]
@Kartik14
I can't find download link.

**Comment by Kartik14** [comment]
You can find the download link here(click the "Download  Android apk" icon
https://llm.mlc.ai/docs/deploy/android.html. The direct download link is
here
https://github.com/mlc-ai/binary-mlc-llm-libs/releases/download/Android/mlc-chat.apk
