### ISSUE TITLE
[Bug]  tir_paged_kv_cache  and flashinfer_paged_kv_cache  not support  model for head size 100

### ISSUE THREAD

**Issue by jpf888** [mlc-ai/mlc-llm#1826]
## To Reproduce

1. use a  open llama 3B Model
2. quant、complier 、 run
3.  following error 

## Expected behavior

open-llama-3B has hiddensize 3200, num_attention_heads=32, so the head size is 100, and this error will be reported. 

The reason may be if it is q4f16, create_tir_paged_kv_cache will be performed, and the head size 100 of TIRPagedKVCache _attention_decode is not supported, and flashinfer_paged_kv_cache is also error。 

Now the means of optimizing kv cache cannot be used. Please give me some suggestions.

## Environment
NV_LIBCUBLAS_VERSION=11.5.2.43-1
NVIDIA_VISIBLE_DEVICES=all
NV_NVML_DEV_VERSION=11.4.43-1
NV_LIBNCCL_DEV_PACKAGE=libnccl-dev=2.11.4-1+cuda11.4
CONDA_EXE=/opt/conda/bin/conda
_CE_M=
NV_LIBNCCL_DEV_PACKAGE_VERSION=2.11.4-1
PLATFORM=gpu
HOSTNAME=tegra-ubuntu
NVIDIA_REQUIRE_CUDA=cuda>=11.4
NV_LIBCUBLAS_DEV_PACKAGE=libcublas-dev-11-4=11.5.2.43-1
NV_NVTX_VERSION=11.4.43-1
NV_CUDA_CUDART_DEV_VERSION=11.4.43-1
NV_LIBCUSPARSE_VERSION=11.6.0.43-1
NV_LIBNPP_VERSION=11.4.0.33-1
NCCL_VERSION=2.11.4-1

 - Any other relevant information:

## Additional context
1、flashinfer_paged_kv_cache

`Traceback (most recent call last):
  File "/workspace/mount_orin/mlc-llm-llava/mlc-llm/examples/python/sample_mlc_chat_llava.py", line 28, in <module>
    output = cm.generate(
             ^^^^^^^^^^^^
  File "/workspace/mount_orin/mlc-llm-llava/mlc-llm/python/mlc_chat/chat_module.py", line 849, in generate
    self._prefill(prompt, generation_config=generation_config, **kwargs)
  File "/workspace/mount_orin/mlc-llm-llava/mlc-llm/python/mlc_chat/chat_module.py", line 1085, in _prefill
    self._prefill_func(
  File "/workspace/tvm-unity-env/tvm-unity/python/tvm/_ffi/_ctypes/packed_func.py", line 239, in __call__
    raise_last_ffi_error()
  File "/workspace/tvm-unity-env/tvm-unity/python/tvm/_ffi/base.py", line 481, in raise_last_ffi_error
    raise py_err
  File "/workspace/mount_orin/mlc-llm-llava/mlc-llm/cpp/llm_chat.cc", line 1689, in mlc::llm::LLMChatModule::GetFunction(tvm::runtime::String const&, tvm::runtime::ObjectPtr<tvm::runtime::Object> const&)::{lambda(tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*)#5}::operator()(tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*) const
    GetChat()->PrefillStep(args[0], true, args[1], place_in_prompt, args[3], args[4]);
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/mount_orin/mlc-llm-llava/mlc-llm/cpp/llm_chat.cc", line 937, in mlc::llm::LLMChat::PrefillStep(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool, bool, mlc::llm::PlaceInPrompt, tvm::runtime::String, tvm::runtime::NDArray)
    logits_on_device = this->ForwardTokens(chunk, new_seq_len, pixel_values);
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/mount_orin/mlc-llm-llava/mlc-llm/cpp/llm_chat.cc", line 1343, in mlc::llm::LLMChat::ForwardTokens(std::vector<int, std::allocator<int> >, long, tvm::runtime::NDArray)
    ret = ft_.prefill_func_(embed, kv_cache_, params_);
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/tvm-unity-env/tvm-unity/src/runtime/relax_vm/vm.cc", line 935, in operator()
    self->InvokeClosurePacked(clo, args, rv);
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/tvm-unity-env/tvm-unity/src/runtime/relax_vm/vm.cc", line 529, in tvm::runtime::relax_vm::VirtualMachineImpl::InvokeClosurePacked(tvm::runtime::ObjectRef const&, tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*)
    clo->impl.CallPacked(TVMArgs(values.data(), tcodes.data(), args.size() + 1), rv);
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/tvm-unity-env/tvm-unity/src/runtime/relax_vm/vm.cc", line 603, in operator()
    *rv = static_cast<VirtualMachineImpl*>(ctx_ptr)->InvokeBytecode(gf_idx, inputs);
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/tvm-unity-env/tvm-unity/src/runtime/relax_vm/vm.cc", line 660, in tvm::runtime::relax_vm::VirtualMachineImpl::InvokeBytecode(long, std::vector<tvm::runtime::TVMRetValue, std::allocator<tvm::runtime::TVMRetValue> > const&)
    RunLoop();
               
  File "/workspace/tvm-unity-env/tvm-unity/src/runtime/relax_vm/vm.cc", line 785, in tvm::runtime::relax_vm::VirtualMachineImpl::RunLoop()
    this->RunInstrCall(curr_frame, instr);
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/tvm-unity-env/tvm-unity/src/runtime/relax_vm/vm.cc", line 738, in tvm::runtime::relax_vm::VirtualMachineImpl::RunInstrCall(tvm::runtime::relax_vm::VMFrame*, tvm::runtime::relax_vm::Instruction)
    this->InvokeClosurePacked(func_pool_[instr.func_idx], args, &ret);
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/tvm-unity-env/tvm-unity/src/runtime/relax_vm/vm.cc", line 511, in tvm::runtime::relax_vm::VirtualMachineImpl::InvokeClosurePacked(tvm::runtime::ObjectRef const&, tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*)
    packed->CallPacked(args, rv);
                  ^^^^^^^^^^^^^^^^
  File "/workspace/tvm-unity-env/tvm-unity/src/runtime/relax_vm/paged_kv_cache.cc", line 1236, in operator()
    kv_cache->AttentionWithFusedQKV(layer_id, std::move(qkv_data), NullOpt, std::move(o_data));
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/tvm-unity-env/tvm-unity/src/runtime/relax_vm/paged_kv_cache.cc", line 736, in tvm::runtime::relax_vm::PagedAttentionKVCacheObj::AttentionWithFusedQKV(long, tvm::runtime::NDArray, tvm::runtime::Optional<tvm::runtime::NDArray>, tvm::runtime::NDArray)
    AttentionInternal(layer_id, q_data, k_data, v_data, o_data);
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/tvm-unity-env/tvm-unity/src/runtime/relax_vm/paged_kv_cache.cc", line 987, in tvm::runtime::relax_vm::PagedAttentionKVCacheObj::AttentionInternal(long, tvm::runtime::NDArray, tvm::runtime::NDArray, tvm::runtime::NDArray, tvm::runtime::NDArray)
    f_attention_prefill_ragged_.value()(
                ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/tvm-unity-env/tvm-unity/3rdparty/flashinfer/src/tvm_wrapper.cu", line 570, in _FlashInferAttentionPrefillWithRaggedKVCache(DLTensor*, DLTensor*, DLTensor*, DLTensor*, DLTensor*, DLTensor*, DLTensor*, DLTensor*, DLTensor*, long, long, double, double)
    SWITCH_TVM_CUDA_DTYPE(
                    ^^^^^^^
  File "/workspace/tvm-unity-env/tvm-unity/3rdparty/flashinfer/src/tvm_wrapper.cu", line 488, in cudaError _BatchPrefillWithRaggedKVCacheWrapper<__half, __half, int>(flashinfer::BatchPrefillHandler*, __half*, int*, __half*, __half*, int*, int*, int*, __half*, float*, unsigned int, unsigned int, unsigned int, unsigned int, bool, flashinfer::QKVLayout, flashinfer::RotaryMode, bool, float, float, CUstream_st*)
    CHECK(allow_fp16_qk_reduction == false) << "The fp16 qk reduction is not supported";
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
tvm._ffi.base.TVMError: Traceback (most recent call last):
  14: mlc::llm::LLMChatModule::GetFunction(tvm::runtime::String const&, tvm::runtime::ObjectPtr<tvm::runtime::Object> const&)::{lambda(tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*)#5}::operator()(tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*) const
        at /workspace/mount_orin/mlc-llm-llava/mlc-llm/cpp/llm_chat.cc:1689
  13: mlc::llm::LLMChat::PrefillStep(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool, bool, mlc::llm::PlaceInPrompt, tvm::runtime::String, tvm::runtime::NDArray)
        at /workspace/mount_orin/mlc-llm-llava/mlc-llm/cpp/llm_chat.cc:937
  12: mlc::llm::LLMChat::ForwardTokens(std::vector<int, std::allocator<int> >, long, tvm::runtime::NDArray)
        at /workspace/mount_orin/mlc-llm-llava/mlc-llm/cpp/llm_chat.cc:1343
  11: operator()
        at /workspace/tvm-unity-env/tvm-unity/src/runtime/relax_vm/vm.cc:935
  10: tvm::runtime::relax_vm::VirtualMachineImpl::InvokeClosurePacked(tvm::runtime::ObjectRef const&, tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*)
        at /workspace/tvm-unity-env/tvm-unity/src/runtime/relax_vm/vm.cc:529
  9: operator()
        at /workspace/tvm-unity-env/tvm-unity/src/runtime/relax_vm/vm.cc:603
  8: tvm::runtime::relax_vm::VirtualMachineImpl::InvokeBytecode(long, std::vector<tvm::runtime::TVMRetValue, std::allocator<tvm::runtime::TVMRetValue> > const&)
        at /workspace/tvm-unity-env/tvm-unity/src/runtime/relax_vm/vm.cc:660
  7: tvm::runtime::relax_vm::VirtualMachineImpl::RunLoop()
        at /workspace/tvm-unity-env/tvm-unity/src/runtime/relax_vm/vm.cc:785
  6: tvm::runtime::relax_vm::VirtualMachineImpl::RunInstrCall(tvm::runtime::relax_vm::VMFrame*, tvm::runtime::relax_vm::Instruction)
        at /workspace/tvm-unity-env/tvm-unity/src/runtime/relax_vm/vm.cc:738
  5: tvm::runtime::relax_vm::VirtualMachineImpl::InvokeClosurePacked(tvm::runtime::ObjectRef const&, tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*)
        at /workspace/tvm-unity-env/tvm-unity/src/runtime/relax_vm/vm.cc:511
  4: operator()
        at /workspace/tvm-unity-env/tvm-unity/src/runtime/relax_vm/paged_kv_cache.cc:1236
  3: tvm::runtime::relax_vm::PagedAttentionKVCacheObj::AttentionWithFusedQKV(long, tvm::runtime::NDArray, tvm::runtime::Optional<tvm::runtime::NDArray>, tvm::runtime::NDArray)
        at /workspace/tvm-unity-env/tvm-unity/src/runtime/relax_vm/paged_kv_cache.cc:736
  2: tvm::runtime::relax_vm::PagedAttentionKVCacheObj::AttentionInternal(long, tvm::runtime::NDArray, tvm::runtime::NDArray, tvm::runtime::NDArray, tvm::runtime::NDArray)
        at /workspace/tvm-unity-env/tvm-unity/src/runtime/relax_vm/paged_kv_cache.cc:987
  1: _FlashInferAttentionPrefillWithRaggedKVCache(DLTensor*, DLTensor*, DLTensor*, DLTensor*, DLTensor*, DLTensor*, DLTensor*, DLTensor*, DLTensor*, long, long, double, double)
        at /workspace/tvm-unity-env/tvm-unity/3rdparty/flashinfer/src/tvm_wrapper.cu:570
  0: cudaError _BatchPrefillWithRaggedKVCacheWrapper<__half, __half, int>(flashinfer::BatchPrefillHandler*, __half*, int*, __half*, __half*, int*, int*, int*, __half*, float*, unsigned int, unsigned int, unsigned int, unsigned int, bool, flashinfer::QKVLayout, flashinfer::RotaryMode, bool, float, float, CUstream_st*)
        at /workspace/tvm-unity-env/tvm-unity/3rdparty/flashinfer/src/tvm_wrapper.cu:488
  File "/workspace/tvm-unity-env/tvm-unity/3rdparty/flashinfer/src/tvm_wrapper.cu", line 486
TVMError: Check failed: (head_dim == 128) is false: The head dimension must be 128
`

2、create_tir_paged_kv_cache

`[2024-02-20 16:49:51] INFO compile.py:136: Creating model from: LlavaConfig(image_token_index=32000, text_config=LlamaConfig(hidden_size=3200, intermediate_size=8640, num_attention_heads=32, num_hidden_layers=26, rms_norm_eps=1e-06, vocab_size=32000, position_embedding_base=10000, context_window_size=2048, prefill_chunk_size=2048, num_key_value_heads=32, head_dim=100, tensor_parallel_shards=1, max_batch_size=80, kwargs={'architectures': ['LlavaLlamaForCausalLM'], 'model_type': 'llama', 'torch_dtype': 'bfloat16'}), vision_config=LlavaVisionConfig(hidden_size=1024, image_size=336, intermediate_size=4096, num_attention_heads=8, num_hidden_layers=24, patch_size=14, projection_dim=3200, vocab_size=32000, dtype='float16', num_channels=3, layer_norm_eps=1e-06, kwargs={'model_type': 'clip_vision_model'}), vocab_size=32000, context_window_size=2048, prefill_chunk_size=2048, tensor_parallel_shards=1, dtype='float16', kwargs={}) [2024-02-20 16:49:52] INFO compile.py:155: Exporting the model to TVM Unity compiler Traceback (most recent call last): File "/opt/conda/envs/mlc-llm-tvm-apply/bin/mlc_chat", line 33, in <module> sys.exit(load_entry_point('mlc-chat', 'console_scripts', 'mlc_chat')()) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/workspace/mount_dir/mlc-llm-llava/mlc-llm/python/mlc_chat/__main__.py", line 24, in main cli.main(sys.argv[2:]) File "/workspace/mount_dir/mlc-llm-llava/mlc-llm/python/mlc_chat/cli/compile.py", line 131, in main compile( File "/workspace/mount_dir/mlc-llm-llava/mlc-llm/python/mlc_chat/interface/compile.py", line 229, in compile _compile(args, model_config) File "/workspace/mount_dir/mlc-llm-llava/mlc-llm/python/mlc_chat/interface/compile.py", line 156, in _compile mod, named_params, ext_mods = model.export_tvm( ^^^^^^^^^^^^^^^^^ File "/workspace/nfs/tvm-unity/python/tvm/relax/frontend/nn/core.py", line 479, in export_tvm mod, params, ext_mods = Exporter(debug=debug).build(spec) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/workspace/nfs/tvm-unity/python/tvm/relax/frontend/nn/exporter.py", line 136, in build outputs, inputs = _emit_method(self.builder, method_spec, params, effects) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/workspace/nfs/tvm-unity/python/tvm/relax/frontend/nn/exporter.py", line 277, in _emit_method outputs = spec.method(*explicit_inputs) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/workspace/mount_dir/mlc-llm-llava/mlc-llm/python/mlc_chat/model/llava/llava_model.py", line 503, in create_tir_paged_kv_cache return TIRPagedKVCache( ^^^^^^^^^^^^^^^^ File "/workspace/mount_dir/mlc-llm-llava/mlc-llm/python/mlc_chat/nn/kv_cache.py", line 260, in __init__ bb.add_func(_attention_prefill(num_key_value_heads, num_attention_heads, head_dim, dtype), "tir_attention_prefill"), ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/workspace/mount_dir/mlc-llm-llava/mlc-llm/python/mlc_chat/nn/kv_cache.py", line 712, in _attention_prefill apply_to_gemm(sch, sch.get_block("O_gemm"), tile_o, 2, 3, k_major=False) File "/workspace/mount_dir/mlc-llm-llava/mlc-llm/python/mlc_chat/nn/kv_cache.py", line 692, in apply_to_gemm ty, tx = sch.split(t, factors=[num_warps, 32]) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/workspace/nfs/tvm-unity/python/tvm/tir/schedule/_type_checker.py", line 340, in wrap return func(*args, **kwargs) ^^^^^^^^^^^^^^^^^^^^^ File "/workspace/nfs/tvm-unity/python/tvm/tir/schedule/schedule.py", line 811, in split _ffi_api.ScheduleSplit(  # type: ignore # pylint: disable=no-member File "/workspace/nfs/tvm-unity/python/tvm/_ffi/_ctypes/packed_func.py", line 239, in __call__ raise_last_ffi_error() File "/workspace/nfs/tvm-unity/python/tvm/_ffi/base.py", line 481, in raise_last_ffi_error raise py_err tvm.tir.schedule.schedule.ScheduleError: Traceback (most recent call last): 1: tvm::tir::TracedScheduleNode::Split(tvm::tir::LoopRV const&, tvm::runtime::Array<tvm::runtime::Optional<tvm::PrimExpr>, void> const&, bool) at /workspace/nfs/tvm-unity/src/tir/schedule/traced_schedule.cc:230 0: tvm::tir::ConcreteScheduleNode::Split(tvm::tir::LoopRV const&, tvm::runtime::Array<tvm::runtime::Optional<tvm::PrimExpr>, void> const&, bool) at /workspace/nfs/tvm-unity/src/tir/schedule/concrete_schedule.cc:506 ScheduleError: An error occurred in the schedule primitive 'split'. `

**Comment by Hzfengsy** [comment]
similar as https://github.com/mlc-ai/mlc-llm/issues/1813

**Comment by jpf888** [comment]
> similar as #1813

ok, closed 1813

**Comment by MasterJH5574** [comment]
Hey @jpf888, thank you for reporting! It is indeed our miss. #1889 should address is. I have tested a bit.

**Comment by jpf888** [comment]
> Hey @jpf888, thank you for reporting! It is indeed our miss. #1889 should address is. I have tested a bit.

thanks!  i will try.

**Comment by allen888ai** [comment]
> Hey @jpf888, thank you for reporting! It is indeed our miss. #1889 should address is. I have tested a bit.

hi @MasterJH5574 ， 
Hello, I have completed the code changes and my model size can be compiled and passed!  Thanks。


But I can only use TIR paged kv cache. Flashinfer currently only supports headsize 128, but my headsize is 100 or 112, so I want to know about this support plan, and which one of flashinfer paged and tir paged can improve the decoding speed more？

**Comment by MasterJH5574** [comment]
> so I want to know about this support plan, and which one of flashinfer paged and tir paged can improve the decoding speed more

@allen888ai Thank you for following up! I guess for this question you can open an issue in [FlashInfer](https://github.com/flashinfer-ai/flashinfer)

**Comment by MasterJH5574** [comment]
Gonna close this issue for now given the original problem is addressed.
