### ISSUE TITLE
[Model Request] TinyLlama

### ISSUE THREAD

**Issue by calebtung** [mlc-ai/mlc-llm#1829]
## ⚙️  Request for TinyLlama-1.1B

- https://huggingface.co/TinyLlama/TinyLlama-1.1B-Chat-v1.0
- Uses the same architecture and tokenizer as Llama2

## Additional context
This would be extremely fast and open the opportunity for deployment on devices with constrained compute resources

**Comment by Hzfengsy** [comment]
Tinyllama is supported already, you could compile it as what you do as llama-2
