### ISSUE TITLE
[Question] build tiny-llama, use latest mlc-llm, report vm.builtin.paged_attention_kv_cache_attention_with_fused_qkv error 

### ISSUE THREAD

**Issue by Bobo-y** [mlc-ai/mlc-llm#1837]
## ❓ General Questions

![image](https://github.com/mlc-ai/mlc-llm/assets/9928596/a0b9fb7c-906d-46e8-a5ef-9dfadd0df6ab)

and refer other issue, I pass create_kv_cache_func params by hard-code:
![image](https://github.com/mlc-ai/mlc-llm/assets/9928596/4a19601e-230e-4d4c-ae3e-814817f79c7f)

I find https://github.com/mlc-ai/relax/blob/mlc/src/runtime/relax_vm/paged_kv_cache.cc, it's have five params,
![image](https://github.com/mlc-ai/mlc-llm/assets/9928596/225c933b-b2c2-4bca-9d22-35490d6302b4)

But in  https://github.com/mlc-ai/mlc-llm/blob/main/python/mlc_chat/nn/kv_cache.py
![image](https://github.com/mlc-ai/mlc-llm/assets/9928596/35c80fcb-3b57-429c-8877-76f05b5e7156)

only pass four params

**Comment by anibohara2000** [comment]
The `rx.call_dps_packed` function is for calling a Destination Passing Style Packed function, i.e. a function whose last argument is the output destination. So when calling this function you need not pass the destination, it is created and allocated in memory from the provided struct info during the model compilation stage.

Can you try re-compiling your TVM, MLC and the model, and running this again?
Also, can you share what commands you are using to build the model?

**Comment by Bobo-y** [comment]
rebuild tvm and mlc-llm, fix this error.

**Comment by bethalianovike** [comment]
@Bobo-y Hi, how do you install tvm-unity? Is it built from source or pip wheels? Thank you!

**Comment by Bobo-y** [comment]
@bethalianovike from source

**Comment by bethalianovike** [comment]
Hi @Bobo-y, are you cloned from the mlc-ai/relax github like in https://llm.mlc.ai/docs/install/tvm.html#option-2-build-from-source? Thank you!
