### ISSUE TITLE
Issue Compiling gemma-2-it for Vulkan on Linux

### ISSUE THREAD

**Issue by brian-pieces** [mlc-ai/mlc-llm#1841]
## 🐛 Bug

Running `mlc_chat compile` command for the `gemma-2-it` model on Linux with Vulkan target results in this error:

```
InternalError: Check failed: shared_memory_bytes_used_ <= spirv_support_.max_shared_memory_per_block (33280 vs. 32768) : Vulkan shader fused_fused_dequantize4_NT_matmul13_kernel uses 33280 bytes of shared memory, but target supports only 32768 bytes.  If the device supports this allocation, please add -max_shared_memory_per_block=NBYTES to the target, or query all device parameters by adding -from_device=0.
```

## To Reproduce

1. Clone pre-converted weights from mlc-ai Hugginface repo
2. Run compile command

## Expected behavior

Compiled binary

## Environment

 - Platform (e.g. WebGPU/Vulkan/IOS/Android/CUDA): Vulkan
 - Operating system (e.g. Ubuntu/Windows/MacOS/...): Linux  (via WSL)
 - Device (e.g. iPhone 12 Pro, PC+RTX 3090, ...) Laptop + 3050ti
 - How you installed MLC-LLM (`conda`, source): conda
 - How you installed TVM-Unity (`pip`, source): pip
 - Python version (e.g. 3.10): 3.11
 - GPU driver version (if applicable):
 - CUDA/cuDNN version (if applicable):
 - TVM Unity Hash Tag (`python -c "import tvm; print('\n'.join(f'{k}: {v}' for k, v in tvm.support.libinfo().items()))"`, applicable if you compile models):
 - Any other relevant information:

## Additional context

I've had no problem compiling Llama 7B, Mistral 7B, Neural Hermes, etc. with this exact flow so I'm surprised a smaller model would be having issues.

**Comment by MasterJH5574** [comment]
Thank you for reporting! We will look into it.

**Comment by brian-pieces** [comment]
@MasterJH5574 just checking in here to see if you'd have a chance to look into this? Thanks!

**Comment by MasterJH5574** [comment]
@brian-pieces Yes sure, we have identified the reason and are working on a fix.

**Comment by MasterJH5574** [comment]
apache/tvm#16731 is the potential fix here.

**Comment by brian-pieces** [comment]
Awesome, thank you!

**Comment by MasterJH5574** [comment]
@brian-pieces You're welcome! The PR was merged, and the Pypi packages should be ready tomorrow.
