### ISSUE TITLE
[Bug] InternalError: Check failed: type == expected_type (float32x2 vs. float16x2) : Attempted to access buffer K_smem as element type float32x2 using an index of size 2 when the element type is float16

### ISSUE THREAD

**Issue by sjtu-scx** [mlc-ai/mlc-llm#1842]
## 🐛 Bug

hello！when I running mlc_chat compile ./dist/Llama-2-7b-chat-hf-q4f16_1-MLC/mlc-chat-config.json --device vulkan -o dist/libs/Llama-2-7b-chat-hf-q4f16_1-vulkan.dll，I get the following errors. 

[18:59:57] D:\a\package\package\tvm\src\tir\schedule./concrete_schedule.h:287: ValueError: The block no longer exists in the IRModule
Stack trace not available when DMLC_LOG_STACK_TRACE is disabled at compile time.
...
[18:59:58] D:\a\package\package\tvm\src\tir\ir\stmt.cc:122: InternalError: Check failed: (e.dtype().bits() <= loop_var.dtype().bits()) is false: Loop variable's dtype (int32) is narrower than that of min or extent (int64)
Stack trace not available when DMLC_LOG_STACK_TRACE is disabled at compile time
...
[19:00:04] D:\a\package\package\tvm\src\target\spirv\codegen_spirv.h:163: InternalError: Check failed: type == expected_type (float32x2 vs. float16x2) : Attempted to access buffer K_smem as element type float32x2 using an index of size 2 when the element type is float16

## Environment

 - Platform:Vulkan
 - Operating system:Windows
 - Device:PC+RTX 3060
 - How you installed MLC-LLM (`conda`):conda
 - How you installed TVM-Unity (`pip`):pip
 - Python version:3.10.0
 - GPU driver version (if applicable):
 - CUDA/cuDNN version (if applicable):
 - TVM Unity Hash Tag (`python -c "import tvm; print('\n'.join(f'{k}: {v}' for k, v in tvm.support.libinfo().items()))"`, applicable if you compile models):
USE_NVTX: OFF   
USE_GTEST: AUTO 
SUMMARIZE: OFF  
USE_IOS_RPC: OFF
USE_MSC: OFF
USE_ETHOSU:
CUDA_VERSION: NOT-FOUND
USE_LIBBACKTRACE: AUTO
DLPACK_PATH: 3rdparty/dlpack/include
USE_TENSORRT_CODEGEN: OFF
USE_THRUST: OFF
USE_TARGET_ONNX: OFF
USE_AOT_EXECUTOR: ON
BUILD_DUMMY_LIBTVM: OFF
USE_CUDNN: OFF
USE_TENSORRT_RUNTIME: OFF
USE_ARM_COMPUTE_LIB_GRAPH_EXECUTOR: OFF
USE_CCACHE: AUTO
USE_ARM_COMPUTE_LIB: OFF
USE_CPP_RTVM:
USE_OPENCL_GTEST: /path/to/opencl/gtest
USE_MKL: OFF
USE_PT_TVMDSOOP: OFF
MLIR_VERSION: NOT-FOUND
USE_CLML: OFF
USE_STACKVM_RUNTIME: OFF
USE_GRAPH_EXECUTOR_CUDA_GRAPH: OFF
ROCM_PATH: /opt/rocm
USE_DNNL: OFF
USE_VITIS_AI: OFF
USE_MLIR: OFF
USE_RCCL: OFF
USE_LLVM: llvm-config --link-static
USE_VERILATOR: OFF
USE_TF_TVMDSOOP: OFF
USE_THREADS: ON
USE_MSVC_MT: OFF
BACKTRACE_ON_SEGFAULT: OFF
USE_GRAPH_EXECUTOR: ON
USE_NCCL: OFF
USE_ROCBLAS: OFF
GIT_COMMIT_HASH: cef243a113d44b5d991e5993f4eeeca71fb1b27f
USE_VULKAN: ON
USE_RUST_EXT: OFF
USE_CUTLASS: OFF
USE_CPP_RPC: OFF
USE_HEXAGON: OFF
USE_CUSTOM_LOGGING: OFF
USE_UMA: OFF
USE_FALLBACK_STL_MAP: OFF
USE_SORT: ON
USE_RTTI: ON
GIT_COMMIT_TIME: 2024-02-02 14:09:23 -0500
USE_HEXAGON_SDK: /path/to/sdk
USE_BLAS: none
USE_ETHOSN: OFF
USE_LIBTORCH: OFF
USE_RANDOM: ON
USE_CUDA: OFF
USE_COREML: OFF
USE_AMX: OFF
BUILD_STATIC_RUNTIME: OFF
USE_CMSISNN: OFF
USE_KHRONOS_SPIRV: OFF
USE_CLML_GRAPH_EXECUTOR: OFF
USE_TFLITE: OFF
USE_HEXAGON_GTEST: /path/to/hexagon/gtest
PICOJSON_PATH: 3rdparty/picojson
USE_OPENCL_ENABLE_HOST_PTR: OFF
INSTALL_DEV: OFF
USE_PROFILER: ON
USE_NNPACK: OFF
LLVM_VERSION: 17.0.6
USE_OPENCL: OFF
COMPILER_RT_PATH: 3rdparty/compiler-rt
RANG_PATH: 3rdparty/rang/include
USE_SPIRV_KHR_INTEGER_DOT_PRODUCT: OFF
USE_OPENMP: OFF
USE_BNNS: OFF
USE_CUBLAS: OFF
USE_METAL: OFF
USE_MICRO_STANDALONE_RUNTIME: OFF
USE_HEXAGON_EXTERNAL_LIBS: OFF
USE_ALTERNATIVE_LINKER: AUTO
USE_BYODT_POSIT: OFF
USE_HEXAGON_RPC: OFF
USE_MICRO: OFF
DMLC_PATH: 3rdparty/dmlc-core/include
INDEX_DEFAULT_I64: ON
USE_RELAY_DEBUG: OFF
USE_RPC: ON
USE_TENSORFLOW_PATH: none
TVM_CLML_VERSION:
USE_MIOPEN: OFF
USE_ROCM: OFF
USE_PAPI: OFF
USE_CURAND: OFF
TVM_CXX_COMPILER_PATH: C:/Program Files/Microsoft Visual Studio/2022/Enterprise/VC/Tools/MSVC/14.37.32822/bin/HostX64/x64/cl.exe     
HIDE_PRIVATE_SYMBOLS: OFF

**Comment by sjtu-scx** [comment]
@sherelynyap, I noticed you mentioned that this is fixed in #1725 and  this change is already in the newest mlc_chat_nightly. However, this solution didn't work for me.

**Comment by MasterJH5574** [comment]
Hi @sjtu-scx, thanks for reporting. We are working on fixing the Windows package, and will report back when it's done.

**Comment by MasterJH5574** [comment]
Hi @sjtu-scx, we updated the Windows wheel. Could you upgrade the package via the command and try again? Thank you!
```
python3 -m pip install --pre -U -f https://mlc.ai/wheels mlc-chat-nightly mlc-ai-nightly
```

**Comment by sjtu-scx** [comment]
OK, thank you！

----- 原始邮件 -----
发件人: "Ruihang Lai" ***@***.***>
收件人: "mlc-ai/mlc-llm" ***@***.***>
抄送: "Sun Chenxing" ***@***.***>, "Mention" ***@***.***>
发送时间: 星期三, 2024年 2 月 28日 上午 3:58:03
主题: Re: [mlc-ai/mlc-llm] [Bug] InternalError: Check failed: type == expected_type (float32x2 vs. float16x2) : Attempted to access buffer K_smem as element type float32x2 using an index of size 2 when the element type is float16 (Issue #1842)

Hi @sjtu-scx, we updated the Windows wheel. Could you upgrade the package via the command and try again? Thank you!
```
python3 -m pip install --pre -U -f https://mlc.ai/wheels mlc-chat-nightly mlc-ai-nightly
```

**Comment by MasterJH5574** [comment]
Close due to inactivity. You can open a new one if the issue persists or there is other new issue.
