### ISSUE TITLE
Cannot find vicuna-v1-7b lib in preferred path "dist/vicuna-v1-7b/float16/vicuna-v1-7b_metal_float16.dylib" or other candidate paths%

### ISSUE THREAD

**Issue by drppsy** [mlc-ai/mlc-llm#185]
Cannot find vicuna-v1-7b lib in preferred path "dist/vicuna-v1-7b/float16/vicuna-v1-7b_metal_float16.dylib" or other candidate paths%

**Comment by junrushao** [comment]
This issue should be fixed by latest HEAD. Please try again and feel free to open a new one if it doesn't work
