### ISSUE TITLE
[Question] How to set up Rag & Prompt engineering in Android app

### ISSUE THREAD

**Issue by Moon-Ahn** [mlc-ai/mlc-llm#1853]
## ❓ General Questions

Thanks. mlc-llm is helping me a lot.
I am currently experimenting with the mistral model, and I succeeded in inserting the model that was fine tuned to mlc-llm in the form of Android on device.

As a next step, I would like to use prompt engineering and RAG for this model.
To complete this, I'm having trouble with which library to touch which code.
Can you give me some advice?

**Comment by MasterJH5574** [comment]
Hi @Moon-Ahn, thanks for the question! As of now we do not have RAG support, however. This is a fun feature we could build centered around KV cache in MLC. I'll think a bit more and see if I can have more info to share.

**Comment by Moon-Ahn** [comment]
@MasterJH5574 Thank you so much. I'll give it a try!

**Comment by RonPeters** [comment]
I would be highly interested in RAG as well!

**Comment by Moon-Ahn** [comment]
@MasterJH5574 

I haven't found a way to apply it yet.
Do you have any ideas that you've thought about?

**Comment by SolshineCode** [comment]
I am also keenly interested in expanding MLC LLM app with RAG such as using Langchain or DSPy-ai.

**Comment by Moon-Ahn** [comment]
I solved the problem by adding reg and prompt engineering to the 'requestGeneration' function.
If you have any better opinions and roadmaps, I would appreciate it if you could write them down.
I'll close this issue.

**Comment by Moon-Ahn** [comment]
I solved the problem by adding reg and prompt engineering to the 'requestGeneration' function.
If you have any better opinions and roadmaps, I would appreciate it if you could write them down.
I'll close this issue.

**Comment by atultiwari** [comment]
> I solved the problem by adding reg and prompt engineering to the 'requestGeneration' function. If you have any better opinions and roadmaps, I would appreciate it if you could write them down. I'll close this issue.

Hi, I am also looking for using RAG with MLC-LLM?
Can you please tell, how did you solve it?
Thank you
Atul

**Comment by aiakubovich** [comment]
@Moon-Ahn , I am interested in you implementation too. I would appreciate if you can share code

**Comment by Moon-Ahn** [comment]
@atultiwari 
@aiakubovich 
I proceeded by inserting the database (.db) file and searching it. It was possible because the number of data was not large. (approximately 3000) It was not perfect, but it was possible to some extent.
