### ISSUE TITLE
[Question] Does MLC support speculative decoding on Android?

### ISSUE THREAD

**Issue by calebtung** [mlc-ai/mlc-llm#1858]
I saw speculative decoding mentioned in #1539 . Is this supported for deployment to Android targets?
If I wanted to deploy Llama2-7b with TinyLlama as a draft model, how would I do that?
Would also be happy to contribute to the docs on this.

Thanks.

**Comment by YiGe-MediaTek** [comment]
I am also interested to see the speculative decoding support on Android platform. Any answer on that?

**Comment by tqchen** [comment]
spec decode is coming to MLCEngine #2217 which is being landed soon
