### ISSUE TITLE
[Bug] TVMError: The output probabilities are all NaNs, can not sample from it

### ISSUE THREAD

**Issue by MBadriNarayanan** [mlc-ai/mlc-llm#1861]
## 🐛 Bug

Seeing TVMError: The output probabilities are all NaNs, can not sample from it while using mlc_chat 

Model Used: `gpt_bigcode-santacoder`

Model weight conversion, config generation, and compilation are being done successfully. The issue is seen while chatting with the model.

## To Reproduce

```
mlc_chat convert_weight models/gpt_bigcode-santacoder/ --quantization q4f16_1 -o compiled_models/gpt_bigcode-santacoder-q4f16_1-MLC/
mlc_chat gen_config models/gpt_bigcode-santacoder/ --quantization q4f16_1 --conv-template gpt_bigcode -o compiled_models/gpt_bigcode-santacoder-q4f16_1-MLC/
mlc_chat compile compiled_models/gpt_bigcode-santacoder-q4f16_1-MLC/ --device metal -o model_libs/gpt_bigcode-santacoder-q4f16_1-metal.so
```

Error is seen when running the command

`mlc_chat chat compiled_models/gpt_bigcode-santacoder-q4f16_1-MLC/ --device "metal:0" --overrides context_window_size=1024 --model-lib-path model_libs/gpt_bigcode-santacoder-q4f16_1-metal.so`

## Error

```
Prompt: Give the code to design a simple calculator
Code: 
, that takes two numbers, and shows the result, 
 * where the user can add, subtract, multiply, and divide numbers.
 */
public class Calculator {

	private static String calculate(String num1, StringTraceback (most recent call last):
  File "/opt/homebrew/bin/mlc_chat", line 33, in <module>
    sys.exit(load_entry_point('mlc-chat', 'console_scripts', 'mlc_chat')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/Desktop/mlc-llm/python/mlc_chat/__main__.py", line 36, in main
    cli.main(sys.argv[2:])
  File "/Users/Desktop/mlc-llm/python/mlc_chat/cli/chat.py", line 41, in main
    chat(
  File "/Users/Desktop/mlc-llm/python/mlc_chat/interface/chat.py", line 159, in chat
    cm.generate(
  File "/Users/Desktop/mlc-llm/python/mlc_chat/chat_module.py", line 861, in generate
    self._decode(generation_config=generation_config)
  File "/Users/Desktop/mlc-llm/python/mlc_chat/chat_module.py", line 1147, in _decode
    self._decode_func(generation_config_str)
  File "/Users/Desktop/tvm-unity/python/tvm/_ffi/_ctypes/packed_func.py", line 239, in __call__
    raise_last_ffi_error()
  File "/Users/Desktop/tvm-unity/python/tvm/_ffi/base.py", line 481, in raise_last_ffi_error
    raise py_err
  File "/Users/Desktop/tvm-unity/src/runtime/relax_vm/lm_support.cc", line 489, in tvm::runtime::relax_vm::SampleTopPFromProb(tvm::runtime::NDArray, double, double)
    LOG(FATAL) << "The output probabilities are all NaNs, can not sample from it";
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^
tvm._ffi.base.TVMError: Traceback (most recent call last):
  5: 
  4: 
  3: 
  2: 
  1: 
  0: tvm::runtime::relax_vm::SampleTopPFromProb(tvm::runtime::NDArray, double, double)
        at /Users/Desktop/tvm-unity/src/runtime/relax_vm/lm_support.cc:489
  File "/Users/Desktop/tvm-unity/src/runtime/relax_vm/lm_support.cc", line 489
TVMError: The output probabilities are all NaNs, can not sample from it
```

## Expected behavior

Answer to the prompt should be generated.

## Environment

 - Platform (e.g. WebGPU/Vulkan/IOS/Android/CUDA): `M2 Pro, 16 GB`
 - Operating system (e.g. Ubuntu/Windows/MacOS/...): `MacOS`
 - Device (e.g. iPhone 12 Pro, PC+RTX 3090, ...): `Macbook Pro`
 - How you installed MLC-LLM (`conda`, source): `From source`
 - How you installed TVM-Unity (`pip`, source): `From source`
 - Python version (e.g. 3.10): `3.11.8`
 - GPU driver version (if applicable): `N/A`
 - CUDA/cuDNN version (if applicable): `N/A`
 - TVM Unity Hash Tag: `59c3556043abdc88f3ed98e07aa6176ac9a3f0cd`

**Comment by Kartik14** [comment]
#1870 should fix this issue. Please note that you might need to recompile the model after fetching these changes.

**Comment by MasterJH5574** [comment]
#1870 fixes the mixed precision attention computation issue for the attention kernels used by PagedKVCache. But given our GPTBigCode model definition hasn't switched to use PagedKVCache, #1870 doesn't effectively fix the issue here.

To fix this issue, my guess is that we need to add a `qk_dtype="float32"` kwarg here https://github.com/mlc-ai/mlc-llm/blob/bd2fb42f17db829b0dce150bce8441aec2f186ee/python/mlc_chat/model/gpt_bigcode/gpt_bigcode_model.py#L130

Perhaps I can quickly test this fix..

**Comment by MasterJH5574** [comment]
Hmmmm I just tried on both CUDA (RTX 4090) and Metal (M2 Ultra) with `q4f16_1` quantization, but was not able to reproduce the NAN issue. @MBadriNarayanan could you try the fix above and see if it works? Given you build MLC from source I think the trying it would be very fast -- just pass in the `qk_dtype="float32"`, and recompile the model with `mlc_chat compile .....`. Then see if it works.

I also noticed that the TVM hash you use (`59c3556043abdc88f3ed98e07aa6176ac9a3f0cd`) is a bit old.
```
commit 59c3556043abdc88f3ed98e07aa6176ac9a3f0cd
Author: Ruihang Lai <ruihangl@cs.cmu.edu>
Date:   Mon Dec 11 13:45:55 2023 -0500

    [MLC] CI Tweaks
    
    - Revert "[CMake][MSVC] Disable permissive mode for MSVC builds (#16343)"
    - Skip MSC tests
    - Disable NNPack and TFLite
    - Tweak CMAKE_CUDA_ARCHITECTURES

 CMakeLists.txt                           |  5 -----
 cmake/modules/CUDA.cmake                 | 24 ++++++++++++++++++++++++
 tests/scripts/task_config_build_cpu.sh   |  6 +++---
 tests/scripts/task_config_build_gpu.sh   |  2 +-
 tests/scripts/unity/task_python_relax.sh |  2 +-
 5 files changed, 29 insertions(+), 10 deletions(-)
```
So if possible, could you try to checkout a latest commit, rebuild TVM, and try run the chat again? I'm not 100% sure that TVM version is the cause, but it is just good to checkout to the latest one. Perhaps it can fix.

**Comment by MBadriNarayanan** [comment]
Hey @MasterJH5574 Just now tried the model. This fix does solve the problem. Seeing no errors currently. Can resolve the issue, thanks!

**Comment by MasterJH5574** [comment]
@MBadriNarayanan Awesome, glad that it works!
