### ISSUE TITLE
[Question] How to print log under mlc-llm?

### ISSUE THREAD

**Issue by gesanqiu** [mlc-ai/mlc-llm#1865]
## ❓ General Questions

How to print debug info in mlc-llm? I add a conv-template in conv_templates.cc and want to verify whether my template is correct, which needs to see the formatted prompt from a conversation object. I add a print code in [llc_chat.cc line 744](https://github.com/mlc-ai/mlc-llm/blob/eb465ec8fdba280dc0a4ebbc287b7bc5ea2a6473/cpp/llm_chat.cc#L744), where I think is the correct place. But the print code in cpp/llm_chat.cc show nothing in the runtime.

BTW, I test my template with `mlc_chat chat` and `examples/python/sample_mlc_chat.py`.

**Comment by tqchen** [comment]
you can use `LOG(INFO) << str`, but normal printing should also work

**Comment by gesanqiu** [comment]
I add `LOG(INFO) << str` in `llc_chat.cc`, it print nothing. Them I add `LOG(INFO)` in [conversation.h line 261](https://github.com/mlc-ai/mlc-llm/blob/eb465ec8fdba280dc0a4ebbc287b7bc5ea2a6473/cpp/conversation.h#L261) to print the `ret`, it works. But it seems there are some sync issue in the runtime, `ret` is a vector, where I can't see the output of assistant role with user role, they are printed seperately.

**Comment by gesanqiu** [comment]
@MasterJH5574 Could you reopen this issue, since I don't see the reopen button. Still have question about debugging under mlc-llm. Except this one, I also can't see the logs in model defenition like https://github.com/mlc-ai/mlc-llm/blob/eb465ec8fdba280dc0a4ebbc287b7bc5ea2a6473/python/mlc_chat/model/llama/llama_model.py.

**Comment by MasterJH5574** [comment]
Thank you for following up. When adding `LOG(INFO) << all_prompt;` or `std::cout << all_prompt << std::endl;` or whatever way you'd like to print, you need to recompile the cpp runtime.

**Comment by MasterJH5574** [comment]
Could you tell me what do you want to print out? Happy to share some more detail
