### ISSUE TITLE
[Question] when the official multimodal-llm can be release ？ like llava or qwen-vl?The llava in MR cannot fully adapt to the latest code. 🤔

### ISSUE THREAD

**Issue by Bobo-y** [mlc-ai/mlc-llm#1879]

**Comment by tatsumakiopm1** [comment]
gg

**Comment by MasterJH5574** [comment]
Thank you for the question. The llava support is still in progress. Maybe @anibohara2000 can share some progress status.

**Comment by anibohara2000** [comment]
We have the initial support for `ChatModule` in #1742 . We are working on support in the Serving Engine, which is almost complete, so expect it to be up by next week.
