### ISSUE TITLE
Can we compile models using TensorRT?

### ISSUE THREAD

**Issue by srikanthsrnvs** [mlc-ai/mlc-llm#1885]
We are using special hardware that runs well with TensorRT, however since we are just using the SLM workflow, we cannot offload some of the computation to the hardware built for TensorRT.

Any guidelines on how I might be able to compile a model using tensorRT for the ops that it supports, and TVM for the rest?

**Comment by tqchen** [comment]
for now we do not support interpolate with TRT, we do incorporate trt kernels at the engine level
