### ISSUE TITLE
[Question] How to use llama-2-7b-chat-q8f16_ft.so which compiled by mlc_llm_build

### ISSUE THREAD

**Issue by wzxcj** [mlc-ai/mlc-llm#1892]
## ❓ General Questions
I compiled the llama2 model using mlc_llm_build and generated a library llama-2-7b-chat-q8f16_ft.so and pramas，this is my command i used:   mlc_llm_build --model ../Llama-2-7b-chat --use-safetensors --quantization q8f16_ft

**Comment by wzxcj** [comment]
How to use this library and params

**Comment by tqchen** [comment]
checkout some docs here https://llm.mlc.ai/docs/compilation/convert_weights.html, we are also transitioning into a new flow that is more well documented

**Comment by tqchen** [comment]
maybe we can try q4 variant instead? likely due to model format not being supported as of now

**Comment by wzxcj** [comment]
thanks
