### ISSUE TITLE
[Question] [Android] A question about MLC-LLM Android latency？

### ISSUE THREAD

**Issue by wanderHZ** [mlc-ai/mlc-llm#1901]
## ❓ General Questions

I exported the Qwen model to the dynamic library of .so by specifying device as mali, and called the cpp interface of mlc-llm to load the dynamic library and corresponding weights. But I found that this method is about 50% slower than using an Android app directly.
https://github.com/mlc-ai/mlc-llm/blob/2f26e05d4ca1beb006099d0c1f1370a73e0f13ba/python/mlc_chat/support/auto_target.py#L212
Can you give me some help?

**Comment by tqchen** [comment]
likely this is the difference between adroid(adreno) and mali
