### ISSUE TITLE
[Question] How to support customized tokenizer?

### ISSUE THREAD

**Issue by gesanqiu** [mlc-ai/mlc-llm#1907]
## ❓ General Questions

Hi, I implemented a customized tokenizer, which optimized some segmentation logics, and use it trained my model. But it seems MLC-LLM only support one type of tokenizer in `3rdparty/tokenizers-cpp` and the output of `encode` is really different from transformers. 

My questions are:
1. How to support customized tokenizer? As far as I known, QWen also has its own tokenizer that shall different from MLC-LLM, since MLC-LLM already supported QWen, can I suppose the `3rdparty/tokenizer-cpp` also supported its tokenizer?
2. Does the tokenizer in MLC-LLM supports `additional_special_tokens`, in my test, the tokenizer sperate the added special token to several independent works.

**Comment by tqchen** [comment]
We encourage converstion to the HF format if possible, otherwise a patch to tokenizers-cpp is necessary
