### ISSUE TITLE
[Bug] input_ids expects Tensor with ndim 2 but get 1

### ISSUE THREAD

**Issue by KittenYang** [mlc-ai/mlc-llm#1923]
## To Reproduce

1. follow this doc to deploy on iOS: https://llm.mlc.ai/docs/deploy/ios.html#id6
2. change the `app-config.json` to "model_path": "RedPajama-INCITE-Chat-3B-v1-q4f16_1", cause the doc above is RedPajama for example
3. build success
4. run success
5. tap `RedPajama`, ready to chat
6. send prompt, crashed! Logs below:

```log
libc++abi: terminating due to uncaught exception of type tvm::runtime::InternalError: [12:40:11] /Users/xxx/Documents/GitHub/mlc-llm/3rdparty/tvm/src/runtime/relax_vm/builtin.cc:241: Check failed: (ptr->dl_tensor.ndim == ndim) is false: ValueError: ErrorContext(fn=embed, loc=param[0], param=input_ids, annotation=R.Tensor((1, seq_len), dtype="int32"))  expect Tensor with ndim 2 but get 1
Stack trace:
  [bt] (0) 1   MLCChat                             0x00000001029b1880 tvm::runtime::detail::LogFatal::Entry::Finalize() + 68
  [bt] (1) 2   MLCChat                             0x00000001029b183c tvm::runtime::detail::LogFatal::Entry::Finalize() + 0
  [bt] (2) 3   MLCChat                             0x00000001029b08b0 __clang_call_terminate + 0
  [bt] (3) 4   MLCChat                             0x0000000102b29d50 tvm::runtime::relax_vm::CheckTensorInfo(tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*) + 952
  [bt] (4) 5   MLCChat                             0x0000000102b2d5f8 tvm::runtime::PackedFuncObj::Extractor<tvm::runtime::PackedFuncSubObj<void (*)(tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*)>>::Call(tvm::runtime::PackedFuncObj const*, tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*) + 44
  [bt] (5) 6   MLCChat                             0x0000000102b93dc8 tvm::runtime::relax_vm::VirtualMachineImpl::InvokeClosurePacked(tvm::runtime::ObjectRef const&, tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*) + 96
  [bt] (6) 7   MLCChat                             0x0000000102b96454 tvm::runtime::relax_vm::VirtualMachineImpl::RunInstrCall(tvm::runtime::relax_vm::VMFrame*, tvm::runtime::relax_vm::Instruction) + 1312
  [bt] (7) 8   MLCChat                             0x0000000102b95c5c tvm::runtime::relax_vm::VirtualMachineImpl::RunLoop() + 100
  [bt] (8) 9   MLCChat                             0x0000000102b9586c tvm::runtime::relax_vm::VirtualMachineImpl::InvokeBytecode(long long, std::__1::vector<tvm::runtime::TVMRetValue, std::__1::allocator<tvm::runtime::TVMRetValue>> const&) + 284

```

## Environment

 - Platform (e.g. WebGPU/Vulkan/IOS/Android/CUDA): IOS
 - Operating system (e.g. Ubuntu/Windows/MacOS/...): iOS 16.6.1
 - Device (e.g. iPhone 12 Pro, PC+RTX 3090, ...) iPhone 14Pro
 - How you installed MLC-LLM (`conda`, source): source
 - How you installed TVM-Unity (`pip`, source):pip
 - Python version (e.g. 3.10): Python 3.10.5 
 - GPU driver version (if applicable):
 - CUDA/cuDNN version (if applicable):
 - TVM Unity Hash Tag (`python -c "import tvm; print('\n'.join(f'{k}: {v}' for k, v in tvm.support.libinfo().items()))"`, applicable if you compile models):
 - Any other relevant information:

**Comment by sygi** [comment]
I am not able to recompile (pending meta approval for the main llama access), but I can confirm I'm seeing this error also on Android, with precompiled LLama 2-7B and Gemma 2B if that helps.

**Comment by MasterJH5574** [comment]
I see. The precompiled Android and iOS libraries need update. We'll address it asap.

**Comment by Kartik14** [comment]
I have updated the android libs. Could you please try again? (If there is some issue, try fetching the latest code from source and build again for TVM and MLC_LLM)

**Comment by KittenYang** [comment]
@Kartik14 Is it capable for iOS?

**Comment by Kartik14** [comment]
Sorry, I have only updated android libs. @CharlieFRuan do you know who works on IOS?

**Comment by sygi** [comment]
> I have updated the android libs. Could you please try again? (If there is some issue, try fetching the latest code from source and build again for TVM and MLC_LLM)

Thank you, I'll check later today. I spent many hours trying to build from source but I kept getting more and more obscure errors and I gave that up.

**Comment by sygi** [comment]
I performed the following steps:
1. replaced the .tar file, after verifying it has a different hash
2. cleaned the project in Android studio
3. ran `./prepare_libs.sh` again
4. confirmed the `tvm4j_core.jar` has a different hash (but `arm64-v8a/libtvm4j_runtime_packed.so` not)
5. built the project
6. ran the app

I got the following error in step 6:
```
$ Installation failed due to: 'Failed to commit install session 41202319 with command package install-commit 41202319. Error: INSTALL_FAILED_VERIFICATION_FAILURE: Verification timed out for file:///data/app/vmdl41202319.tmp'
```

While it looks unconnected to the android libs, I haven't had this issue with the previous version of the libs.

**Comment by sygi** [comment]
Thank you, I already tried them out but to no avail. I suspect something went wrong with the attempt to compile things myself, as I am not able to use the previous android lib either right now. I guess I'll give it a pass for now and maybe will get back again after reinstalling everything from scratch.

Thanks for your help!
