### ISSUE TITLE
[Question]InternalError: Check failed: (lib_handle_ != nullptr) is false: Failed to load dynamic shared library dist\prebuilt\lib\Llama-2-7b-chat-hf\Llama-2-7b-chat-hf-q4f16_1-metal.so Stack trace not available when DMLC_LOG_STACK_TRACE is disabled at compile time.

### ISSUE THREAD

**Issue by Long8279** [mlc-ai/mlc-llm#1927]
## ❓ General Questions

How should I solve the following problem when I am running  Llama-2-7b-chat-hf-q4f16_1-MLC.
My GPU memory size is 7.9GB.
<img width="1273" alt="problem" src="https://github.com/mlc-ai/mlc-llm/assets/129834544/b3db5ac7-a7ae-468e-b472-80887af4c38e">

**Comment by tqchen** [comment]
the vulkan issue should have been fixed in latest update, please try to remove model_lib_path
