### ISSUE TITLE
[NOTICE] Migrating mlc_chat package to mlc_llm

### ISSUE THREAD

**Issue by tqchen** [mlc-ai/mlc-llm#1929]
Now that we are deprecating the old flow #1928 . We have the ability to pick up the formal `mlc_llm` package name for our flow.
Notably, this would indeed cause some breaks of the current usage, but we believe it is important to be able to 

This is a notice that we plan to do that around this week(before Mar 15). That likely means that the package usage of `mlc_chat` will point to `mlc_llm` after the transition. We will also update the document to bring things up to date

**Comment by MasterJH5574** [comment]
PR #1928 has been merged. We are building the Pypi wheels after renaming.
