### ISSUE TITLE
How to set model_lib in app.config.json Android?

### ISSUE THREAD

**Issue by LumenScopeAI** [mlc-ai/mlc-llm#1935]
## ❓ General Questions
I use these json, but meet some problems. So how to set model_lib?
The problems I meet is the same as: https://github.com/mlc-ai/mlc-llm/issues/1517

```
{
  "model_list": [
    {
      "model_url": "https://huggingface.co/mlc-ai/Llama-2-7b-chat-hf-q4f16_1-MLC/",
      "model_lib": "llama_q4f16_1",
      "estimated_vram_bytes": 4348727787,
      "model_id": "Yi-6B-Chat-q4f16_1"
    },
    {
      "model_url": "https://huggingface.co/mlc-ai/Llama-2-7b-chat-hf-q4f16_1-MLC/",
      "model_lib": "llama_q40f16",
      "estimated_vram_bytes": 4348727787,
      "model_id": "Qwen1.5-1.8B-Chat-q0f16"
    }
  ],
  "model_lib_path_for_prepare_libs": {
    "Yi-6B-Chat-q4f16_1": "Yi-6B-Chat-q4f16_1-MLC/Yi-6B-Chat-q4f16_1-android.tar",
    "Qwen1.5-1.8B-Chat-q0f16": "Qwen1.5-1.8B-Chat-q0f16-MLC/Qwen1.5-1.8B-Chat-q0f16-android.tar"
  }
}
```

**Comment by Kartik14** [comment]
Hi the model_lib has the format `mode_type`_`quantization`. you can find both these fields inside the `mlc-chat-config.json` file inside the model directory. Also you need to have a matching JSON inside `model_list` for each model lib key inside `model_lib_path_for_prepare_libs`. Please refer to the base `app-config.json` file for reference. You can also checkout the docs [here](https://llm.mlc.ai/docs/deploy/android.html#create-android-project-using-compiled-models)

**Comment by MrRace** [comment]
@LumenScopeAI what value should I set for the parameter --conv-template？
