### ISSUE TITLE
AttributeError: module 'tvm.dlight.gpu' has no attribute 'LowBatchGEMV'[Bug] 

### ISSUE THREAD

**Issue by sheepHavingPurpleLeaf** [mlc-ai/mlc-llm#1936]
## To Reproduce

MODEL_NAME=Qwen1.5-1.8B-Chat
QUANTIZATION=q4f16_1

mlc_llm convert_weight ../dist/models/$MODEL_NAME/ --quantization $QUANTIZATION -o ../dist/$MODEL_NAME-$QUANTIZATION-MLC/

create mlc-chat-config.json:
mlc_llm gen_config ../dist/models/$MODEL_NAME/ --quantization $QUANTIZATION \
     --conv-template chatml --context-window-size 768 -o ../dist/${MODEL_NAME}-${QUANTIZATION}-MLC/

compile: compile model library with specification in mlc-chat-config.json
mlc_llm compile ../dist/${MODEL_NAME}-${QUANTIZATION}-MLC/mlc-chat-config.json \
    --device mali -o ../dist/${MODEL_NAME}-${QUANTIZATION}-MLC/${MODEL_NAME}-${QUANTIZATION}-opencl.so

## Expected behavior

generate so file successfully

## Environment

 - Platform (e.g. WebGPU/Vulkan/IOS/Android/CUDA): android opencl
 - Operating system (e.g. Ubuntu/Windows/MacOS/...): macOS
 - Device (e.g. iPhone 12 Pro, PC+RTX 3090, ...) Android snapdragon 8295
 - How you installed MLC-LLM (`conda`, source): source
 - How you installed TVM-Unity (`pip`, source): source
 - Python version (e.g. 3.10): 3.10
 - GPU driver version (if applicable): Adreno GPU
 - CUDA/cuDNN version (if applicable):
 - TVM Unity Hash Tag (`python -c "import tvm; print('\n'.join(f'{k}: {v}' for k, v in tvm.support.libinfo().items()))"`, applicable if you compile models):
 USE_NVTX: OFF
USE_GTEST: AUTO
SUMMARIZE: OFF
USE_IOS_RPC: OFF
USE_MSC: OFF
USE_ETHOSU: 
CUDA_VERSION: NOT-FOUND
USE_LIBBACKTRACE: AUTO
DLPACK_PATH: 3rdparty/dlpack/include
USE_TENSORRT_CODEGEN: OFF
USE_THRUST: OFF
USE_TARGET_ONNX: OFF
USE_AOT_EXECUTOR: ON
BUILD_DUMMY_LIBTVM: OFF
USE_CUDNN: OFF
USE_TENSORRT_RUNTIME: OFF
USE_ARM_COMPUTE_LIB_GRAPH_EXECUTOR: OFF
USE_CCACHE: AUTO
USE_ARM_COMPUTE_LIB: OFF
USE_CPP_RTVM: 
USE_OPENCL_GTEST: /path/to/opencl/gtest
USE_MKL: OFF
USE_PT_TVMDSOOP: OFF
MLIR_VERSION: NOT-FOUND
USE_CLML: OFF
USE_STACKVM_RUNTIME: OFF
USE_GRAPH_EXECUTOR_CUDA_GRAPH: OFF
ROCM_PATH: /opt/rocm
USE_DNNL: OFF
USE_VITIS_AI: OFF
USE_MLIR: OFF
USE_RCCL: OFF
USE_LLVM: llvm-config --link-static
USE_VERILATOR: OFF
USE_TF_TVMDSOOP: OFF
USE_THREADS: ON
USE_MSVC_MT: OFF
BACKTRACE_ON_SEGFAULT: OFF
USE_GRAPH_EXECUTOR: ON
USE_NCCL: OFF
USE_ROCBLAS: OFF
GIT_COMMIT_HASH: 292137088115ac81779607ca223bbbd9ad40cb55
USE_VULKAN: OFF
USE_RUST_EXT: OFF
USE_CUTLASS: OFF
USE_CPP_RPC: OFF
USE_HEXAGON: OFF
USE_CUSTOM_LOGGING: OFF
USE_UMA: OFF
USE_FALLBACK_STL_MAP: OFF
USE_SORT: ON
USE_RTTI: ON
GIT_COMMIT_TIME: 2024-02-03 18:46:43 -0800
USE_HEXAGON_SDK: /path/to/sdk
USE_BLAS: none
USE_ETHOSN: OFF
USE_LIBTORCH: OFF
USE_RANDOM: ON
USE_CUDA: OFF
USE_COREML: OFF
USE_AMX: OFF
BUILD_STATIC_RUNTIME: OFF
USE_CMSISNN: OFF
USE_KHRONOS_SPIRV: OFF
USE_CLML_GRAPH_EXECUTOR: OFF
USE_TFLITE: OFF
USE_HEXAGON_GTEST: /path/to/hexagon/gtest
PICOJSON_PATH: 3rdparty/picojson
USE_OPENCL_ENABLE_HOST_PTR: OFF
INSTALL_DEV: OFF
USE_PROFILER: ON
USE_NNPACK: OFF
LLVM_VERSION: 15.0.7
USE_OPENCL: OFF
COMPILER_RT_PATH: 3rdparty/compiler-rt
RANG_PATH: 3rdparty/rang/include
USE_SPIRV_KHR_INTEGER_DOT_PRODUCT: OFF
USE_OPENMP: OFF
USE_BNNS: OFF
USE_CUBLAS: OFF
USE_METAL: ON
USE_MICRO_STANDALONE_RUNTIME: OFF
USE_HEXAGON_EXTERNAL_LIBS: OFF
USE_ALTERNATIVE_LINKER: AUTO
USE_BYODT_POSIT: OFF
USE_HEXAGON_RPC: OFF
USE_MICRO: OFF
DMLC_PATH: 3rdparty/dmlc-core/include
INDEX_DEFAULT_I64: ON
USE_RELAY_DEBUG: OFF
USE_RPC: ON
USE_TENSORFLOW_PATH: none
TVM_CLML_VERSION: 
USE_MIOPEN: OFF
USE_ROCM: OFF
USE_PAPI: OFF
USE_CURAND: OFF
TVM_CXX_COMPILER_PATH: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++
HIDE_PRIVATE_SYMBOLS: ON

## Additional context

I can still successfully compile ${MODEL_NAME}-${QUANTIZATION}-opencl.so one week ago, now i got the above error. Is it because of this commit?
commit 3f05a1f587871cffabcf5884a515e6eff0e38a53
Author: Hongyi Jin <jinhongyi02@gmail.com>
Date:   Fri Mar 8 17:12:43 2024 -0500

    [Pass] Low batch GEMM using GEMV-like schedule (#1769)
    
    When batch size is small, GEMM in MLP of decode stage can be
    dispatched into a specialized GEMV-like schedule to improve efficiency.
    GEMM with a dynamic var in spatial axis will now be lowered into
    ```python
    if dyn_var <= 8:
        low_batch_gemv()
    else:
        normal_gemm()
    ```

**Comment by PengYoun9** [comment]
I also encountered the same error when compiling llama2-7b-chat-hf on Nvidia A10.

**Comment by tqchen** [comment]
low_batch_gemv is introduced very recently, so likely the wheel will land soon

**Comment by MasterJH5574** [comment]
Hi @sheepHavingPurpleLeaf, the `LowBatchGemvSpecialize` is merged into TVM in this commit https://github.com/apache/tvm/commit/ff0b99c5ce4371ec966cd4fa07ae36351faf2a5e. Given you build TVM from source, could you checkout the latest TVM commit and rebuild TVM? I think that would address the issue.

**Comment by PengYoun9** [comment]
Hi @MasterJH5574 Has Unity been merged into the TVM main branch? According to the MLC documentation, I installed TVM-Unity from the Relax (https://github.com/mlc-ai/relax) . Will future updates be based on TVM or Relax?

**Comment by MasterJH5574** [comment]
The original issue should have been addressed now. Gonna close this issue.
