### ISSUE TITLE
build vicuna-v1-7b error

### ISSUE THREAD

**Issue by sgSillage** [mlc-ai/mlc-llm#194]
when I run `python3 build.py --model vicuna-v1-7b` , I get a error following:
![4eb38723413d8c2fd6c092530b46d6e](https://github.com/mlc-ai/mlc-llm/assets/51256576/87852775-e50d-49a4-a2aa-c191c617dd89)

Does anyone resolve it ?

**Comment by junrushao** [comment]
This is due to a buggy LLVM version (10.0.0). We've updated the wheels recently and please refer to this page for more details: https://mlc.ai/mlc-llm/docs/install/tvm.html
