### ISSUE TITLE
[Question] is it possible to build IOS app from source using Windows laptop? 

### ISSUE THREAD

**Issue by sherelynyap** [mlc-ai/mlc-llm#1945]
## ❓ General Questions

is it possible to build IOS app from source using Windows laptop?  I saw the need to use Xcode in the documentation, but Xcode requires macOS and is not available for Windows. Is there any other way like Flutter, ReactNative etc? I've been having some trouble building the Android app from source, so I want to try IOS. (I personally use Windows laptop and IPhone)

Thanks!

**Comment by MasterJH5574** [comment]
Unfortunately I think you may need a Mac for any iOS app development.
