### ISSUE TITLE
[Bug] mlc_llm.build compilation failure

### ISSUE THREAD

**Issue by panghongtao** [mlc-ai/mlc-llm#1946]
## To Reproduce

When I try to use different versions of model, I always get this error. What do I need to adjust?

1. python -m mlc_llm.build --model Llama-2-7b-chat-hf --target android --max-seq-len 768 --quantization q4f16_1

ERROR_MESSAGE:
Using path "dist\models\Llama-2-7b-chat-hf" for model "Llama-2-7b-chat-hf"
Target configured: opencl -keys=opencl,gpu -max_function_args=128 -max_num_threads=256 -max_shared_memory_per_block=16384 -max_threads_per_block=256 -texture_spatial_limit=16384 -thread_warp_size=1
Automatically using target for weight quantization: vulkan -keys=vulkan,gpu -max_num_threads=256 -max_shared_memory_per_block=49152 -max_threads_per_block=1024 -supports_16bit_buffer=1 -supports_float16=1 -supports_float32=1 -supports_int16=1 -supports_int32=1 -supports_int8=1 -thread_warp_size=1
Get old param:   0%|          | 0/197 [00:00<?, ?tensors/s][18:25:39] D:\a\package\package\tvm\src\tir\analysis\verify_memory.cc:205: RuntimeError: Memory verification failed with the following errors:
    Variable `A` is directly accessed by host memory (it is not contained in a thread environment or in the function arguments.
    Variable `scale` is directly accessed by host memory (it is not contained in a thread environment or in the function arguments.
    Variable `w_gathered` is directly accessed by host memory (it is not contained in a thread environment or in the function arguments.
    Variable `w_gathered` is directly accessed by host memory (it is not contained in a thread environment or in the function arguments.
    Variable `w_gathered` is directly accessed by host memory (it is not contained in a thread environment or in the function arguments.
    Variable `A` is directly accessed by host memory (it is not contained in a thread environment or in the function arguments.
    Variable `scale` is directly accessed by host memory (it is not contained in a thread environment or in the function arguments.
  Did you forget to bind?
# from tvm.script import tir as T

@T.prim_func
def encode4(A: T.Buffer((4096, 11008), "float16"), w_gathered: T.Buffer((4096, 1376), "uint32"), scale: T.Buffer((4096, 344), "float16")):
    T.func_attr({"target": T.target({"host": {"keys": ["cpu"], "kind": "llvm", "tag": ""}, "keys": ["vulkan", "gpu"], "kind": "vulkan", "max_num_threads": 256, "max_shared_memory_per_block": 49152, "max_threads_per_block": 1024, "supports_16bit_buffer": 1, "supports_float16": 1, "supports_float32": T.bool(True), "supports_int16": 1, "supports_int32": T.bool(True), "supports_int8": 1, "tag": "", "thread_warp_size": 1}), "tir.is_scheduled": T.bool(True), "tir.noalias": T.bool(True)})
    max_abs_value = T.allocate([1409024], "float16", "global")
    max_abs_value_1 = T.Buffer((1409024,), "float16", data=max_abs_value)
    A_1 = T.Buffer((45088768,), "float16", data=A.data)
    for i, j, k in T.grid(4096, 344, 32):
        cse_var_1: T.int32 = i * 344 + j
        if k == 0:
            max_abs_value_1[cse_var_1] = T.float16(-65504)
        max_abs_value_1[cse_var_1] = T.max(max_abs_value_1[cse_var_1], T.fabs(A_1[i * 11008 + j * 32 + k]))
    scale_1 = T.Buffer((1409024,), "float16", data=scale.data)
    for i, j in T.grid(4096, 344):
        cse_var_2: T.int32 = i * 344 + j
        scale_1[cse_var_2] = T.max(max_abs_value_1[cse_var_2], T.float16(0.0001)) * T.float16(0.14285714285714285)
    for i, j, k in T.grid(4096, 1376, 8):
        cse_var_3: T.int32 = i * 1376 + j
        w_gathered_1 = T.Buffer((5636096,), "uint32", data=w_gathered.data)
        if k == 0:
            w_gathered_1[cse_var_3] = T.uint32(0)
        w_gathered_1[cse_var_3] = T.bitwise_or(w_gathered_1[cse_var_3], T.shift_left(T.Cast("uint32", T.min(T.max(T.round(A_1[i * 11008 + j * 8 + k] / scale_1[i * 344 + j // 4] + T.float16(7)), T.float16(0)), T.float16(14))), T.Cast("uint32", k) * T.uint32(4)))
Stack trace not available when DMLC_LOG_STACK_TRACE is disabled at compile time.

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\ProgramData\anaconda3\Lib\site-packages\mlc_llm\build.py", line 47, in <module>
    main()
  File "C:\ProgramData\anaconda3\Lib\site-packages\mlc_llm\build.py", line 43, in main
    core.build_model_from_args(parsed_args)
  File "C:\ProgramData\anaconda3\Lib\site-packages\mlc_llm\core.py", line 890, in build_model_from_args
    params = utils.convert_weights(mod_transform, param_manager, params, args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\anaconda3\Lib\site-packages\mlc_llm\utils.py", line 282, in convert_weights
    ex = relax.build(mod_transform, target=target)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\anaconda3\Lib\site-packages\tvm\relax\vm_build.py", line 341, in build
    return _vmlink(
           ^^^^^^^^
  File "C:\ProgramData\anaconda3\Lib\site-packages\tvm\relax\vm_build.py", line 247, in _vmlink
    lib = tvm.build(
          ^^^^^^^^^^
  File "C:\ProgramData\anaconda3\Lib\site-packages\tvm\driver\build_module.py", line 297, in build
    rt_mod_host = _driver_ffi.tir_to_runtime(annotated_mods, target_host)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\anaconda3\Lib\site-packages\tvm\_ffi\_ctypes\packed_func.py", line 239, in __call__
    raise_last_ffi_error()
  File "C:\ProgramData\anaconda3\Lib\site-packages\tvm\_ffi\base.py", line 481, in raise_last_ffi_error
    raise py_err
tvm._ffi.base.TVMError: Traceback (most recent call last):
  Did you forget to bind?
    Variable `scale` is directly accessed by host memory (it is not contained in a thread environment or in the function arguments.
    Variable `A` is directly accessed by host memory (it is not contained in a thread environment or in the function arguments.
    Variable `w_gathered` is directly accessed by host memory (it is not contained in a thread environment or in the function arguments.
    Variable `w_gathered` is directly accessed by host memory (it is not contained in a thread environment or in the function arguments.
    Variable `w_gathered` is directly accessed by host memory (it is not contained in a thread environment or in the function arguments.
    Variable `scale` is directly accessed by host memory (it is not contained in a thread environment or in the function arguments.
    Variable `A` is directly accessed by host memory (it is not contained in a thread environment or in the function arguments.
  File "D:\a\package\package\tvm\src\tir\analysis\verify_memory.cc", line 205
RuntimeError: Memory verification failed with the following errors:
# from tvm.script import tir as T

@T.prim_func
def encode4(A: T.Buffer((4096, 11008), "float16"), w_gathered: T.Buffer((4096, 1376), "uint32"), scale: T.Buffer((4096, 344), "float16")):
    T.func_attr({"target": T.target({"host": {"keys": ["cpu"], "kind": "llvm", "tag": ""}, "keys": ["vulkan", "gpu"], "kind": "vulkan", "max_num_threads": 256, "max_shared_memory_per_block": 49152, "max_threads_per_block": 1024, "supports_16bit_buffer": 1, "supports_float16": 1, "supports_float32": T.bool(True), "supports_int16": 1, "supports_int32": T.bool(True), "supports_int8": 1, "tag": "", "thread_warp_size": 1}), "tir.is_scheduled": T.bool(True), "tir.noalias": T.bool(True)})
    max_abs_value = T.allocate([1409024], "float16", "global")
    max_abs_value_1 = T.Buffer((1409024,), "float16", data=max_abs_value)
    A_1 = T.Buffer((45088768,), "float16", data=A.data)
    for i, j, k in T.grid(4096, 344, 32):
        cse_var_1: T.int32 = i * 344 + j
        if k == 0:
            max_abs_value_1[cse_var_1] = T.float16(-65504)
        max_abs_value_1[cse_var_1] = T.max(max_abs_value_1[cse_var_1], T.fabs(A_1[i * 11008 + j * 32 + k]))
    scale_1 = T.Buffer((1409024,), "float16", data=scale.data)
    for i, j in T.grid(4096, 344):
        cse_var_2: T.int32 = i * 344 + j
        scale_1[cse_var_2] = T.max(max_abs_value_1[cse_var_2], T.float16(0.0001)) * T.float16(0.14285714285714285)
    for i, j, k in T.grid(4096, 1376, 8):
        cse_var_3: T.int32 = i * 1376 + j
        w_gathered_1 = T.Buffer((5636096,), "uint32", data=w_gathered.data)
        if k == 0:
            w_gathered_1[cse_var_3] = T.uint32(0)
        w_gathered_1[cse_var_3] = T.bitwise_or(w_gathered_1[cse_var_3], T.shift_left(T.Cast("uint32", T.min(T.max(T.round(A_1[i * 11008 + j * 8 + k] / scale_1[i * 344 + j // 4] + T.float16(7)), T.float16(0)), T.float16(14))), T.Cast("uint32", k) * T.uint32(4)))

## Environment

 - Platform (Android):
 - Operating system (Windows):
 - Device (RTX A4000)
 - How you installed MLC-LLM (conda):
 - How you installed TVM-Unity (pip):
 - Python version (3.11):
 - GPU driver version (if applicable):
 - CUDA/cuDNN version (12.2):
 - TVM Unity Hash Tag (`python -c "import tvm; print('\n'.join(f'{k}: {v}' for k, v in tvm.support.libinfo().items()))"`, applicable if you compile models):
 - Any other relevant information:

**Comment by shreygupta2809** [comment]
The API you are using is now deprecated, can you please try this again using the latest API? You can refer to the [docs](https://llm.mlc.ai/docs/deploy/android.html) for the commands to compile for Android.

**Comment by shreygupta2809** [comment]
This command which you are mentioning is the old deprecated API, which might not work. Is the latest command sequence on the documentation using mlc_llm convert_weight, gen_config and compile resulting in the same above issue?

**Comment by panghongtao** [comment]
> This command which you are mentioning is the old deprecated API, which might not work. Is the latest command sequence on the documentation using mlc_llm convert_weight, gen_config and compile resulting in the same above issue? If so could you please share the commands you are running with the flags. Thanks

W9057210@PAW9057210 MINGW64 /f/project/mlc-llm (main)
$ python mlc_llm convert_weight ./dist/models/$MODEL_NAME/ --quantization $QUANTIZATION -o dist/$MODEL_NAME-$QUANTIZATION-MLC/
C:\ProgramData\anaconda3\python.exe: can't open file 'F:\\project\\mlc-llm\\mlc_llm': [Errno 2] No such file or directory

I tried using the new API command. But it tells me the path is wrong. Is this directory I am currently in incorrect?

**Comment by panghongtao** [comment]
W9057210@PAW9057210 MINGW64 /f/project/mlc-llm (main)
$ python -m mlc_llm convert_weight dist/models/Llama-2-7b-chat-hf/ --quantization q4f16_1 -o dist/Llama-2-7b-chat-hf-q4f16_1-MLC
C:\ProgramData\anaconda3\python.exe: No module named mlc_llm.__main__; 'mlc_llm' is a package and cannot be directly executed

I tried to use the new command, and there was another error. How do I handle this error?

**Comment by shreygupta2809** [comment]
Recently `mlc_chat` was renamed to `mlc_llm`. The documentation has been updated according to that. You may need to pull the latest changes, build MLC again, and then try the above command again. OR if you are on the previous version, just replacing `mlc_llm` with `mlc_chat` in the above command should work most probably.

**Comment by zhongzhenluo** [comment]
I also got the same errors when using the depreciated version of mlc-llm to compile the llm models.  
RuntimeError: Memory verification failed with the following errors:
# from tvm.script import tir as T
it may due to API break

**Comment by panghongtao** [comment]
> Recently `mlc_chat` was renamed to `mlc_llm` [PR](https://github.com/mlc-ai/mlc-llm/pull/1932). The documentation has been updated according to that. You may need to pull the latest changes, build MLC again, and then try the above command again. OR if you are on the previous version, just replacing `mlc_llm` with `mlc_chat` in the above command should work most probably.

I re-downloaded this project from GITHUB. And create a new python environment using conda. But this error still occurs. Others suggested that I clean up all.py files. I don't know how to clean it all up. There is no.py file in this project. Only other projects have.py files. Is the clean.py file under this project folder? Or clean up.py files from other disks?

**Comment by shreygupta2809** [comment]
How are you installing MLC? Could you try building it from source.

**Comment by MasterJH5574** [comment]
Closing this issue for now. To summarize, we have finished the deprecation of the old compilation flow (`mlc_llm.build`). Documentation page https://llm.mlc.ai/docs/compilation/compile_models.html has the up-to-date steps with regard to our new compilation flow.
