### ISSUE TITLE
[Bug] Encountering error on executing  “./prepare_libs.sh” command

### ISSUE THREAD

**Issue by AashiDutt** [mlc-ai/mlc-llm#1947]
## ❓ Error Encountered

Encountering error on executing  “**./prepare_libs.sh**” command

**FileNotFoundError: [Errno 2] No such file or directory: 'Library/Android/sdk/ndk/26.2.11394342/toolchains/llvm/prebuilt/darwin-x86_64/bin/llvm-ar'** 

[_File exists on listing the folder contents_]

The system env paths set are as follows: 

**ANDROID_NDK**=Library/Android/sdk/ndk/26.2.11394342

**TVM_NDK_CC**=$ANDROID_NDK/toolchains/llvm/prebuilt/darwin-x86_64/bin/aarch64-linux-android24-clang

**JAVA_HOME**="/Applications/Android Studio.app/Contents/jbr/Contents/Home"

**TVM_HOME**="/Users/aashidutt/Downloads/gemini/mlc-llm/3rdparty/tvm/include/tvm/runtime"

<img width="1047" alt="Screenshot 2024-03-13 at 4 41 29 PM" src="https://github.com/mlc-ai/mlc-llm/assets/25379502/389237de-0900-490f-bc08-3a994edd3525">

**Comment by NSTiwari** [comment]
@Kartik14: I'm also facing the issue. Can you please check? OS is MacOS.

**Comment by tqchen** [comment]
seems was due to env setup where llvm-ar was not available in the NDK, might be useful to lookup the directory and check
