### ISSUE TITLE
[Question] Failed to load dynamic shared library

### ISSUE THREAD

**Issue by BoiledFiish** [mlc-ai/mlc-llm#1949]
## ❓ General Questions

I wonder how to solve this problem when deploying  Llama-2-7b-chat-hf-q4f16_1-MLC.
![image](https://github.com/mlc-ai/mlc-llm/assets/132544432/e3d9dc5d-6d6d-4bad-88e3-0e1bc24d853f)
p.s. The pre-compiled model library was downloaded by using the command "git clone https://github.com/mlc-ai/binary-mlc-llm-libs.git dist/prebuilt/lib".

**Comment by tqchen** [comment]
try to omit the model-lib-path and see if it automatically jit a verison

**Comment by BoiledFiish** [comment]
> try to omit the model-lib-path and see if it automatically jit a verison

the ouput would be like this😭
![image](https://github.com/mlc-ai/mlc-llm/assets/132544432/68ea1b4a-f767-4ade-8d64-20605fd74901)

**Comment by shreygupta2809** [comment]
Did you use the prebuilt TVM-Unity and MLC-LLM libraries? If so this seems to be similar to #1873

**Comment by MasterJH5574** [comment]
How is the issue going? I am gonna close this due to inactivity. You are welcome to open a new issue if things persist.
