### ISSUE TITLE
Using instructions from website returns Cannot find "mlc-chat-config.json" in path "dist/vicuna-v1-7b-q3f16_0/params/

### ISSUE THREAD

**Issue by GrindamN** [mlc-ai/mlc-llm#195]
As the title states, I've tried to run MLC LLM using miniconda, but at the last step, it tells me that there is no configuration file present in any of the folders.

**Comment by giovanith** [comment]
Me too

Windows 10.. same error

**Comment by tqchen** [comment]
Please try to follow the latest instruction here https://mlc.ai/mlc-llm/#windows-linux-mac and (uninstall/reinstall the mlc-chat-nightly via `conda install -c mlc-ai -c conda-forge mlc-chat-nightly --force-reinstall`)

**Comment by giovanith** [comment]
> Please try to follow the latest instruction here https://mlc.ai/mlc-llm/#windows-linux-mac and (uninstall/reinstall the mlc-chat-nightly via `conda install -c mlc-ai -c conda-forge mlc-chat-nightly --force-reinstall`)

Thank you, I follow the instructions and it run
