### ISSUE TITLE
[Bug] vm.builtin.attention_kv_cache_enable_sliding_window_for_seq

### ISSUE THREAD

**Issue by wanderHZ** [mlc-ai/mlc-llm#1969]
## To Reproduce

1. build libmlc_llm.so and libtvm_runtime.so
```
# Android config
ANDROID_NDK=$ANDROID_NDK
ANDROID_ABI=arm64-v8a
ANDROID_PLATFORM=android-27

arch=$(uname)-$(uname -m)
root=$(cd $(dirname $0);pwd)

rm -rf build_android
mkdir -p build_android
cd build_android
python ../cmake/gen_cmake_config.py
cd ../
cmake -B build_android \
        -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK/build/cmake/android.toolchain.cmake \
        -DANDROID_ABI=$ANDROID_ABI \
        -DANDROID_NDK=$ANDROID_NDK \
        -DANDROID_PLATFORM=$ANDROID_PLATFORM \
        -DBUILD_ARCH=$ANDROID_ABI
cmake --build build_android -j8
```

2. use mlc-llm in the following way：
```
...

this->infer_engine = new tvm::runtime::Module();
*this->infer_engine = mlc::llm::CreateChatModule(device);

this->reload = this->infer_engine->GetFunction("reload");
this->reload(model_lib_path, model_context_path);

...
```

## Expected behavior

```
mlc-llm/cpp/llm_chat.cc:175: Check failed: (f != nullptr) is false: ValueError: Cannot find function vm.builtin.attention_kv_cache_enable_sliding_window_for_seq

Stack trace not available when DMLC_LOG_STACK_TRACE is disabled at compile time.
```

## Environment

 - Platform (Android:OpenCL):
 - How you installed MLC-LLM (source):
 - How you installed TVM-Unity (source):
 - Python version (3.11):
 - TVM Unity Hash Tag (`python -c "import tvm; print('\n'.join(f'{k}: {v}' for k, v in tvm.support.libinfo().items()))"`, applicable if you compile models):
 USE_NVTX: OFF
USE_GTEST: AUTO
SUMMARIZE: OFF
USE_IOS_RPC: OFF
USE_MSC: OFF
USE_ETHOSU: OFF
CUDA_VERSION: NOT-FOUND
USE_LIBBACKTRACE: AUTO
DLPACK_PATH: 3rdparty/dlpack/include
USE_TENSORRT_CODEGEN: OFF
USE_THRUST: OFF
USE_TARGET_ONNX: OFF
USE_AOT_EXECUTOR: ON
BUILD_DUMMY_LIBTVM: OFF
USE_CUDNN: OFF
USE_TENSORRT_RUNTIME: OFF
USE_ARM_COMPUTE_LIB_GRAPH_EXECUTOR: OFF
USE_CCACHE: AUTO
USE_ARM_COMPUTE_LIB: OFF
USE_CPP_RTVM: OFF
USE_OPENCL_GTEST: /path/to/opencl/gtest
USE_MKL: OFF
USE_PT_TVMDSOOP: OFF
MLIR_VERSION: NOT-FOUND
USE_CLML: OFF
USE_STACKVM_RUNTIME: OFF
USE_GRAPH_EXECUTOR_CUDA_GRAPH: OFF
ROCM_PATH: /opt/rocm
USE_DNNL: OFF
USE_VITIS_AI: OFF
USE_MLIR: OFF
USE_RCCL: OFF
USE_LLVM: llvm-config --ignore-libllvm --link-static
USE_VERILATOR: OFF
USE_TF_TVMDSOOP: OFF
USE_THREADS: ON
USE_MSVC_MT: OFF
BACKTRACE_ON_SEGFAULT: OFF
USE_GRAPH_EXECUTOR: ON
USE_NCCL: OFF
USE_ROCBLAS: OFF
GIT_COMMIT_HASH: 641209c69ad153c02471ba71bdf40a10c90789e5
USE_VULKAN: OFF
USE_RUST_EXT: OFF
USE_CUTLASS: OFF
USE_CPP_RPC: OFF
USE_HEXAGON: OFF
USE_CUSTOM_LOGGING: OFF
USE_UMA: OFF
USE_FALLBACK_STL_MAP: OFF
USE_SORT: ON
USE_RTTI: ON
GIT_COMMIT_TIME: 2024-03-13 15:48:49 -0400
USE_HEXAGON_SDK: /path/to/sdk
USE_BLAS: none
USE_ETHOSN: OFF
USE_LIBTORCH: OFF
USE_RANDOM: ON
USE_CUDA: OFF
USE_COREML: OFF
USE_AMX: OFF
BUILD_STATIC_RUNTIME: OFF
USE_CMSISNN: OFF
USE_KHRONOS_SPIRV: OFF
USE_CLML_GRAPH_EXECUTOR: OFF
USE_TFLITE: OFF
USE_HEXAGON_GTEST: /path/to/hexagon/gtest
PICOJSON_PATH: 3rdparty/picojson
USE_OPENCL_ENABLE_HOST_PTR: OFF
INSTALL_DEV: OFF
USE_PROFILER: ON
USE_NNPACK: OFF
LLVM_VERSION: 15.0.7
USE_MRVL: OFF
USE_OPENCL: ON
COMPILER_RT_PATH: 3rdparty/compiler-rt
RANG_PATH: 3rdparty/rang/include
USE_SPIRV_KHR_INTEGER_DOT_PRODUCT: OFF
USE_OPENMP: none
USE_BNNS: OFF
USE_FLASHINFER: 
USE_CUBLAS: OFF
USE_METAL: ON
USE_MICRO_STANDALONE_RUNTIME: OFF
USE_HEXAGON_EXTERNAL_LIBS: OFF
USE_ALTERNATIVE_LINKER: AUTO
USE_BYODT_POSIT: OFF
USE_HEXAGON_RPC: OFF
USE_MICRO: OFF
DMLC_PATH: 3rdparty/dmlc-core/include
INDEX_DEFAULT_I64: ON
USE_RELAY_DEBUG: OFF
USE_RPC: ON
USE_TENSORFLOW_PATH: none
TVM_CLML_VERSION: 
USE_MIOPEN: OFF
USE_ROCM: OFF
USE_PAPI: OFF
USE_CURAND: OFF
TVM_CXX_COMPILER_PATH: /Library/Developer/CommandLineTools/usr/bin/c++
HIDE_PRIVATE_SYMBOLS: ON

## Additional context

I didn't have this problem a few days ago, I suspect it's caused by this PR：https://github.com/mlc-ai/mlc-llm/commit/edffce44c55539ca43c3eff4b4022dd628205cb7

**Comment by MasterJH5574** [comment]
Hi @wanderHZ, thanks for reporting. The PR which introduced sliding window support in PagedKVCache was merged yesterday https://github.com/apache/tvm/pull/16729. Could you checkout the latest TVM, rebuild TVM, and try again?

**Comment by wanderHZ** [comment]
Thank you for your prompt reply. It is indeed an issue with the TVM version. I have tried the latest TVM and this issue has been resolved.

**Comment by MrRace** [comment]
> Thank you for your prompt reply. It is indeed an issue with the TVM version. I have tried the latest TVM and this issue has been resolved.

What is the latest TVM do you use? you get it from  https://mlc.ai/wheels ?

**Comment by MrRace** [comment]
@Kartik14 I still encounter errors even when using:
```
mlc_ai_nightly_cu122-0.15.dev154-cp311-cp311-manylinux_2_28_x86_64.whl
mlc_llm_nightly_cu122-0.1.dev1002-cp311-cp311-manylinux_2_28_x86_64.whl
```
error:
```
MLCChat failed

Stack trace:
org.apache.tvm.Base$TVMError: ValueError: Check failed: (f != nullptr) is false: Cannot find function vm.builtin.attention_kv_cache_enable_sliding_window_for_seq
Stack trace:
  File "/share/home/Repository/mlc-llm/cpp/[llm_chat.cc](http://llm_chat.cc/)", line 175

	at org.apache.tvm.Base.checkCall(Base.java:173)
	at org.apache.tvm.Function.invoke(Function.java:130)
	at ai.mlc.mlcllm.ChatModule.reload(ChatModule.java:46)
	at ai.mlc.mlcchat.AppViewModel$ChatState$mainReloadChat$1$2.invoke(AppViewModel.kt:648)
	at ai.mlc.mlcchat.AppViewModel$ChatState$mainReloadChat$1$2.invoke(AppViewModel.kt:646)
	at ai.mlc.mlcchat.AppViewModel$ChatState.callBackend(AppViewModel.kt:548)
	at ai.mlc.mlcchat.AppViewModel$ChatState.mainReloadChat$lambda$3(AppViewModel.kt:646)
	at ai.mlc.mlcchat.AppViewModel$ChatState.$r8$lambda$CXL6v4mjTu_Sr5Pk2zFDcus0R-8(Unknown Source:0)
	at ai.mlc.mlcchat.AppViewModel$ChatState$$ExternalSyntheticLambda2.run(Unknown Source:8)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:463)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at java.lang.Thread.run(Thread.java:1012)


Error message:
ValueError: Check failed: (f != nullptr) is false: Cannot find function vm.builtin.attention_kv_cache_enable_sliding_window_for_seq
Stack trace:
  File "/share/home/Repository/mlc-llm/cpp/[llm_chat.cc](http://llm_chat.cc/)", line 175
```

**Comment by sbwww** [comment]
@MrRace pull newer mlc-llm and update submodule will help

**Comment by wanderHZ** [comment]
I compiled the source code, not the installed wheel. You can manually update 3rdparty/tvm to the latest version of tvm, as mentioned above.
