### ISSUE TITLE
mlc-llm/3rdparty/tvm/src/runtime/memory/memory_manager.cc:115: InternalError: Check failed: (offset + needed_size <= this->buffer.size) is false: storage allocation failure, attempted to allocate 2048 at offset 0 in region that is 0bytes Stack trace:

### ISSUE THREAD

**Issue by musram** [mlc-ai/mlc-llm#1987]
## ❓ General Questions

I am porting opus-mt-it-en to vulkan device.
During the decode step,  i get this error

         [20:46:58] /home/****/softwares/programs/python_projects/tvm-framework/source-build-support-tvm-mlc/mlc-llm/3rdparty/tvm/src/runtime/memory/memory_manager.cc:115: InternalError: Check failed: (offset + needed_size <= this->buffer.size) is false: storage allocation failure, attempted to allocate 2048 at offset 0 in region that is 0bytes
Stack trace:
  [bt] (0) /home/*****/softwares/programs/python_projects/tvm-framework/source-build-support-tvm-mlc/mlc-llm/build/tvm/libtvm_runtime.so(tvm::runtime::Backtrace[abi:cxx11]()+0x27) [0x7ffff7312f17]
  [bt] (1) /home/*****/softwares/programs/python_projects/tvm-framework/source-build-support-tvm-mlc/mlc-llm/build/mlc_chat_cli(tvm::runtime::detail::LogFatal::Entry::Finalize()+0x37) [0x555555567057]
  [bt] (2) /home/*****/softwares/programs/python_projects/tvm-framework/source-build-support-tvm-mlc/mlc-llm/build/tvm/libtvm_runtime.so(+0x1161f4) [0x7ffff73161f4]
  [bt] (3) /home/*****/softwares/programs/python_projects/tvm-framework/source-build-support-tvm-mlc/mlc-llm/build/tvm/libtvm_runtime.so(tvm::runtime::memory::StorageObj::AllocNDArray(long, tvm::runtime::ShapeTuple, DLDataType)+0x5d7) [0x7ffff7316cb7]
  [bt] (4) /home/*****/softwares/programs/python_projects/tvm-framework/source-build-support-tvm-mlc/mlc-llm/build/tvm/libtvm_runtime.so(tvm::runtime::TypedPackedFunc<tvm::runtime::NDArray (tvm::runtime::memory::Storage, long, tvm::runtime::ShapeTuple, DLDataType)>::AssignTypedLambda<tvm::runtime::Registry::set_body_method<tvm::runtime::memory::Storage, tvm::runtime::memory::StorageObj, tvm::runtime::NDArray, long, tvm::runtime::ShapeTuple, DLDataType, void>(tvm::runtime::NDArray (tvm::runtime::memory::StorageObj::*)(long, tvm::runtime::ShapeTuple, DLDataType))::{lambda(tvm::runtime::memory::Storage, long, tvm::runtime::ShapeTuple, DLDataType)#1}>(tvm::runtime::Registry::set_body_method<tvm::runtime::memory::Storage, tvm::runtime::memory::StorageObj, tvm::runtime::NDArray, long, tvm::runtime::ShapeTuple, DLDataType, void>(tvm::runtime::NDArray (tvm::runtime::memory::StorageObj::*)(long, tvm::runtime::ShapeTuple, DLDataType))::{lambda(tvm::runtime::memory::Storage, long, tvm::runtime::ShapeTuple, DLDataType)#1}, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)::{lambda(tvm::runtime::TVMArgs const&, tvm::runtime::TVMRetValue*)#1}::operator()(tvm::runtime::TVMArgs const&, tvm::runtime::TVMRetValue*) const+0x288) [0x7ffff736bf68]
  [bt] (5) /home/*****/softwares/programs/python_projects/tvm-framework/source-build-support-tvm-mlc/mlc-llm/build/tvm/libtvm_runtime.so(tvm::runtime::PackedFuncObj::Extractor<tvm::runtime::PackedFuncSubObj<tvm::runtime::TypedPackedFunc<tvm::runtime::NDArray (tvm::runtime::memory::Storage, long, tvm::runtime::ShapeTuple, DLDataType)>::AssignTypedLambda<tvm::runtime::Registry::set_body_method<tvm::runtime::memory::Storage, tvm::runtime::memory::StorageObj, tvm::runtime::NDArray, long, tvm::runtime::ShapeTuple, DLDataType, void>(tvm::runtime::NDArray (tvm::runtime::memory::StorageObj::*)(long, tvm::runtime::ShapeTuple, DLDataType))::{lambda(tvm::runtime::memory::Storage, long, tvm::runtime::ShapeTuple, DLDataType)#1}>(tvm::runtime::Registry::set_body_method<tvm::runtime::memory::Storage, tvm::runtime::memory::StorageObj, tvm::runtime::NDArray, long, tvm::runtime::ShapeTuple, DLDataType, void>(tvm::runtime::NDArray (tvm::runtime::memory::StorageObj::*)(long, tvm::runtime::ShapeTuple, DLDataType))::{lambda(tvm::runtime::memory::Storage, long, tvm::runtime::ShapeTuple, DLDataType)#1}, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)::{lambda(tvm::runtime::TVMArgs const&, tvm::runtime::TVMRetValue*)#1}> >::Call(tvm::runtime::PackedFuncObj const*, tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*)+0x15) [0x7ffff736c0e5]
  [bt] (6) /home/*****/softwares/programs/python_projects/tvm-framework/source-build-support-tvm-mlc/mlc-llm/build/tvm/libtvm_runtime.so(tvm::runtime::relax_vm::VirtualMachineImpl::RunInstrCall(tvm::runtime::relax_vm::VMFrame*, tvm::runtime::relax_vm::Instruction)+0x930) [0x7ffff73ade30]
  [bt] (7) /home/*****/softwares/programs/python_projects/tvm-framework/source-build-support-tvm-mlc/mlc-llm/build/tvm/libtvm_runtime.so(tvm::runtime::relax_vm::VirtualMachineImpl::RunLoop()+0x247) [0x7ffff73ab577]
  [bt] (8) /home/*****/softwares/programs/python_projects/tvm-framework/source-build-support-tvm-mlc/mlc-llm/build/tvm/libtvm_runtime.so(tvm::runtime::relax_vm::VirtualMachineImpl::InvokeBytecode(long, std::vector<tvm::runtime::TVMRetValue, std::allocator<tvm::runtime::TVMRetValue> > const&)+0x254) [0x7ffff73ab9e4]

I printed the outputs from  mlc-llm/3rdparty/tvm/src/runtime/memory/memory_manager.cc:, which are as follows.

AllocNDArray108
[1, 512]float32
offset: 0 needed_size: 2048 buffer.size: 4096
AllocNDArray108
[1, 1, 512]float32
offset: 0 needed_size: 2048 buffer.size: 4096
AllocNDArray108
[1, 1, 512]float32
offset: 0 needed_size: 2048 buffer.size: 4096
AllocNDArray108
[1, 1, 512]float32
offset: 0 needed_size: 2048 buffer.size: 4096
AllocNDArray108
[1, 1, 512]float32
offset: 0 needed_size: 2048 buffer.size: 4096
AllocNDArray108
[1, 1, 512]float32
offset: 0 needed_size: 2048 buffer.size: 8192
AllocNDArray108
[1, 8, 1, 64]float32
offset: 0 needed_size: 2048 buffer.size: 0

so  its failing while allocating tensor of [1, 8, 1, 64] as buffer.size = 0 

Timely help is appreciated.
@junrushao

**Comment by musram** [comment]
@MasterJH5574   I saw this reply  https://github.com/mlc-ai/mlc-llm/issues/1327#issuecomment-1825827557.  vocab size of  opus-mt-it-en size is > 80000. But the error happens during the creation of NDarray [1,8,1,64].

**Comment by sheepHavingPurpleLeaf** [comment]
hi，I have met similar error when serving with this command:

**Comment by MasterJH5574** [comment]
Thank you @sheepHavingPurpleLeaf for reporting! I checked a bit and have some fix now in #2463. Could you please checkout the latest commit and try it out? Particularly, you would need to first run `mlc_llm gen_config` again, and then run `mlc_llm compile` again, and finally try run `mlc_llm serve` under the `server` mode.

**Comment by sheepHavingPurpleLeaf** [comment]
> Thank you @sheepHavingPurpleLeaf for reporting! I checked a bit and have some fix now in #2463. Could you please checkout the latest commit and try it out? Particularly, you would need to first run `mlc_llm gen_config` again, and then run `mlc_llm compile` again, and finally try run `mlc_llm serve` under the `server` mode.
> 
> Let me know if you encounter further problems. We can also open new issues given this original issue was stale.

thank you for the quick reply. I pulled the newest code and tried compile tvm and mlc_llm from source. During the compilation of mlc_llm I got the following error:

/mlc-llm/3rdparty/tvm/3rdparty/flashinfer/include/flashinfer/attention/prefill.cuh(1144): error: static assertion failed
    static_assert(group_size == 1 || group_size % 4 == 0 || group_size == 6);
    ^
          detected during:
            instantiation of "void flashinfer::BatchPrefillWithRaggedKVCacheKernel<group_size,causal,kv_layout,pos_encoding_mode,num_frags_x,num_frags_y,num_frags_z,num_warps,DTypeIn,DTypeQKAccum,DTypeOut,IdType>(DTypeIn *, IdType *, IdType *, IdType *, DTypeIn *, DTypeIn *, IdType *, IdType *, IdType *, DTypeOut *, float *, float *, uint32_t, float, float, float) [with group_size=5U, causal=false, kv_layout=flashinfer::QKVLayout::kNHD, pos_encoding_mode=flashinfer::PosEncodingMode::kNone, num_frags_x=1U, num_frags_y=4U, num_frags_z=2U, num_warps=4U, DTypeIn=half, DTypeQKAccum=half, DTypeOut=half, IdType=int32_t]" at line 1826
            instantiation of "cudaError_t flashinfer::BatchPrefillWithRaggedKVCacheDispatched<num_frags_x,GROUP_SIZE,HEAD_DIM,KV_LAYOUT,pos_encoding_mode,ALLOW_FP16_QK_REDUCTION,CAUSAL,DTypeIn,DTypeOut,IdType>(DTypeIn *, IdType *, IdType *, IdType *, DTypeIn *, DTypeIn *, IdType *, IdType *, IdType *, DTypeOut *, float *, float *, uint32_t, uint32_t, uint32_t, float, float, float, cudaStream_t) [with num_frags_x=1U, GROUP_SIZE=5U, HEAD_DIM=64U, KV_LAYOUT=flashinfer::QKVLayout::kNHD, pos_encoding_mode=flashinfer::PosEncodingMode::kNone, ALLOW_FP16_QK_REDUCTION=true, CAUSAL=false, DTypeIn=half, DTypeOut=half, IdType=int32_t]" at line 5 of /cfs-mFSLFh1g3x.lb-9400f8e5/ziyeyang/tvm_serve/mlc-llm/3rdparty/tvm/3rdparty/flashinfer/src/generated/batch_ragged_prefill_group_5_head_64_layout_0_posenc_0_fp16qkred_true_causal_false_dtypein_f16_dtypeout_f16_idtype_i32.cu

I was building with these command:
# 3. mlc-llm build
# create build directory
rm -rf build
mkdir -p build&& cd build
#generate build configuration
python3 ../cmake/gen_cmake_config.py
echo "set(USE_THRUST ON)" >> config.cmake
#build mlc_llm libraries
cmake .. && cmake --build . --parallel 8 && cd ..

and my setup are:
Enter TVM_SOURCE_DIR in absolute path. If not specified, 3rdparty/tvm will be used by default: 
Use CUDA? (y/n): y
Use CUTLASS? (y/n): y
Use CUBLAS? (y/n): y
Use ROCm? (y/n): n
Use Vulkan? (y/n): n
Use Metal (Apple M1/M2 GPU) ? (y/n): n
Use OpenCL? (y/n) n
Use OpenCLHostPtr? (y/n): n
Use FlashInfer? (need CUDA w/ compute capability 80;86;89;90) (y/n): y
Enter your CUDA compute capability: 80

Writing the following configuration to config.cmake...
set(TVM_SOURCE_DIR 3rdparty/tvm)
set(CMAKE_BUILD_TYPE RelWithDebInfo)
set(USE_CUDA ON)
set(USE_CUTLASS ON)
set(USE_CUBLAS ON)
set(USE_ROCM OFF)
set(USE_VULKAN OFF)
set(USE_METAL OFF)
set(USE_OPENCL OFF)
set(USE_OPENCL_ENABLE_HOST_PTR OFF)
set(USE_THRUST ON)
set(USE_FLASHINFER ON)
set(FLASHINFER_CUDA_ARCHITECTURES 80)
set(CMAKE_CUDA_ARCHITECTURES 80)

I was trying to build it on Ubuntu 20.04 with CUDA 12.2 to run llm on Nvidia A100

**Comment by MasterJH5574** [comment]
@sheepHavingPurpleLeaf I see. This is caused by a recent FlashInfer version bump which requires some options being explicitly given. Could you add the lines below to your `build/config.cmake`?

```
set(FLASHINFER_ENABLE_FP8 OFF)
set(FLASHINFER_ENABLE_BF16 OFF)
set(FLASHINFER_GEN_GROUP_SIZES 1 4 6 8)
set(FLASHINFER_GEN_PAGE_SIZES 16)
set(FLASHINFER_GEN_HEAD_DIMS 128)
set(FLASHINFER_GEN_KV_LAYOUTS 0 1)
set(FLASHINFER_GEN_POS_ENCODING_MODES 0 1)
set(FLASHINFER_GEN_ALLOW_FP16_QK_REDUCTIONS "false")
set(FLASHINFER_GEN_CASUALS "false" "true")
```

**Comment by sheepHavingPurpleLeaf** [comment]
> @sheepHavingPurpleLeaf I see. This is caused by a recent FlashInfer version bump which requires some options being explicitly given. Could you add the lines below to your `build/config.cmake`?
> 
> ```
> set(FLASHINFER_ENABLE_FP8 OFF)
> set(FLASHINFER_ENABLE_BF16 OFF)
> set(FLASHINFER_GEN_GROUP_SIZES 1 4 6 8)
> set(FLASHINFER_GEN_PAGE_SIZES 16)
> set(FLASHINFER_GEN_HEAD_DIMS 128)
> set(FLASHINFER_GEN_KV_LAYOUTS 0 1)
> set(FLASHINFER_GEN_POS_ENCODING_MODES 0 1)
> set(FLASHINFER_GEN_ALLOW_FP16_QK_REDUCTIONS "false")
> set(FLASHINFER_GEN_CASUALS "false" "true")
> ```

mlc_llm can be successfully compiled after adding these to config.cmake. but got another undefined symbol error:
mlc_llm chat -h
Traceback (most recent call last):
  File "/cfs-mFSLFh1g3x.lb-9400f8e5/miniconda3/envs/tvm_cuda118/bin/mlc_llm", line 33, in <module>
    sys.exit(load_entry_point('mlc-llm', 'console_scripts', 'mlc_llm')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/cfs-mFSLFh1g3x.lb-9400f8e5/miniconda3/envs/tvm_cuda118/bin/mlc_llm", line 25, in importlib_load_entry_point
    return next(matches).load()
           ^^^^^^^^^^^^^^^^^^^^
  File "/cfs-mFSLFh1g3x.lb-9400f8e5/miniconda3/envs/tvm_cuda118/lib/python3.11/importlib/metadata/__init__.py", line 202, in load
    module = import_module(match.group('module'))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/cfs-mFSLFh1g3x.lb-9400f8e5/miniconda3/envs/tvm_cuda118/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1126, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/cfs-mFSLFh1g3x.lb-9400f8e5/tvm_serve/mlc-llm/python/mlc_llm/__init__.py", line 6, in <module>
    from . import protocol, serve
  File "/cfs-mFSLFh1g3x.lb-9400f8e5/tvm_serve/mlc-llm/python/mlc_llm/serve/__init__.py", line 4, in <module>
    from .. import base
  File "/cfs-mFSLFh1g3x.lb-9400f8e5/tvm_serve/mlc-llm/python/mlc_llm/base.py", line 47, in <module>
    _LIB, _LIB_PATH = _load_mlc_llm_lib()
                      ^^^^^^^^^^^^^^^^^^^
  File "/cfs-mFSLFh1g3x.lb-9400f8e5/tvm_serve/mlc-llm/python/mlc_llm/base.py", line 24, in _load_mlc_llm_lib
    return ctypes.CDLL(lib_path[0]), lib_path[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/cfs-mFSLFh1g3x.lb-9400f8e5/miniconda3/envs/tvm_cuda118/lib/python3.11/ctypes/__init__.py", line 376, in __init__
    self._handle = _dlopen(self._name, mode)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: /cfs-mFSLFh1g3x.lb-9400f8e5/ziyeyang/tvm_serve/mlc-llm/build/libmlc_llm_module.so: undefined symbol: _ZN3tvm7runtime7NDArray10CreateViewENS0_10ShapeTupleE10DLDataTypem

**Comment by sheepHavingPurpleLeaf** [comment]
> @sheepHavingPurpleLeaf I see. This is caused by a recent FlashInfer version bump which requires some options being explicitly given. Could you add the lines below to your `build/config.cmake`?
> 
> ```
> set(FLASHINFER_ENABLE_FP8 OFF)
> set(FLASHINFER_ENABLE_BF16 OFF)
> set(FLASHINFER_GEN_GROUP_SIZES 1 4 6 8)
> set(FLASHINFER_GEN_PAGE_SIZES 16)
> set(FLASHINFER_GEN_HEAD_DIMS 128)
> set(FLASHINFER_GEN_KV_LAYOUTS 0 1)
> set(FLASHINFER_GEN_POS_ENCODING_MODES 0 1)
> set(FLASHINFER_GEN_ALLOW_FP16_QK_REDUCTIONS "false")
> set(FLASHINFER_GEN_CASUALS "false" "true")
> ```

problem solved!  thank you!

**Comment by MasterJH5574** [comment]
@sheepHavingPurpleLeaf glad that it works, thanks for confirming!
