### ISSUE TITLE
[Question] can we make --model-lib-path optional in `mlc_llm.serve.server` as it is in `mlc_llm chat`

### ISSUE THREAD

**Issue by BodhiHu** [mlc-ai/mlc-llm#1998]
Hello,

can we make `--model-lib-path` optional when running the REST API server,
as this arg is indeed optional when running cli chat:
```
# This can run succefully without --model-lib-path:
mlc_llm chat dist/gemma-2b-it-q4f16_0-MLC
```
but is required when running below RESTful server:
```
# ERROR: --model-lib-path is missing
python3 -m mlc_llm.serve.server --model ./dist/gemma-2b-it-q4f16_0-MLC
``` 

Thank you

**Comment by MasterJH5574** [comment]
Hi @BodhiHu, thanks for the question and suggestion. @Kartik14 and @shreygupta2809 are working on updating the command of launching server, which includes what you mentioned as one the the goal. This is expected to be finished in about one week.

**Comment by Kartik14** [comment]
@BodhiHu  Hi, #2014 should support this.

**Comment by BodhiHu** [comment]
Hello~ thanks a lot, I will close this :)
