### ISSUE TITLE
prepare_model_lib.py", line 39, in main     tar_list.append(valid_paths[ls0])                                 ^^^ NameError: name 'ls0' is not defined

### ISSUE THREAD

**Issue by omkar806** [mlc-ai/mlc-llm#2001]
This is inside the prepare_model_lib.py . I think in the new commit there is this error. I replaced this with valid_paths[0] but still it is saying that tvm.contrib.cc has no attribute get_global_symbol_section_map.

**Comment by MasterJH5574** [comment]
Hi @omkar806, the function `get_global_symbol_seciton_map` is introduced by https://github.com/apache/tvm/pull/16763. How did you install TVM? If you installed it from Pypi package, could you try reinstall the mlc-ai package and try again? Or if you build TVM from source, can you update TVM to the latest and check again?

To confirm, the file `tvm/contrib/cc.py` is expected to have the function `get_global_symbol_seciton_map` if your TVM is up-to-date.

**Comment by omkar806** [comment]
I installed this TVM with the python command , the mlc-ai . But this error was not there , previously like just yesterday.
Until the commit .

**Comment by omkar806** [comment]
when is this error going to be resolved ? or fixed in the next commit .

**Comment by MasterJH5574** [comment]
Oh sorry @omkar806 I didn't notice the obvious typo. It was fixed today in #2013.
