### ISSUE TITLE
I have setup a fast api code on hugging face spaces to use phi 2 as a inference endpoint . 

### ISSUE THREAD

**Issue by omkar806** [mlc-ai/mlc-llm#2009]
But I am facing issues regarding device_type on hugging face spaces , like device_type is none . 
My code : 
from fastapi import FastAPI, Depends , HTTPException , Request
from mlc_llm import ChatModule
from mlc_llm.callback import StreamToStdout
from typing import Optional
import psutil  # for monitoring system memory usage
import asyncio

# Initialize FastAPI app
app = FastAPI()

# Maximum memory usage threshold (adjust according to available memory)
MAX_MEMORY_USAGE_PERCENTAGE = 80  # e.g., 80% of available memory

# Minimum free memory threshold (adjust according to available memory)
MIN_FREE_MEMORY_PERCENTAGE = 20  # e.g., maintain at least 20% of memory free

# Available memory in GB
TOTAL_MEMORY_GB = 16
TOTAL_MEMORY_BYTES = TOTAL_MEMORY_GB * 1024 * 1024 * 1024

# Calculate the maximum memory allowed for ChatModule instances
MAX_MEMORY_ALLOWED_BYTES = TOTAL_MEMORY_BYTES * MAX_MEMORY_USAGE_PERCENTAGE / 100

# List to store loaded ChatModule instances
chat_modules = []

# Function to load ChatModule instances dynamically based on memory usage
async def load_chat_modules():
    while True:
        # Get current memory usage
        memory_usage = psutil.virtual_memory().used

        # Calculate the desired number of instances based on memory usage
        desired_instances = int(memory_usage / MAX_MEMORY_ALLOWED_BYTES)

        # Ensure minimum free memory threshold
        available_memory = TOTAL_MEMORY_BYTES - memory_usage
        if available_memory < (TOTAL_MEMORY_BYTES * MIN_FREE_MEMORY_PERCENTAGE / 100):
            desired_instances = max(desired_instances - 1, 1)  # Ensure at least one instance

        # Load or unload instances based on desired number
        current_instances = len(chat_modules)
        if current_instances < desired_instances:
            for _ in range(desired_instances - current_instances):
                chat_module = ChatModule(...)
                chat_modules.append(chat_module)
        elif current_instances > desired_instances:
            for _ in range(current_instances - desired_instances):
                chat_module = chat_modules.pop()
                del chat_module  # Explicitly delete to release memory

        # Sleep for a short interval before checking memory usage again
        await asyncio.sleep(60)  # Adjust interval as needed

# Create a singleton class for managing ChatModule instance
class ChatModuleSingleton:
    _instance = None

    def __new__(cls):
        if cls._instance is None:
            cls._instance = super().__new__(cls)
            cls._instance.cm = ChatModule(
               model="dist/phi-2-q4f16_1-MLC",
               model_lib_path="./dist/prebuilt_libs/phi-2/phi-2-q4f16_1-vulkan.so"
            )
        return cls._instance

# Start loading ChatModule instances dynamically
@app.on_event("startup")
async def startup_event():
    asyncio.ensure_future(load_chat_modules())

# Dependency to get the ChatModule instance
def get_chat_module(chat_module: ChatModuleSingleton = Depends(ChatModuleSingleton)):
    return chat_module.cm

# Define endpoint
@app.post("/generate-response")
async def generate_response(request: Request, cm: ChatModule = Depends(get_chat_module)):
    user_prompt = await request.json()
    print(user_prompt)
    print(user_prompt['prompt'])
    # Generate response for the given prompt
    if not user_prompt['prompt']:
        raise HTTPException(status_code=400, detail="Prompt not provided")
    output = cm.generate(
       prompt=user_prompt.get('prompt')
    #    progress_callback=StreamToStdout(callback_interval=2),
    )
    return {"llm_response": output}

# Run the app with uvicorn server
if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=8000)

**Comment by tqchen** [comment]
checkout https://llm.mlc.ai/docs/get_started/quick_start.html
