### ISSUE TITLE
[Question] Installation of mlc-llm prebuilt package on ubuntu22.04 failed

### ISSUE THREAD

**Issue by bocurry** [mlc-ai/mlc-llm#2016]
## ❓ General Questions

# My Question
I followed option 1 in https://llm.mlc.ai/docs/install/mlc_llm.html#install-mlc-llm-python-package to download the Prebuilt Package. But after the download was completed, I entered "python -c " import mlc_llm; print(mlc_llm)" found a conflict with numpy2.0.0:
![image](https://github.com/mlc-ai/mlc-llm/assets/12912646/814bf183-28c7-4fb3-a8f9-193e3548727f)

# My steps
1. Create an environment
conda create --name mlc-prebuilt python=3.11

2. Activate the environment
conda activate mlc-prebuilt

3. Download Prebuilt Package
python3 -m pip install --pre -U -f https://mlc.ai/wheels mlc-llm-nightly mlc-ai-nightly

4. Confirm the installation status
python -c "import mlc_llm; print(mlc_llm)"

# Other Information
Operating system:ubuntu22.04
conda version: conda 24.1.2

# My Ask
How to solve this problem?

**Comment by RaiaN** [comment]
The same problem here. Perhaps nighly builds are not tested very well?

**Comment by MasterJH5574** [comment]
Thank you folks for reporting. Possibly the nightly package installed the latest numpy (which is now 2.0). We will check that and use the NumPy of 1.*

**Comment by MasterJH5574** [comment]
I think as a quick workaround, could you manually downgrade the NumPy to 1.*? I feel that can be done by `python3 -m pip install "numpy<2.0"`.

**Comment by MasterJH5574** [comment]
We have fixed this in a latest commit. Likely you can try install the package again tmr, and it won't have this issue.

**Comment by Sing-Li** [comment]
Just a note that after replacing `numpy` another error occurred:

```
$ python3 -m pip install "numpy<2.0"
Defaulting to user installation because normal site-packages is not writeable
Collecting numpy<2.0
  Downloading numpy-1.26.4-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (61 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.0/61.0 kB 2.0 MB/s eta 0:00:00
Downloading numpy-1.26.4-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (18.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 18.2/18.2 MB 70.7 MB/s eta 0:00:00
Installing collected packages: numpy
  Attempting uninstall: numpy
    Found existing installation: numpy 2.0.0b1
    Uninstalling numpy-2.0.0b1:
      Successfully uninstalled numpy-2.0.0b1
Successfully installed numpy-1.26.4
$ python3 -m mlc_chat chat HF://mlc-ai/Llama-2-7b-chat-hf-q4f16_1-MLC
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 187, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.10/runpy.py", line 146, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/usr/lib/python3.10/runpy.py", line 110, in _get_module_details
    __import__(pkg_name)
  File "/home/autoqa/.local/lib/python3.10/site-packages/mlc_chat/__init__.py", line 5, in <module>
    from . import protocol, serve
  File "/home/autoqa/.local/lib/python3.10/site-packages/mlc_chat/protocol/__init__.py", line 2, in <module>
    from . import openai_api_protocol
  File "/home/autoqa/.local/lib/python3.10/site-packages/mlc_chat/protocol/openai_api_protocol.py", line 13, in <module>
    from mlc_chat.serve.config import ResponseFormat
  File "/home/autoqa/.local/lib/python3.10/site-packages/mlc_chat/serve/__init__.py", line 4, in <module>
    from .. import base
  File "/home/autoqa/.local/lib/python3.10/site-packages/mlc_chat/base.py", line 28, in <module>
    _LIB, _LIB_PATH = _load_mlc_llm_lib()
  File "/home/autoqa/.local/lib/python3.10/site-packages/mlc_chat/base.py", line 23, in _load_mlc_llm_lib
    return ctypes.CDLL(lib_path[0]), lib_path[0]
  File "/usr/lib/python3.10/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /home/autoqa/.local/lib/python3.10/site-packages/mlc_chat/libmlc_llm_module.so: undefined symbol: _ZN3tvm7runtime6memory7StorageC1ENS1_6BufferE
```

Thanks.

**Comment by Hzfengsy** [comment]
cc @tqchen. Would be great to check tvm compatibility with numpy 2.0

**Comment by RaiaN** [comment]
> Just a note that after replacing `numpy` another error occurred:
> 
> ```
> $ python3 -m pip install "numpy<2.0"
> Defaulting to user installation because normal site-packages is not writeable
> Collecting numpy<2.0
>   Downloading numpy-1.26.4-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (61 kB)
>      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.0/61.0 kB 2.0 MB/s eta 0:00:00
> Downloading numpy-1.26.4-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (18.2 MB)
>    ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 18.2/18.2 MB 70.7 MB/s eta 0:00:00
> Installing collected packages: numpy
>   Attempting uninstall: numpy
>     Found existing installation: numpy 2.0.0b1
>     Uninstalling numpy-2.0.0b1:
>       Successfully uninstalled numpy-2.0.0b1
> Successfully installed numpy-1.26.4
> $ python3 -m mlc_chat chat HF://mlc-ai/Llama-2-7b-chat-hf-q4f16_1-MLC
> Traceback (most recent call last):
>   File "/usr/lib/python3.10/runpy.py", line 187, in _run_module_as_main
>     mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
>   File "/usr/lib/python3.10/runpy.py", line 146, in _get_module_details
>     return _get_module_details(pkg_main_name, error)
>   File "/usr/lib/python3.10/runpy.py", line 110, in _get_module_details
>     __import__(pkg_name)
>   File "/home/autoqa/.local/lib/python3.10/site-packages/mlc_chat/__init__.py", line 5, in <module>
>     from . import protocol, serve
>   File "/home/autoqa/.local/lib/python3.10/site-packages/mlc_chat/protocol/__init__.py", line 2, in <module>
>     from . import openai_api_protocol
>   File "/home/autoqa/.local/lib/python3.10/site-packages/mlc_chat/protocol/openai_api_protocol.py", line 13, in <module>
>     from mlc_chat.serve.config import ResponseFormat
>   File "/home/autoqa/.local/lib/python3.10/site-packages/mlc_chat/serve/__init__.py", line 4, in <module>
>     from .. import base
>   File "/home/autoqa/.local/lib/python3.10/site-packages/mlc_chat/base.py", line 28, in <module>
>     _LIB, _LIB_PATH = _load_mlc_llm_lib()
>   File "/home/autoqa/.local/lib/python3.10/site-packages/mlc_chat/base.py", line 23, in _load_mlc_llm_lib
>     return ctypes.CDLL(lib_path[0]), lib_path[0]
>   File "/usr/lib/python3.10/ctypes/__init__.py", line 374, in __init__
>     self._handle = _dlopen(self._name, mode)
> OSError: /home/autoqa/.local/lib/python3.10/site-packages/mlc_chat/libmlc_llm_module.so: undefined symbol: _ZN3tvm7runtime6memory7StorageC1ENS1_6BufferE
> ```
> 
> Thanks.

I'm facing this error when compiling MLC LLM source code following official tutorial...

**Comment by RaiaN** [comment]
Is there a stable (NON-NIGHTLY) build to use?? It would be super useful for many folks out there

**Comment by bocurry** [comment]
> > Just a note that after replacing `numpy` another error occurred:
> > ```
> > $ python3 -m pip install "numpy<2.0"
> > Defaulting to user installation because normal site-packages is not writeable
> > Collecting numpy<2.0
> >   Downloading numpy-1.26.4-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (61 kB)
> >      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.0/61.0 kB 2.0 MB/s eta 0:00:00
> > Downloading numpy-1.26.4-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (18.2 MB)
> >    ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 18.2/18.2 MB 70.7 MB/s eta 0:00:00
> > Installing collected packages: numpy
> >   Attempting uninstall: numpy
> >     Found existing installation: numpy 2.0.0b1
> >     Uninstalling numpy-2.0.0b1:
> >       Successfully uninstalled numpy-2.0.0b1
> > Successfully installed numpy-1.26.4
> > $ python3 -m mlc_chat chat HF://mlc-ai/Llama-2-7b-chat-hf-q4f16_1-MLC
> > Traceback (most recent call last):
> >   File "/usr/lib/python3.10/runpy.py", line 187, in _run_module_as_main
> >     mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
> >   File "/usr/lib/python3.10/runpy.py", line 146, in _get_module_details
> >     return _get_module_details(pkg_main_name, error)
> >   File "/usr/lib/python3.10/runpy.py", line 110, in _get_module_details
> >     __import__(pkg_name)
> >   File "/home/autoqa/.local/lib/python3.10/site-packages/mlc_chat/__init__.py", line 5, in <module>
> >     from . import protocol, serve
> >   File "/home/autoqa/.local/lib/python3.10/site-packages/mlc_chat/protocol/__init__.py", line 2, in <module>
> >     from . import openai_api_protocol
> >   File "/home/autoqa/.local/lib/python3.10/site-packages/mlc_chat/protocol/openai_api_protocol.py", line 13, in <module>
> >     from mlc_chat.serve.config import ResponseFormat
> >   File "/home/autoqa/.local/lib/python3.10/site-packages/mlc_chat/serve/__init__.py", line 4, in <module>
> >     from .. import base
> >   File "/home/autoqa/.local/lib/python3.10/site-packages/mlc_chat/base.py", line 28, in <module>
> >     _LIB, _LIB_PATH = _load_mlc_llm_lib()
> >   File "/home/autoqa/.local/lib/python3.10/site-packages/mlc_chat/base.py", line 23, in _load_mlc_llm_lib
> >     return ctypes.CDLL(lib_path[0]), lib_path[0]
> >   File "/usr/lib/python3.10/ctypes/__init__.py", line 374, in __init__
> >     self._handle = _dlopen(self._name, mode)
> > OSError: /home/autoqa/.local/lib/python3.10/site-packages/mlc_chat/libmlc_llm_module.so: undefined symbol: _ZN3tvm7runtime6memory7StorageC1ENS1_6BufferE
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Thanks.
> 
> I'm facing this error when compiling MLC LLM source code following official tutorial...

Using tonight's prebuilt package, the problem has been solved.
![image](https://github.com/mlc-ai/mlc-llm/assets/12912646/12b05400-5616-4e05-8e1d-2a6ac6bb1af1)

**Comment by MasterJH5574** [comment]
> Is there a stable (NON-NIGHTLY) build to use?? It would be super useful for many folks out there

@RaiaN thanks for the suggestion! We are planning to start tagging stable releases in the recent future.
