### ISSUE TITLE
site-packages/tvm/relay/op/contrib/ethosn.py", line 20, in <module>     from distutils.version import LooseVersion ModuleNotFoundError: No module named 'distutils'

### ISSUE THREAD

**Issue by omkar806** [mlc-ai/mlc-llm#2019]
So when I install the mlc-ai package that is tvm unity compiler , I get this error and this gets resolved when I install setuptools seperately using the command , pip install setuptools.

**Comment by omkar806** [comment]
I am wondering that due to this are there any issues  for swift api like for eg : executable.cc not found when I try to run it.

**Comment by MasterJH5574** [comment]
Cross refer to https://stackoverflow.com/a/77360702, maybe you can try it out.
