### ISSUE TITLE
[Bug] can't compile to wasm, is it possible in Windows using nightly wheel?

### ISSUE THREAD

**Issue by 0xDEADFED5** [mlc-ai/mlc-llm#2020]
## To Reproduce

mlc_llm compile %dst%\mlc-chat-config.json --device vulkan --host wasm32-unknown-unknown-wasm -o %dst%/None-vulkan.wasm

soon this warning:

`WARNING auto_target.py:239: Unknown output suffix: .wasm. Assuming shared library.`

and then error:

`RuntimeError: Cannot find libraries: wasm_runtime.bc`

## Expected behavior

.wasm file output

## Environment

 - Platform (e.g. WebGPU/Vulkan/IOS/Android/CUDA): **WebGPU/Vulkan**
 - Operating system (e.g. Ubuntu/Windows/MacOS/...): **Windows 11**
 - Device (e.g. iPhone 12 Pro, PC+RTX 3090, ...): **Intel Arc A770**
 - How you installed MLC-LLM (`conda`, source): **fresh conda venv + nightly wheels**
 - How you installed TVM-Unity (`pip`, source): **pip**
 - Python version (e.g. 3.10): **3.11**
 - GPU driver version (if applicable): **latest**
 - CUDA/cuDNN version (if applicable): **n/a**
 - TVM Unity Hash Tag (`python -c "import tvm; print('\n'.join(f'{k}: {v}' for k, v in tvm.support.libinfo().items()))"`, applicable if you compile models):
 - Any other relevant information:

**Comment by Hzfengsy** [comment]
Please follow https://llm.mlc.ai/docs/deploy/javascript.html#bring-your-own-model-library, especially step 0

**Comment by 0xDEADFED5** [comment]
oops, sorry =)
