### ISSUE TITLE
InternalError: Check failed: (config_istream) is false: 

### ISSUE THREAD

**Issue by omkar806** [mlc-ai/mlc-llm#2021]
<img width="569" alt="image" src="https://github.com/mlc-ai/mlc-llm/assets/77787482/a9ca2570-ac45-47eb-8f43-340ff55c85f8">
I have added the dist folder to my IOS target itself and even the build folder.
<img width="250" alt="image" src="https://github.com/mlc-ai/mlc-llm/assets/77787482/fa2bf1e1-450e-4d59-8e29-b5f7165a2d24">
<img width="245" alt="image" src="https://github.com/mlc-ai/mlc-llm/assets/77787482/19204793-5870-46b8-a413-df1e6188b766">
But still it is showing this error .. ?

**Comment by MasterJH5574** [comment]
It's interesting to see this, as `config_stream` is a `std::ifstream` instance https://github.com/mlc-ai/mlc-llm/blob/1c975de60217c82f4dd8a3a7ac2d0c60b8e4da23/cpp/llm_chat.cc#L629-L631. 

Looks like you want to packing local weights into the app. In this case, does your `app-config.json` set the correct `model_path`? https://github.com/mlc-ai/mlc-llm/blob/1c975de60217c82f4dd8a3a7ac2d0c60b8e4da23/ios/MLCChat/app-config.json#L4

**Comment by MasterJH5574** [comment]
`config_stream` not defined means the file does not exist. Could you make sure you run the `ios/prepare_params.sh` so that gemma weights are copied to the right location, as suggested in https://llm.mlc.ai/docs/deploy/ios.html#step-3-build-auxiliary-components, and have `app-config.json` pointing to the correct `model_path`?

**Comment by loekTheDreamer** [comment]
step 3 is optional yet it has been done automatically for me:

```
{
    "device": "iphone",
    "model_list": [
        {
            "model": "HF://mlc-ai/Llama-3.2-3B-Instruct-q4f16_1-MLC",
            "model_id": "Llama-3.2-3B-Instruct-q4f16_1-MLC",
            "estimated_vram_bytes": 3000000000,
            "overrides": {
                "prefill_chunk_size": 128,
                "context_window_size": 2048
            },
            "bundle_weight": true
         }
    ]
}
```

then i run ```mlc_llm package```
and the result is dist folder containing the following:

```
dist
├── bundle                   # The directory for mlc-app-config.json (and optionally model weights)
│   │                        # that will be bundled into the iOS app.
│   ├── mlc-app-config.json  # The app config JSON file.
│   └── [optional model weights]
└── lib
   ├── libmlc_llm.a          # A lightweight interface to interact with LLM, tokenizer, and TVM Unity runtime.
   ├── libmodel_iphone.a     # The compiled model lib.
   ├── libsentencepiece.a    # SentencePiece tokenizer
   ├── libtokenizers_cpp.a   # Huggingface tokenizer.
   └── libtvm_runtime.a      # TVM Unity runtime.
   ````


<img width="744" alt="Screenshot 2024-10-23 at 14 03 34" src="https://github.com/user-attachments/assets/27d679de-bbc8-4bfc-8911-7857d08ad545">

im still facing the above issue. can anyone please assist.

**Comment by Japp-Galang** [comment]
The way I fixed this:

You need to add bundle under copy bundle resources (NOT under Copy Files)
![Image](https://github.com/user-attachments/assets/6fb88344-fd73-49d9-ba50-929ac88278e9)

You need to select Copy Items if Needed and Create folder references
![Image](https://github.com/user-attachments/assets/0eacfabf-a397-4dda-b1e3-a4d9e05560bf)
