### ISSUE TITLE
[Feature Request] shard_strategy attr for qwen1.5-14B. fully support for qwen2

### ISSUE THREAD

**Issue by na20215** [mlc-ai/mlc-llm#2023]
## 🚀 Feature

I set the sys_env_:
```
 export MLC_INTERNAL_PRESHARD_NUM=2
```
and use the command :
```
mlc_chat convert_weight ../../autodl-fs/dist/models/Qwen1.5-14B-Chat/ --quantization q4f16_1 -o ./Qwen1.5-14B-Chat-q4f16_1-MLC
```
 intending to convert a QWEN1.5-14B model into a pre-sharded model. However, it didn't actually generate a pre-sharded model. Upon investigation, it was found that the issue lies in the QWEN model not having a shard_strategy attribute defined.
```
Parameter: model.embed_tokens.weight, Shard Strategy: None
Parameter: model.layers.0.self_attn.c_attn.weight, Shard Strategy: None
Parameter: model.layers.0.self_attn.c_attn.bias, Shard Strategy: None
Parameter: model.layers.0.self_attn.o_proj.weight, Shard Strategy: None
Parameter: model.layers.0.mlp.gate_up_proj.weight, Shard Strategy: None
Parameter: model.layers.0.mlp.down_proj.weight, Shard Strategy: None
Parameter: model.layers.0.input_layernorm.weight, Shard Strategy: None
Parameter: model.layers.0.post_attention_layernorm.weight, Shard Strategy: None

Parameter: model.norm.weight, Shard Strategy: None
Parameter: lm_head.weight, Shard Strategy: None
``` 
and this is the shard_strategy of llama-7b(part):
```
Parameter: model.embed_tokens.weight, Shard Strategy: None
Parameter: model.layers.0.self_attn.qkv_proj.weight, Shard Strategy: ShardSingleDim(name='_shard_qkv', dim=0, segs=[2048, 2048, 2048])
Parameter: model.layers.0.self_attn.o_proj.weight, Shard Strategy: ShardSingleDim(name='_shard_o', dim=1, segs=None)
Parameter: model.layers.0.mlp.gate_up_proj.weight, Shard Strategy: ShardSingleDim(name='_shard_mlp_up', dim=0, segs=[5504, 5504])
Parameter: model.layers.0.mlp.down_proj.weight, Shard Strategy: ShardSingleDim(name='_shard_mlp_down', dim=1, segs=None)
Parameter: model.layers.0.input_layernorm.weight, Shard Strategy: None
Parameter: model.layers.0.post_attention_layernorm.weight, Shard Strategy: None

Parameter: model.norm.weight, Shard Strategy: None
Parameter: lm_head.weight, Shard Strategy: None
```
## Motivation

Since the QWEN model structure has been supported,It maybe would likely be beneficial to have more comprehensive support.
## Alternatives
at least, I think throw a warning or error to tell people the pre-shared model will not be generate , when the people wanna it.

**Comment by MasterJH5574** [comment]
Hi @na20215, tensor parallelism of the qwen2 model is enabled in #1985 (thanks to @tlopex!). So would you like to try again?

**Comment by na20215** [comment]
thanks that is worked

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: Ruihang Lai ***@***.***>
发送时间: Sunday, March 31, 2024 5:49:33 AM
收件人: mlc-ai/mlc-llm ***@***.***>
抄送: na20215 ***@***.***>; Mention ***@***.***>
主题: Re: [mlc-ai/mlc-llm] [Feature Request] shard_strategy attr for qwen1.5-14B. fully support for qwen2 (Issue #2023)


Hi @na20215<https://github.com/na20215>, tensor parallelism of the qwen2 model is enabled in #1985<https://github.com/mlc-ai/mlc-llm/pull/1985> (thanks to @tlopex<https://github.com/tlopex>!). So would you like to try again?

―
