### ISSUE TITLE
[Bug] The app “MLCChat” has been killed by the operating system because it is using too much memory.

### ISSUE THREAD

**Issue by trienbaoha** [mlc-ai/mlc-llm#2028]
![Screenshot 2024-03-25 at 16 25 40](https://github.com/mlc-ai/mlc-llm/assets/4353178/ab41be59-9e3a-486f-ae10-ce06f1e99a2d)

I test in Iphone 15 : Llama, Mistral

**Comment by BlindDeveloper** [comment]
For 7b models you need 8 gb ram.

**Comment by trienbaoha** [comment]
> For 7b models you need 8 gb ram.

Thanks, I try 2b models working.
