### ISSUE TITLE
Wrong answers in simple calculations

### ISSUE THREAD

**Issue by giovanith** [mlc-ai/mlc-llm#203]
Hello,

In mlc-chat-cli, Vicuna does not is able to answer simple questions like square root.  Any clue about ? Thank you guys
(Windows 10, vicuna-v1-7b-q3f16_0)

Examples....

USER: What is the square root of 36 ?
ASSISTANT: The square root of 36 is 4.

USER: what is the square root of 49 ?
ASSISTANT: The square root of 49 is 7.

USER: what is the square root of 36 ?
ASSISTANT: The square root of 36 is 7.

...

**Comment by giovanith** [comment]
Obs.: I'm a simple enthusiast of AI, perhaps a future user of such tech. I reported this observation about wrong square root here just to developers of these brilliant tools know - & perhaps adjust some bolts in this system to avoid so primary mistakes in their answers. Thanks a lot

**Comment by surya-ven** [comment]
MLC LLM didn't make the model, so this is a question for the makers of Vicuna (https://huggingface.co/lmsys/vicuna-13b-delta-v1.1). 

MLC LLM makes it easier to run these models on various types of hardware.

You might get better results by using a version of Vicuna with more parameters, but that would also require more memory.
