### ISSUE TITLE
[Bug] Run Models through MLCChat CLI Error

### ISSUE THREAD

**Issue by flores-o** [mlc-ai/mlc-llm#2035]
## 🐛 Bug

Running models through MLCChat CLI throws errormlc

```
FileNotFoundError: Cannot find the model library that corresponds to `None`.
`None` is either provided in the `chat_config` you passed in, or specified in .cache/mlc_llm/model_weights/mlc-ai/Mistral-7B-Instruct-v0.2-q4f16_1-MLC/mlc-chat-config.json.
```

## To Reproduce

Following steps in CLI [documentation](https://llm.mlc.ai/docs/deploy/cli.html)

1. `conda activate your-environment`
2. `python3 -m pip install --pre -U -f https://mlc.ai/wheels mlc-llm-nightly mlc-ai-nightly`
3.` python -m mlc_llm chat HF://mlc-ai/Mistral-7B-Instruct-v0.2-q4f16_1-MLC --overrides context_window_size=1024`

STACK TRACE

% python -m mlc_llm chat HF://mlc-ai/Mistral-7B-Instruct-v0.2-q4f16_1-MLC --overrides context_window_size=1024

...
unrecognized arguments: --allreduce_strategy=RING
Traceback (most recent call last):
  
FileNotFoundError: Cannot find the model library that corresponds to `None`.
`None` is either provided in the `chat_config` you passed in, or specified in .cache/mlc_llm/model_weights/mlc-ai/Mistral-7B-Instruct-v0.2-q4f16_1-MLC/mlc-chat-config.json.

## Expected behavior

Expected to see the llm chat interface in the cli.

## Environment

 - Platform: Metal
 - Operating system: MacOS
 - Device Macbook Pro M1
 - How you installed MLC-LLM: conda
 - How you installed TVM-Unity: pip
 - Python version (e.g. 3.10)  3.8.18:
 - GPU driver version (if applicable): -
 - CUDA/cuDNN version (if applicable): -
 - TVM Unity Hash Tag (`python -c "import tvm; print('\n'.join(f'{k}: {v}' for k, v in tvm.support.libinfo().items()))"`, applicable if you compile models):
 - Any other relevant information:

**Comment by MasterJH5574** [comment]
Hey @flores-o sorry one of my PR a few days ago broke this. I am working on a fix, which should be ready in 1-2 days. I will report back, and could you re-install the pip package then? Apologize for the inconvenience.

**Comment by flores-o** [comment]
Thanks @MasterJH5574!

Can I install a previous version of the package ( maybe [mlc_ai-0.15.1-cp38-cp38-macosx_13_0_arm64.whl](https://github.com/mlc-ai/package/releases/download/v0.9.dev0/mlc_ai-0.15.1-cp38-cp38-macosx_13_0_arm64.whl) does not contain the breaking changes? )

How should I update the command `python3 -m pip install --pre -U -f https://mlc.ai/wheels mlc-llm-nightly mlc-ai-nightly` to use a different wheel?

**Comment by MasterJH5574** [comment]
@flores-o The update should be ready I assume. You can install via `python3 -m pip install --upgrade -f https://mlc.ai/wheels mlc-llm-nightly mlc-ai-nightly`? Ideally it should install the latest builds. Let me know if it doesn't work.
