### ISSUE TITLE
[Bug] Failed to set the allowed dynamic shared memory size to 73728

### ISSUE THREAD

**Issue by Jasmine090** [mlc-ai/mlc-llm#2044]
## 🐛 Bug

When applying ChatModule ->  [Bug] Failed to set the allowed dynamic shared memory size to 73728

## To Reproduce

```
conda activate your-environment
cd mlc-llm/
mkdir -p dist/models && cd dist/models
git lfs install
git clone https://huggingface.co/togethercomputer/RedPajama-INCITE-Chat-3B-v1
cd ../..
python3 -m mlc_chat convert_weight ./dist/models/RedPajama-INCITE-Chat-3B-v1/ \
    --quantization q4f16_1 \
    -o dist/RedPajama-INCITE-Chat-3B-v1-q4f16_1-MLC
mkdir dist/libs
python3 -m mlc_chat gen_config ./dist/models/RedPajama-INCITE-Chat-3B-v1/ \
    --quantization q4f16_1 --conv-template redpajama_chat \
    -o dist/RedPajama-INCITE-Chat-3B-v1-q4f16_1-MLC/
python3 -m mlc_chat compile ./dist/RedPajama-INCITE-Chat-3B-v1-q4f16_1-MLC/mlc-chat-config.json \
    --device cuda -o dist/libs/RedPajama-INCITE-Chat-3B-v1-q4f16_1-cuda.so

python
>>> from mlc_chat import ChatModule
>>> cm = ChatModule(model="./dist/RedPajama-INCITE-Chat-3B-v1-q4f16_1-MLC", \
    model_lib_path="./dist/libs/RedPajama-INCITE-Chat-3B-v1-q4f16_1-cuda.so")
    
    cm = ChatModule(model="./dist/RedPajama-INCITE-Chat-3B-v1-q3f16_1-MLC", \
    model_lib_path="./dist/libs/RedPajama-INCITE-Chat-3B-v1-q3f16_1-cuda.so")
>>> cm.generate("hi")
```

## Expected behavior

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/’YOUR_PATH/mlc-llm-0304/python/mlc_chat/chat_module.py", line 850, in generate
    self._prefill(prompt, generation_config=generation_config)
  File "/YOUR_PATH/mlc-llm-0304/python/mlc_chat/chat_module.py", line 1072, in _prefill
    self._prefill_func(
  File "/YOUR_PATH/tvm-unity-0304/python/tvm/_ffi/_ctypes/packed_func.py", line 239, in __call__
    raise_last_ffi_error()
  File "/YOUR_PATH/tvm-unity-0304/python/tvm/_ffi/base.py", line 481, in raise_last_ffi_error
    raise py_err
tvm._ffi.base.TVMError: Traceback (most recent call last):
  1: _ZN3tvm7runtime13PackedFuncObj9ExtractorINS0_16PackedFuncSubObjIZNS0_6detail17PackFuncVoidAddr_ILi8ENS0_15CUDAWrappedFuncEEENS0_10PackedFuncET0_RKSt6vectorINS4_14ArgConvertCodeESaISA_EEEUlNS0_7TVMArgsEPNS0_11TVMRet
  0: tvm::runtime::CUDAWrappedFunc::operator()(tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*, void**) const [clone .isra.0]
  File "/YOUR_PATH/tvm-unity-0304/src/runtime/cuda/cuda_module.cc", line 182
TVMError: Failed to set the allowed dynamic shared memory size to 73728

## Environment

 - Platform : CUDA, Vulkan
 - Operating system: Ubuntu
 - Device (e.g. iPhone 12 Pro, PC+RTX 3090, ...)
 - How you installed MLC-LLM (`conda`, source):
 - How you installed TVM-Unity (`pip`, source):
 - Python version (e.g. 3.10): Python 3.12.1
 - GPU driver version (if applicable): Driver Version: 535.161.07 
 - CUDA/cuDNN version (if applicable): 12.2
 - TVM Unity Hash Tag (`python -c "import tvm; print('\n'.join(f'{k}: {v}' for k, v in tvm.support.libinfo().items()))"`, applicable if you compile models): 

## Additional context

I check memory usage by nvidia-smi: 1854MiB /  4096MiB

**Comment by shreygupta2809** [comment]
Thanks for reporting this, could you please mention which GPU you are using?

**Comment by Jasmine090** [comment]
Sorry for late reply, it's NVIDIA GeForce GTX 1650 Ti

**Comment by MasterJH5574** [comment]
Hi @Jasmine090 apologize for the late reply. MLC has changed a lot since April and just wonder if the latest pip package can work for you. I want to close this issue due to it's a bit outdated, and you are more than welcome to open new ones if this problem persists. Thanks!
