### ISSUE TITLE
[Bug] GPT2 paged kv-cache not working, gives TVMError

### ISSUE THREAD

**Issue by DeclK** [mlc-ai/mlc-llm#2047]
## To Reproduce

Just download gpt2 fron huggingface, and following the standard procedure: mlc_llm convert weights & gen config & compile.

The compiling process is pretty successful, but I CAN NOT run the chat module

```python
from mlc_llm import ChatModule

cm = ChatModule(model='dist/gpt2-MLC', device="cuda:0", model_lib_path='dist/libs/gpt2-cuda.so')
cm.generate("hi")
```
Running the script gives error 
```shell
TVMError: Check failed: (!dirty_aux_data_device_) is false: The auxiliary arrays are not synchronized to device. Please call `BeginForward` to synchronize before calling `GetQueryPositions`.
```

This seems to be the paged kv-cache is not working properly with GPT2

tvm & mlc version:

mlc-ai-nightly-cu122      0.15.dev138
mlc-llm-nightly-cu122     0.1.dev993

## Expected behavior

Output the conversation

## Environment

 - Platform (e.g. WebGPU/Vulkan/IOS/Android/CUDA): CUDA
 - Operating system (e.g. Ubuntu/Windows/MacOS/...): Ubuntu
 - Device (e.g. iPhone 12 Pro, PC+RTX 3090, ...): A10
 - How you installed MLC-LLM (`conda`, source): pip install the wheel
 - How you installed TVM-Unity (`pip`, source): pip install the wheel
 - Python version (e.g. 3.10): 3.10
 - GPU driver version (if applicable):  From NGC pytorch 23.10
 - CUDA/cuDNN version (if applicable): From NGC pytorch 23.10
 - Any other relevant information: None

**Comment by Hzfengsy** [comment]
Please try upgrading tvm and mlc. I met this issue before, and it should be fixed

**Comment by DeclK** [comment]
I use the latest mlc & tvm wheel build
mlc-ai-nightly-cu122      0.15.dev183
mlc-llm-nightly-cu122     0.1.dev1042

This would lead to another bug

**Comment by DeclK** [comment]
I see a fix in this [commit](https://github.com/mlc-ai/mlc-llm/commit/2b82091ec6dea2ec39f8d4e7de8788d44ea895ec), I believe it will be fixed in the next version of wheel

**Comment by DeclK** [comment]
Following the [commit](https://github.com/mlc-ai/mlc-llm/commit/2b82091ec6dea2ec39f8d4e7de8788d44ea895ec), I can make the compile work, but the output results are non-sense, code:
```python
from mlc_llm import ChatModule

cm = ChatModule(model='dist/gpt2-MLC', device="cuda:0", model_lib_path='dist/libs/gpt2-cuda.so')
res = cm.generate("hi")
```
result:
```txt
ce.htm.htm.htm.htm.htm.htm.htm.htm.htm.htm.htm.htm.htm.htm.htm.htm.htm.htm.htm.htm.htm.htm.htm.htm.htm.htm.htm.htm.htm.htm.htm.htm.htm.htm.htm.htm.htm.htm.htm.htm.htm.htm.htm.htm.htm.htm.htm.htm.htm.htm.htm.htm.htm.htm.htm.htm.htm...
```
I will try this again when a new release came up, see if this still happens

**Comment by MasterJH5574** [comment]
Hey @DeclK I am wondering whether you quantized the model or not? I just tried but did not reproduce the same error.
```
~/W/mlc-llm workspace *1 ?3 ❯ python
Python 3.11.5 (main, Sep 11 2023, 13:54:46) [GCC 11.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from mlc_llm import ChatModule
>>> cm = ChatModule(model="dist/gpt2", device="cuda:0", model_lib_path="dist/gpt2/lib.so")
[2024-03-29 09:48:56] INFO auto_device.py:76: Found device: cuda:0
[2024-03-29 09:48:56] INFO auto_device.py:76: Found device: cuda:1
[2024-03-29 09:48:56] INFO chat_module.py:379: Using model folder: /home/ruihang/Workspace/mlc-llm/dist/gpt2
[2024-03-29 09:48:56] INFO chat_module.py:380: Using mlc chat config: /home/ruihang/Workspace/mlc-llm/dist/gpt2/mlc-chat-config.json
[2024-03-29 09:48:56] INFO chat_module.py:529: Using library model: dist/gpt2/lib.so
[2024-03-29 09:48:57] INFO model_metadata.py:96: Total memory usage: 324.59 MB (Parameters: 310.97 MB. KVCache: 0.00 MB. Temporary buffer: 13.62 MB)
[2024-03-29 09:48:57] INFO model_metadata.py:105: To reduce memory usage, tweak `prefill_chunk_size`, `context_window_size` and `sliding_window_size`
>>> print(cm.generate("hi"))
This is where you can find out about the volunteer opportunities for a variety of reasons, including:

Becoming a volunteer for a nonprofit

Be able to show that you are willing to be a part of a project

Be able to show that you are willing to work as a consultant, consultant, or speaker

Be able to help with any project related to the volunteer

Be able to give any tips and pointers you would like to share with the community

If you would like to learn more about how to get involved with the volunteer program, contact the Volunteer Program Coordinator or the Volunteer Program Coordinator's office at:

Volunteer Program Coordinator, Volunteer Program Coordinator's Office
```

For very few times, the output is messy and looks like what you showed. Models like GPT-2 are not fine-tuned for instructions, so it is likely that the prompt "hi" is too weak. Can you also try some other prompt?

**Comment by DeclK** [comment]
Using no quantized weight, it works perfectly🤓
so it must be the problem of quantization. I think maybe the GPT2 model is not so quantize-friendly. Thanks for all the quick relpy, closing the issue

**Comment by MasterJH5574** [comment]
Thanks! Yes GPT-2 may be too small for quantization to work.
