### ISSUE TITLE
[Question]  MLC-LLM (nightly-built) cannot be used because it conflicts with the numpy.How to solve it?

### ISSUE THREAD

**Issue by bocurry** [mlc-ai/mlc-llm#2063]
### 2. There is a problem when 'convert_weight' :
![image](https://github.com/mlc-ai/mlc-llm/assets/12912646/2987bca5-2f67-49c9-98f6-a9d9a160888e)
![image](https://github.com/mlc-ai/mlc-llm/assets/12912646/882a9ad9-641b-44f7-920d-a6bcd87047a7)
![image](https://github.com/mlc-ai/mlc-llm/assets/12912646/5ebeae6b-225e-48f1-ad21-2f529637940f)
### 7. I found that the version of numpy has become 2.0.0rc1
![image](https://github.com/mlc-ai/mlc-llm/assets/12912646/b8d47eaf-3e15-4608-8e3c-345a7457a318)

# How to solve it?

**Comment by MasterJH5574** [comment]
Thank you @bocurry for reporting! We will look into it.

**Comment by 0xDEADFED5** [comment]
had same problem after i realized new nightly didn't like my existing quantized model.

`pip install numpy==1.26.4`

fixed it

**Comment by MasterJH5574** [comment]
After looking, it seems that this issue origins from the `transformers` package which is not yet compatible with NumPy 2.0. So for now an option is to downgrade manually to 1.* as @0xDEADFED5 proposed.

**Comment by bocurry** [comment]
> e origins from the `transformers` package which is not yet compatible with NumPy 2.0. So for now an option is to downgrade manually to 1.* as @0xDEADFED5 proposed.

Okay, I tried it and it works, thx!
