### ISSUE TITLE
Base$TVMError after downloading Llama-2-7b-chat-hf-q4f16_1

### ISSUE THREAD

**Issue by jo-elimu** [mlc-ai/mlc-llm#2064]
## 🐛 Bug

![](https://github.com/mlc-ai/mlc-llm/assets/1451036/d6d39ccc-2a54-4d1f-a407-646b0a598c0c)

![](https://github.com/mlc-ai/mlc-llm/assets/1451036/e3b746e0-bd11-4f37-a7b3-547b1598d65d)

@Kartik14 

## To Reproduce

1. Download and install the Android APK from https://llm.mlc.ai/docs/deploy/android.html
1. Then download the llama model from the model list
1. Press chat icon
1. Error appears

## Environment

 - Platform (e.g. WebGPU/Vulkan/IOS/Android/CUDA): Android
 - Operating system (e.g. Ubuntu/Windows/MacOS/...): Android 14
 - Device (e.g. iPhone 12 Pro, PC+RTX 3090, ...): Snapdragon 8+ Gen 1
 - How you installed MLC-LLM (`conda`, source): Downloaded Android APK from https://llm.mlc.ai/docs/deploy/android.html
 - How you installed TVM-Unity (`pip`, source):
 - Python version (e.g. 3.10):
 - GPU driver version (if applicable):
 - CUDA/cuDNN version (if applicable):
 - TVM Unity Hash Tag (`python -c "import tvm; print('\n'.join(f'{k}: {v}' for k, v in tvm.support.libinfo().items()))"`, applicable if you compile models):
 - Any other relevant information:

**Comment by Kartik14** [comment]
Seems like the weights were not download correctly, can you try deleting and redownloading?

**Comment by jo-elimu** [comment]
@Kartik14 I tried deleting and downloading a second time. Same error.

**Comment by Kartik14** [comment]
@jo-elimu Unfortunately, I am unable to reproduce this error on my end. Maybe you can try to copy the model weights manually using adb (instructions are [here](https://llm.mlc.ai/docs/deploy/android.html#incorporate-model-weights))
