### ISSUE TITLE
[Bug] iOS app errors "failed to resolve model config"

### ISSUE THREAD

**Issue by rgov** [mlc-ai/mlc-llm#2071]
## 🐛 Bug

When I launch the iOS app I get an error about "failed to resolve model config". 

The default Mistral model is there and works but it can't be deleted. 

No additional models can be downloaded. 

## To Reproduce

1. Install MLC Chat 1.2 from the App Store
1. Open it

## Environment

 - Operating system: iOS 17.4.1
 - Device: iPhone 15 Pro
 - How you installed MLC-LLM: App Store

**Comment by tqchen** [comment]
please try the latest version in sdk
