### ISSUE TITLE
[Model Request] Octopus-v2

### ISSUE THREAD

**Issue by Tao-begd** [mlc-ai/mlc-llm#2103]
## ⚙️  Request New Models

- Link to an existing implementation (e.g. Hugging Face/Github): https://huggingface.co/NexaAIDev/Octopus-v2
- Is this model architecture supported by MLC-LLM? (the list of [supported models](https://llm.mlc.ai/docs/prebuilt_models.html)) NO

## Additional context

I think this model will perform well on mobile devices, and it's worth a try

**Comment by Hzfengsy** [comment]
Octopus is based on Gemma arch, so mlc-llm should work well

**Comment by Tao-begd** [comment]
Thanks to Dr. Feng, I'll give it a try

**Comment by shubshub** [comment]
I am also interested in this

**Comment by Tao-begd** [comment]
That's okay

**Comment by Tao-begd** [comment]
That's okay
