### ISSUE TITLE
[Bug] mlc_llm command does not respect current conda environment

### ISSUE THREAD

**Issue by Sing-Li** [mlc-ai/mlc-llm#2135]
## 🐛 Bug

As per current documentation, if one uses the following syntax to invoke either `chat` or `serve`:
```
mlc_llm chat HF://mlcai/whatevermodelname-MLC
```
It will crash whenever the python installation of the  `(base)` conda environment is different from the python version  in the  currently activated environment (and if they are incompatible).

It appears that `mlc_llm` executable always use the system python's site-library regardless of the currently activated conda environment.

## To Reproduce

1.  on a clean system, install conda using base python version that is NOT COMPATIBLE with the current nightly  (3.12 is not compatible at the moment due to deprecation of `distutil`)
1.  create a new conda environment with `python=3.11.7`  , a compatible python
1.  activate the new environment
1.  install nightly
1.  run `mlc_llm chat HF://xxxxxxx-MLC`

And it will crash with `distutil` not found.   (because it is using the base environment's system python site lib path)

## Expected behavior

It should behave exactly as if I used `python3 -m mlc_llm chat HF://xxxxx-MLC` in an activated environment

## Environment

 - Platform (e.g. WebGPU/Vulkan/IOS/Android/CUDA): metal
 - Operating system (e.g. Ubuntu/Windows/MacOS/...):  MacOS
 - Device (e.g. iPhone 12 Pro, PC+RTX 3090, ...)    M1 metal
 - How you installed MLC-LLM (`conda`, source):  nightly
 - How you installed TVM-Unity (`pip`, source):
 - Python version (e.g. 3.10):
 - GPU driver version (if applicable):
 - CUDA/cuDNN version (if applicable):
 - TVM Unity Hash Tag (`python -c "import tvm; print('\n'.join(f'{k}: {v}' for k, v in tvm.support.libinfo().items()))"`, applicable if you compile models):
 - Any other relevant information:

**Comment by MasterJH5574** [comment]
Thanks @Sing-Li, this is an interesting finding! We will look into that.

**Comment by Sing-Li** [comment]
@MasterJH5574 we just found that the command also messes up the `LLVM` path for TVM under certain configs  - just fwiw   🙏

**Comment by MasterJH5574** [comment]
#2179 carries the environment along `subprocess.run`. I'm not sure if that PR can address this issue. If the error saying “`distutil` not found” happens in `subprocess.run` then it is possible that this PR can fix. Otherwise the issue might come from some other reason.

**Comment by Sing-Li** [comment]
ok.  I'll give the build a try with the problematic environment.

**Comment by Sing-Li** [comment]
@MasterJH5574    Still a problem,  with latest nightly and a Mac that has Python 3.12.1 as native:

```
$ mlc_llm chat HF://mlc-ai/Llama-3-8B-Instruct-q4f16_1-MLC                               
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/bin/mlc_llm", line 5, in <module>
    from mlc_llm.__main__ import main
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/mlc_llm/__init__.py", line 5, in <module>
    from . import protocol, serve
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/mlc_llm/serve/__init__.py", line 4, in <module>
    from .. import base
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/mlc_llm/base.py", line 6, in <module>
    import tvm
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/tvm/__init__.py", line 81, in <module>
    from . import relay
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/tvm/relay/__init__.py", line 48, in <module>
    from .op import contrib
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/tvm/relay/op/contrib/__init__.py", line 25, in <module>
    from .ethosn import *
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/tvm/relay/op/contrib/ethosn.py", line 20, in <module>
    from distutils.version import LooseVersion
ModuleNotFoundError: No module named 'distutils'
```

**Comment by tqchen** [comment]
i tried to install through miniforge and it works. @Sing-Li can you try the folows:
```
which python3
which python
which mlc_llm
cat /path/to/mlc_llm
```

**Comment by Sing-Li** [comment]
Thanks @tqchen     You're absolutly correct.  

Somehow there is a very old nightly that was installed on the  "mac's system python and sitelib" and since conda install, it is no longer accessible -- but occassionally leaked through.

I removed conda, then removed the system-installed old nightly packages, then reinstalled conda and everything is fine again.

I will close this issue now.
