### ISSUE TITLE
[Model Request] Qwen1.5-MoE-A2.7B

### ISSUE THREAD

**Issue by kenanor** [mlc-ai/mlc-llm#2138]
## ⚙️  Request New Models

- Link to an existing implementation (e.g. Hugging Face/Github): [https://huggingface.co/Qwen/Qwen1.5-MoE-A2.7B](https://huggingface.co/Qwen/Qwen1.5-MoE-A2.7B)
- Is this model architecture supported by MLC-LLM? (the list of [supported models](https://llm.mlc.ai/docs/prebuilt_models.html)) No

**Comment by MasterJH5574** [comment]
Thank you @kenanor for bring this up. We have a pending PR here https://github.com/mlc-ai/mlc-llm/pull/2089
