### ISSUE TITLE
Please support HuggingFaceH4/starchat-alpha

### ISSUE THREAD

**Issue by localagi** [mlc-ai/mlc-llm#214]
https://huggingface.co/HuggingFaceH4/starchat-alpha
fails with issue not supported, bc it's https://huggingface.co/docs/transformers/model_doc/gpt_bigcode

**Comment by localagi** [comment]
There is so many different models out there - how can i tweak the input to generate other models? Do we need any libraries to plugged in?

**Comment by CharlieRuan0130** [comment]
Hi @localagi, if the model you are interested in has architecture supported by MLC-LLM, but the model itself is not explicitly supported, you can follow the tutorial [Distribute Compiled Model](https://mlc.ai/mlc-llm/docs/compilation/distribute_compiled_models.html) to compile it yourself.

If the model's architecture is not supported by MLC-LLM yet, it is also possible to add it yourself with the guide [here](https://mlc.ai/mlc-llm/docs/tutorials/customize/define_new_models.html). Though this is much more involved.
