### ISSUE TITLE
1.0(10) works on IpadOS (iPad Air 2020) 

### ISSUE THREAD

**Issue by su77ungr** [mlc-ai/mlc-llm#215]
Just FYI: 
tested your TestFlight suite and it works just fine on my iPad Air (4. Generation) That's just 4GB RAM. 

is there a benchmark prompt or something?

![9252DFB8-6A34-4B94-84A9-CCD064367A6B](https://github.com/mlc-ai/mlc-llm/assets/69374354/d2808b73-c263-42c7-8d10-d95ae130d9a3)

**Comment by junrushao** [comment]
This is great to see! We haven't started collected RP data, but this is really awesome news!

**Comment by junrushao** [comment]
Closing as there's no further actionable issue, but benchmarking is indeed super interesting thing to do!
