### ISSUE TITLE
[Model Request] Llama 3 please!

### ISSUE THREAD

**Issue by lestan** [mlc-ai/mlc-llm#2165]
## ⚙️  Request New Models

- Link to an existing implementation (e.g. Hugging Face/Github): https://github.com/meta-llama/llama3/blob/main/MODEL_CARD.md
- Is this model architecture supported by MLC-LLM? (the list of [supported models](https://llm.mlc.ai/docs/prebuilt_models.html)) Yes

## Additional context

Llama 3 is the latest and greatest version of the Meta Llama family of models and comes in a 8B variant that should be very useful for edge deployments.

**Comment by scottorly** [comment]
https://huggingface.co/mlc-ai/Llama-3-8B-Instruct-q4f16_1-MLC

**Comment by sunzj** [comment]
> https://huggingface.co/mlc-ai/Llama-3-8B-Instruct-q4f16_1-MLC

Could share how to build library, use the same library as llama2?

**Comment by MasterJH5574** [comment]
@sunzj we have updated our GitHub repo README for some example uses. You can also check out the quick start page (https://llm.mlc.ai/docs/get_started/quick_start.html) and the introduction page (https://llm.mlc.ai/docs/get_started/introduction.html) in our documentation for the examples.

Likely you don't need to manually build the library. When you run `python -m mlc_llm chat HF://mlc-ai/Llama-3-8B-Instruct-q4f16_1-MLC` it is expected to automatically build the model library.

**Comment by 0xDEADFED5** [comment]
> > https://huggingface.co/mlc-ai/Llama-3-8B-Instruct-q4f16_1-MLC
> 
> Could share how to build library, use the same library as llama2?

there's a new conv-template named "llama-3".  do it the same way as before, but use the new conv-template.
