### ISSUE TITLE
[Doc] Instructions on how to install on Intel Arc dGPU

### ISSUE THREAD

**Issue by prakal** [mlc-ai/mlc-llm#2181]
### Suggestion
Is it currently possible to install mlc-llm on Intel Arc A770 dGPU? It worked really well as `mlc_chat_cli` but I am unable to install `mlc-llm` following instructions on https://llm.mlc.ai/docs/install/mlc_llm.html. 

I tried using the prebuilt setup with vulkan and building it from source with vulkan, but it still somehow installs nvidia CUDA packages. Has anyone else done this? Did you build it from source in conda?

**Comment by 0xDEADFED5** [comment]
i'm using it on A770 right now.  you don't need to build from source.  just "pip install --pre -U -f https://mlc.ai/wheels mlc-llm-nightly mlc-ai-nightly" from your venv of choice and use the mlc_llm commands, nothing special needed.

**Comment by qnixsynapse** [comment]
It will use Vulkan API by default, not SYCL so, no XMX support.

**Comment by prakal** [comment]
I think it was a mistake with my `$PYTHONPATH`. Can confirm that it is working as expected on my Ubuntu machine. Thanks for the responses, everyone!
