### ISSUE TITLE
[Bug] gen_config doesn't add context_window_size to model_config every time

### ISSUE THREAD

**Issue by 0xDEADFED5** [mlc-ai/mlc-llm#2182]
## 🐛 Bug

gen_config doesn't add context_window_size to model_config every time.
context_window_size key is required for LLMEngine to load.

to reproduce: gen_config with --conv-template=dolly on a Mistral 7B model, and then try to use LLMEngine() with that model

`  File "<snip>\.venv\Lib\site-packages\mlc_llm\serve\engine_base.py", line 258, in _get_model_config_limit
    compile_time_context_window_size = config["model_config"]["context_window_size"]
                                       ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'context_window_size'
`

Windows + nightly wheel.  fixed by manually adding key to mlc-chat-config.json
i know this is minor, but figured i'd share it

**Comment by MasterJH5574** [comment]
Thanks you so much for digging and reporting. We will look into and get a fix!

**Comment by tqchen** [comment]
let us build a validation function in gen_config to inspect the generated json, and check for required fields
