### ISSUE TITLE
[Doc] Add info about git and lfs to documentation 

### ISSUE THREAD

**Issue by AleksanderObuchowski** [mlc-ai/mlc-llm#2199]
### Suggestion
Add LFS as requirement to the wiki

### Bug
When trying to run the library I got the following error
```
subprocess.CalledProcessError: Command '['git', '-C', '/tmp/tmp9xqe2lg9/tmp', 'lfs', 'ls-files', '-n']' returned non-zero exit status 1.
```
Installing LFS fixed the issue
It would be good to add to the wiki that is is necessary to have LFS install to use the models on huggingface repos

**Comment by MasterJH5574** [comment]
Thank you @AleksanderObuchowski for the suggestion! We will update the documentation for that :-)

**Comment by tqchen** [comment]
added https://github.com/mlc-ai/mlc-llm/pull/2445
