### ISSUE TITLE
Does this mean I should buy a 96GB RAM Macbook?

### ISSUE THREAD

**Issue by Charuru** [mlc-ai/mlc-llm#22]
The 4090 can't run the 65B model. Can I run it on the macbook with this?

**Comment by yzh119** [comment]
Running the 65B model on macbook needs more advanced network compression techniques in addition to quantization (currently we quantize model to 3/4bits, that is not enough for running 65B or larger models), please stay tuned :)

**Comment by yzh119** [comment]
The 65B model quantized to 3bit would take around 30GB, I suppose 64GB RAM is safe to run it locally.
