### ISSUE TITLE
Phi 3 128

### ISSUE THREAD

**Issue by sebastienbo** [mlc-ai/mlc-llm#2205]
## 🚀 Feature
Introduce phi 3 mini 128k instruct

https://huggingface.co/microsoft/Phi-3-mini-128k-instruct

Mini can run on phones (there is a 4k version and 128k version)

**Comment by moondiy** [comment]
r u run phi3 ok?

**Comment by sebastienbo** [comment]
> r u run phi3 ok?

What do you mean?

**Comment by moondiy** [comment]
sorry.i want to known that are yiu run phi3 mini model on the phone?i i run it with onnxruntime genai but it's too slow

**Comment by sebastienbo** [comment]
Well I use phi2 all the time using ml. Android on my phone with Snapdragon 2nd gen and it works really good and smooth. That is why I would like to know how I can put phi 3 on mlc.

**Comment by kripper** [comment]
Have you tried following the instructions for building new models?

**Comment by indiejoseph** [comment]
Tried following the instructions, and got the error:

```
ValueError: Unknown model type: phi3. Available ones: ['llama', 'mistral', 'gemma', 'gpt2', 'mixtral', 'gpt_neox', 'gpt_bigcode', 'phi-msft', 'phi', 'qwen', 'qwen2', 'stablelm', 'baichuan', 'internlm', 'rwkv5', 'orion', 'llava', 'rwkv6', 'chatglm', 'eagle']
```

**Comment by kripper** [comment]
I would try to add the string "phi3" to the list

**Comment by indiejoseph** [comment]
@kripper thanks for your advice, the MODELS is not really just a list with a model name, it is a dict with the model name as key and the corresponding loader and implementation.

I've tried specify the `--model-type phi-msft` but without luck.

**Comment by unmotivatedgene** [comment]
Once this is figured out please update the android app apk with phi3. ❤️

**Comment by MasterJH5574** [comment]
Folks, we have supported Phi-3 mini 4k/128k and you can find the pre-converted models at https://huggingface.co/mlc-ai. Phi-3 is available in the Android app and iOS app now.

Closing this issue due to the completeness.

**Comment by sebastienbo** [comment]
I tried it, but it was impossible to ask any questions, the android app is
crashing so badly that even my whole phone became unstable and crashed.

It's totally unusable on a samsung flip 5

Has anyone else tried it?

On top of that, the phi 2 is gone, so I have nothing left now.
