### ISSUE TITLE
[Bug] Mistral-7B-Instruct-v0.2 Model is creating garbage responses to prompts

### ISSUE THREAD

**Issue by kalyan-nakka** [mlc-ai/mlc-llm#2207]
## To Reproduce

1. Download the android.tar prebuilt file for Mistral-7B-Instruct-v0.2 from https://github.com/mlc-ai/binary-mlc-llm-libs/tree/main/Mistral-7B-Instruct-v0.2
2. Build the android app for MLC Chat based on the instructions provided in https://llm.mlc.ai/docs/prebuilt_models.html#overview
3. Either run app in USB-debug mode on an Android device or build apk file and install it on an Android device.

## Expected behavior

LLM should be able to generate meaningful responses to the questions (prompts) provided.

## Environment

 - Platform (e.g. WebGPU/Vulkan/IOS/Android/CUDA):
 - Operating system (e.g. Ubuntu/Windows/MacOS/...): Android
 - Device (e.g. iPhone 12 Pro, PC+RTX 3090, ...): OnePlus 12
 - How you installed MLC-LLM (`conda`, source): pip
 - How you installed TVM-Unity (`pip`, source): 
 - Python version (e.g. 3.10): 3.10
 - GPU driver version (if applicable):
 - CUDA/cuDNN version (if applicable):
 - TVM Unity Hash Tag (`python -c "import tvm; print('\n'.join(f'{k}: {v}' for k, v in tvm.support.libinfo().items()))"`, applicable if you compile models):
 - Any other relevant information:

## Additional context

The observed behavior is that only Mistral-7B-Instruct-v0.2 is generating garbage responses as shown below,

![323762468-6b83147a-0bac-4d61-a315-04a0031c2ec4](https://github.com/mlc-ai/mlc-llm/assets/44709576/0fbd66fb-b098-44b0-b9d7-2a0fea604614)

**Comment by tqchen** [comment]
we did a major revamp to our android sdk https://llm.mlc.ai/docs/deploy/android.html which might help some of the issues
