### ISSUE TITLE
[Bug] Failed to compile because the correct code page is not set

### ISSUE THREAD

**Issue by MeroZemory** [mlc-ai/mlc-llm#2219]
## 🐛 Bug

Compilation errors occur on where the default code page is not 65001 (UTF-8) on Windows.

## To Reproduce

1. generate cmake config
```
Enter TVM_HOME in absolute path. If not specified, 3rdparty/tvm will be used by default:
Use CUDA? (y/n): y
Use CUTLASS? (y/n): y
Use CUBLAS? (y/n): y
Use ROCm? (y/n): n
Use Vulkan? (y/n): n
Use Metal (Apple M1/M2 GPU) ? (y/n): n
Use OpenCL? (y/n) n
Use FlashInfer? (need CUDA w/ compute capability 80;86;89;90) (y/n): n
```
2. Run cmake with Windows code pages. (it's the default on my system/language)

The following error occurs:
```
  (compiling source file '../cpp/conv_templates.cc')

E:\Git\mlc-llm\cpp\conv_templates.cc(649,17): error C3688: invalid literal suffix '嶺'; literal operator or literal oper
ator template 'operator ""嶺' not found [E:\Git\mlc-llm\build\mlc_llm_objs.vcxproj]
```

The actual code on the line where the error occurred is as follows:
`
  conv.roles = {"问", "答"};
`

The UTF-8 character '答', when interpreted by Windows code pages, becomes '嶺x94'.
This is the same as the character in the error message.

## Solution

Modify `gen_cmake_config.py` to add command `add_compile_options(“$<$<CXX_COMPILER_ID:MSVC>:/utf-8>”)` to `CMakeLists.txt` to use UTF-8 code pages

## Environment

 - Platform: CUDA
 - Operating system: Windows
 - How you installed MLC-LLM: `conda`
 - Python version: 3.11
 - CUDA/cuDNN version: 12.4

**Comment by tqchen** [comment]
Thanks @MeroZemory , this is something that you can manually update config.cmake after gen_cmake_config.py
