### ISSUE TITLE
[Question] Is GGUF model package format supported with quantized models?

### ISSUE THREAD

**Issue by qdrddr** [mlc-ai/mlc-llm#2227]
## ❓ General Questions

Hi, can I use existing gguf model package format of quantized models such as this one?
https://huggingface.co/MaziyarPanahi/Mixtral-8x22B-Instruct-v0.1-GGUF

If not, can I convert it to MLC?

**Comment by Hzfengsy** [comment]
GGUF is not supported with MLC-LLM. You could convert weight from the original model. See https://llm.mlc.ai/docs/compilation/convert_weights.html

**Comment by qdrddr** [comment]
Sorry for the stupid question, but aren't Hugging Face and GGUF two different formats? 
I am specifically interested in GGUF and the manual you provided for HF format. Or are both supported by the converter? @Hzfengsy

**Comment by Hzfengsy** [comment]
Yes Huggingface and GGUF are different formats. GGUF is not supported by the converter now
