### ISSUE TITLE
[Question] Can I serve multiple models with the same instance?

### ISSUE THREAD

**Issue by qdrddr** [mlc-ai/mlc-llm#2228]
## ❓ General Questions

when i do `mlc_llm serve ~/dist/folder --port 8000 ` 

Do you know if I can serve multiple models from the same folder? 

I want to run a model such as Llama-2-7b-chat-hf-q4f16_1-MLC with a second embeddings model and be able to consume it via the same IP & port address. Is that possible with MLC?

**Comment by tqchen** [comment]
For now, we support a single model  you can open up multiple ports.
