### ISSUE TITLE
[Bug] libc++abi: terminating due to uncaught exception of type tvm::runtime::InternalError: [14:02:26]

### ISSUE THREAD

**Issue by ash-rk** [mlc-ai/mlc-llm#2233]
## 🐛 Bug

libc++abi: terminating due to uncaught exception of type tvm::runtime::InternalError: [14:02:26] /Users/Ash/Documents//mlc2/mlc-llm/3rdparty/tvm/src/runtime/relax_vm/vm.cc:705: InternalError: Check failed: (func.defined()) is false: Error: Cannot find PackedFunc vm.builtin.paged_attention_kv_cache_attention_with_fused_qkv in either Relax VM kernel library, or in TVM runtime PackedFunc registry, or in global Relax functions of the VM executable
Stack trace:
  [bt] (0) 1   MLCChat                             0x0000000102c3d690 tvm::runtime::detail::LogFatal::Entry::Finalize() + 180
  [bt] (1) 2   MLCChat                             0x0000000102c3d5dc tvm::runtime::detail::LogFatal::Entry::Finalize() + 0
  [bt] (2) 3   MLCChat                             0x0000000102c3c570 __clang_call_terminate + 0
  [bt] (3) 4   MLCChat                             0x0000000102eac9a0 tvm::runtime::relax_vm::VirtualMachineImpl::InitFuncPool() + 2360
  [bt] (4) 5   MLCChat                             0x0000000102eabe28 tvm::runtime::relax_vm::VirtualMachineImpl::Init(std::__1::vector<DLDevice, std::__1::allocator<DLDevice>> const&, std::__1::vector<tvm::runtime::memory::AllocatorType, std::__1::allocator<tvm::runtime::memory::AllocatorType>> const&) + 1372
  [bt] (5) 6   MLCChat                             0x0000000102eb0ce4 tvm::runtime::relax_vm::VirtualMachineImpl::_Init(tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*) + 952
  [bt] (6) 7   MLCChat                             0x0000000102eb3cb8 tvm::runtime::PackedFuncObj::Extractor<tvm::runtime::PackedFuncSubObj<tvm::runtime::relax_vm::VirtualMachineImpl::GetFunction(tvm::runtime::String const&, tvm::runtime::ObjectPtr<tvm::runtime::Object> const&)::'lambda'(tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*)>>::Call(tvm::runtime::PackedFuncObj const*, tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*) + 52
  [bt] (7) 8   MLCChat                             0x0000000102c79e70 mlc::llm::LLMChat::Reload(tvm::runtime::TVMArgValue, tvm::runtime::String, tvm::runtime::String) + 2896
  [bt] (8) 9   MLCChat                             0x0000000102c79078 mlc::llm::LLMChatModule::GetFunction(tvm::runtime::String const&, tvm::runtime::ObjectPtr<tvm::runtime::Object> const&)::'lambda'(tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*)::operator()(tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*) const + 828

## To Reproduce

1. Install dependencies by following: https://llm.mlc.ai/docs/deploy/ios.html
2. Used Pre-built package TVM for macOS
3. Run on physical iPhone device, download model and then attempt to chat

## Expected behavior

Should be able to chat with model, but its stuck on [system] initialise... and Xcode obviously crashes

## Environment

 - Platform: IOS
 - Operating system: MacOS
 - Device: iPhone 14 Pro
 - How you installed MLC-LLM (`conda`, source): Condo & git clone
 - How you installed TVM-Unity (`pip`, source): pip
 - Python version (e.g. 3.10): 3.11.9
 - GPU driver version (if applicable): M1 Max
 - CUDA/cuDNN version (if applicable):
 - TVM Unity Hash Tag (`python -c "import tvm; print('\n'.join(f'{k}: {v}' for k, v in tvm.support.libinfo().items()))"`, applicable if you compile models):
 (myenv) Ash@Ash-MacBook-Pro ios % python -c "import tvm; print('\n'.join(f'{k}: {v}' for k, v in tvm.support.libinfo().items()))"

USE_NVTX: OFF
USE_GTEST: AUTO
SUMMARIZE: OFF
TVM_DEBUG_WITH_ABI_CHANGE: OFF
USE_IOS_RPC: OFF
USE_MSC: OFF
USE_ETHOSU: 
CUDA_VERSION: NOT-FOUND
USE_LIBBACKTRACE: AUTO
DLPACK_PATH: 3rdparty/dlpack/include
USE_TENSORRT_CODEGEN: OFF
USE_THRUST: OFF
USE_TARGET_ONNX: OFF
USE_AOT_EXECUTOR: ON
BUILD_DUMMY_LIBTVM: OFF
USE_CUDNN: OFF
USE_TENSORRT_RUNTIME: OFF
USE_ARM_COMPUTE_LIB_GRAPH_EXECUTOR: OFF
USE_CCACHE: AUTO
USE_ARM_COMPUTE_LIB: OFF
USE_CPP_RTVM: 
USE_OPENCL_GTEST: /path/to/opencl/gtest
TVM_LOG_BEFORE_THROW: OFF
USE_MKL: OFF
USE_PT_TVMDSOOP: OFF
MLIR_VERSION: NOT-FOUND
USE_CLML: OFF
USE_STACKVM_RUNTIME: OFF
USE_GRAPH_EXECUTOR_CUDA_GRAPH: OFF
ROCM_PATH: /opt/rocm
USE_DNNL: OFF
USE_MSCCL: OFF
USE_VITIS_AI: OFF
USE_MLIR: OFF
USE_RCCL: OFF
USE_LLVM: llvm-config --link-static
USE_VERILATOR: OFF
USE_TF_TVMDSOOP: OFF
USE_THREADS: ON
USE_MSVC_MT: OFF
BACKTRACE_ON_SEGFAULT: OFF
USE_GRAPH_EXECUTOR: ON
USE_NCCL: OFF
USE_ROCBLAS: OFF
GIT_COMMIT_HASH: ced07e88781c0d6416e276d9cd084bb46aaf3da5
USE_VULKAN: OFF
USE_RUST_EXT: OFF
USE_CUTLASS: OFF
USE_CPP_RPC: OFF
USE_HEXAGON: OFF
USE_CUSTOM_LOGGING: OFF
USE_UMA: OFF
USE_FALLBACK_STL_MAP: OFF
USE_SORT: ON
USE_RTTI: ON
GIT_COMMIT_TIME: 2024-04-25 21:07:15 -0400
USE_HEXAGON_SDK: /path/to/sdk
USE_BLAS: none
USE_ETHOSN: OFF
USE_LIBTORCH: OFF
USE_RANDOM: ON
USE_CUDA: OFF
USE_COREML: OFF
USE_AMX: OFF
BUILD_STATIC_RUNTIME: OFF
USE_CMSISNN: OFF
USE_KHRONOS_SPIRV: OFF
USE_CLML_GRAPH_EXECUTOR: OFF
USE_TFLITE: OFF
USE_HEXAGON_GTEST: /path/to/hexagon/gtest
PICOJSON_PATH: 3rdparty/picojson
USE_OPENCL_ENABLE_HOST_PTR: OFF
INSTALL_DEV: OFF
USE_PROFILER: ON
USE_NNPACK: OFF
LLVM_VERSION: 15.0.7
USE_MRVL: OFF
USE_OPENCL: OFF
COMPILER_RT_PATH: 3rdparty/compiler-rt
RANG_PATH: 3rdparty/rang/include
USE_SPIRV_KHR_INTEGER_DOT_PRODUCT: OFF
USE_OPENMP: OFF
USE_BNNS: OFF
USE_FLASHINFER: 
USE_CUBLAS: OFF
USE_METAL: ON
USE_MICRO_STANDALONE_RUNTIME: OFF
USE_HEXAGON_EXTERNAL_LIBS: OFF
USE_ALTERNATIVE_LINKER: AUTO
USE_BYODT_POSIT: OFF
USE_HEXAGON_RPC: OFF
USE_MICRO: OFF
DMLC_PATH: 3rdparty/dmlc-core/include
INDEX_DEFAULT_I64: ON
USE_RELAY_DEBUG: OFF
USE_RPC: ON
USE_TENSORFLOW_PATH: none
TVM_CLML_VERSION: 
USE_MIOPEN: OFF
USE_ROCM: OFF
USE_PAPI: OFF
USE_CURAND: OFF
TVM_CXX_COMPILER_PATH: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++
HIDE_PRIVATE_SYMBOLS: ON

 - Any other relevant information:

**Comment by ash-rk** [comment]
> I am also facing same issue as reported above. Note: I have re installed and upgraded tvm packages. libc++abi: terminating due to uncaught exception of type tvm::runtime::InternalError: [11:11:01] /Users/j0g0w41/Documents/mlc/mlc-llm/3rdparty/tvm/src/runtime/relax_vm/vm.cc:705: InternalError: Check failed: (func.defined()) is false: Error: Cannot find PackedFunc vm.builtin.paged_attention_kv_cache_attention_with_fused_qkv in either Relax VM kernel library, or in TVM runtime PackedFunc registry, or in global Relax functions of the VM executable

Hey, any luck fixing it?

**Comment by ash-rk** [comment]
I also attempted building the TVM from source but still received the same error

**Comment by Ninja4Panda** [comment]
Me too. Not sure where to go from here. 😢

**Comment by jeffwubj** [comment]
+1 any solution ?

**Comment by tqchen** [comment]
https://llm.mlc.ai/docs/deploy/ios.html# this should be fixed by latest ios sdk

**Comment by jalaganapathy** [comment]
My machine configuration is M1 Mac with 16GB RAM

**Comment by jalaganapathy** [comment]
Thanks @tqchen . I cloned and re built the latest iOS SDK. No crash is observed
