### ISSUE TITLE
[Bug] `mlc_llm chat` throws errors for model `mlc-ai/Qwen1.5-1.8B-Chat-q4f16_1-MLC`

### ISSUE THREAD

**Issue by BodhiHu** [mlc-ai/mlc-llm#2254]
## 🐛 Bug

Hello,

`HF://mlc-ai/Qwen1.5-1.8B-Chat-q4f16_1-MLC` seems to be incomplete:

missing `max_batch_size` in `mlc-chat-config.json`;
no tokenizers found under `Qwen1.5-1.8B-Chat-q4f16_1-MLC/`

And above two missings will cause `mlc_llm chat ...` throw errors.

## To Reproduce

1. mlc_llm chat mlc-ai/Qwen1.5-1.8B-Chat-q4f16_1-MLC

## Environment

 - Platform (e.g. WebGPU/Vulkan/IOS/Android/CUDA): Mac M1, Metal
 - Operating system (e.g. Ubuntu/Windows/MacOS/...): MacOS
 - Device (e.g. iPhone 12 Pro, PC+RTX 3090, ...)
 - How you installed MLC-LLM (`conda`, source): yes
 - How you installed TVM-Unity (`pip`, source):
 - Python version (e.g. 3.10):
 - GPU driver version (if applicable):
 - CUDA/cuDNN version (if applicable):
 - TVM Unity Hash Tag (`python -c "import tvm; print('\n'.join(f'{k}: {v}' for k, v in tvm.support.libinfo().items()))"`, applicable if you compile models):
 - Any other relevant information:

**Comment by mengshyu** [comment]
Hi @BodhiHu, I've updated the config file, can you try it again with latest mlc llm, thanks.

https://huggingface.co/mlc-ai/Qwen1.5-1.8B-Chat-q4f16_1-MLC/commit/09f17e66c5fa19bb938898e23d7997ac06371abf
