### ISSUE TITLE
[Bug] `system-lib-prefix` would be cleared if `device` is not strictly `android` while `mlc_llm compile`

### ISSUE THREAD

**Issue by BitCircuit** [mlc-ai/mlc-llm#2255]
## 🐛 Bug

Hi there, thank you so much for your great work. I am new here, sorry if this is silly. 
I have met this problem while converting a LLM for a GPU enabled Android device via Python APIs. 
While in `mlc_llm compile` stage, if I set `device` to `android:adreno` (I assume it won't invoke Adreno GPU if I simply set it to `android`, right?), it will trigger [this code](https://github.com/mlc-ai/mlc-llm/blob/ca7cdcc2652844381181ccdd3e1e8a5aca2aa0a8/python/mlc_llm/support/auto_target.py#L369) and clear the `system-lib-prefix`. 
For my own case, I would just comment them out. But in my opinion, this logic does not make sense, and that's why I am submitting this report.

**Comment by tqchen** [comment]
passing in android would be fine, and it will invoke adreno GPUs.

**Comment by tqchen** [comment]
After reading through the code, i think @BitCircuit you are right and we can safely remove this line, do you mind send a PR?
