### ISSUE TITLE
TVMError: Fail to compile metal lib:This library format is not supported on this platform (or was built with an old version of the tools)

### ISSUE THREAD

**Issue by dongqihouse** [mlc-ai/mlc-llm#226]
I followed instructions in [iOS]( https://github.com/mlc-ai/mlc-llm/blob/main/ios/README.md)

M1 Ventura 13.5

btw:
<img width="1061" alt="image" src="https://github.com/mlc-ai/mlc-llm/assets/13529784/4fab8f70-1537-4721-92cd-6787766bcb0c">

<img width="1083" alt="image" src="https://github.com/mlc-ai/mlc-llm/assets/13529784/e93e16d6-611d-4541-a369-dada7fe7bd74">
What should I do to resolve this issue?

**Comment by sunkaianna** [comment]
Build tvm from source is worked for me.

**Comment by dongqihouse** [comment]
I have attempted to compile tvm from the source code:
<img width="671" alt="image" src="https://github.com/mlc-ai/mlc-llm/assets/13529784/571fa9e9-116f-4537-9f95-a8c3db0933af">
but:
<img width="1044" alt="image" src="https://github.com/mlc-ai/mlc-llm/assets/13529784/6a8ce04b-ce08-40b3-997f-0e49f3530026">

**Comment by dongqihouse** [comment]
> Build tvm from source is worked for me.

can you tell me your llvm version info?

**Comment by rapidlugo** [comment]
Hey there folks, quick chime in that I ran into this too. After building `tvm` from source and manually `pip install`'ing `llvm`, I got it to kick over and start loading checkpoints, but it failed at :

```
Loading checkpoint shards: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [01:02<00:00, 31.37s/it]
[13:45:39] /Users/ivanlugo/localdev/llm/tvm-unity/src/runtime/metal/metal_device_api.mm:165: Intializing Metal device 0, name=Apple M1 Pro
Traceback (most recent call last):
  File "/Users/ivanlugo/localdev/llm/mlc-llm/build.py", line 389, in <module>
    main()
  File "/Users/ivanlugo/localdev/llm/mlc-llm/build.py", line 367, in main
    mod = mod_transform_before_build(mod, params, ARGS)
  File "/Users/ivanlugo/localdev/llm/mlc-llm/build.py", line 254, in mod_transform_before_build
    new_params = utils.transform_params(mod_transform, model_params)
  File "/Users/ivanlugo/localdev/llm/mlc-llm/mlc_llm/utils.py", line 156, in transform_params
    ex = relax.build(mod_transform, target=target)
  File "/Users/ivanlugo/localdev/llm/tvm-unity/python/tvm/relax/vm_build.py", line 338, in build
    return _vmlink(builder, target, tir_mod, ext_libs, params, system_lib=system_lib)
  File "/Users/ivanlugo/localdev/llm/tvm-unity/python/tvm/relax/vm_build.py", line 242, in _vmlink
    lib = tvm.build(
  File "/Users/ivanlugo/localdev/llm/tvm-unity/python/tvm/driver/build_module.py", line 281, in build
    rt_mod_host = _driver_ffi.tir_to_runtime(annotated_mods, target_host)
  File "/Users/ivanlugo/localdev/llm/tvm-unity/python/tvm/_ffi/_ctypes/packed_func.py", line 238, in __call__
    raise get_last_ffi_error()
TypeError: Traceback (most recent call last):
  File "/Users/ivanlugo/localdev/llm/tvm-unity/python/tvm/_ffi/_ctypes/packed_func.py", line 82, in cfun
    rv = local_pyfunc(*pyargs)
TypeError: parse_target.<locals>.compile_metal() takes 1 positional argument but 2 were given
```

Possible version conflict between APIs?

**Comment by tqchen** [comment]
cc @junrushao

**Comment by rapidlugo** [comment]
@junrushao Doh! Why, oh _why_ have I not baked it into my brain to just try pulling down from the branch 😅 Turns out TVM was fine, I just needed the new code; `Updating eed5a28..3f74b1c`.

Also, let me just be frank and say it's awesome you're this communicative and open with help. I personally and sincerely appreciate it, and I look forward to digging into this toolbox more!

**Comment by junrushao** [comment]
Thanks! Yeah it's always a lot of fun to talk with you guys in open-source community as an open source enthusiast! Hope it solves your issue!

**Comment by tqchen** [comment]
Thank you everyone for reporting this, and thanks @junrushao for solving

**Comment by dongqihouse** [comment]
Thanks for your responses @tqchen @junrushao @rapidlugo .
I pull down the latest source code, but still encountered this problem. 
<img width="845" alt="image" src="https://github.com/mlc-ai/mlc-llm/assets/13529784/bd80f35f-001f-4439-ac89-e6becc0bff8d">

 I also tried to compile the latest [relax](https://github.com/mlc-ai/relax/commit/d5b521a507eb9f2166f6865bc685cfaaca76f74a).
<img width="844" alt="image" src="https://github.com/mlc-ai/mlc-llm/assets/13529784/dc0d8c9d-f4b5-496d-b3d1-66f574d1b68f">

I tried as many methods as I could, but the problem remained unresolved.
🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶.

Looking forward to your reply。
