### ISSUE TITLE
[Question] Using FP8 quantization on a RedPajama-INCITE-Chat-3B-v1 model

### ISSUE THREAD

**Issue by razetime** [mlc-ai/mlc-llm#2270]
## ❓ General Questions

I am trying to use the following command to attempt to use fp8 quantization on `RedPajama-INCITE-Chat-3B-v1` (https://huggingface.co/togethercomputer/RedPajama-INCITE-7B-Chat).

```
mlc_llm convert_weight ./dist/models/RedPajama-INCITE-Chat-3B-v1/ \
    --quantization e4m3_e4m3_f16 \
    -o dist/RedPajama-INCITE-Chat-3B-v1-q4f16_1-MLC
```

However i get a key error on this command. 
```
Traceback (most recent call last):
  File "/home/raghu/miniconda3/envs/mlc-chat-venv/bin/mlc_llm", line 33, in <module>
    sys.exit(load_entry_point('mlc-llm', 'console_scripts', 'mlc_llm')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/raghu/mlc-llm/python/mlc_llm/__main__.py", line 29, in main
    cli.main(sys.argv[2:])
  File "/home/raghu/mlc-llm/python/mlc_llm/cli/convert_weight.py", line 87, in main
    convert_weight(
  File "/home/raghu/mlc-llm/python/mlc_llm/interface/convert_weight.py", line 181, in convert_weight
    _convert_args(args)
  File "/home/raghu/mlc-llm/python/mlc_llm/interface/convert_weight.py", line 68, in _convert_args
    model, quantize_map = args.model.quantize[args.quantization.kind](
                          ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'per-tensor-quant'
```

how do i fix this?

full error gist: https://gist.github.com/razetime/50b1d04a06c87b22409a98924b9f2bf7

**Comment by mengshyu** [comment]
hi @razetime fp8(e5m2, e4m3) requires per-tensor quantization support. Currently, there are two model types support it: llama and mixtral. Therefore, you may using Llama-2-7b-chat-hf for fp8 weight conversion.

**Comment by razetime** [comment]
was also considering this: https://huggingface.co/mistral-community/Mixtral-8x22B-v0.1/tree/main but i will try llama first.
