### ISSUE TITLE
Reduced and now seemingly removed support for Mali?

### ISSUE THREAD

**Issue by federicoparra** [mlc-ai/mlc-llm#2274]
## ❓ General Questions

<img width="889" alt="image" src="https://github.com/mlc-ai/mlc-llm/assets/3603101/13e17a8a-0798-4f87-b323-4cddea2747c8">

I've noticed that your documentation is not thorough with regards to the Mali GPU, and now even the blog has been removed.

This is in my opinion such a bad idea :( 

Perhaps the very best argument to move from llama.cpp to MLC was the support for this very cheap computer (the Orange Pi).

**Comment by tqchen** [comment]
We love to support mali, the new link can be found here https://blog.mlc.ai/2024/04/20/GPU-Accelerated-LLM-on-Orange-Pi

I think it was due to we updated the post for llama3 and changed a date, so the blogpost link get updated

**Comment by tqchen** [comment]
I also added a redirection so the old link also works. Thanks @federicoparra for spotting it

**Comment by federicoparra** [comment]
Could you build pip versions for Orange Pi 5?
If there you need someone to do this I could !

**Comment by federicoparra** [comment]
Also, since I got your attention :) @tqchen could answer me this https://github.com/mlc-ai/mlc-llm/issues/2244 namely is there a way with MLC compilation to run an iterative optimization for one's specific harware akin to what AutoTVM does?
Also, is there a way to use GGUF weights that have already been quantized https://github.com/mlc-ai/mlc-llm/issues/2273 with MLC ? In the case of Phi-3 something rather miracoulous happened: Microsoft themselves posted int4 quantized weights, and I tested them and it works just like the 32 bit unquantized version, I suspect this is due to quantization-aware training, something that can't be achieved with quantization after training the likes MLC does, so it would be cool to be able to use their quantized weights ?

**Comment by tqchen** [comment]
On pip packages, MLC pip packages are automated nightly via https://github.com/mlc-ai/package/, we use github actions. I think one main barrier for orange pi(ARM64 build) is to have GH action(which runs on x86) to be able to cross build for that. We do already have Mac arm64 runner. So if docker can work in that env, maybe that is another route.

I do not yet have too much experience on this, but if there are ways to do so, we would certainly be happy to provide them.
