### ISSUE TITLE
[Bug] mlc-llm not working, tvm check returns none

### ISSUE THREAD

**Issue by CallMeTkt** [mlc-ai/mlc-llm#2301]
## 🐛 Bug

![image](https://github.com/mlc-ai/mlc-llm/assets/169208347/082f249a-0832-46ce-9c49-a90fea14691a)
![image](https://github.com/mlc-ai/mlc-llm/assets/169208347/1560b8ae-c87b-4149-a2ed-0bdc995ff6c3)

## To Reproduce

1. i dont even know bro
1.
1.

## Environment

 - Platform (e.g. WebGPU/Vulkan/IOS/Android/CUDA):
 - Operating system (e.g. Ubuntu/Windows/MacOS/...):
 - Device (e.g. iPhone 12 Pro, PC+RTX 3090, ...)
 - How you installed MLC-LLM (`conda`, source):
 - How you installed TVM-Unity (`pip`, source):
 - Python version (e.g. 3.10):
 - GPU driver version (if applicable):
 - CUDA/cuDNN version (if applicable):
 - TVM Unity Hash Tag (`python -c "import tvm; print('\n'.join(f'{k}: {v}' for k, v in tvm.support.libinfo().items()))"`, applicable if you compile models):
 - Any other relevant information:

**Comment by tqchen** [comment]
make sure you installed mlc_llm. on windows we recommend running through a conda env

**Comment by CallMeTkt** [comment]
Could we potentially get on a discord call? I believe I already installed it but I'm not sure what i did wrong exactly

**Comment by CallMeTkt** [comment]
![image](https://github.com/mlc-ai/mlc-llm/assets/169208347/73d0d99f-c2b0-4f3d-9aea-75aa516ec9e3)
here is what happens when i try to install it again

**Comment by CallMeTkt** [comment]
![image](https://github.com/mlc-ai/mlc-llm/assets/169208347/f42efdc8-476e-499f-a993-79173909a151)
its here in my android project as well

**Comment by tqchen** [comment]
seems you are not installing into the conda env. try to run `which python3` to ensure the python comes from conda, make sure you installed python in conda

**Comment by CallMeTkt** [comment]
![image](https://github.com/mlc-ai/mlc-llm/assets/169208347/e27a5b85-e553-400e-a93f-e3e53c550808)
![image](https://github.com/mlc-ai/mlc-llm/assets/169208347/aeea3e72-32c3-43ab-b2e9-8117ec6a0340)
what should i do to install it to conda environment?

**Comment by tqchen** [comment]
usually conda install python would suffice, then you run `python -m pip install` instead of `python3 -m pip` which goes into your system python

**Comment by CallMeTkt** [comment]
got to the second part but got this error 
![image](https://github.com/mlc-ai/mlc-llm/assets/169208347/81bd3331-6926-4dfb-b5bb-76f8cf3d0229)

**Comment by CallMeTkt** [comment]
im still not sure how i would fix the mlc_llm install, i already have it installed but its not picking it up

**Comment by tqchen** [comment]
what i meant was run `python -m pip install --pre -U -f https://mlc.ai/wheels mlc-llm-nightly mlc-ai-nightly`

Make sure you also run `conda install python pip`

**Comment by CallMeTkt** [comment]
Alright, I'll try that when I get off school today, should be in about 8 hours. Also thanks for all the help

**Comment by CallMeTkt** [comment]
![image](https://github.com/mlc-ai/mlc-llm/assets/169208347/2d639310-97f7-42d4-b061-e9e17cc9bbf2)
![image](https://github.com/mlc-ai/mlc-llm/assets/169208347/d5126b9c-542c-4d93-a8c0-abb0a958c9ec)
did what you said, now its saying invalid config file

**Comment by CallMeTkt** [comment]
![image](https://github.com/mlc-ai/mlc-llm/assets/169208347/4146a2c5-72e4-40f5-bdfd-aa6fb6546bc8)
should i make a file and put all these in it in models?

**Comment by CallMeTkt** [comment]
![image](https://github.com/mlc-ai/mlc-llm/assets/169208347/c4f6d6f8-1e19-4926-9540-de4d99fb49e8)
ok so it ran, but now it says numpy is not available, is this a problem?

**Comment by CallMeTkt** [comment]
![image](https://github.com/mlc-ai/mlc-llm/assets/169208347/177237f0-4c6d-408b-b481-72b38aeb8fb6)
![image](https://github.com/mlc-ai/mlc-llm/assets/169208347/c22cd79d-d8f9-44f1-bc69-d9a8819d457c)
![image](https://github.com/mlc-ai/mlc-llm/assets/169208347/6eb1f071-65b5-405d-a9f6-03e12d442dbb)
whenever i run prepare model lib it just doesnt output any files in build, is there a fix?

**Comment by tqchen** [comment]
you do need to install the necessary dependencies such as numpy, usually they should come with pip install, but given it is missing, you need to manually install it

**Comment by CallMeTkt** [comment]
Would I run a command or just Google it and run a installer

**Comment by CallMeTkt** [comment]
![image](https://github.com/mlc-ai/mlc-llm/assets/169208347/72fb5d6a-0b32-440d-a153-b2fd89ddad16)
it says its already installed

**Comment by tqchen** [comment]
unfortunately seems your python did not pick it up, i dn't know why, seems to be issue with your loal env

**Comment by CallMeTkt** [comment]
is there a environment variable i should setup?

**Comment by tqchen** [comment]
I am sorry i don't really know, normally if the conda environment contains the python and you dpn't use your system python, and that python contains all necessary dependency, we should be fine

**Comment by CallMeTkt** [comment]
i managed to get it working by some downgrading of numpy, now but i cant seem to find that output after running ./prepare_libs.sh

![image](https://github.com/mlc-ai/mlc-llm/assets/169208347/13d79316-25b9-45a1-bda8-79b355427d99)
