### ISSUE TITLE
[Bug] mlc_llm package failed once, and i cant run it again

### ISSUE THREAD

**Issue by CallMeTkt** [mlc-ai/mlc-llm#2323]
## To Reproduce

1. i ran it once, it failed after a few minutes, and now i cant run the command again using a different conda environment or anything
1.
1.

## Expected behavior
it to just run again

the code to finish properly
## Environment

 - Platform (e.g. WebGPU/Vulkan/IOS/Android/CUDA):
 - Operating system (e.g. Ubuntu/Windows/MacOS/...): windows
 - Device (e.g. iPhone 12 Pro, PC+RTX 3090, ...)
 - How you installed MLC-LLM (`conda`, source): git clone https://github.com/mlc-ai/mlc-llm.git and nightly one khen mentioned 
 
 - How you installed TVM-Unity (`pip`, source): yea
 - Python version (e.g. 3.10): 3.11 i think
 - GPU driver version (if applicable):
 - CUDA/cuDNN version (if applicable):
 - TVM Unity Hash Tag (`python -c "import tvm; print('\n'.join(f'{k}: {v}' for k, v in tvm.support.libinfo().items()))"`, applicable if you compile models):
 - Any other relevant information:

## Additional context

![image](https://github.com/mlc-ai/mlc-llm/assets/169208347/5e9ca7ce-f0a0-40e3-99d9-00178337960c)

**Comment by CallMeTkt** [comment]
this is using the new page at https://llm.mlc.ai/docs/deploy/android.html#demo-app that you just added

**Comment by AkulRT** [comment]
Hey, I think I might be getting the same issue. For me, it is saying mlc_llm: command not found.

**Comment by tqchen** [comment]
If you see mlc llm command not found. Try to run python -m mlc_LLM usually it is due to multiple python in env
