### ISSUE TITLE
Could not find org.apache.tvm:tvm-android:0.1.0.

### ISSUE THREAD

**Issue by viaowp** [mlc-ai/mlc-llm#2333]
## ❓ General Questions

When executing ./gradlew assembleDebug to compile an Android APK, the following error occurred: Where can this package be found?

/mlc-llm/android$ ./gradlew assembleDebug
> Task :app:checkDebugAarMetadata FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:checkDebugAarMetadata'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not find org.apache.tvm:tvm-android:0.1.0.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/org/apache/tvm/tvm-android/0.1.0/tvm-android-0.1.0.pom
       - https://repo.maven.apache.org/maven2/org/apache/tvm/tvm-android/0.1.0/tvm-android-0.1.0.pom
       - https://maven.aliyun.com/repository/public/org/apache/tvm/tvm-android/0.1.0/tvm-android-0.1.0.pom

     Required by:
         project :app

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

BUILD FAILED in 3s
2 actionable tasks: 1 executed, 1 up-to-date

It was compiling before, but suddenly this error occurred.

**Comment by tqchen** [comment]
make sure you follow https://llm.mlc.ai/docs/deploy/android.html and run mlc_llm package first
