### ISSUE TITLE
[Bug] Can't finish the build process on windows 

### ISSUE THREAD

**Issue by jeanhubdesv** [mlc-ai/mlc-llm#2346]
## 🐛 Bug

When I try to build using `mlc_llm package` cmd on windows I am facing an error:
![image](https://github.com/mlc-ai/mlc-llm/assets/67748380/c35b694e-2f5f-42bd-95a0-ff7a20eac7e2)

## To Reproduce

Create all env variables as explained here https://llm.mlc.ai/docs/deploy/android.html
and run this `mlc_llm package` in terminal

## Environment

 - Windows 11 Pro
 - MLC-LLM cloned using git clone https://github.com/mlc-ai/mlc-llm.git
 - TVM-Unity installed using python -m pip install --pre -U -f https://mlc.ai/wheels mlc-ai-nightly
 - Python 3.11.1

**Comment by tqchen** [comment]
the error was due to lack of cmake dependency, can you install cmake via conda?

**Comment by jeanhubdesv** [comment]
It seems I have the same result. 
![image](https://github.com/mlc-ai/mlc-llm/assets/67748380/1bbb06c3-6fae-43ed-9fcd-29b39609e276)
I installed git, git lfs, cmake from anaconda, also re did all the steps and built using the cmd prompt from anaconda.

**Comment by jeanhubdesv** [comment]
Thank you for your feedback. I did that but it's failing now somewhere else.
I am going to try on a linux machine.

**Comment by AkulRT** [comment]
Facing the same issue here. 
![image](https://github.com/mlc-ai/mlc-llm/assets/170328789/4167c3cf-d3a8-483b-8d3a-323f085fba04)
I'm not sure what I'm doing any wrong, any help would be greatly appreciated.

**Comment by tqchen** [comment]
https://llm.mlc.ai/docs/deploy/android.html#additional-guides-for-windows-users
Please try the above tips

**Comment by Nikhil34712** [comment]
![5](https://github.com/mlc-ai/mlc-llm/assets/152837479/3924f2d5-5407-4069-9d65-5cab69e31e0a)

what is that file that was not found i am trying from 4 days to package the compiled model the model is being compeled but its not packaging its giving error file not found can you please share what was that file or error??

**Comment by tqchen** [comment]
in this case, seems you didn't specify TVM_NDK_CC env variable to the right compiler

**Comment by tqchen** [comment]
In this case it was looking for `llvm-ar`, please check if you have llvm-ar in that path

**Comment by Nikhil34712** [comment]
yeah llvm-ar is available in same path though its not working

**Comment by tqchen** [comment]
Thanks @Nikhil34712 , do you mind go into  file indicated, ndk.py as indicated in the error message and print out the cmd. See there is a `subprocess.Popen`, you can try to print out cmd part and see what it tries to do. Then it should give hints about why it fails

**Comment by Nikhil34712** [comment]
Hey @tqchen thanks fro replying but do mlc_llm supports MiniCPM-V when i am compiling the model or converting the weights  its showing that you have to choose only these models  i have attached the files can you please address this?? 
![Min](https://github.com/mlc-ai/mlc-llm/assets/152837479/0bef4115-1ac8-4988-98c0-c07972840d6e)
