### ISSUE TITLE
[Doc] Cant install mlc

### ISSUE THREAD

**Issue by abpani** [mlc-ai/mlc-llm#2352]
pip install --pre -U -f https://mlc.ai/wheels mlc-llm-nightly-cu122 mlc-ai-nightly-cu122
Looking in indexes: https://pypi.org/simple, https://pip.repos.neuron.amazonaws.com
Looking in links: https://mlc.ai/wheels
ERROR: Could not find a version that satisfies the requirement mlc-llm-nightly-cu122 (from versions: none)
ERROR: No matching distribution found for mlc-llm-nightly-cu122

**Comment by tqchen** [comment]
please check your environment, likely you will need a cuda env and right version of python
