### ISSUE TITLE
执行mlc_chat命令时，提示tvm模块找不到。

### ISSUE THREAD

**Issue by wangmiaojun** [mlc-ai/mlc-llm#2356]
## ❓ General Questions

1、执行了python -m pip install --pre -U -f https://mlc.ai/wheels mlc-ai-nightly-cu121安装tvm
2、执行mlc_chat convert_weight --model-type ${MODEL_TYPE} ./dist/models/${MODEL_NAME}/ --quantization $QUANTIZATION -o dist/$MODEL_NAME/时提示：
ModuleNotFoundError: No module named 'tvm'。

**Comment by tqchen** [comment]
This is likely due to the fact that you installed to a different python. Please double check if you have pip in your env
