### ISSUE TITLE
[Model Request]  Yi-1.5

### ISSUE THREAD

**Issue by 0xDEADFED5** [mlc-ai/mlc-llm#2357]
## ⚙️  Request New Models
looks quite promising!

https://huggingface.co/collections/01-ai/yi-15-2024-05-663f3ecab5f815a3eaca7ca8

prompt, etc:
https://github.com/01-ai/Yi-1.5

- Is this model architecture supported by MLC-LLM? No

**Comment by alphaarea** [comment]
Yi-1.5 architecture is `LlamaForCausalLM`

It should run directly as Llama, so it is recommended to try it with the existing version first.

**Comment by 0xDEADFED5** [comment]
you're asbsolutely right.  i just quantized and ran "01-ai/Yi-1.5-9B-Chat" and it worked just fine.  thanks for the tip.
