### ISSUE TITLE
Question : Prompt configuration

### ISSUE THREAD

**Issue by x4080** [mlc-ai/mlc-llm#238]
Hi, I have M2 pro 16gb and it run really fast using vicuna. I wondered how to customize prompt, temperature, context etc ?

Thanks

**Comment by yzh119** [comment]
To customize temperature you can modify the `mlc-chat-config.json` file in your model directory.
Currently, you need to modify the MLC-LLM source code to customize the prompt, we will make it easier after #251 this PR gets merged. Please stay tuned!

**Comment by x4080** [comment]
@yzh119 Thanks, I'll wait for it

**Comment by junrushao** [comment]
Please refer to this page for detailed documentation: https://mlc.ai/mlc-llm/docs/tutorials/runtime/mlc_chat_config.html

**Comment by x4080** [comment]
@junrushao Thanks for the documentation
