### ISSUE TITLE
No matching distribution found for mlc_ai_nightly

### ISSUE THREAD

**Issue by wanggang1987** [mlc-ai/mlc-llm#240]
Hi guys, i am  using macos and trying to compile chatglm-6b， but i meat an error the first step i begin to init env.

```
(mlc-llm-env) MacBook-Pro mlc-llm % pip install -I mlc_ai_nightly -f https://mlc.ai/wheels
``` 

 this command throws error

```Looking in links: https://mlc.ai/wheels
ERROR: Could not find a version that satisfies the requirement mlc_ai_nightly (from versions: none)
ERROR: No matching distribution found for mlc_ai_nightly
```
 
   Can you point out what can i do to fix ths issue? Thank you very much!

**Comment by yzh119** [comment]
Hi @wanggang1987 what's your Python version? The minimum Python version we support is Python 3.8.

**Comment by junrushao** [comment]
Please refer to this page for proper TVM installation: https://mlc.ai/mlc-llm/docs/install/tvm.html

**Comment by NullCodex** [comment]
I don't understand why this is closed. The instructions are from the linked website and I am running into the same issue as well running the suggested `pip install --pre --force-reinstall mlc-ai-nightly mlc-chat-nightly -f https://mlc.ai/wheels` from the linked website.

**Comment by junrushao** [comment]
@NullCodex i closed the issue because I believe the issue has been fixed, awaiting confirmation but there was no response, so I assume the issue is gone. i would expect a new github issue being raised if the issue pops up again.

given that the failure pops up, as your reported in this thread, would you mind sharing some info about your system? is it mac/win/linux, and what’s your python version?

**Comment by NullCodex** [comment]
I am running it on a macbook air m2. Here are the list of steps that I took:

1. `conda create -n mlc python=3.8`
2. `conda activate mlc`
3. `pip install --pre --force-reinstall mlc-ai-nightly mlc-chat-nightly -f https://mlc.ai/wheels`

Which will give the following error:

```
Looking in links: https://mlc.ai/wheels
ERROR: Could not find a version that satisfies the requirement mlc-ai-nightly (from versions: none)
ERROR: No matching distribution found for mlc-ai-nightly
```

**Comment by junrushao** [comment]
@NullCodex the wheel you are looking for is: `mlc_ai_nightly-0.12.dev1300-cp38-cp38-macosx_13_0_arm64.whl` in https://mlc.ai/wheels.

I am not quite sure why pip didn't find the one you are looking for. Could you check:

```
which python
which pip
python --version
pip --version
```

**Comment by NullCodex** [comment]
@junrushao 

```
which python                  
which pip
python --version
pip --version
/Users/username/miniconda3/envs/mlc/bin/python
/Users/username/miniconda3/envs/mlc/bin/pip
Python 3.8.17
pip 23.1.2 from /Users/username/miniconda3/envs/mlc/lib/python3.8/site-packages/pip (python 3.8)
```

**Comment by junrushao** [comment]
@NullCodex i have no clue unfortunately :( could you instead download this wheel and install it locally?

**Comment by NullCodex** [comment]
@junrushao i got the following:

```
pip install mlc_ai_nightly-0.12.dev1300-cp38-cp38-macosx_13_0_arm64.whl 
ERROR: mlc_ai_nightly-0.12.dev1300-cp38-cp38-macosx_13_0_arm64.whl is not a supported wheel on this platform.
```

Are m2 chips not supported?

**Comment by junrushao** [comment]
M2 is supported. Could you check your conda installation and see if its for x86 or arm? See also: https://mlc.ai/mlc-llm/docs/install/conda.html#validate-installation

**Comment by NullCodex** [comment]
@junrushao 

Input: `conda info | grep platform`

Output:
```
platform : osx-arm64

```

**Comment by junrushao** [comment]
I really have no clue what's going on on your end. I'm able to download and install on my own M2 max without any issue. @NullCodex let's try this dry run and see if it could provide anything informative:

```
pip install --dry-run --pre --force-reinstall mlc-ai-nightly mlc-chat-nightly -f https://mlc.ai/wheels
```

**Comment by NullCodex** [comment]
@junrushao unfortunately, it didn't provide any new information.

```
ERROR: Could not find a version that satisfies the requirement mlc-ai-nightly (from versions: none)
ERROR: No matching distribution found for mlc-ai-nightly
```

Can I clone the tvm repo and use the following to install instead:

```
# Create a conda environment with the dependencies specified by the yaml
conda env create --file conda/build-environment.yaml
# Activate the created environment
conda activate tvm-build

conda build --output-folder=conda/pkg  conda/recipe
# Run conda/build_cuda.sh to build with cuda enabled
conda install tvm -c ./conda/pkg
```
?

**Comment by junrushao** [comment]
@NullCodex we have a detailed set of instructions if you decide to install it from source: Could not find a version that satisfies the requirement mlc-ai-nightly (from versions: none)

**Comment by NullCodex** [comment]
@junrushao i will try it out with building from source. I am not sure what issues are preventing me from using option 1.

**Comment by NullCodex** [comment]
@junrushao are there hardware requirements for the Mac?

I am following the steps to building from source but I keep failing because I am running out of application memory. I am running it on a m2 macbook air with 16g of ram and 512 SSD. I even tried to keep only the terminal open during the process but I am unable to complete.

**Comment by junrushao** [comment]
@NullCodex There is effectively no hardware requirement to build libtvm at all given it’s simply running make/clang stuff. Which command are you running that eats so much memory?

**Comment by NullCodex** [comment]
@junrushao it's only one command to to build TVM which from the linked website is `cmake .. && cmake --build . --parallel $(nproc)` this command after 2 hours will cause my laptop to be out of application memory.

**Comment by junrushao** [comment]
@NullCodex it took 5min to compile on my M2...Not sure what's going on

**Comment by NullCodex** [comment]
@junrushao am i missing anything else?

```
# clone from GitHub
git clone --recursive git@github.com:mlc-ai/relax.git tvm-unity && cd tvm-unity
# create the build directory
rm -rf build && mkdir build && cd build
# specify build requirements in `config.cmake`
cp ../cmake/config.cmake .

# controls default compilation flags
echo "set(CMAKE_BUILD_TYPE RelWithDebInfo)" >> config.cmake
# LLVM is a must dependency
echo "set(USE_LLVM \"llvm-config --ignore-libllvm --link-static\")" >> config.cmake
echo "set(HIDE_PRIVATE_SYMBOLS ON)" >> config.cmake
# GPU SDKs, turn on if needed
echo "set(USE_CUDA   OFF)" >> config.cmake
echo "set(USE_METAL  OFF)" >> config.cmake
echo "set(USE_VULKAN OFF)" >> config.cmake
echo "set(USE_OpenCL OFF)" >> config.cmake

cmake .. && cmake --build . --parallel $(nproc)
```

should i have `USE_METAL` on? I don't think i am missing anything else here. The conda environment was created using the build yml file from the repo

**Comment by junrushao** [comment]
I didn’t see anything missing from your script. You may set USE_METAL to ON, but it shouldn’t have any impact on compilation time at all. I tested out on my M2 again and it does only take 5min to compile…

How about this: can you change “ cmake --build . --parallel $(nproc)” to “make -j8”?

**Comment by junrushao** [comment]
BTW, what's your output of:

```
python -c "import platform; print(platform.platform())"
```

**Comment by NullCodex** [comment]
@junrushao is the makefile at the root directory instead of the build directory? I only see a makefile at the root directory of tvm-unity

**Comment by junrushao** [comment]
@NullCodex should be the one inside `build/`. you will need to do `cd build/` before running make

**Comment by junrushao** [comment]
@NullCodex there should be at least some cmake generated files under `build/` right? they should be generated by those commands:

```
# create the build directory
rm -rf build && mkdir build && cd build
# specify build requirements in `config.cmake`
cp ../cmake/config.cmake .

# controls default compilation flags
echo "set(CMAKE_BUILD_TYPE RelWithDebInfo)" >> config.cmake
# LLVM is a must dependency
echo "set(USE_LLVM \"llvm-config --ignore-libllvm --link-static\")" >> config.cmake
echo "set(HIDE_PRIVATE_SYMBOLS ON)" >> config.cmake
# GPU SDKs, turn on if needed
echo "set(USE_CUDA   OFF)" >> config.cmake
echo "set(USE_METAL  OFF)" >> config.cmake
echo "set(USE_VULKAN OFF)" >> config.cmake
echo "set(USE_OpenCL OFF)" >> config.cmake
```

**Comment by NullCodex** [comment]
@junrushao there's only the `config.cmake` which gives me no makefile found when running `make -j8`

**Comment by arif599** [comment]
Hey @junrushao, I was running into this same issue and I followed the steps in the comments and I do see libtvm.dylib in my build folder.

However, when I run `python -m mlc_chat.rest --help` I get ModuleNotFoundError. Is there something else I need to do to get mlc_chat?

Thanks in advance.

**Comment by Solaxun** [comment]
Same issue on M1 Pro. Will attempt installing the wheel directly, although the versions have changed so I can't be 100% sure I'll pick the correct ones.

**Comment by Solaxun** [comment]
For anybody running into this ... make sure your OS is updated to the latest version.  I was many versions behind and after upgrading, the pip install worked.

**Comment by BodhiHu** [comment]
Same issue here, fixed after upgrading to latest macos(Ventura) :D
