### ISSUE TITLE
README blog & documentation links broken

### ISSUE THREAD

**Issue by melgu** [mlc-ai/mlc-llm#243]
The link to the documentation at the top of the README (`https://mlc.ai/mlc-llm/docs/`) results in a 404 page.

The link to the blog (`https://mlc.ai/blog/blog/2023/05/01/bringing-accelerated-llm-to-consumer-hardware`) results in an infinite redirect loop.

**Comment by tqchen** [comment]
Thanks for reporting, the blog link have been fixed, the documentation is still WIP and we are working to set it up
