### ISSUE TITLE
'ChatGLMTokenizer' object has no attribute 'backend_tokenizer'

### ISSUE THREAD

**Issue by lihaofd** [mlc-ai/mlc-llm#2460]
I can run mlc_llm convert_weight ./dist/models/chatglm3-6b/ --quantization q4f16_1 -o dist/chatglm3-6b-MLC
but when 
running 
mlc_llm gen_config ./dist/models/chatglm3-6b/ --quantization q4f16_1 --conv-template glm  -o dist/chatglm3-6b-MLC/

it shows ValueError: Loading dist/models/chatglm3-6b requires you to execute the configuration file in that repo on your local machine. Make sure you have read the code there to avoid malicious use, then set the option `trust_remote_code=True` to remove this error.

after setting trust_remote_code=True
It shows 'ChatGLMTokenizer' object has no attribute 'backend_tokenizer', any way to fix it?

File ".../lib/python3.11/site-packages/mlc_llm/interface/gen_config.py", line 185, in gen_config
    fast_tokenizer.backend_tokenizer.save(str(tokenizer_json_save_dest))

mlc-ai-nightly-cu122          0.15.dev380
mlc-llm-nightly-cu122         0.1.dev1313

Thank you very much for your help!

**Comment by lihaofd** [comment]
same to chatglm2-6b

**Comment by Ubospica** [comment]
That is related to a recent change in tokenizer in https://github.com/mlc-ai/mlc-llm/pull/2416. We will fix that soon
