### ISSUE TITLE
[Question] Does OpenCL on Adreno GPU support OpenCL ML SDK

### ISSUE THREAD

**Issue by xiaoxiaoyuwen** [mlc-ai/mlc-llm#2461]
## ❓ General Questions

My devices is Qualcomm chip , Android System

my compile command like this

```
mlc_llm compile path/to/mlc_model  \
     --device android:adreno-so \
     -o path/to/output library
```
I want to know does the output library optimized by OpenCL ML and how can I confirm it ?

**Comment by Hzfengsy** [comment]
We do not use OpenCL ML SDK for now.
