### ISSUE TITLE
[Bug] Bug Missing mlc_llm.dll file when setting up MLC LLM for Android development on Windows

### ISSUE THREAD

**Issue by AbhayGopal** [mlc-ai/mlc-llm#2494]
## To Reproduce

Followed the installation instructions for MLC LLM on Windows for [Android development](https://llm.mlc.ai/docs/deploy/android.html).
Installed the required dependencies, including Android Studio, Android SDK, NDK, Rust, Git, and Git LFS.
Cloned the MLC LLM repository and navigated to the python directory.
Ran python setup.py install to install the package.
The setup.py script fails with the following error:
`RuntimeError: Cannot find libraries: mlc_llm.dll`

this is the full error shown
`Traceback (most recent call last):
  File "C:\Users\rando\Documents\mlc-llm\python\setup.py", line 49, in <module>
    LIB_LIST, __version__ = get_lib_path()
                            ^^^^^^^^^^^^^^
  File "C:\Users\rando\Documents\mlc-llm\python\setup.py", line 25, in get_lib_path
    libinfo["find_lib_path"]("mlc_llm")[0],
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rando\Documents\mlc-llm\python\./mlc_llm/libinfo.py", line 70, in find_lib_path
    raise RuntimeError(message)
RuntimeError: Cannot find libraries: mlc_llm.dll
List of candidates:
C:\Users\rando\Documents\mlc-llm\python\mlc_llm\mlc_llm.dll
C:\Users\rando\anaconda3\envs\mlc_llm\lib\mlc_llm.dll
C:\Users\rando\anaconda3\envs\mlc_llm\mlc_llm.dll
C:\Users\rando\anaconda3\envs\mlc_llm\Library\usr\bin\mlc_llm.dll
C:\Users\rando\anaconda3\envs\mlc_llm\Library\bin\mlc_llm.dll
C:\Users\rando\anaconda3\envs\mlc_llm\Scripts\mlc_llm.dll
C:\Users\rando\anaconda3\condabin\mlc_llm.dll
C:\Program Files\Common Files\Oracle\Java\javapath\mlc_llm.dll
C:\Program Files (x86)\VMware\VMware Player\bin\mlc_llm.dll
C:\Windows\system32\mlc_llm.dll
C:\Windows\mlc_llm.dll
C:\Windows\System32\Wbem\mlc_llm.dll
C:\Windows\System32\WindowsPowerShell\v1.0\mlc_llm.dll
C:\Windows\System32\OpenSSH\mlc_llm.dll
C:\Program Files\Git\cmd\mlc_llm.dll
C:\Program Files\Git LFS\mlc_llm.dll
C:\Program Files\Java\jdk-22\bin\mlc_llm.dll
C:\Users\rando\anaconda3\mlc_llm.dll
C:\Users\rando\anaconda3\Library\mingw-w64\bin\mlc_llm.dll
C:\Users\rando\anaconda3\Library\usr\bin\mlc_llm.dll
C:\Users\rando\anaconda3\Library\bin\mlc_llm.dll
C:\Users\rando\anaconda3\Scripts\mlc_llm.dll
C:\Users\rando\.cargo\bin\mlc_llm.dll
C:\Users\rando\AppData\Local\Microsoft\WindowsApps\mlc_llm.dll
C:\Users\rando\AppData\Local\Programs\Microsoft VS Code\bin\mlc_llm.dll
C:\Users\rando\AppData\Local\GitHubDesktop\bin\mlc_llm.dll
C:\ghcup\bin\mlc_llm.dll`

## Expected behavior

I expected the mlc_llm.dll file to be present in the package or generated during the installation process, allowing the setup.py script to complete successfully.

## Environment

 - Platform : Vulkan
 - Operating system : Windows
 - Device  : PC+ amd gpu and cpu
 - How you installed MLC-LLM : conda
 - How you installed TVM-Unity : source
 - Python version : Python 3.11.9

## Additional context

I have followed the installation instructions provided in the MLC LLM documentation for Android development on Windows. I have installed all the required dependencies and set up the necessary environment variables. However, I am stuck at the step where I need to run python setup.py install due to the missing mlc_llm.dll file.
I have searched for the file on my entire PC but couldn't find it. The closest match was mlc_llm.rst in the docs\install directory of the cloned repository.
Any guidance on how to resolve this issue and proceed with the installation would be greatly appreciated.

**Comment by tqchen** [comment]
you don't need to build from source and run setup.py, instead follow prebuilt option here to obtain a copy https://llm.mlc.ai/docs/install/mlc_llm.html#install-mlc-packages

**Comment by AbhayGopal** [comment]
> you don't need to build from source and run setup.py, instead follow prebuilt option here to obtain a copy https://llm.mlc.ai/docs/install/mlc_llm.html#install-mlc-packages

Thank you for your replay 
Can please clarify on this 
![image](https://github.com/mlc-ai/mlc-llm/assets/122857188/1a7b0606-e038-463f-8114-e2a2a4a4dffb)
are you telling me that I only have to follow what it is written here and no need to worry about setup.py?

**Comment by tqchen** [comment]
>are you telling me that I only have to follow what is written here and no need to worry about setup.py? 
that is correct

**Comment by AbhayGopal** [comment]
issue resolved
