### ISSUE TITLE
[Question] Error when running debug_chat.py

### ISSUE THREAD

**Issue by ponytaill** [mlc-ai/mlc-llm#2513]
## ❓ General Questions

Hi, I run testing/debug_chat.py, and get this output:
======================= Starts Tokenization & Embedding =======================
Parsed prompt using conversation template phi-2: ['Instruct: hello\nOutput:']
Input tokens: [43993    25 23748   198 26410    25]
======================= Starts Prefill =======================
Debug instrument output dumped to dist/prefill
======================= Starts Decode =======================
Debug instrument output dumped to dist/decode_0
Debug instrument output dumped to dist/decode_1
Generated output tokens: [ 220  198 5500]
Traceback (most recent call last):
  File "/home/shi/smq/mlc-llm/python/mlc_llm/testing/debug_chat.py", line 454, in <module>
    main()
  File "/home/shi/smq/mlc-llm/python/mlc_llm/testing/debug_chat.py", line 450, in main
    dc.generate("hello", 3)
  File "/home/shi/smq/mlc-llm/python/mlc_llm/testing/debug_chat.py", line 403, in generate
    out_text = self.tokenizer.decode(out_tokens)
  File "/home/shi/anaconda3/envs/newmlc/lib/python3.10/site-packages/mlc_llm/tokenizers/tokenizers.py", line 111, in decode
    return _ffi_api.TokenizerDecode(  # type: ignore  # pylint: disable=no-member
AttributeError: module 'mlc_llm.tokenizers._ffi_api' has no attribute 'TokenizerDecode'. Did you mean: 'TokenizerEncode'?

Weird. It seems like a simple problem, but I really don't know how to solve it.

**Comment by MasterJH5574** [comment]
It's a bug by mistake I believe. Fixed in #2514.

**Comment by ponytaill** [comment]
> It's a bug by mistake I believe. Fixed in #2514.

Thanks! By the way, how can I upgrade my mlc-llm to apply it?

**Comment by MasterJH5574** [comment]
From the stack trace you share, looks like you are using the pip package right? The nightly wheel build happens daily so in this case, could you try to upgrade the pip package tomorrow?

**Comment by ponytaill** [comment]
> From the stack trace you share, looks like you are using the pip package right? The nightly wheel build happens daily so in this case, could you try to upgrade the pip package tomorrow?

OK. I'll try again tomorrow.
