### ISSUE TITLE
[Question] Unable to download and compile custom model from Hugging Face using `mlc_llm package` command

### ISSUE THREAD

**Issue by AbhayGopal** [mlc-ai/mlc-llm#2525]
## ❓ General Questions

I am trying to use my own custom model from Hugging Face (https://huggingface.co/Abnmd/Llama_7b-mental_test2.0) with MLC LLM, but I am encountering an error when running the `mlc_llm package` command.

I am using windows with amd cpu and gpu and followed the documentation for [Android SDK](https://llm.mlc.ai/docs/deploy/android.html). One doubt i have is should I follow [MLC LLM Python Package](https://llm.mlc.ai/docs/install/mlc_llm.html#install-mlc-llm-python-package) also? ([it was giving me error](https://github.com/mlc-ai/mlc-llm/issues/2494))

I have followed the steps to set up the environment and install the necessary dependencies, including :
- Installing Android Studio with NDK and CMake
- Setting up the required environment variables (ANDROID_NDK, TVM_NDK_CC, JAVA_HOME)
- Installing Rust, Git, and Git LFS
- Cloning the MLC LLM repository
- Installing Conda and creating a new environment
- Installing the Python dependencies using pip

However, when I run the `mlc_llm package` command, I get the following error:

`ValueError: Git clone failed with return code 128: None. The command was: ['git', 'clone', 'https://huggingface.co/Abnmd/Llama_7b-mental_test2.0.git', '.tmp']`

I have tried setting the Hugging Face token as an environment variable and logging in using the Hugging Face CLI, but the error persists.

I would appreciate any guidance on how to resolve this issue and successfully download and compile my custom model from Hugging Face using MLC LLM. Please let me know if you need any additional information or if there are any specific steps I should take to troubleshoot the problem.

**Comment by tqchen** [comment]
one way you can try is to pass a local path, instead of the HF path, since the particular repo was not publically visible

**Comment by AbhayGopal** [comment]
Okay, but
1. The repository I mentioned is mine and it is not private also I tried to run it with MLC LLM's own LLMs which were in `mlc-package-config.json` which gave same error
`ValueError: Git clone failed with return code 128: None. The command was: ['git', 'clone', 'https://huggingface.co/mlc-ai/gemma-2b-it-q4f16_1-MLC.git', '.tmp']`
2. Can you help or suggest me how to pass a local path

**Comment by tqchen** [comment]
interesting, can you make sure you have git lfs and git installed, it works on my env

**Comment by AbhayGopal** [comment]
Yes, I have double checked and I have installed both.
One doubt I have is that is it fine if i only follow this documentation [Android SDK](https://llm.mlc.ai/docs/deploy/android.html) or do I need to do anything more

**Comment by tqchen** [comment]
you can try git clone command manually and see if that works,
