### ISSUE TITLE
[Question] Android demo app change model

### ISSUE THREAD

**Issue by panghongtao** [mlc-ai/mlc-llm#2542]
## ❓ General Questions

Android demo app
https://github.com/mlc-ai/binary-mlc-llm-libs/releases/download/Android-06062024/mlc-chat.apk

Can i change this demo download the model? I would like to try using other models to execute the scheme on the phone. If you only modify the configuration file, you can use this APP. Which files should I change?

**Comment by tqchen** [comment]
https://llm.mlc.ai/docs/deploy/android.html#customize-the-app

**Comment by panghongtao** [comment]
OK Thank you very much. I will try to change
