### ISSUE TITLE
Fail to compile CLI

### ISSUE THREAD

**Issue by sunyuhan19981208** [mlc-ai/mlc-llm#255]
I can successfully compile the model but fail to compile cli:
```c++
-- The C compiler identification is GNU 8.4.0
-- The CXX compiler identification is GNU 8.4.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Performing Test SUPPORT_CXX17
-- Performing Test SUPPORT_CXX17 - Success
-- Setting default build type to RelWithDebInfo
CMake Error at CMakeLists.txt:47 (add_subdirectory):
  add_subdirectory given source "tvm" which is not an existing directory.


-- system-nameLinux
-- VERSION: 0.2.00
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
CMake Error at CMakeLists.txt:54 (tvm_file_glob):
  Unknown CMake command "tvm_file_glob".
```

**Comment by rejoicesyc** [comment]
I met the same problem while using mlc_ai_nightly wheel, but I successfully compiled mlc_chat_cli by building tvm-unity from the source(https://github.com/mlc-ai/relax)

**Comment by sunyuhan19981208** [comment]
> I met the same problem while using mlc_ai_nightly wheel, but I successfully compiled mlc_chat_cli by building tvm-unity from the source(https://github.com/mlc-ai/relax) and setting $TVM_HOME

thank you, i'll try this

**Comment by llucid-97** [comment]
> I met the same problem while using mlc_ai_nightly wheel, but I successfully compiled mlc_chat_cli by building tvm-unity from the source(https://github.com/mlc-ai/relax) and setting $TVM_HOME

I had same issue. This fixed it for me

**Comment by yzh119** [comment]
Please check our documentation on CLI compilation: https://mlc.ai/mlc-llm/docs/tutorials/deploy-models.html#option-2-build-from-source

**Comment by sunyuhan19981208** [comment]
> Please check our documentation on CLI compilation: https://mlc.ai/mlc-llm/docs/tutorials/deploy-models.html#option-2-build-from-source

thank you very much! I will try that!

**Comment by Atlantis12000** [comment]
see code in scripts/prep_deps.sh, just git clone https://github.com/apache/tvm 3rdparty/tvm --branch unity --recursive and export TVM_HOME="${TVM_HOME:-3rdparty/tvm}"

**Comment by YouCii** [comment]
> Please check our documentation on CLI compilation: https://mlc.ai/mlc-llm/docs/tutorials/deploy-models.html#option-2-build-from-source

load error?
<img width="649" alt="image" src="https://github.com/mlc-ai/mlc-llm/assets/17899073/b7080279-dc28-42e3-9c63-7bb5ad086c22">

**Comment by MasterJH5574** [comment]
Hi @YouCii, we restructured the documentation and that link is outdated. Now the CLI compilation instructions is here https://mlc.ai/mlc-llm/docs/deploy/cli.html#option-2-build-mlc-runtime-from-source
