### ISSUE TITLE
[Question] Is mlc chat deprecated?

### ISSUE THREAD

**Issue by manu-web** [mlc-ai/mlc-llm#2567]

**Comment by tqchen** [comment]
checkout https://github.com/mlc-ai/mlc-llm/issues/2217, i guess you meant ChatModule

**Comment by manu-web** [comment]
Does MLCEngine also support something like mlc_chat.cli.benchmark?

**Comment by tqchen** [comment]
We are in the process of revamping the benchmarking part, in the mean time you can try to get some of the metrics via mlc_llm chat and `/metrics`
