### ISSUE TITLE
[Question] where to find the JAR file or dependency for TVM 

### ISSUE THREAD

**Issue by surya071** [mlc-ai/mlc-llm#2569]
## ❓ General Questions

When running the project(Android) as suggested in the documentation, I get the error:

package org.apache.tvm does not exist
import org.apache.tvm.Device;

Could someone guide me on where to find the JAR file or dependency for TVM ?

**Comment by panghongtao** [comment]
are you set TVM_SOURCE_DIR and TVM_NDK_CC?   look your ..\mlc-llm\3rdparty folder。if this folder no have file. 
you run 
cd mlc-llm
git submodule update --init --recursive

**Comment by MasterJH5574** [comment]
Thanks @panghongtao for suggesting 🙏 @surya071 please check your if you recursively cloned mlc-llm and have `path/to/mlc-llm/3rdparty/tvm` non-empty.

Gonna close this issue due to inactivity. You are more than welcome to open new issues if the problem persists or for any new problems :-)
