### ISSUE TITLE
[Question] How to run MLC-LLM as a local chat server on Android

### ISSUE THREAD

**Issue by riteme** [mlc-ai/mlc-llm#2577]
## ❓ General Questions

Hello, I want to run MLC-LLM on Android devices as a local chat server. I see there's an Android App for MLC-LLM with a nice UI. But I want to run MLC-LLM much like a system service. Is there a simple way to achieve this?
Thank you.

**Comment by tqchen** [comment]
Can you elaborate a bit more about your usecase. 

As of now android only runs apk. We can bundle mlc into any other app via the android sdk, if you are looking into developing your app.

**Comment by tqchen** [comment]
The android sdk contains the api examples to do so

**Comment by riteme** [comment]
@tqchen Thanks for replying. I have read the source code of the MLCChat app and learned how to use the MLC core in Android  apps. I'll try to develop a app to run as a chat server.
