### ISSUE TITLE
[Question]  MLCEngine instance must be a singleton?

### ISSUE THREAD

**Issue by wqwz111** [mlc-ai/mlc-llm#2581]
## ❓ General Questions
When I create two instance of MLCEngine, each of them always generate: Role "user" is not supported.

**Comment by tqchen** [comment]
@wqwz111 would be great if you can send in a python snippet that reproduces the error, we would be happy to look into it. Although in general we recommend running a single MLCEngine, if there is a need to support multiple models, likely extending the engine to do so would be more efficient

**Comment by wqwz111** [comment]
Thanks! I will try extending the engine to solve my problem.
