### ISSUE TITLE
[Question] Can you programmatically clear the kv cache?

### ISSUE THREAD

**Issue by 0xLienid** [mlc-ai/mlc-llm#2593]
## ❓ General Questions

The kv cache should end up consuming more memory over time, can you programmatically purge it?

**Comment by 0xLienid** [comment]
bump?

**Comment by MasterJH5574** [comment]
Hi @0xLienid, we allocate the KV cache with a fixed size during initialization and do not allocate extra memory for the KV cache as time goes. Could you elaborate a bit more on what you want to do?
