### ISSUE TITLE
[Question] The Android SDK is too large

### ISSUE THREAD

**Issue by canluhuang** [mlc-ai/mlc-llm#2596]
We are planning to integrate mlc sdk in our android app, but now there is a limitation that the size is too large, the increment is nearly 120MB. But for the same model, the increment on iOS is only 20M. What is the reason for such a big difference in the increment between the two platforms? Is there any way to optimize Android size?

![image](https://github.com/mlc-ai/mlc-llm/assets/7105187/8749a907-7d77-4bbf-8e49-b13ee25f97b5)
As shown in the figure above, the largest increment is tvm4j_runtime_packed.so. Is this because of  conatins tvm runtime?

**Comment by tqchen** [comment]
Might be worthwhile reducing the number of models in the mlc-package-config.json list. If you have a list in mind that reproduces the binary size, feel free to share as well

**Comment by canluhuang** [comment]
> One quick way that can help is to reduce the number of models in the mlc-package-config.json list. If you have a list in mind that reproduces the binary size, feel free to share as well

This is the size after it has been reduced to just a 0.5b model. It seems that the main size is in the tvm runtime, but why does the iOS platform look much smaller?

**Comment by MasterJH5574** [comment]
Hi @canluhuang, we tried a bit to reduce the binary size in https://github.com/mlc-ai/mlc-llm/pull/2606. You can try a bit, but it is possible that after reduction it's still higher than the limit (not sure).

Would appreciate it if you can share any further updates on how it goes. Thanks!!

**Comment by MasterJH5574** [comment]
Gonna close this issue due to inactivity. You are more than welcome to open new issues for further problems, thanks!
