### ISSUE TITLE
  Check failed: (__e == VK_SUCCESS) is false: Vulkan Error, code=-2: VK_ERROR_OUT_OF_DEVICE_MEMORY Stack trace not available when DMLC_LOG_STACK_TRACE is disabled at compile time.

### ISSUE THREAD

**Issue by RiyanParvez** [mlc-ai/mlc-llm#260]
i am getting this error when trying to run vicuna, i searched for this issue on the repository and a user said it was due to low vram, but in the supported hardware and speeds it shows that my gpu (1650 with 4 gb vram) is supported.
Heres the full output:
Use MLC config: "dist\\prebuilt\\mlc-chat-vicuna-v1-7b-q3f16_0\\mlc-chat-config.json"
Use model weights: "dist\\prebuilt\\mlc-chat-vicuna-v1-7b-q3f16_0\\ndarray-cache.json"
Use model library: "dist\\prebuilt\\lib\\vicuna-v1-7b-q3f16_0-vulkan.dll"
Loading model...
You can use the following special commands:
  /help               print the special commands
  /exit               quit the cli
  /stats              print out the latest stats (token/sec)
  /reset              restart a fresh chat
  /reload [local_id]  reload model `local_id` from disk, or reload the current model if `local_id` is not specified

[22:07:55] D:\a\package\package\tvm\src\runtime\vulkan\vulkan_buffer.cc:61:
---------------------------------------------------------------
An error occurred during the execution of TVM.
For more information, please see: https://tvm.apache.org/docs/errors.html
---------------------------------------------------------------
  Check failed: (__e == VK_SUCCESS) is false: Vulkan Error, code=-2: VK_ERROR_OUT_OF_DEVICE_MEMORY
Stack trace not available when DMLC_LOG_STACK_TRACE is disabled at compile time.

[22:07:55] D:\a\package\package\tvm\src\runtime\vulkan\vulkan_buffer.cc:61:
---------------------------------------------------------------
An error occurred during the execution of TVM.
For more information, please see: https://tvm.apache.org/docs/errors.html
---------------------------------------------------------------
  Check failed: (__e == VK_SUCCESS) is false: Vulkan Error, code=-2: VK_ERROR_OUT_OF_DEVICE_MEMORY
Stack trace not available when DMLC_LOG_STACK_TRACE is disabled at compile time.

**Comment by yzh119** [comment]
Running `vicuna-v1-7b-q3f16_0` takes around 3.6GB GPU memory, you can try my suggestion in another issue: https://github.com/mlc-ai/mlc-llm/issues/263#issuecomment-1567527503 to clear the GPU memory consumed by X-server and see if it works.

**Comment by RiyanParvez** [comment]
i am on windows

**Comment by yzh119** [comment]
I'm not a Windows user so I have no idea how to disable the graphical interface in Windows.
If you have an integrated graphics CPU (e.g. Intel), I remember that you can control what program are rendered with Intel Graphics and what program rendered with NVIDIA Graphics, see [How to Switch Between Integrated Intel® Graphics and NVIDIA* Discrete Graphics Card in Intel® NUC NUC11PH](https://www.intel.com/content/www/us/en/support/articles/000087403/intel-nuc.html), and in this way, you can save some space for `mlc_llm_cli`.

**Comment by junrushao** [comment]
The error message seems indicative of the out-of-memory issue
