### ISSUE TITLE
[Bug] Could not find a version that satisfies the requirement during installation of prebuilt packages

### ISSUE THREAD

**Issue by SamKG** [mlc-ai/mlc-llm#2605]
## 🐛 Bug

Installation via pip as specified in the [documentation](https://llm.mlc.ai/docs/install/mlc_llm.html) of the prebuilt packages seems to fail with the error

```
ERROR: Could not find a version that satisfies the requirement mlc-llm-nightly-cu121 (from versions: none)
ERROR: No matching distribution found for mlc-llm-nightly-cu121
```

## To Reproduce

1. `python -m pip install --pre -U -f https://mlc.ai/wheels mlc-llm-nightly-cu121 mlc-ai-nightly-cu121`

## Expected behavior

Package installs

## Environment

 - Platform (e.g. WebGPU/Vulkan/IOS/Android/CUDA): Linux p4d ec2 instance with CUDA 12.2
 - Operating system (e.g. Ubuntu/Windows/MacOS/...): Linux AWS Deep Learning AMI 2
 - Python version (e.g. 3.10): python 3.10.14
 - GPU driver version (if applicable): 535.183.01
 - CUDA/cuDNN version (if applicable): 12.2

**Comment by MasterJH5574** [comment]
Hi @SamKG, could you check if `python --version` shows Python 2 or Python 3? If it shows Python 2, we need to use `python3 -m pip install ...`.

**Comment by SamKG** [comment]
Hi,

Here is the output for `python --version`:
`$ python --version
Python 3.10.14`

I am using python 3.10.14.

**Comment by MasterJH5574** [comment]
Thanks for the quick response! This issue looks interesting and our end doesn't have the problem. Could you try manual download these two wheels and install them via `python -m pip install [package-name].whl`? These two should be the matched ones.

* https://github.com/mlc-ai/package/releases/download/v0.9.dev0/mlc_llm_nightly_cu121-0.1.dev1406-cp310-cp310-manylinux_2_28_x86_64.whl
* https://github.com/mlc-ai/package/releases/download/v0.9.dev0/mlc_ai_cu121-0.15.1-cp310-cp310-manylinux_2_28_x86_64.whl

**Comment by MasterJH5574** [comment]
Gonna close this issue for now due to inactivity. You are more than welcome to open new issues.
