### ISSUE TITLE
[Question] How to calculate the VRAM usage in Android package config?

### ISSUE THREAD

**Issue by Lanssi** [mlc-ai/mlc-llm#2609]
## ❓ General Questions

The document states that the parameter for estimated vram is required. Says I want to specify a new model, how should I calculate it to fill that blank?

**Comment by MasterJH5574** [comment]
Thank you for the question. We think you can reuse some of the existing numbers there actually. The estimated VRAM size does not have actual effect for the Android app so far.

**Comment by Lanssi** [comment]
> Thank you @Lanssi for the question. We think you can reuse some of the existing numbers there actually. The estimated VRAM size does not have actual effect for the Android app so far.

Thanks for solving my problem!
