### ISSUE TITLE
[Model Request] Gemma 9b and 27b

### ISSUE THREAD

**Issue by BlindDeveloper** [mlc-ai/mlc-llm#2610]
## ⚙️  Request New Models

- Link to an existing implementation (e.g. Hugging Face/Github): <!-- Link to the model -- https://huggingface.co/google/gemma-2-9b
https://huggingface.co/google/gemma-2-27b
>
- Is this model architecture supported by MLC-LLM? (the list of [supported models](https://llm.mlc.ai/docs/prebuilt_models.html)) <!-- Yes/No -- yes>

## Additional context

<!-- Add any other context that you think would be helpful for the community to add this model
 -- Hello, Could you please add the Gemma 2 models?
Thanks!>

**Comment by yyjhao** [comment]
I gave this a try but I am stuck on the sliding window implementation: https://github.com/mlc-ai/mlc-llm/pull/2674 would love some help if possible!

**Comment by MasterJH5574** [comment]
Hello folks, just want to give an update on this. We merged the initial gemma2 support in #2674 (thanks @yyjhao for the great contribution). The sliding window attn every other layer is yet to be supported in the future, but when the context length does not reach the sliding window size, the gemma2 model should work.

We have uploaded the pre-converted models to https://huggingface.co/mlc-ai. The nightly Pypi package build will happen tonight, and please upgrade the `mlc_llm` package to the latest tomorrow and try out Gemma2.

**Comment by BlindDeveloper** [comment]
@yyjhao 
Hello, could you please add gemma-2-9b-it-q4f16_1-MLc and Llama 3.1 into android prebuild app?

**Comment by MasterJH5574** [comment]
@BlindDeveloper We have already updated the Android apk. You can download the latest app at https://llm.mlc.ai/docs/deploy/android.html

**Comment by BlindDeveloper** [comment]
@MasterJH5574 
In latest app desplayed Gemma 2 2b, but does not Gemma 9b.
