### ISSUE TITLE
In `tvm_runtime.h`, there are extra spaces in `STRINGIFY_MACRO(EXPAND(n1) EXPAND(n2))`.

### ISSUE THREAD

**Issue by XuanqiCui** [mlc-ai/mlc-llm#2618]
## To Reproduce

When[Build Android App from Source](https://llm.mlc.ai/docs/deploy/android.html#id4), during the [Step 2. Build Runtime and Model Libraries](https://llm.mlc.ai/docs/deploy/android.html#id6), while executing `mlc_llm package`, there is a chance that a bug will be triggered due to the extra space between `EXPAND(n1)` and `EXPAND(n2)` in the `#define CONCAT(n1, n2) STRINGIFY_MACRO(EXPAND(n1) EXPAND(n2))` code in `tvm_runtime.h`. This bug manifests as a space appearing between `TVM_SOURCE_DIR` and `/src/runtime/c_runtime_api.cc` when concatenating paths, causing the path to be unrecognizable.

**Comment by MasterJH5574** [comment]
We fixed this in #2616. Could you update and try again?
