### ISSUE TITLE
[Bug] SSL install error on mac

### ISSUE THREAD

**Issue by martystack** [mlc-ai/mlc-llm#2622]
Getting this error today while trying to install on my Mac. Anyone getting an ssl error?

$ python -m pip install --pre -U -f https://mlc.ai/wheels mlc-ai-nightly
Looking in links: https://mlc.ai/wheels
Requirement already satisfied: mlc-ai-nightly in /Users/mstack/.local/lib/python3.11/site-packages (0.15.dev404)
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)'))': /wheels

**Comment by Hzfengsy** [comment]
Might happen if you are using a proxy. Please check your proxy settings are correct
