### ISSUE TITLE
[Question] Are messages always truncated to last `context_length` tokens?

### ISSUE THREAD

**Issue by 0xLienid** [mlc-ai/mlc-llm#2636]
## ❓ General Questions

For example, if I submit 3 messages with a max output length of 500 tokens to GPT-2, on the third one it hangs part of the way through the chat response. I would expect that in your generate functions you would at every step truncate like `tokens[length - context_length:]`, is that not the case? Do I need to manually truncate my inputs to be size `context_length - max_tokens`?

**Comment by CharlieFRuan** [comment]
> Do I need to manually truncate my inputs to be size context_length - max_tokens?

If you want to make sure you can decode `max_tokens` number of tokens, then yes. The logic is that, the generation will stop if either the kv cache size (i.e. context length) is reached, or `max_tokens` is already decoded. If you look at the response object, you may see a finish reason of `"stop"`. This is reflected in code here: https://github.com/mlc-ai/mlc-llm/blob/5bedaec2ca0061eae5ea40f9d575e214adca8130/cpp/serve/request_state.cc#L203-L219

We will always prefill everything and not implicitly truncate the input. If the input already exceeds the kv cache size (i.e. context length), an error will be raised.
