### ISSUE TITLE
[Question] 添加mlc4j包的新版本

### ISSUE THREAD

**Issue by fengmuyan** [mlc-ai/mlc-llm#2637]
如何使用自己编译的模型呢？mlc-package-config.json文件中的model_list的model字段只能是mlc-ai下的模型吗？别的模型下载一直不动？

**Comment by lengjing606** [comment]
可以试下：

**Comment by lengjing606** [comment]
1.mode字段填权重转换后的模型路径

**Comment by lengjing606** [comment]
可参考如下示列：
{
    "device": "android",
    "model_list": [
        {
            "model": "/home/xxxx/mlc-llm/dist/Qwen2-0.5B-Instruct-q4f16_1-MLC",
            "bundle_weight": true,
            "model_lib": "qwen2-q4f16_1",
            "estimated_vram_bytes": 4115131883,
            "model_id": "Qwen2-0.5B-Instruct"
        }
    ],
    "model_lib_path_for_prepare_libs": {
            "qwen2-q4f16_1": "../../dist/libs/Qwen2-0.5B-Instruct-q4f16_1-android.tar"
    }
}

**Comment by fengmuyan** [comment]
> 可参考如下示列： { "device": "android", "model_list": [ { "model": "/home/xxxx/mlc-llm/dist/Qwen2-0.5B-Instruct-q4f16_1-MLC", "bundle_weight": true, "model_lib": "qwen2-q4f16_1", "estimated_vram_bytes": 4115131883, "model_id": "Qwen2-0.5B-Instruct" } ], "model_lib_path_for_prepare_libs": { "qwen2-q4f16_1": "../../dist/libs/Qwen2-0.5B-Instruct-q4f16_1-android.tar" } }

thanks
