### ISSUE TITLE
[Bug] Android deployment answers results that are questionable

### ISSUE THREAD

**Issue by haohenggang** [mlc-ai/mlc-llm#2641]
## To Reproduce

![CjYS1WaJcKaAZVnNAA6rdIqitRw241](https://github.com/mlc-ai/mlc-llm/assets/30398313/71bf8525-94d7-48b3-960e-9512b02276f4)

1.

## Environment

 - Platform (e.g. WebGPU/Vulkan/IOS/Android/CUDA):
 - Operating system (e.g. Ubuntu/Windows/MacOS/...):
 - Device (e.g. iPhone 12 Pro, PC+RTX 3090, ...)
 - How you installed MLC-LLM (`conda`, source):
 - How you installed TVM-Unity (`pip`, source):
 - Python version (e.g. 3.10):
 - GPU driver version (if applicable):
 - CUDA/cuDNN version (if applicable):
 - TVM Unity Hash Tag (`python -c "import tvm; print('\n'.join(f'{k}: {v}' for k, v in tvm.support.libinfo().items()))"`, applicable if you compile models):
 - Any other relevant information:

**Comment by haohenggang** [comment]
> Which model and which quantization?

the model from my company.and others build the answers are ok. I use the llama

**Comment by haohenggang** [comment]
> Which model and which quantization?

mlc_llm convert_weight ./dist/models/ZD-2B-Chat-v1/ --quantization q4f16_1 -o ./dist/nlm2b-q4/
mlc_llm gen_config ./dist/models/ZD-2B-Chat-v1/ --quantization q4f16_1 --model-type llama --conv-template llama-2 --context-window-size 4096 -o ./dist/nlm2b-q4/
mlc_llm compile ./dist/nlm2b-q4/mlc-chat-config.json --device android -o ./dist/libs/nlm2b-q4.tar

**Comment by Hzfengsy** [comment]
The quantization may not work for all customized models, especially those small models. It's not a project bug. Hare are some hint for your further exploration:
1. try `q4f16_2` or `q0f16` if memory size allowed.
2. Try the same `q4f16_1` on cuda or vulkan device to see if it works
3. Try a different model, or a well pretrained model.
