### ISSUE TITLE
[Question]  Qwen model can not use MLC LLM

### ISSUE THREAD

**Issue by tombang** [mlc-ai/mlc-llm#2642]
## ❓ General Questions

Dears,

I have use q4f16_1 and set conv-template to gpt2 for Qwen-1.8B_chat model, but I saw the mlc_chat_config seems invalid, when I ask a normal question like "hello", the model will return "<|im_start|>" and can't stop, the mlc_chat_config like below:

{
  "version": "0.1.0",
  "model_type": "qwen",
  "quantization": "q4f16_1",
  "model_config": {
    "vocab_size": 151936,
    "hidden_size": 2048,
    "num_hidden_layers": 24,
    "num_attention_heads": 16,
    "layer_norm_epsilon": 1e-06,
    "scale_attn_weights": true,
    "kv_channels": 128,
    "rotary_emb_base": 10000,
    "intermediate_size": 11008,
    "context_window_size": 8192,
    "prefill_chunk_size": 2048,
    "tensor_parallel_shards": 1,
    "max_batch_size": 80,
    "head_dim": 128
  },
  "vocab_size": 151936,
  "context_window_size": 8192,
  "sliding_window_size": -1,
  "prefill_chunk_size": 2048,
  "attention_sink_size": -1,
  "tensor_parallel_shards": 1,
  "temperature": 1.0,
  "presence_penalty": 0.0,
  "frequency_penalty": 0.0,
  "repetition_penalty": 1.1,
  "top_p": 0.8,
  "tokenizer_files": [
    "tokenizer_config.json",
    "tokenizer.json",
    "vocab.json",
    "merges.txt",
    "special_tokens_map.json"
  ],
  "tokenizer_info": {
    "token_postproc_method": "byte_level",
    "prepend_space_in_encode": false,
    "strip_space_in_decode": false
  },
  "conv_template": {
    "name": "gpt2",
    "system_template": "{system_message}",
    "system_message": "",
    "system_prefix_token_ids": null,
    "add_role_after_system_message": true,
    "roles": {
      "user": "",
      "assistant": ""
    },
    "role_templates": {
      "user": "{user_message}",
      "assistant": "{assistant_message}",
      "tool": "{tool_message}"
    },
    "messages": [],
    "seps": [
      ""
    ],
    "role_content_sep": "",
    "role_empty_sep": "",
    "stop_str": [
      "</s>"
    ],
    "stop_token_ids": [
      50256
    ],
    "function_string": "",
    "use_function_calling": false
  },
  "pad_token_id": 151643,
  "bos_token_id": 1,
  "eos_token_id": 151643
}

**Comment by Hzfengsy** [comment]
`chatml` template is required for Qwen model

**Comment by tombang** [comment]
> `chatml` template is required for Qwen model

Hello,

I have change the template to chaml and the app is normal, but I have another problem, the prefill token just has 0.4 tok/s, it too slow, could you please give some advise for this problem?

**Comment by Hzfengsy** [comment]
Please tracking issue at https://github.com/mlc-ai/mlc-llm/issues/2648
