### ISSUE TITLE
What to do to re-support MiniCPM-V on mlc? [Question] 

### ISSUE THREAD

**Issue by Foursheepsir** [mlc-ai/mlc-llm#2660]
## ❓ General Questions

Since the codes have been updated and no longer support MiniCPM-V due to MLC and TVM version mismatch, could anyone provide other ways for re-supporting that? Maybe by providing the outdated version of mlc-llm that fitted MiniCPM-V could be helpful (really need that model!)

Or could someone provide any supported multimodal (image-to-text) models (2-3B, support Chinese) that could run on mlc?
Many thanks!

**Comment by MasterJH5574** [comment]
@tlopex would you be interested in this?

**Comment by tlopex** [comment]
Yep, I'll try to support this model after I finished the follow-up PR of starcoder2.

**Comment by Foursheepsir** [comment]
Thanks!
