### ISSUE TITLE
[Question] How to estimation of the vRAM the model takes at runtime?

### ISSUE THREAD

**Issue by limin05030** [mlc-ai/mlc-llm#2666]
In `MLCChat/mlc-package-config.json`, what is the use of `estimated_vram_bytes` value? how to correctly calculate the `estimated_vram_bytes` value of a certain model? What impact does this inaccurate value have?

**Comment by Hzfengsy** [comment]
It's not an accurate value. Just for the simple check to see if the model can run on device
