### ISSUE TITLE
Mistral-Nemo-Instruct-2407 [Model Request] 

### ISSUE THREAD

**Issue by 0xDEADFED5** [mlc-ai/mlc-llm#2671]
## ⚙️  Request New Models

- Link to an existing implementation (e.g. Hugging Face/Github): https://huggingface.co/mistralai/Mistral-Nemo-Instruct-2407
- Is this model architecture supported by MLC-LLM? (the list of [supported models](https://llm.mlc.ai/docs/prebuilt_models.html)) No, needs RoPE support and has custom tokenizer

here's what llama.cpp tokenizer update looked like:

https://github.com/m18coppola/llama.cpp/commit/7fc85054bfb5d622a669f22c8f96e995085df43d

**Comment by yyjhao** [comment]
seems to work by just disabling an assertion: https://github.com/mlc-ai/mlc-llm/pull/2676
