### ISSUE TITLE
[Model Request] Phi 3 Vision

### ISSUE THREAD

**Issue by tmr1** [mlc-ai/mlc-llm#2678]
## ⚙️  Request New Models

- Link to an existing implementation (e.g. Hugging Face/Github): [Phi 3 Vision](https://huggingface.co/microsoft/Phi-3-vision-128k-instruct)
- Is this model architecture supported by MLC-LLM? (the list of [supported models](https://llm.mlc.ai/docs/prebuilt_models.html)) Maybe (Phi 3 is supported, but now you would also need to support the image processing)

**Comment by mengshyu** [comment]
Hi @tmr1 We've added support for Phi 3 Vision[#2658 ]

**Comment by hubertwang** [comment]
Hi @mengshyu, is it supported to run Phi-3-vision on android?

**Comment by mengshyu** [comment]
hi @hubertwang not yet, we are still working on it.

**Comment by MasterJH5574** [comment]
Let's close this as it duplicates with #2388. We are actively working on this.
