### ISSUE TITLE
[Model Request] SmolLM

### ISSUE THREAD

**Issue by tmr1** [mlc-ai/mlc-llm#2679]
## ⚙️  Request New Models

- Link to an existing implementation (e.g. Hugging Face/Github): [SmolLM 135M](https://huggingface.co/HuggingFaceTB/SmolLM-135M-Instruct)
[SmolLM 360M](https://huggingface.co/HuggingFaceTB/SmolLM-360M-Instruct)
[SmolLM 1.7B](https://huggingface.co/HuggingFaceTB/SmolLM-1.7B-Instruct)
- Is this model architecture supported by MLC-LLM? (the list of [supported models](https://llm.mlc.ai/docs/prebuilt_models.html)) No

**Comment by tlopex** [comment]
Hi @tmr1, thanks for your issue! SmolLM is already supported by MLC, you can check PR #2667 and have a try.

**Comment by tmr1** [comment]
Great, thanks!
