### ISSUE TITLE
[Feature Request]

### ISSUE THREAD

**Issue by aibangjuxin** [mlc-ai/mlc-llm#2681]
## 🚀 Feature

Is it possible to allow users to custom-edit the configuration file of the model? Because the current iPad already has 16G of memory now, and I want to try whether a larger model can run.

Want to try whether some 8B models can run?

**Comment by tqchen** [comment]
This problem can be achieved by rebuilding the SDK  with a different larger model. We recommend start enabling these models on python, then change https://github.com/mlc-ai/mlc-llm/blob/main/ios/MLCChat/mlc-package-config.json to include these models
