### ISSUE TITLE
[Model Request] Llama 3.1 8b and Llama 3.1 70 b


### ISSUE THREAD

**Issue by BlindDeveloper** [mlc-ai/mlc-llm#2687]
## ⚙️  Request New Models

- Link to an existing implementation (e.g. Hugging Face/Github):

**Comment by CharlieFRuan** [comment]
Both 8B and 70B are now up on https://huggingface.co/mlc-ai and supported via the latest mlc package. For more, see:
- https://github.com/mlc-ai/mlc-llm/pull/2682
