### ISSUE TITLE
[Question] how to set  gpu_memory_utilization?

### ISSUE THREAD

**Issue by yangpeng666** [mlc-ai/mlc-llm#2691]

**Comment by limin05030** [comment]
Modify the `overrides` parameter when [Launch the Server](https://llm.mlc.ai/docs/deploy/rest.html#id4)

**Comment by yangpeng666** [comment]
> Modify the `overrides` parameter when [Launch the Server](https://llm.mlc.ai/docs/deploy/rest.html#id4)

I can modify "gpu_memory_utilization" in “mlc_llm serve” mode. How to set it when using "mlc_llm chat"?
