### ISSUE TITLE
[Bug] max_single_sequence_length gets overridden?

### ISSUE THREAD

**Issue by kmn1024** [mlc-ai/mlc-llm#2692]
## 🐛 Bug

With mlc-ai/Llama-3.1-8B-Instruct-q4f16_1-MLC (which supports "context_window_size": 131072), I'm trying to input an extremely long prompt (basically an entire book, and one question about the book). Despite setting "max_num_sequence": 1, "max_total_sequence_length": 131072, "max_single_sequence_length": 131072, I still get this error:
`mlc_llm.protocol.error_protocol.BadRequestError: Request prompt has 38726 tokens in total, larger than the model input length limit 8192.`

A related question: does Llama-3.1-8B-Instruct-q4f16_1-MLC support attention sinks? I would like to repeatedly ask questions about the book, and I don't care about context (the questions are not related), but I need the book to remain in context for all questions. So I was thinking of setting attention_sinks to the length of the book. Or, is there a better way to reset cache to the end of the book after every turn?

## To Reproduce
```
from mlc_llm import MLCEngine
from mlc_llm.serve.config import EngineConfig

model = "HF://mlc-ai/Llama-3-8B-Instruct-q4f16_1-MLC"
engine_config = EngineConfig.from_json('''{"additional_models": [], "max_num_sequence": 1, "max_total_sequence_length": 131072, "max_single_sequence_length": 131072}''')
engine = MLCEngine(model, mode = "interactive", engine_config = engine_config)

with open('alice_in_wonderland.txt', 'r') as f:
    txt = f.read()

for response in engine.chat.completions.create(
    messages=[{"role": "user", "content": f"{txt}\n\nIn chapter 5, the Pigeon says Alice must be kind of serpent if she eats what?"}],
    model=model, stream=True):
    for choice in response.choices:
        print(choice.delta.content, end="", flush=True)
```

## Expected behavior

The code should execute without any errors (and hopefully answer the question correctly).

## Environment

 - Platform (e.g. WebGPU/Vulkan/IOS/Android/CUDA): CUDA
 - Operating system (e.g. Ubuntu/Windows/MacOS/...): Ubuntu
 - Device (e.g. iPhone 12 Pro, PC+RTX 3090, ...) RTX3090
 - How you installed MLC-LLM (`conda`, source): python -m pip install --pre -U -f https://mlc.ai/wheels mlc-llm-nightly-cu121 mlc-ai-nightly-cu121
 - How you installed TVM-Unity (`pip`, source): N/A
 - Python version (e.g. 3.10): 3.11.9
 - GPU driver version (if applicable): 550.90.07
 - CUDA/cuDNN version (if applicable): 12.1
 - TVM Unity Hash Tag (`python -c "import tvm; print('\n'.join(f'{k}: {v}' for k, v in tvm.support.libinfo().items()))"`, applicable if you compile models): N/A

## Additional context

Attached 'alice_in_wonderland.txt' (it's just the entire book).
[alice_in_wonderland.txt](https://github.com/user-attachments/files/16375550/alice_in_wonderland.txt)

**Comment by MasterJH5574** [comment]
Thank you for reporting. We will look into this to see how it happens.

**Comment by MasterJH5574** [comment]
We fixed this issue in https://github.com/mlc-ai/mlc-llm/pull/2759, with which it now works well.

BTW Llama3 doesn't support such long context and therefore produces meaningless outputs. Please try `HF://mlc-ai/Llama-3.1-8B-Instruct-q4f16_1-MLC` instead, which answers "eggs" on my end.
