### ISSUE TITLE
[Model Request] minicpm and minicpm-v

### ISSUE THREAD

**Issue by Stephen888888** [mlc-ai/mlc-llm#2693]
## ⚙️  Request New Models

- Link to an existing implementation (e.g. Hugging Face/Github): 
- https://github.com/OpenBMB/MiniCPM/tree/main/model
- 
- Is this model architecture supported by MLC-LLM? (the list of [supported models](https://llm.mlc.ai/docs/prebuilt_models.html))  Yes

**Comment by tqchen** [comment]
cc @tlopex can you look into this one?

**Comment by tlopex** [comment]
@tqchen Yep, no problem. I'll try to support minicpm model first, which has not only standard structure but also has Moe structure.

**Comment by MasterJH5574** [comment]
Minicpm series are supported by #2755, #2808, #2815, thanks for @tlopex's brilliant jobs.
