### ISSUE TITLE
[Bug] Engine restarted with idle process

### ISSUE THREAD

**Issue by Desmond819** [mlc-ai/mlc-llm#2695]
I use pm2 to run the mlc-llm server and after it's running for 2 days. I start to get this error and the server will restart. But after restarted, there will be idle python process occupying 100% of the GPU and make the speed become very slow. Is there anyway to resolve it?
<img width="1137" alt="image" src="https://github.com/user-attachments/assets/1008cc4b-5e26-469d-8a92-676ae70cb4a6">

**Comment by tqchen** [comment]
Did pm2 kill the original engine? The cancelled error in engine happens when requests get cancelled, but the original engine should continue to be functioning. if you can find a way to reproduce the error we would be happy to dig deeper

**Comment by Desmond819** [comment]
I run 2 GPU so literally 2 python programs was running, after the engine restarted, pm2 only killed 1 program, causing overwhelming to the GPU. I can't myself reproduce the error as I get completion requests from the blockchain, but this happens occasionally after the server is running for sometime. Here is how it looks like when this issue happen. the pid 2161 is the idle process which huge memory usage and not release. 
<img width="792" alt="image" src="https://github.com/user-attachments/assets/6417a95c-68cc-400b-a802-5d406185e3c6">

**Comment by Desmond819** [comment]
Looks like it's could be due to way how I start the program. Now I execute the binary directly instead of wrap it with a shell script. It appears mlc_llm is the only program running. I will monitor and see if this resolve the issue.
<img width="792" alt="image" src="https://github.com/user-attachments/assets/30695119-580e-44fd-bcd8-c3d3a2e71919">

**Comment by Desmond819** [comment]
I think when the memory usage goes very high, it will start to get error and pm2 will restart the process but without killing one of them (created for parallel tensor)

**Comment by tqchen** [comment]
Would be nice if you can confirm there is a local command to reproduce the issue. On latest mlc engine, I tried starting the engine with tp=2, and manually run `kill` the main engine process, the extra process did get released as well. Not sure if it is related to how pm2 killed the process
