### ISSUE TITLE
How do i use this in my own programs? 

### ISSUE THREAD

**Issue by Arefaris** [mlc-ai/mlc-llm#27]
Hi there! Im new to programming. I really want to try and implement ai to my own little program. For example chatgpt has api with i can talk using python code. Dose this project allow something like this? Like can i just import mlc-llm and get answers using python?
Sorry for bad english.

**Comment by Lwindsy** [comment]
OpenAI offer API Reference.  https://platform.openai.com/docs/api-reference/introduction

**Comment by XinyuSun** [comment]
> Hi there! Im new to programming. I really want to try and implement ai to my own little program. For example chatgpt has api with i can talk using python code. Dose this project allow something like this? Like can i just import mlc-llm and get answers using python? Sorry for bad english.

Hi! Here is a simple code to implement interaction with mlc-chat-cli in python
[https://github.com/XinyuSun/mlc-chatbot](https://github.com/XinyuSun/mlc-chatbot)

**Comment by tqchen** [comment]
https://github.com/mlc-ai/mlc-llm/tree/main/python
