### ISSUE TITLE
[Bug] error: Multiple top-level packages discovered in a flat-layout: ['web', 'cpp', 'ios', 'site', 'cmake', 'android'].

### ISSUE THREAD

**Issue by llllwwwjj** [mlc-ai/mlc-llm#2708]
## 🐛 Bug

执行命令 # 将mlc-llm安装进环境
pip install .

报错
Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [14 lines of output]
      error: **Multiple top-level packages discovered in a flat-layout: ['web', 'cpp', 'ios', 'site', 'cmake', 'android'].**

      To avoid accidental inclusion of unwanted files or directories,
      setuptools will not proceed with this build.

      If you are trying to create a single distribution with multiple packages
      on purpose, you should not rely on automatic discovery.
      Instead, consider the following options:

      1. set up custom discovery (`find` directive with `include` or `exclude`)
      2. use a `src-layout`
      3. explicitly set `py_modules` or `packages` with a list of names

      To find more information, look for "package discovery" on setuptools docs.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

这个bug怎么解决？

**Comment by llllwwwjj** [comment]
![Uploading 2.PNG…]()

**Comment by MasterJH5574** [comment]
Hi @llllwwwjj, we recommend following the documentation if you want to build from source. https://llm.mlc.ai/docs/install/mlc_llm.html#option-2-build-from-source
