### ISSUE TITLE
[Feature Request][Android] Add Markdown syntax support on Android App.

### ISSUE THREAD

**Issue by kryptobolt07** [mlc-ai/mlc-llm#2726]
## 🚀 Feature
 Add mardown syntax support along with  codemirror support to make code and other outputed text more readable 

## Motivation

This will allow the app to have practical use case

## Alternatives

N/A

**Comment by tqchen** [comment]
As of now we do have not planned the feature,  but we love community contribution to help on this!

**Comment by mengshyu** [comment]
Hi @kryptobolt07, this feature was merged in https://github.com/mlc-ai/mlc-llm/pull/2814

**Comment by kryptobolt07** [comment]
> Hi @kryptobolt07, this feature was merged in #2814

Thanks for informing me,and huge thanks to @huanglizhuo
