### ISSUE TITLE
[Question] Maximum recursion depth of 1000 exceeded

### ISSUE THREAD

**Issue by pipul** [mlc-ai/mlc-llm#273]
## ❓ General Questions
cmake ..
-- Forbidding undefined symbols in shared library, using -Wl,--no-undefined on platform Linux
-- Didn't find the path to CCACHE, disabling ccache
-- VTA build with VTA_HW_PATH=/home/fangdong/baidu/matrix/tvm-unity/3rdparty/vta-hw
-- Build VTA runtime with target: sim
-- Build with contrib.random
-- Build with contrib.sort
-- Build with contrib.hybriddump
-- Git found: /usr/bin/git
-- Found TVM_GIT_COMMIT_HASH=a2bddcf3b21547b72672a88e9d4a0a0fe00321d2
-- Found TVM_GIT_COMMIT_TIME=2023-05-29 09:21:18 -0400
-- Building with TVM Map...
-- Build with thread support...
-- system-nameLinux
-- VERSION: 0.2.00
CMake Error at CMakeLists.txt:118 (set_target_properties):
  set_target_properties Can not find target to add properties to: tvm_dummy

**Comment by rejoicesyc** [comment]
This problem has already been solved in the latest `main` branch after https://github.com/mlc-ai/mlc-llm/pull/281

**Comment by tqchen** [comment]
Thanks @rejoicesyc for confirming! closing for now
