### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by jsoncode** [mlc-ai/mlc-llm#2730]
MLCChat failed

Stack trace:
org.apache.tvm.Base$TVMError: ValueError: Error when loading parameters from params_shard_22.bin: [20:57:18] /Users/kartik/mlc/tvm/src/runtime/relax_vm/ndarray_cache_support.cc:193: Check failed: this->nbytes == raw_data_buffer->length() (33431552 vs. 26896273) : ValueError: Encountered an corrupted parameter shard. It means it is not downloaded completely or downloading is interrupted. Please try to download again.
Stack trace:
  File "/Users/kartik/mlc/tvm/src/runtime/relax_vm/ndarray_cache_support.cc", line 255
![Screenshot_2024-08-02-20-57-52-260_ai mlc mlcchat](https://github.com/user-attachments/assets/100814b5-fa8e-4d23-a109-3643ed1c2f3d)

red mi note 12 pro

**Comment by tqchen** [comment]
As suggested, please consider redownload the weight
