### ISSUE TITLE
[Question] Running MLC_LLM Locally on your Android phone

### ISSUE THREAD

**Issue by Mawriyo** [mlc-ai/mlc-llm#2733]
## ❓ General Questions

Can someone explain the backend of bundle weights.py for android? I thought that you would want to push the weights onto the device so that you dont have to download them within the app. I tried to do this and I still have to download the model despite having it on the device

![Screenshot from 2024-08-02 10-49-43](https://github.com/user-attachments/assets/7e130e52-bc7c-44da-8827-fbe674fad03a)

I may be missing what bundling the weights into the apk is supposed to do but would like some clarification on running locally.

thanks

**Comment by bkiefe** [comment]
Can't answer in detail, but for me, bundle weights py copied the model onto the smartphone from which point on I could use it offline on the phone.

**Comment by Mawriyo** [comment]
Did your path change in the APP-CONFIG? I have attempted to use the directory in /storage/emulated/0/Android......MODELNAME but if I dont use the hf URL I can download it or pull it. I just get an error and a crashed system. 
I do see the weights in the phones file system but I am not sure how to link the APK to find in that directory. 

![Screenshot from 2024-08-02 16-07-02](https://github.com/user-attachments/assets/31f62c64-f246-4b23-881a-16cfca321a06)

**Comment by tqchen** [comment]
bundle weight is only used for debug purposes. For common usage we recommend use the default network download, and you do not need to turn on bundle weights

**Comment by Mawriyo** [comment]
Thanks for the response! I suppose the next question is about non common usage? I think having instructions or the forum as a place of reference is a good idea for others wondering the same thing. For example if I fine-tune gemma or even SmolLM and I dont want to upload the model weights, I am wondering why the need to download them model after a fine tune should occur? Since we package the .tar file into the app via the config, wouldn't it make sense to upload the model as well to avoid needing to redownload it onto the phone? Additionally, can you explain how bundling weights into the signed APK is a debug method? I truly am looking to understand this architecture better and think this is a good place to start.

**Comment by tqchen** [comment]
Thanks for the question, the main reason is that android APK have a size limitation (normally 300MB) so it is harder to package weight as part of APK. iOS apps have larger size limit so it is more feasible.

**Comment by Mawriyo** [comment]
I see, I wasn't aware of that limitation but makes a lot more sense. I am wondering if the next thing I can look into is "replacing" the download button with "load from filesystem". I think the fact that I had to have an active HF repository for it to appear in the view model/UI was something that seemed odd since I am sure there will be moment where internet access will be limited. I can probably look into unless you know of why I should not do this. For example will it break affect/break the chats "State" lifecycle? I guess my end goal would like to be able to replace the HF:// with LF:// in order to run "offline". Right now, the app halts and reports that it "cannot find path" but I am sure its something I am missing as @bkiefe seems to have figured out. I am still fairly new to this so any information is greatly appreciated.

**Comment by Mawriyo** [comment]
To get this to work I had to push the model to the phones file system and set the path to search there.

**Comment by 0-KaiKai-0** [comment]
Can you tell me how to set the path? My app shows Error "Downloading model config failed: non protocol".
