### ISSUE TITLE
Enable multi-turn conversations on Android

### ISSUE THREAD

**Issue by bucess** [mlc-ai/mlc-llm#2740]
Hello, I tried running gemma2-9b-q4f16_1 on Android, but it only seems to support single-turn conversations. How can I enable multi-turn conversations on Android?

**Comment by tqchen** [comment]
this likely is model related, you can try other models, like qwen or phi

**Comment by bucess** [comment]
Thanks for your reply. I've tried qwen2 as well, but it seems to only support single-turn conversations.

**Comment by bucess** [comment]
The compiled model can handle multi-turn conversations on computer when used with mlc_llm chat, but the APK on Android only supports single-turn conversations.

**Comment by tqchen** [comment]
Seems you are right and we missed a support that should be easy to add as we did in iOS app, will update soon.

**Comment by tqchen** [comment]
Related code in iOS that can be used to update android version

- https://github.com/mlc-ai/mlc-llm/blob/main/ios/MLCChat/MLCChat/States/ChatState.swift#L49
- https://github.com/mlc-ai/mlc-llm/blob/main/ios/MLCChat/MLCChat/States/ChatState.swift#L172
- https://github.com/mlc-ai/mlc-llm/blob/main/ios/MLCChat/MLCChat/States/ChatState.swift#L184

**Comment by mengshyu** [comment]
Hi @bucess I have fixed it in #2760, can you try it again with the latest Android APK? Please uninstall MLCChat first, thanks.

**Comment by bucess** [comment]
Thank you!  Is it possible to use gemma2, or is support limited to llama3~3.1?

**Comment by mengshyu** [comment]
Hi @bucess, yes, multi-turn conversation support is available for all models, including gemma2

**Comment by bucess** [comment]
my env:
mlc-ai-nightly-cu121 0.15.dev515
mlc-llm-nightly-cu121 0.1.dev1472
I have updated the code to the latest version.

# mlc_llm gen_config /models/gemma-2-2b-it --quantization q4f16_1 --model-type gemma2 --conv-template gemma_instruction --context-window-size 768 --prefill-chunk-size 256 -o /ok/gemma-2-2b-it-q4f16_1-MLC/

# cat mlc-package-config.json 
{
    "device": "android",
    "model_list": [
        {
            "model": "/ok/gemma-2-2b-it-q4f16_1-MLC/",
            "model_id": "gemma-2-2b-it-q4f16_1-MLC",
            "estimated_vram_bytes": 3000000000,
            "bundle_weight": true,
            "overrides": {
                "context_window_size": 768,
                "prefill_chunk_size": 256
            }

        }
    ]
}
I've successfully compiled an APK, but it keeps crashing on my Xiaomi 14（Snapdragon 8gen3，16G RAM）.I'm having trouble pinpointing the issue, any insights you could offer would be greatly appreciated.

**Comment by tqchen** [comment]
@bucess you want to path in model in a remote url e.g. as in https://github.com/mlc-ai/mlc-llm/blob/main/android/MLCChat/mlc-package-config.json#L16

This is because most APK have size limit and model weights are too large. You can also try bundle weight but that means you need to copy weight to the exact right location.
