### ISSUE TITLE
[Bug] how to accurately measure the real memory usage on Android ？

### ISSUE THREAD

**Issue by MrRace** [mlc-ai/mlc-llm#2748]
After deploying Qwen-4B, Qwen-1.8B, and Qwen-0.5B to an Android phone using mlc-llm, I used the following commands to check the system memory usage:
```
adb shell ps |  findstr "mlc"
adb shell dmabuf_dump PID
adb shell dumpsys meminfo PID
```
However, the results were all similar, showing only a few hundred MB, so I suspect there might be an issue with the method I'm using. Could you please advise on how to accurately measure the real memory usage when mlc-llm is deployed on a phone, both during model loading and runtime? For example, are there any specific commands you would recommend?

**Comment by MasterJH5574** [comment]
Android Studio may have some tools for memory profiling https://developer.android.com/studio/profile/memory-profiler.

**Comment by Hzfengsy** [comment]
a few hundred MB must be the CPU memory usage. However, the model is stored in the GPU memory, so OS-level memory command is not enough

**Comment by MrRace** [comment]
> a few hundred MB must be the CPU memory usage. However, the model is stored in the GPU memory, so OS-level memory command is not enough

Is there a more detailed command?

**Comment by MrRace** [comment]
> Android Studio may have some tools for memory profiling https://developer.android.com/studio/profile/memory-profiler.

@MasterJH5574 You can try, but this method also cannot accurately display memory usage, only a few hundred megabytes.

**Comment by ponytaill** [comment]
I used Android Studio tools for memory profiling, and got the result. It seems to be correct.
![c393468577ea85cd54aaa77057f39dc7](https://github.com/user-attachments/assets/e0824fcf-e7a5-4aed-b89d-5a443c109fdc)

**Comment by MasterJH5574** [comment]
Yes I saw accurate memory usage of gigabytes when I used it last time.

**Comment by pfk-beta** [comment]
Almost perfect sollution:

```shell
watch -n0.1 'adb shell "cat /proc/meminfo | head"'
```

+ read how memory works on android (e.g. https://developer.android.com/topic/performance/memory-management)
