### ISSUE TITLE
[Question] Is there an example using CPU?

### ISSUE THREAD

**Issue by asmith26** [mlc-ai/mlc-llm#2758]
Hi, it looks like this lib supports CPU (e.g. the install instructions: https://llm.mlc.ai/docs/install/mlc_llm.html )

After running `python -m pip install --pre -U -f https://mlc.ai/wheels mlc-llm-nightly mlc-ai-nightly` I'm trying to run the [Command Line Quick Start](https://llm.mlc.ai/docs/get_started/quick_start.html):

```bash
$ mlc_llm chat HF://mlc-ai/Llama-3-8B-Instruct-q4f16_1-MLC
```

But unfortunately I'm getting:
```
INFO auto_device.py:88: Not found device: cuda:0
INFO auto_device.py:88: Not found device: rocm:0
INFO auto_device.py:88: Not found device: metal:0
INFO auto_device.py:88: Not found device: vulkan:0
INFO auto_device.py:88: Not found device: opencl:0
INFO auto_device.py:33: Not found: No available device detected
```

Not sure if I'm doing anything wrong?

Many thanks for any help!

**Comment by MasterJH5574** [comment]
Thank you for the question. Unfortunately we don't support CPU-based inference as of now.
