### ISSUE TITLE
mlc llm and nvidia compute capability mismatch in order of magnitude

### ISSUE THREAD

**Issue by paniabhisek** [mlc-ai/mlc-llm#2771]
## ❓ General Questions

While generating build configurations, it asks to enter compute capability from `(80;86;89;90)`. But `nvidia-docs` shows compute capability in decimal. Even the gpu I am using has compute capability of `7.5`.

**Comment by bethalianovike** [comment]
As I know, 80 means your compute capability is 8.0, 89 means your compute capability is 8.9, and so on. So you need to enter 75 as your CUDA compute capability.

In [the documents](https://llm.mlc.ai/docs/install/tvm.html#id6) said if you are using CUDA and your compute capability is above 80, then it is required to build with set(USE_FLASHINFER ON). If your compute capability is below 80, you can set(USE_FLASHINFER OFF).

**Comment by paniabhisek** [comment]
thank you.
