### ISSUE TITLE
[Question] How to enable the CLI tool to be supported on Android

### ISSUE THREAD

**Issue by handongke** [mlc-ai/mlc-llm#2776]
## ❓ General Questions
There is no Android GUI. Operations cannot be performed by installing the APK.
MLC Chat CLI is the command line tool，It's perfect for me. So How to make CLI tools work on Android，thanks

**Comment by sunzj** [comment]
The cpp cli already removed, right now the cli actualy is a python script. Since you don't have GUI, so the only way is use adb shell. Seems it can't use cli.
