### ISSUE TITLE
[Question] Convert weight doesn't create ndarray-cache.json file 

### ISSUE THREAD

**Issue by vignesh-spericorn** [mlc-ai/mlc-llm#2778]
## ❓ General Questions

When converting weights of Llama-3.1-8B model using `!python -m mlc_llm convert_weight` i'm only getting the params_shard.bin files. The ndarray-cache.json is not getting created. I was following the steps mentioned [here](https://medium.com/google-developer-experts/ml-story-mobilellama3-run-llama3-locally-on-mobile-36182fed3889). Can someone explain what did i do wrong ?

Code:
```
!pip install --pre --force-reinstall mlc-ai-nightly-cu122 mlc-llm-nightly-cu122 -f https://mlc.ai/wheels
!pip install numpy==1.23.5

import mlc_llm
import torch
from huggingface_hub import snapshot_download

from huggingface_hub import notebook_login
notebook_login()

snapshot_download(repo_id="meta-llama/Meta-Llama-3.1-8B-Instruct", local_dir="/content/Llama-3.1-8B-Instruct/")

MODEL_NAME = "Llama-3.1-8B-Instruct"
QUANTIZATION= "q4f16_1"

!python -m mlc_llm convert_weight /content/$MODEL_NAME/ --quantization $QUANTIZATION -o /content/$MODEL_NAME-$QUANTIZATION-android/

```

Enviromnent : Google colab

**Comment by tqchen** [comment]
Not sure what goes wrong in your ase, please do make sure the weight conversion finishes, likely it was due to early cancel of te conversion
