### ISSUE TITLE
[Bug] Importing MLC LLM disables color logging for `rich`

### ISSUE THREAD

**Issue by hykilpikonna** [mlc-ai/mlc-llm#2780]
## 🐛 Bug

I use the `rich` package for colorized logging. However, importing MLC LLM as a python package makes it non-colorized.

## To Reproduce

1. Import MLC LLM
1. Create a logger using RichHandler (see below)
1. The output is not colorized

```py
import logging
import os

def setup_logger(debug: bool = os.environ.get("DEBUG", False)):
    # Try to use rich for pretty printing
    try:
        from rich.logging import RichHandler
        handler = RichHandler(rich_tracebacks=True)

        from rich.traceback import install
        install(show_locals=True)
    except ImportError:
        handler = logging.StreamHandler()

    # Initialize debug logger
    logging.basicConfig(
        level="NOTSET" if debug else "INFO",
        format="%(message)s",
        datefmt="[%X]",
        handlers=[handler]
    )

    return logging.getLogger("a2")


log = setup_logger()
log.info("Hi")
```

## Expected behavior

![image](https://github.com/user-attachments/assets/0bd0b165-01ba-4f1f-a928-d5d11114235a)

**Comment by hykilpikonna** [comment]
The issue can be located in the following lines:

https://github.com/mlc-ai/mlc-llm/blob/36055f01fc656dee0297dc36c60393a38ada9171/python/mlc_llm/support/logging.py#L9-L16

I don't think it is a good idea to initialize a specific logging format in a library. Please consider removing this or moving the initialization code to command line launchers rather than in the initialization of every module file.

**Comment by tqchen** [comment]
this is a good suggestion, @hykilpikonna do you mind send a PR to fix this
