### ISSUE TITLE
[Question] Speculative Decoding Metrics Variable

### ISSUE THREAD

**Issue by bethalianovike** [mlc-ai/mlc-llm#2789]
## ❓ General Questions

What is the meaning behind `draft_count`, `accept_count`, and `spec_draft_length`? Thank you in advance!

**Comment by MasterJH5574** [comment]
Hi @bethalianovike, thanks for your question and sorry for the delayed response. Happy to elaborate on the config and metrics here.

`spec_draft_length` is the number of draft tokens we generate for each request in each round of speculative decoding generation, and it is configurable.

`draft_count` and `accept_count` are internal statistics. In our codebase, `draft_count[i]` means how many times “there are `i + 1` tokens generated in the draft,” and `accept_count[i]` means how many times “there are `i + 1` tokens generated in the draft and all these `i + 1` tokens are accepted in the spec decode verification phase”. Consequently, `draft_count[i] / accept_count[i]` means “the history frequency of that generating `i + 1` tokens in the draft and all these `i + 1` tokens are accepted”.
