### ISSUE TITLE
[Trying to compile my fine-tuned llama3 llm using MLC-LLM but keep running to this]

### ISSUE THREAD

**Issue by danielhse** [mlc-ai/mlc-llm#2790]
## ❓ General Questions about Compiling using MLC-LLM
(venv) root@0192b97af942:/workspace/venv/lib/python3.11/site-packages/mlc_llm# python3 -c "import mlc_llm; print(mlc_llm.__file__)"
/workspace/venv/lib/python3.11/site-packages/mlc_llm/__init__.py
(venv) root@0192b97af942:/workspace/venv/lib/python3.11/site-packages/mlc_llm# python3 -m mlc_llm.build   --model /workspace/lora_model   --target cuda   --quantization q4f16_1   --use-safetensors   --artifact-path /workspace/compiled-models
/workspace/venv/bin/python3: No module named mlc_llm.build

P.S. I have already had the special_tokens_map, tokenizer_config, and tokenizer JSON file in the lora_model folder. Are these all I need to compile my finetuned model using MLC-LLM?

**Comment by Hzfengsy** [comment]
mlc_llm.build is a deprecated interface, please refer latest docs:
https://llm.mlc.ai/docs/compilation/convert_weights.html
https://llm.mlc.ai/docs/compilation/compile_models.html
