### ISSUE TITLE
[Question] 

### ISSUE THREAD

**Issue by lcystudy** [mlc-ai/mlc-llm#2799]
## ❓ General Questions

您好，由于网络访问限制，我没有办法直接从https://mlc.ai/wheels下载对应的文件，在https://github.com/mlc-ai/package这个仓库里下载了mlc_llm_nightly-0.1.dev1483-cp311-cp311-macosx_13_0_arm64.whl和mlc_ai-0.15.1-cp311-cp311-macosx_13_0_arm64.whl这两个文件，验证tvm成功安装
<img width="566" alt="截屏2024-08-13 11 20 50" src="https://github.com/user-attachments/assets/bc934d88-683c-453b-bcb9-ca91655a6628">
因为numpy2.0会报错于是把numpy版本降到了1.24.4出现了警告但应该不影响
在安装完mlcllm之后，运行"import mlc_llm; print(mlc_llm)"报错如下：
<img width="571" alt="截屏2024-08-13 11 16 58" src="https://github.com/user-attachments/assets/e624c349-cd1d-442d-a8f3-a01a1621701e">
请问这是什么问题，后面根据源码重新编译了tvm和mlcllm库，tvm可以运行，但是mlcllm依然报同样的错误

**Comment by MasterJH5574** [comment]
Thanks @lcystudy for reporting. The tvm wheel `mlc_ai-0.15.1-cp311-cp311-macosx_13_0_arm64.whl` you installed does not work for the latest mlc-llm. So you also need to install the **nightly** `mlc_ai` wheel (e.g., `mlc_ai_nightly-0.15.dev***-cp311-cp311-macosx_13_0_arm64.whl`).

**Comment by lcystudy** [comment]
Yes,I have sloved the problem,thanks!
