### ISSUE TITLE
Running into WebGPU device error from the web demo, using Chrome 112

### ISSUE THREAD

**Issue by mikelam14** [mlc-ai/mlc-llm#28]
When trying this out, https://mlc.ai/web-llm/#chat-demo, it gave me the following error. My chrome is 112.0.5615.137 and in the setting no update option is there. 
```
Find an error initializing the WebGPU device Error: Cannot initialize runtime because of requested maxBufferSize exceeds limit. requested=1024MB, limit=256MB. This error may be caused by an older version of the browser (e.g. Chrome 112). You can try to upgrade your browser to Chrome 113 or later.
Init error, Error: Find an error initializing WebGPU: Error: Cannot initialize runtime because of requested maxBufferSize exceeds limit. requested=1024MB, limit=256MB. This error may be caused by an older version of the browser (e.g. Chrome 112). You can try to upgrade your browser to Chrome 113 or later.
```

**Comment by junrushao** [comment]
Yeah, as indicated in the error message:
> This error may be caused by an older version of the browser (e.g. Chrome 112)

We recommend using [Chrome Canary](https://www.google.com/chrome/canary/). You can also try out the latest Chrome 113. Chrome version ≤ 112 is not supported, and if you are using it, the demo will raise an error like Find an error initializing the WebGPU device OperationError.

You might want to follow the [instruction](https://mlc.ai/web-llm/#instructions) section to use the latest WebGPU feature

**Comment by junrushao** [comment]
I am going to close this issue as the problem should be solved in the instruction section, but feel free to reopen if it doesn't work!
