### ISSUE TITLE
[Question] Is anybody able to run speculative decoding on AMD GPUs?

### ISSUE THREAD

**Issue by manu-web** [mlc-ai/mlc-llm#2818]
## ❓ General Questions

This is the error I am getting - **TVMError: Check failed: token_tree_parent_ptr[j] == j - verify_start (0 vs. 1) : CPU sampler only supports chain-style draft tokens.**

This is the main part of the code that I am using - 

def fcallback(delta_outputs: List[RequestStreamOutput]):
        for delta_output in delta_outputs:
            request_id, stream_outputs = delta_output.unpack()
            assert len(stream_outputs) == 1
            outputs[int(request_id)] += stream_outputs[0].delta_token_ids

    # Create engine
    spec_engine = SyncMLCEngine(
        model=model,
        mode="server",
        engine_config=EngineConfig(
            max_total_sequence_length=4096,
            additional_models=[small_model],
            spec_draft_length=4,
            speculative_mode="small_draft",
            max_num_sequence=6,
        ),
        request_stream_callback=fcallback,
    )
    
    num_requests = 1

    # Generate output.
    output_texts, _ = spec_engine.generate(
        prompts[:num_requests], GenerationConfig(temperature=0.0, top_p=0, seed=42, max_tokens=30, stop_token_ids=[2], n=1)
    )
    for req_id, outputs in enumerate(output_texts):
        print(f"Prompt {req_id}: {prompts[req_id]}")
        if len(outputs) == 1:
            print(f"Output {req_id}:{outputs[0]}\n")
        else:
            for i, output in enumerate(outputs):
                print(f"Output {req_id}({i}):{output}\n")

**Comment by MasterJH5574** [comment]
@manu-web Thanks for reporting this! It's a bug and we've fixed it in #2824. If you built MLC from source, you can checkout the latest main branch, build and try again.

**Comment by manu-web** [comment]
@MasterJH5574 Thank you for the response. But I have been unable to install mlc-llm from source for AMD GPUs. Is the documentation up to date?

**Comment by MasterJH5574** [comment]
@manu-web I see. Regarding the source code build, we will check the documentation.

If you installed mlc-llm from pip, we recently encountered some GitHub action issue and so didn't update the ROCm nightly built packages. We'll work on that as soon as possible and report back when you can upgrade the pip packages.

**Comment by MasterJH5574** [comment]
Hi @manu-web we have updated the documentation to reflect the [prebuilt pip package installation](https://llm.mlc.ai/docs/install/mlc_llm.html#option-1-prebuilt-package) and the source code build.

Note that we upgraded our support to ROCm 6.1/6.2 and deprecated the previous 5.6/5.6 support, so you may need to upgrade your ROCm version to 6.1 or 6.2 by following https://rocm.docs.amd.com/projects/install-on-linux/en/docs-6.2.0/install/quick-start.html. With ROCm 6, our prebuilt pip package comes with hipBLAS integration which brings better performance.

Would you like to try out and share your experience? We tried best and did some internal testing to make sure that the prebuilt package can work. We are more than happy to hear any feedback you may have and are happy to help if any problem occurs. Thank you.

**Comment by Erxl** [comment]
> Hi @manu-web we have updated the documentation to reflect the [prebuilt pip package installation](https://llm.mlc.ai/docs/install/mlc_llm.html#option-1-prebuilt-package) and the source code build.
> 
> Note that we upgraded our support to ROCm 6.1/6.2 and deprecated the previous 5.6/5.6 support, so you may need to upgrade your ROCm version to 6.1 or 6.2 by following https://rocm.docs.amd.com/projects/install-on-linux/en/docs-6.2.0/install/quick-start.html. With ROCm 6, our prebuilt pip package comes with hipBLAS integration which brings better performance.
> 
> Would you like to try out and share your experience? We tried best and did some internal testing to make sure that the prebuilt package can work. We are more than happy to hear any feedback you may have and are happy to help if any problem occurs. Thank you.

 Translation: "I cannot use speculative decoding on my AMD GPU server. The server is running, but there is no response to any chat requests, and there are no any error outputs. no output similar to `INFO:     192.168.1.4:34425 - "POST /v1/chat/completions HTTP/1.1" 200 OK`. Is this related to the current issue? I have already updated ROCm to 6.2 and installed the latest pre-built mlcllm Python package."

**Comment by manu-web** [comment]
I did not try speculative decoding. But the hipblas and rocblas, does not seem to benefit much at least for ISL-OSL 128-128 case. Do we have to compile the engine with a special arg to enable it? Llama.cpp already uses rocblas kernels for context phase gemms, so would love to try it out. 

However, just as a side note, is there any plan to add flash attention support for AMD? I am not sure if we have currently, even if we have fmha performs very poorly on AMD 7900 XTX.

**Comment by MasterJH5574** [comment]
@manu-web Yes it is possible to disable hipblas, which right now needs you to manually compile models using `mlc_llm compile` with the optimization option `--opt "cublas_gemm=0"`, as documented in this page https://llm.mlc.ai/docs/compilation/compile_models.html. We should be able to improve the flow so that in the future you don't have to manually run this step, but as of now a manual model compilation is required if you want to disable hipblas.

On the other hand, even when hipblas is enabled, we don't use it all the time. We only leverage hipblas for gemms, and for gemv we use our own fast customized kernels.
