### ISSUE TITLE
[Model Request]  phi 3.5 for android demo app

### ISSUE THREAD

**Issue by BlindDeveloper** [mlc-ai/mlc-llm#2829]
Hello, could you add phi 3.5 mini model in android demo app?

**Comment by BlindDeveloper** [comment]
@mengshyu  
Thanks for uploading the model, they probably haven't managed to add it to the Android demo app.

**Comment by MasterJH5574** [comment]
@BlindDeveloper The Phi3.5 support is introduced in #2839. @mengshyu will help update the Android apk soon.

**Comment by BlindDeveloper** [comment]
@MasterJH5574  thank you!

**Comment by BlindDeveloper** [comment]
@mengshyu  thanks for update android app!

**Comment by mengshyu** [comment]
Hi @BlindDeveloper, Although the APK has been updated, but we found the processing time of Phi 3.5 prefill is too long. We are still looking into this issue and welcome your help in solving this performance problem.

**Comment by BlindDeveloper** [comment]
@mengshyu  My smartphone doesn't have enough RAM to run this model.
Do you try Phi-3.5-mini-instruct-q4f16_0-MLC?
