### ISSUE TITLE
[Bug] 2x7900xtx运行Mistral-7B-Instruct-v0.3-q4f16_1-MLC卡死在loading parameters

### ISSUE THREAD

**Issue by Erxl** [mlc-ai/mlc-llm#2833]
- Ubuntu22.04
- 2x7900xtx
- python3.10
- amgpu-install安装的rocm5.7.3
- `python3 -m pip install --pre -U -f https://mlc.ai/wheels mlc-llm-nightly-rocm57 mlc-ai-nightly-rocm57`安装
- --device rocm
- --mode 默认local
- 不开张量并行没有问题，瞬间加载完成
- 开张量并行就会卡死在loading parameters不动，等待很长仍然没有反应
- python进程cpu占用总有两个核是满的
- 等待很长时间显存占用都只有1g，没有看到显存涨

**Comment by MasterJH5574** [comment]
Hi @Erxl we have updated the documentation to reflect the [prebuilt pip package installation](https://llm.mlc.ai/docs/install/mlc_llm.html#option-1-prebuilt-package) and the source code build.

Note that we upgraded our support to ROCm 6.1/6.2 and deprecated the previous 5.6/5.6 support, so you may need to upgrade your ROCm version to 6.1 or 6.2 by following https://rocm.docs.amd.com/projects/install-on-linux/en/docs-6.2.0/install/quick-start.html. With ROCm 6, our prebuilt pip package comes with hipBLAS integration which brings better performance.

Would you like to try out and share your experience? We tried best and did some internal testing to make sure that the prebuilt package can work on two 7900XTX GPUs. We are more than happy to hear any feedback you may have and are happy to help if any problem occurs. Thank you.

**Comment by Erxl** [comment]
solved: https://www.cnblogs.com/JiangOil/p/10513906.html
