### ISSUE TITLE
[Bug] mlc_llm generates randomly corrupted Unicode character when outputting Chinese

### ISSUE THREAD

**Issue by LuRenJiasWorld** [mlc-ai/mlc-llm#2835]
## To Reproduce

1. Install latest mlc-llm and mlc-ai in conda with python 3.12, running on an Apple Silicon (M1 Pro) MacBook Pro with 32 GiB of RAM
2. Download Qwen-2-7b-MLC Model from https://huggingface.co/mlc-ai/Qwen2-7B-Instruct-q4f16_1-MLC (Other LLMs can also reproduce this issue)
3. Using mlc_llm serve Qwen2-7B-Instruct-q4f16_1-MLC --host 0.0.0.0 to run the server (mlc_llm chat can also reproduce this issue)
4. In any application that can produce many outputs (for example immersive translate working with OpenAI compatible API), I can see the following result, which contains many corrupted Chinese character.
![wecom-temp-210601-c6c28ad642b7a653de81603bb9ae5509](https://github.com/user-attachments/assets/4dbaae75-4b83-44d0-9b61-fecbe1be605b)
![wecom-temp-122688-1b8ddf75ef55a6ac8030475ebdb13170](https://github.com/user-attachments/assets/401c5f4d-73df-4e70-a0be-4c319dabd743)
![wecom-temp-112502-31845a08e6749aa4f2d3734cd5a5ad5d](https://github.com/user-attachments/assets/530751df-8240-4a83-8d0c-855532895b6c)

When I use a Linux server with Nvidia L20 GPU, by using the same model, same application, same prompt, I could also reproduce this issue, but not as frequently as MacBook does.

<img width="1847" alt="image" src="https://github.com/user-attachments/assets/365ce4fb-5ffa-4c6c-a239-39fd4a31107b">

## Expected behavior

There should not have corrupted Unicode character when outputting Chinese, which is frustrating, makes me frequently guess what the word should be.

**Comment by LuRenJiasWorld** [comment]
<img width="502" alt="image" src="https://github.com/user-attachments/assets/e1fba2e0-fa16-4cba-be67-4d952ec0d248">
It appeared again when I tried to translate this issue XD

**Comment by LuRenJiasWorld** [comment]
It seems like the corruption often occurred at the first Chinese character after a non-Chinese character, is tokenizers to be the cause?

**Comment by MasterJH5574** [comment]
Hi @LuRenJiasWorld, sorry for the delayed response. Do you mind providing a Python script that runs with MLCEngine and we can use to reproduce? That will be very helpful for identifying the problem.

**Comment by samuelqy** [comment]
facing same issue

**Comment by samuelqy** [comment]
My best guess is tokenizer.decode inside tvm has some issues

**Comment by bojiang** [comment]
@MasterJH5574 
I can reproduce with:
```
mlc_llm serve HF://mlc-ai/Qwen2.5-32B-Instruct-q4f16_1-MLC  --host 0.0.0.0
```
and
query with

```
system: You are a helpful assistant. You can help me by answering my questions. You can also ask me questions.
user: 用遗造句，每句一个编号
```
<img width="708" alt="截屏2024-10-14 10 19 44" src="https://github.com/user-attachments/assets/c6b5f8c5-f6e4-493d-9f7a-1936949b9dd0">

**Comment by MasterJH5574** [comment]
Hi @LuRenJiasWorld @samuelqy @bojiang, we fixed this issue in https://github.com/mlc-ai/mlc-llm/pull/2978. It will be merged soon and will be ready in the nightly prebuilt package by tomorrow. Please upgrade the pip package and try again, thanks! And please also let us know if there are further issues.

**Comment by bojiang** [comment]
Great work! Thanks!

**Comment by samuelqy** [comment]
Nice work!
