### ISSUE TITLE
[Bug] crash when getting an answer from Qwen

### ISSUE THREAD

**Issue by Kaneki-x** [mlc-ai/mlc-llm#2846]
## 🐛 Bug

<img width="1935" alt="image" src="https://github.com/user-attachments/assets/447b82c7-44b1-4607-a322-6d08d8c86c54">

I already try #2788 way to fix the problem，but it still doesn't work

Attached is the crash log I grabbed, my device is Google Pixel 7, Android 15

[Google-Pixel-7-Android-15_2024-08-24_014644.log](https://github.com/user-attachments/files/16732229/Google-Pixel-7-Android-15_2024-08-24_014644.log)

**Comment by Kaneki-x** [comment]
Found a temporary solution to this crash, but it shouldn't be the final solution

add `case kTVMArgBool:` into `jni_helper_func.h` file's `tvmRetValueToJava` method switch to temporary handle this case

**Comment by hubertwang** [comment]
Same issue here, thank you @Kaneki-x , your solution works!

**Comment by Kaneki-x** [comment]
update the 3rdparty/tvm submodule to [Fix boolean value conversion for Java](https://github.com/mlc-ai/relax/commit/f65b73221a83b2a94c383c5d1b0bfd6d75c69800) commit will solve this problem
