### ISSUE TITLE
[Bug]  gemma2_q4f16_1_batch_prefill_ragged_kv: Expect arg[10] to be int

### ISSUE THREAD

**Issue by mos-fine** [mlc-ai/mlc-llm#2865]
Why is initialization successful when running on Android using gemma2-2b-it model compression, but shows org.apache.tvm.Base$TVMError: TVMError: Assert fail: rotary_mode_code == 0, gemma2_q4f16_1_ batch_prefill_ragged_kv: Expect arg[10] to be int error, unable to dialog

**Comment by zhiwei-dong** [comment]
Hi,

I noticed that this issue has been closed, but I’m curious about how you resolved it. Could you please share the steps you took or any insights that helped you overcome the error related to rotary_mode_code when using the gemma2-2b-it model compression on Android?

Thank you!

**Comment by mos-fine** [comment]
Just recompile using the latest code and tools from the mlc-llm repository

**Comment by zhiwei-dong** [comment]
What specific "tools" are you referring to? I'm using the latest code. This information would be helpful for me in understanding and resolving the problem

**Comment by mos-fine** [comment]
Some of the latest tool packages in https://mlc.ai/wheels, you can try to delete your cache and then start again.

**Comment by zhiwei-dong** [comment]
Get, thx.
