### ISSUE TITLE
[Bug] InternalError: Check failed: type_code_ == kTVMPackedFuncHandle (0 vs. 10) : expected FunctionHandle but got int

### ISSUE THREAD

**Issue by Mawriyo** [mlc-ai/mlc-llm#2884]
## 🐛 Bug

I made a new environment and using NIGHTLY install packages got 

InternalError: Check failed: type_code_ == kTVMPackedFuncHandle (0 vs. 10) : expected FunctionHandle but got int

Similar issues 
https://discuss.tvm.apache.org/t/check-failed-type-code-ktvmobjecthandle-0-vs-8-expected-object-but-got-int/12504

This seems to be an ISSUE TIME AND TIME AGAIN whenever there is an update. 

Is there any chance you can release a tag with a stable release? IF NOT please provide which llvm version you use, cmake, android ndk, and other variables... Following the guide seems to cause these issues and lack of clear versioning...

**Comment by MasterJH5574** [comment]
Apologize for the inconvenience. The latest nightly packages have fixed the issue. You may need to use environment variable `MLC_JIT_POLICY=REDO python -m mlc_llm chat ...` to force the automatic model recompilation after upgrade. Meanwhile we are working on a stable release.

**Comment by Mawriyo** [comment]
HI @MasterJH5574 I was able to resolve this by redownloading the nightly build. 

Are there any safeguard to remove pushing a broken version of MLC onto the pip repo? I ask because I have noticed many reports of similar issues. It may help reduce the amount of technical debt too. I am not much of a CI/CD guy but maybe this can be something for the community to help out with.
