### ISSUE TITLE
[Bug] llama2 radix_tree->MatchPrefix fail cause lots of redunction prefilling.

### ISSUE THREAD

**Issue by sunzj** [mlc-ai/mlc-llm#2897]
I found a interesting issue on llama2, radix_tree->MatchPrefix fail, cause lots of redunction prefilling.

The issue is:
1. Enter prompt S1, llama2 tokenize to "S1+29871".
2. Decode result is S2.
3. The radix_tree store "S1+29871+S2"
4. Enter prompt S3, history and S3 tokenize to "S1+S2+S3+29871".
5. radix_tree->MatchPrefix try to match "S1+S2+S3+29871" with "S1+29871+S2", and only find "S1" matched.
6. Since only "S1" match, then KV Cache Pop "29871+S2", and send "S2+S3+29871" to prefill.

So, llama2 tokenizer plus token "29871" for the prompt, cause radix tree match fail, thus mlc use "last decode result + prompt" to prefill everytime, actully it's only need "prompt"

The issue only happens on llama2.

**Comment by MasterJH5574** [comment]
cc @cyx-6

**Comment by tqchen** [comment]
to resolve this, likely we will need to enable a mode that matches on string content

**Comment by cyx-6** [comment]
Thanks for reporting! So token 29871 is the fixed suffix in each prefill appended by llama2, and will be forwarded to newly prefill during next generation. Is my understanding correct?

**Comment by sunzj** [comment]
> Thanks for reporting! So token 29871 is the fixed suffix in each prefill appended by llama2, and will be forwarded to newly prefill during next generation. Is my understanding correct?

As i test, Yes, 29871 is the fixed suffix of llama2 tokenizer.

At the beginning of second round conversion. The prompt is "prompt2", the message  [https://github.com/mlc-ai/mlc-llm/blob/main/python/mlc_llm/interface/chat.py#L188C9-L188C18](url)  send to request is: "prompt1+decode1+prompt2" and it tokenize to **M**: "_prompt1+decode1+prompt2+29871_".  

Tokens store in radix_tree are **S**: "_prompt1+29871+decode1_":  Since the first round of conversion, "prompt1" tokenize to "_prompt1+29871_" add the decode result is "_decode1_". 

Then radix_tree->MatchPrefix try to match:
**M**: "_prompt1+decode1+prompt2+29871_"
**S**: "_prompt1+29871+decode1_"

only "_prompt1_" match, so **M** - **S** : "_decode1+prompt2+29871_" is sent to prefill. 

But actully, only "_prompt2+29871_" is needed.

**Comment by cyx-6** [comment]
https://medium.com/@manyi.yim/in-depth-understanding-of-llama-tokenizer-d91777025dab
seems that token 29871 may occur in many cases. We may add a string-based prefix cache, in addition to current token-based prefix cache, to root this issue.
