### ISSUE TITLE
[Question]  How to bundle weight directly in android apk?

### ISSUE THREAD

**Issue by ponytaill** [mlc-ai/mlc-llm#2900]
## ❓ General Questions

Hi, I am studying the source code of the MLCChat Android project, and I want to know if I can directly put the model weights into the apk for installation instead of using bundle_weight.py. 
I learned from Chatgpt that it can be placed in the assets directory and installed with the apk, but it seems that the weight file cannot be obtained as a File type, which conflicts with the current code. Is this technically feasible?

**Comment by Mawriyo** [comment]
I still dont get the bundle weights thing tbh....

https://github.com/mlc-ai/mlc-llm/issues/2733 I got it to work. Heres my initial conversation about it.

**Comment by ponytaill** [comment]
> I still dont get the bundle weights thing tbh....
> 
> #2733 I got it to work. Heres my initial conversation about it.

I now think downloading model weights online might be a better solution :)
