### ISSUE TITLE
[Question] How can I access my own models in the MLC-LLM App ???

### ISSUE THREAD

**Issue by Ruban-07** [mlc-ai/mlc-llm#2911]
## ❓ General Questions

1. I've used the `MLCChat` App, it showing the below models alone which is shown in the screenshot, how can I access my own models, which is in my device?
2. Is there any possible to use my local models in this `MLCChat` App ?
3. How can I do this with flutter?

## 🔗 Screenshot
![image](https://github.com/user-attachments/assets/36bff802-b2b3-4616-aebc-d13aae41c9f4)

## Expected behavior
Kindly help me out in this doubt, thank you.

**Comment by Mawriyo** [comment]
https://github.com/mlc-ai/mlc-llm/issues/2733 I got it to work. Heres my initial conversation about it.

**Comment by Ruban-07** [comment]
> #2733 I got it to work. Heres my initial conversation about it.

Thank you so much dude!
