### ISSUE TITLE
[Question] Facing build issue in Android MLC-LLM Chat App!!!

### ISSUE THREAD

**Issue by Ruban-07** [mlc-ai/mlc-llm#2914]
## ❓ General Questions

When I run MLC-LLM Chat Android app, I'm getting some build errors which is captured in the screenshot
![image](https://github.com/user-attachments/assets/24de4291-7e96-4111-a364-6d728bfc5be8)![image](https://github.com/user-attachments/assets/58b7c8af-a017-4b30-b3df-aa5a6b741992)

Please help me to fix this issue, I can't able fix this. Thank you!

**Comment by Kaneki-x** [comment]
you should run` mlc_llm package` in MLCChat first. Please carefully read the Android section of the [document](https://llm.mlc.ai/docs/deploy/android.html), rather than just importing the project and running it directly.

**Comment by Ruban-07** [comment]
> you should run` mlc_llm package` in MLCChat first. Please carefully read the Android section of the [document](https://llm.mlc.ai/docs/deploy/android.html), rather than just importing the project and running it directly.

Sure, Thank you!

**Comment by Ruban-07** [comment]
> you should run` mlc_llm package` in MLCChat first. Please carefully read the Android section of the [document](https://llm.mlc.ai/docs/deploy/android.html), rather than just importing the project and running it directly.

Thank you so much, it's worked!
