### ISSUE TITLE
[Bug] 3rdparty/tvm submodule not found in mlc_llm python package directory

### ISSUE THREAD

**Issue by remon-rakibul** [mlc-ai/mlc-llm#2915]
## 🐛 Bug

I installed the mlc python package in a conda environment. The android documentation suggests to add TVM Unity runtime like this:

export TVM_SOURCE_DIR=/path/to/mlc-llm/3rdparty/tvm

but there is no directory 3rd party in the mlc-llm package directory in conda env

## To Reproduce

1. conda activate your-environment
1. python -m pip install --pre -U -f https://mlc.ai/wheels mlc-llm-nightly-cpu mlc-ai-nightly-cpu
1. check mlc-llm package directory if there's any folder named 3rdparty

## Expected behavior

the 3rdparty/tvm directory should be there as mentioned in the docs 

## Environment

 - Platform (e.g. WebGPU/Vulkan/IOS/Android/CUDA): Android
 - Operating system (e.g. Ubuntu/Windows/MacOS/...): Ubuntu MacOS
 - How you installed MLC-LLM (`conda`, source): conda
 - How you installed TVM-Unity (`pip`, source): pip
 - Python version (e.g. 3.10): 3.11

**Comment by remon-rakibul** [comment]
I am talking about exporting the tvm path mentioned in the documentation.

"TVM Unity runtime is placed under 3rdparty/tvm in MLC LLM, so there is no need to install anything extra. Set up the following environment variable:

export TVM_SOURCE_DIR=/path/to/mlc-llm/3rdparty/tvm"
 https://llm.mlc.ai/docs/deploy/android.html#:~:text=TVM%20Unity%20runtime%20is,mlc%2Dllm/3rdparty/tvm

**Comment by MasterJH5574** [comment]
Thank you @remon-rakibul for the question. When you install the mlc-llm package via `pip install`, only the Python part is installed and it does not include any 3rdparty. As @AspenFPS suggested, we need to get a copy of the mlc-llm full source code via `git clone`, which is mentioned in the document https://llm.mlc.ai/docs/deploy/android.html#step-1-install-build-dependencies.

Thank you for letting us know the confusion here and we'll update the documentation to make it clear that a `git clone` is needed.
