### ISSUE TITLE
[Question] after pip install mlc-llm, No module named 'mlc_llm'

### ISSUE THREAD

**Issue by kidhan1234** [mlc-ai/mlc-llm#2932]
## ❓ General Questions
when i use a new environment, i have use python -m pip install --pre -U -f https://mlc.ai/wheels mlc-llm-nightly-cu121 mlc-ai-nightly-cu121 to install. There are no error, and i successfully  install the package. But then i run python -c "import mlc_llm; print(mlc_llm)",the bug is No module named 'mlc_llm'

my environment is Linux, cuda12.1, python 3.10

![image](https://github.com/user-attachments/assets/d94e75bb-3e15-4afe-9753-c71e5efa9460)

**Comment by ali-asad-fzea** [comment]
Try installing their cou version too

**Comment by rickzx** [comment]
@kidhan1234 Please make sure you're using the correct Python interpreter. Compare `pip show mlc-llm-nightly-cu121` and `python -c "import sys; print(sys.path)"` to make sure that the correct Python path is included.

**Comment by MasterJH5574** [comment]
Hey folks, we recently deprecated the package for cuda 12.1. So could you try the following instead?
```
python -m pip install --pre -U -f https://mlc.ai/wheels mlc-llm-nightly-cu122 mlc-ai-nightly-cu122
```

**Comment by whr819987540** [comment]
@MasterJH5574 
Still failed.

```bash
(mlc_llm) whr@jetson-agx-orin-32:~/hust_2/code/cloud_end/test_mlc_llm$ python -c "import mlc_llm; print(mlc_llm)"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'mlc_llm'
(mlc_llm) whr@jetson-agx-orin-32:~/hust_2/code/cloud_end/test_mlc_llm$ pip show mlc-llm-nightly-cu122
Name: mlc-llm-nightly-cu122
Version: 0.1
Summary: Machine learning for systems
Home-page: https://github.com/mlc-ai
Author: mlc-ai
Author-email: tianqi.tchen@gmail.com
License: Apache-2.0
Location: /home/whr/miniconda3/envs/mlc_llm/lib/python3.10/site-packages
Requires: 
Required-by: 
(mlc_llm) whr@jetson-agx-orin-32:~/hust_2/code/cloud_end/test_mlc_llm$ python -c "import sys; print(sys.path)"
['', '/home/whr/miniconda3/envs/mlc_llm/lib/python310.zip', '/home/whr/miniconda3/envs/mlc_llm/lib/python3.10', '/home/whr/miniconda3/envs/mlc_llm/lib/python3.10/lib-dynload', '/home/whr/miniconda3/envs/mlc_llm/lib/python3.10/site-packages']

```
