### ISSUE TITLE
[Question] Please explain how the VRAM mechanism of MLC-LLM works on AMD ROCm 6.1?

### ISSUE THREAD

**Issue by shahizat** [mlc-ai/mlc-llm#2955]
## ❓ General Questions

Hello everyone,

I am running inference using two dual AMD Radeon RX 7900 XTX GPUs with the following command:
`mlc_llm chat HF://mlc-ai/Llama-3.1-70B-Instruct-q4f16_1-MLC --overrides "tensor_parallel_shards=2;prefill_chunk_size=128"`

During inference, I have observed that the GPU utilization remains constant at 86% and 87% when sending multiple prompts. Is the static preloading? How it differs from vLLM and others

Could you please explain the meaning of "interactive" mode? Is it the same as submitting multi-turn conversational questions within a single context window?

**Comment by MasterJH5574** [comment]
Hi @shahizat thanks for the question, for `Llama-3.1-70B-Instruct-q4f16_1-MLC` the quantized model weights is about 39GB in total. Given you are using dual 7900 XTX it will then be about 18.5 GB on each GPU, which already takes 77% of the 24GB VRAM. We need some more VRAM for KV cache and runtime intermediate memory, which adds up to the 86% and 87% you observed.
