### ISSUE TITLE
Is there a stable release?

### ISSUE THREAD

**Issue by plufz** [mlc-ai/mlc-llm#2965]
## Is there a stable release?

I noticed that the instruction for installing refers to a nightly build. I.e. 
`python -m pip install --pre -U -f https://mlc.ai/wheels mlc-llm-nightly-cpu mlc-ai-nightly-cpu`

Is there no stable version that is recommened to use at this stage? Sorry if I am missing something obvious here! :)

**Comment by MasterJH5574** [comment]
@plufz Yes we started to do stable releases. Right now you can install
```
python -m pip install --pre -U -f https://mlc.ai/wheels mlc-llm-cpu mlc-ai-cpu
```
We will add to our documentation.
