### ISSUE TITLE
'tvm/runtime/packed_func.h' file not found

### ISSUE THREAD

**Issue by mubeenasif01** [mlc-ai/mlc-llm#2970]
## 🐛 Bug

Trying to Build iOS Project but facing the issue in MLCSwift Package that 'tvm/runtime/packed_func.h' file not found

Using Xcode 16. 

<img width="1423" alt="Screenshot 2024-10-10 at 3 02 53 AM" src="https://github.com/user-attachments/assets/17819c97-fecf-48a8-99ba-7e119d851cf6">

**Comment by MasterJH5574** [comment]
Hi @mubeenasif01! Just wondering if you have asked this in the discord server and if it is resolved, thanks!

**Comment by mubeenasif01** [comment]
@MasterJH5574  Yes, It's resolved now. Thanks.

**Comment by loredunk** [comment]
how to solve it? please?

**Comment by SebRincon** [comment]
I am having the same issue atm

**Comment by dieffe** [comment]
Same issue, no answer on Discord server

**Comment by mathav95raj** [comment]
I am also having the same issue. How was it resolved?
I was thinking mlc can run only on device directly and this issue came up when trying to run in simulator

**Comment by mubeenasif01** [comment]
Please try to install mlc package properly as mentioned here in documentation.

https://llm.mlc.ai/docs/deploy/ios.html

**Comment by mathav95raj** [comment]
@mubeenasif01 I have installed the packages properly now. I am getting this error now,
<img width="445" alt="Image" src="https://github.com/user-attachments/assets/feb08630-594e-4ff3-aa50-3c1070e6194a" />

Did you build it on phone directly or in emulator?

**Comment by dim971** [comment]
Hello, I'm having the same issue. I followed the instructions of the documentation to install mlc_llm properly, the command works, but it does not compile.

<img width="1324" alt="Image" src="https://github.com/user-attachments/assets/e87481a5-3f19-4f67-8edc-8977f5d97f86" />

**Comment by tomasfn** [comment]
Was this solved?

**Comment by nikolaknez** [comment]
Cant install package maximum recursion depth exceeded

**Comment by nikolaknez** [comment]
@MasterJH5574  how was it resolved ?

**Comment by nikolaknez** [comment]
@mubeenasif01 how was it resolved ?

**Comment by hanna-dudina** [comment]
I am also having the same issue. How was it resolved?
Also, I want to clarify — are specific versions of Conda, Rust, and CMake important for the build to work correctly? If yes, could you please share the recommended versions?

**Comment by jonahallibone** [comment]
I am also having this problem in my react native app.
