### ISSUE TITLE
[Question] Performance on long sequence

### ISSUE THREAD

**Issue by gabrielolympie** [mlc-ai/mlc-llm#2971]
## ❓ General Questions

In my tests, performance on short sequence is incredible, but when i am going in the range of 10k tokens, the generation speed drops significantly (much more than with vllm or exllama).

Would you have an idea about how i could improve this?

(i am using Qwen 2.5 on a 3090)

**Comment by MasterJH5574** [comment]
Thank you for the question. We have not yet looked into the regime of 10k long context so it is likely that the optimization is not sufficient. We will further work on this. As a side note, we recently published a blogpost summarizing our results and lessons in low-latency LLM serving https://blog.mlc.ai/2024/10/10/optimizing-and-characterizing-high-throughput-low-latency-llm-inference, please definitely check it out if you're interested!
