### ISSUE TITLE
[Bug] DLL error

### ISSUE THREAD

**Issue by ArpanDhot** [mlc-ai/mlc-llm#3003]
## 🐛 Bug

I am getting this DLL error when composing mlc
![379672277-51fb52c4-1783-4504-869e-642c2d717f7e](https://github.com/user-attachments/assets/c26a5a31-9375-4580-ac58-994730c541fa)

## Environment

 - Platform: Android
 - Operating system: Windows
 - Device: PC+RTX 2060
 - How you installed MLC-LLM: `conda`
 - How you installed TVM-Unity: `pip`
 - Python version: 3.10

**Comment by Lanssi** [comment]
@ArpanDhot Hi! Could you please tell me how you installed the mlc_llm and tvm package in detail? Especially how you installed mlc_llm through conda?

**Comment by ArpanDhot** [comment]
@ArpanDhot I couldn’t get MLC to run. The Windows documentation was unclear, and there was a bug in the Git command due to the path being too long. I think they’ve updated the documentation since, but I stopped trying after spending over a week on it. There are other libraries you might want to consider instead.

**Comment by ArpanDhot** [comment]
Help not provided
