### ISSUE TITLE
[Question] How to export MLCChat .apk with weight bundled/included?

### ISSUE THREAD

**Issue by lifelongeeek** [mlc-ai/mlc-llm#3013]
## ❓ General Questions

Hello. 
I want to share MLCChat .apk including the model weights.
I successfully follow 'bundle weight' guideline in (https://llm.mlc.ai/docs/deploy/android.html#bundle-model-weights), and try to export .apk afterward. However, the exported .apk does not include the model weight inside. The size of the .apk is about 105MB, and my MLC model is about 4GB.

How to export MLCChat .apk with weight bundled/included?

**Comment by Mawriyo** [comment]
https://github.com/mlc-ai/mlc-llm/issues/2733
