### ISSUE TITLE
[Bug] Error compiling ./cpp/llm_chat.cc on a M1 Pro system

### ISSUE THREAD

**Issue by ghostsun89** [mlc-ai/mlc-llm#302]
## 🐛 Bug

While I compiled the project, it appears the following errors:

```
/Users/xm/Documents/Projects/mlc_llm/mlc-llm/cpp/llm_chat.cc:877:85: error: non-virtual member function marked 'final' hides virtual member function
  PackedFunc GetFunction(const String& name, const ObjectPtr<Object>& sptr_to_self) final {
...
/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/tvm/include/tvm/runtime/memory.h:122:18: error: allocating an object of abstract class type 'mlc::llm::LLMChatModule'
      new (data) T(std::forward<Args>(args)...);
```

## Reproduce

./mlc-llm
1. mkdir build
2. cd build
3. cmake
4. make
```
[  0%] Building CXX object CMakeFiles/mlc_llm_objs.dir/cpp/conv_templates.cc.o
[  0%] Building CXX object CMakeFiles/mlc_llm_objs.dir/cpp/conversation.cc.o
[  0%] Building CXX object CMakeFiles/mlc_llm_objs.dir/cpp/llm_chat.cc.o
/Users/xm/Documents/Projects/mlc_llm/mlc-llm/cpp/llm_chat.cc:877:85: error: non-virtual member function marked 'final' hides virtual member function
  PackedFunc GetFunction(const String& name, const ObjectPtr<Object>& sptr_to_self) final {
                                                                                    ^
/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/tvm/include/tvm/runtime/module.h:168:22: note: hidden overloaded virtual function 'tvm::runtime::ModuleNode::GetFunction' declared here: type mismatch at 1st parameter ('const std::string &' (aka 'const basic_string<char, char_traits<char>, allocator<char>> &') vs 'const tvm::runtime::String &')
  virtual PackedFunc GetFunction(const std::string& name,
                     ^
In file included from /Users/xm/Documents/Projects/mlc_llm/mlc-llm/cpp/llm_chat.cc:9:
In file included from /Users/xm/Documents/Projects/mlc_llm/mlc-llm/cpp/llm_chat.h:6:
In file included from /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/tvm/include/tvm/runtime/container/string.h:29:
In file included from /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/tvm/include/tvm/runtime/container/./base.h:29:
/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/tvm/include/tvm/runtime/memory.h:122:18: error: allocating an object of abstract class type 'mlc::llm::LLMChatModule'
      new (data) T(std::forward<Args>(args)...);
                 ^
/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/tvm/include/tvm/runtime/memory.h:72:23: note: in instantiation of function template specialization 'tvm::runtime::SimpleObjAllocator::Handler<mlc::llm::LLMChatModule>::New<>' requested here
    T* ptr = Handler::New(static_cast<Derived*>(this), std::forward<Args>(args)...);
                      ^
/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/tvm/include/tvm/runtime/memory.h:196:31: note: in instantiation of function template specialization 'tvm::runtime::ObjAllocatorBase<tvm::runtime::SimpleObjAllocator>::make_object<mlc::llm::LLMChatModule>' requested here
  return SimpleObjAllocator().make_object<T>(std::forward<Args>(args)...);
                              ^
/Users/xm/Documents/Projects/mlc_llm/mlc-llm/cpp/llm_chat.cc:1021:32: note: in instantiation of function template specialization 'tvm::runtime::make_object<mlc::llm::LLMChatModule>' requested here
  ObjectPtr<LLMChatModule> n = make_object<LLMChatModule>();
                               ^
/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/tvm/include/tvm/runtime/module.h:168:22: note: unimplemented pure virtual method 'GetFunction' in 'LLMChatModule'
  virtual PackedFunc GetFunction(const std::string& name,
                     ^
2 errors generated.
make[2]: *** [CMakeFiles/mlc_llm_objs.dir/cpp/llm_chat.cc.o] Error 1
make[1]: *** [CMakeFiles/mlc_llm_objs.dir/all] Error 2
make: *** [all] Error 2
```

## Expected behavior

make success

## Environment

 - CLI:
 - MacOS 13.4:
 - Device (e.g. iPhone 12 Pro, PC+RTX 3090, ...): NA
 - How you installed MLC-LLM (`conda`, source): source
 - How you installed TVM-Unity (`pip`, source): pip
 - Python version (e.g. 3.10): 3.11
 - GPU driver version (if applicable): NA
 - CUDA/cuDNN version (if applicable): NA
 - TVM Unity Hash Tag (`python -c "import tvm; print('\n'.join(f'{k}: {v}' for k, v in tvm.support.libinfo().items()))"`, applicable if you compile models):
USE_GTEST: AUTO
SUMMARIZE: OFF
USE_IOS_RPC: OFF
CUDA_VERSION: NOT-FOUND
USE_LIBBACKTRACE: AUTO
DLPACK_PATH: 3rdparty/dlpack/include
USE_TENSORRT_CODEGEN: OFF
USE_THRUST: OFF
USE_TARGET_ONNX: OFF
USE_AOT_EXECUTOR: ON
USE_CUDNN: OFF
USE_TENSORRT_RUNTIME: OFF
USE_ARM_COMPUTE_LIB_GRAPH_EXECUTOR: OFF
USE_CCACHE: AUTO
USE_ARM_COMPUTE_LIB: OFF
USE_CPP_RTVM: 
USE_OPENCL_GTEST: /path/to/opencl/gtest
USE_MKL: OFF
USE_PT_TVMDSOOP: OFF
USE_CLML: OFF
USE_STACKVM_RUNTIME: OFF
USE_GRAPH_EXECUTOR_CUDA_GRAPH: OFF
ROCM_PATH: /opt/rocm
USE_DNNL: OFF
USE_VITIS_AI: OFF
USE_LLVM: llvm-config --link-static
USE_VERILATOR: OFF
USE_TF_TVMDSOOP: OFF
USE_THREADS: ON
USE_MSVC_MT: OFF
BACKTRACE_ON_SEGFAULT: OFF
USE_GRAPH_EXECUTOR: ON
USE_ROCBLAS: OFF
GIT_COMMIT_HASH: f611983b2c7c320f854bdc239657538df7efa4cc
USE_VULKAN: OFF
USE_RUST_EXT: OFF
USE_CUTLASS: OFF
USE_CPP_RPC: OFF
USE_HEXAGON: OFF
USE_CUSTOM_LOGGING: OFF
USE_UMA: OFF
USE_FALLBACK_STL_MAP: OFF
USE_SORT: ON
USE_RTTI: ON
GIT_COMMIT_TIME: 2023-05-31 17:21:50 -0400
USE_HEXAGON_SDK: /path/to/sdk
USE_BLAS: none
USE_ETHOSN: OFF
USE_LIBTORCH: OFF
USE_RANDOM: ON
USE_CUDA: OFF
USE_COREML: OFF
USE_AMX: OFF
BUILD_STATIC_RUNTIME: OFF
USE_CMSISNN: ON
USE_KHRONOS_SPIRV: OFF
USE_CLML_GRAPH_EXECUTOR: OFF
USE_TFLITE: OFF
USE_HEXAGON_GTEST: /path/to/hexagon/gtest
PICOJSON_PATH: 3rdparty/picojson
USE_OPENCL_ENABLE_HOST_PTR: OFF
INSTALL_DEV: OFF
USE_PROFILER: ON
USE_NNPACK: OFF
LLVM_VERSION: 15.0.7
USE_OPENCL: OFF
COMPILER_RT_PATH: 3rdparty/compiler-rt
RANG_PATH: 3rdparty/rang/include
USE_SPIRV_KHR_INTEGER_DOT_PRODUCT: OFF
USE_OPENMP: OFF
USE_BNNS: OFF
USE_CUBLAS: OFF
USE_METAL: ON
USE_MICRO_STANDALONE_RUNTIME: ON
USE_HEXAGON_EXTERNAL_LIBS: OFF
USE_ALTERNATIVE_LINKER: AUTO
USE_BYODT_POSIT: OFF
USE_HEXAGON_RPC: OFF
USE_MICRO: ON
DMLC_PATH: 3rdparty/dmlc-core/include
INDEX_DEFAULT_I64: ON
USE_RELAY_DEBUG: OFF
USE_RPC: ON
USE_TENSORFLOW_PATH: none
TVM_CLML_VERSION: 
USE_MIOPEN: OFF
USE_ROCM: OFF
USE_PAPI: OFF
USE_CURAND: OFF
TVM_CXX_COMPILER_PATH: /Library/Developer/CommandLineTools/usr/bin/c++
HIDE_PRIVATE_SYMBOLS: ON
 - cmake output information: 
-- The C compiler identification is AppleClang 14.0.0.14000029
-- The CXX compiler identification is AppleClang 14.0.0.14000029
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Performing Test SUPPORT_CXX17
-- Performing Test SUPPORT_CXX17 - Success
-- Setting default build type to RelWithDebInfo
-- Forbidding undefined symbols in shared library, using -Wl,-undefined,error on platform Darwin
-- Didn't find the path to CCACHE, disabling ccache
-- VTA build with VTA_HW_PATH=/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/tvm/3rdparty/vta-hw
-- Build VTA runtime with target: sim
-- Build with contrib.random
-- Build with contrib.sort
-- Build with contrib.hybriddump
-- Git found: /opt/homebrew/bin/git
-- Not a git repo
-- Building with TVM Map...
-- Build with thread support...
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE  
-- Performing Test FILE_PREFIX_MAP_SUPPORTED
-- Performing Test FILE_PREFIX_MAP_SUPPORTED - Success
-- system-nameDarwin
-- VERSION: 0.2.00
-- Configuring done (2.3s)
-- Generating done (0.2s)
-- Build files have been written to: /Users/xm/Documents/Projects/mlc_llm/mlc-llm/build

**Comment by yzh119** [comment]
Please follow the documentation: https://mlc.ai/mlc-llm/docs/install/index.html#id15

**Comment by junrushao** [comment]
This is a bug that I fixed in this commit: https://github.com/mlc-ai/mlc-llm/commit/d1c1a67a3009ca35289b557045dde538a4ec41ec

Please check if it works on HEAD :-)

**Comment by ghostsun89** [comment]
@junrushao Yeah, it works now.
