### ISSUE TITLE
[Bug] encouterned Unsupported class file major version 66 on windows

### ISSUE THREAD

**Issue by HelloWorldU** [mlc-ai/mlc-llm#3049]
## To Reproduce

1. l built Android App from Source refered to official document(https://llm.mlc.ai/docs/deploy/android.html#deploy-android)
2.l built the model,see below picture 1 && 2 and successed
3.l Opened folder ./android/MLCChat as an Android Studio Project. Connect your Android device to my machine. In the menu bar of Android Studio, click “Build → Make Project”. it's so wired to always encountered Unsupported class file major version 66 about tvm4j_core.jar, as you could see in pic 3.

## Expected behavior

l've tried serveral times of diverse method such as different jdk or build.gradle doc,but it couldn't build suceussfully.
## Environment

 - Platform (e.g. WebGPU/Vulkan/IOS/Android/CUDA): android
 - Operating system (e.g. Ubuntu/Windows/MacOS/...): windows
 - Device (e.g. iPhone 12 Pro, PC+RTX 3090, ...) : honor 50
 - How you installed MLC-LLM (`conda`, source): conda
 - How you installed TVM-Unity (`pip`, source):
 - Python version (e.g. 3.10):
 - GPU driver version (if applicable):
 - CUDA/cuDNN version (if applicable):
 - TVM Unity Hash Tag (`python -c "import tvm; print('\n'.join(f'{k}: {v}' for k, v in tvm.support.libinfo().items()))"`, applicable if you compile models):
 - Any other relevant information:

## Additional context

![image](https://github.com/user-attachments/assets/27ffdd1b-f556-4c4d-86b8-593128327ed8)
![image](https://github.com/user-attachments/assets/d2969fcc-0412-4cae-a4bd-1e9d63373868)
![image](https://github.com/user-attachments/assets/a0fcc796-6bf6-4927-857b-a7d260d9c542)

**Comment by HelloWorldU** [comment]
![image](https://github.com/user-attachments/assets/9df9f7df-11f0-49f2-86e3-2ec753e1ffe1)
this is the pic 3,actually the JAVA_HOME variable is the same with jdk where l set in Android Studio

**Comment by Lanssi** [comment]
It seems that I've encounter the same problem once. I remembered the main reason is the version mismatch.
You said that you've tried different version of jdk. But did you remove the cached files before rebuild the project? From my experience, when you build the project first time, it may cached some files. So even if you change your jdk version, if you don't remove those cache, you will still get a failure.

So my suggestion is:
1. Change the version of jdk (mine is jdk 17)
2. Compare with the official file tree in `mlc_llm/android` and remove the unnecessary files
3. Rebuild it again

**Comment by HelloWorldU** [comment]
> It seems that I've encounter the same problem once. I remembered the main reason is the version mismatch. You said that you've tried different version of jdk. But did you remove the cached files before rebuild the project? From my experience, when you build the project first time, it may cached some files. So even if you change your jdk version, if you don't remove those cache, you will still get a failure.
> 
> So my suggestion is:
> 
> 1. Change the version of jdk (mine is jdk 17)
> 2. Compare with the official file tree in `mlc_llm/android` and remove the unnecessary files
> 3. Rebuild it again

thank u, l follow your step and finally successed, l remove all the related files called build (this is the key) and rebuild it again.
