### ISSUE TITLE
[question]  Where to get the cuda version of mlc-ai

### ISSUE THREAD

**Issue by vfdff** [mlc-ai/mlc-llm#3062]
* I think this question is similar to https://github.com/mlc-ai/mlc-llm/issues/2799, as we can access the **https://mlc.ai/wheels**, so we can install mlc-ai with pip install --pre mlc-ai-nightly-cu122 -f https://mlc.ai/wheels.

* It provide a alternate link **https://github.com/mlc-ai/package/releases** in above issue,  but there is no cuda versions there, so my question is where can I get the cuda version of mlc-ai ?

**Comment by ereish64** [comment]
The cuda version is after the cu part of the wheel name
The python version is after the cp part of the wheel name

For example:
mlc_ai_cu122-0.15.1-cp311-cp311-manylinux_2_28_x86_64.whl
would be Cuda12.2 for python3.11

In other words, any wheel in the releases part of this repo that include cu in the name are going to be for CUDA. Just make sure you match your package name with the cuda version installed on your computer (which can be obtained from the command line using:
nvcc --version


Hope this helps!

**Comment by vfdff** [comment]
Thanks very much @ereish64
