### ISSUE TITLE
[Bug] No module named 'tvm' after specifing the TVM dynamic library

### ISSUE THREAD

**Issue by vfdff** [mlc-ai/mlc-llm#3072]
## 🐛 Bug

* report  **No module named 'tvm'**
![image](https://github.com/user-attachments/assets/6596cd80-742b-4cb6-95fd-169b5e059b7a)

## To Reproduce

1. According https://tvm.hyper.ai/docs/install/from_source, I build the tvm base on source code, and I can see libtvm.so      libtvm_runtime.so under **/home/zhongyunde/tvm/build**
![image](https://github.com/user-attachments/assets/691dbc87-27fa-451b-815b-fa474f35657d)
2. then I config **export TVM_LIBRARY_PATH=/home/zhongyunde/tvm/build** ,and test it with **python test.py** 
```
import tvm
from tvm import relax
from tvm.relax.frontend import nn


class MLPModel(nn.Module):
    def __init__(self):
        super(MLPModel, self).__init__()
        self.fc1 = nn.Linear(784, 256)
        self.relu1 = nn.ReLU()
        self.fc2 = nn.Linear(256, 10)

    def forward(self, x):
        x = self.fc1(x)
        x = self.relu1(x)
        x = self.fc2(x)
        return x
```

## Expected behavior

works fine without error message

## Environment (172)

 - Python 3.11.0
 -  Ubuntu 7.5.0-3ubuntu1~18.04 (cat /proc/version)

**Comment by MasterJH5574** [comment]
Thank you for the question. Could you try set the PYTHONPATH accordingly? For packages that are not installed via pip or conda, Python finds packages via PYTHONPATH. For your case, you may try
```
export PYTHONPATH=/home/zhongyunde/tvm/python
```

`import tvm` is supposed to work after this step, and you may consider putting this line in your `.bashrc`.

**Comment by vfdff** [comment]
yes, it works, thanks very much
