### ISSUE TITLE
[Feature Request] Delete model functionality on Android/IOS app

### ISSUE THREAD

**Issue by devanshamin** [mlc-ai/mlc-llm#312]
## 🚀 Feature
Functionality to delete models from the Android/IOS app.

## Motivation

I downloaded the `vicuna-v1-7b-q3f16_0` model on the iPhone 12 device. But the model couldn't initialize due to not having enough memory. Now I want to delete the `vicuna-v1-7b-q3f16_0` model to free up space. But currently the only way to do it is to delete the app and reinstall the app.

## Alternatives

Maybe in the future you can perform a check when adding a new model using the URL if the model will work with the current mobile device before downloading the model.

Thank you!

**Comment by vitaliyhan** [comment]
Same problem. I would like to delete llama 2 model, and use only pajama model on my iOS device. But I can't delete model inside the interface, nor in file manager. Delete button does not work on default model.

**Comment by tqchen** [comment]
this is now supported in ios
