### ISSUE TITLE
[Bug] Wrong Answer

### ISSUE THREAD

**Issue by leftthomas** [mlc-ai/mlc-llm#314]
## To Reproduce

![IMG_6578](https://github.com/mlc-ai/mlc-llm/assets/9991443/fed80730-f2c3-4c87-bde8-079436567215)

## Expected behavior
Jay Chou is an American man?

## Environment

 - Platform (e.g. WebGPU/Vulkan/IOS/Android/CUDA): IOS
 - Operating system (e.g. Ubuntu/Windows/MacOS/...): IOS
 - Device (e.g. iPhone 12 Pro, PC+RTX 3090, ...):  iPhone 12
 - How you installed MLC-LLM (`conda`, source): APP Store
 - How you installed TVM-Unity (`pip`, source):
 - Python version (e.g. 3.10):
 - GPU driver version (if applicable):
 - CUDA/cuDNN version (if applicable):
 - TVM Unity Hash Tag (`python -c "import tvm; print('\n'.join(f'{k}: {v}' for k, v in tvm.support.libinfo().items()))"`, applicable if you compile models):

**Comment by Hzfengsy** [comment]
MLC-LLM is a project focusing on DEPLOYING models, rather than training the models. The model outputs are fully depends on the model itself, which is not in our control. You can try to report this issue to the RedPajama community :)
