### ISSUE TITLE
[Bug] crash in vkCreateComputePipelines

### ISSUE THREAD

**Issue by Atlantis12000** [mlc-ai/mlc-llm#331]
I'm on win10 x64(intel UHD Graphics 630) (I know VRAM is not enough, just for test), using the downloaded RedPajama-INCITE-Chat-3B-v1-q4f16_0 model, VS2022 to compile the source code;

(First cargo and vulkan are installed and env TVM_HOME is set, in cmake set USE_VULKAN to ON;

Then I had a few compile errors, and I modified it:
1.llm_chat.cc line 877 String to std::string;
2.mlc_llm and mlc_llm_moudle project link dependencies add ntdll.lib)

Then run the command mlc_chat_cli --local-id RedPajama-INCITE-Chat-3B-v1-q4f16_0 --device-name vulkan
exception occurs:
llm_chat.cc line:872 tvm::runtime::Registry::Get("vm.builtin.memory_manager.clear");
ICHECK(fclear_memory_manager) << "Cannot find env function vm.builtin.memory_manager.clear";

I searched through the code and found no place to register this function (TVM_REGISTER_GLOBAL("vm.builtin.memory_manager.clear").set_body_typed), so comment out the this code;
Build and run)

Finally, the exception occurs:

igc64.dll! 00007ff8b8bec51f()
igc64.dll! 00007ff8b9499b7c()
igc64.dll! 00007ff8b9492bc4()
igc64.dll! 00007ff8b94b2c57()
igvk64.dll! 00007ff8716d48e9()
igvk64.dll! 00007ff8716d3e70()
igvk64.dll! 00007ff8716cefd4()
igvk64.dll! 00007ff8716cc708()
> tvm_runtime.dll!tvm::runtime::vulkan::VulkanModuleNode::GetPipeline(unsigned __int64 device_id, const std::string & func_name, unsigned __int64 num_pack_args) line 385

and variable pipeline_cinfo.stage.pName is "take_decode_kernel0";
igc64.dll file description is Intel Graphics Shader Compiler, with no pdb and source code;
Any suggestions?

**Comment by junrushao** [comment]
Please refer to our official doc for TVM installation rather than commenting out code :-)

https://mlc.ai/mlc-llm/docs/install/tvm.html
