### ISSUE TITLE
[Model Request] sources for RedPajama-3b and Vicuna-7B

### ISSUE THREAD

**Issue by tobrun** [mlc-ai/mlc-llm#332]
It's great to have these prebuild models on huggingface:
- https://huggingface.co/mlc-ai/mlc-chat-RedPajama-INCITE-Chat-3B-v1-q4f32_0
- https://huggingface.co/mlc-ai/mlc-chat-vicuna-v1-7b-q3f16_0

And have them preconfigured in app-config.json 
but without the actual sources, we won't be able to generate the android.tar required as part of `./prepare_libs.sh`.

Would be great to either have the sources of the models provided on huggingface or have them android.tar files commited to the repo in /dist

**Comment by namchuai** [comment]
Sorry I'm a noob.

When I follow this documentation: https://github.com/mlc-ai/mlc-llm/tree/main/android, I thought that I can use `databricks/dolly-v2-3b` instead of `vicuna`. But I encountered error that said not found `vicuna` later on.

Could someone please guide me the next step? I think I might using some of the `vicuna` models available on Huggingface, like this one: `eachadea/vicuna-7b-1.1` to continue, but I'm not sure.

Thanks for reading!

**Comment by junrushao** [comment]
I'm not sure if I fully capture what you mean. Currently we release MLC-generated model libs via this repo: https://github.com/mlc-ai/binary-mlc-llm-libs, but as you just mentioned, we haven't provided a prebuilt Android one yet, which is the problem. As you suggested, it may be a good idea to instead move this github repo into HF - did I get this right? Thanks a lot!

**Comment by tobrun** [comment]
@junrushao 

Apologies, I'm still diving deep into this project and unable to give you a correct contextual answer or try fixing it myself. I can however try describing the scenario I'm having issues with and, considering the upvotes, others are having as well.

- clean clone of project
- go through installation instructions for Android
- run in `cd android && ./prepare_libs.sh`

It will produce an error for both the preconfigured vicuna and redpajama from `app-config.json` because we don't have any data in `dist/` or `dist/models`. I was however assuming we can run the chatapp using prebuild data from huggingface without downloading/building anything extra. Either I'm missing something or there is something that can be optimized. 

> RuntimeError: Cannot find /home/tobrun/ws/mlc-llm/dist/vicuna-v1-7b-q4f32_0/vicuna-v1-7b-q4f32_0-android.tar

**Comment by tqchen** [comment]
https://llm.mlc.ai/docs/deploy/android.html should contain latest instructions
