### ISSUE TITLE
[Bug] make[2]: *** [tokenizers/CMakeFiles/tokenizers_c.dir/build.make:71: tokenizers/release/libtokenizers_c.a] Error 1

### ISSUE THREAD

**Issue by felixslu** [mlc-ai/mlc-llm#335]
## To Reproduce

1.  python3 build.py --hf-path databricks/dolly-v2-3b --quantization q3f16_0 **(It is OK!)**
2.  Build the CLI :
     cd build
     cmake ..
     make

## Expected behavior

[  0%] Built target mlc_llm_objs
[  0%] Built target mlc_cli_objs
[ 45%] Built target sentencepiece-static
[ 54%] Built target tvm_libinfo_objs
[100%] Built target tvm_runtime_objs
[100%] Built target tvm_runtime
[100%] Generating release/libtokenizers_c.a
No such file or directory
make[2]: *** [tokenizers/CMakeFiles/tokenizers_c.dir/build.make:71: tokenizers/release/libtokenizers_c.a] Error 1
make[1]: *** [CMakeFiles/Makefile2:553: tokenizers/CMakeFiles/tokenizers_c.dir/all] Error 2
make: *** [Makefile:156: all] Error 2

## Environment

 - Platform (Intel):
 - Operating system ( Ubuntu):
 - Device ( PC+RTX 3090, ...)
 - How you installed MLC-LLM (source):
 - How you installed TVM-Unity (`pip`):
 - Python version (3.11):
 - GPU driver version (if applicable):
 - CUDA/cuDNN version (if applicable):
 - TVM Unity Hash Tag (`python -c "import tvm; print('\n'.join(f'{k}: {v}' for k, v in tvm.support.libinfo().items()))"`, applicable if you compile models):
 - Any other relevant information:

## Additional context

![image](https://github.com/mlc-ai/mlc-llm/assets/20659028/2d9e6115-5cbc-4b43-a575-e970206ebf8e)

![image](https://github.com/mlc-ai/mlc-llm/assets/20659028/a7757471-bf85-4f98-b198-bc18553d5bfa)

**Comment by junrushao** [comment]
Did you install rust and cargo?

**Comment by felixslu** [comment]
> Did you install rust and cargo?

Yes,I have  install rust and cargo , by commands below!

_mkdir -p build
bash scripts/prep_deps.sh
source "$HOME/.cargo/env"
python3 cmake/gen_cmake_config.py
cp config.cmake build
cd build
cmake ..
make_

**Comment by railgun-zyy** [comment]
> /prep_deps.sh
I coun't find it, please tell me how to solve.
