### ISSUE TITLE
[Model Request] Guanaco

### ISSUE THREAD

**Issue by rndompc** [mlc-ai/mlc-llm#336]
## ⚙️  Request New Models

- Link to an existing implementation (e.g. Hugging Face/Github):  https://huggingface.co/TheBloke/guanaco-33B-GGML
- Is this model architecture supported by MLC-LLM? (the list of [supported models](https://mlc.ai/mlc-llm/docs/model-prebuilts.html#off-the-shelf-models))  Yes

## Additional context

This model have shown good performance within the Llama model. I would like to test it in different hardware. I also would appreciate If you can give me some recommendations about how to compile for a GPU Target: gfx90a.

**Comment by Kathryn-cat** [comment]
Hi, you may refer to PR #497.
