### ISSUE TITLE
[Question] Is it compatible with flutter?

### ISSUE THREAD

**Issue by hj24** [mlc-ai/mlc-llm#344]
## ❓ General Questions

I want to try it to build an iOS App, but still in research phase. Not sure if it's compatiable with flutter.

**Comment by junrushao** [comment]
To interact with MLC-compiled LLMs on iOS, the only file you need is LLMChat.mm: https://github.com/mlc-ai/mlc-llm/blob/main/ios/MLCChat/LLMChat.mm. Not knowing much about flutter, but as long as it allows us to call those interfaces, it should be fine
