### ISSUE TITLE
[Feature Request] get only the last generated part of a message

### ISSUE THREAD

**Issue by tobrun** [mlc-ai/mlc-llm#348]
## 🚀 Feature

Allow to get only the new parts of a message

## Motivation

I'm trying to stream data and currently backend.getMessage returns the full message:

```
    fun getMessage(): String {
        assert(!Looper.getMainLooper().isCurrentThread)
        return get_message_!!.invoke().asString()
    }
```

**Comment by tqchen** [comment]
Feel free to refer to the CLI impl, we can have a diff message that allows you to get things as streamed. One catch is that as we partially decode the message can change
