### ISSUE TITLE
[Doc] broken link (points to 127.0.0.1)

### ISSUE THREAD

**Issue by deep-pipeline** [mlc-ai/mlc-llm#349]
### Bug (Broken link)
- Link to the buggy documentation/tutorial:  https://mlc.ai/mlc-llm/docs/tutorials/compile-models.html
- Description of the bug: in the section marked “Run Build Script” there is a sentence
For full explanation and usage of each argument, please check out the [API reference](http://127.0.0.1/). 

Unfortunately that link is broken and links to 127.0.0.1…

The API reference is obviously not going to the API reference (wherever it is) and needs to be adjusted. Using the search interface to the docs with “API reference” only yields the above broken link - so I don’t know what the correct one should be.

Please could we have the API reference page in the public site.

Many thanks.

**Comment by yzh119** [comment]
Hi @deep-pipeline , we have fixed the documentation that mentions API reference.

Actually, MLC-LLM itself haven't exposed any standard APIs yet (there will be soon!), so there is no API reference up to now.
