### ISSUE TITLE
for architecture arm64

### ISSUE THREAD

**Issue by Leoeeeeeeea** [mlc-ai/mlc-llm#352]
in /Users/leo/Desktop/mlc-llm-main/ios/build/lib/libmlc_llm.a(conv_templates.cc.o), building for iOS Simulator, but linking in object file built for iOS, file '/Users/leo/Desktop/mlc-llm-main/ios/build/lib/libmlc_llm.a' for architecture arm64

i just followed the instructions

how can i fix it？

**Comment by NullCodex** [comment]
@junrushao actually i am running into the same issue. I am following https://mlc.ai/mlc-llm/docs/deploy/ios.html in the last step https://mlc.ai/mlc-llm/docs/deploy/ios.html#id6 where it builds the iOS application I chose my own iPhone as the target and the build fails with the same error message `in /Users/leo/Desktop/mlc-llm-main/ios/build/lib/libmlc_llm.a(conv_templates.cc.o), building for iOS Simulator, but linking in object file built for iOS, file '/Users/leo/Desktop/mlc-llm-main/ios/build/lib/libmlc_llm.a' for architecture arm64`. 

It looks like the current steps do not work if you tried to build the target as your own iPhone?

**Comment by junrushao** [comment]
@NullCodex on the contrary, it works for a real iphone but doesn’t work with a simulator.

**Comment by NullCodex** [comment]
@junrushao you are right i had it set on the wrong device my bad.
