### ISSUE TITLE
build the "cpp" dir for android and how  to generate vicuna-v1-7b-q4f16_0-opencl.so file？

### ISSUE THREAD

**Issue by yuwenjun1988** [mlc-ai/mlc-llm#353]
./mlc_chat_cli --model vicuna-v1-7b
Use MLC config: "/data/local/tmp/build_arm/dist/vicuna-v1-7b-q4f16_0/params/mlc-chat-config.json"
Use model weights: "/data/local/tmp/build_arm/dist/vicuna-v1-7b-q4f16_0/params/ndarray-cache.json"
Cannot find library "vicuna-v1-7b-q4f16_0-opencl.so" in "dist"/prebuilt/lib or other search paths

**Comment by yzh119** [comment]
How did you compile the model? Building the cpp dir (it's used to build `mlc_chat_cli`) is not related to model compilation.

**Comment by yuwenjun1988** [comment]
use “python3 build.py --model /mnt/c/vicuna-v1-7b --quantization q4f16_0 --target android --max-seq-len 768” to build model

**Comment by yuwenjun1988** [comment]
--target opencl and can generate vicuna-v1-7b-q4f16_0-opencl.so file

**Comment by yuwenjun1988** [comment]
--target opencl and can generate vicuna-v1-7b-q4f16_0-opencl.so file is  EM_X86_64 ,how to generate vicuna-v1-7b-q4f16_0-opencl.so file is EM_AARCH64

**Comment by yuwenjun1988** [comment]
An error occurred during the execution of TVM.
For more information, please see: https://tvm.apache.org/docs/errors.html
---------------------------------------------------------------
  Check failed: (lib_handle_ != nullptr) is false: Failed to load dynamic shared library /data/local/tmp/build_arm/dist/vicuna-v1-7b-q4f16_0/vicuna-v1-7b-q4f16_0-opencl.so dlopen failed: "/data/local/t
mp/build_arm/dist/vicuna-v1-7b-q4f16_0/vicuna-v1-7b-q4f16_0-opencl.so" is for EM_X86_64 (62) instead of EM_AARCH64 (183)

**Comment by yuwenjun1988** [comment]
I have solved it

**Comment by chaitanyakrishna1248** [comment]
Hi, @yuwenjun1988 , may I know how solved the error? I am also building the opencl.so file
