### ISSUE TITLE
[Bug] Error when building app on android studio

### ISSUE THREAD

**Issue by Jiminator** [mlc-ai/mlc-llm#354]
## 🐛 Bug

I already verified I have installed the ndk, and have passed in its file path as environment variables like shown in the tutorial, and into local.properties. 
When I build the project, I get the error:
Execution failed for task ':app:buildJni'.
> A problem occurred starting process 'command 'ndk-build'
Cause: error=2, No such file or directory

## To Reproduce

1. Follow all steps in Android tutorial
2. Download ndk and put it in sdk
3. Build MLCChat on Android Studio 

## Expected behavior

No Error/app being successfully built

## Environment

 - Platform: Android
 - Operating system: MacOS
 - Device: LG G8 Thin
 - How you installed MLC-LLM: conda
 - How you installed TVM-Unity: source
 - Python version: python 3.11.3
 - GPU driver version (if applicable):
 - CUDA/cuDNN version (if applicable):
 - TVM Unity Hash Tag:
 - Any other relevant information: 

## Additional context

I tried changing ndk-build with its full file path. I get a slightly different error message
Update build.gradle (Module :app) line 36, replace "ndk-build" with "full-path-to-ndk/ndk-build"
Execution failed for task ':app:buildJni'.
> Process 'command '/Users/jimmy/Library/Android/sdk/ndk/25.2.9519653/ndk-build'' finished with non-zero exit value 2

**Comment by tobrun** [comment]
Fully agree with the assessment here, was hitting the same issue of ndk-build not found.

> Process 'command '/Users/jimmy/Library/Android/sdk/ndk/25.2.9519653/ndk-build'' finished with non-zero exit value 2

Would love to help you move forward with resolving this issue though, there should be more error logs, could you double check?

**Comment by Jiminator** [comment]
The full error log is pasted below:

Executing tasks: [:app:assembleDebug] in project /Users/jimmy/Desktop/Research/MIT_HAN_Lab/test/relax/jvm/mlc-llm/android/MLCChat

> Task :app:createDebugVariantModel UP-TO-DATE
> Task :app:preBuild UP-TO-DATE
> Task :app:preDebugBuild UP-TO-DATE
> Task :app:mergeDebugNativeDebugMetadata NO-SOURCE
> Task :app:generateJniHeaders
> Task :app:copyFiles UP-TO-DATE
> Task :app:deleteLibs UP-TO-DATE
> Task :app:buildJni FAILED
> Task :app:checkDebugAarMetadata UP-TO-DATE
> Task :app:generateDebugResValues UP-TO-DATE
> Task :app:mapDebugSourceSetPaths UP-TO-DATE
> Task :app:generateDebugResources UP-TO-DATE
> Task :app:mergeDebugResources UP-TO-DATE
> Task :app:packageDebugResources UP-TO-DATE
> Task :app:parseDebugLocalResources UP-TO-DATE
> Task :app:createDebugCompatibleScreenManifests UP-TO-DATE
> Task :app:extractDeepLinksDebug UP-TO-DATE
> Task :app:processDebugMainManifest UP-TO-DATE
> Task :app:processDebugManifest UP-TO-DATE
> Task :app:processDebugManifestForPackage UP-TO-DATE
> Task :app:processDebugResources UP-TO-DATE
> Task :app:compileDebugKotlin UP-TO-DATE
> Task :app:javaPreCompileDebug UP-TO-DATE
> Task :app:mergeDebugShaders UP-TO-DATE
> Task :app:compileDebugShaders NO-SOURCE
> Task :app:generateDebugAssets UP-TO-DATE
> Task :app:mergeDebugAssets UP-TO-DATE
> Task :app:compressDebugAssets UP-TO-DATE
> Task :app:processDebugJavaRes NO-SOURCE
> Task :app:mergeDebugJavaResource UP-TO-DATE
> Task :app:checkDebugDuplicateClasses UP-TO-DATE
> Task :app:desugarDebugFileDependencies UP-TO-DATE
> Task :app:mergeExtDexDebug UP-TO-DATE
> Task :app:mergeLibDexDebug UP-TO-DATE
> Task :app:mergeDebugJniLibFolders UP-TO-DATE
> Task :app:mergeDebugNativeLibs NO-SOURCE
> Task :app:stripDebugDebugSymbols NO-SOURCE
> Task :app:validateSigningDebug UP-TO-DATE
> Task :app:writeDebugAppMetadata UP-TO-DATE
> Task :app:writeDebugSigningConfigVersions UP-TO-DATE

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:buildJni'.
> A problem occurred starting process 'command 'ndk-build''

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 723ms
31 actionable tasks: 2 executed, 29 up-to-date

**Comment by tobrun** [comment]
There is a PR open that addressed this issue in https://github.com/mlc-ai/mlc-llm/pull/319

**Comment by Jiminator** [comment]
tysm for the help. Closing the issue.
