### ISSUE TITLE
[Question] Is Chatglm currently not supported?

### ISSUE THREAD

**Issue by wangxu569** [mlc-ai/mlc-llm#355]
## ❓ General Questions

AssertionError: Model type chatglm not supported.
free(): invalid pointer
Aborted (core dumped)

**Comment by yzh119** [comment]
Not yet, we will have tutorials on how to add new model architectures like GLM, and you are welcomed to contribute.

**Comment by shuyaoyimei** [comment]
I have read the PR of RWKV, which was developed by Siyuanfeng. Now, I will write an article to better understand the process of developing a new model, Hope to be of help to you and me.

**Comment by JianbangZ** [comment]
@yzh119 is there any update on Chatglm2 support? It's a fairly popular model now
