### ISSUE TITLE
Android support

### ISSUE THREAD

**Issue by Pandapip1** [mlc-ai/mlc-llm#36]
Pretty self-explanatory: can we get an Android version of this?

**Comment by durmazt** [comment]
upcoming [https://github.com/mlc-ai/mlc-llm/issues/15](see also)

**Comment by shiqimei** [comment]
duplicate of #4 , the team is working in progress for the android port.

**Comment by junrushao** [comment]
It’s up! https://twitter.com/bohanhou1998/status/1655772690760994818

**Comment by Pandapip1** [comment]
> duplicate of #4

Have no idea how I missed that. Closing.
