### ISSUE TITLE
ARM64 CPU on Linux

### ISSUE THREAD

**Issue by Crystalxd** [mlc-ai/mlc-llm#363]
Can mlc-llm precisely run arm64v8 CPU on Ubuntu? Not just on the Mac M series chip.

**Comment by Crystalxd** [comment]
**detail:** I can't install TVM by running `pip install -I mlc_ai_nightly -f https://mlc.ai/wheels` on my Ubuntu server, so I compile one by source code([https://github.com/apache/tvm](https://github.com/apache/tvm)), but when I run `python build.py --hf-path=databricks/dolly-v2-3b` I get an error about 'ImportError: cannot import name 'relax' from 'tvm''

**Comment by junrushao** [comment]
Seems that you are not using the correct TVM branch. Would you mind double checking: https://mlc.ai/mlc-llm/docs/install/tvm.html#id2

**Comment by Crystalxd** [comment]
Yes, it works for me according to the docs, thanks for much!
