### ISSUE TITLE
[Bug] Unsupported opcode, application dumps core

### ISSUE THREAD

**Issue by GTP95** [mlc-ai/mlc-llm#365]
## 🐛 Bug
Application dumps core in the moment I press return after typing a prompt, the full output is provided in the next section.

## To Reproduce

1. Follow the instructions [here](https://mlc.ai/mlc-llm/#windows-linux-mac) to install with Conda. Use the redpajama model
2. Start application
3. Type a prompt and hit return
Full output:

```
$ mlc_chat_cli --local-id RedPajama-INCITE-Chat-3B-v1-q4f16_0
WARNING: radv is not a conformant Vulkan implementation, testing use only.
Use MLC config: "/home/giacomo/git/mlc/dist/prebuilt/mlc-chat-RedPajama-INCITE-Chat-3B-v1-q4f16_0/mlc-chat-config.json"
Use model weights: "/home/giacomo/git/mlc/dist/prebuilt/mlc-chat-RedPajama-INCITE-Chat-3B-v1-q4f16_0/ndarray-cache.json"
Use model library: "/home/giacomo/git/mlc/dist/prebuilt/lib/RedPajama-INCITE-Chat-3B-v1-q4f16_0-vulkan.so"
You can use the following special commands:
  /help               print the special commands
  /exit               quit the cli
  /stats              print out the latest stats (token/sec)
  /reset              restart a fresh chat
  /reload [local_id]  reload model `local_id` from disk, or reload the current model if `local_id` is not specified

Loading model...
Loading finished
Running system prompts...
System prompts finished
<human>: Hi, how are you?
ACO ERROR:
    In file ../mesa-23.1.1/src/amd/compiler/aco_assembler.cpp:168
    Unsupported opcode:  v2b: %84:v[3][0:16] = v_add_f16 0xffffc700, %82:v[3][0:16]
Annullato (core dump creato)
```

## Expected behavior
The bot replies using the loaded model.

## Environment

 - Platform (e.g. WebGPU/Vulkan/IOS/Android/CUDA): Vulkan
 - Operating system (e.g. Ubuntu/Windows/MacOS/...): ArchLinux
 - Device (e.g. iPhone 12 Pro, PC+RTX 3090, ...) Laptop+AMD Radeon R5 M330
 - How you installed MLC-LLM (`conda`, source): conda
 - How you installed TVM-Unity (`pip`, source):
 - Python version (e.g. 3.10): 3.11.3
 - GPU driver version (if applicable): 23.1.1 (96473089)
 - CUDA/cuDNN version (if applicable):
 - TVM Unity Hash Tag (`python -c "import tvm; print('\n'.join(f'{k}: {v}' for k, v in tvm.support.libinfo().items()))"`, applicable if you compile models):
 - Any other relevant information:

**Comment by junrushao** [comment]
You might want to install a more proper Vulkan driver: https://mlc.ai/mlc-llm/docs/install/software-dependencies.html#valkan-driver-validate-installation

**Comment by GTP95** [comment]
Hello, the link you provided is broken. Can you please update it?

**Comment by junrushao** [comment]
@GTP95 how about this one: https://mlc.ai/mlc-llm/docs/install/gpu.html
