### ISSUE TITLE
[Doc] TVM_HOME env should be configured

### ISSUE THREAD

**Issue by islavutin** [mlc-ai/mlc-llm#366]
### Suggestion
TVM_HOME env variable should be configured, otherwise user will get the issue at cmake .. stage

https://github.com/mlc-ai/mlc-llm/blob/main/cpp/README.md

**Comment by yzh119** [comment]
Our documentation for building cpp is available at https://mlc.ai/mlc-llm/docs/tutorials/runtime/cpp.html.

These README files would be deprecated and linked to documentation.
