### ISSUE TITLE
Error:VK_ERROR_INCOMPATIBLE_DRIVER

### ISSUE THREAD

**Issue by Wings236** [mlc-ai/mlc-llm#37]
my environment is win10 WSL2 Ubuntu22.04, and I follow the command:
`conda create -n mlc-chat`
`conda activate mlc-chat`
`conda install git git-lfs`
`conda install -c mlc-ai -c conda-forge mlc-chat-nightly`
`mkdir -p dist`
`git lfs install`
`git clone https://huggingface.co/mlc-ai/demo-vicuna-v1-7b-int3 dist/vicuna-v1-7b`
`git clone https://github.com/mlc-ai/binary-mlc-llm-libs.git dist/lib`

However, when I complete this command:
`mlc_chat_cli`
error happen.
![image](https://user-images.githubusercontent.com/43870869/235589513-bef0424d-9f89-4f1d-86c5-0501a0f2ba85.png)

**Comment by logan-markewich** [comment]
I had the same error actually in wsl. I should try powershell next time

**Comment by junrushao** [comment]
WSL support for Vulkan is not there yet AFAIK, so please use CMD instead if you want to use Vulkan on Windows

**Comment by LiHao217** [comment]
I had the same error：
<img width="1445" alt="image" src="https://github.com/mlc-ai/mlc-llm/assets/26959371/5bc91ae0-a27f-49cd-8b99-f3830c7e6acf">

CentOS Linux release 8.0.1905 (Core)
4.18.0-348.7.1.el8_5.x86_64

**Comment by arif599** [comment]
> I had the same error： <img alt="image" width="1445" src="https://user-images.githubusercontent.com/26959371/265457455-5bc91ae0-a27f-49cd-8b99-f3830c7e6acf.png">
> 
> CentOS Linux release 8.0.1905 (Core) 4.18.0-348.7.1.el8_5.x86_64

Hey were you able to get it working?

**Comment by Espacio-root** [comment]
tvm.error.InternalError: Traceback (most recent call last):
  7: tvm::runtime::PackedFuncObj::Extractor<tvm::runtime::PackedFuncSubObj<__mk_TVM1::{lambda(tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*)#1}> >::Call(tvm::runtime::PackedFuncObj const*, __mk_TVM1, tvm::
runtime::TVMRetValue)
  6: tvm::runtime::DeviceAPIManager::GetAPI(int, bool)
  5: tvm::runtime::DeviceAPIManager::GetAPI(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool) [clone .isra.0]
  4: tvm::runtime::PackedFuncObj::Extractor<tvm::runtime::PackedFuncSubObj<tvm::runtime::vulkan::__mk_TVM0::{lambda(tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*)#1}> >::Call(tvm::runtime::PackedFuncObj co
nst*, tvm::runtime::vulkan::__mk_TVM0, tvm::runtime::TVMRetValue)
  3: tvm::runtime::vulkan::VulkanDeviceAPI::Global()
  2: tvm::runtime::vulkan::VulkanDeviceAPI::VulkanDeviceAPI()
  1: tvm::runtime::vulkan::VulkanInstance::VulkanInstance()
  0: _ZN3tvm7runtime6deta
  File "/workspace/tvm/src/runtime/vulkan/vulkan_instance.cc", line 111
InternalError: Check failed: (__e == VK_SUCCESS) is false: Vulkan Error, code=-9: VK_ERROR_INCOMPATIBLE_DRIVER


I'm getting the same error. How do I run this on arch?
