### ISSUE TITLE
It Just Seemingly Crashes....?

### ISSUE THREAD

**Issue by RiyanParvez** [mlc-ai/mlc-llm#374]
## 🐛 Bug

When ever i run it using mlc_chat_cli --local-id vicuna-v1-7b-q3f16_0, it just stops loading the model into memory with this error : 
[12:31:23] C:\Miniconda\envs\mlc-llm-build\conda-bld\mlc-chat-nightly-package_1686373785773\work\3rdparty\tvm\src\runtime\vulkan\vulkan_buffer.cc:61:
---------------------------------------------------------------
An error occurred during the execution of TVM.
For more information, please see: https://tvm.apache.org/docs/errors.html
---------------------------------------------------------------
  Check failed: (__e == VK_SUCCESS) is false: Vulkan Error, code=-2: VK_ERROR_OUT_OF_DEVICE_MEMORY
Stack trace not available when DMLC_LOG_STACK_TRACE is disabled at compile time.

Well It Says Out Of Device Memory, but i took a look at the vram usage and it never uses it all it goes near 2.9 then this error occurs, and i am using the integrated gpu for rendering normal stuff, so its not that either.

![image](https://github.com/mlc-ai/mlc-llm/assets/127128626/71b5722a-fff4-4ee6-8901-14b10e30e8de)

## To Reproduce

1.mlc_chat_cli --local-id vicuna-v1-7b-q3f16_0

## Environment

 - Platform (e.g. Vulkan):
 - Operating system (Windows 11): 
 - Device (GTX 1650)
 - How you installed MLC-LLM (`conda`, source): YEs
 - How you installed TVM-Unity (`pip`, source):....I dont think so
 - CUDA/cuDNN version (12.1):
 - Any other relevant information:

**Comment by yzh119** [comment]
Vulkan driver is not installed.

**Comment by Hzfengsy** [comment]
Please try RedPajama-INCITE-Chat-3B-v1, which is more friendly to 4G VRAM

**Comment by junrushao** [comment]
4G VRAM is not enough for Vicuna-7b.
