### ISSUE TITLE
[Bug] build mlc-chat failed with cpp

### ISSUE THREAD

**Issue by SeekPoint** [mlc-ai/mlc-llm#380]
(mlc-chat-venv) amd00@asus00:~/llm_dev/mlc-llm$ rm -rf build
(mlc-chat-venv) amd00@asus00:~/llm_dev/mlc-llm$ mkdir -p build && cd build
(mlc-chat-venv) amd00@asus00:~/llm_dev/mlc-llm/build$ python3 ../cmake/gen_cmake_config.py
Use CUDA? (y/n): y
Use Vulkan? (y/n): n
Use Metal (Apple M1/M2 GPU) ? (y/n): n
set(CMAKE_BUILD_TYPE RelWithDebInfo)
set(USE_CUDA ON)
set(USE_VULKAN OFF)
set(USE_METAL OFF)

Writing configuration to config.cmake...
(mlc-chat-venv) amd00@asus00:~/llm_dev/mlc-llm/build$
(mlc-chat-venv) amd00@asus00:~/llm_dev/mlc-llm/build$
(mlc-chat-venv) amd00@asus00:~/llm_dev/mlc-llm/build$
(mlc-chat-venv) amd00@asus00:~/llm_dev/mlc-llm/build$ cmake .. && cmake --build . --parallel $(nproc) && cd ..
-- The C compiler identification is GNU 9.4.0
-- The CXX compiler identification is GNU 9.4.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Performing Test SUPPORT_CXX17
-- Performing Test SUPPORT_CXX17 - Success
-- Forbidding undefined symbols in shared library, using -Wl,--no-undefined on platform Linux
-- Didn't find the path to CCACHE, disabling ccache
-- VTA build with VTA_HW_PATH=/home/amd00/llm_dev/mlc-llm/3rdparty/tvm/3rdparty/vta-hw
-- Build VTA runtime with target: sim
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE
-- Found CUDA_TOOLKIT_ROOT_DIR=/usr/local/cuda
-- Found CUDA_CUDA_LIBRARY=/usr/local/cuda/targets/x86_64-linux/lib/stubs/libcuda.so
-- Found CUDA_CUDART_LIBRARY=/usr/local/cuda/lib64/libcudart.so
-- Found CUDA_NVRTC_LIBRARY=/usr/local/cuda/lib64/libnvrtc.so
-- Found CUDA_CUDNN_INCLUDE_DIRS=
-- Found CUDA_CUDNN_LIBRARY=
-- Found CUDA_CUBLAS_LIBRARY=/usr/local/cuda/lib64/libcublas.so
-- Found CUDA_CURAND_LIBRARY=/usr/local/cuda/lib64/libcurand.so
-- Found CUDA_CUBLASLT_LIBRARY=/usr/local/cuda/lib64/libcublasLt.so
-- Build with CUDA 11.7 support
-- Build with contrib.random
-- Build with contrib.sort
-- Build with contrib.hybriddump
-- Git found: /usr/bin/git
-- Found TVM_GIT_COMMIT_HASH=6fd55bcfecc7abcc707339d7a8ba493f0048b613
-- Found TVM_GIT_COMMIT_TIME=2023-06-05 12:18:09 -0700
-- Building with TVM Map...
-- Build with thread support...
-- Check if compiler accepts -pthread
-- Check if compiler accepts -pthread - yes
-- Performing Test FILE_PREFIX_MAP_SUPPORTED
-- Performing Test FILE_PREFIX_MAP_SUPPORTED - Success
-- system-nameLinux
-- VERSION: 0.2.00
-- Configuring done (0.8s)
-- Generating done (0.1s)
-- Build files have been written to: /home/amd00/llm_dev/mlc-llm/build
[  0%] Building CXX object CMakeFiles/mlc_llm_objs.dir/cpp/conv_templates.cc.o
[  0%] Building CXX object CMakeFiles/mlc_llm_objs.dir/cpp/conversation.cc.o
[  0%] Building CXX object CMakeFiles/mlc_llm_objs.dir/cpp/llm_chat.cc.o
[  0%] Building CXX object CMakeFiles/mlc_cli_objs.dir/cpp/cli_main.cc.o
[  0%] Generating release/libtokenizers_c.a
[  0%] Building CXX object tokenizers/CMakeFiles/tokenizer_cpp_objs.dir/src/sentencepiece_tokenizer.cc.o
[  0%] Building CXX object tvm/CMakeFiles/tvm_libinfo_objs.dir/src/support/libinfo.cc.o
[  0%] Building CXX object tokenizers/CMakeFiles/tokenizer_cpp_objs.dir/src/huggingface_tokenizer.cc.o
[  9%] Building CXX object tokenizers/sentencepiece/src/CMakeFiles/sentencepiece-static.dir/__/third_party/protobuf-lite/bytestream.cc.o
[  9%] Building CXX object tvm/CMakeFiles/tvm_runtime_objs.dir/src/runtime/c_runtime_api.cc.o
[  9%] Building CXX object tvm/CMakeFiles/tvm_runtime_objs.dir/src/runtime/builtin_fp16.cc.o
[  9%] Building CXX object tokenizers/sentencepiece/src/CMakeFiles/sentencepiece-static.dir/__/third_party/protobuf-lite/coded_stream.cc.o
[  9%] Building CXX object tvm/CMakeFiles/tvm_runtime_objs.dir/src/runtime/const_loader_module.cc.o
[  9%] Building CXX object tokenizers/sentencepiece/src/CMakeFiles/sentencepiece-static.dir/__/third_party/protobuf-lite/arena.cc.o
[  9%] Building CXX object tokenizers/sentencepiece/src/CMakeFiles/sentencepiece-static.dir/__/third_party/protobuf-lite/common.cc.o
[  9%] Building CXX object tokenizers/sentencepiece/src/CMakeFiles/sentencepiece-static.dir/__/third_party/protobuf-lite/arenastring.cc.o
No such file or directory
make[2]: *** [tokenizers/CMakeFiles/tokenizers_c.dir/build.make:71: tokenizers/release/libtokenizers_c.a] Error 1
make[1]: *** [CMakeFiles/Makefile2:553: tokenizers/CMakeFiles/tokenizers_c.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[  9%] Building CXX object tvm/CMakeFiles/tvm_runtime_objs.dir/src/runtime/container.cc.o
[  9%] Building CXX object tvm/CMakeFiles/tvm_runtime_objs.dir/src/runtime/cpu_device_api.cc.o
[  9%] Building CXX object tvm/CMakeFiles/tvm_runtime_objs.dir/src/runtime/debug.cc.o
[  9%] Built target tokenizer_cpp_objs

**Comment by Hzfengsy** [comment]
Please try to update git submodule by `git submodule update --init --recursive`

**Comment by Crystalxd** [comment]
> Please try to update git submodule by `git submodule update --init --recursive`

I tried it and not work yet. Is not this a bug?

**Comment by Crystalxd** [comment]
#335 I solved it by this.
