### ISSUE TITLE
[Question] Can i use customized transformer llm model?

### ISSUE THREAD

**Issue by chensinit** [mlc-ai/mlc-llm#386]
## ❓ General Questions

Hello.
We have a LLM model. and we want to use mlc-llm solution.
Our model is trasformer base and we customize structure.
Can we use your solution?

And we build model by pitorch. so file name is model.pt
Should we convert it?

**Comment by chensinit** [comment]
Could you give me link?

**Comment by Kathryn-cat** [comment]
Please refer to this link: https://github.com/mlc-ai/notebooks/blob/main/tutorial/How_to_add_model_architeture_in_MLC_LLM.ipynb.
