### ISSUE TITLE
[Bug]  Added models don't work?

### ISSUE THREAD

**Issue by GameOverFlowChart** [mlc-ai/mlc-llm#389]
I can run the build in models after downloading them (vicuna-v1-7b-q4f16_0 and RedPajama-INCITE-Chat-3B-v1-q4f16_0). 

But I can't run vicuna-v1-7b-q3f16_0 after successfully downloading it which should be less demanding than the q4 variant. The initializing process never ends while it just takes some seconds for the q4 variant.
I also can't run the 1b rwkv model but I'm not sure how heavy it is since it's a q8 model.

Since a weaker model doesn't get initialized while the heavier version does get initialized I don't think that this has to do with hardware limitations. Is there some other difference between the 2 default models and the ones which can be added manually with the URL?

System:
Android 13
Snapdragon 888
12GB RAM

**Comment by cyx-6** [comment]
Thanks for reporting! It seems like an issue about the backend, rather than the frontend UX issue. @spectrometerHBH do you have time to take a look?

**Comment by namchuai** [comment]
I'm also having this problem. Vicuna just stuck at Initialization.
Samsung S23 Ultra 8GB ram
Snapdragon 8 Gen 2

**Comment by Mgz-97** [comment]
@GameOverFlowChart which raw model link( in the preparelib.sh period) you used for vicuna-7b?

**Comment by GameOverFlowChart** [comment]
> @GameOverFlowChart which raw model link( in the preparelib.sh period) you used for vicuna-7b?

I didn't build anything myself if you are asking this (because you mentioned a shell script which I don't know, I'm on Android not on a Linux Desktop).

I used the precompiled apk. The models I used...
well again all the ones which come included in the apk are working. And none of those I added worked. To focus on the q3 one, this is one of the models I tested which didn't work:
https://huggingface.co/mlc-ai/mlc-chat-vicuna-v1-7b-q3f16_0/resolve/main/

**Comment by GameOverFlowChart** [comment]
> thanks for reply, so you just use the apk mlc-llm provided, not build it from source?

That's right.

**Comment by gvJaime** [comment]
For me it does not even get to download the model. It fails with a EACCESS error when trying to store the model into a folder inside `/storage/emulated/0/Downloads`.

The app does not ask for storage permissions, however, you can grant them from settings after they've been denied.

It does not solve the issue.

The hardware is:
BQ Aquaris X2
3GB RAM
API level 29

I know the ram is hilariously low, but i was trying to check if the latest MLC build can execute rwkv-raven-1B5 on really low-spec hardware.

**Comment by GameOverFlowChart** [comment]
> For me it does not even get to download the model. It fails with a EACCESS error when trying to store the model into a folder inside `/storage/emulated/0/Downloads`, as i can see from the error pop-up.
> 
> The app does not ask for storage permissions, however, you can grant them from settings after they've been denied.
> 
> It does not solve the issue.
> 
> The hardware is: BQ Aquaris X2 3GB RAM API level 29
> 
> I know the ram is hilariously low, but i was trying to check if the latest MLC build can execute rwkv-raven-1B5 on really low-spec hardware.

I can definitively download models so it would probably make sense to open a separate issue for that.

**Comment by GameOverFlowChart** [comment]
@cyx-6 since spectrometerHBH had no time to give an answer. I tried to do research. Might it be that not all of the prebuild models are meant to be run Android? I was assuming that all mlc models can run on every mlc application independently from the operating system as long as the hardware is powerful enough. 

This documentation page:
https://mlc.ai/mlc-llm/docs/prebuilt_models.html#prebuilt-models-for-android
Make me think that it's different.

Also maybe my problem is related to #571 and maybe https://github.com/mlc-ai/mlc-llm/issues/571#issuecomment-1642398399
is a way to fix my problem but that's out of my scope of understanding.

In this case we need more prebuild models for Android (I could open a new request for that).

**Comment by GameOverFlowChart** [comment]
This issue can be closed. I know now that the problem was the missing model libs in the apk. In future it would be better to separate model libs from the apk, but that's it's own issue.
