### ISSUE TITLE
huggingface.co: no such host

### ISSUE THREAD

**Issue by durmazt** [mlc-ai/mlc-llm#39]
I have this error when I ` git clone https://huggingface.co/mlc-ai/demo-vicuna-v1-7b-int3 dist/vicuna-v1-7b`
> Error downloading object: float16/params_shard_1.bin (0fb70c2): Smudge error: Error downloading float16/params_shard_1.bin (0fb70c297b47ce4ecade5f7875c4c90f518069bab49f359a1644766b2279e8e2): batch response: Post "https://huggingface.co/mlc-ai/demo-vicuna-v1-7b-int3.git/info/lfs/objects/batch": dial tcp: lookup huggingface.co: no such host

**Comment by durmazt** [comment]
You're right, problem is my network connection.

**Comment by biubiu3721** [comment]
I faced with the same problem, but my netowork is fine. I can access google .
