### ISSUE TITLE
raise "TVMError: LLVM module verification failed" when build from source-code[Bug] 

### ISSUE THREAD

**Issue by zhangxiao-stack** [mlc-ai/mlc-llm#396]
## To Reproduce

1、download relax, follow the instructions to build the source code（set USE_ROCM, USE_ROCBLAS, USE_LLVM ON)） and export TVM_HOME and PYTHONPATH
download mlc-llm from github. python3 ./build.py --df-path=databricks/dolly-v2-3b --target cuda ... , raise "
can fluently build mlc-llm source code following the instruction(mkdir build && cd build; cmake .. && make)

## Environment

 - Platform (e.g. WebGPU/Vulkan/IOS/Android/CUDA):
 - Operating system (e.g. Ubuntu/Windows/MacOS/...):
 - Device (e.g. iPhone 12 Pro, PC+RTX 3090, ...)
 - How you installed MLC-LLM (`conda`, source):
 - How you installed TVM-Unity (`pip`, source):
 - Python version (e.g. 3.10):
 - GPU driver version (if applicable):
 - CUDA/cuDNN version (if applicable):
 - TVM Unity Hash Tag (`python -c "import tvm; print('\n'.join(f'{k}: {v}' for k, v in tvm.support.libinfo().items()))"`, applicable if you compile models):
 - Any other relevant information:

**Comment by zhangxiao-stack** [comment]
# To Reproduce
Steps to reproduce the behavior:
1、download relax, follow the instructions to build the source code（set USE_ROCM, USE_ROCBLAS, USE_LLVM ON)） and export TVM_HOME and PYTHONPATH
download mlc-llm from github. python3 ./build.py --df-path=databricks/dolly-v2-3b --target rocm , 
raise "TVMError: LLVM module verification failed with the following errors: 
Calling convention requires void return type
ptr @encode1_kernel
Function return type does not match operand type of return inst!
  ret void
can fluently build mlc-llm source code following the instruction(mkdir build && cd build; cmake .. && make)


# Environment
Python:3.8.12
OS:Centos
LLVM:15.0.7

python -c "import tvm; print('\n'.join(f'{k}: {v}' for k, v in tvm.support.libinfo().items()))"
USE_GTEST: AUTO
SUMMARIZE: OFF
USE_IOS_RPC: OFF
CUDA_VERSION: NOT-FOUND
USE_LIBBACKTRACE: AUTO
DLPACK_PATH: 3rdparty/dlpack/include
USE_TENSORRT_CODEGEN: OFF
USE_THRUST: OFF
USE_TARGET_ONNX: ON
USE_AOT_EXECUTOR: ON
BUILD_DUMMY_LIBTVM: OFF
USE_CUDNN: OFF
USE_TENSORRT_RUNTIME: OFF
USE_ARM_COMPUTE_LIB_GRAPH_EXECUTOR: OFF
USE_CCACHE: AUTO
USE_ARM_COMPUTE_LIB: OFF
USE_CPP_RTVM: OFF
USE_OPENCL_GTEST: /path/to/opencl/gtest
USE_MKL: OFF
USE_PT_TVMDSOOP: OFF
USE_CLML: OFF
USE_STACKVM_RUNTIME: OFF
USE_GRAPH_EXECUTOR_CUDA_GRAPH: OFF
ROCM_PATH: /opt/rocm
USE_DNNL: OFF
USE_VITIS_AI: OFF
USE_LLVM: /llvm_install/bin/llvm-config
USE_VERILATOR: OFF
USE_TF_TVMDSOOP: OFF
USE_THREADS: ON
USE_MSVC_MT: OFF
BACKTRACE_ON_SEGFAULT: OFF
USE_GRAPH_EXECUTOR: ON
USE_ROCBLAS: ON
GIT_COMMIT_HASH: 6fd55bcfecc7abcc707339d7a8ba493f0048b613
USE_VULKAN: OFF
USE_RUST_EXT: OFF
USE_CUTLASS: OFF
USE_CPP_RPC: OFF
USE_HEXAGON: OFF
USE_CUSTOM_LOGGING: OFF
USE_UMA: OFF
USE_FALLBACK_STL_MAP: OFF
USE_SORT: ON
USE_RTTI: ON
GIT_COMMIT_TIME: 2023-06-05 12:18:09 -0700
USE_HEXAGON_SDK: /path/to/sdk
USE_BLAS: none
USE_ETHOSN: OFF
USE_LIBTORCH: OFF
USE_RANDOM: ON
USE_CUDA: OFF
USE_COREML: OFF
USE_AMX: OFF
BUILD_STATIC_RUNTIME: OFF
USE_CMSISNN: OFF
USE_KHRONOS_SPIRV: OFF
USE_CLML_GRAPH_EXECUTOR: OFF
USE_TFLITE: OFF
USE_HEXAGON_GTEST: /path/to/hexagon/gtest
PICOJSON_PATH: 3rdparty/picojson
USE_OPENCL_ENABLE_HOST_PTR: OFF
INSTALL_DEV: OFF
USE_PROFILER: ON
USE_NNPACK: OFF
LLVM_VERSION: 15.0.7_AOMP_
USE_OPENCL: OFF
COMPILER_RT_PATH: 3rdparty/compiler-rt
RANG_PATH: 3rdparty/rang/include
USE_SPIRV_KHR_INTEGER_DOT_PRODUCT: OFF
USE_OPENMP: none
USE_BNNS: OFF
USE_CUBLAS: OFF
USE_METAL: OFF
USE_MICRO_STANDALONE_RUNTIME: OFF
USE_HEXAGON_EXTERNAL_LIBS: OFF
USE_ALTERNATIVE_LINKER: OFF
USE_BYODT_POSIT: OFF
USE_HEXAGON_RPC: OFF
USE_MICRO: OFF
DMLC_PATH: 3rdparty/dmlc-core/include
INDEX_DEFAULT_I64: ON
USE_RELAY_DEBUG: OFF
USE_RPC: ON
USE_TENSORFLOW_PATH: none
TVM_CLML_VERSION: 
USE_MIOPEN: ON
USE_ROCM: /opt/dtk-22.10
USE_PAPI: OFF
USE_CURAND: OFF
TVM_CXX_COMPILER_PATH: /opt/rh/devtoolset-7/root/usr/bin/c++
HIDE_PRIVATE_SYMBOLS: OFF

**Comment by junrushao** [comment]
Sorry I couldn't help with such limited information without any detailed error messages, but according to the command your provided, please:
- install TVM properly: https://mlc.ai/mlc-llm/docs/install/tvm.html
- use `vulkan` as the target

**Comment by zhangxiao-stack** [comment]
Does mlc-llm support amdgpu using ROCM instead Vulkan??

## Environment

 - Platform (e.g. WebGPU/Vulkan/IOS/Android/CUDA): ROCM
 - Operating system (e.g. Ubuntu/Windows/MacOS/...): Centos
 - Device (e.g. iPhone 12 Pro, PC+RTX 3090, ...) :AMDGPU
 - How you installed MLC-LLM (`conda`, source):source
 - How you installed TVM-Unity (`pip`, source):source  set USE_ROCM ON, USE_ROCBLAS ON, USE_LLVM ON)
 - Python version (e.g. 3.10): python 3.8.12
 - GPU driver version (if applicable): ROCM 
 - Any other relevant information:
 - LLVM:15.0.7
 -Install Instructions:
git clone https://github.com/mlc-ai/relax.git --recursive
edit config.cmake 
USE_ROCM ON, USE_ROCBLAS ON, USE_LLVM ON
cmake ..
make -j32

**Comment by zhangxiao-stack** [comment]
Does mlc-llm support amdgpu using ROCM instead Vulkan??

## Environment

 - Platform (e.g. WebGPU/Vulkan/IOS/Android/CUDA): ROCM
 - Operating system (e.g. Ubuntu/Windows/MacOS/...): Centos
 - Device (e.g. iPhone 12 Pro, PC+RTX 3090, ...) :AMDGPU
 - How you installed MLC-LLM (`conda`, source):source
 - How you installed TVM-Unity (`pip`, source):source  set USE_ROCM ON, USE_ROCBLAS ON, USE_LLVM ON)
 - Python version (e.g. 3.10): python 3.8.12
 - GPU driver version (if applicable): ROCM 
 - Any other relevant information:
 - LLVM:15.0.7
 -Install Instructions:
git clone https://github.com/mlc-ai/relax.git --recursive
edit config.cmake 
USE_ROCM ON, USE_ROCBLAS ON, USE_LLVM ON
cmake ..
make -j32
