### ISSUE TITLE
[Bug] TVM runtime cannot find vm_load_executable for vicuna-7b

### ISSUE THREAD

**Issue by Mgz-97** [mlc-ai/mlc-llm#401]
## 🐛 Bug

TVMError: 
---------------------------------------------------------------
An error occurred during the execution of TVM.
For more information, please see: https://tvm.apache.org/docs/errors.html
---------------------------------------------------------------
  Check failed: (fload_exec.defined()) is false: TVM runtime cannot find vm_load_executable
Stack trace:
  File "/home/*/MLC_NEW/tvm-unity/jvm/mlc-llm/cpp/llm_chat.cc", line 246
## To Reproduce

1.we use this https://huggingface.co/TheBloke/vicuna-7B-1.1-HF to prepare the lib for vicuna
2. and will get the error info as shown above.

## Environment

 - Platform (Android):
 - Operating system (Ubuntu:
 - Device (Samsung s23 ...)
 - How you installed MLC-LLM (source):
 - How you installed TVM-Unity (source):
 - Python version (3.9):
 - TVM Unity Hash Tag (`python -c "import tvm; print('\n'.join(f'{k}: {v}' for k, v in tvm.support.libinfo().items()))"`, applicable if you compile models):
 - Any other relevant information:

**Comment by junrushao** [comment]
Please check your TVM installation. I don't think you are using TVM Unity. https://mlc.ai/mlc-llm/docs/install/tvm.html

**Comment by Mgz-97** [comment]
I did follow the [Option 2. Build from Source](https://mlc.ai/mlc-llm/docs/install/tvm.html#id7)[¶](https://mlc.ai/mlc-llm/docs/install/tvm.html#option-2-build-from-source), and successfully verify it with the script [Validate Installation](https://mlc.ai/mlc-llm/docs/install/tvm.html#id8)[¶](https://mlc.ai/mlc-llm/docs/install/tvm.html#validate-installation)..So use the https://huggingface.co/TheBloke/vicuna-7B-1.1-HF is okay?

**Comment by junrushao** [comment]
To be clear, `vm_load_executable` is defined on this line in TVM: https://github.com/mlc-ai/relax/blob/1b87dce4aee9f82d657808e9b244e335fd3cb8f0/src/runtime/relax_vm/executable.cc#L63

It means if you are using a correct TVM distribution, you will find this method properly. Therefore, it's not about any particular model. Please do check again if there are multiple different TVM distros you have installed in your system 🙂

**Comment by Mgz-97** [comment]
### (tvm-build-venv) owen@owen-HP-Z4-G4-Workstation:~/MLC_NEW/tvm-unity/build$ git log
commit **bd5ee5888f4e**7e1e9f14ffcbc335186efb21880f (HEAD -> mlc, origin/mlc, origin/HEAD)
Author: tqchen <tianqi.tchen@gmail.com>
Date:   Mon Jun 12 22:23:11 2023 -0400

    [CherryPick][ARITH] Improve arith simplify to handle symbolic reshape pattern
    
    This PR enhances arith simplify to handle symbolic reshape patterns.
    Lift the CombineIters to callers of TryFuseIters so they can be used
    in early return simplifications. Testcases are added.
    
    Also updates a minor spelling issue in the testcase.
    
### (tvm-build-venv) owen@owen-HP-Z4-G4-Workstation:~/MLC_NEW/tvm-unity/build$ python -c "import tvm; print(tvm._ffi.base._LIB)"
<CDLL '/home/owen/anaconda3/envs/tvm-build-venv/lib/python3.9/site-packages/tvm-0.12.dev1094+g**bd5ee5888**-py3.9-linux-x86_64.egg/tvm/libtvm.so', handle 5609a1d288a0 at 0x7f7ee0b1fbb0>

### (base) owen@owen-HP-Z4-G4-Workstation:~$ python -c "import tvm; print(tvm._ffi.base._LIB)"

Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'tvm'
(base) owen@owen-HP-Z4-G4-Workstation:~$ 


thanks for explanation, and i confirm that i use the lastest tvm distros in my tvm-build-venv? but i am not sure the android build use the tvm version.. how to verify the andoird build use the right version tvm...
