### ISSUE TITLE
[Bug] Android app is not work.

### ISSUE THREAD

**Issue by chensinit** [mlc-ai/mlc-llm#404]
## 🐛 Bug

Android app is not work.
When i open android app, It appear system msg for prepare.
I'm wait long time.  But There is nothing to happen.
I try to several device. but it work same. (galaxy fold4, s22)
![Screenshot_20230614_093134_MLCChat](https://github.com/mlc-ai/mlc-llm/assets/28124957/f4253deb-1a5d-49e6-b748-55c519259765)

## To Reproduce

1. download app from mlc-llm web site.
2. install apk.
3. open app.

1. download app from mlc-llm web site.
2. install apk.
3. Push custom model.
4. open app.

## Environment

 - Platform (e.g. WebGPU/Vulkan/IOS/Android/CUDA):
 - Operating system (e.g. Ubuntu/Windows/MacOS/...):
 - Device (e.g. iPhone 12 Pro, PC+RTX 3090, ...)
 - How you installed MLC-LLM (`conda`, source):
 - How you installed TVM-Unity (`pip`, source):
 - Python version (e.g. 3.10):
 - GPU driver version (if applicable):
 - CUDA/cuDNN version (if applicable):
 - TVM Unity Hash Tag (`python -c "import tvm; print('\n'.join(f'{k}: {v}' for k, v in tvm.support.libinfo().items()))"`, applicable if you compile models):
 - Any other relevant information:

**Comment by spectrometerHBH** [comment]
There's a new version of APK here: https://github.com/mlc-ai/binary-mlc-llm-libs/blob/main/mlc-chat.apk.

Would you mind trying out the new app? Be sure to clear the storage of the old app and uninstall it.

**Comment by GameOverFlowChart** [comment]
> > It seems you are using the old release of app.
> > There's a new version of APK here: https://github.com/mlc-ai/binary-mlc-llm-libs/blob/main/mlc-chat.apk.
> > Would you mind trying out the new app? Be sure to clear the storage of the old app and uninstall it.
> 
> Thank you. I installed new apk. New App demand model url. and I input huggingface link. but it's not work. What should i do for it?

Hello, I think you have the same problem which I had #369

Did you update the app? You shouldn't. You must uninstall the old one first and install the new version. Than you should have 2 models in the list which you can download. (Maybe #369 shouldn't be closed before ensuring that this can't happen in future?)

If you still want to download another model, you can use links in this format (this doesn't work until you do the reinstall):
https://huggingface.co/mlc-ai/mlc-chat-vicuna-v1-7b-q3f16_0/resolve/main/

But even though the download works, running them doesn't work for me #389 so it would be interesting to hear from you if you also have that problem.

**Comment by chensinit** [comment]
> > > It seems you are using the old release of app.
> > > There's a new version of APK here: https://github.com/mlc-ai/binary-mlc-llm-libs/blob/main/mlc-chat.apk.
> > > Would you mind trying out the new app? Be sure to clear the storage of the old app and uninstall it.
> > 
> > 
> > Thank you. I installed new apk. New App demand model url. and I input huggingface link. but it's not work. What should i do for it?
> 
> Hello, I think you have the same problem which I had #369
> 
> Did you update the app? You shouldn't. You must uninstall the old one first and install the new version. Than you should have 2 models in the list which you can download. (Maybe #369 shouldn't be closed before ensuring that this can't happen in future?)
> 
> If you still want to download another model, you can use links in this format (this doesn't work until you do the reinstall): https://huggingface.co/mlc-ai/mlc-chat-vicuna-v1-7b-q3f16_0/resolve/main/
> 
> But even though the download works, running them doesn't work for me #389 so it would be interesting to hear from you if you also have that problem. But the 2 build in ones do work.

Thank you.
It's very helpful for me. : )
I will check your issue and try it.
Have a nice day~

**Comment by cyx-6** [comment]
@chensinit Sorry for replying late. Please try new [apk](https://github.com/mlc-ai/binary-mlc-llm-libs/blob/main/mlc-chat.apk).
