### ISSUE TITLE
[Question] Does mlc-llm support amdgpu using ROCM instead Vulkan ? 

### ISSUE THREAD

**Issue by zhangxiao-stack** [mlc-ai/mlc-llm#405]
I notice that mlc-llm has supported amdgpu by Vulkan. Does mlc-llm support amdgpu using ROCM instead Vulkan?

**Comment by zhangxiao-stack** [comment]
I notice that mlc-llm has supported amdgpu by Vulkan. Does mlc-llm support amdgpu using ROCM instead Vulkan?

**Comment by junrushao** [comment]
Currently by default, AMD GPU is supported via Vulkan, because it is more stable and generic. TVM has decent ROCm support, but we didn't have bandwidth to validate it in this project yet.
