### ISSUE TITLE
[Question] 

### ISSUE THREAD

**Issue by 18140663659** [mlc-ai/mlc-llm#406]
## ❓ General Questions

I use this Cmake version, but have the same question as #398 
cmake version 3.27.0-rc2

**Comment by junrushao** [comment]
```
Feature 'WHOLE_ARCHIVE',..., is not supported for the 'CXX' link language
```

Could you check your C++ compiler?

**Comment by 18140663659** [comment]
> ```
> Feature 'WHOLE_ARCHIVE',..., is not supported for the 'CXX' link language
> ```
> 
> 
>      
>   
> 
> Could you check your C++ compiler?

I  use 3.25 can solve this problem

**Comment by 18140663659** [comment]
but the document link in android/ , can not be visited

**Comment by junrushao** [comment]
You mean the link to the document doesn't work? I just checked but it works on my end: https://mlc.ai/mlc-llm/docs/tutorials/runtime/android.html

**Comment by 18140663659** [comment]
> You mean the link to the document doesn't work? I just checked but it works on my end: https://mlc.ai/mlc-llm/docs/tutorials/runtime/android.html

I can not visit this link, Is there any other address that can be accessed

**Comment by junrushao** [comment]
This page is hosted by github, so theoretically you can access the page if you have access to github, but I really don’t know if there are other network issues. The page is built from this RST file if you’d love to read without building it locally: https://github.com/mlc-ai/mlc-llm/blob/main/docs/tutorials/runtime/android.rst

**Comment by 18140663659** [comment]
> This page is hosted by github, so theoretically you can access the page if you have access to github, but I really don’t know if there are other network issues. The page is built from this RST file if you’d love to read without building it locally: https://github.com/mlc-ai/mlc-llm/blob/main/docs/tutorials/runtime/android.rst

thank you , this helps me. maybe other network issues influence.
