### ISSUE TITLE
very slow in Mac

### ISSUE THREAD

**Issue by paulk8s** [mlc-ai/mlc-llm#41]
Tried on a Mac with the below capacity and the response is very slow. Is there any way to speed it up?

Spec:
2.6 GHz 6-Core Intel Core i7
Intel UHD Graphics 630 1536 MB
32 GB 2667 MHz DDR4

**Comment by christopherpickering** [comment]
I have the same mac, and also slow. It prompts fairly quickly, but the text prints back out very slowly.

**Comment by Hzfengsy** [comment]
We use GPUs (also Integrated GPUs) to run models. As `Intel UHD Graphics 630` is too weak, we can do nothing to break the hardware limitations

**Comment by FreeBlues** [comment]
> Tried on a Mac with the below capacity and the response is very slow. Is there any way to speed it up?
> 
> Spec: 2.6 GHz 6-Core Intel Core i7 Intel UHD Graphics [630 1536](tel:630 1536) MB 32 GB 2667 MHz DDR4

You can try to add an eGPU for mac

**Comment by junrushao** [comment]
Macbooks ship with M1/M2 GPUs are quite capable of running those LLM workloads, but indeed Intel integrated ones with previous macbooks are far behind
