### ISSUE TITLE
TVM runtime cannot find vm_load_executable[Bug] 

### ISSUE THREAD

**Issue by yongbing** [mlc-ai/mlc-llm#411]
## To Reproduce
mac pro： intel i7, os-Ventura 13.4

1. build relax, set USE_LLVM and USE_METAL ON. Succeed.
2. export TVM_HOME=/Users/rockey/work/github/src_code/mlc-llm/conda_env/mlc-chat/relax
    export PYTHONPATH=$PYTHONPATH:$TVM_HOME/python
3. python build.py --hf-path=databricks/dolly-v2-3b --target metal. Succeed
4. build mlc-llm following the instructions. Succeed
5. run  ./build/mlc_chat_cli --model dolly-v2-3b --device-name metal. raise error: TVM runtim cannot find vm_load_executable

Use MLC config: "/Users/rockey/work/github/src_code/mlc-llm/conda_env/mlc-chat/mlc-llm/dist/dolly-v2-3b-q3f16_0/params/mlc-chat-config.json"
Use model weights: "/Users/rockey/work/github/src_code/mlc-llm/conda_env/mlc-chat/mlc-llm/dist/dolly-v2-3b-q3f16_0/params/ndarray-cache.json"
Use model library: "/Users/rockey/work/github/src_code/mlc-llm/conda_env/mlc-chat/mlc-llm/dist/dolly-v2-3b-q3f16_0/dolly-v2-3b-q3f16_0-metal.so"
You can use the following special commands:
  /help               print the special commands
  /exit               quit the cli
  /stats              print out the latest stats (token/sec)
  /reset              restart a fresh chat
  /reload [local_id]  reload model `local_id` from disk, or reload the current model if `local_id` is not specified

Loading model...
[17:50:15] /Users/rockey/work/github/src_code/mlc-llm/conda_env/mlc-chat/mlc-llm/cpp/llm_chat.cc:245: 
---------------------------------------------------------------
An error occurred during the execution of TVM.
For more information, please see: https://tvm.apache.org/docs/errors.html
---------------------------------------------------------------
  Check failed: (fload_exec.defined()) is false: TVM runtime cannot find vm_load_executable
Stack trace:
  [bt] (0) 1   libtvm_runtime.dylib                0x0000000104208208 tvm::runtime::Backtrace() + 24
  [bt] (1) 2   libmlc_llm.dylib                    0x00000001048f850d tvm::runtime::detail::LogFatal::Entry::Finalize() + 77
  [bt] (2) 3   libmlc_llm.dylib                    0x00000001048f84b9 tvm::runtime::detail::LogFatal::~LogFatal() + 25
  [bt] (3) 4   libmlc_llm.dylib                    0x00000001048f7499 tvm::runtime::detail::LogFatal::~LogFatal() + 9
  [bt] (4) 5   libmlc_llm.dylib                    0x000000010490a60d mlc::llm::LLMChat::Reload(tvm::runtime::Module, tvm::runtime::String, tvm::runtime::String) + 5693
  [bt] (5) 6   libmlc_llm.dylib                    0x0000000104908bdc mlc::llm::LLMChatModule::GetFunction(tvm::runtime::String const&, tvm::runtime::ObjectPtr<tvm::runtime::Object> const&)::'lambda'(tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*)::operator()(tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*) const + 300
  [bt] (6) 7   mlc_chat_cli                        0x0000000103ebfe66 ChatModule::Reload(ModelPaths const&) + 934
  [bt] (7) 8   mlc_chat_cli                        0x0000000103ebf151 Chat(ChatModule*, std::__1::__fs::filesystem::path const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, int) + 97
  [bt] (8) 9   mlc_chat_cli                        0x0000000103ec150a main + 1722

![image](https://github.com/mlc-ai/mlc-llm/assets/5310875/f99f17ec-26b5-4555-89c3-439206c66182)

## Environment

 - Platform (e.g. WebGPU/Vulkan/IOS/Android/CUDA): 
 - Operating system (e.g. Ubuntu/Windows/MacOS/...): os-Ventura 13.4
 - Device (e.g. iPhone 12 Pro, PC+RTX 3090, ...): mac pro
 - How you installed MLC-LLM (`conda`, source): conda 
 - How you installed TVM-Unity (`pip`, source):  pip
 - Python version (e.g. 3.10): 3.11
 - GPU driver version (if applicable):
 - CUDA/cuDNN version (if applicable):
 - TVM Unity Hash Tag (`python -c "import tvm; print('\n'.join(f'{k}: {v}' for k, v in tvm.support.libinfo().items()))"`, applicable if you compile models):
 - USE_GTEST: AUTO
SUMMARIZE: OFF
USE_IOS_RPC: OFF
CUDA_VERSION: NOT-FOUND
USE_LIBBACKTRACE: AUTO
DLPACK_PATH: 3rdparty/dlpack/include
USE_TENSORRT_CODEGEN: OFF
USE_THRUST: OFF
USE_TARGET_ONNX: OFF
USE_AOT_EXECUTOR: ON
BUILD_DUMMY_LIBTVM: OFF
USE_CUDNN: OFF
USE_TENSORRT_RUNTIME: OFF
USE_ARM_COMPUTE_LIB_GRAPH_EXECUTOR: OFF
USE_CCACHE: AUTO
USE_ARM_COMPUTE_LIB: OFF
USE_CPP_RTVM: OFF
USE_OPENCL_GTEST: /path/to/opencl/gtest
USE_MKL: OFF
USE_PT_TVMDSOOP: OFF
USE_CLML: OFF
USE_STACKVM_RUNTIME: OFF
USE_GRAPH_EXECUTOR_CUDA_GRAPH: OFF
ROCM_PATH: /opt/rocm
USE_DNNL: OFF
USE_VITIS_AI: OFF
USE_LLVM: ON
USE_VERILATOR: OFF
USE_TF_TVMDSOOP: OFF
USE_THREADS: ON
USE_MSVC_MT: OFF
BACKTRACE_ON_SEGFAULT: OFF
USE_GRAPH_EXECUTOR: ON
USE_ROCBLAS: OFF
GIT_COMMIT_HASH: 6fd55bcfecc7abcc707339d7a8ba493f0048b613
USE_VULKAN: OFF
USE_RUST_EXT: OFF
USE_CUTLASS: ON
USE_CPP_RPC: OFF
USE_HEXAGON: OFF
USE_CUSTOM_LOGGING: OFF
USE_UMA: OFF
USE_FALLBACK_STL_MAP: OFF
USE_SORT: ON
USE_RTTI: ON
GIT_COMMIT_TIME: 2023-06-05 12:18:09 -0700
USE_HEXAGON_SDK: /path/to/sdk
USE_BLAS: none
USE_ETHOSN: OFF
USE_LIBTORCH: OFF
USE_RANDOM: ON
USE_CUDA: OFF
USE_COREML: OFF
USE_AMX: OFF
BUILD_STATIC_RUNTIME: OFF
USE_CMSISNN: OFF
USE_KHRONOS_SPIRV: OFF
USE_CLML_GRAPH_EXECUTOR: OFF
USE_TFLITE: OFF
USE_HEXAGON_GTEST: /path/to/hexagon/gtest
PICOJSON_PATH: 3rdparty/picojson
USE_OPENCL_ENABLE_HOST_PTR: OFF
INSTALL_DEV: OFF
USE_PROFILER: ON
USE_NNPACK: OFF
LLVM_VERSION: 16.0.5
USE_OPENCL: OFF
COMPILER_RT_PATH: 3rdparty/compiler-rt
RANG_PATH: 3rdparty/rang/include
USE_SPIRV_KHR_INTEGER_DOT_PRODUCT: OFF
USE_OPENMP: none
USE_BNNS: OFF
USE_CUBLAS: ON
USE_METAL: ON
USE_MICRO_STANDALONE_RUNTIME: OFF
USE_HEXAGON_EXTERNAL_LIBS: OFF
USE_ALTERNATIVE_LINKER: AUTO
USE_BYODT_POSIT: OFF
USE_HEXAGON_RPC: OFF
USE_MICRO: OFF
DMLC_PATH: 3rdparty/dmlc-core/include
INDEX_DEFAULT_I64: ON
USE_RELAY_DEBUG: OFF
USE_RPC: ON
USE_TENSORFLOW_PATH: none
TVM_CLML_VERSION: 
USE_MIOPEN: OFF
USE_ROCM: OFF
USE_PAPI: OFF
USE_CURAND: OFF
TVM_CXX_COMPILER_PATH: /Library/Developer/CommandLineTools/usr/bin/c++
HIDE_PRIVATE_SYMBOLS: OFF
 - Any other relevant information:

**Comment by tqchen** [comment]
Please try out the latest instructions https://mlc.ai/mlc-llm/docs/get_started/try_out.html

**Comment by tqchen** [comment]
closing due to inactive status,  should be resolved in latest updates feel free to open new one.

**Comment by yongbing** [comment]
> Please try out the latest instructions https://mlc.ai/mlc-llm/docs/get_started/try_out.html

This works for me. Thx very much @tqchen . Sorry for the late reply.
