### ISSUE TITLE
[Question] Benchmark performance is poor. 

### ISSUE THREAD

**Issue by sleepwalker2017** [mlc-ai/mlc-llm#412]
## ❓ General Questions

I'm using T4 GPU.

I run this project to inference vicuda 7B, using vicuna-v1-7b-q3f16_0. 
I download the model and run python build.py to generate compiled libs.

it runs ok, but the prefill tokens/second is low. 
```
prefill: 50.6 tok/s, decode: 27.6 tok/s
```

I tested LLama 7B on pytorch, the performance is better than this, prefill can get 400+ tokens/s.

So is that right?  I tested the prefill step without tokenizer step. The input is input tokens, and generate the first token.

Is the models compiled by tvm fully optimized? Seems there is no auto tuning or call to the cublas?

**Comment by junrushao** [comment]
We haven’t focused on performance yet, while we do have a fork that runs faster than torch.compile baseline using flash attention and other optimization techniques.

**Comment by yzh119** [comment]
The performance for CUDA is not optimized yet (we prioritize platform coverage, and currently the kernels are tuned for Metal GPUs, not CUDA), please stay tuned for later updates.

**Comment by sleepwalker2017** [comment]
> stay tuned

hello   I don't quite understand. what do you mean by 'stay tuned'?

**Comment by yzh119** [comment]
The default schedule feature is coming soon which should get you a much faster speed.

**Comment by sleepwalker2017** [comment]
> The default schedule (which does not rely on tuning and you can get decent speed on any device) is coming soon which should get you a much faster speed on CUDA.

thank you! I got it.

**Comment by sleepwalker2017** [comment]
> The default schedule (which does not rely on tuning and you can get decent speed on any device) is coming soon which should get you a much faster speed on CUDA.

hello, how is the performance issue going? Anywhere I can find the updates ? thank you!

**Comment by junrushao** [comment]
@sleepwalker2017 we actually provide a Dockerfile for you guys to reproduce. Please refer to https://github.com/junrushao/llm-perf-bench/
