### ISSUE TITLE
[Doc] How to cite this page

### ISSUE THREAD

**Issue by DongChen06** [mlc-ai/mlc-llm#414]
## 📚 Documentation

Do you have any citation suggestions that we can use to cite this wonderful page? Thank you so much!

**Comment by junrushao** [comment]
CC @tqchen

**Comment by tqchen** [comment]
For now, feel free to cite the github page https://github.com/mlc-ai/mlc-llm/

**Comment by junrushao** [comment]
For academic reference, you may also cite:
- TVM: https://arxiv.org/abs/1802.04799
- TensorIR: https://arxiv.org/abs/2207.04296
- MetaSchedule: https://arxiv.org/abs/2205.13603
