### ISSUE TITLE
build file error when using mlc-llm to compile  rwkv-raven-3b model

### ISSUE THREAD

**Issue by hhhh70** [mlc-ai/mlc-llm#421]
## 🐛 Bug

    when I run the code **python3 build.py --hf-path=RWKV/rwkv-raven-3b --target iphone --quantization q8f16_0**  on ubuntu os, in 
    conda environment, it report an error: 

            TVMError:
        ---------------------------------------------------------------
        An error occurred during the execution of TVM.
        For more information, please see: https://tvm.apache.org/docs/errors.html
        ---------------------------------------------------------------
        
          Check failed: type_code_ == kTVMStr (4 vs. 11) : expected str but got NULL

if I change the 'target' parameter to 'cuda' , it works, but it doesn't work if I set the target parameter to 'iphone'

## Environment

 - build on cuda device in conda env
 - target device is iphone
 - Operating system: Ubuntu
 - How you installed MLC-LLM : conda
 - How you installed TVM-Unity av: pip
 - Python version (e.g. 3.10): 3.9.16
 - CUDA/cuDNN versioncuda (if applicable):11.4

**Comment by yzh119** [comment]
@hhhh70 you need a mac to compile models for iphone target.
