### ISSUE TITLE
[Question] How do I paste the model link for mlc chat Android?

### ISSUE THREAD

**Issue by pbz134** [mlc-ai/mlc-llm#439]
## ❓ General Questions

Every time I try to paste the repo link https://huggingface.co/mlc-ai/mlc-chat-vicuna-v1-7b-q3f16_0 the app tells me „Add model failed.

Can anyone help?

**Comment by cyx-6** [comment]
Thanks for reaching out! Are you running the app built from source, or downloaded from our binary release?
If it is later, it may be the old version. So you can try https://huggingface.co/mlc-ai/mlc-chat-vicuna-v1-7b-q3f16_0/resolve/main/ instead.
We will support the url like https://huggingface.co/mlc-ai/mlc-chat-vicuna-v1-7b-q3f16_0 in next release.

**Comment by pbz134** [comment]
> Thanks for reaching out! Are you running the app built from source, or downloaded from our binary release?
> If it is later, it may be the old version. So you can try https://huggingface.co/mlc-ai/mlc-chat-vicuna-v1-7b-q3f16_0/resolve/main/ instead.
> We will support the url like https://huggingface.co/mlc-ai/mlc-chat-vicuna-v1-7b-q3f16_0 in next release.

Hey there, I now got a different error using your provided link, saying „Add model failed […] (Permission denied)“, with a path pointing to the Downloads folder.

I gave the app all the permissions it asked for, so I really don’t know what to do now.

I then tried the app on a newer Android version (13 instead of 10). „RedPajama“ and „Vicuna“ instantly showed up upon launching the app! Generations also work perfectly fine and dast. I have no clue why it didn’t work on the other version, but for me, the issue is solved now! :)

**Comment by cyx-6** [comment]
That sounds great! Actually, we do not have so many devices with different Android versions to develop and test. So there might be some unexpected errors in some versions or variants of Android system. Anyway, we are glad to see you are able to run our app as expected now.
