### ISSUE TITLE
[Question] How to use my own model?

### ISSUE THREAD

**Issue by liujuncn** [mlc-ai/mlc-llm#447]
## ❓ General Questions

I trained a model with a custom architecture, using a vocab compatible with the hf tokenizer. So how can I use this model in MLC chat?

**Comment by Hzfengsy** [comment]
We are working on documents for adding new model, please stay tuned :)

**Comment by rdcoder33** [comment]
> We are working on documents for adding new model, please stay tuned :)

Really looking forward to this

**Comment by Kathryn-cat** [comment]
Here's the ipynb tutorial: https://github.com/mlc-ai/notebooks/blob/main/tutorial/How_to_add_model_architeture_in_MLC_LLM.ipynb
Please let us know if you have any questions :)
