### ISSUE TITLE
[Bug]  Don't understand how to do the iOS step 4. Running to an error

### ISSUE THREAD

**Issue by LexiestLeszek** [mlc-ai/mlc-llm#451]
## Steps to reproduce the behavior:

I am novice hobby dev. Trying to build MLC iOS app with local LLM from source. Steps 1-3 done.

When i proceed to Step 4, I open Xcode project and open ./ios/MLCChat.xcodeproj using Xcode. I have an Apple Developer Account and used Xcode to build simple stuff couple times (never deployed anything to App Store and don't have paid Dev Account).

**Once opened XCode, I push "play" (run) - I receive an error:**
"Build failed"
1. Library not found for -lmodel_iphone
2. Linker command failed with exit code 1 (use -v to see invocation)

Maybe I should've done "Ensure that all the necessary dependencies and configurations are correctly set up in the Xcode project", but I don't understand what that means. I only opened the ./ios/MLCChat.xcodeproj using Xcode and pushed "run" the project

## Environment

 - Platform (e.g. WebGPU/Vulkan/IOS/Android/CUDA): Mac M1 2020
 - Device (e.g. iPhone 12 Pro, PC+RTX 3090, ...): Mac M1 2020 trying to build an iPhone app
 - How you installed MLC-LLM (`conda`, source): I used pip3 for steps 1-3 in iOS instruction, I don't have conda
 - How you installed TVM-Unity (`pip`, source): pip install --pre --force-reinstall mlc-ai-nightly mlc-chat-nightly -f https://mlc.ai/wheels
 - Python version: 3.11

Please assist, I may be just not understanding what should be done at step 4, but I just don't understand what the documentation implies.

**Comment by tqchen** [comment]
Please make sure you have done step3 https://mlc.ai/mlc-llm/docs/deploy/ios.html#step-3-build-auxiliary-components and check 

```
>>> ls ./build/lib/
libmlc_llm.a         # A lightweight interface to interact with LLM, tokenizer, and TVM Unity runtime
libmodel_iphone.a    # The compiled model lib
libsentencepiece.a   # SentencePiece tokenizer
libtokenizers_cpp.a  # Huggingface tokenizer
libtvm_runtime.a     # TVM Unity runtime
```

**Comment by LexiestLeszek** [comment]
After I run "./prepare_libs.sh" in ./ios i got this message:

+ rustup target add aarch64-apple-ios
info: component 'rust-std' for target 'aarch64-apple-ios' is up to date
+ mkdir -p build/
+ cd build/
+ cmake ../.. -DCMAKE_BUILD_TYPE=Release -DCMAKE_SYSTEM_NAME=iOS -DCMAKE_SYSTEM_VERSION=14.0 -DCMAKE_OSX_SYSROOT=iphoneos -DCMAKE_OSX_ARCHITECTURES=arm64 -DCMAKE_OSX_DEPLOYMENT_TARGET=14.0 -DCMAKE_BUILD_WITH_INSTALL_NAME_DIR=ON -DCMAKE_SKIP_INSTALL_ALL_DEPENDENCY=ON -DCMAKE_INSTALL_PREFIX=. -DCMAKE_CXX_FLAGS=-O3 -DMLC_LLM_INSTALL_STATIC_LIB=ON -DUSE_METAL=ON
-- TVM_HOME: 3rdparty/tvm
-- Forbidding undefined symbols in shared library, using -Wl,-undefined,error on platform iOS
-- Didn't find the path to CCACHE, disabling ccache
-- VTA build with VTA_HW_PATH=/Users/leszekmielnikow/Coding/mlc-llm/3rdparty/tvm/3rdparty/vta-hw
-- Build VTA runtime with target: sim
-- Build with Metal support
-- Build with contrib.random
-- Build with contrib.sort
-- Build with contrib.hybriddump
-- Git found: /opt/homebrew/bin/git
-- Found TVM_GIT_COMMIT_HASH=206661b4aecb362dd5bccfba4de9013f8175cf20
-- Found TVM_GIT_COMMIT_TIME=2023-06-17 14:36:49 -0400
-- Building with TVM Map...
-- Build with thread support...
-- system-nameiOS
-- VERSION: 0.2.00
-- Configuring done (0.7s)
-- Generating done (0.2s)
-- Build files have been written to: /Users/leszekmielnikow/Coding/mlc-llm/ios/build
+ make mlc_llm_static
[ 45%] Built target sentencepiece-static
[ 45%] Built target mlc_llm_objs
[ 54%] Built target tvm_libinfo_objs
[100%] Built target tvm_runtime_objs
[100%] Built target tvm_runtime
[100%] Built target tokenizers_c
[100%] Built target tokenizer_cpp_objs
[100%] Built target tokenizers_cpp
[100%] Built target mlc_llm_static
+ cmake --build . --target install --config release -j
Install the project...
-- Install configuration: "Release"
-- Installing: /Users/leszekmielnikow/Coding/mlc-llm/ios/build/lib/libmlc_llm.a
-- Installing: /Users/leszekmielnikow/Coding/mlc-llm/ios/build/lib/libtokenizers_cpp.a
-- Installing: /Users/leszekmielnikow/Coding/mlc-llm/ios/build/lib/libsentencepiece.a
-- Installing: /Users/leszekmielnikow/Coding/mlc-llm/ios/build/lib/libtvm_runtime.a
-- Up-to-date: /Users/leszekmielnikow/Coding/mlc-llm/ios/build/lib/libtokenizers_c.a
+ cd ..
+ rm -rf MLCSwift/tvm_home
+ ln -s ../../3rdparty/tvm MLCSwift/tvm_home
+ python prepare_model_lib.py
./prepare_libs.sh: line 28: python: command not found

Im particularly worried about last row: **"./prepare_libs.sh: line 28: python: command not found"**

Is it ok and if not, how to fix it?

**Comment by tqchen** [comment]
That seems to mean that you don't have python, which is an issue, please make sure you follow step 1 https://mlc.ai/mlc-llm/docs/deploy/ios.html#step-1-install-build-dependencies to install tvm unity (which have python)

**Comment by LexiestLeszek** [comment]
I definetely have python and ran it multiple times. Maybe the issue is that I use python 3.11 and pip3?

**Comment by tqchen** [comment]
I think it could due to the fact that prepare_libs.sh uses bash, and you setup your python in zsh 

as a result line 28: python: command not found"

**Comment by LexiestLeszek** [comment]
Fixed, changed for zsh and also changed python to python3

**Comment by tqchen** [comment]
You will need to select a real target(iphone, or My Mac(build for iPad)) instead of simulator.

**Comment by LexiestLeszek** [comment]
Can you please tell me how to do that?

Sorry, im just starting ios dev journey and really struggling with a lot of these setup issues.

**Comment by tqchen** [comment]
Click on the top bar, that allows you to select a target, pick iphone(you need to plugin your iphone), or My Mac(designed for iPad) if you have a M1/M2 device

<img width="811" alt="image" src="https://github.com/mlc-ai/mlc-llm/assets/2577440/34f1d420-a32e-40b2-a342-da770caf2c89">

**Comment by tqchen** [comment]
@LexiestLeszek please let us know if ^ helps to resolve the issue

**Comment by tqchen** [comment]
You need to  set sigining & capabilities, select automatically manage signing, change team to your apple dev account team. and change the bundle identifier likely


<img width="677" alt="image" src="https://github.com/mlc-ai/mlc-llm/assets/2577440/f8ec5a92-53c3-4267-b44b-2c79b60b4f83">

**Comment by LexiestLeszek** [comment]
hi, sorry for delay, it still isn't working and I switched to use BERT in my project :(

**Comment by tqchen** [comment]
Likely you need an apple dev account, and change the team to your personal team per above image

**Comment by LexiestLeszek** [comment]
Once I'll have some time, probably next week, I'll try again and will return to you, I really need an LLM in my ios app

**Comment by LexiestLeszek** [comment]
Yay, it runs on my mac locally as an MCL chat. Thanks!

but I after i did most of the step 4 to add it to my own app, Import MLCSwift doesn't work for some reason. Can I ask why didn't you decided to create a model in *.mlmodel format and one class for it? Kinda like HF did with GPT-2 for swift

**Comment by tqchen** [comment]
The process requires a new iphone and not on simulator (due to architecture choice). 

In this case we are not leveraging coreml but uses the mlc runtime and directly generate metal shader

**Comment by MrJungle1** [comment]
> hi, sorry for delay, it still isn't working and I switched to use BERT in my project :(

hello, I would like to ask if you have supported bert for mlc-llm yourself, because it seems that there is no support for bert now.

**Comment by LexiestLeszek** [comment]
> > hi, sorry for delay, it still isn't working and I switched to use BERT in my project :(
> 
> hello, I would like to ask if you have supported bert for mlc-llm yourself, because it seems that there is no support for bert now.

Hi. Apple supports bert by default: https://developer.apple.com/documentation/coreml/model_integration_samples/finding_answers_to_questions_in_a_text_document
