### ISSUE TITLE
[Feature Request] Conversion of weights from bfloat16 to float32 during compilation Relax model.

### ISSUE THREAD

**Issue by vvchernov** [mlc-ai/mlc-llm#458]
## 🚀 Feature
Currently the feature which converts model with bfloat16 data type to float32 model exists. But it looks like it is not optimal and requires  some improvement.

## Motivation
I faced problem related to bfloat16 pytorch model when implemented mpt-7b-instruct on Relax. As a result I simply converted it to float16 on pytorch side. Recently I saw that there is feature partly doing it: if data type of torch tensor is bfloat16 it converts it to float32 and after that keep weights in Relax in float32. To check this feature I used bfloat16 mpt model and quantization type q0f16 and expected that it saved the model in float16, but it does it in float32.

## Alternatives
There are two obvious improvements which can be implemented
* It is more logical to convert data to float16 from bfloat16.
* It is still can be converted to float32 but after that convert it to `quantization.model_dtype` before pack it to tvm::ndarray as weights of Relax model.

cc @tqchen

**Comment by yzh119** [comment]
> It is more logical to convert data to float16 from bfloat16.

The conversion between bfloat16 and float32 is easier than (bf16 vs fp16) because bfloat16 is designed for fast conversion with float32 (we just need to cut off/pad the fractions).

> To check this feature I used bfloat16 mpt model and quantization type q0f16 and expected that it saved the model in float16, but it does it in float32.

Can we post the steps to reproduce this issue? This sounds like a bug.

Thanks for bringing this up anyways. Ideally, we should support bf16 data types as model weights but it requires some effort on the TVM side to make it efficient (I'm working on that).

**Comment by vvchernov** [comment]
Hello @yzh119! Unfortunately I do not have simple reproduction sample.
I used 2 strategies with mpt model (see [branch](https://github.com/Deelvin/mlc-llm/tree/vc/mpt-7b-instruct)). 1. I converted the model from bfloat16 to float16 by handmade pytorch script (it can be found in the branch) and result model weight was slightly more than 12Gb. 2. I used mlc-llm feature for bfloat16 conversion, the result model weight became ~24.5 Gb.

I think it is a bug in the [lines](https://github.com/mlc-ai/mlc-llm/blob/35009639638ad00b5e8662d4791c4b5ef7eedde0/mlc_llm/utils.py#L224C21-L233C46). The `raw_param` should be converted from the original to quantization type (quantization.model_dtype). Moreover the bug is not related to an original model with data type bfloat16, it can occur when the original data type is float16 but we need float32 at any reasons or vice versa

**Comment by vvchernov** [comment]
Some words about difficulties related to conversion from bfloat16 to float16. It can be done by torch, it is intermediate procedure and executed during compilation I do not think it requires much time. It does not matter if the bug is fixed, but bfloat16->float32 increases memory consumption and potentially can be critical in some cases

**Comment by yzh119** [comment]
Thank you for your clarification, I'm reviewing your PR :)

> Some words about difficulties related to conversion from bfloat16 to float16. It can be done by torch, it is intermediate procedure and executed during compilation I do not think it requires much time. It does not matter if the bug is fixed, but bfloat16->float32 increases memory consumption and potentially can be critical in some cases

Yup you are right, I'm just explaining why sometimes it's preferable to use float32 for the intermediate data type of bfloat16), and the memory consumption issue you mentioned is important.
