### ISSUE TITLE
[Bug] I couldn't get rest server to chat back, keep getting exception

### ISSUE THREAD

**Issue by gangchen99** [mlc-ai/mlc-llm#466]
## 🐛 Bug 

I couldn't get rest server to chat back, keep getting exception.

## To Reproduce

1. I set up dist folder side by side with mlc_chat
3. copy prebuilt model
4. run 'conda' to set up mlc-chat-venv.
5. run 'python -m mlc_chat.rest --device-name metal'
6. the serve started, and I can get response for "/stats".
7. try sample_client.py, get exception.

Exception has occurred: ConnectionError
('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
TypeError: HTTPConnection.getresponse() got an unexpected keyword argument 'buffering'

During handling of the above exception, another exception occurred:

  File "<string>", line 3, in raise_from
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

  File "<string>", line 3, in raise_from
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

During handling of the above exception, another exception occurred:

  File "/Users/gangchen/Programming/mlc-llm/examples/rest/sample_client.py", line 25, in <module>
    r = requests.post("http://127.0.0.1:8000/v1/chat/completions", json=payload)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

## Expected behavior

expect service response correctly. 

## Environment

 - Platform: Mac Studio M1 Max
 - Operating system: Mac OS
 - How you installed MLC-LLM (`conda`):
 - Python version: 3.11.3

## Additional context

if I use mlc_chat_cli with the same dist folder, it works fine.

**Comment by yzh119** [comment]
The `mlc_chat_cli` and `mlc_chat` are different packages.
To use REST api you need to install `mlc_chat` package which should be installed with pip:
```bash
pip install --pre --force-reinstall mlc-ai-nightly mlc-chat-nightly -f https://mlc.ai/wheels
```

**Comment by gangchen99** [comment]
> The `mlc_chat_cli` and `mlc_chat` are different packages. To use REST api you need to install `mlc_chat` package which should be installed with pip:
> 
> ```shell
> pip install --pre --force-reinstall mlc-ai-nightly mlc-chat-nightly -f https://mlc.ai/wheels
> ```
right. I am just using mlc_chat_cli to make sure that the /dist folder I copied over is working fine.

**Comment by gangchen99** [comment]
Confirm #469 fixed my issue.
