### ISSUE TITLE
[Question] android apk: Add model failed: no protocol :/data/xxx/mlc-chat-config.json

### ISSUE THREAD

**Issue by zhufuwengang** [mlc-ai/mlc-llm#468]
## ❓ General Questions
I install mlc-chat.apk on device successfully:
![image](https://github.com/mlc-ai/mlc-llm/assets/24954820/42a6418e-fb9b-4865-8d81-0d97ead556c0)

But when I open the apk, it recommand me to fill model URL:
![image](https://github.com/mlc-ai/mlc-llm/assets/24954820/64c407ee-cb24-4aab-9871-9e076fca4d1c)

I input the local path '/data/wg' where models have been placed:
![image](https://github.com/mlc-ai/mlc-llm/assets/24954820/067d6cb8-7eba-47a8-ac0a-afa0dc29c9f8)

![image](https://github.com/mlc-ai/mlc-llm/assets/24954820/dc67c047-55e0-4e0d-9f5f-46e98f88bab1)
And an error has occurred:
![image](https://github.com/mlc-ai/mlc-llm/assets/24954820/55851df4-85a6-466f-adbe-0bff2fa30114)

I search the docs this project, but find nothing about this issue.
Did i miss somthing?

**Comment by zhufuwengang** [comment]
![image](https://github.com/mlc-ai/mlc-llm/assets/24954820/62b22a7a-09d5-4bed-b591-07facb765016)

**Comment by cyx-6** [comment]
Thanks for reporting! We do not support the local params loading yet. So the model url to add should be the Internet url only. That is why it errors as "no protocol :/data/xxx/mlc-chat-config.json". By the way, the model list should have 2 default model entries. Did you installed the old MLCChat app before? If so, it may need you to uninstall and re-install the current one to refresh.

**Comment by windmaple** [comment]
Where is the latest android binary then?

I'm following the instruction [here](https://github.com/mlc-ai/mlc-llm/blob/main/site/index.md#android) and there is no default download model after installing the apk from the instruction section.

**Comment by cyx-6** [comment]
https://github.com/mlc-ai/binary-mlc-llm-libs/blob/main/mlc-chat.apk
this should be the latest apk to download, though we may release something new soon.
But this version should have 2 entries in model list, by deault initially.
Did you install any old version of android apk?

**Comment by windmaple** [comment]
OK, for some reason the Vicuna/RedPajama models didn't show up in my first few tries. Now I can see them. Thanks!
