### ISSUE TITLE
[Bug] Android Phone Problems

### ISSUE THREAD

**Issue by MRQJsfhf** [mlc-ai/mlc-llm#476]
Phone model Realme GTneo
Android version: 13
Processor: Dimensity 1200
memory 8gb
Structure: 1 x 3.0 GHz large core Arm Cortex-A78
3 x 2.6 GHz large core Arm Cortex-A78
4 x 2.0 GHz Arm Cortex-A55
GPU adopts G77 architecture
Questions: 1. Use prompt words to give knowledge and ask questions on the spot
It can be given, but as soon as I exit the software and enter, there is no chat history, and then I ask the same content, and I start talking nonsense, and I don’t remember anything before.
2. On Realme GTneo, the 3b parameter model cannot be used. I waited for several hours to load, downloaded, deleted, and installed many times.
3. The generation speed is too slow, two characters per second. Not sure if it's a compatibility issue. Also, once you log out of the phone, all chat records are gone when you go in.

**Comment by cyx-6** [comment]
Thanks for reporting! For the question 1 and 3, we do clear the history when exiting the chatting view. We only keep history when back to main page and chat with the same model again. So it is possible when you lock the phone or hang the app in the background and then back to chat, the history or entire apk is reset.
