### ISSUE TITLE
[Bug] Android project can't refer ChatModule.java after #478

### ISSUE THREAD

**Issue by chensinit** [mlc-ai/mlc-llm#479]
## 🐛 Bug

Android project can't refer ChatModule.java after #478

mlc-llm/android/MLCChat/app/src/main/java/ai/mlc/mlcchat/AppViewModel.kt:3:15 Unresolved reference: mlcllm

## To Reproduce

1. pull
1. try build android project

## Expected behavior

There is no error.

## Environment

Platform (e.g. WebGPU/Vulkan/IOS/Android/CUDA):
Operating system (e.g. Ubuntu/Windows/MacOS/...):
Device (e.g. iPhone 12 Pro, PC+RTX 3090, ...)
How you installed MLC-LLM (conda, source):
How you installed TVM-Unity (pip, source):
Python version (e.g. 3.10):
GPU driver version (if applicable):
CUDA/cuDNN version (if applicable):
TVM Unity Hash Tag (python -c "import tvm; print('\n'.join(f'{k}: {v}' for k, v in tvm.support.libinfo().items()))", applicable if you compile models):

**Comment by cyx-6** [comment]
Thanks for reaching out! This may not be a bug, but due to the late update of our docs. Now #481 updates with the change in #478. Feel free to try it.

**Comment by chensinit** [comment]
Thank you. I will check and try again.

**Comment by chensinit** [comment]
Follow new doc. and I build apk successfully.
but i still got error in runtime.

W/System.err: [WARN] Couldn't find native library tvm4j.
W/System.err: java.lang.UnsatisfiedLinkError: Couldn't find the resource libtvm4j.so

**Comment by cyx-6** [comment]
@chensinit do you have the complete log? That warning is normal if there is a following log says, `tvm4j_runtime_packed.so` found. And the app works well as expected.
