### ISSUE TITLE
[Bug] Warning: Fast mode segfaults when there are out-of-bounds indices. Make sure input indices are in bound LLVM ERROR: 

### ISSUE THREAD

**Issue by davidjohn001** [mlc-ai/mlc-llm#485]
## 🐛 Bug

python3 build.py --model /home/LLM/vicuna-7b-v1.1 --quantization q4f16_0 --target android --max-seq-len 768

1.  Install TVM Unity success
2.  validate TVM success
3. Getting Vicuna Weights success also have the change sed -i 's/LLaMAForCausalLM/LlamaForCausalLM/g' llama-7b-hf/config.json
4.python3 build.py --model /home/LLM/vicuna-7b-v1.1 --quantization q4f16_0 --target android --max-seq-len 768 failed

Log:
(tvm-build-venv) mlc-llm$ python3 build.py --model  /LLM/vicuna-7b-v1.1 --quantization q4f16_0 --target android --max-seq-len 768
Using path "/home/LLM/vicuna-7b-v1.1" for model "vicuna-7b-v1.1"
Database paths: ['log_db/rwkv-raven-3b', 'log_db/redpajama-3b-q4f32', 'log_db/vicuna-v1-7b', 'log_db/redpajama-3b-q4f16', 'log_db/dolly-v2-3b', 'log_db/rwkv-raven-7b', 'log_db/rwkv-raven-1b5']
Target configured: opencl -keys=opencl,gpu -max_num_threads=256 -max_shared_memory_per_block=16384 -max_threads_per_block=256 -texture_spatial_limit=16384 -thread_warp_size=1
[13:55:23] /home//LLM/tvm-unity/include/tvm/topi/transform.h:1075: Warning: Fast mode segfaults when there are out-of-bounds indices. Make sure input indices are in bound
**[13:55:26] /home//LLM/tvm-unity/include/tvm/topi/transform.h:1075: Warning: Fast mode segfaults when there are out-of-bounds indices. Make sure input indices are in bound
LLVM ERROR:** 

## Environment

 - Platform (e.g. Android):
 - Operating system (e.g. Ubuntu..):
 - Device (e.g. iPhone 12 Pro, PC+RTX 3090, ...)
 - How you installed MLC-LLM (`conda`, source):
 - How you installed TVM-Unity (`pip`, source):
 - Python version (e.g. 3.10):
 - GPU driver version (if applicable):
 - CUDA/cuDNN version (if applicable):
 - TVM Unity Hash Tag (`python -c "import tvm; print('\n'.join(f'{k}: {v}' for k, v in tvm.support.libinfo().items()))"`, applicable if you compile models):
 - Any other relevant information:

**Comment by MasterJH5574** [comment]
Hi @davidjohn001, thanks for reporting. Regarding the warning, yes we are aware of it. And we expect that the warning itself does not indicate anything real segfault and is not expected to affect anything. It is just an warning out there and possibly we will deprecate the warning in the future.

On the other hand, the LLVM ERROR looks like the real issue here. So would you like to share more details about the concrete LLVM ERROR so that we can further examine? Thanks!

**Comment by davidjohn001** [comment]
[14:30:16] /home/LLM/tvm-unity/include/tvm/topi/transform.h:1075: Warning: Fast mode segfaults when there are out-of-bounds indices. Make sure input indices are in bound
**LLVM ERROR:** 
(tvm-build-venv) Workstation:~/LLM/mlc-llm$

nothing follow in LLVM ERROR, and the script ended directly

**Comment by davidjohn001** [comment]
**The LLVM ERROR:**
happened in this line.
mod = relax.pipeline.get_pipeline()(mod)  # pylint: disable=no-value-for-parameter

{'_name_or_path': 'llama-7b-hf', 'architectures': ['LlamaForCausalLM'], 'bos_token_id': 0, 'eos_token_id': 1, 'hidden_act': 'silu', 'hidden_size': 4096, 'initializer_range': 0.02, 'intermediate_size': 11008, 'max_position_embeddings': 2048, 'max_sequence_length': 2048, 'model_type': 'llama', 'num_attention_heads': 32, 'num_hidden_layers': 32, 'pad_token_id': -1, 'rms_norm_eps': 1e-06, 'tie_word_embeddings': False, 'torch_dtype': 'float16', 'transformers_version': '4.28.1', 'use_cache': True, 'vocab_size': 32000}

**Comment by junrushao** [comment]
You are using LLVM 6, which is quite outdated. Please refer to this page to compile TVM Unity properly: https://mlc.ai/mlc-llm/docs/install/tvm.html#option-2-build-from-source
