### ISSUE TITLE
[Bug] it's alway answer the same contents

### ISSUE THREAD

**Issue by CharlesWai** [mlc-ai/mlc-llm#491]
## To Reproduce

1.ask some questions
2.reply same contents
3.it seems can not stop by itself

## Environment

 - Platform (Android):
 - Operating system (Android13):
 - Device (moto edge x30)
 - How you installed MLC-LLM (github release apk file):
 - How you installed TVM-Unity (the same as upon):
 - Python version ():
 - GPU driver version (if applicable):
 - CUDA/cuDNN version (if applicable):
 - TVM Unity Hash Tag (`python -c "import tvm; print('\n'.join(f'{k}: {v}' for k, v in tvm.support.libinfo().items()))"`, applicable if you compile models):
 - Any other relevant information:

## Additional context

![Screenshot_20230701-203046.png](https://github.com/mlc-ai/mlc-llm/assets/50195284/25c6f7a6-c186-4b6f-a279-cfac52cb2783)

**Comment by yzh119** [comment]
The red pajama model is not trained on Chinese text so it's normal that it can not produce meaningful text for inputs in Chinese. You can try compiling another model which was trained or fine-tuned on Chinese text.
