### ISSUE TITLE
[Bug] RedPajama wrong on macos:An error occurred during the execution of TVM.

### ISSUE THREAD

**Issue by ceasarXuu** [mlc-ai/mlc-llm#493]
## To Reproduce

1. conda create -n mlc-chat-venv -c mlc-ai -c conda-forge mlc-chat-cli-nightly
2. conda activate mlc-chat-venv
3. conda install git git-lfs
4. git lfs install
5. mkdir -p dist/prebuilt
6. download binary-mlc-llm-libs.zip  from github,   unzip it to dist/prebuilt/lib
7. cd dist/prebuilt]
8. git clone https://huggingface.co/mlc-ai/mlc-chat-RedPajama-INCITE-Chat-3B-v1-q4f16_0
9. cd ../..
10. mlc_chat_cli --local-id RedPajama-INCITE-Chat-3B-v1-q4f16_0

![image](https://github.com/mlc-ai/mlc-llm/assets/50387804/767cdc48-6b3b-4bec-80e1-3252f06aa91e)

## Environment

 - Platform (e.g. WebGPU/Vulkan/IOS/Android/CUDA):
 - Operating system (e.g. Ubuntu/Windows/MacOS/...): macos
 - Device (e.g. iPhone 12 Pro, PC+RTX 3090, ...): macmini(M2)
 - How you installed MLC-LLM (`conda`, source): conda
 - How you installed TVM-Unity (`pip`, source): git
 - Python version (e.g. 3.10):none
 - GPU driver version (if applicable):none
 - CUDA/cuDNN version (if applicable):none
 - TVM Unity Hash Tag (`python -c "import tvm; print('\n'.join(f'{k}: {v}' for k, v in tvm.support.libinfo().items()))"`, applicable if you compile models):none

## Additional context

mlc-chat-vicuna-v1-7b-q3f16_0   can run success.

**Comment by tqchen** [comment]
The error indicate that you have an M1 but installed a conda for x86, please install https://github.com/conda-forge/miniforge miniforge for m1

**Comment by junrushao** [comment]
Please follow the instructions on this page:  https://mlc.ai/mlc-llm/docs/install/conda.html#validate-installation
