### ISSUE TITLE
ms.tune_tir doesn't work properly

### ISSUE THREAD

**Issue by ylc2001** [mlc-ai/mlc-llm#501]
## ms.tune_tir doesn't work properly

I'm using mlc-llm to compile Vicuna-7B (target is cuda), and I'm trying to apply the auto-tuning method introduced in [https://mlc.ai/zh/chapter_gpu_acceleration/part1.html#](url), to make the compiled model run faster. I make some changes to my build.py, executing the following code in build():

```python
def optimize_static_tir(mod: tvm.IRModule):
    """Optimize static shape TIR only"""
    mod_static, mod_dynamic = utils.split_static_dynamic_tir(mod)
    database = ms.tune_tir(
        mod=mod_static,
        target="nvidia/geforce-rtx-2080-ti",
        max_trials_global=128,
        num_trials_per_iter=64,
        work_dir="./tune_tmp",
    )
    sch = ms.tir_integration.compile_tir(database, mod_static, "nvidia/geforce-rtx-2080-ti")
    # merge mod_dynamic back into the optimized mod_static
    mod_merged = {}
    for k, v in mod.functions.items():
        if not isinstance(v, tvm.tir.PrimFunc):
            mod_merged[k] = v
    for k, v in sch.mod.functions.items():
        mod_merged[k] = v
    for k, v in mod_dynamic.functions.items():
        mod_merged[k] = v
    mod_merged = tvm.IRModule(mod_merged)
    return mod_merged
```

Then I got error `ValueError: Unsupported argument type: n`. This is because one of the TIRs(rotary_embedding1) in `mod_static` has a parameter called `n`, and `ms.tune_tir()` can't handle that. This is the bug.

I also tried to put that one TIR into `mod_dynamic` to try to quickly fix this by changing the following in `mlc_llm/utils.py`:

```python
# line 332
if _is_static_shape_func(v) and k.__str__().find("rotary_embedding1") < 0:
    mod_static[k] = v
else:
    mod_dynamic[k] = v
```

But I still get error afterwards in this step: `sch = ms.tir_integration.compile_tir(database, mod_static, "nvidia/geforce-rtx-2080-ti")`

Error message: `ValueError: too many values to unpack (expected 1)`

## To Reproduce

1. Change build.py as described above.
1. Run build: `python3 build.py --model vicuna-7b-v1.3 --target cuda --quantization q3f16_0`

## Expected behavior

Successfully perform auto-tune to the static TIRs in `mod_static` using the method introduced in [https://mlc.ai/zh/chapter_gpu_acceleration/part1.html#](url), and the model runs faster.

## Environment

 - Platform: CUDA
 - Operating system: Ubuntu
 - Device: server + 2080Ti
 - How you installed MLC-LLM (`conda`, source): source
 - How you installed TVM-Unity (`pip`, source): pip
 - Python version: 3.11.3

**Comment by LeiWang1999** [comment]
As far as I know about meta schedule, currently meta is not able to perform tuning for the expr with dynamic symbolic.

**Comment by ylc2001** [comment]
I know, so I made sure the input for meta schedule only have static tir functions: `mod_static, mod_dynamic = utils.split_static_dynamic_tir(mod)`

So it's confusing that ms.tune_tir still doesn't work properly with a module without dynamic tirs.

**Comment by yzh119** [comment]
@ylc2001 The way MLC team uses meta schedule to optimize dynamic workloads is to replace symbolic variables with constants (e.g. 128), then search for the best schedule for these workloads, and insert symbolic variables back in the end. The process is tedious and not scalable thus we only provide a limited set of examples using auto-tuning.

The team is now pushing [dlight](https://discuss.tvm.apache.org/t/vertical-focused-community-meeting-july-25th-large-language-models-2/15138): default scheduling for dynamic workloads without the need of auto-tuning.

Some efforts have been upstreamed: https://github.com/apache/tvm/pulls?q=is%3Apr+dlight+is%3Aclosed, please stay tuned.

**Comment by ylc2001** [comment]
thx a lot, looking forward to it.
