### ISSUE TITLE
[Question] I am running the llama-7B model on 3080Ti, why is it only 10 tok/s？

### ISSUE THREAD

**Issue by wangxu569** [mlc-ai/mlc-llm#502]
## ❓ General Questions

This is significantly different from the performance comparison in the performance summary table
![image](https://github.com/mlc-ai/mlc-llm/assets/53510676/730415ad-8e78-40ba-9098-869e0aa5fc01)

OS: ubuntu20.04
GPU:3080Ti

![image](https://github.com/mlc-ai/mlc-llm/assets/53510676/6eb9b553-d202-4f72-a56b-34f16571655b)

**Comment by ylc2001** [comment]
What quantization are you using? Try `--quantization q3f16_0`, that's gonna be fast.

**Comment by wangxu569** [comment]
> What quantization are you using? Try `--quantization q3f16_0`, that's gonna be fast.

I am using q8f16_ 0 quantization method, because I want better output effect

**Comment by ylc2001** [comment]
That might be the reason. Try q3 or q4 : )

**Comment by tqchen** [comment]
Please try q4f16_1 instead

**Comment by jimmy-adams** [comment]
> ## ❓ General Questions
> This is significantly different from the performance comparison in the performance summary table ![image](https://github.com/mlc-ai/mlc-llm/assets/53510676/730415ad-8e78-40ba-9098-869e0aa5fc01)
> 
> OS: ubuntu20.04 GPU:3080Ti
> 
> ![image](https://github.com/mlc-ai/mlc-llm/assets/53510676/6eb9b553-d202-4f72-a56b-34f16571655b)

Hello, which batch and input length did you use for the test? @wangxu569
