### ISSUE TITLE
Some questions about quantification methods...[Question] 

### ISSUE THREAD

**Issue by wangxu569** [mlc-ai/mlc-llm#504]
## ❓ General Questions

When I tested the performance, I found that the quantization method of q4f32_0 is four times faster than the quantization method of q4f16_0, but I don't know how much difference the accuracy of the two methods will have. Which of these two methods is recommended? ?
The speed of q4f16_0 and q8f16_0 is almost the same, which is somewhat different from the previous cognition. How to explain these quantization methods?

**Comment by MasterJH5574** [comment]
Hi @wangxu569, thanks for the question. Right now for LLaMA-family models, the performance of `q4f16_0` is not well-optimized and this can explain the phenomenon you observed. At this moment you may try `q3f16_0` (whose performance is optimized) for better performance for LLaMA-family models, though compared with 4-bit quantization, the 3-bit one comes with a bit accuracy loss sometimes.

Recently we are optimizing the performance of 4-bit quantization and it is expected to come soon. This optimized one will have much better performance than current ones. Please stay tuned :-)
