### ISSUE TITLE
[Feature Request] Do you have plan to support it for Windows on Arm devices?

### ISSUE THREAD

**Issue by zhanweiw** [mlc-ai/mlc-llm#505]
## 🚀 Feature

There're more Windows on Arm devices today, such as Surface Pro 9, x13s. Do you have plan to support mlc-llm for these devices?
Thanks in advance!

**Comment by Hzfengsy** [comment]
I think there is no technical problem to run on Arm devices. But we do not have the bandwidth to support prebuilt libs on every device, please try to build it by yourself :)

**Comment by zhanweiw** [comment]
It seems Arm devices doesn't have **Vulkan** and **OpenCL** driver. How can run it on GPU? Thanks in advance!
