### ISSUE TITLE
[Bug] Tokens from HF and MLC-LLM are not the same

### ISSUE THREAD

**Issue by vvchernov** [mlc-ai/mlc-llm#509]
## 🐛 Bug

I'm debugging mpt model implemented on Relax as custom model in mlc-llm. I'm trying to compare intermediate tensor in the topology with the original model from hugging face (HF) as apple-to-apple. I've observed that sequence of tokens for prompt ("give me instructions how to prepare boiled eggs") are not the same: 31089,   479,  7997,   849,   281, 10347, 35517, 11624 is used by HF and 8780, 27, 1918, 479, 7997, 849, 281, 10347, 35517, 11624, 187, 249, 26161, 32 is used by mlc-llm. In both cases "EleutherAI/gpt-neox-20b" tokenizer is used. I do not have any additional system prompt for mpt in mlc-llm. It looks like the sequences are close, but mlc-llm one has additional pre- and post tokens

## To Reproduce

Semi-script for launch on HF:
```python
config = AutoConfig.from_pretrained(
    'mosaicml/mpt-7b-instruct',
    trust_remote_code=True
)

# Recommendation from https://huggingface.co/mosaicml/mpt-7b-instruct
config.update({"max_seq_len": 4096}) # 4096 recommended but it was decreased to 128 for test
config.update({"max_new_tokens": args.seq_len})
model = AutoModelForCausalLM.from_pretrained(
      'mosaicml/mpt-7b-instruct',
      config=config,
      torch_dtype=torch.bfloat16,
      trust_remote_code=True
)
model.to(device='cuda:0')
tokenizer = AutoTokenizer.from_pretrained("EleutherAI/gpt-neox-20b")
tokens = tokenizer("give me instructions how to prepare boiled eggs", return_tensors="pt")
print("PROMPT TOKENS: ", tokens.input_ids)
input_ids = tokens.input_ids.to("cuda")
torch.cuda.synchronize()
outputs = model.generate(input_ids)
``` 

On mlc-llm side the branch https://github.com/Deelvin/mlc-llm/tree/vc/dev can be used with MPT implementation and standard scripts for compilation (use 74b0c6561bc75a2bfda356bc7b11eff9a60597f5 commit of mlc-llm for correct compilation) and launching mlc_chat_cli with prompt "give me instructions how to prepare boiled eggs". I'm printing input tokens in PrefillStep before Forward func. 

## Expected behavior

No differences between sequence of tokens for mlc-llm and HF for the same tokenizer and input prompt by default.

## Environment

 - Platform: CUDA
 - Operating system: Ubuntu
 - Device: PC+A10G
 - How you installed MLC-LLM: source
 - How you installed TVM-Unity: source
 - Python version: 3.10.6
 - GPU driver version: 530.41.03
 - CUDA/cuDNN version: 12.1

**Comment by yzh119** [comment]
I checked the tokenizer file of gpt-neox-20b: https://huggingface.co/EleutherAI/gpt-neox-20b/raw/main/tokenizer.json

The discrepancy is that mlc-llm add some prefix and suffix to the sentence:
```
client: give me instructions how to prepare boiled eggs <eos> instructor
```
I think it's because of the roles you defined here https://github.com/mlc-ai/mlc-llm/pull/460/files#diff-c10850af6bfede469df975406122f7f9e26ce662a93643bf65bf3207ae608e46R302 ?

**Comment by yzh119** [comment]
Note that the tokenizer treat differently for tokens in the sentence front and tokens in the middle of sentence.
For in-sentence token "word", the tokenizer would parse it as "Ġword" to distinguish it from "word" in the beginning of a sentence.

**Comment by vvchernov** [comment]
Hello @yzh119! Thank you for your quick and detailed response, but there are still some questions. 1. I thought that role tags are for the sake of clearance of chat API, not to connect to initial prompt. It seemed that for it we have system prompt. Could we use for addition to the original prompt the system pre- and post- fixes? 2. I do not see `<eos>` token in mlc-llm token sequence as you wrote. 3. Should I clear roles and role_empty_sep to have the same input token sequence as for the script based on HF or there is other way?

**Comment by tqchen** [comment]
We switched to the HF toknizers.json, closing this as the issue can be stale
