### ISSUE TITLE
CL_OUT_OF_HOST_MEMORY

### ISSUE THREAD

**Issue by njuhang** [mlc-ai/mlc-llm#512]
Here are my steps:
python3 build.py  --model /mnt/e/llm/dolly-v2-3b --quantization q4f16_0 --target android-dylib --max-seq-len 768
adb push dist/dolly-v2-3b-q4f16_0/ /data/local/tmp/mlc/dist
./mlc_chat_cli --model dolly-v2-3b --evaluate

Then I got error as:
/home/mlc-llm/3rdparty/tvm/src/runtime/library_module.cc:87: TVMError: OpenCL build error for device=0x797e6cdae0
Error: CL_OUT_OF_HOST_MEMORY
Pass
Stack trace:
  File "/home/mlc-llm/3rdparty/tvm/src/runtime/opencl/opencl_module.cc", line 255

But I could pass dolly-v2-7b model in the same steps. As my opinion, dolly-7b will take more memory but it got no error.

**Comment by xukui1203** [comment]
I found the same issue on Android platform. It can pass vicuna-v1-7b model. But by the same steps, when using RedPajama-INCITE-Chat-3B, it failed with error: CL_OUT_OF_HOST_MEMORY

**Comment by tqchen** [comment]
the latest build should greatly reduced the memory cost
