### ISSUE TITLE
[Question] How to Set use the CUP or GPU or NPU in MLC-LLM on Android  Phone? and how to set the use percentage？

### ISSUE THREAD

**Issue by davidjohn001** [mlc-ai/mlc-llm#513]

**Comment by yzh119** [comment]
I suppose you mean mixed execution on different processing units in mobile?
MLC-LLM didn't explore this direction actually. In general, GPU would have much more cores and arithmetic units than CPU so we prefer to execute the network on GPU as much as possible.

Does Samsung S23 have its own NPU units?

**Comment by davidjohn001** [comment]
I mean could we set the phone use CPU or GPU and set the memory memory_fraction? like PyTorch in PC
like this : torch.cuda.set_per_process_memory_fraction(0.5, 0)

**Comment by yzh119** [comment]
1. Yes, unless the ISA for programming these NPU's are exposed in OpenCL or Vulkan.
2. By default we will use GPU if it's available, there is no option to switch between CPU and GPU but we should support it in the future.
3. Not yet.
