### ISSUE TITLE
[Bug] python ChatModule init gives "ValueError: Cannot find global function mlc.llm_chat_create"

### ISSUE THREAD

**Issue by pecanjk** [mlc-ai/mlc-llm#521]
## 🐛 Bug

I'm trying to test the python mlc_chat ChatModule from the source file chat_module.py. （I do not use the prebuild mlc-chat-nightly）

The ```fcreate = tvm.get_global_func("mlc.llm_chat_create")```  inside `ChatModule` will return "ValueError: Cannot find global function mlc.llm_chat_create"

Besides, I cannot understand what is the ```mlc.llm_chat_create```, and where ```mlc.llm_chat_create``` comes from.

## To Reproduce

1. pip install --pre --force-reinstall mlc-ai-nightly-cu117 -f https://mlc.ai/wheels
2. validation python -c "import tvm; print(tvm.__file__)"  gives  "/home/xxx/.conda/envs/mlc-chat-venv/lib/python3.11/site-packages/tvm/__init__.py"
3. validation python -c "import tvm; print(tvm._ffi.base._LIB)"   gives  "<CDLL '/home/xxx/.conda/envs/mlc-chat-venv/lib/python3.11/site-packages/tvm/libtvm.so', handle 56554b361550 at 0x7f5bf58e6510>"
4. python3 build.py --model RedPajama-INCITE-Chat-3B-v1 --target cuda --quantization q4f16_0
5.  inside python env
``` python
chat_mod = ChatModule(ARGS.device_name, ARGS.device_id)
lib = tvm.runtime.load_module(lib_dir)
chat_mod.reload(lib=lib, model_path=local_model_path)
```

Error: 
``` python
import tvm
fcreate = tvm.get_global_func("mlc.llm_chat_create")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/xxx/.conda/envs/mlc-chat-venv/lib/python3.11/site-packages/tvm/_ffi/registry.py", line 234, in get_global_func
    return _get_global_func(name, allow_missing)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "tvm/_ffi/_cython/./packed_func.pxi", line 344, in tvm._ffi._cy3.core._get_global_func
ValueError: Cannot find global function mlc.llm_chat_create
```

**Comment by yzh119** [comment]
You must load the mlc_llm.so before using `ChatModule` which is compiled from C++ source code: https://github.com/mlc-ai/mlc-llm/blob/b71bd391239343d262c9931343e20a6aa8ce5bdc/python/mlc_chat/chat_module.py#L30-L41

> Besides, I cannot understand what is the mlc.llm_chat_create, and where mlc.llm_chat_create comes from.

These functions are cross-language TVM runtime functions that can be defined from one language and used in another language. In MLC-LLM, these functions are defined and registered in C++ (https://github.com/mlc-ai/mlc-llm/blob/b71bd391239343d262c9931343e20a6aa8ce5bdc/cpp/llm_chat.cc#L1178-L1180), to use them in Python, you must load the shared library compiled from C++ source code.

**Comment by pecanjk** [comment]
> You must load the mlc_llm.so before using `ChatModule` which is compiled from C++ source code:
> 
> https://github.com/mlc-ai/mlc-llm/blob/b71bd391239343d262c9931343e20a6aa8ce5bdc/python/mlc_chat/chat_module.py#L30-L41
> 
> > Besides, I cannot understand what is the mlc.llm_chat_create, and where mlc.llm_chat_create comes from.
> 
> These functions are cross-language TVM runtime functions that can be defined from one language and used in another language. In MLC-LLM, these functions are defined and registered in C++ (
> 
> https://github.com/mlc-ai/mlc-llm/blob/b71bd391239343d262c9931343e20a6aa8ce5bdc/cpp/llm_chat.cc#L1178-L1180
> 
> ), to use them in Python, you must load the shared library compiled from C++ source code.

got it. Thanks
