### ISSUE TITLE
[Question] Can I run the mlc-chat on linux-aarch64? Or is there some practical doc or methods to achieve it?

### ISSUE THREAD

**Issue by chen982** [mlc-ai/mlc-llm#533]
## ❓ General Questions

There isn't linux-aarch64 package in conda org. Since the osx-arm64 is okay, is there some practical doc or methods to achieve it on linux-aarch64?

**Comment by yzh119** [comment]
Do you mean `mlc_chat_cli`?
You can compile it from source: https://mlc.ai/mlc-llm/docs/deploy/cli.html#option-2-build-mlc-runtime-from-source

**Comment by yzh119** [comment]
Do you mean `mlc_chat_cli`?
You can compile it from source: https://mlc.ai/mlc-llm/docs/deploy/cli.html#option-2-build-mlc-runtime-from-source
