### ISSUE TITLE
[Bug] Unclear how to create mlc-ai/demo-vicuna-v1-7b-int4 manually

### ISSUE THREAD

**Issue by kmadsen** [mlc-ai/mlc-llm#540]
## To Reproduce

1. Follow instructions for compiling vicuna https://mlc.ai/mlc-llm/docs/compilation/get-vicuna-weight.html
1. Follow instruction for compiling models https://mlc.ai/mlc-llm/docs/compilation/compile_models.html
1. End result is a vicuna-7b-v1.1-q4f16_0
1. This result is incompatible with https://huggingface.co/mlc-ai/demo-vicuna-v1-7b-int4

I've been making it work by manually push the vicuna weights to my device.

I also pushed them here https://huggingface.co/kmadsen/vicuna-7b-v1.1-q4f16_0 so our app can download them from something instead of requiring adb.

**Comment by kmadsen** [comment]
Was reading more of the documentation and noticed `--reuse-lib`.. Maybe that is the way? I'll give a try later

https://mlc.ai/mlc-llm/docs/compilation/distribute_compiled_models.html

**Comment by Hzfengsy** [comment]
`mlc-ai/demo-vicuna-v1-7b-int4` is deprecated, we are now moving to `vicuna-7b-v1.1-q4f16_0` instead

**Comment by kmadsen** [comment]
Thanks @Hzfengsy! Is it a work in progress or am I missing the update somewhere?

It's still in use here https://github.com/mlc-ai/mlc-llm/blob/9c3f12c89474d38366d91d61658be615f509654a/android/MLCChat/app/src/main/assets/app-config.json#L8

I published one earlier today (thinking it's temporary) because I couldn't find it anywhere else https://huggingface.co/kmadsen/vicuna-7b-v1.1-q4f16_0

**Comment by Hzfengsy** [comment]
The prebuilt libs are here: https://mlc.ai/mlc-llm/docs/prebuilt_models.html, which contains `vicuna-v1-7b-q3f16_0`.

**Comment by kmadsen** [comment]
@Hzfengsy actually another issue is building the android libraries introduced here https://github.com/mlc-ai/mlc-llm/pull/478

Android it seems you still need to build the prebuild_models in order to create the android libraries. Is there a command to build the android libraries from existing mlc weights like `vicuna-v1-7b-q3f16_0`?
