### ISSUE TITLE
[Question] how to profiling 

### ISSUE THREAD

**Issue by njuhang** [mlc-ai/mlc-llm#544]
## ❓ General Questions

I see there is a evaluator.py which we could use to evaluate time on local machine with python environment. 
Now I want to profiling or evaluate on mobile devices without python. For example, how to achieve this function in mlc_chat_cli on mobile phone?

**Comment by WashSwang** [comment]
I think you can use TVM RPC. `relax.VirtualMachine` can be initialized with a remote device. There won't be much effort to revision evaluator.py to profiling on mobile devices. In my practice, by default, TVM RPC apk doesn't support relax executable. You may need to include the code of relax virtual machine to build the apk.

**Comment by njuhang** [comment]
Thanks, I will make a try on it. BTW, does it support OpenCL?

**Comment by WashSwang** [comment]
Yes. OpenCL is directly supported.

**Comment by njuhang** [comment]
yes it is .Thanks a lot

**Comment by Lanssi** [comment]
Hello!
Do you solve the problem of profiling the operator?
If so, could you please tell me how to do?
