### ISSUE TITLE
The  Android app built from source code is not working 

### ISSUE THREAD

**Issue by willswordh** [mlc-ai/mlc-llm#545]
I think it is a critical issue from the repo code that the Android App built from the source code can't work at the ChatView.kt page. All three buttons are not working and the llm model can't be used on that page. Please take a look at it.

**Comment by cyx-6** [comment]
Thanks for reporting! What device are you running the app on? If you are running it on device(or simulator) without OpenCL, like Google Pixel, it won't work like that. We shall add some helper information in app for this case soon.

**Comment by willswordh** [comment]
@cyx
Thanks for helping! The Issue appears as early at the android studio emulator stage, so it is not a device issue. In the emulator on my laptop, the ChatView.kt is broken, all three buttons can't work and the model can't be initiated. I tried to debug in the android studio and found that: {Base$TVMError@30037} Object is being initialized. InternalError: Check failed: (fload_exec.defined()) is false: TVM runtime cannot find vm_load_executable
Stack trace:
  File "/Users/mlc-llm/cpp/llm_chat.cc", line 244"
  Please help me with it, thanks a lot!!!

**Comment by willswordh** [comment]
@cyx-6 For your easier reference, the  "/Users/mlc-llm/cpp/llm_chat.cc", line 236-244 is:
  void Reload(tvm::runtime::Module executable, String model_path, String app_config_json = "") {
    // Step 1. Set tokenizer.
    this->tokenizer_ = TokenizerFromPath(model_path);

    // Step 2. Initialize vm, we use the packed function mechanism
    // so there is no explicit abi dependency on these extra
    // classes other than basic tvm runtime.
    auto fload_exec = executable->GetFunction("vm_load_executable");
    ICHECK(fload_exec.defined()) << "TVM runtime cannot find vm_load_executable";

**Comment by cyx-6** [comment]
This is wierd though. We have never encountered this issue, which is in `llm_chat.cc`. I will check it with team.

**Comment by willswordh** [comment]
@cyx-6 Thank you! I think it might be the issue that hinders the app running on any device based on Android if building from the source through android studio. Maybe could be the changes of repo code in 3rd party or tvm related issue?

**Comment by neelsudhakaran** [comment]
I'm having the same issue. Does it perhaps mean that TVM needs to be installed directly on the Android device or are the JNI  Libraries (`libtvm4j_runtime_packed.so` and the `tvm4j_core.jar`) enough?

And/or does it have any relation to needing to include binaries generated by these two files?
1. `3rdparty/tvm/src/runtime/relax_vm/executable.cc`
1. `3rdparty/tvm/src/runtime/vm/executable.cc`

**Comment by brianjking** [comment]
@cyx-6 Can you point me in the direction of how to get this working on a Pixel 7 Pro?

**Comment by cyx-6** [comment]
@brianjking Sorry, we do not support devices(or simulators) without OpenCL, like Google Pixel. So we cannot get it working currently.

**Comment by Lucyan11** [comment]
Im going to try an experiment and attempt to build the vmtvm right onto the android. Seems easy enough lol face palm.

@cyx-6 have you had any luck with the team?  If it is related to this

3rdparty/tvm/src/runtime/relax_vm/executable.c3rdparty/tvm/src/runtime/vm/executable.cc

Can we just add them and remake?

Ill try and see what happens.

@willswordh @neelsudhakaran any luck fuguring it out,

**Comment by Lucyan11** [comment]
Sorry to double post. But i am pretty sure @neelsudhakaran is right about the bin loading. If its starts to initialize, but then fails to load the bin, it locks up the buttons cause it diesnt pass on to the next logic stream.

**Comment by cyx-6** [comment]
@Lucyan11 Sorry for replying late. Please try new [apk](https://github.com/mlc-ai/binary-mlc-llm-libs/blob/main/mlc-chat.apk).
