### ISSUE TITLE
[Question] other quantization scheme on Android phone

### ISSUE THREAD

**Issue by ChenMnZ** [mlc-ai/mlc-llm#546]
## ❓ General Questions

"I rebuilt Vicuna's weight using the `q4f16_0` and `q3f16_0` quantization schemes, as well as some other quantization schemes, by modifying the `group_size` or `sym`. However, I have noticed that only the `q4f16_0` scheme can run successfully. When using other schemes on an Android phone, the app would report 'Ready to chat', but it would either crash or not reply when I send a message.

The fact that the `q4f16_0` scheme runs successfully confirms the accuracy of my reproduction. Therefore, I would like to determine whether the failure of the other quantization schemes is caused by a bug or if I have overlooked something important.

**Comment by ChenMnZ** [comment]
When I change the `group_size` from '32' to '64', the inference speed becomes more than 10 times slower. 

Is this because the kernel is customized?

**Comment by WashSwang** [comment]
Yes. MLC-LLM customizes kernels (through auto-tuning) for q4f16_0 and q3f16_0 with `group_size` 32 for Android. Modifying the `group_size` will result in falling to a default GPU schedule, which has terrible performance. As announced by the developers, the new default schdule `dlight` is still under development. There will be specific strategies to optimize decode GEMV, related to quantization schemes. It may provide better performance without auto-tuning.

**Comment by MasterJH5574** [comment]
Regarding the performance, we merged dlight into the main branch last week. You can try customize the `group_size` and build again. I suppose with dlight, the performance will be much better than the unoptimized one previously.

**Comment by CharlieFRuan** [comment]
Closing this issue for now due to inactivity. Feel free to reopen or open another issue if there are other questions!
