### ISSUE TITLE
[Question] why OpenLLaMA-7B with quantization mode q4f16_0 output so bad 

### ISSUE THREAD

**Issue by davidjohn001** [mlc-ai/mlc-llm#547]
## ❓ General Questions
I try to chat， but the quantization mode q4f16_0 model by your script output are so bad, so do you have some experience about this?
<img width="287" alt="image" src="https://github.com/mlc-ai/mlc-llm/assets/18191347/01e70d16-0017-446f-a977-a9a8c13fd1ae">

<img width="296" alt="image" src="https://github.com/mlc-ai/mlc-llm/assets/18191347/2bde5159-bb5f-4a1c-ab6a-16b5f58f5ecc">

**Comment by LeiWang1999** [comment]
two probably solutions, firstly, you could modify the q4f16_0 for quantization without using word embeddings and the language model head. Secondly, you might want to try the auto gptq quantization scheme.

**Comment by yzh119** [comment]
Hi @davidjohn001 OpenLLaMA is a base model that hasn't been fine-tuned w/ instruction tuning, so it cannot be used to chat directly.

The default mode for OpenLLaMA is LM mode, which means it will complete a sentence given your prompt (your input is used as a prompt).
The correct usage of base models such as OpenLLaMA was like this:

Your input: I have a dream
model: that one day every valley shall be exalted, every hill and mountain shall be made low, the rough places will be made plain...

Only models that have been fine-tuned by instruction tuning or RLHF can be used for conversation.

**Comment by Hzfengsy** [comment]
As the above replies have already answered your question. I will close this issue. Feel free to reopen it if you have further questions.
