### ISSUE TITLE
[Bug] Error met for the mlc-chat on linux-aarch64? 

### ISSUE THREAD

**Issue by willswordh** [mlc-ai/mlc-llm#556]
I am building the mlc-chat on a linux-aarch64 chip-based device. The last step of it, which is launching the server didn't work: python -m mlc_chat.rest --device-name DEVICE [--quantization QUANTIZATION_MODE] [--device-id DEVICE_ID] [--port PORT] [--artifact-path ARTIFACT_PATH].     The "The device name to run the model. Available options are: metal, cuda, vulkan, cpu", all of the choices can't work out to finish this step. How to solve the is problem? Thanks!!!

**Comment by willswordh** [comment]
Hi, I think the issue could be that there is no "vicuna-v1-7b-q3f16_0-vulkan.so" for cpu version, following from the instruction. The missing  "so" file might block the process of this step. Is there any way you can provide the cpu version of the "so" file? Than ks!!!

**Comment by Hzfengsy** [comment]
CPU is a bit weak for LLMs. Please try to run on GPUs or integrated GPUs
