### ISSUE TITLE
[Feature Request] Enabling the Enter key on an iOS hardware keyboard to send input

### ISSUE THREAD

**Issue by dtimekeeper** [mlc-ai/mlc-llm#578]
## 🚀 Feature
Making the Enter key on a hardware keyboard (Bluetooth, Magic Keyboard folio) attached to an ios device Send the input message instead of having to tap the Send button.

## Motivation

This would greatly increase the natural conversational chat feel of communicating with the LLM instead of having to read up and tap the Send button.

**Comment by cyx-6** [comment]
Thanks for your suggestion! I think #677 has solved this issue?
