### ISSUE TITLE
[Feature Request] Docker container

### ISSUE THREAD

**Issue by saad-palapa** [mlc-ai/mlc-llm#580]
## 🚀 Feature
Docker containers

## Motivation

It will make things easy and quick to setup

## Alternatives

Using conda

## Additional context

[YoloV8's docker features](https://github.com/ultralytics/ultralytics/tree/main/docker) inspire this feature request:

**Comment by yzh119** [comment]
Good idea, I'll help set it up.

**Comment by saad-palapa** [comment]
Thank you! It took me 2 days to get things up and running.

**Comment by jparismorgan** [comment]
> Good idea, I'll help set it up.

Awesome! It looks like someone else tried previously, maybe their work will help you: https://github.com/mlc-ai/mlc-llm/issues/33#issuecomment-1538712250

**Comment by yzh119** [comment]
@jparismorgan thank you for your suggestion, actually, there is no difficulty setting up docker for CUDA, we already prepared a bunch of docker images and scripts for CI/CD in https://github.com/mlc-ai/package.

MLC-LLM targets different backends, so I'm mainly working on docker images that ship AMD GPU drivers. I'll let you know about my progress.

**Comment by junrushao** [comment]
Update: I opened up a repo (https://github.com/junrushao/llm-perf-bench) of dockerfiles to help reproduce cuda performance numbers. The takeaway is: MLC LLM is around 30% faster than Exllama.

I’m not a docker expert and still think docker isn’t always the best way for MLC LLM to demonstrate universal deployment as some drivers may not available in it (Metal/Vulkan), but it does help for cuda cases.
