### ISSUE TITLE
[Question] when support Llama2 on Android 

### ISSUE THREAD

**Issue by davidjohn001** [mlc-ai/mlc-llm#583]
## ❓ General Questions
 when support Llama2 on Android

**Comment by twiceyuan** [comment]
Duplicated of #569

**Comment by CharlieFRuan** [comment]
Llama 2 should be supported as mentioned in https://github.com/mlc-ai/mlc-llm/issues/569.

Closing this issue for now due to inactivity. Feel free to reopen or open a new issue if there are other questions.
