### ISSUE TITLE
[Model Request] [Android] llama2_7b_chat_uncensored by georgesung

### ISSUE THREAD

**Issue by FreeCode4All** [mlc-ai/mlc-llm#586]
## ⚙️  Request New Models

- Link to an existing implementation (e.g. Hugging Face/Github): 
Original: 
georgesung/llama2_7b_chat_uncensored 
https://huggingface.co/georgesung/llama2_7b_chat_uncensored
GGML: 
TheBloke/llama2_7b_chat_uncensored-GGML 
https://huggingface.co/TheBloke/llama2_7b_chat_uncensored-GGML
GPTQ:
TheBloke/llama2_7b_chat_uncensored-GPTQ
https://huggingface.co/TheBloke/llama2_7b_chat_uncensored-GPTQ

- Is this model architecture supported by MLC-LLM?
Yes (it's llama2)

## Additional context

Pls add this model to Android it's 7b and should work like viccuna 7b. This model also doesn't have the problem of denying to kill JavaScript processes like the official llama 2 chat model.

The prompt style is on the Hugging Face page I linked:

```
### HUMAN:
Hello

### RESPONSE:
Hi, how are you?

### HUMAN:
I'm fine.

### RESPONSE:
How can I help you?
...
```

**Comment by Hzfengsy** [comment]
As it's with the same arch as llama-2, you can use the same instruction at [here](https://mlc.ai/mlc-llm/docs/compilation/compile_models.html) but only use a different weight. 

Additionally, there are too many different weights (e.g. official, uncensored, qlora), but we have limited bandwidth and cannot support all of them. We welcome the community to build and upload their own weight while we are focus on the different model arch

**Comment by CharlieRuan0130** [comment]
Hi @FreeCode4All , the prebuilt models for georgesung/llama2_7b_chat_uncensored are added to huggingface:
- https://huggingface.co/mlc-ai/mlc-chat-llama2-7b-chat-uncensored-q4f32_1/tree/main
- https://huggingface.co/mlc-ai/mlc-chat-llama2-7b-chat-uncensored-q4f16_1/tree/main

**Comment by FreeCode4All** [comment]
My last update is that I was able to edit the json to match the prompt style better (according to my understanding) and now the f16 model is the best model I was ever able to run on my phone (it's slow and sometimes crashes but it works). Editing that file without root wasn't trivial since Android limits which apps have access to that folder and it's files but it worked with the right apps.
Again thx to @CharlieFRuan

**Comment by CharlieFRuan** [comment]
Thank you for the updates! Closing this one for now; if any more problems persist, feel free to open a new issue.

**Comment by Re4mer** [comment]
hi @CharlieFRuan
unfortunatly the problem of prompt style of this model has made it almost useless as the AI frequently answers itself.
could you please edit the json file on Hugging Face so that **everyone** can download and use this fantastic model without any issues?
