### ISSUE TITLE
[Bug] Gradio demo not able to found model

### ISSUE THREAD

**Issue by sheldonchiu** [mlc-ai/mlc-llm#587]
Gradio demo cannot found any model.

In gradio.py, It seems the expected model folder structure is different from the current prebuilt model, are there any undocumented step to use the cli model with python?

**Comment by CharlieRuan0130** [comment]
Hi @sheldonchiu! Could you kindly list out the steps to reproduce the error you are seeing? This would help us debug. Thanks!

**Comment by tqchen** [comment]
closing due to inactive status, feel free to open new ones
