### ISSUE TITLE
[Bug]  REST API endpoint broken - `/v1/completions`

### ISSUE THREAD

**Issue by Sing-Li** [mlc-ai/mlc-llm#590]
## 🐛 Bug

With `mlc_chat.rest` running the example program `sample_openai.py`,  server crashes when `/v1/completions` endpoint is invoked by the sample program.

## To Reproduce

1.  set up `mlc_chat.rest` to handle request, I used llama-2 7b f16 model 
2.  run the `sample_openai.py` program (require installing the openai package)
3.  server crashes in the 3rd part of this program when the `/v1/completions`  endpoint returns

```
File "/Users/sam/miniconda3/lib/python3.11/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/Users/sam/miniconda3/lib/python3.11/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
               ^^^^^^^^^^^^^^^^^^^
  File "/Users/sam/miniconda3/lib/python3.11/site-packages/fastapi/routing.py", line 273, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sam/miniconda3/lib/python3.11/site-packages/fastapi/routing.py", line 190, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sam/miniconda3/lib/python3.11/site-packages/mlc_chat/rest.py", line 156, in request_completion
    CompletionResponseChoice(
  File "/Users/sam/miniconda3/lib/python3.11/site-packages/pydantic/main.py", line 150, in __init__
    __pydantic_self__.__pydantic_validator__.validate_python(data, self_instance=__pydantic_self__)
pydantic_core._pydantic_core.ValidationError: 1 validation error for CompletionResponseChoice
finish_reason
  Field required [type=missing, input_value={'index': 0, 'text': "I'm...my best to assist you."}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.0.3/v/missing
```    

## Expected behavior

Example program not to crash, but to print a completion in this 3rd part similar to the first two part.

## Environment

 - Platform  metal
 - Operating system  Mac OS Ventura 13.4.1
 - Device   M2 Mac Mini
 - How you installed MLC-LLM (`conda`, source):  miniconda3 
 - How you installed TVM-Unity (`pip`, source): NA
 - Python version (e.g. 3.10):  3.11.4
 - GPU driver version (if applicable):
 - CUDA/cuDNN version (if applicable):
 - TVM Unity Hash Tag (`python -c "import tvm; print('\n'.join(f'{k}: {v}' for k, v in tvm.support.libinfo().items()))"`, applicable if you compile models):
 - Any other relevant information:

## Additional context

Seems to be in the return value not conforming to class `CompletionResponseChoice`

**Comment by sudeepag** [comment]
Same as https://github.com/mlc-ai/mlc-llm/issues/581. We are putting up a PR to add support for pydantic v2.

**Comment by Sing-Li** [comment]
Awesome thanks.  Will test and confirm with nightly.

**Comment by Sing-Li** [comment]
Verified fixed in Nightly

However as pointed out in #592       The `examples/rest/langchain.py`    now fails.   

It required installation of pydantic less than 2  (which is actually in the comments of the example now)  -
   
`pip install pydantic==1.10.9`
