### ISSUE TITLE
[Question] Llama 2 on iOS questions about response time and Chinese support

### ISSUE THREAD

**Issue by johnnynanjiang** [mlc-ai/mlc-llm#593]
## ❓ General Questions

Great work 

A couple of questions

1. The response sometimes was a bit slow token by token, it happened 2 out of 3 attempts.

```
Some discussions around the issue on Discord
https://discord.com/channels/1108078063931097149/1115389904709492866/1115856591485407313
```

2. It is a known issue that Llama 2 doesn't support Chinese well, is there a plan for better Chinese support by extra training?

Thanks

**Comment by JustLoveBen** [comment]
Better Chinese support:
https://github.com/FlagAlpha/Llama2-Chinese

**Comment by yzh119** [comment]
The MLC-LLM project focuses on deploying LLM, if there is a new Llama2 variant fine-tuned on Chinese corpus, it should be easily deployed using MLC-LLM.

**Comment by CharlieRuan0130** [comment]
Hi @johnnynanjiang, in case you still need it, we uploaded the prebuilt FlagAlpha-llama2-chinese:
- https://huggingface.co/mlc-ai/mlc-chat-FlagAlpha-Llama2-Chinese-7b-Chat-q4f32_1/tree/main
- https://huggingface.co/mlc-ai/mlc-chat-FlagAlpha-Llama2-Chinese-7b-Chat-q4f16_1/tree/main

**Comment by johnnynanjiang** [comment]
> Hi @johnnynanjiang, in case you still need it, we uploaded the prebuilt FlagAlpha-llama2-chinese:
> 
> * https://huggingface.co/mlc-ai/mlc-chat-FlagAlpha-Llama2-Chinese-7b-Chat-q4f32_1/tree/main
> * https://huggingface.co/mlc-ai/mlc-chat-FlagAlpha-Llama2-Chinese-7b-Chat-q4f16_1/tree/main

Thanks a lot @CharlieRuan0130  for following up, great progress 👏
