### ISSUE TITLE
[Bug] Fails to build static lib on Windows. 

### ISSUE THREAD

**Issue by brian-pieces** [mlc-ai/mlc-llm#595]
## 🐛 Bug

Fails to build static lib on Windows. 

## To Reproduce

1. Clone mlc-llm
1. Set `MLC_LLM_INSTALL_STATIC_LIB` to `ON`
1. build with cmake

Building like this results in a long list of "already defined" errors like this:
`error LNK2005: "class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > __cdecl tvm::runtime::Backtrace(void)" (?Backtrace@runtime@tvm@@YA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@XZ) already defined in tvm_runtime.lib(logging.obj) [D:\a\mlc-llm\mlc-llm\build\mlc_chat.vcxproj]`

## Expected behavior

Static dll for mlc chat cli

## Environment

 - Platform (e.g. WebGPU/Vulkan/IOS/Android/CUDA): Vulkan
 - Operating system (e.g. Ubuntu/Windows/MacOS/...): Windows
 - Device (e.g. iPhone 12 Pro, PC+RTX 3090, ...): windows-latest GitHub Actions runner
 - How you installed MLC-LLM (`conda`, source): source
 - How you installed TVM-Unity (`pip`, source): source
 - Python version (e.g. 3.10): 3.11
 - GPU driver version (if applicable):
 - CUDA/cuDNN version (if applicable):
 - TVM Unity Hash Tag (`python -c "import tvm; print('\n'.join(f'{k}: {v}' for k, v in tvm.support.libinfo().items()))"`, applicable if you compile models):
 - Any other relevant information:

## Additional context

No issues with this on Mac and Linux

**Comment by tqchen** [comment]
The static lib option is only used for very limited use-cases like iOS and is not intended for windows build. So unfortunately it is not supported atm
