### ISSUE TITLE
[Question] How to run MLC Chat REST API on CPU without Vulkan

### ISSUE THREAD

**Issue by ZYChimne** [mlc-ai/mlc-llm#598]
## ❓ General Questions

I would like to deploy mlc-chat REST on servers, and I am wondering if it is possible to run llama 2 on CPU only without Vulkan Driver. If this is possible, how do I specify the library when I call ChatModule.reload()?

**Comment by yzh119** [comment]
I think models compiled to `opencl` targets can be executed on CPU. But I have no idea what the performance will be.
