### ISSUE TITLE
[Question] The memory usage on the iOS device is too high.

### ISSUE THREAD

**Issue by alimysoyang** [mlc-ai/mlc-llm#600]
## ❓ General Questions

I used this command to compile the new model, but when running it on the iPhone, after loading the model, the memory usage reached 3.9GB. Performing further operations causes the memory to exceed the limit, leading to a direct crash.

Could anyone please tell me what methods are available to reduce memory usage?

python3 -m mlc_llm.build --model Llama-2-7b-chat-hf --target iphone --max-seq-len 512 --quantization q4f16_1

**Comment by MasterJH5574** [comment]
Hi @alimysoyang, the 4-bit quantization on a 7B model does not keep the memory usage under the 4GB limit. We recommend using the 3-bit quantization mode `q3f16_1` with max sequence length 768 to build for iPhone.
```
python3 -m mlc_llm.build --model Llama-2-7b-chat-hf --target iphone --max-seq-len 768 --quantization q3f16_1
```

**Comment by alimysoyang** [comment]
Hi @MasterJH5574  
Thank you, the quality of q3f16_1 is not as good as q4f16_1, so I wanted to try running it on iOS to see the effect, but the memory usage is too high. Thank you for your help.
