### ISSUE TITLE
[Bug] Error building MLC chat on iOS

### ISSUE THREAD

**Issue by NullCodex** [mlc-ai/mlc-llm#603]
## 🐛 Bug

When building the xCode project on my personal device the build succeeds but when launching the application an Error message saying "Local ID: RedPajama-INCITE-Chat-3B-v1-q4f16_0 already exists". This makes the application unable to store chat states.

#### Update
It looks like if you don't run the step to add the prepackage model then it works.

## To Reproduce

1. Follow steps 1 - 4 in https://mlc.ai/mlc-llm/docs/deploy/ios.html but select the target as your own iPhone
2. Launch the Application
3. The error message is presented

## Expected behavior

The error message should not be present and chat states should be saved.

## Environment

 - Platform (e.g. WebGPU/Vulkan/IOS/Android/CUDA): IOS
 - Operating system (e.g. Ubuntu/Windows/MacOS/...): MacOS
 - Device (e.g. iPhone 12 Pro, PC+RTX 3090, ...: iPhone 13 pro max
 - How you installed MLC-LLM (`conda`, source): conda
 - How you installed TVM-Unity (`pip`, source): source
 - Python version (e.g. 3.10): 3.11
 - GPU driver version (if applicable):
 - CUDA/cuDNN version (if applicable):
 - TVM Unity Hash Tag (`python -c "import tvm; print('\n'.join(f'{k}: {v}' for k, v in tvm.support.libinfo().items()))"`, applicable if you compile models):
 - Any other relevant information:

**Comment by tqchen** [comment]
This error is due to the fact that there is a conflicting local id, if you try to deploy a new model, consider to use a model with a different local id instead
