### ISSUE TITLE
[Bug] error: model_lib/libmodel_android.a(params_shard_75.bin): not an ELF file

### ISSUE THREAD

**Issue by YouCii** [mlc-ai/mlc-llm#605]
## 🐛 Bug

I'm trying build android app but got an error with `error: model_lib/libmodel_android.a(params_shard_75.bin): not an ELF file`  when excuting ./prepare_libs.sh. 
Whats wrong and how to fix it?

## To Reproduce

1. tvm build successful with libtvm_runtime.dylib/libtvm.dylib outputed.
    <img width="1225" alt="image" src="https://github.com/mlc-ai/mlc-llm/assets/17899073/111a4c72-9d3f-45a4-920e-45c067032102">

2. Models downloaded

    <img width="485" alt="image" src="https://github.com/mlc-ai/mlc-llm/assets/17899073/28ba6ade-e501-4e56-bbfa-b8c840067c56">

3. Excute ./prepare_libs.sh and get output message:
```
[ 91%] Building CXX object mlc_llm/tvm/CMakeFiles/tvm_runtime_objs.dir/src/runtime/contrib/sort/sort.cc.o
   Compiling tokenizers-c v0.1.0 (/Users/bytedance/Documents/ai/mlc-llm/3rdparty/tokenizers-cpp/rust)
    Finished release [optimized] target(s) in 2m 23s
[ 91%] Built target tokenizers_c
[ 91%] Linking CXX static library libtokenizers_cpp.a
[ 91%] Built target tokenizers_cpp
[ 91%] Built target tvm_runtime_objs
[ 91%] Linking CXX static library libtvm_runtime.a
You have build static version of the TVM runtime library. Make sure to use --whole-archive when linking it into your project.
[ 91%] Built target tvm_runtime
[100%] Linking CXX static library libmlc_llm.a
[100%] Built target mlc_llm_static
[100%] Building CXX object CMakeFiles/tvm4j_runtime_packed.dir/Users/bytedance/Documents/ai/mlc-llm/3rdparty/tvm/jvm/native/src/main/native/org_apache_tvm_native_c_api.cc.o
[100%] Linking CXX shared library libtvm4j_runtime_packed.so
ld: error: model_lib/libmodel_android.a(params_shard_75.bin): not an ELF file
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
make[3]: *** [libtvm4j_runtime_packed.so] Error 1
make[2]: *** [CMakeFiles/tvm4j_runtime_packed.dir/all] Error 2
make[1]: *** [CMakeFiles/tvm4j_runtime_packed.dir/rule] Error 2
make: *** [tvm4j_runtime_packed] Error 2
```

## Expected behavior

build successful

## Environment

 - Platform (e.g. WebGPU/Vulkan/IOS/Android/CUDA): Mac intel i7, Intel Iris Plus Graphics
 - Operating system (e.g. Ubuntu/Windows/MacOS/...): MacOS
 - Device (e.g. iPhone 12 Pro, PC+RTX 3090, ...)
 - How you installed MLC-LLM (`conda`, source):
 - How you installed TVM-Unity (`pip`, source):
 - Python version (e.g. 3.10):
 - GPU driver version (if applicable): Intel Iris Plus Graphics
 - CUDA/cuDNN version (if applicable): Not ues
 - TVM Unity Hash Tag (`python -c "import tvm; print('\n'.join(f'{k}: {v}' for k, v in tvm.support.libinfo().items()))"`, applicable if you compile models):
 - Any other relevant information:

**Comment by YouCii** [comment]
anyone who can help me 😭

**Comment by Lucyan11** [comment]
I am having the same issue

[100%] Linking CXX shared library libtvm4j_runtime_packed.so
ld: error: model_lib/libmodel_android.a(params_shard_40.bin): not an ELF file
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
make[3]: *** [CMakeFiles/tvm4j_runtime_packed.dir/build.make:104: libtvm4j_runtime_packed.so] Error 1
make[2]: *** [CMakeFiles/Makefile2:251: CMakeFiles/tvm4j_runtime_packed.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:258: CMakeFiles/tvm4j_runtime_packed.dir/rule] Error 2
make: *** [Makefile:203: tvm4j_runtime_packed] Error 2

**Comment by tqchen** [comment]
closing for now, this seems to due to the fact that the libmodel_android.a accidentally packed in `params_shard_40.bin`

Please checkout the latest version and feel free to open a new issue if this problem persists

**Comment by BakingBrains** [comment]
@tqchen facing similar error for the latest commit, any resolution?

```
ld.lld: error: model_lib/libmodel_android.a(._lib0.o): not an ELF file
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
make[3]: *** [CMakeFiles/tvm4j_runtime_packed.dir/build.make:104: libtvm4j_runtime_packed.so] Error 1
make[2]: *** [CMakeFiles/Makefile2:268: CMakeFiles/tvm4j_runtime_packed.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:275: CMakeFiles/tvm4j_runtime_packed.dir/rule] Error 2
make: *** [Makefile:203: tvm4j_runtime_packed] Error 2
```

Thanks.
