### ISSUE TITLE
[Question] Compile quantized models

### ISSUE THREAD

**Issue by NullCodex** [mlc-ai/mlc-llm#606]
## ❓ General Questions

I have been looking at https://mlc.ai/mlc-llm/docs/compilation/compile_models.html which is great btw but one thing I wanted to ask if it's possible to compile a quantized model? Normal model training isn't very widely available but training of different models with qLora with 4bit quantization isn't as bad. I am wondering if it's possible to compile a finetuned/trained quantized model instead.

thanks!

**Comment by yzh119** [comment]
It's a good idea to decouple quantize and compile considering there are many other existing quantization frameworks, and the community has discussion on that before, our current ParameterManager design should be capable of doing that.

cc @junrushao @MasterJH5574

**Comment by NullCodex** [comment]
@yzh119 do you have a link to the ParameterManager design?

**Comment by MasterJH5574** [comment]
There is an ongoing new effort slim-LM to bring nn.Module based quantization e2e, consolidating to https://github.com/mlc-ai/mlc-llm/issues/1157 to track latest status
