### ISSUE TITLE
[Question] MLC-Chat Rest API server: Unable to find *.dylib error (Apple Silicon)

### ISSUE THREAD

**Issue by Jasonnor** [mlc-ai/mlc-llm#608]
## ❓ General Questions

Hello, I'm getting an error `Unable to find *.dylib` while using the Rest API. I didn't find relevant steps in the [documentation](https://mlc.ai/mlc-llm/docs/deploy/rest.html). Am I missing any pre-steps? Thanks!

### Installation Steps

```bash
> pip3.10 install --pre --force-reinstall mlc-ai-nightly mlc-chat-nightly -f https://mlc.ai/wheels
# Verify installation, it works 
> python3.10 -m mlc_chat.rest --help
usage: MLC Chat REST API [-h] [--model MODEL] [--artifact-path ARTIFACT_PATH] [--quantization {q3f16_0,q4f16_0,q4f16_1,q4f32_0,q8f16_0,q0f16,q0f32}] [--device-name DEVICE_NAME] [--device-id DEVICE_ID]
                         [--port PORT]
options:
  -h, --help            show this help message and exit
  --model MODEL
  --artifact-path ARTIFACT_PATH
  --quantization {q3f16_0,q4f16_0,q4f16_1,q4f32_0,q8f16_0,q0f16,q0f32}
  --device-name DEVICE_NAME
  --device-id DEVICE_ID
  --port PORT
```

### Error Message

```bash
> python3.10 -m mlc_chat.rest --device-name metal --port 8000
INFO:     Started server process [89499]
INFO:     Waiting for application startup.
ERROR:    Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/starlette/routing.py", line 677, in lifespan
    async with self.lifespan_context(app) as maybe_state:
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/contextlib.py", line 199, in __aenter__
    return await anext(self.gen)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/mlc_chat/rest.py", line 41, in lifespan
    raise ValueError(
ValueError: Unable to find vicuna-v1-7b-q3f16_0-metal.dylib at dist/vicuna-v1-7b-q3f16_0/vicuna-v1-7b-q3f16_0-metal.dylib or dist/prebuilt/lib/vicuna-v1-7b-q3f16_0-metal.dylib.

ERROR:    Application startup failed. Exiting.
```

**Comment by Hzfengsy** [comment]
Please confirm if you've downloaded the prebuilt lib and model weight. See https://mlc.ai/mlc-llm/docs/get_started/try_out.html

**Comment by Jasonnor** [comment]
@Hzfengsy I have pulled `mlc-chat-Llama-2-7b-chat-hf-q4f16_1` as docs, and `mlc_chat_cli` works fine. 

But the Rest API requires `vicuna-v1-7b-q3f16_0-metal.dylib`, does this mean that I cannot use the Llama 2 model in the Rest API? Thanks!

**Comment by Hzfengsy** [comment]
You need to specify the arguments in the command. Try
`python3.10 -m mlc_chat.rest --model llama-2 --quantization q4f16_1 --device-name metal --port 8000`

**Comment by hongnk** [comment]
I think macos arm should load _metal.so file, just edit rest.py to load .so instead of .dylib

**Comment by Jasonnor** [comment]
@Hzfengsy @hongnk 
Thanks! I modified `rest.py` as follows to make ARM macOS load `.so`:
```python
def _shared_lib_suffix():
    if sys.platform.startswith("linux") or sys.platform.startswith("freebsd"):
        return ".so"
    if sys.platform.startswith("win32"):
        return ".dll"
    if subprocess.check_output(["sysctl", "-n", "machdep.cpu.brand_string"]).decode("utf-8").startswith("Apple"):
        return ".so"
    if sys.platform.startswith("darwin"):
        return ".dylib"
    return ".so"
```

And run:
```
python3.10 -m mlc_chat.rest --model Llama-2-7b-chat-hf --quantization q4f16_1 --device-name metal --port 8000                                     
```

It works now!

Maybe I can open a pull request to add this macOS CPU check, thanks again!

**Comment by Sing-Li** [comment]
@Jasonnor  please do  :pray:  This is broken for me as well ever since nightly update.

**Comment by Jasonnor** [comment]
@Sing-Li Sure! 
I've created a pull request (#617), let's see if this could helps. 🙏

**Comment by tqchen** [comment]
Maybe we should instead tweak to make the Arm metal to also use dyblib file instead, cc @MasterJH5574

**Comment by sudeepag** [comment]
@Jasonnor This should now be handled by the `ChatModule` - https://github.com/mlc-ai/mlc-llm/blob/main/python/mlc_chat/chat_module.py#L355-L371. Please open a new issue if you are still running into it.
