### ISSUE TITLE
[Question] Error building Llama-2-7b-chat-hf for iOS

### ISSUE THREAD

**Issue by NullCodex** [mlc-ai/mlc-llm#611]
## ❓ General Questions

Hi i am trying to experiment with different quantization with the iOS app and one of the experiment is with Llama-2-7b-chat-hf. I was able to get the model to show up on the app but when I tried to select the model to start chatting the app crashes and i see the following error in the xCode debugger

```
InternalError: Check failed: (fload_exec.defined()) is false: TVM runtime cannot find vm_load_executable
```

Here are the steps i took to produce the issue:

1. Downloaded the hugging face model `Llama-2-7b-chat-hf` into the `mlc-llm` directory
2. Activated conda environment
3. Ran `python3 -m mlc_llm.build --model ./Llama-2-7b-chat-hf --target iphone --max-seq-len 768 --quantization q4f16_1` at the root directory
4. `cd ios`
5. Edited `prepare_params.sh` to include the 4bit llama 2 model
6. `./prepare_params.sh`
7. Built the MLCChat xCode project against my personal iPhone

iPhone spec: iPhone 13 pro max

The steps i took works for building 3bit on my own instead but it looks like it crashes with 4bit

**Comment by Hzfengsy** [comment]
First, 4bit 7B models are too large for iPhone (A single app has a 4GB memory limitation by Apple). However, I'm not sure why it will crash during building

**Comment by NullCodex** [comment]
@Hzfengsy It doesn't crash during building it's more that when it's running it crashes with the error message i provided. Regarding the memory limit since iOS 15 doesn't apple allow an app's memory usage to be even greater than the current 5GB limit.

**Comment by gsgoldma** [comment]
doesn't work on my ipad pro with 16gigs of ram either, when downloaded from the mlc huggingface repository with the different models. downloads, but then crashes when submitting the input button

**Comment by Ramees025** [comment]
@junrushao @tqchen @twiceyuan 

I am also getting same error when trying to load llama-2 ,vicuna and RedPajama models in Android Phone with 12 GB RAM and Snapdragon 8 Gen 2 chipset.  (previously, 1 month back, I was able to run at least vicuna model on android)

load model failed.
org.apache.tvm.Base$TVMError: InternalError: Check failed: (fload_exec.defined()) is false: TVM runtime cannot find vm_load_executable
Stack trace:
File "/Users/twiceyuan/Documents/WorkSpace/AndroidLab/mlc-llm/cpp/llm_chat.cc", line 244

It will be helpful if we get some support. Thank you.

**Comment by junrushao** [comment]
@Ramees025 could you actually check if the file `tvm/src/runtime/relax_vm/executable.cc` exists? The function is defined there - otherwise, you are likely using a wrong tvm

**Comment by NullCodex** [comment]
@tqchen i updated the `app-config.json` but it's the same error

**Comment by tqchen** [comment]
likely we also need to call prep_libs.sh that packages the libmodel_iphone.a which takes in the generated module

**Comment by NullCodex** [comment]
same error still i ran `./prepare_libs.sh` and i can see the parameters have been copied over to the `dist` directory via `prepare_params`.

**Comment by tqchen** [comment]
Try to confirm the q3 first since we didn't tested and anticipated q4 would work

**Comment by NullCodex** [comment]
@tqchen i was able to get the q3 version working just fine with the `prepare_params`

**Comment by tqchen** [comment]
did you get the q3 version working through build process?

**Comment by NullCodex** [comment]
yep

**Comment by tqchen** [comment]
ok if the complain is `TVM runtime cannot find vm_load_executable`, then likely something wrong in build, if it just crashes, then we need to still think about the possibility of OOM unfortunately, as we know 4b will exceed what iphone OS normally handle

**Comment by NullCodex** [comment]
@tqchen  i think it's specific for the 4bit quantization i just tested my procedures on the Chinese llama 2 with no issues. Here are the steps i took:

1. Clone the model
2. `python3 -m mlc_llm.build --model ./Chinese-Llama-2-7b --target iphone --max-seq-len 768 --quantization q3f16_1`
3. Edit the `app-config.json`
4. `./prepare_libs.sh`
5. `./prepare_params.sh` - added the model to the list here
6. Built the target against my iPhone

I don't think i am missing any steps for the q4 model since it worked for the 3bit models.

What's the expected memory usages for 4b? I pointed out before that the maximum is 5 but with newer iOS versions you can request more memory. My personal phone is 8g of ram at least

**Comment by tqchen** [comment]
I do not know the expected memory usage as we didn't tested 4b, but if it crashes likely it is a memory issue, I think the usage of 4b likely will be around 6G or so and is really pushing it.  I also had a iphone with 8G ram.  That was why we go with q3 as supported for iOS for now

**Comment by tqchen** [comment]
I also confirmed on my latest iphone max, and it indeed still crashes, so unfortunately we have to go with the officially supported 3b for now.

**Comment by Ramees025** [comment]
@junrushao : I have followed the exact step mentioned here [https://mlc.ai/mlc-llm/docs/deploy/android.html](url). both tvm4j_core.jar and libtvm4j_runtime_packed.so build successfully from source. Any idea how to check the tvm version on Android?

How can i request for updating the apk file in the pre-built apk download link?. 
[https://seeklogo.com/images/D/download-android-apk-badge-logo-D074C6882B-seeklogo.com.png](https://github.com/mlc-ai/binary-mlc-llm-libs/raw/main/mlc-chat.apk)
