### ISSUE TITLE
[Model Request] will 100+B model be supported in near future 

### ISSUE THREAD

**Issue by SaraiQX** [mlc-ai/mlc-llm#616]
## ⚙️  Request New Models
Hi masters from MLC,
I'm so excited to know the 70B llama can run on M2 Max.  Thank you for this wonderful work!
As an apple user, I cannot resist to wonder whether 100+B model(s) could be supported (see 192 M2 Ultra)? 

## Additional context
Bloom 176B is recommended as (probably well-known) they are multi-lingual and open source 😄.
Have seen a relevant request [Model Request] BLOOM model of BigScience #492. 

ps. this will help me decide between M2 Max macbookpro and M2 Ultra studio  (😂 all huge investment after two mbps already)

Great thanks and wish you all the best!
Sarai

**Comment by tqchen** [comment]
closing as BLOOM was not as in need as in latest models, feel free to open a new issue
