### ISSUE TITLE
[Question] in quantization format of the code qAfB(_id), which is mean the GPTQ? _0 , _1, or something else

### ISSUE THREAD

**Issue by davidjohn001** [mlc-ai/mlc-llm#625]
## ❓ General Questions
The format of the code is qAfB(_id), where A represents the number of bits for storing weights and B represents the number of bits for storing activations. **The _id is an integer identifier to distinguish different quantization algorithms (e.g. symmetric, non-symmetric, GPTQ, etc).**

**Comment by Hzfengsy** [comment]
Please see the definition in https://github.com/mlc-ai/mlc-llm/blob/main/mlc_llm/quantization/__init__.py

**Comment by davidjohn001** [comment]
![image](https://github.com/mlc-ai/mlc-llm/assets/18191347/bb234b46-3312-494d-881b-4c707afde17f)

**Comment by Hzfengsy** [comment]
You are right, there is only one support, but feel free to add more :)

**Comment by willswordh** [comment]
@Hzfengsy Hi what is the difference between q4f16_0 and q4f16_1? Is that q4f16_1's transpose=False, whereas q4f16_0's transpose=True? Thanks

**Comment by MasterJH5574** [comment]
@willswordh In `q4f16_0`, the quantized linear layer weights are stored in layout `(K, N)`, and in `q4f16_1`, the quantized linear layer are stored in layout `(N, K)`.

The raw model linear weights from PyTorch/Hugging Face are stored in layout `(N, K)` by default, so when doing `q4f16_0`, we will *transpose* the layout from `(N, K)` to `(K, N)` in quantization, and when doing `q4f16_1` we do not transpose.

**Comment by CharlieFRuan** [comment]
Closing this issue for now due to inactivity. Feel free to reopen this or open a new issue if there are other questions!

**Comment by chenzhenbupt** [comment]
> @willswordh In `q4f16_0`, the quantized linear layer weights are stored in layout `(K, N)`, and in `q4f16_1`, the quantized linear layer are stored in layout `(N, K)`.
> 
> The raw model linear weights from PyTorch/Hugging Face are stored in layout `(N, K)` by default, so when doing `q4f16_0`, we will _transpose_ the layout from `(N, K)` to `(K, N)` in quantization, and when doing `q4f16_1` we do not transpose.

@MasterJH5574 I would like to ask, whether the linear weight is transposed has anything to do with symmetric/asymmetric quantization？Thanks.
