### ISSUE TITLE
[Tracking][iOS][Robustness] Report an Error When model lib does not match packaged model lib

### ISSUE THREAD

**Issue by tqchen** [mlc-ai/mlc-llm#634]
## Overview

When a mlc-chat config request a `model_lib` that is not in the packaged list(as indicated by app-config) we should have a  proper error message. 

## Action Items

- [x] Update iOS app to check for model_lib field in app-config

## Links to Related Isssue

- https://github.com/mlc-ai/mlc-llm/issues/611#issuecomment-1660782883

**Comment by tqchen** [comment]
cc @cyx-6

**Comment by cyx-6** [comment]
Added in #675 together with Android.
