### ISSUE TITLE
[Doc] Would best have more demo on how to load/use model via native Python API

### ISSUE THREAD

**Issue by Chrisz236** [mlc-ai/mlc-llm#635]
### Suggestion
Having a short code demo on using ChatModule to initiate and call for a response.

### Bug
- Link to the buggy documentation/tutorial: https://mlc.ai/mlc-llm/docs/deploy/python.html
- Description of the bug: The "API reference" section. I have been checking the website for native Python API to call and run LLM. Only found the introduction of mlc_chat.ChatModule and its method.

**Comment by tqchen** [comment]
cc @CharlieRuan0130 @Kathryn-cat

**Comment by junrushao** [comment]
Also CC @sudeepag @MasterJH5574 lets get python docs done neat this week!

**Comment by CharlieRuan0130** [comment]
Hi @Chrisz236, thanks for the suggestion! We are having an overhaul on Python API and its documentation this week, and hopefully it will be clearer and more user-friendly afterward.

Meanwhile, you could look at two Jupyter notebooks (runnable on Colab) on the Python API: [Getting Started with ChatModule](https://github.com/mlc-ai/notebooks/blob/main/mlc-llm/tutorial_chat_module_getting_started.ipynb), [Compiling with MLC-LLM in Python](https://github.com/mlc-ai/notebooks/blob/main/mlc-llm/tutorial_compile_llama2_with_mlc_llm.ipynb).

**Comment by Chrisz236** [comment]
> 

Thank you! I will try this.

**Comment by Kathryn-cat** [comment]
Hi @Chrisz236 , thanks for the issue! I've opened up a tracking issue with linked PR to demonstrate our progress. We'll introduce high-level functions for the chat module with getting started examples in the doc as well :)

**Comment by Kathryn-cat** [comment]
Hi @Chrisz236 , we have updated the Python API doc with demos: https://mlc.ai/mlc-llm/docs/deploy/python.html . Let us know if you have any more questions!

**Comment by Kathryn-cat** [comment]
resolved.
