### ISSUE TITLE
[Doc] prebuilt model weights repo not found

### ISSUE THREAD

**Issue by klyap** [mlc-ai/mlc-llm#637]
### Bug
- Link to the buggy documentation/tutorial: https://mlc.ai/mlc-llm/docs/deploy/ios.html#step-2-download-prebuilt-weights-and-library
- Description of the bug: 
This line errors out for me
```
git clone https://huggingface.co/mlc-ai/mlc-chat-RedPajama-INCITE-Chat-3B-v1-q4f16_1
```
with
```
remote: Repository not found
fatal: repository 'https://huggingface.co/mlc-ai/mlc-chat-RedPajama-INCITE-Chat-3B-v1-q4f16_1/' not found
```
### Suggestion
Is the correct command this?
```
git clone https://huggingface.co/mlc-ai/mlc-chat-RedPajama-INCITE-Chat-3B-v1-q4f16_0
```

**Comment by Hzfengsy** [comment]
Likely it's due to https://github.com/mlc-ai/mlc-llm/pull/626.  cc @junrushao 

Background:
1. `q4f16_1` does be much faster than `q4f16_0`, we are moving towards it.
2. We haven't pushed the `q4f16_1` weight and prebuilt libs for now but changed the docs mistakenly.

**Comment by junrushao** [comment]
@Hzfengsy shall we quickly produce a RedPajama q4f16_1 as it's now the recommended layout?

**Comment by tqchen** [comment]
Thanks for the catch, opening https://github.com/mlc-ai/mlc-llm/issues/639 to track the RedPajama update, in the meantime, let us keep docs at the right state, i will send a PR to do this

**Comment by tqchen** [comment]
https://github.com/mlc-ai/mlc-llm/pull/641 should make sure the current docs is at the right state. Thanks @klyap for reporting. Let us followup on #639

**Comment by MasterJH5574** [comment]
Follow up with some update: we have updated the `q4f16_1` prebuilt model libraries and weights to https://github.com/mlc-ai/binary-mlc-llm-libs and https://huggingface.co/mlc-ai. And we updated the documentation accordingly as well. Now the URLs should point to the right repo.
