### ISSUE TITLE
[Question] Binary was created using {relax.Executable} but a loader of that name is not registered. Available loaders are cuda, GraphExecutorFactory, GraphRuntimeFactory. Perhaps you need to recompile with this runtime enabled

### ISSUE THREAD

**Issue by wangxu569** [mlc-ai/mlc-llm#638]
## ❓ General Questions

I migrated the code in mlc-llm/cpp to my project, and after compiling and running, there was such a problem:
**Loading model...
terminate called after throwing an instance of 'tvm::runtime::InternalError'
  what():  [10:37:53] /home/mlc-llm/3rdparty/tvm/src/runtime/library_module.cc:141: Binary was created using {relax.Executable} but a loader of that name is not registered. Available loaders are cuda, GraphExecutorFactory, GraphRuntimeFactory. Perhaps you need to recompile with this runtime enabled.**

However, there will be no such problem when running in the mlc-llm framework, and the loaded model files are the same.

In the mlc-llm/3rdparty/tvm/src/runtime/library_module.cc file, I try to print all the loaders:
In the mlc-llm framework, available loaders include: **metadata, const_loader, metadata_module, VMExecutable, relax.Executable, cuda**

In my program, available loaders include: **cuda, GraphExecutorFactory, GraphRuntimeFactory**

That's the problem, but I don't know how to register these loaders, or is there any other solution?

_By the way, the program I created did not use the method of calling the API in the [mlc-llm/docs/deploy/cli.rst] tutorial, I merged all the c++ code into my program and recompiled_

**Comment by tqchen** [comment]
this is likely you did not link the right version of tvm unity, see some examples in https://mlc.ai/mlc-llm/docs/install/tvm.html, and https://github.com/mlc-ai/relax/tree/befac6c079a80bf66f68aa7a8b661b1d01671430 about the specific version that mlc llm use. A simple alternative is to just reuse the CMakeList in mlc llm

**Comment by wangxu569** [comment]
> this is likely you did not link the right version of tvm unity, see some examples in https://mlc.ai/mlc-llm/docs/install/tvm.html, and https://github.com/mlc-ai/relax/tree/befac6c079a80bf66f68aa7a8b661b1d01671430 about the specific version that mlc llm use. A simple alternative is to just reuse the CMakeList in mlc llm

But the tvm unity linked by my program is the same as the tvm unity linked by mlc-llm

**Comment by WashSwang** [comment]
> By the way, the program I created did not use the method of calling the API in the [mlc-llm/docs/deploy/cli.rst] tutorial, I merged all the c++ code into my program and recompiled

Looks like you try to compile the TVM runtime and other sources into a single object. I think you should check the included `.cc` file in your program. I guess you forgot to include source files under `src/runtime/relax_vm`.

**Comment by tqchen** [comment]
If you try static linking, make sure you link it through whole_archive

**Comment by wangxu569** [comment]
> If you try static linking, make sure you link it through whole archive option, otherwise the symbols can get missing
> 
> see for example https://github.com/mlc-ai/mlc-llm/blob/main/CMakeLists.txt#L126

I have solved it, thanks for your work !

**Comment by MasterJH5574** [comment]
Glad to hear that the issue got resolved :-)

**Comment by guojilei** [comment]
How did you solve the problem? i have same issue with u

**Comment by lixiaolong0424** [comment]
我也遇到了这个问题，方便说下怎么解决的吗？
