### ISSUE TITLE
[Question] How to fix failed installation of MLC-Chat Package? 

### ISSUE THREAD

**Issue by arif599** [mlc-ai/mlc-llm#659]
## ❓ General Questions

This is the command I used to install the package: 
```pip install --pre --force-reinstall mlc-ai-nightly mlc-chat-nightly -f https://mlc.ai/wheels```

When I try to verify installation by running:
```python -c "from mlc_chat import ChatModule; print(ChatModule)"```
and
```python -m mlc_chat.rest --help```

I keep getting 
```Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\arshaik\Desktop\MLC LLM\env\Lib\site-packages\mlc_chat\__init__.py", line 6, in <module>
    from .chat_module import ChatModule
  File "C:\Users\arshaik\Desktop\MLC LLM\env\Lib\site-packages\mlc_chat\chat_module.py", line 7, in <module>
    import tvm
  File "C:\Users\arshaik\Desktop\MLC LLM\env\Lib\site-packages\tvm\__init__.py", line 26, in <module>
    from ._ffi.base import TVMError, __version__, _RUNTIME_ONLY
  File "C:\Users\arshaik\Desktop\MLC LLM\env\Lib\site-packages\tvm\_ffi\__init__.py", line 28, in <module>
    from .base import register_error
  File "C:\Users\arshaik\Desktop\MLC LLM\env\Lib\site-packages\tvm\_ffi\base.py", line 71, in <module>
    _LIB, _LIB_NAME = _load_lib()
                      ^^^^^^^^^^^
  File "C:\Users\arshaik\Desktop\MLC LLM\env\Lib\site-packages\tvm\_ffi\base.py", line 57, in _load_lib
    lib = ctypes.CDLL(lib_path[0], ctypes.RTLD_GLOBAL)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\arshaik\AppData\Local\Programs\Python\Python311\Lib\ctypes\__init__.py", line 376, in __init__
    self._handle = _dlopen(self._name, mode)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
**FileNotFoundError: Could not find module 'C:\Users\user\Desktop\MLC LLM\env\Lib\site-packages\tvm\tvm.dll' (or one of its dependencies). Try using the full path with constructor syntax.**```


Do you guys know how I can fix this? Thanks.

**Comment by junrushao** [comment]
If you are installing inside a conda environment, could you try `conda install zstd` as one of its possible missing dependency?

**Comment by arif599** [comment]
> If you are installing inside a conda environment, could you try `conda install zstd` as one of its possible missing dependency?

I'm using a virtual env in python. 

When I used Conda to install the mlc chat package, I got dependency conflicts: 
`ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.`

**Comment by junrushao** [comment]
Pay extra attention if you are using conda and pip together. You might be using mismatched conda/python/pip which may go wrong

**Comment by arif599** [comment]
I have the same versions on both conda and python. 
Python: 3.11.4
Pip: 23.2.1

Still getting the error :(
![image](https://github.com/mlc-ai/mlc-llm/assets/59244462/03fbaca5-00d6-4693-b3be-1f17d8e65fa4)

**Comment by tqchen** [comment]
I think what Junru meant is that you should install zstd in conda. Then pip install the original package

**Comment by arif599** [comment]
It works now. Thank you @junrushao and @tqchen !

**Comment by tqchen** [comment]
glad it works.

**Comment by fuse94** [comment]
1. download libzstd.dll from: https://www.dll-files.com/libzstd.dll.html
2. extract and rename libzstd.dll to zstd.dll
3. put zstd.dll to `%PYTHON_ROOT%\Lib\site-packages\tvm\`

**Comment by williamcastrillon** [comment]
> 1. download libzstd.dll from: https://www.dll-files.com/libzstd.dll.html
> 2. extract and rename libzstd.dll to zstd.dll
> 3. put zstd.dll to `%PYTHON_ROOT%\Lib\site-packages\tvm\`

please make sure is the 64Bit version! it worked for me!!

**Comment by lapo-luchini** [comment]
On Windows I needed to do this:

`ln /mnt/c/Users/lapo/scoop/apps/zstd/1.5.5/dll/libzstd.dll /mnt/c/Users/lapo/scoop/persist/python/Lib/site-packages/tvm/zstd.dll`
