### ISSUE TITLE
[Bug] Document web is dead

### ISSUE THREAD

**Issue by sleepwalker2017** [mlc-ai/mlc-llm#663]
Get Started with MLC-LLM
Please check our [documentation](https://mlc.ai/mlc-llm/docs/get_started/try_out.html) to start the journey with MLC-LLM.

this link can't be opened.
https://mlc.ai/mlc-llm/docs/get_started/try_out.html

**Comment by MasterJH5574** [comment]
We confirmed that the page is alive. If you’re in China then the documentation page is banned by GFW though, unfortunately.

**Comment by sleepwalker2017** [comment]
> We confirmed that the page is alive. If you’re in China then the documentation page is banned by GFW though, unfortunately.

well... that's a pity.. thank you.

BTW, I notice that masahi have some commits from FasterTransformer llama int4 repo, do you know where the repo is?  Thank you!

**Comment by MasterJH5574** [comment]
> BTW, I notice that masahi have some commits from FasterTransformer llama int4 repo, do you know where the repo is?

Sorry I’m not sure actually. Are you referring to the FastTransformer int4 quantization offloading? If yes you may check out https://github.com/mlc-ai/mlc-llm/pull/661.

**Comment by sleepwalker2017** [comment]
> > BTW, I notice that masahi have some commits from FasterTransformer llama int4 repo, do you know where the repo is?
> 
> Sorry I’m not sure actually. Are you referring to the FastTransformer int4 quantization offloading? If yes you may check out #661.

Seems yes,  I'll check it . thank you!
