### ISSUE TITLE
Model Do Not Respond [Bug] 

### ISSUE THREAD

**Issue by bunnywaffle** [mlc-ai/mlc-llm#665]
## 🐛 Bug

I downloaded the model RedPajamas 3B, but when I try to chat with it, it does not respond.

## Expected behavior

The model should respond to my chat requests.

## Environment

 - Platform (Android):
 - Operating system (e.g. Ubuntu/Windows/MacOS/...):
 - Device (Samsung Galaxy M32)
 - How you installed MLC-LLM (APK):
 - Any other relevant information:

## Additional context

![WhatsApp Image 2023-08-04 at 20 31 12](https://github.com/mlc-ai/mlc-llm/assets/100540808/fc0592cb-2091-4375-873b-2adee993a5e3)

**Comment by sherelynyap** [comment]
I have the same problem using Samsung Galaxy S21+

**Comment by cyx-6** [comment]
Sorry for replying late! Please try new [apk](https://github.com/mlc-ai/binary-mlc-llm-libs/blob/main/mlc-chat.apk). It will show error message for information.

**Comment by sherelynyap** [comment]
`Error message:
InternalError: Check failed: (chat_ != nullptr) is false: Chat is not initialized via reload
Stack trace:
  File "/Users/houbohan/mlc-llm/cpp/llm_chat.cc", line 1301`

Got this error message

**Comment by junrushao** [comment]
@sherelynyap I just tried again but couldn't reproduce this issue with my device. The particular lines you point to is: https://github.com/mlc-ai/mlc-llm/blob/f0b12259b2e5f38c4fc63692cd7298ce81125092/cpp/llm_chat.cc#L1329-L1330, which means the `chat_` field is not initialized yet, but we do already initialize it in the Android app in those lines: https://github.com/mlc-ai/mlc-llm/blob/f0b12259b2e5f38c4fc63692cd7298ce81125092/android/MLCChat/app/src/main/java/ai/mlc/mlcchat/AppViewModel.kt#L477-L483
