### ISSUE TITLE
Cannot send message[Bug] 

### ISSUE THREAD

**Issue by JFlamel** [mlc-ai/mlc-llm#666]
## 🐛 Bug

Only working model is RedPajama; All others, when loaded app says "initializing" and this is it. I'm unable to press "send message" button.

## To Reproduce

1.
1.
1.

## Expected behavior

"Ready to chat" message should appear

## Environment

 - Platform Android):
 - Operating system (e.g. Ubuntu/Windows/MacOS/...):
 - Device (Samsung A53 5G)
 - How you installed MLC-LLM (mlc chat app):
 - How you installed TVM-Unity (`pip`, source):
 - Python version (e.g. 3.10):
 - GPU driver version (if applicable):
 - CUDA/cuDNN version (if applicable):
 - TVM Unity Hash Tag (`python -c "import tvm; print('\n'.join(f'{k}: {v}' for k, v in tvm.support.libinfo().items()))"`, applicable if you compile models):
 - Any other relevant information:

**Comment by twzhyyxwhez31057** [comment]
I have the same problem!

**Comment by suoko** [comment]
Same issue with both models

**Comment by cyx-6** [comment]
Sorry for replying late! Please try new [apk](https://github.com/mlc-ai/binary-mlc-llm-libs/blob/main/mlc-chat.apk). It will show error message for information.
