### ISSUE TITLE
[Question] How to set Class Conversation for BaiChuan Model

### ISSUE THREAD

**Issue by huanyingjun** [mlc-ai/mlc-llm#676]
Dear
I try to run Baichuan Model on MLC-LLM, model is from https://huggingface.co/baichuan-inc/Baichuan-7B
In conv_templates.cc , I add below config
```
Conversation BaichuanDefault() {
  Conversation conv;
  conv.name = "baichuan_default";
  conv.system = "";
  conv.roles = {"USER", "ASSISTANT"};
  conv.messages = {};
  conv.offset = 0;
  conv.separator_style = SeparatorStyle::kSepRoleMsg;
  conv.seps = {"</s>"};
  conv.role_msg_sep = ": ";
  conv.role_empty_sep = ":";
  // TODO(mlc-team): add eos to mlc-chat-config
  // and remove eos from stop token setting.
  conv.stop_tokens = {0};
  conv.stop_str = "</s>";
  conv.add_bos = false;
  return conv;
}
```
But not run well, seems seps, stop_tokens, stop_str not set right, 
Anyone knows how to set this ？

Thanks

**Comment by Kathryn-cat** [comment]
Hi @huanyingjun , seps, stop_tokens, stop_str are specific to each model, and we would suggest looking closely at their codebase to check their behavior. 
https://github.com/baichuan-inc/Baichuan-7B/blob/main/models/modeling_baichuan.py
In MLC-LLM, `seps` refers to the string that acts as separators between dialogs in the conversation history. `stop_tokens` are the tokens that tell the decoding stage to stop if encountering them. `stop_str` acts for similar purpose but in string format.
