### ISSUE TITLE
[Feature Request] Multimodality support (LLAVA)

### ISSUE THREAD

**Issue by JianbangZ** [mlc-ai/mlc-llm#678]
## 🚀 Feature
Multimodality model support (LLAVA)
There has been more and more community interest in the multimodality models, such as LLAVA. LLAVA itself has quite simple architecture: CLIP+projector+LLM.

**Comment by JianbangZ** [comment]
> Woah, why specifically LLaVa? Any plans for InstructBlip or other options?
> 
> Either way, VERY cool. @Kathryn-cat

I think mainly due to it's simpleness. straight matmul projector instead of cross attention etc.

**Comment by JianbangZ** [comment]
> Hey @JianbangZ , thanks for bringing this up! We're bringing in LLaVA support this coming week after some major announcements are finished. We'll also bring a simple Python API that handles multimodality.

Great news.
Will the entire pipeline be able to running on Vulkan or CUDA? perticularly the CLIP visual encoder.

**Comment by JianbangZ** [comment]
@Kathryn-cat Great news! Will the entire pipeline be able to run on Vulkan or CUDA? perticularly the CLIP visual encoder part as LLM already has great Vulkan/CUDA support.

**Comment by saad-palapa** [comment]
Any updates on adding LLaVA to MLC?

**Comment by sam1am** [comment]
Really looking forward to this. Is it still happening?

**Comment by MasterJH5574** [comment]
Hello folks, llava has been supported in #1974 and other followup PRs recently (many thanks to @anibohara2000!!). You are more than welcome to try out, and are welcome to open new issues if there are errors or questions regarding the Llava support.
