### ISSUE TITLE
 Check failed: (__e == VK_SUCCESS) is false: Vulkan Error, code=-9: VK_ERROR_INCOMPATIBLE_DRIVER

### ISSUE THREAD

**Issue by wuyuesong** [mlc-ai/mlc-llm#68]
wsl 22.04 in win11
after mlc_chat_cli command:
![image](https://user-images.githubusercontent.com/56100579/235955651-cb5e031d-d55f-4f2e-a463-0de1adbf381d.png)

**Comment by Lolagatorade** [comment]
Same issue here
