### ISSUE TITLE
[Tracking] Support more OpenAI parameters for chat completion endpoint in REST API

### ISSUE THREAD

**Issue by sudeepag** [mlc-ai/mlc-llm#683]
## Overview
The OpenAI chat completion API currently supports a number of parameters that are not currently supported in the mlc-llm REST API, such as temperature, stop sequences, etc. This issue tracks adding support for these parameters, so that they can be used by downstream dependencies of the REST API, such as Langchain integration.

Note that some parameters may require changes in the underlying chat module or `llm_chat`.

## Action Items
- [x] `temperature`
- [x] `top_p`
- [x] `n`
- [x] `stop`
- [x] `max_tokens`
- [x] `presence_penalty`
- [x] `frequency_penalty`

See the [OpenAI API Reference](https://platform.openai.com/docs/api-reference/chat/create) for details on each of these parameters.

## Links to Related Issues and PRs

- https://github.com/mlc-ai/mlc-llm/issues/596
- https://github.com/mlc-ai/mlc-llm/issues/674
- #1024 
- #1107

**Comment by davidpissarra** [comment]
Concluded by #1107
