### ISSUE TITLE
[Feature Request] Qwen 7B model support 

### ISSUE THREAD

**Issue by JianbangZ** [mlc-ai/mlc-llm#684]
Qwen 7B is reporting impressive numbers for both English and Chinese.
Qwen is similar to Llama model. Need to add bias params for QKV, and change the tokenizer to tiktoken.

**Comment by lindd-zju** [comment]
Qwen is the strongest Chinese large model, and the 14B versions are now available for download. We would like to utilize mlc for inference acceleration and kindly request your support in doing so. Thank you!

**Comment by ZhenyuYangGithub** [comment]
> Qwen is the strongest Open Chinese large model, and the 14B versions is now available for download. MLC-LLM is the fastest inference acceleration solution I have ever used, I hope to utilize mlc for inference acceleration of the model and kindly request your support in doing so.

Have you managed to make Qwen work?

**Comment by CyberTimon** [comment]
Qwen 72b is releasing in 2 days and I really hope Qwen support get's added, as I can't imagine how slow it will be to serve 72b on 2x3090's.. Thanks!

**Comment by alphaarea** [comment]
I noticed that CausalLM just released 72B-preview, which the description says is an uncensored model trained using Qwen's weights.

Most importantly, the config.json of CausalLM/72B-preview states that its architectures is LlamaForCausalLM! same as common llama!

Perhaps until official Qwen-72B support is added, it would be possible to build CausalLM directly on the current version of mlc-llm? Anyone care to try that?

[CausalLM/72B-preview](https://huggingface.co/CausalLM/72B-preview)

**Comment by MrJungle1** [comment]
@JianbangZ @ZhenyuYangGithub @alphaarea @CharlieFRuan @CyberTimon  I see that it has been almost 2 months since everyone requested support for qwen, but there seems to be no new progress. I would like to ask what is the difficulty in supporting qwen. I am a newbie. What knowledge do I need if I want to support qwen? Are you interested in supporting us? I urgently need a model with small parameters and excellent Chinese language capabilities. qwen is the best choice.

**Comment by CharlieFRuan** [comment]
Hi @MrJungle1, apologies for the delayed response. We recently released a tutorial for adding a model here: https://llm.mlc.ai/docs/compilation/define_new_models.html

**Comment by CharlieFRuan** [comment]
Please see the Qwen PR: https://github.com/mlc-ai/mlc-llm/pull/1646; we'll release prebuilts soon

**Comment by CharlieFRuan** [comment]
Prebuilts released on https://huggingface.co/mlc-ai!
