### ISSUE TITLE
Build Android Fail

### ISSUE THREAD

**Issue by twzhyyxwhez31057** [mlc-ai/mlc-llm#691]
Hi, I tried to run ./prepare_libs.sh according to the document, then I got error message:
```
[100%] Built target mlc_llm_static
[100%] Building CXX object CMakeFiles/tvm4j_runtime_packed.dir/Users/majuntian/Work/AliCode/mlc-llm/3rdparty/tvm/jvm/native/src/main/native/org_apache_tvm_native_c_api.cc.o
/xxx/mlc-llm/3rdparty/tvm/jvm/native/src/main/native/org_apache_tvm_native_c_api.cc:232:31: error: cannot initialize a parameter of type 'void **' with an rvalue of type 'JNIEnv **' (aka 'JNIEnv_ **')
    _jvm->AttachCurrentThread(&env, nullptr);
                              ^~~~
/Library/Java/JavaVirtualMachines/jdk-17.jdk/Contents/Home/include/jni.h:1938:37: note: passing argument to parameter 'penv' here
    jint AttachCurrentThread(void **penv, void *args) {
                                    ^
/xxx/mlc-llm/3rdparty/tvm/jvm/native/src/main/native/org_apache_tvm_native_c_api.cc:309:31: error: cannot initialize a parameter of type 'void **' with an rvalue of type 'JNIEnv **' (aka 'JNIEnv_ **')
    _jvm->AttachCurrentThread(&env, nullptr);
                              ^~~~
/Library/Java/JavaVirtualMachines/jdk-17.jdk/Contents/Home/include/jni.h:1938:37: note: passing argument to parameter 'penv' here
    jint AttachCurrentThread(void **penv, void *args) {
                                    ^
2 errors generated.
make[3]: *** [CMakeFiles/tvm4j_runtime_packed.dir/Users/majuntian/Work/AliCode/mlc-llm/3rdparty/tvm/jvm/native/src/main/native/org_apache_tvm_native_c_api.cc.o] Error 1
make[2]: *** [CMakeFiles/tvm4j_runtime_packed.dir/all] Error 2
make[1]: *** [CMakeFiles/tvm4j_runtime_packed.dir/rule] Error 2
make: *** [tvm4j_runtime_packed] Error 2


```

**Comment by qc903113684** [comment]
Edit org_apache_tvm_native_c_api.cc
Make the following changes to the /home/me/mlc-llm/3rdparty/tvm/jvm/native/src/main/native/org_apache_tvm_native_c_api.cc file:

// Callback function
extern "C" int funcInvokeCallback(TVMValue* args, int* typeCodes, int numArgs,
                                  TVMRetValueHandle ret, void* resourceHandle) {
  JNIEnv* env;
  int jniStatus = _jvm->GetEnv(reinterpret_cast<void**>(&env), JNI_VERSION_1_6);
  if (jniStatus == JNI_EDETACHED) {
#ifdef TVM4J_ANDROID
    _jvm->AttachCurrentThread(reinterpret_cast<void**>(&env), nullptr);
#else
    _jvm->AttachCurrentThread(reinterpret_cast<void**>(&env), nullptr);
#endif
  } else {
    CHECK(jniStatus == JNI_OK);
  }
  // rest of code unchanged
}

// Free callback function
extern "C" void funcFreeCallback(void* resourceHandle) {
  JNIEnv* env;
  int jniStatus = _jvm->GetEnv(reinterpret_cast<void**>(&env), JNI_VERSION_1_6);
  if (jniStatus == JNI_EDETACHED) {
#ifdef TVM4J_ANDROID
    _jvm->AttachCurrentThread(reinterpret_cast<void**>(&env), nullptr);
#else
    _jvm->AttachCurrentThread(reinterpret_cast<void**>(&env), nullptr);
#endif
  } else {
    CHECK(jniStatus == JNI_OK);
  }
  env->DeleteGlobalRef(reinterpret_cast<jobject>(resourceHandle));
}

**Comment by vkolgi** [comment]
@twzhyyxwhez31057 Did this change work for you ? Because I am hitting the same issue, however the code change that was posted here didn't work for me. Since you have closed the issue, I am curious how you managed to get it working.
