### ISSUE TITLE
Does it support iPhone 13

### ISSUE THREAD

**Issue by upintheairsheep** [mlc-ai/mlc-llm#70]
Does MLC support the non pro iPhone 13, or do I need to buy more RAM?

**Comment by shiqimei** [comment]
Refer to this [comment](https://github.com/mlc-ai/mlc-llm/issues/15#issuecomment-1529336741). It's not working on iPhone 13 when using `vicuna-v1-7b` which requires at least 4GB ram, which iPhone 13 has total 4GB memory. iPhone 14 has 6GB memory so it's supported.

There's smaller model called `dolly-v2-3b` with poor performance that requires less memory. But the usage instructions are not provided yet.

**Comment by upintheairsheep** [comment]
> Refer to this [comment](https://github.com/mlc-ai/mlc-llm/issues/15#issuecomment-1529336741). It's not working on iPhone 13 when using `vicuna-v1-7b` which requires at least 4GB ram, while iPhone 13 has total 4GB memory. iPhone 14 has 6GB memory so it's supported.
> 
> There's smaller model called `dolly-v2-3b` with poor performance that requires less memory. But the usage instructions are not provided yet.

I don't live in the EU anyways, but I will be sure to consider getting a RAM upgrade on my phone.
