### ISSUE TITLE
[Doc] Speed compare with vllm

### ISSUE THREAD

**Issue by lucasjinreal** [mlc-ai/mlc-llm#709]
## 📚 Documentation

Any docs / link point to speed compare with vllm on GPU?

**Comment by sbelcmu** [comment]
Hi @lucasjinreal as far as I am aware mlc doesn't have any direct comparisons with other tools, but I was able to find [this comparison](https://hamel.dev/notes/llm/inference/03_inference.html) which shows at least some data between several tools (including mlc and vllm).
