### ISSUE TITLE
[Bug] Unsupported gpu architecture 'compute_89'

### ISSUE THREAD

**Issue by Cydia2018** [mlc-ai/mlc-llm#710]
## 🐛 Bug

I got this error while building the model. 

Compilation error:
nvcc fatal   : Unsupported gpu architecture 'compute_89'

I didn't encounter it before. After I commented https://github.com/mlc-ai/mlc-llm/pull/686 , the error was resolved.

**Comment by Hzfengsy** [comment]
What's your cuda version? I guess we are trying to build sm89 while your local nvcc does not support it. 

We should not enable fatbin by default cc @MasterJH5574

**Comment by Hzfengsy** [comment]
The problem should be solved if you upgrade to CUDA 11.8. Meanwhile, we would fix it and turn off by default

**Comment by MasterJH5574** [comment]
Thanks @Cydia2018 for reporting! With #716 we will be good to go.

**Comment by MasterJH5574** [comment]
#716 gets merged. Please open an issue again if the issue persists :-)
