### ISSUE TITLE
[Question] Llama2-Chinese-7b-Chat-q4f16_1-vulkan.dll support please

### ISSUE THREAD

**Issue by athlan20** [mlc-ai/mlc-llm#712]
would you please support "Llama2-Chinese-7b-Chat-q4f16_1-vulkan.dll" ?

**Comment by Hzfengsy** [comment]
I think you can use the llama2 dll,

**Comment by MasterJH5574** [comment]
Refer to https://github.com/mlc-ai/mlc-llm/issues/726#issuecomment-1673990816, I feel right now you can re-clone the `Llama2-Chinese-7b-Chat-q4f16_1` repo and it works with the llama 2 dll.

**Comment by athlan20** [comment]
OK,thanks
