### ISSUE TITLE
[Bug] Threadworker is not executing in when I use the IOS swift API

### ISSUE THREAD

**Issue by LLMUSER** [mlc-ai/mlc-llm#713]
I have successfully compiled the llama 2 7b model and also setup all the required steps for for building the IOS app from source.
I have imported the MLCSwift package and also added all the paths that is path to model that is mlc-llm/dist/prebuilt/lib to library search path in the xcode.
Also I have added these
 -Wl,-all_load
-lmodel_iphone
-lmlc_llm -ltvm_runtime
-Wl,-noall_load
-ltokenizers_cpp
-lsentencepiece
-ltokenizers_c
in the build settings \ other linker flags . I have also added the MLCSwift as a dependency.
But now there no errors in the code but When I run/build the ios app I don't get the output from the LLm , infact the threadworker closure specified in the documentation is not executing , when I debugged the code.
This is my code below.
![Screenshot 2023-08-09 at 2 20 04 PM](https://github.com/mlc-ai/mlc-llm/assets/141007240/f5ca181b-9233-40c0-b9a1-9b29399a8bfb)
Let me know this api would be a very helpul to me

**Comment by omkar806** [comment]
No actually can you share a code template how exactly should I use the threadworker ?

**Comment by omkar806** [comment]
Like all of its attributes

**Comment by scottorly** [comment]
You just need to call `threadWorker.start()`.

**Comment by LLMUSER** [comment]
ohh okay , should I call it before I initialize threadworker.init() ?

**Comment by LLMUSER** [comment]
Hey I have initialized the threadworker.start() , the app builds successfully but when I enter a prompt and feed it to the threadworker the app gets paused and I am directed to this 
![Screenshot 2023-08-10 at 1 56 03 PM](https://github.com/mlc-ai/mlc-llm/assets/141007240/9523a4cb-aee4-49c2-93d4-6dc700da15dd)

umm This is my code where I have initialized threadworker.start()

**Comment by LLMUSER** [comment]
sharing the code.....
![Screenshot 2023-08-10 at 1 56 03 PM](https://github.com/mlc-ai/mlc-llm/assets/141007240/e4bda1bc-4e0d-4bba-afb7-87637df574bf)

**Comment by LLMUSER** [comment]
ummm sorry this is the code 
![Screenshot 2023-08-10 at 1 58 57 PM](https://github.com/mlc-ai/mlc-llm/assets/141007240/c6ab8af9-7b1a-4bee-a0e9-08552c818d75)

**Comment by LLMUSER** [comment]
What is the issue exactly here ?

**Comment by besarism** [comment]
modelPath might be wrong, post your entire error here

**Comment by besarism** [comment]
it might be that it cannot find tokenizer via that path

**Comment by omkar806** [comment]
Umm okay so in modelpath  which path should I exactly give ?

**Comment by scottorly** [comment]
You probably need to add the weights that get copied after running the `prepare_params.sh` to your project bundle then the path would something like "dist/llama2. . ."

**Comment by besarism** [comment]
I think there might be a bug, the app mlcchat crashes when you send a message from your phone, tried to integrate this on another app, I am getting signal SIGABRT
on   `reload_func_(lib, model_path, app_config_json);`

/mlc-llm/cpp/llm_chat.cc:59: Check failed: (std::filesystem::exists(path)) is false: Cannot find tokenizer via path:

**Comment by LLMUSER** [comment]
Hey @scottorly I changed the model path but its still not working ?

**Comment by LLMUSER** [comment]
@besarism exactly the same issue ....

**Comment by LLMUSER** [comment]
Umm I don't know exactly what is the issue but @besarism can share the Screen shot of the code that you have written for your custom application ? for generating the response n all ?

**Comment by LLMUSER** [comment]
Are there any other solutions ?

**Comment by dylanbeadle** [comment]
I got it working.
Suggestions:
- Update modelPath to `let modelPath = Bundle.main.bundlePath + "/dist/mlc-chat-Llama-2-7b-chat-hf-q3f16_1"`
- Make sure `appConfigJson` is `""` - it uses this to override the default model's `mlc-chat-config.json`, but seems to have parse issues

**Comment by omkar806** [comment]
I didn't understand the second point that is should I make a appConfig.json file in the project directory and keep it empty ?

**Comment by dylanbeadle** [comment]
@omkar806 the `mlc-chat-config.json` file is read automatically when you call `chat.reload()` and is the default model configuration. If it is not empty, it will try to do a partial override over the default `mlc-chat-config.json` that comes with the model.

In my tests, trying to pass `mlc-chat-config.json` at `chat.reload()` always results in a crash trying to decode the json, so there could be an issue with the partial chat config overrides. (More exploration needed though)

**Comment by LLMUSER** [comment]
umm okay .. so have you got the swift api working or are you still facing an error ?

**Comment by besarism** [comment]
> I got it working. Suggestions:
> 
>     * Update modelPath to `let modelPath = Bundle.main.bundlePath + "/dist/mlc-chat-Llama-2-7b-chat-hf-q3f16_1"`
> 
>     * Make sure `appConfigJson` is `""` - it uses this to override the default model's `mlc-chat-config.json`, but seems to have parse issues

nice, it does not fully work again, but at least the error message is different now
```Thread 15: EXC_RESOURCE (RESOURCE_TYPE_MEMORY: high watermark memory limit exceeded) (limit=2098 MB)```

looks like app exceeds the memory limit for the process.

**Comment by omkar806** [comment]
Maybe Google or chatgpt can help here

**Comment by dylanbeadle** [comment]
For the memory issue, make sure you have an entitlement file like `MCLChat` project with `com.apple.developer.kernel.increased-memory-limit` set to true.

**Comment by dylanbeadle** [comment]
> umm okay .. so have you got the swift api working or are you still facing an error ?

@LLMUSER it is working. The error only happens if you pass in a chat config file on `chat.reload()`.

**Comment by besarism** [comment]
> For the memory issue, make sure you have an entitlement file like `MCLChat` project with `com.apple.developer.kernel.increased-memory-limit` set to true.

Yep, already have that, still the app can't bear this volume:

```The app “TestRP” on iPhone quit unexpectedly.
Message from debugger: Terminated due to memory issue```


However, a few things to keep in mind:

This entitlement isn't meant for all apps. Only apps that have a genuine need for increased memory (like network extensions) should use it. On top of that if you're planning to submit your app to the App Store, be aware that using this entitlement without a valid reason could lead to your app being rejected.


Even if increased memory limit trick would work, it's still crucial to optimize app's memory usage and ensure that there aren't any memory leaks or unnecessary allocations.

I feel the ios solution can be refactored further

**Comment by dylanbeadle** [comment]
@besarism Agreed.

For reducing memory, maybe use a smaller model? I'm using `mlc-chat-RedPajama-INCITE-Chat-3B-v1-q4f16_0` (I haven't tried `mlc-chat-Llama-2-7b-chat-hf-q3f16_1` yet. Note: I am testing on an iPad Pro with 8 GB of RAM.

Related: I wonder if any of the recent WWDC23 stuff could help reduce the size of the models (and memory requirements) further:
- Optimize machine learning for Metal apps: https://developer.apple.com/videos/play/wwdc2023/10050/
- Use Core ML Tools for machine learning model compression: https://developer.apple.com/videos/play/wwdc2023/10047/

**Comment by tqchen** [comment]
closing for now and hopefully we have resolved the issue, feel free to open new ones
