### ISSUE TITLE
[Question] increase MAX_ALLOWED_SEQUENCE_LENGTH 

### ISSUE THREAD

**Issue by willswordh** [mlc-ai/mlc-llm#720]
## ❓ General Questions

 In the example, the MAX_ALLOWED_SEQUENCE_LENGTH is 768. Can we increase this value to 2048 as the largest token value that vicuna model can take for the context length? Thanks

**Comment by MasterJH5574** [comment]
Hi, for iOS and Android app we use 768 as the max sequence length. This is in the purpose of fitting the model into the tight-budget memory of the mobile phones. For other use cases we build with 128 as the max sequence length.

**Comment by willswordh** [comment]
@MasterJH5574 Hi, thanks for your reply! I am wondering can I increase the token limit to the model's original token limit in the compiling model process? I am running the android version on a device with adequate memory. Thanks!

**Comment by MasterJH5574** [comment]
I see. In this case you can just remove the `--max-seq-len 768` from the model compilation command. For Vicuna I think it will then use 2048 as the max sequence length.

**Comment by willswordh** [comment]
@MasterJH5574 Hi do you know if the vicuna 1.3, 7B model with max 2048 token limit will have longer processing time for a query compared to the same model with 768 token limit?  From my testing, I have the model with max 2048 token limit processing much slower than the one with 768 token limit. Not sure if it should behave like this. Thanks!
