### ISSUE TITLE
Add model for MLC Android App 

### ISSUE THREAD

**Issue by sufeidechabei** [mlc-ai/mlc-llm#725]
## ❓ General Questions
I tried to use the MLC Android app to download the Llama model. Here is the link I use:https://huggingface.co/mlc-ai/mlc-chat-llama2-7b-chat-uncensored-q4f16_1.  It reports add model failed. How to resolve this?

**Comment by jepjoo** [comment]
Try:

https://huggingface.co/mlc-ai/mlc-chat-llama2-7b-chat-uncensored-q4f16_1/resolve/main/

(the last / is necessary too...)

**Comment by JFlamel** [comment]
Doesn't work for me too. After "initializing" it doesn't show "Ready to chat" ; send button stays grey.

**Comment by willswordh** [comment]
> Doesn't work for me too. After "initializing" it doesn't show "Ready to chat" ; send button stays grey.

@JFlamel This problem has been here around at least a month, it seems the MLC team still hasn't solve this important issue. But I heard their old repo was working without this issue.

**Comment by willswordh** [comment]
> Try:
> 
> https://huggingface.co/mlc-ai/mlc-chat-llama2-7b-chat-uncensored-q4f16_1/resolve/main/
> 
> (the last / is necessary too...)
> 
> edit: it downloads the model but for me the model doesn't actually work. Dunno what's up with that.

@jepjoo It is the error that is within the build of the app. This problem has been here around at least a month, it seems the MLC team still hasn't solve this important issue. But I heard their old repo was working without this issue.

**Comment by GameOverFlowChart** [comment]
The official apk doesn't support llama2 yet. The simplest way is it to wait until they release the updated apk.

**Comment by Lucyan11** [comment]
@JFlamel do you know which commit was working?

**Comment by cyx-6** [comment]
Please try the new [apk](https://github.com/mlc-ai/binary-mlc-llm-libs/blob/main/mlc-chat.apk) with llama-2 support.
