### ISSUE TITLE
[Bug] Prebuilt model lib missing

### ISSUE THREAD

**Issue by iseebrowser** [mlc-ai/mlc-llm#726]
It's my first time to use MLC, I want to run "mlc-chat-FlagAlpha-Llama2-Chinese-7b-Chat-q4f16_1", but I failed.
mlc_chat_cli --local-id mlc-chat-FlagAlpha-Llama2-Chinese-7b-Chat-q4f16_1 not work,missing "mlc-chat-FlagAlpha-Llama2-Chinese-7b-Chat-q4f16_1-vulkan.so"

**Comment by CharlieFRuan** [comment]
Hi @iseebrowser, could you check `mlc-chat-FlagAlpha-Llama2-Chinese-7b-Chat-q4f16_1/mlc-chat-config.json` and change `model_lib` to `Llama-2-7b-chat-hf-q4f16_1` and retry? 

Sorry for the inconvenience, will update huggingface accordingly soon.

**Comment by CharlieFRuan** [comment]
Hi @iseebrowser, could you re-clone the huggingface repo and retry? I just modified `mlc-chat-FlagAlpha-Llama2-Chinese-7b-Chat-q4f16_1/mlc-chat-config.json` as there was an error in the `mode_lib`. Sorry for the inconvenience.

**Comment by MasterJH5574** [comment]
Close for now. You can open a new one if the issue persists.
