### ISSUE TITLE
[Bug] Add model failed - Wrong model config and params path in Android app

### ISSUE THREAD

**Issue by sbwww** [mlc-ai/mlc-llm#731]
## 🐛 Bug

The model config and params path defined in [AppViewModel.kt#L38-L39](https://github.com/mlc-ai/mlc-llm/blob/88e6d3e9bb65b4b864834f751743210666ab5047/android/MLCChat/app/src/main/java/ai/mlc/mlcchat/AppViewModel.kt#L38-L39) result in not exist files.

```kt
    companion object {
        const val AppConfigFilename = "app-config.json"
        const val ModelConfigFilename = "mlc-chat-config.json"
        const val ParamsConfigFilename = "ndarray-cache.json"
        const val ModelUrlSuffix = "resolve/main/"
    }
```

Follow the steps of [Build Android Package from Source](https://mlc.ai/mlc-llm/docs/deploy/android.html#id3), the config and params files are stored in `/storage/emulated/0/Android/data/ai.mlc.mlcchat/files/model_name/params`.

However, the Android app would look for these files directly in `/storage/emulated/0/Android/data/ai.mlc.mlcchat/files/model_name`, i.e. `modelDirFile`, ignoring the `params` subfolder.

https://github.com/mlc-ai/mlc-llm/blob/88e6d3e9bb65b4b864834f751743210666ab5047/android/MLCChat/app/src/main/java/ai/mlc/mlcchat/AppViewModel.kt#L233

This issue result in `Add model failed` error.

## To Reproduce

Build a custom model and Android app following [Build Android Package from Source](https://mlc.ai/mlc-llm/docs/deploy/android.html#id3)

## Expected behavior

I guess a refactor on `modelDirFile` is needed.

## Environment

 - Platform (e.g. WebGPU/Vulkan/IOS/Android/CUDA): Android
 - Operating system (e.g. Ubuntu/Windows/MacOS/...): Ubuntu
 - Device (e.g. iPhone 12 Pro, PC+RTX 3090, ...)
 - How you installed MLC-LLM (`conda`, source): conda
 - How you installed TVM-Unity (`pip`, source): pip
 - Python version (e.g. 3.10): 3.9
 - GPU driver version (if applicable):
 - CUDA/cuDNN version (if applicable):
 - TVM Unity Hash Tag (`python -c "import tvm; print('\n'.join(f'{k}: {v}' for k, v in tvm.support.libinfo().items()))"`, applicable if you compile models):
 - Any other relevant information:

## Additional context

I think I can try to fix this issue and open an PR later.

**Comment by cyx-6** [comment]
Sorry for replaying late! Yes, we have dreprecated the subfolder `params`. Please put everything in the same model folder.

**Comment by sbwww** [comment]
> we have deprecated the subfolder `params`.

I'm not sure if other platforms (CLI, IOS, ...) are still using the `params` subfolder. **I tried CLI and it works without any param shards outside `params` subfolder.**

I guess a simple modification will do the job once deprecation of subfolder `params` is confirmed on all platforms.

https://github.com/mlc-ai/mlc-llm/blob/bae37b33034532f9e13e61cf0f9a05a10dec4779/mlc_llm/core.py#L488

change to `args.params_path = os.path.join(args.artifact_path)`

**Comment by cyx-6** [comment]
Oh, sorry for the misleading. Only the iOS and Android deprecated the `params` subfolders, while other platforms keep the same.
