### ISSUE TITLE
[Tracking] Enable verbose message supression

### ISSUE THREAD

**Issue by tqchen** [mlc-ai/mlc-llm#744]
## Overview

For downstream libraries it is helpful to be able to suppress informations. We should by default not show these informations and only show them at a more verbose level

## Action Items

- [ ] Move the python side loading to logging.info, which by default should not appear unless logging is enabled.
- [ ] Remove the metal, opencl, vulkan driver initialization `LOG(INFO)` (consider move to DLOG that are not enabled by default)

## Links to Related Issues and PRs

- https://github.com/mlc-ai/mlc-llm/issues/740

**Comment by tqchen** [comment]
cc @CharlieFRuan @Kathryn-cat on python ChatModule size

**Comment by tqchen** [comment]
cc @junrushao @Hzfengsy on the tvm driver initialization

**Comment by Hzfengsy** [comment]
Metal initialization message removed in https://github.com/apache/tvm/pull/15543. Vulkan and OpenCL messages comes from the driver instead of TVM runtime, which is hard to remove
