### ISSUE TITLE
Add sm70 support

### ISSUE THREAD

**Issue by Daryl149** [mlc-ai/mlc-llm#747]
## 🚀 Feature
Support for V100 and V100S GPUs which have compute capability sm70 (7.0)

## Motivation

Newer GPUs (A100 and newer) are scarce and hard to get, so adding support for sm70 would allow us to make better use of the available resources.

## Alternatives

Currently using transformers with bitsandbytes in 4bit for 4x V100S. For 0-2000 tokens context questions, it averages 2.5 tokens per second on llama-2-70b. For 3500 tokens context, it averages 0.5 tokens per second, rendering them practically useless for long context in a chat context. 
Going by the benchmarks by https://hamel.dev/notes/llm/inference/03_inference.html, mlc could make that 1.5 tokens per second, which is the difference between useless and useful.

## Additional context
```
python -m mlc_llm.build --model /my_local_path/models/Llama-2-70b-chat-hf --target cuda --quantization q4f16_1 --max-seq-len 4096
#returns this helpful error:

  File "/mlc_test/venv_1/lib/python3.10/site-packages/tvm/contrib/cutlass/build.py", line 981, in profile_relax_function
    conv2d_profiler = CutlassConv2DProfiler(sm, _get_cutlass_path(), tmp_dir)
  File "/mlc_test/venv_1/lib/python3.10/site-packages/tvm/contrib/cutlass/gen_conv2d.py", line 186, in __init__
    self.gemm_profiler = CutlassGemmProfiler(sm, cutlass_path, binary_path)
  File "/mlc_test/venv_1/lib/python3.10/site-packages/tvm/contrib/cutlass/gen_gemm.py", line 197, in __init__
    assert sm in GENERATOR_FUNC_TABLE and sm in DEFAULT_KERNELS, f"sm{sm} not supported yet."
AssertionError: sm70 not supported yet.


```

**Comment by Hzfengsy** [comment]
That's because cutlass does not support `sm70`, you can try to disable cutlass by adding `--no-cutlass-attn --no-cutlass-norm` to the building command

BTW, MLC-LLM does not support distributed/multi-GPUs for now (which is on our roadmap), so it's hard to run 70B model on V100 cards.

**Comment by Daryl149** [comment]
Ahh, that would be the next and larger barrier then. Thanks for letting me know.

**Comment by sleepwalker2017** [comment]
@Hzfengsy hello, Does it affect the performance when disabling cutlass? thank you!
