### ISSUE TITLE
Does mlc only compile huggingface models?

### ISSUE THREAD

**Issue by armsp** [mlc-ai/mlc-llm#750]
I have the original Llama 2 model (not huggingface ones). When I try to compile the model using - 
```python3 -m mlc_llm.build --model llama-2-7b-chat --target cuda --quantization q4f16_1```
I get the following error -
```
❯ python3 -m mlc_llm.build --model llama-2-7b-chat --target cuda --quantization q4f16_1
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/---/mlc-llm/mlc_llm/build.py", line 13, in <module>
    main()
  File "/home/---/mlc-llm/mlc_llm/build.py", line 9, in main
    parsed_args = core._parse_args(parsed_args)  # pylint: disable=protected-access
  File "/home/---/mlc-llm/mlc_llm/core.py", line 245, in _parse_args
    parsed = _setup_model_path(parsed)
  File "/home/---/mlc-llm/mlc_llm/core.py", line 283, in _setup_model_path
    validate_config(args.model_path)
  File "/home/---/mlc-llm/mlc_llm/core.py", line 318, in validate_config
    assert os.path.exists(
AssertionError: Expecting HuggingFace config, but file not found: dist/models/llama-2-7b-chat/config.json.
```
Is it not supposed to be used with the original model? Or am I missing something trivial?

**Comment by BarfingLemurs** [comment]
@armsp assume so. meta has converted them to hf here: https://huggingface.co/meta-llama/Llama-2-7b-chat-hf

**Comment by Hzfengsy** [comment]
Huggingface config provides useful information, e.g. the model size, tokenizers, and stop tokens. Technically, the Huggingface config is not necessary for MLC-LLM, while the config information is. You have to modify the code to specify this information manually if you persist to use the original model (which may be hard), we encourage you to use HF models for better UX

**Comment by armsp** [comment]
@Hzfengsy thats useful information. I did manage to get HF model working. However, I would also like to know how to get the original model working too. I am willing to make a PR to make the documentation better if you could point me in the right direction on how to also get the original model working i.e how and where to provide those config information you just mentioned.

**Comment by Hzfengsy** [comment]
I don't know what the original model look like, but I'd love to share all information that is required by MLC-LLM:
1. model arch information config.json
    Different model arch needs different info, taking llama as an example: we use HF config to create our own config https://github.com/mlc-ai/mlc-llm/blob/94e0109d78517a9df4ae7354f1da1ac4190a5c1d/mlc_llm/relax_model/llama.py#L843-L847
3. Tokenizer and its config
    https://github.com/mlc-ai/mlc-llm/blob/94e0109d78517a9df4ae7354f1da1ac4190a5c1d/mlc_llm/utils.py#L256-L270

I guess those are all information we use from HF
