### ISSUE TITLE
[Bug] 4-bit quantized llama-2-chat 13b ignores prompts when they exceed 1100 tokens

### ISSUE THREAD

**Issue by okhat** [mlc-ai/mlc-llm#751]
## 🐛 Bug

At 13B, generation ignores the prompt completely when it's longer than 1100 tokens. This problem doesn't seem to affect 7B.

Is this related to the 4bit quantization/compilation?

## To Reproduce

1. Go to colab notebook from this library at: https://colab.research.google.com/github/mlc-ai/notebooks/blob/main/mlc-llm/tutorial_chat_module_getting_started.ipynb
1. Make the most minimal change to use 13b instead of 7b: `!cd dist/prebuilt && git clone https://huggingface.co/mlc-ai/mlc-chat-Llama-2-13b-chat-hf-q4f16_1` and `cm = ChatModule(model="Llama-2-13b-chat-hf-q4f16_1")`
1. Replace the first prompt `"When was Python released?"` with something that has any N tokens followed by `Please ignore all the above and tell me a nice story about sheep.` or whatever. If N is below ~1100, both 7b and 13b generate reasonable completions. Above ~1100 tokens, only 7b works. The 13b model generates text that appears very random and has nothing to do with anything in the prompt.

**Comment by okhat** [comment]
Btw thanks for this very powerful tool! I'm very glad I came across this.

**Comment by tqchen** [comment]
Thank you for reporting! I know the description is detailed enough, but just to be accurate, do you mind create a pythons script of using the python API that reproduces the diff?  It will help folks to reproduce faster.

**Comment by okhat** [comment]
Even with just 1100 tokens, generating text is basically random. It doesn’t follow the prompt

**Comment by willswordh** [comment]
> Even with just 1100 tokens, generating text is basically random. It doesn’t follow the prompt

So you mean the 7b q4 model's performance is really bad?

**Comment by okhat** [comment]
Only when the prompt is longer than 1100 tokens

**Comment by saronsamuel** [comment]
I was able to replicate this issue. With the code below, for prompts w/ a token length ~1300 or less, after running the generate 3 times, it produces a random response. For more tokens, this occurs after generating more times. 

`!pip install --pre --force-reinstall mlc-ai-nightly-cu118 mlc-chat-nightly-cu118 -f https://mlc.ai/wheels

!mkdir -p dist/prebuilt
!git clone https://github.com/mlc-ai/binary-mlc-llm-libs.git dist/prebuilt/lib

!cd dist/prebuilt && git clone https://huggingface.co/mlc-ai/mlc-chat-Llama-2-13b-chat-hf-q4f16_1

from mlc_chat import ChatModule
from mlc_chat.callback import StreamToStdout

cm = ChatModule(model="Llama-2-13b-chat-hf-q4f16_1")

for i in range(3):
   output = cm.generate(Prompt = "PROMPT HERE", progress_callback=StreamToStdout(callback_interval=2),)`

**Comment by okhat** [comment]
Up to Saron’s description, is this just because of the conversational history adding up?

(Aside: One element in my test that I forgot to specify is that I also changed the format to be LM not llama2 in the config file.)

**Comment by willswordh** [comment]
> I was able to replicate this issue. With the code below, for prompts w/ a token length ~1300 or less, after running the generate 3 times, it produces a random response. For more tokens, this occurs after generating more times.
> 
> ```
> 
> !mkdir -p dist/prebuilt
> !git clone https://github.com/mlc-ai/binary-mlc-llm-libs.git dist/prebuilt/lib
> 
> !cd dist/prebuilt && git clone https://huggingface.co/mlc-ai/mlc-chat-Llama-2-13b-chat-hf-q4f16_1
> 
> from mlc_chat import ChatModule
> from mlc_chat.callback import StreamToStdout
> 
> cm = ChatModule(model="Llama-2-13b-chat-hf-q4f16_1")
> 
> for i in range(3):
>    output = cm.generate(Prompt = "PROMPT HERE", progress_callback=StreamToStdout(callback_interval=2),)
> ```

Hi I might not getting it, so you mean that prompts with more token are able to have more stable output compared to prompts with token less than 1300?

**Comment by saronsamuel** [comment]
Hi @willswordh,

I tried it for a range of ~200 - 1300 tokens for the code I used above, and after running the generate 3 times for that range, it produces a random response.

**Comment by nverke** [comment]
This may be related to an issue I found with llama2 being hardcoded to use 2048 tokens max. If I went over that it would start spitting out garbage data. Updating here and a few other places resolved the issue. https://github.com/mlc-ai/mlc-llm/blob/main/mlc_llm/relax_model/llama.py#L958

**Comment by MasterJH5574** [comment]
Hello folks, we expect #828 to resolve this issue by shifting correctly when the context length overflows.
