### ISSUE TITLE
[Model Request] LLaMA-2-7B-32K

### ISSUE THREAD

**Issue by simonw** [mlc-ai/mlc-llm#755]
## ⚙️  Request New Models

- Link to an existing implementation (e.g. Hugging Face/Github): https://huggingface.co/togethercomputer/LLaMA-2-7B-32K
- Is this model architecture supported by MLC-LLM? Yes, Llama 2

## Additional context

https://together.ai/blog/llama-2-7b-32k

**Comment by yzh119** [comment]
Hi @simonw , thank you for bringing this up, @cyx-6 and I are working on this.

**Comment by tqchen** [comment]
closing for now as llama models are superseded by llama3 variants
