### ISSUE TITLE
[Bug] unable to build: _pickle.UnpicklingError: invalid load key, 'v'.

### ISSUE THREAD

**Issue by suhjohn** [mlc-ai/mlc-llm#756]
## To Reproduce

Dockerfile
```
FROM runpod/pytorch:2.0.1-py3.10-cuda11.8.0-devel

WORKDIR /
RUN pip install --pre --force-reinstall mlc-ai-nightly-cu118 mlc-chat-nightly-cu118 -f https://mlc.ai/wheels
RUN git clone https://github.com/mlc-ai/mlc-llm.git --recursive
RUN cd mlc-llm; pip install .
ARG MODEL="Austism/chronos-hermes-13b-v2"
ENV MODEL=$MODEL
RUN python -m mlc_llm.build --hf-path $MODEL --target cuda --quantization q4f16_1

```
Fails on the last step. I've tried three different Llama-2 derivative models and they all seem to fail. 

## Expected behavior

It should build. 

## Environment

 - Platform (e.g. WebGPU/Vulkan/IOS/Android/CUDA):
     - Running on RTX6000 CUDA
 - Operating system (e.g. Ubuntu/Windows/MacOS/...):
     - Ubuntu
 - Device (e.g. iPhone 12 Pro, PC+RTX 3090, ...)
 - How you installed MLC-LLM (`conda`, source):
     - Included in the script
 - How you installed TVM-Unity (`pip`, source):
     - Included in the script
 - Python version (e.g. 3.10):
     - 3.9.16
 - GPU driver version (if applicable):
 ```
root@234e2df8eb03:/mlc-llm# nvidia-smi
Tue Aug 15 00:48:33 2023
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 530.30.02              Driver Version: 530.30.02    CUDA Version: 12.1     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                  Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf            Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA RTX A4000                On | 00000000:00:0C.0 Off |                  Off |
| 41%   29C    P8               13W / 140W|      1MiB / 16376MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+

+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|  No running processes found                                                           |
+---------------------------------------------------------------------------------------+ ```
 - CUDA/cuDNN version (if applicable):
```
root@234e2df8eb03:/mlc-llm# dpkg -l | grep cuda
ii  cuda-cccl-11-8                  11.8.89-1                               amd64        CUDA CCCL
ii  cuda-command-line-tools-11-8    11.8.0-1                                amd64        CUDA command-line tools
ii  cuda-compat-11-8                520.61.05-1                             amd64        CUDA Compatibility Platform
ii  cuda-compiler-11-8              11.8.0-1                                amd64        CUDA compiler
ii  cuda-cudart-11-8                11.8.89-1                               amd64        CUDA Runtime native Libraries
ii  cuda-cudart-dev-11-8            11.8.89-1                               amd64        CUDA Runtime native dev links, headers
ii  cuda-cuobjdump-11-8             11.8.86-1                               amd64        CUDA cuobjdump
ii  cuda-cupti-11-8                 11.8.87-1                               amd64        CUDA profiling tools runtime libs.
ii  cuda-cupti-dev-11-8             11.8.87-1                               amd64        CUDA profiling tools interface.
ii  cuda-cuxxfilt-11-8              11.8.86-1                               amd64        CUDA cuxxfilt
ii  cuda-driver-dev-11-8            11.8.89-1                               amd64        CUDA Driver native dev stub library
ii  cuda-gdb-11-8                   11.8.86-1                               amd64        CUDA-GDB
ii  cuda-keyring                    1.1-1                                   all          GPG keyring for the CUDA repository
ii  cuda-libraries-11-8             11.8.0-1                                amd64        CUDA Libraries 11.8 meta-package
ii  cuda-libraries-dev-11-8         11.8.0-1                                amd64        CUDA Libraries 11.8 development meta-package
ii  cuda-memcheck-11-8              11.8.86-1                               amd64        CUDA-MEMCHECK
ii  cuda-minimal-build-11-8         11.8.0-1                                amd64        Minimal CUDA 11.8 toolkit build packages.
ii  cuda-nsight-compute-11-8        11.8.0-1                                amd64        NVIDIA Nsight Compute
ii  cuda-nvcc-11-8                  11.8.89-1                               amd64        CUDA nvcc
ii  cuda-nvdisasm-11-8              11.8.86-1                               amd64        CUDA disassembler
ii  cuda-nvml-dev-11-8              11.8.86-1                               amd64        NVML native dev links, headers
ii  cuda-nvprof-11-8                11.8.87-1                               amd64        CUDA Profiler tools
ii  cuda-nvprune-11-8               11.8.86-1                               amd64        CUDA nvprune
ii  cuda-nvrtc-11-8                 11.8.89-1                               amd64        NVRTC native runtime libraries
ii  cuda-nvrtc-dev-11-8             11.8.89-1                               amd64        NVRTC native dev links, headers
ii  cuda-nvtx-11-8                  11.8.86-1                               amd64        NVIDIA Tools Extension
ii  cuda-profiler-api-11-8          11.8.86-1                               amd64        CUDA Profiler API
ii  cuda-sanitizer-11-8             11.8.86-1                               amd64        CUDA Sanitizer
ii  cuda-toolkit-11-8-config-common 11.8.89-1                               all          Common config package for CUDA Toolkit 11.8.
ii  cuda-toolkit-11-config-common   11.8.89-1                               all          Common config package for CUDA Toolkit 11.
ii  cuda-toolkit-config-common      12.2.53-1                               all          Common config package for CUDA Toolkit.
hi  libnccl-dev                     2.15.5-1+cuda11.8                       amd64        NVIDIA Collective Communication Library (NCCL) Development Files
hi  libnccl2                        2.15.5-1+cuda11.8                       amd64        NVIDIA Collective Communication Library (NCCL) Runtime
```
 - TVM Unity Hash Tag (`python -c "import tvm; print('\n'.join(f'{k}: {v}' for k, v in tvm.support.libinfo().items()))"`, applicable if you compile models):
```
GIT_COMMIT_HASH: 9fc619d0fdf1719c9e85fdaddf75770935895314
```
 - Any other relevant information:

## Additional context

<!-- Add any other context about the problem here. -->

**Comment by tqchen** [comment]
thank you for reporting, can you include the python stack trace?

**Comment by suhjohn** [comment]
```root@e2fb746ddb84:/mlc-llm# python -m mlc_llm.build --hf-path $MODEL --target cuda --quantization q4f16_1
Weights exist at dist/models/chronos-hermes-13b-v2, skipping download.
Using path "dist/models/chronos-hermes-13b-v2" for model "chronos-hermes-13b-v2"
Target configured: cuda -keys=cuda,gpu -arch=sm_80 -max_num_threads=1024 -max_shared_memory_per_block=49152 -max_threads_per_block=1024 -registers_per_block=65536 -thread_warp_size=32
Automatically using target for weight quantization: cuda -keys=cuda,gpu -arch=sm_80 -max_num_threads=1024 -max_shared_memory_per_block=49152 -max_threads_per_block=1024 -registers_per_block=65536 -thread_warp_size=32
Start computing and quantizing weights... This may take a while.
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/mlc-llm/mlc_llm/build.py", line 13, in <module>
    main()
  File "/mlc-llm/mlc_llm/build.py", line 10, in main
    core.build_model_from_args(parsed_args)
  File "/mlc-llm/mlc_llm/core.py", line 559, in build_model_from_args
    new_params = utils.convert_weights(param_manager, params, args)
  File "/mlc-llm/mlc_llm/utils.py", line 224, in convert_weights
    vm["transform_params"]()
  File "tvm/_ffi/_cython/./packed_func.pxi", line 331, in tvm._ffi._cy3.core.PackedFuncBase.__call__
  File "tvm/_ffi/_cython/./packed_func.pxi", line 262, in tvm._ffi._cy3.core.FuncCall
  File "tvm/_ffi/_cython/./packed_func.pxi", line 251, in tvm._ffi._cy3.core.FuncCall3
  File "tvm/_ffi/_cython/./base.pxi", line 181, in tvm._ffi._cy3.core.CHECK_CALL
tvm._ffi.base.TVMError: Traceback (most recent call last):
  6: TVMFuncCall
  5: tvm::runtime::relax_vm::VirtualMachineImpl::InvokeClosurePacked(tvm::runtime::ObjectRef const&, tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*)
  4: tvm::runtime::PackedFuncObj::Extractor<tvm::runtime::PackedFuncSubObj<tvm::runtime::relax_vm::VirtualMachineImpl::GetClosureInternal(tvm::runtime::String const&, bool)::{lambda(tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*)#1}> >::Call(tvm::runtime::PackedFuncObj const*, tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*)
  3: tvm::runtime::relax_vm::VirtualMachineImpl::InvokeBytecode(long, std::vector<tvm::runtime::TVMRetValue, std::allocator<tvm::runtime::TVMRetValue> > const&)
  2: tvm::runtime::relax_vm::VirtualMachineImpl::RunLoop()
  1: tvm::runtime::relax_vm::VirtualMachineImpl::RunInstrCall(tvm::runtime::relax_vm::VMFrame*, tvm::runtime::relax_vm::Instruction)
  0: tvm::runtime::PackedFuncObj::Extractor<tvm::runtime::PackedFuncSubObj<TVMFuncCreateFromCFunc::{lambda(tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*)#2}> >::Call(tvm::runtime::PackedFuncObj const*, tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*) [clone .cold]
  File "tvm/_ffi/_cython/./packed_func.pxi", line 56, in tvm._ffi._cy3.core.tvm_callback
  File "/mlc-llm/mlc_llm/relax_model/param_manager.py", line 564, in get_item
    load_torch_params_from_bin(torch_binname)
  File "/mlc-llm/mlc_llm/relax_model/param_manager.py", line 524, in load_torch_params_from_bin
    torch_params = torch.load(
  File "/usr/local/lib/python3.10/dist-packages/torch/serialization.py", line 815, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/usr/local/lib/python3.10/dist-packages/torch/serialization.py", line 1033, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, 'v'.```

**Comment by suhjohn** [comment]
@tqchen

**Comment by Hzfengsy** [comment]
It is likely the derivative models use different weight names in their pytorch definition. Could you please check if you can build the original llama on your end? If so, that's the naming issue.

**Comment by suhjohn** [comment]
Where might I be able to find whether the model uses different weight names? FYI this is the model that I'm interested in: https://huggingface.co/Austism/chronos-hermes-13b-v2/tree/main

**Comment by berataydin** [comment]
Same error in here, Metal_x86_64 even model from documentation gives same error 

python3 -m mlc_llm.build --hf-path togethercomputer/RedPajama-INCITE-Chat-3B-v1 --target metal_x86_64 --quantization q4f16_1
git: 'lfs' is not a git command. See 'git --help'.

The most similar command is
	log
Cloning into 'dist/models/RedPajama-INCITE-Chat-3B-v1'...
remote: Enumerating objects: 75, done.
remote: Counting objects: 100% (22/22), done.
remote: Compressing objects: 100% (8/8), done.
remote: Total 75 (delta 20), reused 14 (delta 14), pack-reused 53
Unpacking objects: 100% (75/75), 601.14 KiB | 1.35 MiB/s, done.
Downloaded weights to dist/models/RedPajama-INCITE-Chat-3B-v1
Using path "dist/models/RedPajama-INCITE-Chat-3B-v1" for model "RedPajama-INCITE-Chat-3B-v1"
Target configured: metal -keys=metal,gpu -max_function_args=31 -max_num_threads=256 -max_shared_memory_per_block=32768 -max_threads_per_block=256 -thread_warp_size=1
[12:38:49] /Users/runner/work/package/package/tvm/src/runtime/metal/metal_device_api.mm:167: Intializing Metal device 0, name=AMD Radeon Pro 5500M
[12:38:49] /Users/runner/work/package/package/tvm/src/runtime/metal/metal_device_api.mm:167: Intializing Metal device 1, name=Intel(R) UHD Graphics 630
Host CPU dection:
  Target triple: x86_64-apple-darwin22.6.0
  Process triple: x86_64-apple-darwin22.6.0
  Host CPU: skylake
Automatically using target for weight quantization: metal -keys=metal,gpu -max_function_args=31 -max_num_threads=256 -max_shared_memory_per_block=32768 -max_threads_per_block=1024 -thread_warp_size=32
Start computing and quantizing weights... This may take a while.
Traceback (most recent call last):
  File "/Users/berataydin/anaconda3/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Users/berataydin/anaconda3/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/Users/berataydin/mlc-llm/mlc_llm/build.py", line 13, in <module>
    main()
  File "/Users/berataydin/mlc-llm/mlc_llm/build.py", line 10, in main
    core.build_model_from_args(parsed_args)
  File "/Users/berataydin/mlc-llm/mlc_llm/core.py", line 559, in build_model_from_args
    new_params = utils.convert_weights(param_manager, params, args)
  File "/Users/berataydin/mlc-llm/mlc_llm/utils.py", line 227, in convert_weights
    vm["transform_params"]()
  File "tvm/_ffi/_cython/./packed_func.pxi", line 331, in tvm._ffi._cy3.core.PackedFuncBase.__call__
  File "tvm/_ffi/_cython/./packed_func.pxi", line 262, in tvm._ffi._cy3.core.FuncCall
  File "tvm/_ffi/_cython/./packed_func.pxi", line 251, in tvm._ffi._cy3.core.FuncCall3
  File "tvm/_ffi/_cython/./base.pxi", line 181, in tvm._ffi._cy3.core.CHECK_CALL
tvm._ffi.base.TVMError: Traceback (most recent call last):
  File "tvm/_ffi/_cython/./packed_func.pxi", line 56, in tvm._ffi._cy3.core.tvm_callback
  File "/Users/berataydin/mlc-llm/mlc_llm/relax_model/param_manager.py", line 564, in get_item
    load_torch_params_from_bin(torch_binname)
  File "/Users/berataydin/mlc-llm/mlc_llm/relax_model/param_manager.py", line 524, in load_torch_params_from_bin
    torch_params = torch.load(
  File "/Users/berataydin/anaconda3/lib/python3.10/site-packages/torch/serialization.py", line 815, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/Users/berataydin/anaconda3/lib/python3.10/site-packages/torch/serialization.py", line 1033, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, 'v'.

**Comment by Hzfengsy** [comment]
Yeah, I understand!
> git: 'lfs' is not a git command. See 'git --help'.

You did not install `git-lfs`, so you cannot download weights. Please:
1. Install git-lfs
2. remove the current model folder (likely in `dist/RedPajama-INCITE-Chat-3B-v1`)
3. try again

**Comment by suhjohn** [comment]
I think ^ is separate issue from what I am seeing right?

**Comment by Hzfengsy** [comment]
Not sure about it. Could you please check if the weight file is in your folder `dist/models/chronos-hermes-13b-v2`. It's also possible you are facing the same issue

**Comment by yongjer** [comment]
@suhjohn I ran "conda install -c conda-forge git-lfs" and solved the issue after activating conda env.

**Comment by junrushao** [comment]
Please refer to [this PR](https://github.com/mlc-ai/llm-perf-bench/pull/28). It's very likely caused by "git-lfs" is not installed. Thanks @yongjer for figuring this out!
