### ISSUE TITLE
[Model Request] 

### ISSUE THREAD

**Issue by jikario** [mlc-ai/mlc-llm#760]
## ⚙️  Request New Models

- Link to an existing implementation (e.g. Hugging Face/Github): 
- Is this model architecture supported by MLC-LLM? (the list of [supported models](https://mlc.ai/mlc-llm/docs/prebuilt_models.html))

**Comment by Hzfengsy** [comment]
Hi @jikario. Welcome to the MLC community. I'm closing this issue as it does not provide any useful information.

Feel free to open a new one with the following things:
1. What kind of model would you like to have
2. The HF links to your request model
