### ISSUE TITLE
[Bug] `q4f16_ft`, `q8f16_ft` fail at symbol lookup on `mlc_chat_cli`

### ISSUE THREAD

**Issue by sunggg** [mlc-ai/mlc-llm#764]
## 🐛 Bug

`mlc_chat_cli` fails at symbol lookup for faster transformer kernels. 
* TVM commit: https://github.com/apache/tvm/commit/aa2178282811d34df3ca3d9ee58580396fd0358d
* MLC-LLM commit: https://github.com/mlc-ai/mlc-llm/commit/0735f6cebb8c208109925d552a62d64a700892db

It worked previoulsy on 
* TVM commit: https://github.com/apache/tvm/commit/bd359685c7d2b6cb666dfa4eca1b6902b22d2a4f
* MLC-LLM: https://github.com/mlc-ai/mlc-llm/commit/88e6d3e9bb65b4b864834f751743210666ab5047

## To Reproduce

1. `python3 build.py --model llama-2-7b-chat-hf --quantization q4f16_ft --use-cache=0 --use-cuda-graph`
2. `./build/mlc_chat_cli --model llama-2-7b-chat-hf --quantization q4f16_ft`
3. Error
```
ubuntu@ip-172-31-7-87:~/mlc-llm$ ./build/mlc_chat_cli --model llama-2-7b-chat-hf --quantization q4f16_ft
Use MLC config: "/home/ubuntu/mlc-llm/dist/llama-2-7b-chat-hf-q4f16_ft/params/mlc-chat-config.json"
Use model weights: "/home/ubuntu/mlc-llm/dist/llama-2-7b-chat-hf-q4f16_ft/params/ndarray-cache.json"
Use model library: "/home/ubuntu/mlc-llm/dist/llama-2-7b-chat-hf-q4f16_ft/llama-2-7b-chat-hf-q4f16_ft-cuda.so"
You can use the following special commands:
  /help               print the special commands
  /exit               quit the cli
  /stats              print out the latest stats (token/sec)
  /reset              restart a fresh chat
  /reload [local_id]  reload model `local_id` from disk, or reload the current model if `local_id` is not specified

Loading model...
Loading finished
Running system prompts...
./build/mlc_chat_cli: symbol lookup error: /home/ubuntu/mlc-llm/dist/llama-2-7b-chat-hf-q4f16_ft/llama-2-7b-chat-hf-q4f16_ft-cuda.so: undefined symbol: _ZN17fastertransformer22gemm_fp16_int_bias_actIN7cutlass15integer_subbyteILi4ELb0EEEEEvPKNS1_6half_tEPKT_S6_S6_PS4_St8optionalINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEiiiiPcmP11CUstream_st
```

## Expected behavior
Chat works. 

## Environment

 - Platform (e.g. WebGPU/Vulkan/IOS/Android/CUDA): CUDA
 - Operating system (e.g. Ubuntu/Windows/MacOS/...): Ubuntu
 - Device (e.g. iPhone 12 Pro, PC+RTX 3090, ...): A10G
 - How you installed MLC-LLM (`conda`, source): Source
 - How you installed TVM-Unity (`pip`, source): Source
 - Python version (e.g. 3.10): Python 3.10.12
 - GPU driver version (if applicable): 12.1
 - CUDA/cuDNN version (if applicable): 12.1
 - TVM Unity Hash Tag (`python -c "import tvm; print('\n'.join(f'{k}: {v}' for k, v in tvm.support.libinfo().items()))"`, applicable if you compile models): Provided in the bug description
 - Any other relevant information: Provided in the bug description

**Comment by masahi** [comment]
It works for me, and it has nothing to do with a change in mlc or TVM. Probably you haven't add `USE_CUTLASS` when building `mlc_chat_cli`.
