### ISSUE TITLE
[Question] token limit settings on model's performance 

### ISSUE THREAD

**Issue by willswordh** [mlc-ai/mlc-llm#765]
## ❓ General Questions

I tried the vicuna models on android platform with max-seq-len of 768 , 1000, and 2048. Compared to 768 version, it appeared that the prefill token speed of 1000 and 2048 version both are lowered tremendously from 14 token/s to 3 token/s. My question is why the 1000 token limit version had such a huge performance downgrade compared to 768 token limit version. Thanks!

**Comment by Hzfengsy** [comment]
It should not influence the performance if memory is enough. What's the memory size of your device?

One possible reason is that the android system uses swap when the program is out of memory

**Comment by willswordh** [comment]
> It should not influence the performance if memory is enough. What's the memory size of your device?
> 
> One possible reason is that the android system uses swap when the program is out of memory

The memory should be enough for a 12gb device. It is weird that a slight increase of 768 token to 1000 token will limit the model's performance this much. I wonder if memory is not the issue that causes this problem.
