### ISSUE TITLE
s:/[Doc]: Adding important notes for docs/deploy/android.html#app-build-instructions

### ISSUE THREAD

**Issue by BarfingLemurs** [mlc-ai/mlc-llm#769]
### Suggestion
- state dependencies needed for build process. Do we need the same conda and pip packages like when installing the cli executable? 
- add initialize step `git submodule init && git submodule update` in case user does regular git clone
- add installing rustup, add instruction `rustup default stable` for setting up.
- *add android studio install as zip file, with llvm-ar package (I don't have it installed somehow.) FileNotFoundError: [Errno 2] No such file or directory: '/home/user/Downloads/android-studio/plugins/c-clangd/bin/clang/linux/x64/llvm-ar
> ls /home/user/Downloads/android-studio/plugins/c-clangd/bin/clang/linux/x64/
clangd       clang-tidy   libc++.so.1  

- exporting with ubuntu 22.04
    - `export TVM_NDK_CC=/home/user/Downloads/android-studio/plugins/c-clangd/bin/clang/linux/x64/clangd` 
    - `export ANDROID_NDK=/home/user/Downloads/android-studio/plugins/android-ndk`
    - `export JAVA_HOME=/home/user/Downloads/jdk-20`

Since I'm not in development. I'm stuck on the android-studio plugin installation not having *'llvm-ar' package for building libraries with ./prepare_libs.sh. 

I was able to quantize a hf 7b model and get a .jar file as it was a requirement for ./prepare_libs.sh

Side Question: is it easier to build and run the cli for android with acceleration on termux?

**Comment by Hzfengsy** [comment]
Thanks for the suggestion. Would be great if you could directly create a PR if you've confident with the instruction.

BTW, we (most of the teammates) are not experts of android, so we also do not know the details about APP development.
