### ISSUE TITLE
Chinese variants model support

### ISSUE THREAD

**Issue by lucasjinreal** [mlc-ai/mlc-llm#77]
As for Vicuna didn't support Chinese very well, is there a way to support some more good performance Chinese model in demo?>

**Comment by yzh119** [comment]
We have some preliminary support for [MOSS](https://github.com/OpenLMLab/MOSS/tree/main) on the main branch, and you can build and run them manually (by specifying `--model moss-moon-003-sft`. Currently, they are still using default schedules (that said, very slow). I'll tune the kernel performance by the end of this week, and we will make them available in the next release.

@LeshengJin is working on ChatGLM support.

**Comment by lucasjinreal** [comment]
@yzh119 thanks, hoping for it.

**Comment by yzh119** [comment]
We can make a release as soon as we finish tuning the Dolly and MOSS performance.

**Comment by colakang** [comment]
how about Chinese-Alpaca-Plus-7B?
is it possible run on mlc-llm?

**Comment by jiacheo** [comment]
> We have some preliminary support for [MOSS](https://github.com/OpenLMLab/MOSS/tree/main) on the main branch, and you can compile and run them manually (by specifying `--model moss-moon-003-sft`. Currently, they are still using default schedules (that said, very slow). I'll tune the kernel performance by the end of this week, and we will make them available in the next release.
> 
> @LeshengJin is working on ChatGLM support.

Hi @LeshengJin, how was the progress going on ChatGLM?
