### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by venuv** [mlc-ai/mlc-llm#770]
## 🐛 Bug

On a Macbook Pro (M2 Max) - MLC-Chat works in CLI mode but not python mode. In CLI it seems to reach for the 'metal_x86_64' lib, where in the python script it reaches for .so. 
 
## To Reproduce

1. compile MLC-chat with 'metal' instructions you've provided .. on an M2
2. try llama-2-13b on CLI
3. try your python example verbatim,  on 2-13b

screen shots attached
## Expected behavior

both of the above should either work or not work (not 1 and 1) 
## Environment
two images are attached  - showing the CLI and python runs

 - Platform (e.g. WebGPU/Vulkan/IOS/Android/CUDA):
<img width="1202" alt="python mlc chat" src="https://github.com/mlc-ai/mlc-llm/assets/1031925/18ef2b5a-4a2b-4eeb-b7a1-9966b4ad952a">

<img width="1208" alt="M2 strangeness" src="https://github.com/mlc-ai/mlc-llm/assets/1031925/80c02202-af8b-4e2e-a628-2e343f178508">

 - Operating system (e.g. Ubuntu/Windows/MacOS/...):
 - Device (e.g. iPhone 12 Pro, PC+RTX 3090, ...)
 - How you installed MLC-LLM (`conda`, source):
 - How you installed TVM-Unity (`pip`, source):
 - Python version (e.g. 3.10):
 - GPU driver version (if applicable):
 - CUDA/cuDNN version (if applicable):
 - TVM Unity Hash Tag (`python -c "import tvm; print('\n'.join(f'{k}: {v}' for k, v in tvm.support.libinfo().items()))"`, applicable if you compile models):
 - Any other relevant information:

**Comment by Hzfengsy** [comment]
Please check your Python arch via
```bash
python3 -c "import platform; print(platform.machine())"
```

Here is my guess:
1. You installed `x86_64` python/conda
2. use `x86_64` conda to install CLI, so that the CLI is also with `x86_64`
3. The arch detection is a little different between Python and CLI (but should be fine if you install the correct python, so Python API tries to load ARM so, however, it's a `x86_64` based python, then fails

**Comment by venuv** [comment]
@Hzfengsy thx much. it does indeed say x86_64 and CLI does work .. but would reinstalling conda with arm get both CLI and python to work?

--
python3 -c "import platform; print(platform.machine())"
x86_64

**Comment by Hzfengsy** [comment]
That should work!

**Comment by CharlieFRuan** [comment]
Closing this issue for now due to inactivity. Feel free to open another if there are other questions!
