### ISSUE TITLE
[Bug] Segmentation Fault while attemping to Quantize with ROCm

### ISSUE THREAD

**Issue by TNT3530** [mlc-ai/mlc-llm#775]
## 🐛 Bug

Running the command `python3 -m mlc_llm.build --hf-path <model> --target rocm --quantization q4f16_1`

gives the following error:
![image](https://github.com/mlc-ai/mlc-llm/assets/7338884/1c0b87c7-786c-444a-a32d-a3f480763833)

## To Reproduce

1. Follow these steps to compile https://mlc.ai/mlc-llm/docs/compilation/compile_models.html on Ubuntu 22.04, ROCm 5.6
2. Update LLVM to 16.0.6, recompile TVM using instructions https://mlc.ai/mlc-llm/docs/install/tvm.html#option-2-build-from-source
3. `pip3 install -e .`
4. Run build command, download model from HF, get segmentation fault, no other error given

## Expected behavior

Should download (succeeds) and then compile model into given quantization

## Environment

 - Platform (e.g. WebGPU/Vulkan/IOS/Android/CUDA): ROCm
 - Operating system (e.g. Ubuntu/Windows/MacOS/...): Ubuntu 22.04
 - Device (e.g. iPhone 12 Pro, PC+RTX 3090, ...): 4x AMD Instinct MI100
 - How you installed MLC-LLM (`conda`, source): Source
 - How you installed TVM-Unity (`pip`, source): Source
 - Python version (e.g. 3.10): 3.10
 - GPU driver version (if applicable): ROCm 5.6
 - CUDA/cuDNN version (if applicable): N/A
 - TVM Unity Hash Tag (`python -c "import tvm; print('\n'.join(f'{k}: {v}' for k, v in tvm.support.libinfo().items()))"`, applicable if you compile models): in linked txt file
 - Any other relevant information: N/A

[llvm.txt](https://github.com/mlc-ai/mlc-llm/files/12364299/llvm.txt)

**Comment by Hzfengsy** [comment]
cc @spectrometerHBH

**Comment by TNT3530** [comment]
More attempts:
Tried uninstalling the PIP versions of MLC and only using source
Tried recompiling using `USE_LLVM=/path/to/llvm` instead of ON, for LLVM 16.0.6
Same as above but with LLVM 17.0.0
Forcefully deleted TVM in site-packages and reinstalled a freshly built version with `pip install -e .`

No luck

**Comment by junrushao** [comment]
The segfault happens during quantization rather than compilation, meaning it might be something else

**Comment by clayscode** [comment]
Just confirming I also run into the same issue

**Comment by junrushao** [comment]
Interesting! Would you guys like to share some extra information? Specifically, the stacktrace from GDB

```
>>> gdb python3
>>> run -m mlc_llm.build --hf-path <model> --target rocm --quantization q4f16_1
...
segmentation fault ...
>> bt
```

**Comment by TNT3530** [comment]
![image](https://github.com/mlc-ai/mlc-llm/assets/7338884/4cbed410-a458-4819-929e-4d8dda14c655)

**Comment by junrushao** [comment]
Frame 1 shows some weird stuff from pytorch, which is not supposed to mess up with with MLC. Perhaps pytorch did some weird hacks or has some symbol conflicts with MLC…How about installing pytorch cpu without rocm support?

**Comment by TNT3530** [comment]
Uninstalling ROCm Torch and swapping with CPU works. Its a shame I need the ROCm version for other projects though
