### ISSUE TITLE
[Bug] Gradio cannot work

### ISSUE THREAD

**Issue by nksgw11** [mlc-ai/mlc-llm#776]
## 🐛 Bug

When deploying using the mlc_chat.gradio command, everything works fine and can also be displayed on the web page, but when loading the model starts working, there is an error saying "expected value line 1 column 1 char 0"

![image](https://github.com/mlc-ai/mlc-llm/assets/32957565/1e9e3317-55f4-4d47-b4a1-4012e76f6b2e)

**Comment by nksgw11** [comment]
By the way, the default address of gradio startup is 127.0.0.1. It is best to set the startup address to 0.0.0.0, so that even if it is deployed on other machines, other intranet machines can also access it through the port number, otherwise it can only be started locally.  my changes to the gradio.py file are as follows
```Python
# launch to the web
demo.queue().launch(share=share, inbrowser=True, server_name='0.0.0.0', server_port=port)
```

**Comment by Kathryn-cat** [comment]
Hi @nksgw11 , if "Error" appears on the web page, there should be concrete error messages in the command line showing what goes wrong. Would you like to take a screenshot of these concrete error messages?

Also, thanks for the feedback on the startup address and I will change it soon.

**Comment by nksgw11** [comment]
> Hi @nksgw11 , if "Error" appears on the web page, there should be concrete error messages in the command line showing what goes wrong. Would you like to take a screenshot of these concrete error messages?
> 
> Also, thanks for the feedback on the startup address and I will change it soon.

Thanks for your reply！There doesn't seem to be any relevant error messages in the console, so I don't know what's going on

![image](https://github.com/mlc-ai/mlc-llm/assets/32957565/70acd71d-71d0-48be-8dc6-2d96883b1269)

**Comment by Kathryn-cat** [comment]
Hi @nksgw11 , thanks for the feedback. If no error messages appear in the console, it is not an issue with MLC LLM itself.

Looking at the errors

> "Expecting value: line 1 column 1 (char 0)"

> "Could not create share link. Please check your internet connection or our status page."

These errors suggest that there might be a problem with the internet connection. Would you please check if any network proxy is turned on (i.e. shadowsocks)? If you're using proxy, perhaps you might need to add `--no-gradio-queue`. Also, would you like to check if Gradio installation is up-to-date? We tested on Gradio 3.35 and it works fine.

For more debugging info, you can consider visit [https://status.gradio.app/](https://status.gradio.app) and follow the instructions to check network status.

**Comment by nksgw11** [comment]
> Hi @nksgw11 , thanks for the feedback. If no error messages appear in the console, it is not an issue with MLC LLM itself.
> 
> Looking at the errors
> 
> > "Expecting value: line 1 column 1 (char 0)"
> 
> > "Could not create share link. Please check your internet connection or our status page."
> 
> These errors suggest that there might be a problem with the internet connection. Would you please check if any network proxy is turned on (i.e. shadowsocks)? If you're using proxy, perhaps you might need to add `--no-gradio-queue`. Also, would you like to check if Gradio installation is up-to-date? We tested on Gradio 3.35 and it works fine.
> 
> For more debugging info, you can consider visit [https://status.gradio.app/](https://status.gradio.app) and follow the instructions to check network status.

Hi @Kathryn-cat , thank you for your suggestion. When I tried the same command to start the service again after a few days, I found that it works normally this time. However, your suggestion makes me guess that the problem may indeed be caused by using some proxy services, but now I can not to reproduce it. Finally, thank you for your help again! 👍
