### ISSUE TITLE
[Feature Request]  MLC support for non-chat Llama models

### ISSUE THREAD

**Issue by arnavsinghvi11** [mlc-ai/mlc-llm#792]
## 🚀 Feature

MLC support for non-chat Llama models

## Motivation

Currently, it seems that MLC is primarily hosted for supporting llama-chat models but it would be great to have support for the non-chat models (e.g. [meta-llama/Llama-2-7b-hf](https://huggingface.co/meta-llama/Llama-2-7b-hf)). It's great to have the chat models supported and functional within Colab notebooks and having similar support for these non-chat models would be great as well.

**Comment by junrushao** [comment]
I think it’s already supported. There’s a note on using non-chat ones from Hamel: https://hamel.dev/notes/llm/inference/03_inference.html#mlc

**Comment by arnavsinghvi11** [comment]
Oh so I was actually using this change already so does it mean using `"conv_template": "LM"` on Llama-2-7b-chat-hf-q4f16_1 is effectively running mlc - Llama-2-7b-hf?

**Comment by junrushao** [comment]
LM is short for language model, meaning in vanilla language model mode. Therefore,

-  "conv_template": "LM" is for Llama-2-7b-hf
-  "conv_template": "llama2" is for Llama-2-7b-chat-hf

**Comment by arnavsinghvi11** [comment]
Makes sense. Thank you for the explanation!

**Comment by okhat** [comment]
Hmm this sounds unlikely so we want to double-check.

Changing the template changes the entire model weights? This sounds super unlikely to be happening (and bad practice IMO if it's true), especially since I think we download the weights ourselves and clearly they are the chat weights.

My understanding is that the conv_template=LM setting just uses basic LM templating (non-chat) with the model weights from llama2-chat.

**Comment by junrushao** [comment]
Certainly, I'd love to explain in details. @okhat @arnavsinghvi11 

There are essentially two steps in MLC LLM: weight conversion (e.g. quantization), compute compilation. To run a non-chat model, you will need weights from `Llama-2-7b-hf` to be quantized, and change the `conv_template` properly to `LM`.

To briefly describe the workflow:
- Run `build.py` to quantize and compile the non-chat model
- This generates a compiled model (e.g. `Llama-2-7b-hf-q4f16_1-cuda.so`), as well as a `params/` folder that contains 1) quantized weights; 2) tokenizer configurations; 3) mlc chat configuration (`mlc-chat-config.json`).
- Change the `conv-template` field in `mlc-chat-config.json` from `llama-2` to `LM`.

Let me know if it makes sense

**Comment by CharlieFRuan** [comment]
Closing this issue for now due to inactivity. Feel free to open another one if there are other questions!
