### ISSUE TITLE
[Bug] Getting Model lib RedPajama-INCITE-Chat-3B-v1-q4f16_0 is not supported on ios

### ISSUE THREAD

**Issue by adukale** [mlc-ai/mlc-llm#793]
## To Reproduce

1. Added https://huggingface.co/mlc-ai/mlc-chat-RedPajama-INCITE-Chat-3B-v1-q4f16_0 to dist/prebuilt
2. Executed ./prepare_libs.sh
3. Executed ./prepare_params.sh 

## Expected behavior

The app should load RedPajama-INCITE-Chat-3B-v1-q4f16_0 model since it is pre packaged. Also adding model varient from URL is not working for same model.

## Environment

 - Platform (e.g. WebGPU/Vulkan/IOS/Android/CUDA): iOS
 - Operating system (e.g. Ubuntu/Windows/MacOS/...): MacOS
 - Device (e.g. iPhone 12 Pro, PC+RTX 3090, ...): iPhone 13 Pro Max
 - How you installed MLC-LLM (`conda`, source): source
 - How you installed TVM-Unity (`pip`, source): source
 - Python version (e.g. 3.10): 3.10.10
 - GPU driver version (if applicable):
 - CUDA/cuDNN version (if applicable):
 - TVM Unity Hash Tag (`python -c "import tvm; print('\n'.join(f'{k}: {v}' for k, v in tvm.support.libinfo().items()))"`, applicable if you compile models):
 - Any other relevant information:

**Comment by junrushao** [comment]
Not sure I fully understand it, but `q4f16_0` was deprecated a while ago. How about `q4f16_1`?

**Comment by adukale** [comment]
@Lucyan11 Nope not yet.

**Comment by Hzfengsy** [comment]
At this moment, we are pushing `q4f16_1` instead of `q4f16_0`. So please use compile it as `q4f16_1` if possible
