### ISSUE TITLE
[Doc] max_gen_len is not explained

### ISSUE THREAD

**Issue by simonw** [mlc-ai/mlc-llm#794]
## 📚 Documentation

The `max_gen_len` option seems important, but there's nothing in the documentation to help explain exactly what it is or what it does.

I guessed it meant "maximum generation length" but that's just a guess, and it sometimes surprises me in terms of what happens when I use it

### Suggestion

Explain exactly what `max_gen_len` does, ideally with some illustrative examples.

**Comment by Kathryn-cat** [comment]
Hi @simonw , yes, `max_gen_len` means maximum generation length. Specifically, it's a parameter that allows users to configure MLC Chat and controls the maximum number of generated tokens. If `max_gen_len=512`, generation will stop at the 513-th token. 

Thanks for the suggestion. We will update the docs accordingly.

**Comment by jefftriplett** [comment]
Having scanned the docs, https://llm.mlc.ai/docs/search.html?q=max_gen_len&check_keywords=yes&area=default I'm still not sure if this is very clear. 

Maybe expanding the docstrings for `max_gen_len (Optional[int]) –` from https://llm.mlc.ai/docs/deploy/python.html would help explain it?

**Comment by tqchen** [comment]
@jefftriplett great suggestion, @Kathryn-cat @davidpissarra @CharlieFRuan would be great we followup on this

**Comment by CharlieFRuan** [comment]
@jefftriplett #1119 should add the doc accordingly. Thank you!

**Comment by jefftriplett** [comment]
@CharlieFRuan thank you! Much appreciated.
