### ISSUE TITLE
Does MLC support CPU or not

### ISSUE THREAD

**Issue by aitss2017** [mlc-ai/mlc-llm#795]
## ❓ General Questions
https://mlc.ai/package/
From above link, it seems that MLC can support CPU inference, but when I install it on a CPU platform, it failed with below error message even install vulkan
# vulkaninfo
WARNING: [Loader Message] Code 0 : terminator_CreateInstance: Failed to CreateInstance in ICD 1.  Skipping ICD.
'DISPLAY' environment variable not set... skipping surface info
ERROR at vulkaninfo/vulkaninfo.h:248:vkEnumeratePhysicalDevices failed with ERROR_INITIALIZATION_FAILED

# mlc_chat_cli --local-id Llama-2-7b-chat-hf-q4f16_1
terminate called after throwing an instance of 'tvm::runtime::InternalError'
  what():  [14:52:44] /usr/share/miniconda/envs/mlc-llm-build/conda-bld/mlc-chat-cli-nightly-package_1692767194298/work/3rdparty/tvm/src/runtime/vulkan/vulkan_instance.cc:144: InternalError: Check failed: (__e == VK_SUCCESS) is false: Vulkan Error, code=-3: VK_ERROR_INITIALIZATION_FAILED
Stack trace:
  [bt] (0) /root/anaconda3/envs/mlc/bin/../lib/libtvm_runtime.so(tvm::runtime::Backtrace[abi:cxx11]()+0x27) [0x7fb5050a4d27]
  [bt] (1) /root/anaconda3/envs/mlc/bin/../lib/libtvm_runtime.so(+0x680a8) [0x7fb5050680a8]
  [bt] (2) /root/anaconda3/envs/mlc/bin/../lib/libtvm_runtime.so(tvm::runtime::vulkan::VulkanInstance::GetPhysicalDevices() const+0x1cd) [0x7fb50519af7d]
  [bt] (3) /root/anaconda3/envs/mlc/bin/../lib/libtvm_runtime.so(tvm::runtime::vulkan::VulkanDeviceAPI::VulkanDeviceAPI()+0x14b) [0x7fb50519903b]
  [bt] (4) /root/anaconda3/envs/mlc/bin/../lib/libtvm_runtime.so(tvm::runtime::vulkan::VulkanDeviceAPI::Global()+0x4c) [0x7fb5051992cc]
  [bt] (5) /root/anaconda3/envs/mlc/bin/../lib/libtvm_runtime.so(+0x19930d) [0x7fb50519930d]
  [bt] (6) /root/anaconda3/envs/mlc/bin/../lib/libtvm_runtime.so(+0x70c1c) [0x7fb505070c1c]
  [bt] (7) /root/anaconda3/envs/mlc/bin/../lib/libtvm_runtime.so(tvm::runtime::DeviceAPI::Get(DLDevice, bool)+0x299) [0x7fb505072369]
  [bt] (8) mlc_chat_cli(+0xfb98) [0x55a7ceb78b98]

Aborted (core dumped)

**Comment by junrushao** [comment]
Looks like your vulkan driver fails:

> vulkaninfo/vulkaninfo.h:248:vkEnumeratePhysicalDevices failed with ERROR_INITIALIZATION_FAILED


Please confirm if vulkaninfo could work.

**Comment by SpringWave1** [comment]
> Looks like your vulkan driver fails:
> 
> > vulkaninfo/vulkaninfo.h:248:vkEnumeratePhysicalDevices failed with ERROR_INITIALIZATION_FAILED
> 
> Please confirm if vulkaninfo could work.
So? I still don't know whether MLC-LLM support pure CPU, as I guess vulkan should be a GPU driver?

**Comment by junrushao** [comment]
Do you like to follow the instructions here to properly install Vulkan and validate if it works: https://mlc.ai/mlc-llm/docs/install/gpu.html#vulkan-driver?

If you are not using Vulkan, MLC LLM has a LLVM backend that targets CPU, but it's not officially supported. Use it at your own risk.

**Comment by aitss2017** [comment]
> Do you like to follow the instructions here to properly install Vulkan and validate if it works: https://mlc.ai/mlc-llm/docs/install/gpu.html#vulkan-driver?
> 
> If you are not using Vulkan, MLC LLM has a LLVM backend that targets CPU, but it's not announced as officially supported yet. Use it at your own risk.

If CPU support is ok, can you share the guide about how to enable it on pure CPU platform?
If not, I think there should be some warning about CPU support on the webpage.

**Comment by LiHao217** [comment]
> Do you like to follow the instructions here to properly install Vulkan and validate if it works: https://mlc.ai/mlc-llm/docs/install/gpu.html#vulkan-driver?
> 
> If you are not using Vulkan, MLC LLM has a LLVM backend that targets CPU, but it's not announced as officially supported yet. Use it at your own risk.

I would like to try using llvm as the backend version. Where can I obtain this version? If there are any bugs in this version, I am willing to try fixing it. I have some understanding of llvm.
