### ISSUE TITLE
Can you give the code and guide for all models conversion?

### ISSUE THREAD

**Issue by ZSitong** [mlc-ai/mlc-llm#80]
If you give the code of the model conversion, so that everyone can apply all the models according to the code and guide. ：）

**Comment by Hzfengsy** [comment]
All codes, including model conversion codes, are in this repo. We are going to write tutorials soon

**Comment by ZSitong** [comment]
look forward the tutorials

**Comment by Hzfengsy** [comment]
As Relax has native dynamic shape support and modulized compilation flow, we won't waste our time on Relay in this project. And we are constructed by relax, because:
1. We admit that relax does not have a well-done front-end importer
2. LLM model are easy to write
