### ISSUE TITLE
I am trying to install mlc-ai on aws amazon-linux machine

### ISSUE THREAD

**Issue by vk-maurya** [mlc-ai/mlc-llm#803]
##  No matching distribution found
I am trying to install mlc-ai dependency using the below command on my aws amazon-Linux machine. but it is saying No matching distribution found for mlc-ai-nightly-cu118. 

### command : 
$ `pip install --pre --force-reinstall mlc-ai-nightly-cu118 mlc-chat-nightly-cu118 -f https://mlc.ai/wheels`
**Error** 
Looking in links: https://mlc.ai/wheels
ERROR: Could not find a version that satisfies the requirement mlc-ai-nightly-cu118 (from versions: none)
ERROR: No matching distribution found for mlc-ai-nightly-cu118

### Linux machine details :
$ `cat /etc/*-release`

NAME="Amazon Linux"
VERSION="2"
ID="amzn"
ID_LIKE="centos rhel fedora"
VERSION_ID="2"
PRETTY_NAME="Amazon Linux 2"
ANSI_COLOR="0;33"
CPE_NAME="cpe:2.3:o:amazon:amazon_linux:2"
HOME_URL="https://amazonlinux.com/"
Amazon Linux release 2 (Karoo)

### Python version :
`Python 3.10.12`

### Nvidia driver : 
$ `nvcc --version `

nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2022 NVIDIA Corporation
Built on Wed_Sep_21_10:33:58_PDT_2022
Cuda compilation tools, release 11.8, V11.8.89
Build cuda_11.8.r11.8/compiler.31833905_0

**Comment by junrushao** [comment]
This is weird. The prebuilt is based on standard manylinux convention so it’s supposed to be available. Could you download the specific wheel and try to install locally?

**Comment by vk-maurya** [comment]
Locally and Google Colab both have Ubuntu it is working there. However AWS Machine has Amazon Linux 2 which causing the issue.

**Comment by Hzfengsy** [comment]
Try to upgrade `pip`?

**Comment by vk-maurya** [comment]
I have upgraded Latest pip version: pip 23.2.1

**Comment by junrushao** [comment]
How about:

```
python -m pip install ...
```

**Comment by linjie7674** [comment]
I have the same problem, and I tried to install it by downloading the wheel, but it still does not work.

## Command
![image](https://github.com/mlc-ai/mlc-llm/assets/133086269/08cb7f7d-b782-4fca-95c9-59a37b04dcb4)
![image](https://github.com/mlc-ai/mlc-llm/assets/133086269/fb4d2efa-89c4-4cbc-a347-cb342b3f7073)
![image](https://github.com/mlc-ai/mlc-llm/assets/133086269/3ef41348-1e10-4770-a69d-6a2e4ea61f3b)

## Linux machine details :
![image](https://github.com/mlc-ai/mlc-llm/assets/133086269/eea2bba1-58fa-4fc7-bcae-d07ae9372c45)
## Python version:
`Python 3.10.12`

**Comment by Hzfengsy** [comment]
Is it an x86 machine or an arm one?

**Comment by junrushao** [comment]
Would love to have more info to debug. Could you guys use the command below:

python3 -m pip install -v …

**Comment by yzh119** [comment]
Hi @vk-maurya , our pip wheels are built upon `manylinux_2_28` to install vulkan sdk (the glibc in `manylinux_2014` is too old to install a relatively new version of vulkan sdk).

manylinux list distribution compatibility in their [README](https://github.com/pypa/manylinux), They didn't explicitly mention Amazon Linux 2 but I suppose it's only compatible with `manylinux_2014`, not `manylinux_2_28`.

We can compile standalone CUDA wheels based on `manylinux_2014` without incorporating Vulkan SDK to make our wheels compatible with more distributions. @junrushao @tqchen WDYT?

**Comment by tqchen** [comment]
@yzh119 yah i think this is something we can do if that is not as complicated

**Comment by junrushao** [comment]
Some additional discussion around Amazon Linux can be found here: https://github.com/pypa/manylinux/issues/1332

**Comment by smpurkis** [comment]
I'm having similar issues with linux arm oracle cloud server.

**Comment by williamcastrillon** [comment]
Hey! I was having a similar issue, but I found this [mlc-ai repo](https://github.com/mlc-ai/llm-perf-bench) and I was able to solve the problem I was having! 
Hope that helps!

**Comment by 1748995976** [comment]
1. use `pip debug --verbose` to see related information
2. use personal computer download file in https://mlc.ai/wheels ,then upload it to your server computer
3. use `python -m pip install ***.whl ` to install it

About this post, you can:
1. download mlc_ai_nightly_cu118-0.12.dev1689-cp310-cp310-manylinux_2_28_x86_64.whl
2. execute `python -m pip install mlc_ai_nightly_cu118-0.12.dev1689-cp310-cp310-manylinux_2_28_x86_64.whl `

**Comment by ameryzhu** [comment]
python3 -m pip install --pre -U -f https://mlc.ai/wheels mlc-ai-nightly --verbose
Using pip 24.0 from /Users/zhuzhe/miniconda3/envs/mlc/lib/python3.7/site-packages/pip (python 3.7)
Looking in links: https://mlc.ai/wheels
ERROR: Could not find a version that satisfies the requirement mlc-ai-nightly (from versions: none)
ERROR: No matching distribution found for mlc-ai-nightly
