### ISSUE TITLE
[Feature Request] multiple stop strings

### ISSUE THREAD

**Issue by GameOverFlowChart** [mlc-ai/mlc-llm#808]
## 🚀 Feature
Currently the `mlc-chat-config.json` only supports a single stop string. Instead, support multiple (an array).

## Motivation
One of the most common problems with llm's is that they confuse the roles and start speaking as the user after answering a question. This can be prevented  if the `role` starts with a string that is also a stop string. This would make the llm stop instead of talking in the name of the user.

## Alternatives
The alternative is simple yet complicated.
During the training of a model, it would need to get two reserved tokens ("start of user input" & "end of llm output". The prompt template used during reinforcement training would use these tokens in the templates. The model than would only be allowed to output the "end of llm output" token which would act as a stop string, and it would be forbidden to output the "start of user input" token. In short this would use  reserved tokens instead of strings, but as far as I know llama2 doesn't have such reserved tokens and if it does, there is no reinforcement trained model that makes use of it. The idea is simple but it's complicated because we don't have control over the training phase of the models.

**Comment by junrushao** [comment]
Is there a specific model using such conversation template?

**Comment by GameOverFlowChart** [comment]
> Is there a specific model using such conversation template?

Conversation templates can be edited. I'm using the uncensored llama2 which already has a wrong template (the "### " is missing before the roles). So I edited it in and it works much better this way, the model is less confused and more aware that it's not a human. But the model still starts to talk as the user sometimes. So I could make "###" a stop string so that the model wouldn't start saying "### user: ".

I this request is even more powerful than just that. You could turn new lines into stop strings to output just one line. You could turn punctuation into stop strings to make the model just output one sentence if that's what you want. It would be a very flexible feature.

**Comment by MasterJH5574** [comment]
Hey @GameOverFlowChart I think as of now we have supported multiple stop strings. The preset conversation templates are defined here https://github.com/mlc-ai/mlc-llm/blob/main/python/mlc_llm/conversation_template.py. If you follow the instructions in our documentation https://llm.mlc.ai/docs/compilation/compile_models.html#generate-mlc-chat-config-and-compile and run `mlc_llm gen_config ...`, the generated `mlc-chat-config.json` has a list for stop strings.

Therefore, I'm going to close this issue. Feel free to try out, and you are welcome to open new issues if there are any other problems.
