### ISSUE TITLE
(mlc-chat-venv) C:\gpt>mlc_chat_cli --local-id Llama-2-70b-chat-hf-q4f16_1 Unknown argument: --local-id Usage: mlc_chat [--help] [--version] [--model VAR] [--device VAR] [--evaluate] [--eval-prompt-len VAR] [--eval-gen-len VAR]

### ISSUE THREAD

**Issue by crystalyue2023** [mlc-ai/mlc-llm#812]
**Problem**
(mlc-chat-venv) C:\gpt>mlc_chat_cli --local-id Llama-2-70b-chat-hf-q4f16_1
Unknown argument: --local-id
Usage: mlc_chat [--help] [--version] [--model VAR] [--device VAR] [--evaluate] [--eval-prompt-len VAR] [--eval-gen-len VAR]
**mlc_chat_cli**
(mlc-chat-venv) C:\gpt>mlc_chat_cli --h
Unknown argument: --h
Usage: mlc_chat [--help] [--version] [--model VAR] [--device VAR] [--evaluate] [--eval-prompt-len VAR] [--eval-gen-len VAR]

Optional arguments:
  -h, --help            shows help message and exits
  -v, --version         prints version information and exits
  --model
  --device              [default: "auto"]
  --evaluate
  --eval-prompt-len     [default: 128]
  --eval-gen-len        [default: 1024]

**Comment by Kathryn-cat** [comment]
Hi @crystalyue2023 , we recently get rid of `--local-id` and replace it with `--model`. You can try passing in `--model` and see if it works.

**Comment by junrushao** [comment]
@Kathryn-cat would you like to update our doc to reflect the change effectively (if not yet)

**Comment by library110** [comment]
> > 嗨，我们最近摆脱了它并将其替换为.您可以尝试传入，看看它是否有效。`--local-id``--model``--model`
> 
> ## 仍然无法在窗口上运行...
> （MLC-chat-venv）D：\dest>mlc_chat_cli --model Llama-2-7b-chat-hf-q4f16_1 [23：07：39] C：\Miniconda\envs\mlc-llm-build\conda-bld\mlc-chat-cli-nightly-package_1693372238907\work\cpp\cli_main.cc：339：提供的模型文件夹似乎没有引用有效的 mlc-llm 模型文件夹。具体来说，我们找不到 ，所需的文件。应提供包含该文件的路径。根据您的输入，我们查看了文件夹：`mlc-chat-config.json``Llama-2-7b-chat-hf-q4f16_1`
> 
> * 美洲驼-2-7b-聊天-hf-q4f16_1
> * dist/prebuild/Llama-2-7b-chat-hf-q4f16_1
> * dist/Llama-2-7b-chat-hf-q4f16_1/params
> * dist/prebuild/mlc-chat-Llama-2-7b-chat-hf-q4f16_1 在编译时禁用DMLC_LOG_STACK_TRACE时，堆栈跟踪不可用。

我也是遇到这错误了，怎么办

**Comment by library110** [comment]
(mlc-chat-venv) E:\prebuilt>mlc_chat_cli --model E:\prebuilt\mlc-chat-Llama-2-7b-chat-hf-q4f16_1
Use MLC config: "E:\\prebuilt\\mlc-chat-Llama-2-7b-chat-hf-q4f16_1\\mlc-chat-config.json"
Use model weights: "E:\\prebuilt\\mlc-chat-Llama-2-7b-chat-hf-q4f16_1\\ndarray-cache.json"
[22:51:54] C:\Miniconda\envs\mlc-llm-build\conda-bld\mlc-chat-cli-nightly-package_1694236248929\work\cpp\cli_main.cc:377: Cannot find the model library that corresponds to `Llama-2-7b-chat-hf-q4f16_1`.
We searched over the following possible paths:
- Llama-2-7b-chat-hf-q4f16_1
- dist/prebuilt/lib
- dist/E:\prebuilt\mlc-chat-Llama-2-7b-chat-hf-q4f16_1
- dist/prebuilt/Llama-2-7b-chat-hf-q4f16_1
Stack trace not available when DMLC_LOG_STACK_TRACE is disabled at compile time.
这怎么办？

**Comment by hcaicai** [comment]
@library110 解决了吗？

**Comment by library110** [comment]
@hcaicai 没有解决，你有办法吗

**Comment by shengmengru** [comment]
> > Hi @crystalyue2023 , we recently get rid of `--local-id` and replace it with `--model`. You can try passing in `--model` and see if it works.
> 
> ## still not working on windows...
> (mlc-chat-venv) D:\dest>mlc_chat_cli --model Llama-2-7b-chat-hf-q4f16_1 [23:07:39] C:\Miniconda\envs\mlc-llm-build\conda-bld\mlc-chat-cli-nightly-package_1693372238907\work\cpp\cli_main.cc:339: The model folder provided does not seem to refer to a valid mlc-llm model folder. Specifically, we cannot find `mlc-chat-config.json`, a required file. You should provide a path that contains the file. According to your input `Llama-2-7b-chat-hf-q4f16_1`, we looked at folder(s):
> 
> * Llama-2-7b-chat-hf-q4f16_1
> * dist/prebuilt/Llama-2-7b-chat-hf-q4f16_1
> * dist/Llama-2-7b-chat-hf-q4f16_1/params
> * dist/prebuilt/mlc-chat-Llama-2-7b-chat-hf-q4f16_1
>   Stack trace not available when DMLC_LOG_STACK_TRACE is disabled at compile time.

**Comment by CharlieFRuan** [comment]
Hi @hcaicai @library110, following https://llm.mlc.ai/docs/, you would need to have a `dist` folder first.

Under `dist`, you would have `prebuilt/lib`. Under `prebuilt`, you download  `mlc-chat-Llama-2-7b-chat-hf-q4f16_1`, and under `lib` you clone https://github.com/mlc-ai/binary-mlc-llm-libs.git.

Finally you can run `mlc_chat_cli` from the top level, where you can only see `dist`. That is, the structure would look like:
```
dist
    prebuilt
        mlc-chat-Llama-2-7b-chat-hf-q4f16_1
    lib
        Llama-2-7b-chat-hf-q4f16_1.so
        #other files...
```

You could follow [this tutorial](https://github.com/mlc-ai/notebooks/blob/main/mlc-llm/tutorial_chat_module_getting_started.ipynb) (runnable on Colab) to see how the files are structured:
<img width="336" alt="image" src="https://github.com/mlc-ai/mlc-llm/assets/53290280/1b590b5a-0caa-4a58-825b-d9005d903434">
