### ISSUE TITLE
[Feature Request] auto-generate mlc-chat-config.json when compiling with mlc_llm.build

### ISSUE THREAD

**Issue by denise-k** [mlc-ai/mlc-llm#820]
## 🚀 Feature
Automatically generate `mlc-chat-config.json` as a part of the `mlc-llm.build` process.

## Motivation

The `mlc-chat-config.json` is a critical file used to to configure pre-compiled models for the MLC Chat CLI. Currently, if you compile your own model with the `mlc-llm.build` process, you do not get a `mlc-chat-config.json` file in the new model directory and you only find out that this file is necessary when you try the MLC Chat CLI and encounter an error saying "We cannot find `mlc-chat-config.json`, a required file". 

IMO, since this file is required to use the MLC Chat CLI, and all the metadata is available during the compilation process, this file should be auto-generated.

## Alternatives

I believe that the MLC-LLM build process has enough context to be able to auto-generate the `mlc-chat-config.json` pretty easily.

However, if it is not feasible or high enough priority, the `mlc-llm.build` process could either (a) inform the user that they need to manually generate the `mlc-chat-config.json` and point them to the documentation, or (b) provide a scaffold/template `mlc-chat-config.json` to the user upon build, and ask them to edit the relevant vlues.

## Additional context

(DOC) [Configure MLCChat in JSON](https://mlc.ai/mlc-llm/docs/get_started/mlc_chat_config.html)

**Comment by Hzfengsy** [comment]
IIRC, we do auto-generate `mlc-chat-config.json`. 

`We cannot find mlc-chat-config.json` may caused by wrong paths. Would be great if you could check your folder structure again. And show the structure if you need helps from the community :)

**Comment by CharlieFRuan** [comment]
Closing this issue for now due to inactivity. Feel free to open another one if there are further questions!
