### ISSUE TITLE
[Feature Request] Top K support

### ISSUE THREAD

**Issue by moinnadeem** [mlc-ai/mlc-llm#823]
## 🚀 Feature
It would be great if Top K, in addition to Top P, was supported in a sampling algorithm. 

## Motivation
Top K and Top P perform slightly different tasks. Supporting both is common place for ML, and is important for MLC-LLM to take off as a framework.

I would also be happy to add this as a PR if someone can point me to the right files to work on.

**Comment by GameOverFlowChart** [comment]
And I would like if it would also be possible to combine top and top k similar how it is in the online demo of Open Assistant.

**Comment by kmn1024** [comment]
Yes, this would be awesome! Would love to contribute, just tell us how.

**Comment by tqchen** [comment]
top p is now supported
