### ISSUE TITLE
[Bug] REST API sample_langchain.py crashes under Windows

### ISSUE THREAD

**Issue by Sing-Li** [mlc-ai/mlc-llm#841]
## 🐛 Bug

The Python REST API example `sample_langchain.py` has multiple errors when running  the `retrieval_qa_mlc_docs_example()` under Windows 11:

1.   The path separator `/`  used in the following lines doesn't work on windows
```
 loader = TextLoader('../resources/state_of_union.txt')
 ```
2.   The TextLoader loads the text in Code Page 1252 and there are out-of-range characters in the file around the apostrophe characters   

3.  When executing on nightly 0.12.dev1398  - embeddings endpoint has error with `embedding_ctx_length`   See  *Additional Context* section below.

## To Reproduce

1.  setup conda environment on Windows with latest nightly 0.12.dev1398
1.  run rest api
1.  setup environment variables and replace pydantic with 1.10
1.  uncomment `retrieval_qa_sotu_example()` in `sample-langchain.py`
1.  run   `python sample_langchain.py`

## Expected behavior

It should run and not crash.

## Environment

 - Platform Vulkan
 - Operating system Windows 11
 - Device  AMD 7900XTX
 - How you installed MLC-LLM (`conda`):  conda
 - How you installed TVM-Unity (`pip`):  pip 
 - Python version (e.g. 3.10): 3.10.10
 - GPU driver version (if applicable):  NA
 - CUDA/cuDNN version (if applicable):  NA
 - TVM Unity Hash Tag (`python -c "import tvm; print('\n'.join(f'{k}: {v}' for k, v in tvm.support.libinfo().items()))"`, applicable if you compile models):
 - Any other relevant information:

## Additional context

 ```
 Traceback (most recent call last):
  File "D:\allmy\dev\work\mlc-llm\examples\rest\python\sample_langchain.py", line 155, in <module>
    retrieval_qa_sotu_example()
  File "D:\allmy\dev\work\mlc-llm\examples\rest\python\sample_langchain.py", line 86, in retrieval_qa_sotu_example
    embeddings = MLCEmbeddings(deployment="text-embedding-ada-002", embedding_ctx_length=None)
  File "pydantic\main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for MLCEmbeddings
embedding_ctx_length
  none is not an allowed value (type=type_error.none.not_allowed)
```

**Comment by Sing-Li** [comment]
Adding more information here:

The `retrieval_qa_mlc_docs_example()`  requires:

```
pip install chromadb
```

changing the `embedding_ctx_length` from `None` to 0 got me past the validation check:
```
embeddings = MLCEmbeddings(deployment="text-embedding-ada-002", embedding_ctx_length=0)
```

Then I got this error:

```
TVMError: Check failed: (embed_func_.defined()) is false: In order to use the embedding functionality, make sure you build the model in MLC-LLM with `sep_embed` option on.
```

Seems not all models (I'm using the Llama2 13B)  supports embedding.  Which ones do?

**Comment by plateaukao** [comment]
@Sing-Li 
It seems that you need to add `--sep-embed` when building the model. I am trying this too.
https://github.com/mlc-ai/mlc-llm/blob/4776c196e73601e48f79f0cba0d8b55f21f04cc2/mlc_llm/core.py#L76

**Comment by tqchen** [comment]
Closing due to inactive status for now. Feel free to open new ones
