### ISSUE TITLE
[Question] How to cross compile MODEL for Jetson AGX Xavier?

### ISSUE THREAD

**Issue by junarwohn** [mlc-ai/mlc-llm#847]
Hi,

I have a question about how to cross compile model for NVIDIA Jetson AGX Xavier from x86 PC host.

I know a little bit about TVM which is the backend engine of mlc-llm, 

so as far as I know, setting host target as "llvm -mtriple=aarch64-linux-gnu", arch "sm_72", device "arm_cpu" would be enough to cross compile for aarch64 architecture.

So, I changed a bit of code at `mlc-llm/utils.py/_detect_local_cuda` as

```python
def _detect_local_cuda():
    dev = tvm.cuda()
    if not dev.exist:
        return None
    return tvm.target.Target(
        {
            "kind": "cuda",
            "max_shared_memory_per_block": dev.max_shared_memory_per_block,
            "max_threads_per_block": dev.max_threads_per_block,
            "thread_warp_size": dev.warp_size,
            "registers_per_block": 65536,
            "arch": "sm_" + "72",
            "host": "llvm -mtriple=aarch64-linux-gnu",
            "device": "arm_cpu",
        }
    )
```

However, I got the following error

```
Weights exist at dist/models/RedPajama-INCITE-Chat-3B-v1, skipping download.
Using path "dist/models/RedPajama-INCITE-Chat-3B-v1" for model "RedPajama-INCITE-Chat-3B-v1"
Target configured: cuda -keys=arm_cpu,cuda,gpu -arch=sm_72 -device=arm_cpu -max_num_threads=1024 -max_shared_memory_per_block=49152 -max_threads_per_block=1024 -registers_per_block=65536 -thread_warp_size=32
Automatically using target for weight quantization: cuda -keys=arm_cpu,cuda,gpu -arch=sm_72 -device=arm_cpu -max_num_threads=1024 -max_shared_memory_per_block=49152 -max_threads_per_block=1024 -registers_per_block=65536 -thread_warp_size=32
[05:23:44] /home/jd/workspace/mlc-llm/3rdparty/tvm/src/target/llvm/llvm_module.cc:420: Architecture mismatch: module=aarch64-linux-gnu host=x86_64-pc-linux-gnu
Traceback (most recent call last):
  File "/home/jd/workspace/ground-zero/mlc-llm_test/cross_compile.py", line 12, in <module>
    lib_path, model_path, chat_config_path = mlc_llm.build_model(build_args)
                                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jd/workspace/mlc-llm/mlc_llm/core.py", line 625, in build_model
    build_model_from_args(args)
  File "/home/jd/workspace/mlc-llm/mlc_llm/core.py", line 573, in build_model_from_args
    new_params = utils.convert_weights(param_manager, params, args)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jd/workspace/mlc-llm/mlc_llm/utils.py", line 249, in convert_weights
    vm = relax.vm.VirtualMachine(ex, device)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jd/workspace/mlc-llm/3rdparty/tvm/python/tvm/runtime/relax_vm.py", line 96, in __init__
    self._setup_device(device, memory_cfg)
  File "/home/jd/workspace/mlc-llm/3rdparty/tvm/python/tvm/runtime/relax_vm.py", line 137, in _setup_device
    self.module["vm_initialization"](*init_args)
  File "/home/jd/workspace/mlc-llm/3rdparty/tvm/python/tvm/_ffi/_ctypes/packed_func.py", line 238, in __call__
    raise get_last_ffi_error()
tvm._ffi.base.TVMError: Traceback (most recent call last):
  6: TVMFuncCall
  5: tvm::runtime::PackedFuncObj::Extractor<tvm::runtime::PackedFuncSubObj<tvm::runtime::relax_vm::VirtualMachineImpl::GetFunction(tvm::runtime::String const&, tvm::runtime::ObjectPtr<tvm::runtime::Object> const&)::{lambda(tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*)#1}> >::Call(tvm::runtime::PackedFuncObj const*, tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*)
  4: tvm::runtime::relax_vm::VirtualMachineImpl::Init(std::vector<DLDevice, std::allocator<DLDevice> > const&, std::vector<tvm::runtime::relax_vm::AllocatorType, std::allocator<tvm::runtime::relax_vm::AllocatorType> > const&)
  3: tvm::runtime::relax_vm::VirtualMachineImpl::InitFuncPool()
  2: tvm::runtime::ModuleNode::GetFunction(tvm::runtime::String const&, bool)
  1: tvm::codegen::LLVMModuleNode::GetFunction(tvm::runtime::String const&, tvm::runtime::ObjectPtr<tvm::runtime::Object> const&)
  0: tvm::codegen::LLVMModuleNode::LazyInitJIT()
  File "/home/jd/workspace/mlc-llm/3rdparty/tvm/src/target/llvm/llvm_module.cc", line 391
TVMError: Cannot run module, architecture mismatch
```

I know that the framework is still developing and my code modification is not the official or recommended way, but I'm just curious about there is already implemented or recommended way to cross compile.

Thanks in advance.

**Comment by junarwohn** [comment]
You can check the commit #863.

**Comment by srikanthsrnvs** [comment]
Re-opening this

I am trying to compile on an x86 host setting a cc-path variable, however I get errors:

RuntimeError: Compilation error:
/home/srikanth/l4t-gcc/aarch64--glibc--stable-2022.08-1/bin/../lib/gcc/aarch64-buildroot-linux-gnu/11.3.0/../../../../aarch64-buildroot-linux-gnu/bin/ld: /tmp/tmpsushxijm/lib0.o: Relocations in generic ELF (EM: 62)
/home/srikanth/l4t-gcc/aarch64--glibc--stable-2022.08-1/bin/../lib/gcc/aarch64-buildroot-linux-gnu/11.3.0/../../../../aarch64-buildroot-linux-gnu/bin/ld: /tmp/tmpsushxijm/lib0.o: Relocations in generic ELF (EM: 62)
/home/srikanth/l4t-gcc/aarch64--glibc--stable-2022.08-1/bin/../lib/gcc/aarch64-buildroot-linux-gnu/11.3.0/../../../../aarch64-buildroot-linux-gnu/bin/ld: /tmp/tmpsushxijm/lib0.o: Relocations in generic ELF (EM: 62)
/home/srikanth/l4t-gcc/aarch64--glibc--stable-2022.08-1/bin/../lib/gcc/aarch64-buildroot-linux-gnu/11.3.0/../../../../aarch64-buildroot-linux-gnu/bin/ld: /tmp/tmpsushxijm/lib0.o: Relocations in generic ELF (EM: 62)
/home/srikanth/l4t-gcc/aarch64--glibc--stable-2022.08-1/bin/../lib/gcc/aarch64-buildroot-linux-gnu/11.3.0/../../../../aarch64-buildroot-linux-gnu/bin/ld: /tmp/tmpsushxijm/lib0.o: Relocations in generic ELF (EM: 62)
/home/srikanth/l4t-gcc/aarch64--glibc--stable-2022.08-1/bin/../lib/gcc/aarch64-buildroot-linux-gnu/11.3.0/../../../../aarch64-buildroot-linux-gnu/bin/ld: /tmp/tmpsushxijm/lib0.o: Relocations in generic ELF (EM: 62)
/home/srikanth/l4t-gcc/aarch64--glibc--stable-2022.08-1/bin/../lib/gcc/aarch64-buildroot-linux-gnu/11.3.0/../../../../aarch64-buildroot-linux-gnu/bin/ld: /tmp/tmpsushxijm/lib0.o: Relocations in generic ELF (EM: 62)
/home/srikanth/l4t-gcc/aarch64--glibc--stable-2022.08-1/bin/../lib/gcc/aarch64-buildroot-linux-gnu/11.3.0/../../../../aarch64-buildroot-linux-gnu/bin/ld: /tmp/tmpsushxijm/lib0.o: Relocations in generic ELF (EM: 62)
/home/srikanth/l4t-gcc/aarch64--glibc--stable-2022.08-1/bin/../lib/gcc/aarch64-buildroot-linux-gnu/11.3.0/../../../../aarch64-buildroot-linux-gnu/bin/ld: /tmp/tmpsushxijm/lib0.o: Relocations in generic ELF (EM: 62)
/home/srikanth/l4t-gcc/aarch64--glibc--stable-2022.08-1/bin/../lib/gcc/aarch64-buildroot-linux-gnu/11.3.0/../../../../aarch64-buildroot-linux-gnu/bin/ld: /tmp/tmpsushxijm/lib0.o: Relocations in generic ELF (EM: 62)
/home/srikanth/l4t-gcc/aarch64--glibc--stable-2022.08-1/bin/../lib/gcc/aarch64-buildroot-linux-gnu/11.3.0/../../../../aarch64-buildroot-linux-gnu/bin/ld: /tmp/tmpsushxijm/lib0.o: Relocations in generic ELF (EM: 62)
/home/srikanth/l4t-gcc/aarch64--glibc--stable-2022.08-1/bin/../lib/gcc/aarch64-buildroot-linux-gnu/11.3.0/../../../../aarch64-buildroot-linux-gnu/bin/ld: /tmp/tmpsushxijm/lib0.o: Relocations in generic ELF (EM: 62)
/home/srikanth/l4t-gcc/aarch64--glibc--stable-2022.08-1/bin/../lib/gcc/aarch64-buildroot-linux-gnu/11.3.0/../../../../aarch64-buildroot-linux-gnu/bin/ld: /tmp/tmpsushxijm/lib0.o: Relocations in generic ELF (EM: 62)
/home/srikanth/l4t-gcc/aarch64--glibc--stable-2022.08-1/bin/../lib/gcc/aarch64-buildroot-linux-gnu/11.3.0/../../../../aarch64-buildroot-linux-gnu/bin/ld: /tmp/tmpsushxijm/lib0.o: Relocations in generic ELF (EM: 62)
/home/srikanth/l4t-gcc/aarch64--glibc--stable-2022.08-1/bin/../lib/gcc/aarch64-buildroot-linux-gnu/11.3.0/../../../../aarch64-buildroot-linux-gnu/bin/ld: /tmp/tmpsushxijm/lib0.o: Relocations in generic ELF (EM: 62)
/home/srikanth/l4t-gcc/aarch64--glibc--stable-2022.08-1/bin/../lib/gcc/aarch64-buildroot-linux-gnu/11.3.0/../../../../aarch64-buildroot-linux-gnu/bin/ld: /tmp/tmpsushxijm/lib0.o: Relocations in generic ELF (EM: 62)
/home/srikanth/l4t-gcc/aarch64--glibc--stable-2022.08-1/bin/../lib/gcc/aarch64-buildroot-linux-gnu/11.3.0/../../../../aarch64-buildroot-linux-gnu/bin/ld: /tmp/tmpsushxijm/lib0.o: Relocations in generic ELF (EM: 62)
/home/srikanth/l4t-gcc/aarch64--glibc--stable-2022.08-1/bin/../lib/gcc/aarch64-buildroot-linux-gnu/11.3.0/../../../../aarch64-buildroot-linux-gnu/bin/ld: /tmp/tmpsushxijm/lib0.o: Relocations in generic ELF (EM: 62)
/home/srikanth/l4t-gcc/aarch64--glibc--stable-2022.08-1/bin/../lib/gcc/aarch64-buildroot-linux-gnu/11.3.0/../../../../aarch64-buildroot-linux-gnu/bin/ld: /tmp/tmpsushxijm/lib0.o: Relocations in generic ELF (EM: 62)
/home/srikanth/l4t-gcc/aarch64--glibc--stable-2022.08-1/bin/../lib/gcc/aarch64-buildroot-linux-gnu/11.3.0/../../../../aarch64-buildroot-linux-gnu/bin/ld: /tmp/tmpsushxijm/lib0.o: Relocations in generic ELF (EM: 62)
/home/srikanth/l4t-gcc/aarch64--glibc--stable-2022.08-1/bin/../lib/gcc/aarch64-buildroot-linux-gnu/11.3.0/../../../../aarch64-buildroot-linux-gnu/bin/ld: /tmp/tmpsushxijm/lib0.o: Relocations in generic ELF (EM: 62)
/home/srikanth/l4t-gcc/aarch64--glibc--stable-2022.08-1/bin/../lib/gcc/aarch64-buildroot-linux-gnu/11.3.0/../../../../aarch64-buildroot-linux-gnu/bin/ld: /tmp/tmpsushxijm/lib0.o: Relocations in generic ELF (EM: 62)
/home/srikanth/l4t-gcc/aarch64--glibc--stable-2022.08-1/bin/../lib/gcc/aarch64-buildroot-linux-gnu/11.3.0/../../../../aarch64-buildroot-linux-gnu/bin/ld: /tmp/tmpsushxijm/lib0.o: Relocations in generic ELF (EM: 62)
/home/srikanth/l4t-gcc/aarch64--glibc--stable-2022.08-1/bin/../lib/gcc/aarch64-buildroot-linux-gnu/11.3.0/../../../../aarch64-buildroot-linux-gnu/bin/ld: /tmp/tmpsushxijm/lib0.o: Relocations in generic ELF (EM: 62)
/home/srikanth/l4t-gcc/aarch64--glibc--stable-2022.08-1/bin/../lib/gcc/aarch64-buildroot-linux-gnu/11.3.0/../../../../aarch64-buildroot-linux-gnu/bin/ld: /tmp/tmpsushxijm/lib0.o: Relocations in generic ELF (EM: 62)
/home/srikanth/l4t-gcc/aarch64--glibc--stable-2022.08-1/bin/../lib/gcc/aarch64-buildroot-linux-gnu/11.3.0/../../../../aarch64-buildroot-linux-gnu/bin/ld: /tmp/tmpsushxijm/lib0.o: Relocations in generic ELF (EM: 62)
/home/srikanth/l4t-gcc/aarch64--glibc--stable-2022.08-1/bin/../lib/gcc/aarch64-buildroot-linux-gnu/11.3.0/../../../../aarch64-buildroot-linux-gnu/bin/ld: /tmp/tmpsushxijm/lib0.o: Relocations in generic ELF (EM: 62)
/home/srikanth/l4t-gcc/aarch64--glibc--stable-2022.08-1/bin/../lib/gcc/aarch64-buildroot-linux-gnu/11.3.0/../../../../aarch64-buildroot-linux-gnu/bin/ld: /tmp/tmpsushxijm/lib0.o: Relocations in generic ELF (EM: 62)
/home/srikanth/l4t-gcc/aarch64--glibc--stable-2022.08-1/bin/../lib/gcc/aarch64-buildroot-linux-gnu/11.3.0/../../../../aarch64-buildroot-linux-gnu/bin/ld: /tmp/tmpsushxijm/lib0.o: Relocations in generic ELF (EM: 62)
/home/srikanth/l4t-gcc/aarch64--glibc--stable-2022.08-1/bin/../lib/gcc/aarch64-buildroot-linux-gnu/11.3.0/../../../../aarch64-buildroot-linux-gnu/bin/ld: /tmp/tmpsushxijm/lib0.o: Relocations in generic ELF (EM: 62)
/home/srikanth/l4t-gcc/aarch64--glibc--stable-2022.08-1/bin/../lib/gcc/aarch64-buildroot-linux-gnu/11.3.0/../../../../aarch64-buildroot-linux-gnu/bin/ld: /tmp/tmpsushxijm/lib0.o: Relocations in generic ELF (EM: 62)
/home/srikanth/l4t-gcc/aarch64--glibc--stable-2022.08-1/bin/../lib/gcc/aarch64-buildroot-linux-gnu/11.3.0/../../../../aarch64-buildroot-linux-gnu/bin/ld: /tmp/tmpsushxijm/lib0.o: Relocations in generic ELF (EM: 62)
/home/srikanth/l4t-gcc/aarch64--glibc--stable-2022.08-1/bin/../lib/gcc/aarch64-buildroot-linux-gnu/11.3.0/../../../../aarch64-buildroot-linux-gnu/bin/ld: /tmp/tmpsushxijm/lib0.o: Relocations in generic ELF (EM: 62)
/home/srikanth/l4t-gcc/aarch64--glibc--stable-2022.08-1/bin/../lib/gcc/aarch64-buildroot-linux-gnu/11.3.0/../../../../aarch64-buildroot-linux-gnu/bin/ld: /tmp/tmpsushxijm/lib0.o: Relocations in generic ELF (EM: 62)
/home/srikanth/l4t-gcc/aarch64--glibc--stable-2022.08-1/bin/../lib/gcc/aarch64-buildroot-linux-gnu/11.3.0/../../../../aarch64-buildroot-linux-gnu/bin/ld: /tmp/tmpsushxijm/lib0.o: error adding symbols: file in wrong format
collect2: error: ld returned 1 exit status

Any idea why?
