### ISSUE TITLE
[Question] How to compile arm64 CPU  *.so with using mlc_llm.build?

### ISSUE THREAD

**Issue by KimmyYang** [mlc-ai/mlc-llm#849]
## ❓ General Questions

I can't find any related option (python3 -m mlc_llm.build --help) to compile model to arm64.
How could I compile the vicuna model to arm64 with using mlc_llm.build?

Step 1:
Follow the step to download vicuna : https://mlc.ai/mlc-llm/docs/compilation/get-vicuna-weight.html

Step 2: Compile model (https://mlc.ai/mlc-llm/docs/compilation/compile_models.html)
```
$python3 -m mlc_llm.build --model dist/models/vicuna-v1-7b --target "llvm -device=arm_cpu -mtriple=aarch64-linux-gnu" --max-seq-len 768 --quantization q4f16_0

$file dist/vicuna-v1-7b-q4f16_0/vicuna-v1-7b-q4f16_0-cpu.so
dist/vicuna-v1-7b-q4f16_0/vicuna-v1-7b-q4f16_0-cpu.so: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, BuildID[sha1]=1cc4fc3796d853da66558e1f35db535c43dd7a5e, with debug_info, not stripped
```

**Comment by Hzfengsy** [comment]
We are focusing on GPU devices now, CPU is not supported right now
