### ISSUE TITLE
Dose mlc-llm support parallelism like multi-gpu, multi-node ? 

### ISSUE THREAD

**Issue by xiongjun19** [mlc-ai/mlc-llm#85]
Dose mlc-llm support parallelism like multi-gpu, multi-node ?

**Comment by yzh119** [comment]
Not yet, distributed inference is indeed an interesting topic that is not supported in TVM yet.

**Comment by xiongjun19** [comment]
> Not yet, distributed inference is indeed an interesting topic that is not supported in TVM yet.

Ok thanks

**Comment by junrushao** [comment]
At this moment, this project focuses on single consumer-class GPU, making it possible for everyone to run on their own laptops and phones. We will bring in distributed inference later

**Comment by tqchen** [comment]
This is now supported
