### ISSUE TITLE
[Bug] TVM runtime cannot find vm_load_executable

### ISSUE THREAD

**Issue by KimmyYang** [mlc-ai/mlc-llm#850]
## 🐛 Bug

It seems my `libtvm_runtime.so` can't find `vm_load_executable`, but I can see the .o was built `[ 66%] Building CXX object tvm/CMakeFiles/tvm_runtime_objs.dir/src/runtime/relax_vm/executable.cc.o` and locate in my tvm obj file.
https://github.com/mlc-ai/relax/blob/1b87dce4aee9f82d657808e9b244e335fd3cb8f0/src/runtime/relax_vm/executable.cc#L63

Why `libtvm_runtime.so` still can't find the definition of vm_load_executable?

Error Msg:
```
2023-08-31 17:49:21.060 11130-11130 libc++abi  E  terminating with uncaught exception of type tvm::runtime::InternalError: [17:49:21] /home/kimmy/project2/OpenAI/mlc-llm/cpp/llm_chat.cc:244: InternalError: Check failed: (fload_exec.defined()) is false: TVM runtime cannot find vm_load_executable
```
Code Snippet:
```
this->executable_ = (*tvm::runtime::Registry::Get("runtime.SystemLib"))(model_lib); 
reload_(this->executable_, tvm::runtime::String(model_path)); // <== Exception Here
```

## To Reproduce

1. git clone git@github.com:mlc-ai/mlc-llm.git --recursive
2. python3 ../cmake/gen_cmake_config.py
```
set(TVM_HOME 3rdparty/tvm)
set(CMAKE_BUILD_TYPE RelWithDebInfo)
set(USE_CUDA OFF)
set(USE_CUTLASS OFF)
set(USE_CUBLAS OFF)
set(USE_ROCM OFF)
set(USE_VULKAN OFF)
set(USE_METAL OFF)
set(USE_OPENCL OFF)
```
3. make tvm_runtime
```
/mlc-llm/build/tvm$ ls -l
total 37204
drwxrwxr-x 10 kimmy kimmy     4096  八  31 21:35 CMakeFiles
-rw-rw-r--  1 kimmy kimmy     5482  八  31 21:35 cmake_install.cmake
-rwxrwxr-x  1 kimmy kimmy 36942432  八  31 21:36 libtvm_runtime.so
-rw-rw-r--  1 kimmy kimmy  1129414  八  31 21:35 Makefile
-rw-rw-r--  1 kimmy kimmy      136  八  31 21:35 temp_config_file.cmake
-rw-rw-r--  1 kimmy kimmy     1002  八  31 21:35 tvmConfig.cmake
```
5. Import `mlc-llm/3rdparty/tvm/include` header file and `libtvm_runtime.so` to my CMakefile

## Expected behavior
Find vm_load_executable

## Environment

 - Platform (e.g. WebGPU/Vulkan/IOS/Android/CUDA): Android
 - Operating system (e.g. Ubuntu/Windows/MacOS/...): Ubuntu
 - Device (e.g. iPhone 12 Pro, PC+RTX 3090, ...)
 - How you installed MLC-LLM (`conda`, source):
 - How you installed TVM-Unity (`pip`, source):
 - Python version (e.g. 3.10): 3.10
 - GPU driver version (if applicable):
 - CUDA/cuDNN version (if applicable):
 - TVM Unity Hash Tag (`python -c "import tvm; print('\n'.join(f'{k}: {v}' for k, v in tvm.support.libinfo().items()))"`, applicable if you compile models):
 - Any other relevant information:

**Comment by Hzfengsy** [comment]
Looks like you turned off all possible GPU supports (CUDA, OpenCL, Vulkan and Rocm), which device is expected to run?

**Comment by KimmyYang** [comment]
@Hzfengsy I run on Android device. Do you mean should I enable the OpenCL option when compiled TVM ? Thanks.

**Comment by KimmyYang** [comment]
Re-compiled TVM with enabling `USE_OPENCL=ON` still happen `TVM runtime cannot find vm_load_executable`

Step 1: git clone --recursive git@github.com:mlc-ai/relax.git tvm-unity
Step 2: 
```
set(USE_LLVM /home/kimmy/Android/Sdk/ndk/android-ndk-r26-rc1-linux/android-ndk-r26-beta2/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-config)
set(USE_CUDA   OFF)
set(USE_METAL  OFF)
set(USE_VULKAN OFF)
set(USE_OPENCL ON)
```

Step 3:  
 ```
cmake -DCMAKE_TOOLCHAIN_FILE="${ANDROID_NDK_HOME}/build/cmake/android.toolchain.cmake" \
      -DANDROID_ABI=arm64-v8a \
      -DANDROID_PLATFORM=android-33 \
      -DCMAKE_SYSTEM_VERSION=1 \
      -DCMAKE_CXX_COMPILER="${ANDROID_NDK_HOME}/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android33-clang++" \
      -DCMAKE_C_COMPILER="${ANDROID_NDK_HOME}/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android33-clang" \
      -DMLC_LOG_STACK_TRACE=ON \
      -DMACHINE_NAME="aarch64-linux-clang" ..
```
Step 4: make tvm_runtime -j8

**Comment by Hzfengsy** [comment]
For Android uses, here is the docs: https://mlc.ai/mlc-llm/docs/deploy/android.html

**Comment by KimmyYang** [comment]
@Hzfengsy It's possible to build android llm_model.tar to llm_model.so by using mlc_llm.build? Thanks.

**Comment by Hzfengsy** [comment]
Try to set the target from `android` to `android-dylib` , with the following env:
```
export TVM_NDK_CC="${ANDROID_NDK_HOME}/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android28-clang"
```

Note that this method is only used for debug for now, not the offcial support.

**Comment by KimmyYang** [comment]
> Try to set the target from `android` to `android-dylib` , with the following env:
> 
> ```
> export TVM_NDK_CC="${ANDROID_NDK_HOME}/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android28-clang"
> ```
> 
> Note that this method is only used for debug for now, not the offcial support.

Thanks a lot. It works.

**Comment by varunlmxd** [comment]
I ran into the same issue, what I realized is to run a model you need to have {MODEL_NAME}-${QUANTIZATION}-android.tar this file for the particular model you want to run in the application.
