### ISSUE TITLE
[Feature Request] How to get execution breakup (GPU vs CPU) when running llama model on android using OPENCL=ON

### ISSUE THREAD

**Issue by Ramees025** [mlc-ai/mlc-llm#854]
Hi,

I am running, llama model with q8f16_1 quantization on android device (build from source, both relax and mlc-llm). 
It run successfully. 
I would like to know, How to check the execution break up( which layers really ran on GPU? which layers fall back to CPU?).

Or is it like, when i use DUSE_OPENCL=ON, all the layers will run on GPU?

Regards

**Comment by Hzfengsy** [comment]
MLC-LLM runs the whole model on GPUs. We do not have CPU support right now

**Comment by BarfingLemurs** [comment]
@Ramees025 may I ask if you could share the binaries and apk?

**Comment by xukui1203** [comment]
@Hzfengsy Do you have plan to support Android CPU backend? The GPU is used by other display process in our system, so we hope  MLC-LLM can run on CPU.

**Comment by tqchen** [comment]
Closing as original question has been answered. As of now we are focusing on GPU and possibly NPU. CPU can in theory be supported through tvm but there is no specific plan to optimize yet.
