### ISSUE TITLE
[Question] Cannot install TVM Unity

### ISSUE THREAD

**Issue by empty2enrich** [mlc-ai/mlc-llm#857]
## ❓ General Questions
I downloaded the installation package, but the installation failed！
（mlc_ai_nightly_cu117-0.12.dev1453-cp39-cp39-manylinux_2_28_x86_64.whl  mlc_chat_nightly_cu117-0.1.dev397-cp39-cp39-manylinux_2_28_x86_64.whl）

error log:
ERROR: mlc_ai_nightly_cu117-0.12.dev1453-cp39-cp39-manylinux_2_28_x86_64.whl is not a supported wheel on this platform.

System:
centos 7.9

**Comment by wangzy0327** [comment]
could you solve the problem? I also met this question @empty2enrich

**Comment by wangzhaode** [comment]
Same question.

```shell
 ➜  ~ python -m pip install -v mlc_ai_nightly-0.12.dev1689-cp39-cp39-manylinux_2_28_x86_64.whl
Using pip 23.2.1 from /home/yanxing/miniconda3/lib/python3.9/site-packages/pip (python 3.9)
ERROR: mlc_ai_nightly-0.12.dev1689-cp39-cp39-manylinux_2_28_x86_64.whl is not a supported wheel on this platform.
```

**Comment by wangzy0327** [comment]
> Same question.
> 
> ```shell
>  ➜  ~ python -m pip install -v mlc_ai_nightly-0.12.dev1689-cp39-cp39-manylinux_2_28_x86_64.whl
> Using pip 23.2.1 from /home/yanxing/miniconda3/lib/python3.9/site-packages/pip (python 3.9)
> ERROR: mlc_ai_nightly-0.12.dev1689-cp39-cp39-manylinux_2_28_x86_64.whl is not a supported wheel on this platform.
> ```

I have solved the problem by update linux system version. @wangzhaode 
I suggest you to try ubuntu 20.04 version.

**Comment by wangzhaode** [comment]
> > Same question.
> > ```shell
> >  ➜  ~ python -m pip install -v mlc_ai_nightly-0.12.dev1689-cp39-cp39-manylinux_2_28_x86_64.whl
> > Using pip 23.2.1 from /home/yanxing/miniconda3/lib/python3.9/site-packages/pip (python 3.9)
> > ERROR: mlc_ai_nightly-0.12.dev1689-cp39-cp39-manylinux_2_28_x86_64.whl is not a supported wheel on this platform.
> > ```
> 
> I have solved the problem by update linux system version. @wangzhaode I suggest you to try ubuntu 20.04 version.

Thanks! But my system can't update. I'm trying compile it by myself.
