### ISSUE TITLE
[Bug] After complied in Windows with llvm-mingw for Chatglm2-6B, Chinese garbled shown and model could not catch any Chinese words instead of English language.

### ISSUE THREAD

**Issue by ZCloud2014** [mlc-ai/mlc-llm#864]
1.install in windows and complied the model with chatglm2-6b with vulkan and llvm-mingw
2. Model complied and succeeded.
3. When run in windows,  all Chinese garbled.

**Comment by davidpissarra** [comment]
Can you please provide examples and the environment so that I could reproduce this?

**Comment by ZCloud2014** [comment]
![WX20230906-174818](https://github.com/mlc-ai/mlc-llm/assets/126860364/83a757b4-b1a2-4620-b3c5-2a6de5b50057)
System: Windows 10 Pro 22H2
LLVM 10.0.0
Others is install as the requirement list.
