### ISSUE TITLE
What commit was the apk built using? 

### ISSUE THREAD

**Issue by Lucyan11** [mlc-ai/mlc-llm#865]
## ❓ General Questions

@cyx-6 hello.

What was the original commit that was used to build the apk for android that ran the vicuna?

Somewhere in a commit/update, the android version stopped being able to initiate chat and the buttons stopped working.  But 1 of the commits had to have the secret sauce that allowed vicuna to run on a android mobile.

Please help

**Comment by cyx-6** [comment]
Hi @Lucyan11, thanks for reaching out. Actually, our Android APK released is kinda outdated. And we shall release a new version soon, and bring more information in release. :)

**Comment by Lucyan11** [comment]
BAM!!!

Galaxy A52 5g running red pajama from source build!!!
![Screenshot_20230904_211020_MLCChat](https://github.com/mlc-ai/mlc-llm/assets/122138129/9c92dc11-32fb-4c68-9b8c-4abadf306802)

So awesome!!!

**Comment by cyx-6** [comment]
@BarfingLemurs Yes, we shall integrate this update in new released apk.
