### ISSUE TITLE
[Bug] Unable to install MLC-AI & MLC-Chat on Ubuntu 18.04 LTS via pre-build packages

### ISSUE THREAD

**Issue by Matthieu-Tinycoaching** [mlc-ai/mlc-llm#870]
## 🐛 Bug

I didn't manage to install MLC-AI & MLC-Chat on Ubuntu 18.04 LTS via pre-build packages as described here: https://mlc.ai/mlc-llm/docs/install/tvm.html#install-tvm-unity

## To Reproduce

I have an `RTX 3090` and `CUDA 11.6` installed and when launching the required install command: `pip install --pre --force-reinstall mlc-ai-nightly-cu116 mlc-chat-nightly-cu116 -f https://mlc.ai/wheels`

I got the following error message:
```
ERROR: Could not find a version that satisfies the requirement mlc-ai-nightly-cu116 (from versions: none)
ERROR: No matching distribution found for mlc-ai-nightly-cu116
```
Is there a workaround to install them on my machine?

## Environment

 - Platform (e.g. WebGPU/Vulkan/IOS/Android/CUDA):  CUDA 11.6
 - Operating system (e.g. Ubuntu/Windows/MacOS/...): Ubuntu 18.04 LTS
 - Device (e.g. iPhone 12 Pro, PC+RTX 3090, ...): RTX 3090
 - How you installed TVM-Unity (`pip`, source): pip
 - Python version (e.g. 3.10): 3.8.17

**Comment by LIzhiqian-cassie** [comment]
did you solve this? I met the same problem

**Comment by Matthieu-Tinycoaching** [comment]
I finished by upgrading Ubuntu to 22.04

**Comment by tqchen** [comment]
This is likely due to the Ubuntu libc issue. Upgrading glibc or use latest LTS should work
