### ISSUE TITLE
[Question] 

### ISSUE THREAD

**Issue by jsadecki1** [mlc-ai/mlc-llm#871]
## ❓ General Questions

Hello, thanks for reading,

where do i find other URLs to add into the MLC android ap please, im very new to this and only gathered from chatGPT to add URLs from huggingface main apges on models but none of them seem to work, thanks for any help

**Comment by tqchen** [comment]
We need to add models that are leverages the same model library that means model architecture as the llama2 as being supported in the app and converted through mlc
