### ISSUE TITLE
Android Studio Emulator

### ISSUE THREAD

**Issue by Lucyan11** [mlc-ai/mlc-llm#872]
## ❓ General Questions
Do none of the emulators work for this in android studio.  Loads the app and then crashes.  Any insite would be amazing

**Comment by junrushao** [comment]
We require actual phones to run MLC because MLC uses GPUs to accelerate. Emulators would not work unfortunately because it's challenging to emulate GPUs

**Comment by Lucyan11** [comment]
@junrushao thank you so much. Been racking my brain for hours thinking i as a dumb dumb.

1 more question.  Will it run on this?

AOCWEI 10 Inch Tablet Android 13 Tablets 2024 with Keyboard, 12GB RAM 128GB ROM 512GB Expand, 5G/2.4G WiFi, HD IPS Display, 8000mAh Tablet PC with Mouse GPS Split Screen Support -X900(Blue)

**Comment by Hzfengsy** [comment]
It should work, free feel to have a try :)
