### ISSUE TITLE
[Question] CLI Model Failed

### ISSUE THREAD

**Issue by tjhxwbp** [mlc-ai/mlc-llm#876]
## ❓ General Questions

`git clone https://github.com/mlc-ai/binary-mlc-llm-libs.git d:\prebuilt\lib`
`git clone https://huggingface.co/mlc-ai/mlc-chat-Llama-2-7b-chat-hf-q4f16_1 d:\prebuilt`

I executed these commands, but there are still errors, what should I do?

```
D:\>mlc_chat_cli --model D:\prebuilt\mlc-chat-Llama-2-7b-chat-hf-q4f16_1
Use MLC config: "D:\\prebuilt\\mlc-chat-Llama-2-7b-chat-hf-q4f16_1\\mlc-chat-config.json"
Use model weights: "D:\\prebuilt\\mlc-chat-Llama-2-7b-chat-hf-q4f16_1\\ndarray-cache.json"
[16:38:13] C:\Miniconda\envs\mlc-llm-build\conda-bld\mlc-chat-cli-nightly-package_1693890509158\work\cpp\cli_main.cc:377: Cannot find the model library that corresponds to `Llama-2-7b-chat-hf-q4f16_1`.
We searched over the following possible paths:
- Llama-2-7b-chat-hf-q4f16_1
- dist/prebuilt/lib
- dist/D:\prebuilt\mlc-chat-Llama-2-7b-chat-hf-q4f16_1
- dist/prebuilt/Llama-2-7b-chat-hf-q4f16_1
Stack trace not available when DMLC_LOG_STACK_TRACE is disabled at compile time.
```

**Comment by fritol** [comment]
same here 
this is some BOGUS path `C:\Miniconda\envs\mlc-llm-build\conda-bld\mlc-chat-cli-nightly-package_1693890509158\work\cpp\cli_main.c`
i dont have `C:\Miniconda\`

**Comment by David-Sharma** [comment]
The follow information should help.
https://mlc.ai/mlc-llm/#windows-linux-mac

**Comment by David-Sharma** [comment]
This is what I did to get started
-I ran the following from the \user\XXXX base directory

https://mlc.ai/mlc-llm/#windows-linux-mac
