### ISSUE TITLE
[Question] Speed of GPTQ transformer vs MLC ?

### ISSUE THREAD

**Issue by Matthieu-Tinycoaching** [mlc-ai/mlc-llm#882]
Hi,

Thanks for this great library!

I have one question since Transformers has enabled inference of GPTQ models: why inference of quantized (GPTQ) model with MLC faster than quantized (GPTQ) model with Transformers library?

Is this because of the C++ compilation or something else?

**Comment by junrushao** [comment]
BTW which specific repo are you referring to?

**Comment by Matthieu-Tinycoaching** [comment]
https://huggingface.co/lmsys/vicuna-7b-v1.5 for the non quantized model.

And https://huggingface.co/TheBloke/vicuna-7B-v1.5-GPTQ for the GPTQ one.

**Comment by junrushao** [comment]
As the underlying compiler that AutoGPT uses, Triton isn't actually performant in most of the cases I've seen. It's programming interface is really nice but probably isn't good for squeezing performance.
