### ISSUE TITLE
[Bug] Error to compile android Llama-2-7b model

### ISSUE THREAD

**Issue by Sunnyday2016** [mlc-ai/mlc-llm#886]
## 🐛 Bug

After compiled tvm with set(USE_OPENCL ON) and installed mlc_llm, when I tryed to follow the instructions in compile_modles.rst by running python3 -m mlc_llm.build --model Llama-2-7b-chat-hf --target android --max-seq-len 768 --quantization q4f16_1

I got the following errors:

Using path "Llama-2-7b-chat-hf" for model "Llama-2-7b-chat-hf"
Target configured: opencl -keys=opencl,gpu -max_function_args=128 -max_num_threads=256 -max_shared_memory_per_block=16384 -max_threads_per_block=256 -texture_spatial_limit=16384 -thread_warp_size=1
Automatically using target for weight quantization: opencl -keys=opencl,gpu -max_function_args=128 -max_num_threads=256 -max_shared_memory_per_block=16384 -max_threads_per_block=256 -texture_spatial_limit=16384 -thread_warp_size=1
Start computing and quantizing weights... This may take a while.
UNSUPPORTED (log once): createKernel: newComputePipelineState failed
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/Users/yi/miniconda3/lib/python3.11/site-packages/mlc_llm/build.py", line 13, in <module>
    main()
  File "/Users/yi/miniconda3/lib/python3.11/site-packages/mlc_llm/build.py", line 10, in main
    core.build_model_from_args(parsed_args)
  File "/Users/yi/miniconda3/lib/python3.11/site-packages/mlc_llm/core.py", line 575, in build_model_from_args
    new_params = utils.convert_weights(param_manager, params, args)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/yi/miniconda3/lib/python3.11/site-packages/mlc_llm/utils.py", line 258, in convert_weights
    vm["transform_params"]()
  File "/Users/yi/dev/git/mlc-llm/3rdparty/tvm/python/tvm/_ffi/_ctypes/packed_func.py", line 238, in __call__
    raise get_last_ffi_error()
tvm.error.InternalError: Traceback (most recent call last):
  [bt] (8) 9   libtvm.dylib                        0x0000000155470b70 tvm::runtime::PackedFuncObj::Extractor<tvm::runtime::PackedFuncSubObj<tvm::runtime::relax_vm::VirtualMachineImpl::GetClosureInternal(tvm::runtime::String const&, bool)::$_14> >::Call(tvm::runtime::PackedFuncObj const*, tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*) + 204
  [bt] (7) 8   libtvm.dylib                        0x000000015546bcbc tvm::runtime::relax_vm::VirtualMachineImpl::InvokeBytecode(long long, std::__1::vector<tvm::runtime::TVMRetValue, std::__1::allocator<tvm::runtime::TVMRetValue> > const&) + 360
  [bt] (6) 7   libtvm.dylib                        0x000000015546c010 tvm::runtime::relax_vm::VirtualMachineImpl::RunLoop() + 100
  [bt] (5) 6   libtvm.dylib                        0x000000015546c8d4 tvm::runtime::relax_vm::VirtualMachineImpl::RunInstrCall(tvm::runtime::relax_vm::VMFrame*, tvm::runtime::relax_vm::Instruction) + 1484
  [bt] (4) 5   libtvm.dylib                        0x000000015546acac tvm::runtime::relax_vm::VirtualMachineImpl::InvokeClosurePacked(tvm::runtime::ObjectRef const&, tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*) + 96
  [bt] (3) 4   libtvm.dylib                        0x00000001553f7a88 tvm::runtime::PackedFuncObj::Extractor<tvm::runtime::PackedFuncSubObj<tvm::runtime::WrapPackedFunc(int (*)(TVMValue*, int*, int, TVMValue*, int*, void*), tvm::runtime::ObjectPtr<tvm::runtime::Object> const&)::$_0> >::Call(tvm::runtime::PackedFuncObj const*, tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*) + 200
  [bt] (2) 3   libtvm.dylib                        0x0000000153037ecc __clang_call_terminate + 0
  [bt] (1) 2   libtvm.dylib                        0x000000015303b2c8 tvm::runtime::detail::LogFatal::Entry::Finalize() + 0
  [bt] (0) 1   libtvm.dylib                        0x000000015303b30c tvm::runtime::detail::LogFatal::Entry::Finalize() + 68
  [bt] (8) 9   libtvm.dylib                        0x000000015546acac tvm::runtime::relax_vm::VirtualMachineImpl::InvokeClosurePacked(tvm::runtime::ObjectRef const&, tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*) + 96
  [bt] (7) 8   ???                                 0x0000000126d19cb0 0x0 + 4946238640
  [bt] (6) 7   libtvm.dylib                        0x00000001553cdbd8 TVMFuncCall + 60
  [bt] (5) 6   libtvm.dylib                        0x0000000155507e8c tvm::runtime::PackedFuncObj::Extractor<tvm::runtime::PackedFuncSubObj<tvm::runtime::PackedFunc tvm::runtime::detail::PackFuncVoidAddr_<4, tvm::runtime::OpenCLWrappedFunc>(tvm::runtime::OpenCLWrappedFunc, std::__1::vector<tvm::runtime::detail::ArgConvertCode, std::__1::allocator<tvm::runtime::detail::ArgConvertCode> > const&)::'lambda'(tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*)> >::Call(tvm::runtime::PackedFuncObj const*, tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*) + 172
  [bt] (4) 5   libtvm.dylib                        0x0000000155507f68 tvm::runtime::OpenCLWrappedFunc::operator()(tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*, void**) const + 208
  [bt] (3) 4   libtvm.dylib                        0x0000000155503ffc tvm::runtime::OpenCLModuleNode::InstallKernel(tvm::runtime::cl::OpenCLWorkspace*, tvm::runtime::cl::OpenCLThreadEntry*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, tvm::runtime::OpenCLModuleNodeBase::KTRefEntry const&) + 1764
  [bt] (2) 3   libtvm.dylib                        0x0000000153037ecc __clang_call_terminate + 0
  [bt] (1) 2   libtvm.dylib                        0x000000015303b2c8 tvm::runtime::detail::LogFatal::Entry::Finalize() + 0
  [bt] (0) 1   libtvm.dylib                        0x000000015303b30c tvm::runtime::detail::LogFatal::Entry::Finalize() + 68
  File "/Users/yi/dev/git/mlc-llm/3rdparty/tvm/src/runtime/opencl/opencl_module.cc", line 263
  File "/Users/yi/dev/git/mlc-llm/3rdparty/tvm/src/runtime/library_module.cc", line 87
InternalError: Check failed: (err == CL_SUCCESS) is false: OpenCL Error, code=-48: CL_INVALID_KERNEL

seems  the openCL createProgram succeeded but falied when create newComputePipelineState kernel. I searched newComputePipelineState, but only found for metal.

## To Reproduce

1. follow the instructions in tvm.rst and set(USE_OPENCL ON) to enable opencl
2. pip install tvm and mlc_llm
3. clone Llama-2-7b-chat-hf from git clone https://huggingface.co/meta-llama/Llama-2-7b-chat-hf and run python3 -m mlc_llm.build --model Llama-2-7b-chat-hf --target android --max-seq-len 768 --quantization q4f16_1

## Environment

 - Platform (e.g. WebGPU/Vulkan/IOS/Android/CUDA): Android
 - Operating system (e.g. Ubuntu/Windows/MacOS/...): MacOS M1 Pro
 - Device (e.g. iPhone 12 Pro, PC+RTX 3090, ...) 8Gen2
 - How you installed MLC-LLM (`conda`, source): source
 - How you installed TVM-Unity (`pip`, source): source
 - Python version (e.g. 3.10): 3.11
 - GPU driver version (if applicable):
 - CUDA/cuDNN version (if applicable):
 - TVM Unity Hash Tag (`python -c "import tvm; print('\n'.join(f'{k}: {v}' for k, v in tvm.support.libinfo().items()))"`, applicable if you compile models):
 - Any other relevant information:

**Comment by Hzfengsy** [comment]
The quantization step utilize your host GPU (metal on Mac) instead of the target GPU (opencl on android). So you need to turn on Metal when building TVM-Unity, or directly instead via prebuilt pip wheel

**Comment by CharlieFRuan** [comment]
Closing the issue for now due to inactivity. Feel free to reopen if there are further questions!
