### ISSUE TITLE
[Question] Why is the inference speed of the q4fp16 quantized model faster than the autogptq quantized model?

### ISSUE THREAD

**Issue by pangr** [mlc-ai/mlc-llm#887]
## ❓ General Questions

I used q4fp16 and autogptq-llama-q4fp16 to quantify the llama2 7B model and found that the inference speed of q4fp16 is more than twice as fast as that of autogptq-llama-q4fp16. What is the reason? Is there a difference in the dequantization operation, q4fp16 What is the quantification method used

**Comment by junrushao** [comment]
AutoGPT uses Triton, which is slower than TVM-based solution as most of our experiments. There is no difference in computation.

**Comment by pangr** [comment]
> Triton
Does mlc-llm inference autogptq-llama-q4fp16 model also use Triton?

**Comment by pangr** [comment]
> AutoGPT uses Triton, which is slower than TVM-based solution as most of our experiments. There is no difference in computation.

Does mlc-llm inference autogptq-llama-q4fp16 model also use Triton?

**Comment by junrushao** [comment]
No. MLC LLM uses Apache TVM, which is faster than OpenAI Triton

**Comment by pangr** [comment]
> No. MLC LLM uses Apache TVM, which is faster than OpenAI Triton

Thank you for your reply，In my case, I used mlc-llm to quantify the model in two ways: `q4fp16` and `autp_llama_q4fp16`. Then I used `mlc-llm` to test the inference speed of the two quantized models respectively. I found that the inference speed of the q4fp16 model is faster than autp_llama_q4fp16.
