### ISSUE TITLE
[Question] Why is the inference speed of the q4fp16 quantized model faster than the autgptq_llama_q4fp16 quantized model?

### ISSUE THREAD

**Issue by pangr** [mlc-ai/mlc-llm#894]
## ❓ General Questions

 I used mlc-llm to quantify the model in two ways: q4fp16 and autp_llama_q4fp16. Then I used mlc-llm to test the inference speed of the two quantized models respectively. I found that the inference speed of the q4fp16 model is faster than autgptq_llama_q4fp16.

**Comment by tqchen** [comment]
This is likely because of the layout issue for now. A solution would be to add layout conversion to a preferred layout for the hw. As of now indeed the native format is faster
