### ISSUE TITLE
[Feature Request] Support InternLM Deploy

### ISSUE THREAD

**Issue by vansinhu** [mlc-ai/mlc-llm#898]
Dear mlc-llm developer,

Greetings! I am vansinhu, a community developer and volunteer at InternLM. [InternLM](https://github.com/InternLM/InternLM) is a large language model similar to llama2, and we look forward to InternLM being supported in mlc-llm. If there are any challenges or inquiries regarding support for InternLM, please feel free to join our Discord discussion at https://discord.gg/gF9ezcmtM3. 

Best regards,
vansinhu

**Comment by tqchen** [comment]
Thanks for reaching out, we would love contributions to add InternLM support :)

**Comment by MasterJH5574** [comment]
InternLM is supported now.
