### ISSUE TITLE
[Question] Batched Inference

### ISSUE THREAD

**Issue by varshith15** [mlc-ai/mlc-llm#904]
@junrushao
1.  I see that MLC doesn't currently support batched inference, is there any work being done there? I'd love to pick it up otherwise
2. I think there should also be support for something like model.generate() api instead of going through the whole chat module, thoughts?

I'd love to contribute to the above features, if you can please help me on where to get started

**Comment by junrushao** [comment]
> I see that MLC doesn't currently support batched inference, is there any work being done there? I'd love to pick it up otherwise

@MasterJH5574 and @vinx13 are leading the effort of batched inference in terms of introducing paged attention, continuous batching and guaranteeing performance in batch mode

> I think there should also be support for something like model.generate() api instead of going through the whole chat module, thoughts?

This is great question. @tqchen thoughts?

**Comment by varshith15** [comment]
> > I see that MLC doesn't currently support batched inference, is there any work being done there? I'd love to pick it up otherwise
> 
> @MasterJH5574 and @vinx13 are leading the effort of batched inference in terms of introducing paged attention, continuous batching and guaranteeing performance in batch mode

@MasterJH5574 @vinx13 can i help contribute to it in some capacity?

**Comment by hanrui1sensetime** [comment]
> > I see that MLC doesn't currently support batched inference, is there any work being done there? I'd love to pick it up otherwise
> 
> @MasterJH5574 and @vinx13 are leading the effort of batched inference in terms of introducing paged attention, continuous batching and guaranteeing performance in batch mode
> 
> > I think there should also be support for something like model.generate() api instead of going through the whole chat module, thoughts?
> 
> This is great question. @tqchen thoughts?

Is there some developing branch opened sourse? Or we should stay tuned for the batch inference features?

**Comment by 0x1997** [comment]
> > I see that MLC doesn't currently support batched inference, is there any work being done there? I'd love to pick it up otherwise
> 
> @MasterJH5574 and @vinx13 are leading the effort of batched inference in terms of introducing paged attention, continuous batching and guaranteeing performance in batch mode

Any updates?

**Comment by moinnadeem** [comment]
Hi, I would also be interested in this -- do you have an update?

**Comment by tqchen** [comment]
consolidating to https://github.com/mlc-ai/mlc-llm/issues/1118
