### ISSUE TITLE
[Model Request] Microsoft phi-1.5

### ISSUE THREAD

**Issue by acalatrava** [mlc-ai/mlc-llm#905]
## ⚙️  Request New Models

- Link to an existing implementation (e.g. Hugging Face/Github): https://huggingface.co/microsoft/phi-1_5
- Is this model architecture supported by MLC-LLM? (the list of [supported models](https://mlc.ai/mlc-llm/docs/prebuilt_models.html)) No

## Additional context
This would be a great addition to MLC-LLM since it has only 1.5B parameters and therefor it will use very little RAM making it very suitable for mobile devices.

**Comment by nundys** [comment]
Will this also work for phi-2?

**Comment by CharlieFRuan** [comment]
Phi 1.5 and phi 2 are supported now, and prebuilts are uploaded: https://llm.mlc.ai/docs/prebuilt_models.html#level-1-supported-model-architectures-the-all-in-one-table

**Comment by coder543** [comment]
@CharlieFRuan On the iOS app, I no longer see a way to add a model from a URL. Phi-2 (and/or the Dolphin fine tune) seem like a perfect fit for the limited resources of a smartphone. Phi-2 was just relicensed by Microsoft with the MIT license, which makes it more interesting than it was.

**Comment by CharlieFRuan** [comment]
@coder543 Thanks for the inquiry! We are looking into integrating phi into iOS, Android, and web-llm and may take a bit of time.

cc @davidpissarra If you have the bandwidth, would you mind perhaps adding phi-2 into iOS after SLMify-ing iOS?

cc @Kartik14 Would be great to have phi in Android as well!

**Comment by Kartik14** [comment]
@CharlieFRuan Sure I will take a look
