### ISSUE TITLE
After I run "pip install .",I try to  verify installation,so I try "python3 -m mlc_llm.build --help",and there is a problem

### ISSUE THREAD

**Issue by ChenJY1221** [mlc-ai/mlc-llm#908]
## ❓ General Questions
the command line report: ImportError: cannot import name 'relax' from 'tvm'
my python version is Python 3.8.18
so have others meet this problem? I would appreciate it if you could tell me how to solve this problem

**Comment by Hzfengsy** [comment]
You might install the wrong version of TVM, mlc-llm requires TVM Unity

**Comment by junrushao** [comment]
This should be helpful to your case https://mlc.ai/mlc-llm/docs/install/tvm.html

**Comment by ChenJY1221** [comment]
@Hzfengsy thank for you response! I will try this method soon.

**Comment by ChenJY1221** [comment]
I solved that problem I met before.However there is a new problem.I try "make -j4" in my "path/to/tvm-unity/build",and it reports that :
"
collect2: error: ld returned 1 exit status
collect2: error: ld returned 1 exit status
CMakeFiles/tvm.dir/build.make:1916: recipe for target 'libtvm.so' failed
make[2]: *** [libtvm.so] Error 1
CMakeFiles/tvm_allvisible.dir/build.make:1916: recipe for target 'libtvm_allvisible.so' failed
make[2]: *** [libtvm_allvisible.so] Error 1
CMakeFiles/Makefile2:259: recipe for target 'CMakeFiles/tvm_allvisible.dir/all' failed
make[1]: *** [CMakeFiles/tvm_allvisible.dir/all] Error 2
make[1]: *** 正在等待未完成的任务....
CMakeFiles/Makefile2:176: recipe for target 'CMakeFiles/tvm.dir/all' failed
make[1]: *** [CMakeFiles/tvm.dir/all] Error 2
Makefile:135: recipe for target 'all' failed
make: *** [all] Error 2
"
I don't know why I will meet such problem.
cmake version 3.27.5
GNU ld (GNU Binutils for Ubuntu) 2.30
gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
g++ (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Python 3.6.9

**Comment by Hzfengsy** [comment]
TVM Unity requires Python 3.7+ and a cpp compiler with full support of CXX17 standard. 

BTW, ubuntu 18.04 has ended its life, and we will not officially support it

**Comment by ChenJY1221** [comment]
@Hzfengsy thx,I try to install a new virtual machine now,I hope my problem can be solved this time 55

**Comment by vfdff** [comment]
@ChenJY1221  Do you fix this issue at final ?
