### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by qc903113684** [mlc-ai/mlc-llm#909]
## 🐛 Bug
Directly compile llama-7b-hf on Android response string contains USER: XXXX, ASSISTANT:XXXX

## To Reproduce

1. download llama-7b-hf from https://huggingface.co/decapoda-research/llama-7b-hf
2. python build.py --model llama-7b-hf --quantization q4f16_1 --target android --max-seq-len 768
3. build Android apk
4. ask who are u? and response string contains USER: XXXX, ASSISTANT:XXXX

## Expected behavior

May be mlcllm accidentally deserialized context and act into the response string? Because I used vicuna weight and llama network to build a vicuna-7b, its response dont include USER and ASSISTANTS

## Environment

 - Platform (e.g. WebGPU/Vulkan/IOS/Android/CUDA): Android
 - Operating system (e.g. Ubuntu/Windows/MacOS/...): Ubuntu
 - Device (e.g. iPhone 12 Pro, PC+RTX 3090, ...): snapdragon 8gen2 phone
 - How you installed MLC-LLM (`conda`, source): git
 - How you installed TVM-Unity (`pip`, source): pip
 - Python version (e.g. 3.10): 3.8
 - TVM Unity Hash Tag (`python -c "import tvm; print('\n'.join(f'{k}: {v}' for k, v in tvm.support.libinfo().items()))"`, applicable if you compile models): 6d1932ba16c44ce4cfboe23dbadebe957916042a

**Comment by junrushao** [comment]
It's recommended to use latest Llama2 and latest MLC
