### ISSUE TITLE
Seriously what was that?

### ISSUE THREAD

**Issue by Alimazraeh** [mlc-ai/mlc-llm#91]
![image](https://user-images.githubusercontent.com/19336248/236444935-b9d2a82b-75a9-4b83-aad7-545944c4c7ba.png)

**Comment by junrushao** [comment]
I'm not sure, but Vicuna-7b as a language model it definitely suffers from potential hallucination

**Comment by tqchen** [comment]
closing as there is no actionable items atm ,feel free to bring up more in the community discord
