### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by linjie830914** [mlc-ai/mlc-llm#911]
## To Reproduce

1.
![04cc239ceb6f9a947f3ed21c1fff864](https://github.com/mlc-ai/mlc-llm/assets/7983557/873eb45a-d162-4ae8-95aa-1df43c5a9024)

## Environment

 - Platform (e.g. WebGPU/Vulkan/IOS/Android/CUDA):
 - Operating system (e.g. Windows):
 - Device (NVIDIA GeForce GTX 1650)
 - How you installed MLC-LLM (`conda`,):
 - Python version (e.g. Python 3.11.4):
 - GPU driver version (31.0.15.3713):

**Comment by linjie830914** [comment]
How to execute the model in the latest version of 'mlc_chat_cli'

**Comment by junrushao** [comment]
the last line of the info msg should be informative:

![image](https://github.com/mlc-ai/mlc-llm/assets/22515877/d4496359-fadf-43d7-b1bb-097fe4b5f2cf)
