### ISSUE TITLE
[Bug]  Check failed: (partial_update) is false: Key "vocab_size" not found.

### ISSUE THREAD

**Issue by x330930520** [mlc-ai/mlc-llm#913]
## 🐛 Bug

execute prebuilt binary with error.
`[19:51:22] C:\Miniconda\envs\mlc-llm-build\conda-bld\mlc-chat-cli-nightly-package_1694668248240\work\cpp\llm_chat.cc:354: Check failed: (partial_update) is false: Key "vocab_size" not found.
Stack trace not available when DMLC_LOG_STACK_TRACE is disabled at compile time.`

## To Reproduce
![image](https://github.com/mlc-ai/mlc-llm/assets/9064969/dda0b060-9788-4e43-8229-9de6e8d9a87c)

## Environment

 - Platform (e.g. WebGPU/Vulkan/IOS/Android/CUDA): Vulkan
 - Operating system (e.g. Ubuntu/Windows/MacOS/...): Windows 11
 - Device (e.g. iPhone 12 Pro, PC+RTX 3090, ...) AMD 3550H
 - How you installed MLC-LLM (`conda`, source): conda
 - How you installed TVM-Unity (`pip`, source):
 - Python version (e.g. 3.10): 3.10.9
 - GPU driver version (if applicable):
 - CUDA/cuDNN version (if applicable):
 - TVM Unity Hash Tag (`python -c "import tvm; print('\n'.join(f'{k}: {v}' for k, v in tvm.support.libinfo().items()))"`, applicable if you compile models):
 - Any other relevant information:

**Comment by Alumniminium** [comment]
same on linux
