### ISSUE TITLE
[Bug] Can not install TVM Unity via prebuilt package on Apple M1 chip

### ISSUE THREAD

**Issue by rayrayraykk** [mlc-ai/mlc-llm#914]
## 🐛 Bug
```
ERROR: mlc_ai_nightly-0.12.dev1573-cp39-cp39-macosx_13_0_arm64.whl is not a supported wheel on this platform.
```

## Environment

 - Platform (e.g. WebGPU/Vulkan/IOS/Android/CUDA): -
 - Operating system (e.g. Ubuntu/Windows/MacOS/...): MacOS
 - Device (e.g. iPhone 12 Pro, PC+RTX 3090, ...) M1 chip
 - How you installed MLC-LLM (`conda`, source): source
 - How you installed TVM-Unity (`pip`, source): pip
 - Python version (e.g. 3.10): 3.9
 - GPU driver version (if applicable): -
 - CUDA/cuDNN version (if applicable): -
 - TVM Unity Hash Tag (`python -c "import tvm; print('\n'.join(f'{k}: {v}' for k, v in tvm.support.libinfo().items()))"`, applicable if you compile models): - 
 - Any other relevant information:

I tried every python version but got the error. Btw, my macos is 13.5.2.
Can you help me with this?
And I tried to build from source, but it seems to take hours. And my memory is only 16GB.

**Comment by junrushao** [comment]
Not sure what the root cause is, but it's not an isolated case. Do you have more info why it's not a supported wheel from pip?

**Comment by anushreedhople** [comment]
@rayrayraykk did you compile from source or were you able to use the prebuilt package?
I have the right conda installed for M1 chip (platform : osx-arm64) but I see the same error.

**Comment by junrushao** [comment]
@anushreedhople it could happen as well if your macOS is a bit outdated. would you like to double check?

**Comment by anushreedhople** [comment]
You are right. I got it working soon after looking at the wheels. Having the correct conda and osx 13.x are the only requirements. It works fine beyond that. Thank you for sharing this project @junrushao
