### ISSUE TITLE
no enough to run app for iPhone 14 pro max

### ISSUE THREAD

**Issue by mccoysc** [mlc-ai/mlc-llm#94]
report "not have 4GB memory for run app" when start the app on iPhone 14 pro max 256.

if the device can not run this app,may be no device can run.

**Comment by tqchen** [comment]
This is on DRAM requirement, not exactly sure  in your case thogh, since normally pro max is ok.

**Comment by mccoysc** [comment]
> This is on DRAM requirement, not exactly sure  in your case though, since normally pro max is ok (the app comes with require extra dram requirement to the system).

but for me and for my friend,none of the iphone can be run.
and in fact,any memory need more than GBs is not good for any app.

**Comment by mccoysc** [comment]
and,if i restart my iPhone 14 ProMax,the app can not run.

**Comment by junrushao** [comment]
This is weird because my 14 pro runs properly without this issue. 14 ProMax comes with 6GB memory, which means they should work smoothly without the issue you guys mentioned.

**Comment by dajunli** [comment]
I will also encounter the same issue when testing under iPhone OS 16.0.4, but it will work normally under 16.4.1. Please check your system version to see if Apple's behavior is inconsistent between different operating system versions

**Comment by junrushao** [comment]
This should work now if you upgrade to the latest iOS :-)
