### ISSUE TITLE
KeyError: 'vocab_size' error occurs when compiling ChatGLM2-6B

### ISSUE THREAD

**Issue by wangxu569** [mlc-ai/mlc-llm#945]
## 🐛 Bug
Using path "dist/models/chatglm2-6b" for model "chatglm2-6b"
Target configured: cuda -keys=cuda,gpu -arch=sm_86 -max_num_threads=1024 -max_shared_memory_per_block=49152 -max_threads_per_block=1024 -registers_per_block=65536 -thread_warp_size=32
Automatically using target for weight quantization: cuda -keys=cuda,gpu -arch=sm_86 -max_num_threads=1024 -max_shared_memory_per_block=49152 -max_threads_per_block=1024 -registers_per_block=65536 -thread_warp_size=32
Start computing and quantizing weights... This may take a while.
Finish computing and quantizing weights.
Total param size: 3.2713050842285156 GB
Start storing to cache dist/chatglm2-6b-q4f16_1/params
[0313/0313] saving param_312
All finished, 88 total shards committed, record saved to dist/chatglm2-6b-q4f16_1/params/ndarray-cache.json
Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/root/miniconda3/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/test/mlc-llm/mlc_llm/build.py", line 13, in <module>
    main()
  File "/home/test/mlc-llm/mlc_llm/build.py", line 10, in main
    core.build_model_from_args(parsed_args)
  File "/home/test/mlc-llm/mlc_llm/core.py", line 628, in build_model_from_args
    vocab_size=config["vocab_size"],
KeyError: 'vocab_size'

## To Reproduce

1.git clone https://huggingface.co/THUDM/chatglm2-6b
2.python3 -m mlc_llm.build --model chatglm2-6b --target cuda --quantization q4f16_1

## Environment

 - Platform (CUDA):
 - Operating system (Ubuntu):
 - Device (RTX 3080ti)
 - How you installed MLC-LLM (source):
 - How you installed TVM-Unity (source):
 - Python version (Python 3.10.10):
 - GPU driver version (525.116.04):
 - CUDA/cuDNN version (11.8):
 - TVM Unity Hash Tag (USE_GTEST: AUTO
SUMMARIZE: OFF
USE_IOS_RPC: OFF
USE_MSC: OFF
USE_ETHOSU: OFF
CUDA_VERSION: 11.8
USE_LIBBACKTRACE: AUTO
DLPACK_PATH: 3rdparty/dlpack/include
USE_TENSORRT_CODEGEN: OFF
USE_THRUST: OFF
USE_TARGET_ONNX: OFF
USE_AOT_EXECUTOR: ON
BUILD_DUMMY_LIBTVM: OFF
USE_CUDNN: OFF
USE_TENSORRT_RUNTIME: OFF
USE_ARM_COMPUTE_LIB_GRAPH_EXECUTOR: OFF
USE_CCACHE: AUTO
USE_ARM_COMPUTE_LIB: OFF
USE_CPP_RTVM: OFF
USE_OPENCL_GTEST: /path/to/opencl/gtest
USE_MKL: OFF
USE_PT_TVMDSOOP: OFF
MLIR_VERSION: NOT-FOUND
USE_CLML: OFF
USE_STACKVM_RUNTIME: OFF
USE_GRAPH_EXECUTOR_CUDA_GRAPH: OFF
ROCM_PATH: /opt/rocm
USE_DNNL: OFF
USE_VITIS_AI: OFF
USE_MLIR: OFF
USE_RCCL: OFF
USE_LLVM: llvm-config --ignore-libllvm --link-static
USE_VERILATOR: OFF
USE_TF_TVMDSOOP: OFF
USE_THREADS: ON
USE_MSVC_MT: OFF
BACKTRACE_ON_SEGFAULT: OFF
USE_GRAPH_EXECUTOR: ON
USE_NCCL: OFF
USE_ROCBLAS: OFF
GIT_COMMIT_HASH: 50a4dce98841ecb825143a79019142dcd1fe9611
USE_VULKAN: OFF
USE_RUST_EXT: OFF
USE_CUTLASS: OFF
USE_CPP_RPC: OFF
USE_HEXAGON: OFF
USE_CUSTOM_LOGGING: OFF
USE_UMA: OFF
USE_FALLBACK_STL_MAP: OFF
USE_SORT: ON
USE_RTTI: ON
GIT_COMMIT_TIME: 2023-09-17 12:11:15 -0700
USE_HEXAGON_SDK: /path/to/sdk
USE_BLAS: none
USE_ETHOSN: OFF
USE_LIBTORCH: OFF
USE_RANDOM: ON
USE_CUDA: ON
USE_COREML: OFF
USE_AMX: OFF
BUILD_STATIC_RUNTIME: OFF
USE_CMSISNN: OFF
USE_KHRONOS_SPIRV: OFF
USE_CLML_GRAPH_EXECUTOR: OFF
USE_TFLITE: OFF
USE_HEXAGON_GTEST: /path/to/hexagon/gtest
PICOJSON_PATH: 3rdparty/picojson
USE_OPENCL_ENABLE_HOST_PTR: OFF
INSTALL_DEV: OFF
USE_PROFILER: ON
USE_NNPACK: OFF
LLVM_VERSION: 16.0.6
USE_OPENCL: OFF
COMPILER_RT_PATH: 3rdparty/compiler-rt
RANG_PATH: 3rdparty/rang/include
USE_SPIRV_KHR_INTEGER_DOT_PRODUCT: OFF
USE_OPENMP: none
USE_BNNS: OFF
USE_CUBLAS: OFF
USE_METAL: OFF
USE_MICRO_STANDALONE_RUNTIME: OFF
USE_HEXAGON_EXTERNAL_LIBS: OFF
USE_ALTERNATIVE_LINKER: AUTO
USE_BYODT_POSIT: OFF
USE_HEXAGON_RPC: OFF
USE_MICRO: OFF
DMLC_PATH: 3rdparty/dmlc-core/include
INDEX_DEFAULT_I64: ON
USE_RELAY_DEBUG: OFF
USE_RPC: ON
USE_TENSORFLOW_PATH: none
TVM_CLML_VERSION: 
USE_MIOPEN: OFF
USE_ROCM: OFF
USE_PAPI: OFF
USE_CURAND: OFF
TVM_CXX_COMPILER_PATH: /usr/bin/c++
HIDE_PRIVATE_SYMBOLS: ON):
 - Any other relevant information:

**Comment by MasterJH5574** [comment]
Thanks @wangxu569 for reporting. This is because the config.json of the ChatGLM HuggingFace repo does not contain `vocab_size` and uses `padded_vocab_size` instead. We will follow up and fix it soon.

On the other hand, to get this around for now, you can update this line to
```diff
- vocab_size=config["vocab_size"]
+ vocab_size=config["padded_vocab_size"]
```

https://github.com/mlc-ai/mlc-llm/blob/c6348cfbdd84a3eca55ff4eb3c5b4cef040df3af/mlc_llm/core.py#L633

**Comment by wangxu569** [comment]
> Thanks @wangxu569 for reporting. This is because the config.json of the ChatGLM HuggingFace repo does not contain `vocab_size` and uses `padded_vocab_size` instead. We will follow up and fix it soon.
> 
> On the other hand, to get this around for now, you can update this line to
> 
> ```diff
> - vocab_size=config["vocab_size"]
> + vocab_size=config["padded_vocab_size"]
> ```
> 
> https://github.com/mlc-ai/mlc-llm/blob/c6348cfbdd84a3eca55ff4eb3c5b4cef040df3af/mlc_llm/core.py#L633

Okay，thanks! it can be compiled.
