### ISSUE TITLE
[Bug] Under windows, there is a problem about "lib".

### ISSUE THREAD

**Issue by lm1978lm** [mlc-ai/mlc-llm#947]
When I run this code (mlc-chat-venv) E:\>mlc_chat_cli --model E:\prebuilt\mlc-chat-Llama-2-7b-chat-hf-q4f16_1, 

but I got this message:

(mlc-chat-venv) E:\>mlc_chat_cli --model E:\prebuilt\mlc-chat-Llama-2-7b-chat-hf-q4f16_1
Use MLC config: "E:\\prebuilt\\mlc-chat-Llama-2-7b-chat-hf-q4f16_1\\mlc-chat-config.json"
Use model weights: "E:\\prebuilt\\mlc-chat-Llama-2-7b-chat-hf-q4f16_1\\ndarray-cache.json"
[12:20:00] C:\Miniconda\envs\mlc-llm-build\conda-bld\mlc-chat-cli-nightly-package_1695121718642\work\cpp\cli_main.cc:378: Cannot find the model library that corresponds to `Llama-2-7b-chat-hf-q4f16_1`.
We searched over the following possible paths:
- Llama-2-7b-chat-hf-q4f16_1
- dist/prebuilt/lib
- dist/E:\prebuilt\mlc-chat-Llama-2-7b-chat-hf-q4f16_1
- dist/prebuilt/Llama-2-7b-chat-hf-q4f16_1
Stack trace not available when DMLC_LOG_STACK_TRACE is disabled at compile time.

I don't no how to deal with it.

**Comment by junrushao** [comment]
Did you download this file from our repo: https://github.com/mlc-ai/binary-mlc-llm-libs?

**Comment by lm1978lm** [comment]
Yes, I did. There is my code git clone https://github.com/mlc-ai/binary-mlc-llm-libs.git e:\prebuilt\lib. But I don't know where is the problem. The old version has a --artifact-path. But now this argument has been moved. How can I do let the model where is the lib?

**Comment by Sing-Li** [comment]
> Yes, I did. There is my code git clone https://github.com/mlc-ai/binary-mlc-llm-libs.git e:\prebuilt\lib. But I don't know where is the problem. The old version has a --artifact-path. But now this argument has been moved. How can I do let the model where is the lib?

you should have a `dist\prebuilt\lib`  directory tree,  clone that into the `lib` directory;  then run from top level  (where you see only `dist` as subdirectory)

**Comment by CharlieFRuan** [comment]
Hi @lm1978lm, you could run our [tutorial notebook](https://github.com/mlc-ai/notebooks/blob/main/mlc-llm/tutorial_chat_module_getting_started.ipynb) on Colab and see how the directory is structured. 

Closing the issue for now due to inactivity. But definitely feel free to reopen if there are further questions!
