### ISSUE TITLE
[Question] Delay between command and first token increases based on input length.

### ISSUE THREAD

**Issue by ereish64** [mlc-ai/mlc-llm#952]
## ❓ General Questions

Is it normal for the delay before the first token of output to increase significantly based on the amount of input used in the prompt? I've noticed a pretty linear increase in the time it takes to generate the first token and the amount of input (at least using Llama 2). Does anyone have any insights on how I could speed up this process?

Using an intel Arc A750 and Intel i9 10900k, let me know if example code would help.

**Comment by junrushao** [comment]
What’s the tok/sec in the prefilling phase?

**Comment by junrushao** [comment]
You may print out some stats with the API below: 

https://github.com/mlc-ai/mlc-llm/blob/main/examples/python/sample_mlc_chat.py#L19
