### ISSUE TITLE
[Bug]  REST API  rest.py broken on latest nightly

### ISSUE THREAD

**Issue by Sing-Li** [mlc-ai/mlc-llm#957]
## 🐛 Bug

REST API mlc_chat.rest  crashes when running on windows since recent nightly update.  
with  `AttributeError: function 'TVMGetLastPythonError' not found`

## To Reproduce

1.  install the latest nightly
1.  run `python -m mlc_chat.rest --model xxxx`

See stack trace at end 

## Expected behavior

working as usual

## Environment

 - Platform (e.g. WebGPU/Vulkan/IOS/Android/CUDA):  vulkan
 - Operating system (e.g. Ubuntu/Windows/MacOS/...):  windows 11
 - Device (e.g. iPhone 12 Pro, PC+RTX 3090, ...)    
 - How you installed MLC-LLM (`conda`, source):  mini conda3
 - How you installed TVM-Unity (`pip`, source):
 - Python version (e.g. 3.10):  
 - GPU driver version (if applicable):
 - CUDA/cuDNN version (if applicable):
 - TVM Unity Hash Tag (`python -c "import tvm; print('\n'.join(f'{k}: {v}' for k, v in tvm.support.libinfo().items()))"`, applicable if you compile models):
 - Any other relevant information:

## Additional context
```
INFO:     Started server process [30888]
INFO:     Waiting for application startup.
ERROR:    Traceback (most recent call last):
  File "C:\Users\allmy\miniconda3\lib\site-packages\starlette\routing.py", line 677, in lifespan
    async with self.lifespan_context(app) as maybe_state:
  File "C:\Users\allmy\miniconda3\lib\contextlib.py", line 199, in __aenter__
    return await anext(self.gen)
  File "C:\Users\allmy\miniconda3\lib\site-packages\mlc_chat\rest.py", line 119, in lifespan
    chat_mod = ChatModule(
  File "C:\Users\allmy\miniconda3\lib\site-packages\mlc_chat\chat_module.py", line 603, in __init__
    self._reload(self.lib_path, self.model_path, user_chat_config_json_str)
  File "C:\Users\allmy\miniconda3\lib\site-packages\mlc_chat\chat_module.py", line 784, in _reload
    self._reload_func(lib, model_path, app_config_json)
  File "C:\Users\allmy\miniconda3\lib\site-packages\tvm\_ffi\_ctypes\packed_func.py", line 239, in __call__
    raise_last_ffi_error()
  File "C:\Users\allmy\miniconda3\lib\site-packages\tvm\_ffi\base.py", line 415, in raise_last_ffi_error
    _LIB.TVMGetLastPythonError.restype = ctypes.c_void_p
  File "C:\Users\allmy\miniconda3\lib\ctypes\__init__.py", line 387, in __getattr__
    func = self.__getitem__(name)
  File "C:\Users\allmy\miniconda3\lib\ctypes\__init__.py", line 392, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: function 'TVMGetLastPythonError' not found

ERROR:    Application startup failed. Exiting.
```

**Comment by David-Sharma** [comment]
I am experiencing the same.

**Comment by junrushao** [comment]
Interesting! Noticing that it seems to be related to “reload”, which changes its signature lately causing a few issues in our usecases. Shall we double check if it’s the source of the problem in this particular case as well? @jinhongyii @MasterJH5574 

```
  File "C:\Users\allmy\miniconda3\lib\site-packages\mlc_chat\rest.py", line 119, in lifespan
    chat_mod = ChatModule(
  File "C:\Users\allmy\miniconda3\lib\site-packages\mlc_chat\chat_module.py", line 603, in __init__
    self._reload(self.lib_path, self.model_path, user_chat_config_json_str)
  File "C:\Users\allmy\miniconda3\lib\site-packages\mlc_chat\chat_module.py", line 784, in _reload
    self._reload_func(lib, model_path, app_config_json)

```

**Comment by Sing-Li** [comment]
Thanks @junrushao for looking into this.

We've determined that it is due to the two extra  `mlc-chat-config.json`  parameters that were added **exactly two days ago** to all the quantized weights on huggingface.      Since we cache them on our local disks,  the configs were not updated.

```
    "max_window_size": xxxx,
    "vocab_size": xxxxxxx
```

Once we added those two attributes to each config, no more problem. 

I'll close the issue as resolved 🙏

**Comment by Sing-Li** [comment]
Just dropping an opinion from an MLCLLM user's perspective,  @tqchen 

In our mental models -  weights on huggingface are static assets and changes on them should be version controlled via name changes to  `v2` etc, or via git / release mechanisms etc.    (since they are so large many of us will be caching them on local disks as well)

What happened in this case may happen to many more working apps built on top of MLC AI in the near future.

The default configuration file, being more dynamic in nature, conceptually fits better with the decoding library binaries.  But unfortunately/fortunately  we're now  going with single decoder for "families" of models.

So I only have the problem but no suggested solutions.   Sharing fwiw

**Comment by hhr0315** [comment]
I am experiencing the same circumstances.
I just started learning TVM,now the code is 
```
a = np.arange(16).reshape(4, 4)
b = np.arange(16, 0, -1).reshape(4, 4)

#numpy version
c_np = a + b
print(c_np)

#low-level numpy version
def lnumpy_add(a: np.ndarray, b: np.ndarray, c: np.ndarray):
    for i in range(4):
        for j in range(4):
            c[i, j] = a[i, j] + b[i, j]

# c_lnumpy = np.empty((4, 4), dtype = np.int64)
# lnumpy_add(a, b, c_lnumpy)
# print(c_lnumpy)

#TensorIR version
@tvm.script.ir_module
class MyAdd:
    @T.prim_func
    def add(A: T.Buffer((4, 4), "int64"),
            B: T.Buffer((4, 4), "int64"),
            C: T.Buffer((4, 4), "int64")):
        T.func_attr({"global_symbol": "add"})
        for i, j in T.grid(4, 4):
            with T.block("C"):
                vi = T.axis.spatial(4, i)
                vj = T.axis.spatial(4, j)
                C[vi, vj] = A[vi, vj] + B[vi, vj]

rt_lib = tvm.build(MyAdd, target = "llvm")
a_tvm = tvm.nd.array(a)
b_tvm = tvm.nd.array(b)
c_tvm = tvm.nd.array(np.empty((4, 4), dtype = np.int64))
rt_lib["add"](a_tvm, b_tvm, c_tvm)
np.testing.assert_allclose(c_tvm.numpy(), c_np, rtol=1e-5)
```
the error message is 
**[17:07:31] D:\a\package\package\tvm\src\runtime\library_module.cc:78: Assert fail: T.tvm_struct_get(A_handle, 0, 5, "uint8") == T.uint8(0) and T.tvm_struct_get(A_handle, 0, 6, "uint8") == T.uint8(64) and T.tvm_struct_get(A_handle, 0, 7, "uint16") == T.uint16(1), add.A_handle.dtype is expected to be int64
Stack trace not available when DMLC_LOG_STACK_TRACE is disabled at compile time.

Traceback (most recent call last):
  File "D:\python\learn_tvm\learn_tvm.py", line 44, in <module>
    rt_lib["add"](a_tvm, b_tvm, c_tvm)
  File "D:\Anaconda1\envs\tvm_pt\lib\site-packages\tvm\_ffi\_ctypes\packed_func.py", line 239, in __call__
    raise_last_ffi_error()
  File "D:\Anaconda1\envs\tvm_pt\lib\site-packages\tvm\_ffi\base.py", line 415, in raise_last_ffi_error
    _LIB.TVMGetLastPythonError.restype = ctypes.c_void_p
  File "D:\Anaconda1\envs\tvm_pt\lib\ctypes\__init__.py", line 386, in __getattr__
    func = self.__getitem__(name)
  File "D:\Anaconda1\envs\tvm_pt\lib\ctypes\__init__.py", line 391, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: function 'TVMGetLastPythonError' not found**

**Comment by Radnyx** [comment]
@hhr0315 I got the same thing from the MLC course exercises. In this one I replaced `int64` with `float32` and it started working. This works just as well since the exercises have us use `assert_allclose` anyway.
