### ISSUE TITLE
[Question] 

### ISSUE THREAD

**Issue by David-Sharma** [mlc-ai/mlc-llm#958]
How to roll back nightly wheel?

"Is it possible to locally load previous versions of the nightly builds? I have noticed that we have a few archived tar.bz2 files in the 'pkgs' folder on Windows 11. This could be useful if we encounter any issues with the current release."

**Comment by junrushao** [comment]
This issue seems empty...

**Comment by David-Sharma** [comment]
Can you please recheck at your convenience? Thanks
