### ISSUE TITLE
[Question] iOS Performance Benchmark

### ISSUE THREAD

**Issue by NaNa7Miiii** [mlc-ai/mlc-llm#959]
## ❓ General Questions

Hi, I have read the tutorials for having chats in Colab, including a benchmark:
<img width="713" alt="Screenshot 2023-09-21 at 3 52 33 PM" src="https://github.com/mlc-ai/mlc-llm/assets/97627889/32ddad39-bf05-411c-b820-69daba58278d">

I wonder what are the procedures for benchmarking the performance on iOS Devices instead of on Colab. Thank you so much for your help!

**Comment by tqchen** [comment]
In this case, we show up the stats on the app.
