### ISSUE TITLE
App crashes when trying to use new models

### ISSUE THREAD

**Issue by SalomonKisters** [mlc-ai/mlc-llm#972]
- Link to an existing implementation: mlc-ai/mlc-chat-rwkv-raven-3b-q8f16_0
- Is this model architecture supported by MLC-LLM? Yes
## Context
I tried to run the MLC chat app on my new ipad pro and iphone 14 pro max. Both worked fine for the preinstalled models. However, when I add a model by link and download it in the app, I can not open the chat interface. whenever I click on the model, the app crashes.
I really like the idea of being able to run LLMs locally and privately and I hope you will be able to resolve this.
Thanks for your help!

**Comment by Sing-Li** [comment]
@SalomonKisters it does already, but you have to stay within the same "family tree" of models when loading new variants.  And the current app binary only supports one or two such families.  If you recompile and install the app yourself, you can get any of the supported models running (subjected to the capabilities of your hardware).

**Comment by SalomonKisters** [comment]
@Sing-Li Thank you for the quick response, so where can I find which models work for iOS and are of the same family tree?

**Comment by David-Sharma** [comment]
Please find the link here https://mlc.ai/mlc-llm/docs/prebuilt_models.html#prebuilt-models-for-ios
