### ISSUE TITLE
[Bug] There are errors when compile model with `q3f16_1` quantization.

### ISSUE THREAD

**Issue by ChenMnZ** [mlc-ai/mlc-llm#975]
## 🐛 Bug

comment:
```
python3 -m mlc_llm.build --target cuda --quantization q3f16_1 --model ./dist/models/llama-13b
```

error:
![image](https://github.com/mlc-ai/mlc-llm/assets/57585796/79acfed7-cc94-4c78-807d-20bb1121a243)

**Comment by ChenMnZ** [comment]
No, I still have this problem.

**Comment by junrushao** [comment]
I believe this issue has been fixed by @vinx13. Please upgrade to latest TVM Unity nightly pip package. Feel free to create a new issue if it persists!
