### ISSUE TITLE
[Question] Experiencing degraded accuracy when running quantized fine-tuned Llama V2 13 model with long prompt

### ISSUE THREAD

**Issue by changun** [mlc-ai/mlc-llm#978]
First of all, I'd like to extend my deepest appreciation to the entire MLC team. The MLC is unrivalled in terms of its speed for the Llamma V2 13B model, at least in terms of the specific tasks we've put it through, especially long prompt summarization (2000+ tokens).

However, I'm encountering a somewhat peculiar issue that I wanted to bring to the community's attention. I find it a bit challenging to report this issue with precision, so I'll share two specific incidents to elaborate further:

1. **Loss of Instruction Following Capabilities with int4 Model:** Quantizing a fine-tuned V2 13B model to any int4 model running on MLC seems to significantly compromise its capability to follow instructions. For instance, our prompts require the model to format the output response as follows:
```
## Step 1
...
## Step 2
...
## Step 3
...
```
The model, post-fine-tuning, can follow these instructions quite well when run on most other slower frameworks (for instance, Vanilla Transformer with BitsAndBytes int4, llama.cpp int4, and so forth). Surprisingly though, when using an int4 MLC model (with any quantization schemes), there's over a 50% probability the model won't be able to adhere to the instructions and might end up jumbling the steps together. The led us to resort to int8 quantization, which we had similar but less severe issue described as follow.

2. **Repetition in Output with int8 Model:** When quantizing a V2 13B model to an int8 model using MLC (which remains impressively fast during inference), the model fares better in following the Steps format, but has a 1-2% chance of repeating itself in Step 2 indefinitely until it runs out of tokens. Here's an example of a problematic output:
```
## Step 1
{answer for step 1}
## Step 2
- answer 1
- answer 2
- answer 3
- answer 3
- answer 3
- answer 3
... {repeats indefinitely, and never get to Step 3}
```
I must underscore, though, that this occurs only in 1-2% of our sample prompts, which is definitely good news. However, these issues are absent when running the model with other, albeit slower, frameworks. 

And I want to emphasize that it might only occur to our specific use case: 
* lora-tuned
* long-prompt summarization tasks with 2000+ tokens
* int4/int8 quantized (we didn't try the unquantized version yet). 

But just to share these anecdotes with the community to see if anyone has similar issues and have a solution.

Thanks!

**Comment by masahi** [comment]
Can you try adding an option `--no_cutlass_norm` to your build command? Recently I learned that some model may hit accuracy problems using our default compilation options.

**Comment by junrushao** [comment]
Also if there's specifically repetition patterns, you may want to tweak `repetition_penalty` in `mlc-chat-config.json`, as an example:

```
>>> cat ./dist/Llama-2-7b-chat-hf-q4f16_1/params/mlc-chat-config.json
{
    "model_lib": "Llama-2-7b-chat-hf-q4f16_1",
    "local_id": "Llama-2-7b-chat-hf-q4f16_1",
    "conv_template": "llama-2",
    "temperature": 0.7,
    "repetition_penalty": 1.0, <<<<<<<<<<<<<<<<<<<< this 
    "top_p": 0.95,
    "mean_gen_len": 128,
    "max_gen_len": 512,
    "max_window_size": 768,
    "num_shards": 1,
    "shift_fill_factor": 0.3,
    "tokenizer_files": [
        "added_tokens.json",
        "tokenizer.json",
        "tokenizer.model"
    ],
    "model_category": "llama",
    "model_name": "Llama-2-7b-chat-hf",
    "vocab_size": 32000
}
```

**Comment by MasterJH5574** [comment]
Closing for now due to staleness. Feel free to open a new one if needed.
