### ISSUE TITLE
[Question] If you have more than one GPU, say an iGPU and a dGPU, can you select which one?

### ISSUE THREAD

**Issue by Drael64** [mlc-ai/mlc-llm#983]
## ❓ General Questions

This question applies to both inference and compiling models. I tried looking this up, but couldn't find any answers. It's clear compiling in particular uses a lot of RAM, so it would be helpful if you could run this more slowly on iGPU.

**Comment by Sing-Li** [comment]
Great question!   The answer depends on actual mix of hardware, the operating system, as well as the (versions of the) acceleration library used/available/installed on the system.    

If any team member working on (or with) multi-GPU can share some tips  --- that'd be great!   🙏

**Comment by Drael64** [comment]
I can provide some more details if it's helpful. It would be iGPU = 680M, dGPU=6600M, both AMD, using the vulkan driver on windows 11.

**Comment by x330930520** [comment]
It would be of great help if I can choose iGPU over dGPU, since iGPU uses system RAM which I can easily upgrade for much less.

**Comment by Drael64** [comment]
> It would be of great help if I can choose iGPU over dGPU, since iGPU uses system RAM which I can easily upgrade for much less.

Well exactly. Especially for something like compiling which is a once off, it doesn't matter so much if it's a lot slower esp given barely any models are compiled to MLC on HF. System RAM is a ton cheaper, and is usually much more without spending a dime to start with.   

It would also allow you to run larger models even if much slower, if you need to (it's not going to compete on speed but it's flexibility basically)

**Comment by Sing-Li** [comment]
non-laptop mixed vendors setup on windows is especially difficult to figure out -- for example,  AMD APU with Nvidia P40 (ex data center card).   Seems the Windows drivers are hard-wired to work on games, but trying to fish out the vulkan / cuda support on the P40 to run MLC-AI is almost impossible   😞

**Comment by x330930520** [comment]
> non-laptop mixed vendors setup on windows is especially difficult to figure out -- for example, AMD APU with Nvidia P40 (ex data center card). Seems the Windows drivers are hard-wired to work on A1 games, but trying to fish out the vulkan / cuda support on the P40 to run MLC-AI is almost impossible 😞

How about laptop with Intel iGPU and Nvidia dGPU?
