### ISSUE TITLE
Can I use new dataset to train MLC LLM?

### ISSUE THREAD

**Issue by liyizhe3975** [mlc-ai/mlc-llm#99]

**Comment by liyizhe3975** [comment]
Hi there.I love to chat with MLC LLM.but I found it know not enough about scientific fiction novel.
So can I use some scientific fiction novels,especially Chinese science fiction novels ,to train the LLM?

**Comment by liyizhe3975** [comment]
Maybe I have a misunderstanding that the MLC LLM is based on other LLM such as ChatGPT,LLaMa. TianQi and other people's work is use TVM technology to make LLM can be deployed and run on iPhones and laptops.
So if I want to train the LLM with new dateset,I have to train the GPT model or LLaMa model. Am I right?

**Comment by shiqimei** [comment]
This is out of scope for this repo, since mlc-llm is a "deployment technique" to help users deploy models to devices natively in low cost.

As for the techniques for fine-tuning llm using your own dataset, there're approaches like (Freeze、Lora、P-tuning etc.) hope this [repo](https://github.com/liucongg/ChatGLM-Finetuning) helps.

**Comment by liyizhe3975** [comment]
Thanks a lot for your information.😁😁
I didn't understand the repo introduction well since my poor English.I need to learn hard at Github in English.



---- Replied Message ----
| From | Shiqi ***@***.***> |
| Date | 05/08/2023 22:11 |
| To | ***@***.***> |
| Cc | ***@***.***>、State ***@***.***> |
| Subject | Re: [mlc-ai/mlc-llm] Can I use new dataset to train MLC LLM? (Issue #99) |

This is out of scope for this repo, since mlc-llm is a "deployment technique" to help users deploy models to devices natively in low cost.

As for the techniques for fine-tuning llm using your own dataset, there're approaches like (Freeze、Lora、P-tuning etc.) hope this repo helps.
