### ISSUE TITLE
[Model Request] Mistral-7b

### ISSUE THREAD

**Issue by scottorly** [mlc-ai/mlc-llm#991]
- Link to an existing implementation (e.g. Hugging Face/Github): https://huggingface.co/mistralai/Mistral-7B-v0.1
- Is this model architecture supported by MLC-LLM? (the list of [supported models](https://llm.mlc.ai/docs/prebuilt_models.html))  No

**Comment by masahi** [comment]
https://github.com/mlc-ai/mlc-llm/pull/986

**Comment by masahi** [comment]
It turned out #986 is not complete for Mistral 7b support, see https://github.com/mlc-ai/mlc-llm/pull/986#issuecomment-1739084638

@scottorly I suggest reopening this issue to make it more visible.

**Comment by coder543** [comment]
My primary interest in this is running it on my phone. Testing it on my laptop with ollama, it seemed better than the vanilla llama2-chat 7B model.

Will MLC be uploading the built model to huggingface? I’ve never successfully gotten the app to download a model that wasn’t provided by MLC

**Comment by digisomni** [comment]
If Mistral is now supported, we should probably update the README to reflect that.

**Comment by tusing** [comment]
What is the URL for the MLC version of Mistral-7b?

**Comment by knd775** [comment]
Can this please be re-opened? I'm worried it may prevent this from actually being implemented.

**Comment by junrushao** [comment]
This is already implemented by @CharlieFRuan @davidpissarra et al a few weeks ago.

**Comment by coder543** [comment]
@junrushao what is the link to download the model to the MLCChat app on my phone?

**Comment by CharlieFRuan** [comment]
@coder543 Mistral's support on iOS is a current WIP, please stay tuned!

**Comment by junrushao** [comment]
so to summarize, for Mistral, we already got:
- Desktop (CUDA, ROCm, Metal)
- Web (WebGPU & WASM)

but the following(s) are not ready:
- iOS
- Android

Is that accurate? @CharlieFRuan

**Comment by CharlieFRuan** [comment]
@junrushao Yep that is correct! I will upload the prebuilts and update the doc sometime this week.

**Comment by philippgille** [comment]
> @junrushao Yep that is correct! I will upload the prebuilts and update the doc sometime this week.

Is there any update on being able to run Mistral on Android?

**Comment by CharlieFRuan** [comment]
@philippgille I believe Mistral is supported in Android now; here is the prebuilt model library: https://github.com/mlc-ai/binary-mlc-llm-libs/blob/main/Mistral-7B-Instruct-v0.2/Mistral-7B-Instruct-v0.2-q4f16_1-android.tar.
